### ISSUE TITLE
Deep links weird scenarios

### ISSUE THREAD

**Issue by anthowm** [react-navigation/react-navigation#8672] opened 2020-08-04 06:34 UTC
**Current Behavior**
Deep links not works correctly
- What code are you running and what is happening?
Navigation Container
```
const linking = {
        prefixes: ['https://latineo.com', 'latineo://'],
        config: {
            Home: {
                path: 'homestack',
                initialRouteName: 'Explore',
                screens: {
                    Explore: 'explore',
                    Posts: 'posts',
                    Favorites: 'favorites',
                    Settings: 'settings',
                },
            },
            ExploreOptions: {
                path: 'explorestack',
                initialRouteName: 'Restaurants',
                screens: {
                    Restaurants: 'rts',
                    ShowRestaurants: 'restaurants',
                    ShowRestaurant: 'restaurant/:id',
                },
            }
        },
    };

<NavigationContainer
            theme={navigatorTheme}
            ref={(nav: any) => {
                navigator = nav;
                NavigationService.setNavigator(navigator);
            }}

            linking={linking}
            fallback={<LoadingIndicator
                size='giant'
            ></LoadingIndicator>}
            onStateChange={(nav) => {
                console.log("AppNavigator -> nav", nav)
            }}
        >
            {isAuth && <HomeNavigator />}
            {!isAuth && didTryAutoLogin && didOnboard && didPermission && <AuthNavigator />}
            {!isAuth && didTryAutoLogin && !didOnboard && <OnboardScreen />}
            {!isAuth && didTryAutoLogin && didOnboard && !didPermission && <LocationPermissionScreen />}
            {!isAuth && !didTryAutoLogin && <IsAuthScreen />}
        </NavigationContainer>
```

Navigators
```
const Stack = createStackNavigator<HomeParamList>();
export const HomeNavigator = (): React.ReactElement => {
    return (
        <Stack.Navigator
            initialRouteName={'Home'}
            headerMode='none'
        >
            <Stack.Screen name='Home' component={HomeTabsNavigator} />
            <Stack.Screen name='ExploreOptions' component={LayoutsNavigator} />
            <Stack.Screen name='CreateOptions' component={PostNavigator} />
            <Stack.Screen name='FavoritesOptions' component={FavoritesNavigator} />
            <Stack.Screen name='SettingsOptions' component={SettingsNavigator} />
        </Stack.Navigator>
    );
};

export const HomeTabsNavigator = (): React.ReactElement => {
    return (
        <BottomTab.Navigator
            screenOptions={TabBarVisibleOnRootScreenOptions}
            initialRouteName={'Explore'}
            tabBar={props => <HomeBottom {...props} />}>
            <BottomTab.Screen name='Explore' component={LayoutsScreen} />
            <BottomTab.Screen name='Post' component={PostsScreen} />
            <BottomTab.Screen name='Favorites' component={LayoutsScreen} />
            <BottomTab.Screen name='Settings' component={SettingsContainer} />
        </BottomTab.Navigator>
    );
};
```

Scenario 1

When I try (App in background) with xcrun simctl openurl booted latineo://homestack/explore or latineo://homestack/settings, explorestack/restaurant/:id, etc it works fine, but when the app is closed(killed) it always open homestack/explore.

Scenario 2 

When I try with explorestack/restaurant/:id it works but when I press a button that navigation.back() it back to a blank screen (If I use gestures from this white screen I can back to my home screen).
We can encounter the full problem here
https://stackoverflow.com/questions/63203159/deep-link-with-react-navigation-v5

**Expected Behavior**

- What do you expect should be happening?
Deep links works correctly.
- Include a screenshot or video if it makes sense.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios 9 and android 9
| @react-navigation/native       | 5.5.1
| react-native                   | 0.61.2
| expo                           | -
| node                           | v10.15.3
| npm or yarn                    | npm 6.4.1

**Comment by rdewolff** [comment] 2020-11-14 06:09
I can reproduce the scenario 1 issue.

**Comment by satya164** [comment] 2020-11-28 01:56
Closing since you didn't provide a repro to be able to debug the issue. Please open a new issue if you have a minimal repro which I could take a look at.

**Closed by satya164** 2020-11-28 01:56 UTC
Labels: bug, needs repro

**Comment by plgrazon** [comment] 2025-05-19 17:43
@anthowm Hi there, if you don't mind, would you be able to share how you solved this issue?
