### ISSUE TITLE
[Typescript] 🆘 Rethink the way of using typings in React Navigation

### ISSUE THREAD

**Issue by ScreamZ** [react-navigation/react-navigation#6295] opened 2019-09-13 14:41 UTC
Hello @brentvatne, @ericvicenti, @satya164 and others from community.

**I'm a proud user of EXPO and react-navigation, those are great tools…** but today it's getting complicated.

> **🆘 I'm sending out an SOS 🎶**

I'm posting this to get your attention because this is getting really embarrassing… I'm working on professionals RN projects everyday and everybody in the team is having hard time using types (everybody do whatever they can and there is no consistency, because there are too many ways to do typings).

**The thing is that Typescript types in RN are complicated**  : types keep changing every-time and it's really difficult to apply patches on RN navigation with that.

# A bit of context

As I reported here #6195 there is not real documentation on how to deal with types for now. 

💡 **I would like to help having this.** 

That's why I made the other thread but I'm having hard time keeping it alive and updated.

I also opened a pull request #6294 because I was stuck with one use case because typings are too restrictive on some parts, maybe I was not using the good type… ? No answers…

_(@satya164 I agree with the fact that any is too opened. I'm a pro-typescript/types guy, but if we do so, this has to be clear and easy)_

That's why I suggest the following:

# Suggesting solutions 

What I'm presenting here are possible solutions, I you have some others, feel free to post an answers below : 

Just keep in mind that if you are not a core contributor or active user of react-navigation it's already complicated to understand how it works (nesting navigator, custom navigators, …) and if you lose auto-completion, it's even harder!

## I - Having scoped types

Currently each types including the internal one (those who are used to factorize typings) are exported (more than 50).

**The result is we have tons of exported types that are never used**, they are just distracting to those who are useful and it's hard to see which one serve which purpose.

**🚀 Example implementation**
This could be avoided by using **namespaces** (which is a good practice that avoid types conflicts in case someone name one interface the same name) so that you scope type that are internals and type that are externals, I have an example here : https://github.com/kkemple/graphql-auth/blob/master/index.d.ts

This example is based from the documentation here for that https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

## II - Having a part of the doc which present typescript usage with many components types

Just as I do in #6195, this could be avoided if we export properly named interface like `ReactNavigationComponent<props, state, navProps, screenProps>` `RNFC` (React Navigation Function Component` ?

This could be nice and easy, don't you think ? There is not much case to handle.

---- 
For now, I don't know what changed but in `"react-navigation": "^4.0.0",` everything was fine… But this is changing too quickly and seems introducing breaking changes for new Alpha coming…

I'll try something different, hacking little by little my types, awaiting for you to answers me…

Thanks for taking the time to read me and taking this seriously,
I hope we can make this even greater than this is currently, I'm pretty sure this would help a lot of people who starts.

**And do not forget, I would be pleased to help with that.** 

Best regards,
Andréas

PS : Sorry for my 🇺🇸 English 🏴󠁧󠁢󠁥󠁮󠁧󠁿, you know those French 🇫🇷 people with their baguettes…

**Comment by satya164** [comment] 2019-09-13 15:11
> As I reported here #6195 there is not real documentation on how to deal with types for now.

I think it's upto the community to add documentation for types. I'd happily merge a PR with a guide showing how to use React Navigation's type definitions.

The existing type definitions were monolithic, assuming that all navigators are built-in. This wasn't the case even in 3.x where we had external navigators such as material-bottom-tab-navigator, react-navigation-shared-element etc. However, the defintions didn't account for this.

With 4.x, we removed the navigators from the main package, and navigators can be installed separately. This makes it necessary to extract out the type definitions as well and make them more flexible to properly allow navigator packages.

After making changes to the type definitions, I have updated the example app which you can find in the [example/](https://github.com/react-navigation/react-navigation/tree/master/example) folder in this repo. But since there's currently no documentation, it's not possible for me to look at all existing use cases and update examples.

> I also opened a pull request #6294 because I was stuck with one use case because typings are too restrictive on some parts, maybe I was not using the good type… ? No answers…

I already answered with the solution in your PR.

> Having scoped types

I don't think we should make more changes to the definitions. It'll create more work for users to upgrade. The changes I made were necessary to support external navigator packages, but I touched very few existing types.

> Having a part of the doc which present typescript usage with many components types

We definitely need a guide demonstrating usage with TypeScript and I'll happily review a PR.

> For now, I don't know what changed but in "react-navigation": "^4.0.0", everything was fine… But this is changing too quickly and seems introducing breaking changes for new Alpha coming…

We have removed the navigators from the main package as mentioned in the release notes. The changes in types should've been a part of the 4.x release, but I had very little time to publish 4.x and as a result those I had to do those changes in subsequent releases.

I think the current state of the definitions is pretty ok, and I don't think there are going to be further changes to the typescript definitions.

**Comment by brentvatne** [comment] 2019-09-14 02:21
Adoption for TypeScript has been gradual in this project and we've never had really excellent coverage, but there definitely was a bit of a regression when pulling navigators out. Hopefully the changes @satya164 has made recently should address those.

@satya164 and @osdnk have rewritten much of React Navigation from scratch in TypeScript and with an eye towards making it work well with the type system in version 5. This will be the way forward.

I'd also be happy to help review a PR to add some documentation around TypeScript usage with React Navigation! I really appreciate you reaching out and writing this up @ScreamZ!

**Comment by jsamr** [comment] 2019-09-30 18:38
@ScreamZ Salut compatriote ! I totally agree with these statements. Only the relevant API surface should be exposed through types. That is the exact purpose of [the `api-extractor` tool](https://api-extractor.com/). I have been using it with [`@typeskill/typer`](https://github.com/typeskill/typer#----typeskilltyper) and am very satisfied up until now.

Here are the benefits I have witnessed:

- Reducing API surface;
- Enforcing a high quality documentation with [tsdoc](https://github.com/microsoft/tsdoc) standard;
- Complying easily with semantic versioning;
- Automatically generating an API reference with [`api-documenter`](https://www.npmjs.com/package/@microsoft/api-documenter).

An easy to understand usage would be not exposing the `State` type of one library component. [Here is an example](https://github.com/typeskill/typer/blob/master/src/components/Print.ts#L42). And as much as you advocated, I favor namespacing to limit the number of explicit exports, resulting in a more thin, readable API.

I would be glad with helping through such integration.

**Comment by satya164** [comment] 2019-09-30 18:49
PRs welcome to add JSDocs to the definitions and improve the [documentation](https://reactnavigation.org/docs/en/typescript.html). But we're not going to further change the type definitions and limit them as all it's going to do is require more work for the users for migration.

**Comment by satya164** [comment] 2019-10-01 09:49
I've already added documentation. I'm closing this because the issue is not actionable for us.

**Closed by satya164** 2019-10-01 09:49 UTC

**Comment by ScreamZ** [comment] 2019-10-09 16:25
Thanks :)
