### ISSUE TITLE
Deep linking and Expo integration

### ISSUE THREAD

**Issue by triplea24** [react-navigation/react-navigation#5409] opened 2018-12-20 13:53 UTC
### Current Behavior

I intend integrating `Expo` and `react-navigation`. Although I set `uriPrefix` for AppNavigator and `path` for screens, the screens do not pop when I open their links.

	import { Linking } from "expo";
	import { createStackNavigator, createAppContainer } from "react-navigation";
	
	const uriPrefix = Linking.makeUrl();
	
	const AppNavigator = createStackNavigator(
	  {
	    Home: {
	      screen: HomeScreen,
	      path: "home/"
	    },
	    Details: {
	      screen: DetailsScreen,
	      path: "detail/"
	    }
	  },
	  {
	    initialRouteName: "Home"
	  }
	);
	
	const AppContainer = createAppContainer(AppNavigator);
	
	export default class App extends React.Component {
		render() {
			return <AppContainer uriPrefix={uriPrefix} />;
		}
	}
	
The snippet for opening a url is written as below:
	
	const redirectUrl = `${Linking.makeUrl("detail")}`;
	Linking.openURL(redirectUrl);

### Expected Behavior

I assume when the `openURL` method is triggered, the app should be navigated to `Details`.

### How to reproduce

You can check out my code in [expo-react-navigation-linking](https://github.com/triplea24/expo-react-navigation-linking) repository.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.1 (expo)
| expo             | 31.0.2
| node             | 8.12.0
| yarn             | 1.12.1

**Comment by ericvicenti** [comment] 2018-12-21 00:55
Hi there! I tested your example and it seems that Expo Linking.makeUrl is behaving inconsistently.. 

The following change fixes deep linking for your app: https://github.com/ericvicenti/expo-react-navigation-linking/commit/425b47eedad7629e89fbed07a67fd654824ec1ee

```js
const uriPrefix = Linking.makeUrl("") + "/--/";
```

So lets check in with @brentvatne  about the intended behavior of that function, then maybe we can publish some example code to help people avoid this issue in the future.

**Comment by eriveltonelias** [comment] 2018-12-21 01:15
Hi @ericvicenti, 

on that function, we need to append a path to have the same behavior as you wrote, so will be something like that to solve this problem. :)
```js
const uriPrefix = Linking.makeUrl("/");
```

so, should we close this issue? seems not related to `react-navigation`.

**Comment by ericvicenti** [comment] 2018-12-21 01:18
Oh I didn't realize that `"/"` would do it, nice!

Sounds like this is a non-problem for now, but it would be nice if we had a better example so people can avoid this in the future. Would you be able to fix up our linking document to explain the usage with expo?

**Closed by ericvicenti** 2018-12-21 01:18 UTC

**Comment by eriveltonelias** [comment] 2018-12-21 01:20
yeah, for sure. I'll do that, thanks! :)

**Comment by triplea24** [comment] 2018-12-21 07:59
@ericvicenti @eriveltonelias,  Thank you all!  I am going to extend the project exploring nested navigators deep linking. If you find my code useful, feel free to use it as an example.

**Comment by triplea24** [comment] 2018-12-22 12:44
I've just used a StackNavigator inside a TabNavigator and I see strange behaviour. 

The linking is working except for `profile/detail/` when I am in `ProfileScreen`.

	const HomeStack = createStackNavigator(
	  {
	    Home: {
	      screen: HomeScreen,
	      path: "home/"
	    },
	    Details: {
	      screen: DetailsScreen,
	      path: "detail/"
	    }
	  },
	  {
	    initialRouteName: "Home"
	  }
	);
	
	const ProfileStack = createStackNavigator(
	  {
	    Profile: {
	      screen: ProfileScreen,
	      path: "main/"
	    },
	    Details: {
	      screen: DetailsScreen,
	      path: "detail/"
	    }
	  },
	  { initialRouteName: "Profile" }
	);
	
	const AppNavigator = createBottomTabNavigator(
	  {
	    App: HomeStack,
	    Profile: ProfileStack
	  },
	  {
	    initialRouteName: "Profile"
	  }
	);
