### ISSUE TITLE
How to take user confirmation before navigating to another screen

### ISSUE THREAD

**Issue by sagarrabadiya** [react-navigation/react-navigation#3999] opened 2018-04-17 09:57 UTC
how can i prevent the screen navigation, for ex. I have a form at screen a and when user have unsaved changes and tries to navigate to another screen or try to go back i want to ask for confirmation about unsaved changes will be lost, so i will have to prevent the route navigation until user confirms how can i do it?

**Comment by charlie-axsy** [comment] 2018-04-17 10:11
Well you just put the navigation call inside the callback from the confirmation prompt.  

```js
<Button onPress={() => {
   Alert.alert("Confirm", "You might lose changes", [{
      title: "OK",
      onPress: () => navigate("MY_OTHER_SCREEN")
   }])
}} />
```

**Comment by sagarrabadiya** [comment] 2018-04-17 11:01
thats correct but what about back button or android hardware back button the above will work if the navigation is on my own button i am not using headerLeft so the back button is coming from react navigation and when user press hardware back button it still will navigate

**Comment by avioli** [comment] 2018-04-18 01:42
Isn't `MyRouter.router.getStateForAction` exactly for that?

https://reactnavigation.org/docs/routers.html#blocking-navigation-actions

**Comment by sagarrabadiya** [comment] 2018-04-18 03:04
@avioli yes it can be done in getStateForAction but again is there a way to access component's internal state in that function? or i will have to set the whole data in params, this is a bit confusing to me

**Comment by michchan** [comment] 2018-05-05 06:57
I have also look for the solution about this for a few times.
What I exactly expect is that the swipe back transition can be interrupted and bounced back.
At this time we can prompt to confirm leaving screen.
Is this not possible for react-navigation so far?

**Comment by brentvatne** [comment] 2018-05-07 22:32
@michchan - disable gestures on your screen in navigationOptions

we need to improve docs around intercepting navigation actions, so i created https://github.com/react-navigation/react-navigation.github.io/issues/151

this is otherwise a question and not a bug so closing

**Closed by brentvatne** 2018-05-07 22:32 UTC
