### ISSUE TITLE
Conflict between react-navigation when headerMode: 'none' and safeAreaView

### ISSUE THREAD

**Issue by lucasfernandes** [react-navigation/react-navigation#3327] opened 2018-01-22 13:16 UTC
Hi, I'm experiencing a weird behavior using react-navigation and safeAreaView .
Without safe area, when my StackNavigator is headerMode: 'none', everything goes fine, but when I use safeAreaView, the StackNavigator doesn't works perfectly and don't hide the header completely, ...maybe you guys can help with some tip.

Thats the illustration:
![simulator screen shot - iphone x - 2018-01-22 at 00 27 26](https://user-images.githubusercontent.com/29531/35222459-220ef1ee-ff65-11e7-8a71-d6ec416aabbe.png)

**Comment by kelset** [comment] 2018-01-22 14:37
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-22 14:37 UTC
