### ISSUE TITLE
Drawer can sometimes not be closed

### ISSUE THREAD

**Issue by Maxeh** [react-navigation/react-navigation#4522] opened 2018-06-16 17:20 UTC
I'm using the newest version of react-navigation (2.3.0). When `props.navigation.closeDrawer()` is called inside a custom drawer component the drawer sometimes is not closed. The same bug occurs when `props.navigation.navigate("SCREEN_NAME")` is called inside a custom drawer component (navigation is executed, but drawer is still open). However, this bug only occurs when the drawer is opened by swiping (not via the menu icon). Moreover, this bug does not occur every time. I tried to fix it with a setTimeout, to wait until the drawer is completely opened, but unfortunately this did not work.

I hope this GIF helps to clarify the bug:

![svid_20180616_191044](https://user-images.githubusercontent.com/10271898/41500851-eaa55ffc-7199-11e8-827a-3bdfda556070.gif)

**Comment by vonovak** [comment] 2018-06-17 19:50
hello, sorry you're having an issue. I'd like to ask you to create a reproduction of this problem that people can actually run, debug and find out what is wrong. With just a gif, this unfortunately isn't actionable. Thanks.

**Comment by Maxeh** [comment] 2018-06-17 20:46
Ok thanks for the reply. I have created a minimal version (just one file called App.js) with a DrawerNavigator. I used the code from the official docs. Here is a link to the [REPO](https://github.com/Maxeh/react-native-navigation-test). Just run `npm install` and `react-native run-android` to start the app. 

You can see in the GIF that the bug still exists in this simple app. Sometimes the drawer is not closed automatically when a drawer item is selected. In this sample app, the default Drawer Items are used. In the app above I used a custom drawer component and called `props.navigation.closeDrawer()`, but the bug also occurred.

![svid_20180617_222439](https://user-images.githubusercontent.com/10271898/41511882-bb7007c8-727f-11e8-92a0-b0f1e56eeb28.gif)

**Comment by brentvatne** [comment] 2018-06-20 20:14
https://snack.expo.io/HJZ6rNdWm

**Comment by brentvatne** [comment] 2018-06-20 22:35
fixed in 2.4.1

**Closed by brentvatne** 2018-06-20 22:35 UTC
Labels: component: Drawer

**Comment by Maxeh** [comment] 2018-06-21 00:33
Just updated to version 2.4.1 and the bug is still there.

**Comment by brentvatne** [comment] 2018-06-21 19:35
@Maxeh - ok, it worked in my tests and I don't have more time to spend on this. want to submit a PR to fix it? https://github.com/react-navigation/react-navigation-drawer

**Comment by Maxeh** [comment] 2018-06-21 22:08
Well ok, the issue should be reopend then and not stay closed. 

I had a look at the source code, but I cannot figure out how exactly everything works together. I'm wondering why no one else has reported this bug yet? Isn't it a quite obvious one?

**Comment by brentvatne** [comment] 2018-06-21 22:53
moved the issue over to react-navigation-drawer

**Comment by brentvatne** [comment] 2018-06-21 22:54
> I'm wondering why no one else has reported this bug yet? Isn't it a quite obvious one?

i have no idea

**Comment by brentvatne** [comment] 2018-06-22 17:34
@Maxeh - I cleaned up the implementation of drawer navigator, it was awkwardly trying to maintain a source of truth for drawer open state in two places which led to race conditions like you observed here. I can't reproduce anything like in your videos above on react-navigation@2.5.0

**Comment by Maxeh** [comment] 2018-06-23 21:55
@brentvatne that's great. I also tested it and the bug seems to be fixed. Thanks a lot!
