### ISSUE TITLE
Jest failure 1.0.0-beta.13 (RN 0.48.4) due to CardStackStyleInterpolator

### ISSUE THREAD

**Issue by Palisand** [react-navigation/react-navigation#2691] opened 2017-10-04 20:00 UTC
### Current Behavior

When testing _`App.test.js`_ (below) with jest
``` javascript
import React from 'react';
import App from './App';

import renderer from 'react-test-renderer';

it('renders without crashing', () => {
  const rendered = renderer.create(<App />).toJSON();
  expect(rendered).toBeTruthy();
});
```
I get the following failure:
```
 FAIL  ./App.test.js
  ● Test suite failed to run

    /Users/palisand/Projects/trendGit/mobile-test/node_modules/react-navigation/src/views/CardStack/CardStackStyleInterpolator.js:3
    import { I18nManager } from 'react-native';
    ^^^^^^

    SyntaxError: Unexpected token import
```

### Expected Behavior

The test suite should not fail to run.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.48.4
| node             | 8.4.0
| npm or yarn      | 4.6.1
| jest | 21.2.1

jest preset: `"react-native"`

**Comment by kelset** [comment] 2017-10-14 11:25
Thanks for reporting! A PR to fix the issue is surely welcome ;)

**Comment by spencercarli** [comment] 2017-11-03 16:59
Is this still an issue with the latest release (beta.17)?

**Comment by kelset** [comment] 2018-01-03 09:23
Hi there @Palisand,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since Spencer last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2018-01-03 09:23 UTC
Labels: bug
