### ISSUE TITLE
Navigation in "componentDidMount" takes almost a second to flush

### ISSUE THREAD

**Issue by JesperLekland** [react-navigation/react-navigation#5438] opened 2019-01-01 18:51 UTC
### Current Behavior
Doing a navigation action in `componentDidMount` of a (nested) transitioning StackNavigator doesn't actually perform the action until the StackNavigator's transition has settled. Thus causing a "jank" when actually navigating.  

```js
// If I do this inside of a StackNavigator that is currently being transitioned the actual replace isn't flushed until the transition settles.
componentDidMount() {
    const condition = this.props.navigation.state.params.condition;
    if(condition) {
      this.props.navigation.replace('foo');
    } else {
      this.props.navigation.replace('bar');
    }
  }
```
```js
// If I instead do this (outside of the StackNavigator that is being transitioned,) it works but doesn't allow me to reuse any logic for which screen to actually land on (which might be complex)

const conditional = true;

this.props.navigation.navigate({
  routeName: 'stackNavigator',
  action: NavigationActions.navigate({ routeName: conditional ? 'foo' : 'bar' }),
});

```
### Expected Behavior

I would expect for the navigation to be performed immediately. In my previous Redux implementation this was the case and is therefore creating a whole lot of problems when I'm trying to migrate away from Redux.

### How to reproduce

See [this snack](https://snack.expo.io/@lekland/cmVhY3)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 8.10.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment] 2019-01-01 21:04
this change was intentional, we don't update the transitioner state until after a transition completes - the state update is queued. it's not clear to me what the desired result would be here and i don't think we can assume that for people - should it replace the screen that is being animated in and continue the animation? should it animate the replaced screen in?

i think you could reorganize the way navigators are laid out to get the behavior you want, perhaps to use a switch somewhere where you're using a stack.

if you're interested in proposing a change to this functionality, i'd love to read a rfc for it. but considering that this works as designed and is not a bug, i will close this issue

**Closed by brentvatne** 2019-01-01 21:04 UTC

**Comment by JesperLekland** [comment] 2019-01-01 21:30
@brentvatne Thanks for the response. 

Regarding the transition I think it would be safe to assume that a `replace` shouldn't transition at all (as it never does anywhere else). The Stack itself should transition as usual as it's only its content we're replacing. 

Regarding reorganizing my navigators I don't see how that helps. Swapping out the inner navigator for a SwitchNavigator results in the exact same behaviour, i.e the switch doesn't occur until the new screen has completed it's transition.

Consider for example a checkout flow. I don't want my entire app to be aware of the fact that I have different checkout flows based on some parameter. I just want to call `navigation.navigate('checkoutflow', { someParam })` and have the checkout flow decide on the exact flow to present. I can't for the life of me figure out how to make this happen without having the `initialRouteName` screen of the checkout flow first transitioning in and then being replaced once it settled. I would be super thankful for any help!

I'm really trying to wrap my head around how this is meant to be solved. Hopefully with my learnings I'll be able to contribute back with either an RFC or a PR for the docs.

**Comment by brentvatne** [comment] 2019-01-01 21:39
> I just want to call navigation.navigate('checkoutflow', { someParam }) and have the checkout flow decide on the exact flow to present.

you could move the logic into a custom action - https://reactnavigation.org/docs/en/routers.html#custom-navigation-actions

**Comment by JesperLekland** [comment] 2019-01-02 12:08
@brentvatne That would work, but the custom action isn't passed down to the children of a StackNavigator (it is for a SwitchNavigator though). Is this a bug?

**Comment by brentvatne** [comment] 2019-01-02 21:07
a custom action is implemented on a specific router (which is just a reducer). when you dispatch an action it starts from the top of the navigation tree and works its way down
