### ISSUE TITLE
[Question] React Navigation get stack header height

### ISSUE THREAD

**Issue by James2516** [react-navigation/react-navigation#2411] opened 2017-08-17 12:06 UTC
How do i get the height of the StackNavigator header programmatically?

I need to detect if component A's position is within component B when pan gesture (drag) on A is released. However, the position from `onPanResponderRelease`'s `gesture.moveY` is measured with respect to the entire screen, whereas the position returned from A's `onLayout`is measured with respect to the parent view. So i'd need to know the parent view's current height to reconcile the differences.

**Comment by spencercarli** [comment] 2017-08-17 18:51
You can access the header height like this

```
import { Header } from 'react-navigation';
Header.HEIGHT;
```

[Source](https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js#L41)

**Comment by kaiyuanneo** [comment] 2017-11-08 02:56
I am getting this warning now. Seems like the approved method will fail soon.

Header.HEIGHT is deprecated and will be removed before react-navigation comes out of beta.

Any other way to get height of StackNavigator header?

**Comment by kaiyuanneo** [comment] 2017-11-08 03:32
So far I've been following hard-coded values here to avoid the warning from react navigation https://stackoverflow.com/questions/45698607/programmatically-retrieve-header-component-height-react-native

**Comment by spencercarli** [comment] 2017-11-09 17:42
That's a good question, @kaiyuanneo. We've made some changes because the header wasn't working correctly in landscape and now the iPhoneX changes things.

@brentvatne added the deprecation warning - could you add any insight on how we could handle this question? 

Once we determine that we should update the docs in some way

**Comment by jordanmkoncz** [comment] 2017-11-15 00:09
Also wondering what the 'correct' method is now for getting the height of the header. I'm using `Header.HEIGHT` in order to set this value as the width of my custom header button, i.e. to make my custom header button square, since it will automatically fill the full height of the header and I want it to always be a consistent 1:1 square aspect ratio.

**Comment by brentvatne** [comment] 2017-11-15 00:29
@spencercarli - `Header.HEIGHT` was initially removed when @davepack landed `SafeAreaView` because the [height is dynamic depending on orientation](https://github.com/react-community/react-navigation/blob/f2f4e5ce44c76b8273ad6082e8e5866fc8ebe7dd/src/views/Header/Header.js#L321) and `Header.HEIGHT` is a constant. I added it back because I didn't want to outright break apps without a deprecation warning well in advance. We need a solution that lets components subscribe to the get the current header height and also subscribe to changes, until then we can leave `Header.HEIGHT` as in. Open for ideas for how to solve this.

**Comment by jordanmkoncz** [comment] 2017-11-15 22:38
@brentvatne you mentioned that the height of the header is dynamic depending on orientation - does it also depend on the height of the status bar? I was looking into solutions for getting the current height of the status bar yesterday and saw that on iPhone X the behaviour of the status bar is different; it appears that it always has a height of 44pt, while on other iOS devices it has a height of 20pt by default, which can increase to 40pt (not 44pt), e.g. during a phone call.

**Comment by spencercarli** [comment] 2017-11-17 21:22
@jordanmkoncz I believe so

**Comment by xavierlefevre** [comment] 2018-01-02 10:31
@brentvatne Why don't you still export appBarHeight ?

**Comment by lukewlms** [comment] 2018-01-03 17:49
@brentvatne What about adding a property onContainerLayout that gives a callback whenever the header is laid out?  Seems this might be fairly simple since React Native provides this on all views, so it would just be a matter of passing the provided callback to the top-level View container of the header.

This seems to be needed for us b/c KeyboardAvoidingView needs to know the top offset of the view, which is at the bottom of the StackNavigator.  So I don't yet see how we can use react-navigation with a KeyboardAvoidingView, which is quite a strong limitation.

**Comment by elliotfleming** [comment] 2018-02-07 01:16
This is working for me...

``` jsx
import {
  Dimensions,
  KeyboardAvoidingView,
  View,
} from 'react-native';
import React, { Component } from 'react';
import PropTypes from 'prop-types';

const { height: fullHeight } = Dimensions.get('window');

export default class LayoutView extends Component {

  static propTypes = {
    children: PropTypes.node.isRequired,
  }

  state = {
    offset: 0,
  }

  onLayout = ({
    nativeEvent: { layout: { height } },
  }) => {
    const offset = fullHeight - height;
    this.setState({ offset });
  }

  render = () => (
    <View style={{ flex: 1 }} onLayout={this.onLayout}>
      <KeyboardAvoidingView
        style={{ flex: 1 }}}
        behavior="padding"
        keyboardVerticalOffset={this.state.offset}
      >
        {this.props.children}
      </KeyboardAvoidingView>
    </View>
  )

}
```

**Comment by brentvatne** [comment] 2018-02-07 22:38
@jordanmkoncz - yup, and status bar matters too!

@elliotfleming - seems reasonable.

I left `Header.HEIGHT` exposed until we have a better solution. please [create a RFC](https://github.com/react-navigation/rfcs) if you care about solving this problem

**Closed by brentvatne** 2018-02-07 22:38 UTC
Labels: component: Stack, question

**Comment by igor90007** [comment] 2018-02-09 11:25
my way:
navigationOptions:({navigation})=>{
    return{     
      headerStyle:{marginTop:-30}
    }
}`

**Comment by javier-orellana-tx** [comment] 2018-04-18 15:45
There are the helpers that I use:
```
import { Dimensions, DeviceInfo, Platform } from 'react-native';
import { Header } from 'react-navigation';

export const LANDSCAPE = 'landscape';
export const PORTRAIT = 'portrait';

export const getHeaderHeight = () => {
  let height;
  const orientation = getOrientation();
  height = getHeaderSafeAreaHeight();
  height += DeviceInfo.isIPhoneX_deprecated && orientation === PORTRAIT ? 24 : 0;

  return height;
};

// This does not include the new bar area in the iPhone X, so I use this when I need a custom headerTitle component
export const getHeaderSafeAreaHeight = () => {
  const orientation = getOrientation();
  if (Platform.OS === 'ios' && orientation === LANDSCAPE && !Platform.isPad) {
    return 32;
  }
  return Header.HEIGHT;
};

export const getOrientation = () => {
  const { width, height } = Dimensions.get('window');
  return width > height ? LANDSCAPE : PORTRAIT;
};

```

**Comment by grissproject** [comment] 2018-04-18 15:47
These are the helpers that I use:

import { Dimensions, DeviceInfo, Platform } from 'react-native';
import { Header } from 'react-navigation';

export const LANDSCAPE = 'landscape';
export const PORTRAIT = 'portrait';

export const getHeaderHeight = () => {
  let height;
  const orientation = getOrientation();
  height = getHeaderSafeAreaHeight();
  height += DeviceInfo.isIPhoneX_deprecated && orientation === PORTRAIT ? 24 : 0;

  return height;
};

// This does not include the new bar area in the iPhone X, so I use this when I need a custom headerTitle component
export const getHeaderSafeAreaHeight = () => {
  const orientation = getOrientation();
  if (Platform.OS === 'ios' && orientation === LANDSCAPE && !Platform.isPad) {
    return 32;
  }
  return Header.HEIGHT;
};

export const getOrientation = () => {
  const { width, height } = Dimensions.get('window');
  return width > height ? LANDSCAPE : PORTRAIT;
};

**Comment by Raunak-Agrawal** [comment] 2019-12-26 06:32
Header.height is not accessible via react-navigation. Any update on this?

**Comment by tylerg509** [comment] 2019-12-31 02:45
@Raunak-Agrawal just import as below

`import { Header } from 'react-navigation-stack';
`

`      console.log(Header.HEIGHT)
`

**Comment by Prosquid1** [comment] 2020-01-02 21:22
Have you tried what you posted @tylerg509 
It's been removed in `react-navigation-stack`

**Comment by phliem** [comment] 2020-01-11 16:26
'Header.HEIGHT' is depreciated in v2 

You can now use the useHeaderHeight hook
```
import { useHeaderHeight } from 'react-navigation-stack';
const headerHeight = useHeaderHeight();
console.warn(headerHeight)
```

**Comment by kiwipxl** [comment] 2020-02-02 06:24
Using `useHeaderHeight` in the `render()` function of a react-native Component is giving me the following error: "Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component."
What could I be doing wrong? It's in the render function.

**Comment by sharifhh** [comment] 2020-02-19 11:52
> Using `useHeaderHeight` in the `render()` function of a react-native Component is giving me the following error: "Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component."
> What could I be doing wrong? It's in the render function.

You need to write functional components or HOC, you cannot use hooks in class components.

**Comment by DnEgorWeb** [comment] 2020-03-07 07:35
From the [documentation](https://reactnavigation.org/docs/stack-navigator/): use hook for function components to get header's height
```
import { useHeaderHeight } from '@react-navigation/stack';

const headerHeight = useHeaderHeight();
```
or you can use HeaderHeightContext with React's Context API 
```
import { HeaderHeightContext } from '@react-navigation/stack';

<HeaderHeightContext.Consumer>
  {headerHeight => (
    /* render something */
  )}
</HeaderHeightContext.Consumer>
```

**Comment by mi-mazouz** [comment] 2020-03-09 15:41
I have lot of trouble using useHeaderHeight()! It causes some UI regressions as the height suddenly change for nothing in particular

**Comment by PositronicBrain** [comment] 2020-03-31 10:40
I have the same problem as @mi-mazouz. Is there a workaround?

**Comment by PositronicBrain** [comment] 2020-03-31 10:47
I have the same problem as @mi-mazouz, header height updating during render with a jerk in the UI.

**Comment by 5ervant** [comment] 2020-04-01 20:06
> This is working for me...
> 
> ```js-jsx
> import {
>   Dimensions,
>   KeyboardAvoidingView,
>   View,
> } from 'react-native';
> import React, { Component } from 'react';
> import PropTypes from 'prop-types';
> 
> const { height: fullHeight } = Dimensions.get('window');
> 
> export default class LayoutView extends Component {
> 
>   static propTypes = {
>     children: PropTypes.node.isRequired,
>   }
> 
>   state = {
>     offset: 0,
>   }
> 
>   onLayout = ({
>     nativeEvent: { layout: { height } },
>   }) => {
>     const offset = fullHeight - height;
>     this.setState({ offset });
>   }
> 
>   render = () => (
>     <View style={{ flex: 1 }} onLayout={this.onLayout}>
>       <KeyboardAvoidingView
>         style={{ flex: 1 }}}
>         behavior="padding"
>         keyboardVerticalOffset={this.state.offset}
>       >
>         {this.props.children}
>       </KeyboardAvoidingView>
>     </View>
>   )
> 
> }
> ```

@elliotfleming Will that work with a transparent header? *(https://reactnavigation.org/docs/stack-navigator/#headerbackground)* It seems not because a transparent header don't have a height?

Take note, don't ask me to use `HeaderHeightContext` nor `useHeaderHeight`, they're raising an error on a Next.js app. https://github.com/expo/expo-cli/issues/1782

**Comment by kdpadhiyar** [comment] 2020-05-25 13:13
> > Using `useHeaderHeight` in the `render()` function of a react-native Component is giving me the following error: "Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component."
> > What could I be doing wrong? It's in the render function.
> 
> You need to write functional components or HOC, you cannot use hooks in class components.

how can i get header height in class component i am using React navigation v5 help me

**Comment by sharifhh** [comment] 2020-05-25 13:32
@k

> > > Using `useHeaderHeight` in the `render()` function of a react-native Component is giving me the following error: "Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component."
> > > What could I be doing wrong? It's in the render function.
> > 
> > 
> > You need to write functional components or HOC, you cannot use hooks in class components.
> 
> how can i get header height in class component i am using React navigation v5 help me
> @sharifhh

@kdpadhiyar 

`export const withHeight = (Component) => { 

const height = useHeaderHeight();

return <Component height={height} />

}`

`
Class Test ....

export default withHeight(Test);
`

**Comment by martinezguillaume** [comment] 2020-06-07 15:18
Same problem as @mi-mazouz and @PositronicBrain 
During first render, I receive 2 difference value with `useCurrentHeight` making a flicker. 
The first one is wrong, and the second is the right one. 

I'm using headerTransparent too

**Comment by kdpadhiyar** [comment] 2020-06-08 13:03
@sharifhh  thank you so much for help.

**Comment by kamalpandey** [comment] 2020-07-21 08:16
How to use this in class component?

**Comment by neclamis1285** [comment] 2020-07-27 14:41
You can use this in a class component by wrapping your render contents in a 'HeaderHeightContext.Consumer'

`
import {HeaderHeightContext} from '@react-navigation/stack';

 return (
    <HeaderHeightContext.Consumer>
        {(headerHeight: any) => {
            return (
                <View>
                    <Text>Some Text</Text>
                </View>
                );
        }}
    </HeaderHeightContext.Consumer>
 );
`

**Comment by warrenalphonso** [comment] 2020-08-20 19:18
> I get this error when I try to use `useHeaderHeight()`:
> `Error: Couldn't find the header height. Are you inside a screen in Stack?`
> 
> Code:
> 
> ```
> //...
> 
> import {
> 	createStackNavigator,
> 	useHeaderHeight
> } from '@react-navigation/stack';
> 
> //...
> 
> const AppStack = createStackNavigator();
> const AppStackNavigation = () => {
> 	const headerHeight = useHeaderHeight();  // <-- ERROR
> 	console.log(headerHeight);
> 	render (
> 		//...
> 	)
> }
> ```

Does anyone have a solution to this? I'm getting the same error.

**Comment by neclamis1285** [comment] 2020-08-20 20:21
Is this in a React Native `Class` component or a `Function` component?

**Comment by nicotroia** [comment] 2020-08-29 06:30
How would you get the header height, ie. use `useHeaderHeight` or `HeaderHeightContext` in a plain helper function? Since it is neither a "function component" nor within a class component

**Comment by neclamis1285** [comment] 2020-08-29 13:16
If I am understanding your question correctly, you could pass the header height from your function/class component to your utility function. 

### Class Component

```    
import {HeaderHeightContext} from '@react-navigation/stack';

export default class MyClassComponent extends Component<Props, State> {

static contextType = HeaderHeightContext;

const {headerHeight} = this.context;
console.log('HEADER HEIGHT: ' + Utils.doSomethingWithHeaderHeight(headerHeight));

render = () => {
  <View style="{{height: headerHeight}}">
  </View>
};

}
```

### Utility Function

```
export const Utils = {
   doSomethingWithHeaderHeight: (headerHeight) => {
        return headerHeight + 10;
    }
};
```

**Comment by Belgin-Android** [comment] 2020-11-27 15:38
@neclamis1285 Just Wanted To Know Why You Are Increasing The Value By 10 In The Utility Function ?

**Comment by P026** [comment] 2021-04-22 22:34
This isn't working anymore

**Comment by kp72-dev** [comment] 2021-06-14 10:27
> > I get this error when I try to use `useHeaderHeight()`:
> > `Error: Couldn't find the header height. Are you inside a screen in Stack?`
> > Code:
> > ```
> > //...
> > 
> > import {
> > 	createStackNavigator,
> > 	useHeaderHeight
> > } from '@react-navigation/stack';
> > 
> > //...
> > 
> > const AppStack = createStackNavigator();
> > const AppStackNavigation = () => {
> > 	const headerHeight = useHeaderHeight();  // <-- ERROR
> > 	console.log(headerHeight);
> > 	render (
> > 		//...
> > 	)
> > }
> > ```
> 
> Does anyone have a solution to this? I'm getting the same error.



> > I get this error when I try to use `useHeaderHeight()`:
> > `Error: Couldn't find the header height. Are you inside a screen in Stack?`
> > Code:
> > ```
> > //...
> > 
> > import {
> > 	createStackNavigator,
> > 	useHeaderHeight
> > } from '@react-navigation/stack';
> > 
> > //...
> > 
> > const AppStack = createStackNavigator();
> > const AppStackNavigation = () => {
> > 	const headerHeight = useHeaderHeight();  // <-- ERROR
> > 	console.log(headerHeight);
> > 	render (
> > 		//...
> > 	)
> > }
> > ```
> 
> Does anyone have a solution to this? I'm getting the same error.





function headerHeight() {
        const height = useHeaderHeight();
        return height
    }
 const height = headerHeight();

**Comment by Kiran-infostretch** [comment] 2021-12-29 08:03
Check this solution: [link](https://stackoverflow.com/a/46040401)

React navigation V6

import { useHeaderHeight } from '@react-navigation/elements';
const headerHeight = useHeaderHeight();
React navigation V5

import { useHeaderHeight } from '@react-navigation/stack';
const headerHeight = useHeaderHeight();
or with React Context's API (not recommended)

React navigation V4

import { Header } from 'react-navigation-stack';
const headerHeight = Header.HEIGHT;
React navigation V2-V3

import { Header } from 'react-navigation';
const headerHeight = Header.HEIGHT;

**Comment by AlexMNet** [comment] 2022-01-17 08:50
@Kiran-infostretch I am still getting the same error some of the others are getting when trying to use useHeaderHeight()

Error: Couldn't find the header height. Are you inside a screen in a navigator with a header?

Has anyone else managed to figure this out? Any additional information would be greatly appreciated!
"@react-navigation/elements": "^1.2.1",

**Comment by maryjenel** [comment] 2022-04-01 17:33
> You can access the header height like this
> 
> ```
> import { Header } from 'react-navigation';
> Header.HEIGHT;
> ```
> 
> [Source](https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js#L41)

this gave me an error for the import. I used `import { Header } from '@react-navigation/elements';`

**Comment by fcole90** [comment] 2022-11-23 13:59
> I get this error when I try to use `useHeaderHeight()`: `Error: Couldn't find the header height. Are you inside a screen in Stack?`
> 
> Code:
> 
> ```
> //...
> 
> import {
> 	createStackNavigator,
> 	useHeaderHeight
> } from '@react-navigation/stack';
> 
> //...
> 
> const AppStack = createStackNavigator();
> const AppStackNavigation = () => {
> 	const headerHeight = useHeaderHeight();  // <-- ERROR
> 	console.log(headerHeight);
> 	render (
> 		//...
> 	)
> }
> ```

The hook is defined here: https://github.com/react-navigation/react-navigation/blob/5.x/packages/stack/src/utils/useHeaderHeight.tsx

If you know it's a safe operation, you can define your own hook as
´´´tsx
import { HeaderHeightContext } from '@react-navigation/stack';

const useHeaderHeight = () => {
  const height = React.useContext(HeaderHeightContext);

  if (height === undefined) {
    return 0;
  }

  return height;
};
´´´

**Comment by HarwinderSingh15** [comment] 2023-09-07 07:42
Use this instead

`import { HeaderHeightContext } from '@react-navigation/elements';

const useHeaderHeight = () => {
  const height = React.useContext(HeaderHeightContext);

  if (height === undefined) {
    return 0;
  }

  return height;
};
`

[https://reactnavigation.org/docs/elements/#headerheightcontext](url)


as per the officials docs, 

headerHeightContext has been shifted to @react-native-navigation/elemts
