### ISSUE TITLE
NavigationActions.back() action is unexpected behavior

### ISSUE THREAD

**Issue by Gennady77** [react-navigation/react-navigation#3298] opened 2018-01-18 09:22 UTC
Hi everyone.

I started to learn react navigation and saw that back action behavior is not like in a browser and unexpected for me. I created small app with the follow structure:

TabNavigator has 'Home', 'Notifications' and 'Topics' tabs.
'Topics' is a StackNavigator and has 'Topic1', 'Topic2' and 'Topic3' screens
'Topic1' has a button to navigate to 'Topic2'
'Topic2' has a button to navigate to 'Topic3'
(important) Tab 'Notification' has a button to navigate to 'Topic3'

see link https://snack.expo.io/r1DT5e6NM

I'm doing the navigation according to the following scheme:

Home -> Notifications -> Topic3 -> press 'back'

Expected result:

I should be returned from Topic3 screen to the Notification

Real result:

I navigate to 'Topic2' screen and when I press 'back' again I navigate to 'Topic1'

I didn't test it on ios. Android only. It happen on both Debug and Release modes.  It happens with Debugger On and Off. Code and example of app see by the link above.

It's really unexpected behavior for me. So I need to understand this problem. Is it notmal for react navigation? Any ideas?

**Comment by kelset** [comment] 2018-01-18 09:24
Duplicate of #3294

**Closed by kelset** 2018-01-18 09:24 UTC

**Comment by Gennady77** [comment] 2018-01-18 09:46
I don't understand why are you closing my issues?
