### ISSUE TITLE
Wrong URL of screen in Web

### ISSUE THREAD

**Issue by krivochenko** [react-navigation/react-navigation#10196] opened 2021-12-14 22:16 UTC
### Current behavior

1. git clone git@github.com:krivochenko/navigation-web.git
2. npm i
3. npm run start
4. Build web-version. URL: http://localhost:19006/chat
5. Press "Chat 3". URL: http://localhost:19006/chat/3
6. Press second bottom navigation tab. URL: http://localhost:19006/profile
7. Press "Chat 5". Correct content will be displayed, but URL is wrong: http://localhost:19006/chat/3 instead of expected http://localhost:19006/chat/5. Also if update page, another content will be displayed.

### Expected behavior

Correct URL should be displayed.

### Reproduction

https://github.com/krivochenko/navigation-web

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.6
| @react-navigation/bottom-tabs          | ^6.0.9
| @react-navigation/drawer               | ^6.1.8
| @react-navigation/native-stack         | ^6.2.5
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | ~3.8.0
| react-native-gesture-handler           | ^1.10.3
| react-native-reanimated                | ^2.2.3
| react-native                           | 0.64.3
| expo                                   | ~43.0.2
| node                                   | 16.8.0
| npm or yarn                            | npm 7.21.0

**Comment by AMSTKO** [comment] 2021-12-15 16:12
Exactly the same problem, I'm looking for a solution right now but if you have an idea don't hesitate

**Comment by AMSTKO** [comment] 2021-12-15 17:48
We can see that the right url will be applied in the browser a few milliseconds before being replaced by the previous value of the screen visited the first time.

**Comment by krivochenko** [comment] 2021-12-15 18:35
> We can see that the right url will be applied in the browser few milliseconds (like a blink) before being replaced by the previous value of the same screen visited the first time. but the params from useRoute() are ok and don't "blink" with the url.

Yes, you are right.

**Comment by AMSTKO** [comment] 2021-12-15 18:40
I did a little hack to solve this before a better solution.

I use a component to make all my links so this addition was fast, I force linkTo after few milliseconds for the right link to be applied in the browser.

```js
  const handlePress = (to) => {
    linkTo(to);

    setTimeout(() => {
      linkTo(to);
    }, 50);
  }
```

**Comment by satya164** [comment] 2022-01-28 15:24
Closing as duplicate of #10046

**Closed by satya164** 2022-01-28 15:24 UTC
Labels: bug, package:drawer, platform:web, package:bottom-tabs, repro provided, package:native-stack

**Comment by quicksilverr** [comment] 2023-03-13 08:01
@AMSTKO Is this due to some sale state? In my case, it shows some url path, which is not even accessed once in the app?
