### ISSUE TITLE
How do I go back "to" an arbitrary route from another?

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#1213] opened 2017-04-24 16:51 UTC
I don't understand the meaning / usage of the `goBack` method when a key is supplied. Let's say I have the following event history:

```js
navigation.navigate(SCREEN_KEY_A);
...
navigation.navigate(SCREEN_KEY_B);
...
navigation.navigate(SCREEN_KEY_C);
...
navigation.navigate(SCREEN_KEY_D);
```

I am now on Screen D and when I click some contrived button on Screen D, I expect to go all the way back to A. Not immediately back to C, but straight back to A (popping D, C, and B). My intuition says the following code should do it:

```jsx
navigation.goBack(SCREEN_KEY_A)
```

I.e., "go back **TO** Screen A", but this doesn't seem to be the case. [The docs say](https://github.com/react-community/react-navigation/blob/dff746a83c0159ebf69aeb9961228abe211e4041/docs/guides/Screen-Navigation-Prop.md#goback---close-the-active-screen-and-move-back) that when you supply a key to `goBack`, it specifies the screen to go back **FROM**. Does this mean in the example above, I would want:

```js
navigation.goBack(SCREEN_KEY_B) // if I go back from B, I will land on A?
```

I tried the above usage (supplying a key to goBack), but nothing happens. Nothing gets popped, no errors are logged. So I've fallen back to using:

```js
navigation.goBack(null);
navigation.goBack(null);
navigation.goBack(null);
```

But this is terrible for obvious reasons.

Can you clarify what you mean by "from", and how the `goBack` method should be used to achieve the example above? Thanks!

**Comment by grabbou** [comment] 2017-04-24 17:35
I believe it's a typo and we meant `to`, @ericvicenti ?

**Comment by RichardLindhout** [comment] 2017-04-24 18:49
I also would like to go back from e.g. Home > Start > Login from the Login page straight back to the Home page.

**Comment by despreston** [comment] 2017-04-24 20:36
goBack with a key does not seem to work at all on beta 7. Nothing happens + no error message.

**Comment by beeglebug** [comment] 2017-04-25 08:07
I would also like to know how to do this. I previously used NavigationExperimental and had access to a popTo function, which would pop routes off the stack all the way to a specifc named route, but I can't see an obvious way to do this with react-navigation.

**Comment by lettleprince** [comment] 2017-04-25 14:44
Same problem +1.

**Comment by edmofro** [comment] 2017-04-26 02:19
I agree that this should be available by default. Here's code I use which works (does flash up the screens in between though):
```
import { Navigator } from './Navigator';
import { JUMP_BACK_TO_ROUTE } from './constants';

export const reducer = (state, action) => {
  if (action.type === JUMP_BACK_TO_ROUTE) {
    const newState = {
      ...state,
      routes: [],
    };
    for (let i = 0; i < state.index; i += 1) {
      const routeCopy = { ...state.routes[i] };
      newState.routes.push(routeCopy);
      if (routeCopy.routeName === action.routeName) {
        newState.index = i;
        break;
      }
    }
    return newState;
  }
  return Navigator.router.getStateForAction(action, state) || state;
};
```

**Comment by satya164** [comment] 2017-04-26 12:34
> I expect to go all the way back to A

How do you get the key for `A`?

Probably the following is better:

`goBack()` - Go back 1 level
`goBack({ to: key })` - Go back to this screen, but where do you get this key? prolly you should be able to supple a `routeName` and it should take you two the last screen with that name

Though I'm not sure what `goBack({ from: key })` will do, or supposed to do.

**Comment by ashrithks** [comment] 2017-04-26 12:38
can we pass Params while using goBack() function

**Comment by joncursi** [comment] 2017-04-26 13:12
> How do you get the key for A?

Many ways. For example, passing an `onDone` function prop, such as this:

```jsx
// in some part of the application, i..e ScreenX
<SomeComplexScreenOrStackOfScreens
  ...
  onDone={() => {
    navigation.goBack(SCREEN_KEY_X);
  }}
  ...
/>

// in another part of the application, i..e ScreenY
<SomeComplexScreenOrStackOfScreens
  ...
  onDone={() => {
    navigation.goBack(SCREEN_KEY_Y);
  }}
  ...
/>
```

**Comment by satya164** [comment] 2017-04-26 13:14
How would you pass the `onDone` prop to a screen?

**Comment by joncursi** [comment] 2017-04-26 13:25
Oh. Imperatively, through params:

```js
// push to SomeComplexScreenOrStackOfScreens from ScreenY, want to return to ScreenY when done
navigation.navigate(SCREEN_KEY_SOME_COMPLEX_SCREEN_OR_STACK_OF_SCREENS, {
  onDone: () => {
    navigation.goBack(SCREEN_KEY_Y);
  },
});

// push to SomeComplexScreenOrStackOfScreens from ScreenX, want to return to ScreenX when done
navigation.navigate(SCREEN_KEY_SOME_COMPLEX_SCREEN_OR_STACK_OF_SCREENS, {
  onDone: () => {
    navigation.goBack(SCREEN_KEY_X);
  },
});
```

The `onDone` param is then treated as a first class citizen in `SomeComplexScreenOrStackOfScreens`; it is passed around / stored / wired up accordingly so the system knows what do do when the user is "Done".

**Comment by joncursi** [comment] 2017-04-26 13:27
To clarify what I mean by `SomeComplexScreenOrStackOfScreens`, think of a slide show. It can be a screen that calls itself recursively until you reach the end of the slide show. At that point, you have no more slides to push, so you need an exit strategy. This is where `onDone` comes in.

**Comment by ashrithks** [comment] 2017-04-26 13:28
@joncursi  can we pass Params while using goBack() function ???

**Comment by satya164** [comment] 2017-04-26 13:28
Passing functions in params in not recommended. Though yeah, you can pass the key in the param. Doesn't seem a lot useful though since it's just the previous screen.

**Comment by joncursi** [comment] 2017-04-26 13:29
@satya164 it's not always the previous screen. In the slideshow example above, you could push through 20 slides, and then at the end want to pop all the way back to the screen that initiated the slide show to begin with. Know what i mean?

**Comment by satya164** [comment] 2017-04-26 13:32
yeah, gotcha

**Comment by ericvicenti** [comment] 2017-04-26 15:31
What if we allowed a key to be specified to `navigate`, and it would "navigate back" if the key is in already in the routes.

This could also be a nice solution to the 'tap-twice push-twice' issue. When providing a key and a link is quickly tapped twice, the first `navigate` pushes, and the second `navigate` simply makes sure that the correct key is active.

More discussion in https://github.com/react-community/react-navigation/issues/135

**Comment by RichardLindhout** [comment] 2017-04-26 17:10
That would be a good idea!

Op 26 apr. 2017 17:31 schreef "Eric Vicenti" <notifications@github.com>:

**Comment by ztplz** [comment] 2017-05-03 15:55
same problem

**Comment by wilomgfx** [comment] 2017-05-03 19:10
thanks @edmofro , that suits me well for now!

**Comment by laclance** [comment] 2017-05-09 08:29
My case is quite specific so to go back from say `routeFive` to `routeTwo` i passed `routeTwoKey` as a prop down to `routeFive` then used `goBack(routeTwoKey);`

**Comment by giautm** [comment] 2017-06-20 04:47
I have routes: List -> Detail -> Update.
I want to back to the List after submitted an update. So, i did:
```
  // Navigate to Update with Detail key as a param.
  handleUpdatePress = (params) => {
    const { navigate, state } = this.props.navigation;
    navigate('UpdateResult', {
      ...params,
      parentKey: state.key,
    });
  };
```
On Update screen, i write a handle for submitted update:
```
  handleSubmitted = () => {
    const { goBack, state } = this.props.navigation;
    const { parentKey } = state.params;
    goBack(parentKey || null);
  };
```

**Comment by joncursi** [comment] 2017-09-25 16:44
@giautm I'm not sure how you got that to work because when I do the same thing on my end (supplying a key rather than `null`), nothing pops!

**Comment by alexrussell** [comment] 2017-11-15 10:57
To be honest, the whole key/from thing doesn't make much sense to me. My absolute preference would be to maybe have an alternative mode for "goBack" (if we didn't want to break BC) which would simply keep popping until a given routeName (not key - they're too hard to create\* and then pass around!) is found, and then stop at that screen. So pretty much like the OP's method but instead of using these weird keys we just use the routeName (which, actually, I think the OP is trying to do anyway). That'd also work for @joncursi's slideshow issue.

---

\*In fact I'm not currently sure *how* to create them. They appear to be being generated for me on my `navigate` actions, but I need to read the docs as to how to create my own to use as "back from" keys temporarily.

**Comment by alexrussell** [comment] 2017-11-15 12:48
FWIW I have written by own [`goBackTo` saga](https://gist.github.com/alexrussell/65aace4c6f9d3bec01876d1083c79705) that I am currently using. While it is based on redux-saga, the same could work for redux-thunk or anything else that can query the current state in order to determine an action that should be dispatched.

I feel like it does the most correct (with what react-navigation gives us anyway) way to solve this. In short:

1. Get current stack
2. Starting at the current index, and working backwards, find a route with the given `routeName`
3. When found, get the key for the screen that's "next" in the stack after it
4. Call `NavigationActions.back() using the "from key" mode and using that key

There's a little bit of extra checking in there to ensure we don't go to odd places if the screen was not found or is the screen we're on. (Not found: just go back one screen, screen we're on: do nothing.)

So far in my limited testing it works fine, but I'll update that gist if it needs refinement.

**Comment by elyran** [comment] 2018-01-03 17:26
This code:
https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L290
```
          const backRoute = state.routes.find(
            (route: NavigationRoute) => route.key === key
          );
```
It's iterating through `routes`, which in my POC is:
```[{"routeName":"Home","key":"Init-id-1514998913105-3"},{"key":"id-1514998913105-4","routeName":"Details"},{"key":"id-1514998913105-5","routeName":"UpdateDetails"}]```

Now, the problem is that the keys are just some random strings. In other places in the docs, the `key` is the screen/route's name. For example here: https://reactnavigation.org/docs/navigators/navigation-prop#goBack-Close-the-active-screen-and-move-back

See the example at the bottom of the section? The 'Going back from a specific screen'. In that case it specifies a code example like `navigation.navigate(SCREEN_KEY_A)` while this actually means `navigation.navigate(SCREEN_NAME_A)`. See the difference? The definition of `name` and `key` seems to be inconsistent and is causing a confusion.

Please let me know if I got something wrong, as I'm just starting out with your component (THANKS!! 😄  ).

**Comment by elyran** [comment] 2018-01-03 17:29
I suggest that the above code will look like:
```(route: NavigationRoute) => (route.key === key) || (route.routeName === key)```

**Comment by alexrussell** [comment] 2018-01-04 09:53
@elyran You should probably refine the code though so that it looks backwards through the stack - keys are always unique so as long as it's found in the stack it's good, but a route name may be in the stack a few times (circular navigation) and it is most likely that you'll only want to go back as far as the *most recent* version of a given route, not the *first ever* one.

**Comment by elyran** [comment] 2018-01-04 11:39
I agree @alexrussell . Is there a solution for that already? Any PR?

**Comment by alexrussell** [comment] 2018-01-04 11:46
The gist I mentioned does a reverse search in this manner, but isn't integrated into react-navigation and doesn't do the combining of key *or* route name thing that yours does. So no, no PR already existing that I know of, but you can combine your suggestion here and code similar to my gist to do the reverse find and maybe create one.

**Comment by ericvicenti** [comment] 2018-01-31 05:58
Hey folks, I've got a proposed fix to this in https://github.com/react-navigation/react-navigation/pull/3393

As proposed, the navigate action would take an optional `key`, which would allow you to navigate back to the route with that key. If you pass params, they will also be applied.

Hopefully that will take care of these use cases!

**Comment by alexrussell** [comment] 2018-01-31 10:01
@ericvicenti so this 'fixes' the issue from the other side, right? I.e. it allows you to specify keys when you route *to*, so the "back from" routing stays as it is, having to pass the key in?

This is okay, (at least we can route back to/from a specific screen) but I really do think that being about to specify the route by its name would be more useful, as it'd mean you don't have to attach keys to navigation actions and then pass them (possibly deep) down your hierarchy. So, with that in mind, is there a reason you're sticking to the "navigate back using keys, not route names" thing? Is there a good reason that I'm not aware of?

**Comment by ericvicenti** [comment] 2018-02-01 20:00
#3393 has landed, so hopefully this is addressed now! Feel free to file followup issues if it doesn't work for you

@alexrussell, the main reason is because there may be several routes with the same routeName (it really means more like route type), so they are not really identifiable that way. Keys will never be duplicated. However, you can now provide a key while navigating to something, so hopefully they key will be more accessible when navigating back to a screen.

Also, you can provide a key to the back action to tell the stack where to go back *from*.

**Closed by ericvicenti** 2018-02-01 20:00 UTC
Labels: question, related: goBack, request for comments

**Comment by alexrussell** [comment] 2018-02-01 21:49
I see where you're coming from, though I must say, even given the caveats of a route name not being unique (though it is unique to a 'screen', just not a screen + parameters, right?), most of the time all I want to do is actually go back in the stack until you find a route (any route) that matches the route name. Realistically I want to go back to the most recent state of a given screen, so that wouldn't matter to me as long as the semantics of going back is that it goes back only to the most recent route in the stack.

(Also, side note, I'd definitely have to go back *to* rather than *from* but again maybe that's just me misunderstanding the use-case of the current situation and trying to fit my own one into it.)

Anyway, fair enough if you don't feel comfortable with the library supporting something very slightly ambiguous (though, of course this could be specified in the docs, etc.). As mentioned earlier I managed to come up with my own utility function to do this anyway, it's just a shame it's not in the lib.

**Comment by ericvicenti** [comment] 2018-02-01 21:53
I kinda agree that it would be nice to support this general use case of going back to the screen with the route name. Actually.. we could probably fix this by using the route name as the key, until the first duplicate key arrives!

Only confusing part is that you specify the "key" inside the action and not the routeName, so people may mix up the concepts because of this.

cc @brentvatne

**Comment by alexrussell** [comment] 2018-02-02 09:06
@ericvicenti actually that may not be as useful a fix as you think - if RN uses the route name as the key until it sees a duplicate, it means that if the stack contains two entries with the same route name, the more recent one will have the generated (unknown) key, so going back to a given 'screen' will end up going back to the first (oldest), not the most recent one. Unless I'm not understanding you correctly.

**Comment by ericvicenti** [comment] 2018-02-02 16:00
Yeah, you're right that it wouldn't be ideal in that case. If you have another suggestions, maybe you could draft up an RFC to propose it to the community?

**Comment by alexrussell** [comment] 2018-02-02 17:06
@ericvicenti the only suggestion I have right now is [the gist](https://gist.github.com/alexrussell/65aace4c6f9d3bec01876d1083c79705) that I [posted earlier](https://github.com/react-navigation/react-navigation/issues/1213#issuecomment-344582467). It would probably need a tweak to be implemented into RN: first off it wouldn't need to be a saga as it'd be built into RN and wouldn't need to generate a back-from-key action as it's already *be* an action, also it has its own set of heuristics that you may not like (if no route found go back one screen, if current route is the route searching for do nothing), so I dunno if it's really worth anything to you.

**Comment by ericvicenti** [comment] 2018-02-02 17:32
It seems there isn't a clear solution here, but thanks for the feedback. I'll keep the use case in mind for future improvements!

**Comment by alexrussell** [comment] 2018-02-03 11:36
That sounds fair.

**Comment by thaoth58** [comment] 2018-03-20 11:07
@alexrussell I agree that a function to go back to screen with routeName is necessary and it'll make my code much cleaner. At the first time, i'm so confused about the routeName and key. Hope @ericvicenti could provide an official function to solve this.

**Comment by ericvicenti** [comment] 2018-03-20 13:59
Good news! This is something we are changing in v2 within the navigate behavior:

https://github.com/react-navigation/rfcs/pull/25

Now you can 'navigate' to a routeName that is earlier in the stack, and you will go back to it.

Feel free to try this behavior out in `react-navigation@2.0.0-beta.3`

Thanks go to @brentvatne for this fix!

**Comment by alexrussell** [comment] 2018-03-21 14:30
Ooh, sounds promising. And from the looks of it you can still have multiple entries in the stack of a given route by just using the `key` property, right? (Because that could be an issue in some use cases.)

**Comment by brentvatne** [comment] 2018-03-22 21:07
@alexrussell - yup, exactly. those are the two options in that case

**Comment by superdopey** [comment] 2018-08-30 15:44
I changed @edmofro code a bit, so you can add a parameter backTo when navigating to a page which needs to goBack to a certain page when navigating back:  

```
if (
    action.type === NavigationActions.BACK &&
    (state.routes[state.index].params &&
      state.routes[state.index].params.backTo)
  ) {
    const backTo = state.routes[state.index].params.backTo
    const newState = {
      ...state,
      routes: []
    }
    for (let i = 0; i < state.index; i += 1) {
      const routeCopy = { ...state.routes[i] }
      newState.routes.push(routeCopy)
      if (routeCopy.routeName === backTo) {
        newState.index = i
        break
      }
    }
    return newState
  }
```

Now when I navigate to a screen which needs to goBack to a certain page I can use the backTo param:
```navigate('UserInfo', { backTo: 'Dashboard' })```

**Comment by smitthakkar1** [comment] 2019-04-04 14:15
@superdopey looks good but can you please tell me where do you put this code?
