### ISSUE TITLE
Unhandled JS Exception: null is not an object (evaluating 'RNGestureHandlerModule.State')

### ISSUE THREAD

**Issue by CyberMew** [react-navigation/react-navigation#5621] opened 2019-02-24 14:27 UTC
### Current Behavior

Loading the React Native app in iOS (did not test Android) is giving `Unhandled JS Exception: null is not an object (evaluating 'RNGestureHandlerModule.State')`

### Expected Behavior

I expected it to show the view without issues.

### How to reproduce

I followed the docs and installed the packages and linked them as instructed.

In RN using index.js only.:
```
import {AppRegistry, StyleSheet, Text, View, Button, Component} from 'react-native';
import React from 'react';

import { createStackNavigator, createAppContainer } from "react-navigation";

class RNHighScores extends React.Component {
    render() {
      return (
        <AppContainer />
      );
    }
  }

 const AppNavigator = createStackNavigator({
    Home: {
      screen: RNHighScores
    }
  });

  export default createAppContainer(AppNavigator);
```
In iOS, I am using a push navigation controller, and there is a UIButton action that pushes a view controller (which is basically loads RN):
```
let rootView = RCTRootView(
            bundleURL: jsCodeLocation,
            moduleName: "RNHighScores",
            initialProperties: nil,
            launchOptions: nil
        )
                
        let vc = UIViewController()
        vc.view = rootView
        self.navigationController?.pushViewController(vc, animated: true)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.3.0
| react-native     | ^0.58.5
| node             | 11.9.0
| npm or yarn      |6.7.0
|react-native-gesture-handler|^1.0.16

**Comment by Anhmike** [comment] 2019-02-24 20:01
Have anyone can resolve it? I have the same problem.

**Comment by eriveltonelias** [comment] 2019-02-24 21:27
Hi there,

Duplicate of https://github.com/react-navigation/react-navigation/issues/5440

**Closed by eriveltonelias** 2019-02-24 21:27 UTC

**Comment by CyberMew** [comment] 2019-02-24 23:58
Hi, I think it is a different error from the previous issue. This is a null error instead of undefined. It is already linked properly as per setup instructions. It should work for a new install, if not, the instructions need to change. I think there is something more that I am missing. I will try to upload a mcve if I have the time.

**Comment by eriveltonelias** [comment] 2019-02-25 00:08
hi @CyberMew, 

if you think that is a different issue, post a new issue with a reproducible example, please. I'll be happy to investigate it.

**Comment by Anhmike** [comment] 2019-02-25 20:19
The issue is not yet resolved for  Android. You had only resolve with IOS.  I follow the instruction as on https://reactnavigation.org/docs/en/getting-started.html.

So other Android guys out there must have the same issue as I have. 

The result is Unhandled JS Exception: null is not an object (evaluating 'RNGestureHandlerModule.State'. 

Here are the dependencies and the java files:

  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.5",
    "prop-types": "15.7.2"
    "react-native-screens": "1.0.0-alpha.22"
    "react-native-gesture-handler": "1.0.16",
    "react-navigation":"^3.3.0"
  }

On MainActivity.java

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;


public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "reactnativethird";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}

On MainApplication.java

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

**Comment by Anhmike** [comment] 2019-02-25 21:21
So I see a quick close out on the issue because it wad duplicate and failed to check in with instruction. So convenience of saying these reasons to close out the issue, the remain is we can't get it to work. Please survey your users. Maybe most of the people had no issue are the people using Expo. I am using regular react-native project. There is this guy CyberMew can't seem to get it to work. You have the real issue on hand. Just saying if you want to work on it. Thanks,
