### ISSUE TITLE
proposal: TabNavigator backBehavior: 'historyStack' option remembers history and goes back to actual previous Tab

### ISSUE THREAD

**Issue by faceyspacey** [react-navigation/react-navigation#1545] opened 2017-05-16 22:07 UTC
### Current Behavior
The only option currently is to go back to the initial tab
```js
TabNavigator(RouteConfigs,{
   backBehavior: 'initialRoute'
})
```

### Expected Behavior
I feel like this is kind of a temporary "good enough" solution so that the maintainers can work on higher priority things. Totally makes sense, but a history stack should be maintained so that the Android `BackHandler` can trace your steps back and the like. This is especially important if you you're using another routing package (which maintains its own history stack), which does remember those tab changes. 

Therefore the expected behavior of a more optimized solution would look like this:

```js
TabNavigator(RouteConfigs,{
   backBehavior: 'historyStack'
})
```

And would function *almost* like a browser's history stack. I.e. it keeps an array of all the tabs you tap, and if you go back from one of them, it pops and navigates to the tab corresponding to the new tail entry (similar to the way `StackRouter` is working, it doesn't need to remember the tail of the array like in the browser). And that's it. 

If you were to emulate the exact browser's history stack behavior, you wouldn't pop, and you'd change the index of where you're at in the array, and then when you eventually push a new history entry, you replace the tail entries after the index of the array with just that one new entry plus increment the index + length. *I dont think we gotta do all that.*

**Comment by faceyspacey** [comment] 2017-05-17 20:01
Also note: I personally have built a redux-specific router that I'm transforming to operate as a "master controller router" of React Navigation. It's called: [redux-first-router](https://github.com/faceyspacey/redux-first-router). I've done a lot of work to integrate React Navigation. It focuses on the concept of having multiple disconnected react navigation router "families" and communication between the 2, plus a complete reconciled history stack so things like the `BackHandler` can back out through your complete history. This also includes URL-driven states for non-React_Navigation actions. Basically it's a complete URL-driven solution to your app that picks up where React Navigation leaves off, allowing you to not be confined to just one "Router Family" for URL-driven states and history.

**Comment by satya164** [comment] 2017-12-28 17:02
https://github.com/react-navigation/react-navigation/pull/889

**Comment by satya164** [comment] 2018-01-04 05:28
Duplicate of #678

**Closed by satya164** 2018-01-04 05:28 UTC
Labels: component: Tabs, feature request, related: goBack
