### ISSUE TITLE
When app starts, app crashed on android [React Navigation 5.0.0 Alpha].

### ISSUE THREAD

**Issue by burhanyilmaz** [react-navigation/react-navigation#6267] opened 2019-09-06 13:51 UTC
### Current Behavior
When my app starts, app crashed on Android.
The app is working on IOS.

### Expected Behavior
The app is working on Android and IOS.

**Error Log**
```
AndroidRuntime	FATAL EXCEPTION: mqt_native_modules
Process: com.rnnext, PID: 24380
java.lang.NoClassDefFoundError: com.facebook.react.views.swiperefresh.ReactSwipeRefreshLayout
	at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
	at java.lang.Class.getDexCacheType(Class.java:2551)
	at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
	at java.lang.reflect.Method.getParameterTypes(Method.java:193)
	at java.lang.Class.getDeclaredMethods(Class.java:1812)
	at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:446)
	at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:341)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:124)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:118)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:81)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:68)
	at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:230)
	at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:148)
	at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:95)
	at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:274)
	at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:181)
	at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:142)
	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:187)
	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:155)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:123)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:111)
	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:189)
	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:154)
	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:429)
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:38)
	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1049)
	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1008)
	at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:124)
	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:969)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ClassNotFoundException: com.facebook.react.views.swiperefresh.ReactSwipeRefreshLayout
	at java.lang.VMClassLoader.findLoadedClass(Native Method)
	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
```
### How to reproduce
**package.json**
```
{
  "name": "rnnext",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "postinstall": "jetifier"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.1",
    "@react-navigation/core": "^5.0.0-alpha.8",
    "@react-navigation/native": "^5.0.0-alpha.7",
    "@react-navigation/stack": "^5.0.0-alpha.15",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.2.0",
    "react-native-screens": "^2.0.0-alpha.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.3.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
**App.js** 
```
import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationNativeContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { TouchableOpacity } from 'react-native-gesture-handler';

function HomeScreen({ navigation: { navigate } }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screens</Text>
      <TouchableOpacity onPress={() => navigate('Home1')}>
        <Text>Go to Home1 </Text>
      </TouchableOpacity>
    </View>
  );
}

function HomeScreen1() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screens</Text>
    </View>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationNativeContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Home1" component={HomeScreen1} />
      </Stack.Navigator>
    </NavigationNativeContainer>
  );
}

export default App;

```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5 Alpha
| react-native     | 0.60.5
| react-native -cli    | 2.0.1
| node             | 12.3.1
| yarn      | 1.16.0

**Comment by Martian2Lee** [comment] 2019-09-06 14:06
Same issue!

**Comment by mustafakemalelma** [comment] 2019-09-06 14:09
I am also having this same issue on version 4.0.0

**Comment by burhanyilmaz** [comment] 2019-09-06 14:45
@Martian2Lee @mustafakemalelma 
I found a solution. Problem is related to `react-native-screens`.
When the version is `1.0.0-alpha.23`, the app is work.
```
    "react-native-screens": "1.0.0-alpha.23"
```

**Comment by satya164** [comment] 2019-09-11 19:08
Closing since the solution is posted

**Closed by satya164** 2019-09-11 19:08 UTC

**Comment by f-hoedl** [comment] 2019-09-18 07:45
If I add those 2 dependencies i get this error:

`> Could not find method implementation() for arguments [androidx.appcompat:appcompat:1.1.0-rc01] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

Am I adding it the right way?
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")
        implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
        implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
    }
}
`

**Comment by TopGuo** [comment] 2019-12-02 18:09
the same like issue when i use Native Module

**Comment by TopGuo** [comment] 2019-12-02 18:15
[error log]
2019-12-03 02:14:33.059 14485-14526/com.yoyo_app E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.yoyo_app, PID: 14485
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
        at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:185)
        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
        at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:201)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
2019-12-03 02:14:33.060 14485-14526/com.yoyo_app E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/base.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_resources_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/lib/arm64, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/base.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 22 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.yoyo_app-ahHopjY5x6PUwF04izqfBg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:358)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:407)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:729)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
2019-12-03 02:14:33.060 14485-14526/com.yoyo_app E/AndroidRuntime:     at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5829)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

[package.json]

{
  "name": "yoyo_app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.3",
    "crypto-js": "^3.1.9-1",
    "moment": "^2.24.0",
    "native-base": "^2.13.8",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-iphone-x-helper": "^1.2.1",
    "react-native-router-flux": "^4.0.6",
    "react-native-tab-navigator": "^0.3.4",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-persist": "6.0.0",
    "redux-persist-transform-filter": "^0.0.20"
  },
  "devDependencies": {
    "@babel/core": "^7.7.4",
    "@babel/runtime": "^7.7.4",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.7.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by Ebeldev** [comment] 2019-12-05 18:29
I can build the app in dev mode. But when I build it in production the app keep crashing. 

I added @burhanyilmaz snippet. 

Still the same bug.

**Comment by tfritsch-km** [comment] 2020-02-19 13:05
Hello
thank you @burhanyilmaz !
Shouldn't this be mentioned in the Getting Started section as it was in v4.x documentation ? Any reason why it was not brought back in v5 doc ?
https://reactnavigation.org/docs/en/4.x/getting-started.html#installing-dependencies-into-a-bare-react-native-project

**Comment by Qusain** [comment] 2020-02-19 15:49
> implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
> implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
thanku so much , i solved my problem after 12 hour

**Comment by FrozenIce0617** [comment] 2020-03-02 10:26
> implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
> implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'

Thank you very much, it is very helpful.

**Comment by ykws** [comment] 2020-03-19 14:17
Now stable version

```
implementation 'androidx.appcompat:appcompat:1.1.0'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'
```

🔖 https://mvnrepository.com/artifact/androidx.appcompat/appcompat
🔖 https://mvnrepository.com/artifact/androidx.swiperefreshlayout/swiperefreshlayout

**Comment by tfritsch-km** [comment] 2020-03-26 12:32
> Hello
> thank you @burhanyilmaz !
> Shouldn't this be mentioned in the Getting Started section as it was in v4.x documentation ? Any reason why it was not brought back in v5 doc ?
> https://reactnavigation.org/docs/en/4.x/getting-started.html#installing-dependencies-into-a-bare-react-native-project

Hello @satya164 
sorry to insist but do you have any idea why this step isn't mentioned anymore in docs ? Shouldn't this be written back before closing this issue ?

@ykws thank you for version bump but are you sure swiperefreshlayout@1.0.0 is ok ? previous workaround from @burhanyilmaz used 1.1.0-alpha02 and the link you provided shows there is now a 1.1.0-beta01 version.

**Comment by satya164** [comment] 2020-03-26 12:34
> @tfritsch-km Hello @satya164 sorry to insist but do you have any idea why this step isn't mentioned anymore in docs ? Shouldn't this be written back before closing this issue ?

It's not needed as of the latest version of `react-native-screen`. Make sure you have upgraded to the latest versions and rebuilt your app.

**Comment by tfritsch-km** [comment] 2020-03-26 12:40
thank you for the quick feedback :) I'll try that

**Comment by d8en** [comment] 2020-11-26 19:48
FWIW I had android app crashes on launch and deleteing the 'build' folder and running npx react-native run-android fixed my problem. It took my hours to find someone who suggested that (in addition to the above [dependencies](https://github.com/react-navigation/react-navigation/issues/6267#issuecomment-593331649) suggestion). Maybe I had other issues with my build directory...

**Comment by jaquinocode** [comment] 2022-01-29 04:28
> @Martian2Lee @mustafakemalelma I found a solution. Problem is related to `react-native-screens`.
> 
> Add the following two lines to **dependencies section** in **android/app/build.gradle**.
> 
> ```
> implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
> implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
> ```
> 
> https://github.com/kmagiera/react-native-screens#usage-with-react-navigation-without-expo

This comment's link is now outdated. The link is here now: https://github.com/software-mansion/react-native-screens/tree/2.3.0#usage-with-react-navigation-without-expo
