### ISSUE TITLE
Simple Stack not working

### ISSUE THREAD

**Issue by Derewith** [react-navigation/react-navigation#7797] opened 2020-03-12 18:42 UTC
**Current Behavior**
[This example](https://reactnavigation.org/examples/5.x/simple-stack.js) is not working in [snack.expo.io](snack.expo.io). 
Also all the others examples from the website of react-navigation v5 are not working on a real iOS device.

**Expected Behavior**
To render the navigator

**Comment by Kielan** [comment] 2020-03-16 22:38
please fix the hyperlinks so that this thread does not get archives

**Comment by WoLewicki** [comment] 2020-03-18 16:37
I think it is a duplicate of #7807, so I am closing it. Tell me please if I am wrong.

**Closed by WoLewicki** 2020-03-18 16:37 UTC
Labels: bug, package:stack

**Comment by Derewith** [comment] 2020-03-18 23:42
Mine was started before.. btw ok

**Comment by WoLewicki** [comment] 2020-03-19 09:20
True, it's my mistake, sorry. Also, #7807 seems to better describe the exact bug.
