### ISSUE TITLE
`gestureEnabled: true` does not work on `presentation: fullScreenModal` screens on iPad

### ISSUE THREAD

**Issue by bradleyflood** [react-navigation/react-navigation#10913] opened 2022-10-06 00:31 UTC
### Current behavior

When creating a modal screen using screen options `presentation: 'fullScreenModal'` (as opposed to `presentation: 'modal`) the swipe to dismiss gestures do not work. Even when `gestureEnabled: true` and `gestureDirection: 'vertical'` screen options are set.

NOTE: The swipe gestures DO work correctly when using `presentation: 'modal'`, but as soon as you change the `presentation` value to `fullScreenModal` all swipe gestures stop working, regardless of other gesture options set.

Tested in iOS simulator and real **iPad**.

### Expected behavior

The`presentation: 'fullScreenModal'`screen should respond to swipe gestures as per the configured screen options. Just like a regular `presentation: 'modal'` screen does on iOS.

👀**NOTE:** The need for `fullScreenModal` is made clear when using an iPad. On a iPhone there is no distinguishable difference between `modal` and `fullScreenModal`. But when using an iPad you will see that a regular `modal` screen is rather small, only filling about 50% of the screen, and shows much of the screen behind it. This is often not ideal. Where as `fullScreenModal` is, obviously, full screen.

## Example of Full Screen Modal with Swipe Down Gesture...
The "Player" screen in Apple Music is a full screen modal with swipe down gesture. I want to replicate this.

![IMG_DD268E20951E-1](https://user-images.githubusercontent.com/1085976/194187110-85a1b462-5ae5-4fcf-b8a2-52054ca32c07.jpeg)

### Reproduction

https://github.com/bradleyflood/react-navigation/tree/main/example

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13 |
| @react-navigation/bottom-tabs          |6.4.0|
| @react-navigation/native-stack                |6.8.0|
| react-native-safe-area-context         |4.4.1|
| react-native-screens                   |3.17.0|
| react-native-gesture-handler           |2.6.2|
| react-native-reanimated                |2.10.0|
| react-native                           |0.70.2|
| node                                   |16
| npm or yarn                            |yarn

**Comment by bradleyflood** [comment] 2022-10-06 00:35
> The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link, a [www.typescriptlang.org/play](https://www.typescriptlang.org/play) link or link to a GitHub repo under your username).

Yes it does. I provided the link in the Issue form and it's there above. It is in my username too.

**Comment by dylancom** [comment] 2022-10-12 08:44
@bradleyflood had the same problem and the way I solved it is by removing `presentation: 'fullScreenModal'` and adding: `gestureDirection: 'vertical'`. This seems to add a bunch of different options automatically such as `animation: slide_from_bottom`. The only problem I now have, is that when you finish swiping it will suddenly animate very fast to the bottom or top.

**Comment by bradleyflood** [comment] 2022-10-13 04:30
Thanks @dylancom. Yes adding `gestureDirection: 'vertical'` does automatically add other options, this is specified in [the docs here](https://reactnavigation.org/docs/native-stack-navigator#gesturedirection).

> When using `vertical` option, options `fullScreenGestureEnabled: true`, `customAnimationOnGesture: true` and `animation: 'slide_from_bottom'` are set by default.

However, if you have removed the `presentation` value then you won't be getting a `fullScreenModal`, just the regular `modal`.

![Screen Shot 2022-10-13 at 14 19 52](https://user-images.githubusercontent.com/1085976/195501761-c79ef5ca-9be1-4e1d-9d9a-3b3a5633a3c4.jpg)

As you can see from this screenshot of my app using the latest `react-navigation`, the regular `modal` on an iPad is thin and short, and it does not occupy the whole screen.

My problem still remains in that using `fullScreenModal` means the gestures do not work. `gestureEnabled` and `gestureDirection`, do nothing and you can't swipe to close the full screen modal, like you could with a regular modal.

**Comment by dylancom** [comment] 2022-10-13 07:00
Ah I see, I solely tested on an iPhone.
The problem is that the underlying package "react-native-screens" maps the "fullScreenModal" to [UIModalPresentationFullScreen](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/uimodalpresentationfullscreen) which has no support for swipe gestures. It would need a custom implementation of a modal.

**Comment by bradleyflood** [comment] 2022-10-13 11:23
Ahh ok good to know. Thanks @dylancom 

I'm guessing this might need to become a feature request then, rather than a big report. 

Either way we need to update the docs because this isn't clear.

**Comment by bradleyflood** [comment] 2022-11-13 03:28
This is still an issue. And the repro is attached. Thank you.

**Comment by bradleyflood** [comment] 2022-12-12 01:18
Thanks @branaust but see my note in the original post...
> 👀NOTE: The need for fullScreenModal is made clear when using an iPad. On a iPhone there is no distinguishable difference between modal and fullScreenModal.

This is an iPad issue. Do you get the same in the iPad simulator?

**Comment by kacperkapusciak** [comment] 2022-12-14 11:29
By Apple's design full screen modals can't be closed by a gesture and it's not a bug 

Unfortunately, the feature from your screenshot (the Apple music one) isn't implemented in `react-native-screens`. Based on [this video from WWDC21](https://developer.apple.com/videos/play/wwdc2021/10063/) probably [this property](https://developer.apple.com/documentation/uikit/uisheetpresentationcontroller/3801905-prefersedgeattachedincompactheig) on a `formSheet` would make that work.

Closest that you can get with the current state of native-stack is by using the `gestureDirection: 'vertical'` property:


https://user-images.githubusercontent.com/39658211/207579268-f409f5d2-85cf-4d06-a64d-1f3bd08fb396.mov

<details>
<summary>Code Snippet</summary>
<br>


```jsx
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import * as React from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';

function HomeScreen({ navigation }) {
  return (
    <View
      style={{
        ...styles.container,
        backgroundColor: 'palevioletred',
      }}
    >
      <Text>Home Screen</Text>
      <Button
        title="Go to Details"
        onPress={() => navigation.navigate('Details')}
      />
    </View>
  );
}

function DetailsScreen() {
  return (
    <View
      style={{
        ...styles.container,
        backgroundColor: 'tomato',
      }}
    >
      <Text>Details Screen</Text>
    </View>
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen
          name="Details"
          component={DetailsScreen}
          options={{
            gestureDirection: 'vertical',
            headerShown: false,
          }}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default App;

```


</details>

I encourge you to open a feature request on `react-native-screens` repo

Cheers

**Closed by kacperkapusciak** 2022-12-14 11:29 UTC
Labels: bug, needs repro, library:react-native-screens, platform:ios

**Comment by AndonMitev** [comment] 2023-01-16 08:51
Hey i'm facing this issue on Android, modals are simply not closing using `"react-native-screens": "3.15.0"` is anyone manage to resolve it?

**Comment by abdulmateentechbits** [comment] 2024-09-01 15:11
+1 for android  here is my code
i have just remove the presentation option still not working


 ```
<Stack.Screen name="player" options={{
          gestureEnabled: true,
          gestureDirection: 'vertical',
          animationDuration: 400,
          headerShown: false,
          animation:"slide_from_bottom"
        }} />
        
        dependencies:{
          "@react-navigation/native": "^6.0.2",
          "react-native": "0.74.5",
          "expo": "~51.0.28",
          "expo-router": "~3.5.23",
          "react-native-gesture-handler": "~2.16.1",
          .... others
      }

```
