### ISSUE TITLE
On first mount of app, Drawer buttons are clickable even when its closed for some time.

### ISSUE THREAD

**Issue by adiwon9555** [react-navigation/react-navigation#7945] opened 2020-04-03 15:22 UTC
**Current Behavior**

React Navigation 5

If user Taps on screen just after he opens app, buttons of Drawer screens are clicked even when drawer is closed.

This is for atleat 2 -  3 seconds after app is first mounted.

**Comment by satya164** [comment] 2020-05-06 14:40
Closing since you didn't follow the issue template.

**Closed by satya164** 2020-05-06 14:40 UTC
Labels: bug, needs more info, package:drawer

**Comment by kkirby** [comment] 2020-05-06 21:16
Also having this issue. There's not much more information that I personally can provide. It's happening on Android, and possibly iOS too.

**Comment by raajnadar** [comment] 2020-05-07 02:36
@kkirby but you should at least provide a runnable repro to check the issue.

**Comment by kkirby** [comment] 2020-05-07 15:38
> @kkirby but you should at least provide a runnable repro to check the issue.

I actually haven’t been able to reproduce this one myself yet. Our QA team and PM brought it to my attention. When I find the cause or find a minimal reproducible app I’ll update you.
