### ISSUE TITLE
NavigationActions.reset is bug?

### ISSUE THREAD

**Issue by fadeli1** [react-navigation/react-navigation#5322] opened 2018-12-03 03:29 UTC
### Current Behavior

1、app.js -> global.myValue = 15;
2、login.js -> componentDidMount{global.myValue = 8;} 
3、click login -> NavigationActions.reset -> 
```
		let resetAction = NavigationActions.reset({
			index: 0,
			actions: [
				NavigationActions.navigate({routeName: 'IndexScreen'}),
			]
		});
		this.props.navigation.dispatch(resetAction);
```
4、index.js -> componentDidMount{global.myValue = 9;} 
5、last result myValue value 8 

Its actual logic is：
1. run NavigationActions.reset
2. index.js->componentDidMount
3. login.js -> componentDidMount

How can I make myValue equal to 9?

### Expected Behavior

1、app.js -> global.myValue = 15;
2、login.js -> componentDidMount{global.myValue = 8;} 
3、click login -> NavigationActions.reset -> 
```
		let resetAction = NavigationActions.reset({
			index: 0,
			actions: [
				NavigationActions.navigate({routeName: 'IndexScreen'}),
			]
		});
		this.props.navigation.dispatch(resetAction);
```
4、index.js -> componentDidMount{global.myValue = 9;} 
5、last result myValue value 9

### How to reproduce

https://snack.expo.io/@ok13135tu7/navigation-test-reset

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.5
| react-native         | 0.55.2
| node                    | 9.5.0
| npm                     | 6.4.1
| android                | 7.1.2

**Comment by eriveltonelias** [comment] 2018-12-07 00:57
Hi @fadeli1! 

you're using a so old version of `react-navigation` ( 1.5.11)  try to update to the last ( 3.0.5 ) and tell me if that works as expected.

**Comment by brentvatne** [comment] 2018-12-07 02:33
we don't provide support for version 1.x anymore so if this can't be reproduced in the latest version we should close the issue :)

**Comment by fadeli1** [comment] 2018-12-07 05:35
thank you very much, the latest version, there is no such problem @eriveltonelias @brentvatne

**Comment by fadeli1** [comment] 2018-12-07 06:17
@eriveltonelias @brentvatne 
Sorry, I got it wrong.
I will be the latest version of react-navigation update and still have the problem.
Reproduce:
https://snack.expo.io/@ok13135tu7/navigation-test-reset

**Comment by wbowlin** [comment] 2019-01-07 00:39
@fadeli1 Looking at your example, the components are mounting in the order you expect.  However, the render() method in React executes before componentDidMount().  

See this for lifecycle order: https://reactjs.org/docs/react-component.html#mounting

The componentDidMount() method in index executes after render() has run, but then nothing forces the index component to re-render.  I created a new version of your example to show it is correct by forcing a render.

To say another way, what you are seeing is:

1、app.js -> global.myValue = 15;
2、login.js -> componentDidMount{global.myValue = 8;}
3、click login -> NavigationActions.reset ->
4、index.js -> render() -> global.myValue is still 8 so it renders 8
5、index.js -> componentDidMount{global.myValue = 9;}
6、component does not re-render because its props and state were not updated (this is the issue)

Heres a fork of your snack that forces a render in componentDidMount() of index, showing that the value is indeed set to 9.

https://snack.expo.io/SJbK1QgfN

**Comment by fadeli1** [comment] 2019-01-07 10:42
@wbowlin 
Thank you for your answer, I think I understand

**Closed** 2019-01-12 18:55 UTC
