### ISSUE TITLE
[WEB] browser back button handling is broken

### ISSUE THREAD

**Issue by pruski** [react-navigation/react-navigation#10263] opened 2022-01-14 07:58 UTC
### Current behavior

Whenever the initial screen is reached, the rest of the history gets wiped out. Eg. when you navigate to:
FirstScreen -> HomeScreen -> SecondScreen and start going back with browser button, you won't be able to go back to FirstScreen. 

What is worse, if your browser tab has a longer history, you will get out of the app unexpectedly, eg:
google.com -> FirstScreen -> HomeScreen -> SecondScreen -back-> HomeScreen -back-> google.com

Pasting minimal example below, it's `App.js` of freshly `expo init`-ed app.

```
import { Text, View, Pressable } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

const Stack = createStackNavigator();

const HomeScreen = ({navigation}) => {
  return <View>
    <Pressable onPress={() => {navigation.navigate('FirstScreen')}}>
      <Text>1. Go to first screen</Text>
    </Pressable>
    <Pressable onPress={() => {navigation.navigate('SecondScreen')}}>
      <Text>2. Go to second screen</Text>
    </Pressable>
  </View>
}

const FirstScreen = ({navigation}) => {
  return <View>
    <Pressable onPress={() => {navigation.navigate('HomeScreen')}}>
      <Text>Go to home screen</Text>
    </Pressable>
  </View>
}

const SecondScreen = ({}) => {
  return <View>
      <Text>Go back to first screen using browser's back button</Text>
  </View>
}

export default function App() {
  return (
    <NavigationContainer linking={{
      config: {
        screens: {
          HomeScreen: '/',
          FirstScreen: '/first',
          SecondScreen: '/second',
        },
      },
    }}>
      <Stack.Navigator screenOptions={{ headerShown: false }}>
        <Stack.Screen name="HomeScreen" component={HomeScreen} />
        <Stack.Screen name="FirstScreen" component={FirstScreen} />
        <Stack.Screen name="SecondScreen" component={SecondScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

### Expected behavior

History is preserved and your able to use browser's forward/back buttons 

### Reproduction

`expo init` and copy-paste the included snippet

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

In the minimal example I used:

@react-navigation/native 6.0.6
@react-navigation/stack 6.0.11

**Comment by conzett** [comment] 2022-01-21 18:25
Experiencing this bug as well and this example demonstrates it perfectly. After running `expo init` I installed the following:
`expo install @react-navigation/native @react-navigation/stack react-native-screens react-native-safe-area-context`
and then pasted the example above into App.js

**Comment by drpiou** [comment] 2022-01-26 10:39
Hi there! I'm also experiencing this issue. I dig a bit using `screenListeners` to debug the state, and I think I know why the back button does not work, but then I don't know why the state behave weirdly:

1. I navigate across many screens that are NOT the same, here is the `state.routes`:
```
routes: Array(5)
0: {name: 'Screen1', params: {…}, path: '/en/screen-1-path/:key', key: 'Screen1-0j9w8TTL1I6SIKW5rRGkz'}
1: {key: 'Screen2-jngi-6O_6W6X1V8qjZxHm', name: 'Screen2', path: undefined, params: undefined}
2: {key: 'Screen3-7s_Q0ovXUNE71n-z_RzE0', name: 'Screen3', path: undefined, params: undefined}
3: {key: 'Screen4-KcxCUzXG3-_Gjf65T9sJz', name: 'Screen4', path: undefined, params: undefined}
4: {key: 'Screen5-XRNnW0DqGwLZ2t9VFAns9', name: 'Screen5', path: undefined, params: {…}}
```

Here I can see:
- something created the first route not the same way something else is adding next routes
- `path` is always `undefined` except for the first route (idk if `path` is needed then, or if it is a bug...)

2. When I navigate FORWARD (not `goBack` but `push`) on a screen I already navigated, like "Screen2", here is the `state.routes`:
```
routes: Array(2)
0: {name: 'Screen1', params: {…}, path: '/en/screen-1-path/:key', key: 'Screen1-0j9w8TTL1I6SIKW5rRGkz'}
1: {key: 'Screen2-jngi-6O_6W6X1V8qjZxHm', name: 'Screen2', path: undefined, params: undefined}
```

Here I expect:
```
routes: Array(6)
0: {key: 'Screen1-0j9w8TTL1I6SIKW5rRGkz', name: 'Screen1', path: '/en/screen-1-path/:key', params: {…}}
1: {key: 'Screen2-jngi-6O_6W6X1V8qjZxHm', name: 'Screen2', path: '/en/screen-2-path', params: undefined}
2: {key: 'Screen3-7s_Q0ovXUNE71n-z_RzE0', name: 'Screen3', path: '/en/screen-3-path', params: undefined}
3: {key: 'Screen4-KcxCUzXG3-_Gjf65T9sJz', name: 'Screen4', path: '/en/screen-4-path', params: undefined}
4: {key: 'Screen5-XRNnW0DqGwLZ2t9VFAns9', name: 'Screen5', path: '/en/screen-5-path/:key', params: {…}}
5: {key: 'Screen2-somenewhash', name: 'Screen2', path: '/en/screen-2-path', params: undefined}
```

So from there, if I navigate somewhere to end up on the same page than the landing one, I just can't go back at all because I have no screens to navigate back to. On my opinion, this is a bug, and this is breaking our navigation flow.

**ALSO**

If i navigate on many screens that shares the same path, then going back ignores every in between routes.

1. I navigate from my landing screen to the next screen (let's say "/en/page/aaa"):
```
routes: Array(2)
0: {name: 'Screen1', path: '/en', key: 'Screen1-ZLuIcdkf7rS8qfIzzmrtM', params: undefined}
1:
key: "Screen2-SJlKITZtZeKPVwFwHplEG"
name: "Screen2"
params: {id: 'my-id-1'}
path: undefined
```

2. Then I navigate from to the next screen (let's say "/en/page/bbb"):
```
routes: Array(2)
0: {name: 'Screen1', path: '/en', key: 'Screen1-ZLuIcdkf7rS8qfIzzmrtM', params: undefined}
1:
key: "Screen2-SJlKITZtZeKPVwFwHplEG"
name: "Screen2"
params: {id: 'my-id-2'}
path: undefined
```

Here I can see:
- the second screen got replaced by the third screen

Here I expect:
```
routes: Array(3)
0: {name: 'Screen1', path: '/en', key: 'Screen1-ZLuIcdkf7rS8qfIzzmrtM', params: undefined}
1:
key: "Screen2-SJlKITZtZeKPVwFwHplEG"
name: "Screen2"
params: {id: 'my-id-1'}
path: undefined
2:
key: "Screen2-somenewhash"
name: "Screen2"
params: {id: 'my-id-2'}
path: undefined
```

So from here, when I go back from the third screen, I go back to the landing page directly instead of going back to the second screen.

**Comment by conzett** [comment] 2022-01-27 18:59
We're seeing the same issues as @drpiou when debugging (thank you for the great write-up btw!). We were hoping that two recently merged related issues would either resolve or help make this easier to debug but that hasn't been the case. Testing against the main branch locally with @pruski's provided example unfortunately still yields the same results.

For reference

#9128
#10186

**Comment by drpiou** [comment] 2022-01-31 09:42
Is there any ETA on this? I work for a company and we have an app that is in production... I upgraded our RN app with the latest Expo version (bare workflow) the past weeks and we were using react-native-navigation for native and react-router-dom for web. Because react-native-navigation installation is not compatible with the latest Expo (override MainActivity for a non-MainActivity extended class in Android), I then refactored both side of our app with only react-navigation. But I need to know if we (and I forever) drop react-navigation or should I wait just a couple of days for a fix to be pushed?

**Comment by drpiou** [comment] 2022-02-01 15:20
Here is my workaround (maybe this is intended to be done that way, but please correct me if I'm doing something that will push me into a wall), right now this is the only solution I figured out:

I have a `root.ts`:
```
import { CommonActions, createNavigationContainerRef } from '@react-navigation/native';
import { takeWhile } from 'lodash';

type ScreenName = 'Screen1' | 'Screen2'; // mentioned as this just to understand the context of my code

...

export const navigationRef = createNavigationContainerRef();

export function doAction(callee: Parameters<NavigationRef['dispatch']>[0]): void {
  if (navigationRef.isReady()) {
    navigationRef.dispatch(callee);
  }
}

/**
 * Instead of invoking "CommonActions.navigate(...)", I'm using "reset" and add
 * the next route object to the current "state.routes" and specifying "stale: false"
 * (just because I don't want react-navigator to fix anything - again, I am not sure about the "stale",
 * but react-navigator set that to false also so I make sure it stays false ¯\_(ツ)_/¯)
 * /
export function navigate(name: ScreenName, params: any): void {
  doAction((state) => {
    const routes = [...state.routes, { name, params }];

    return CommonActions.reset({
      ...state,
      routes,
      index: routes.length - 1,
      stale: false,
    });
  });
}

export function reset(name: ScreenName, params: any): void {
  doAction(() => CommonActions.reset({ routes: [{ name, params }] }));
}

export function canGoBack(): boolean {
  return navigationRef.canGoBack();
}

export function goBack(): void {
  doAction(() => CommonActions.goBack());
}

export function goBackTo(name: ScreenName): void {
  doAction((state) => {
    const routes = takeWhile(state.routes, { name });

    return CommonActions.reset({
      ...state,
      routes,
      index: routes.length - 1,
      stale: false,
    });
  });
}
```

Here is the usage:
```
import { navigate } from '@/lib/Navigator/root';

...

const handleClick = (): void => {
  navigate('Screen2', { id: 1 });
}

// Later...

const handleClick = (): void => {
  navigate('Screen2', { id: 2 });
}

...
```

And I have in the end:
```
state:
  index: 2
  key: "stack-DjfunRsf4usChDxxg8F26"
  routeNames: (37) ['...']
  routes: Array(3)
    0:
    key: "Screen1-alKsa081kmKA9nnFYZrPx"
    name: "Files"
    params: undefined
    path: "/en"
    1:
    key: "Screen2-euzHczfgiTphSY_W0XTpy"
    name: "FilesCategories"
    params: {id: 1}
    2:
    key: "Screen2-FFHkRKE0FIFooI22aLpeK"
    name: "FilesCategories"
    params: {id: 2}
  stale: false
  type: "stack"
```

...which the back button behave as expected by going back through each screen.

**Comment by CarlosHdez** [comment] 2022-02-11 20:53
I've tried @drpiou's workaround and seems to work fine, but I noticed that it has problems when dealing with nested navigators, in my case I have a Stack inside a Drawer, while navigating in the stack everything works as expected but not with the Drawer.

**Comment by drpiou** [comment] 2022-02-11 21:02
Yes you are certainly right, in my case I don’t have nested navigators so I didn’t tested that use-case, sorry I should have mentioned that.

**Comment by CarlosHdez** [comment] 2022-02-11 21:04
No problem, I added it in case someone also tries it.
In any case this is a very useful workaround, I'll poke around and if I come up with a solution I'll share it here

**Comment by conzett** [comment] 2022-02-15 17:23
Workaround does work for a single navigator for us as well, but we're in the same position as @CarlosHdez just with multiple nested stacks.

This issue should also have the "needs repro" tag removed as it has been reproduced by multiple people with executable examples here.

**Comment by CarlosHdez** [comment] 2022-02-22 17:08
After looking deeper I think I found two possible explanations as to why this is happening (for Drawer and Tab routers at least)
First, whenever navigating between drawer items, once the new route is defined [Tab Router on line 120](https://github.com/react-navigation/react-navigation/blob/16f3462fb258e7e1264d3eb3f4f6c3a93381e01e/packages/routers/src/TabRouter.tsx#L120) does this
```
 if (backBehavior === 'history') {
    const currentKey = state.routes[index].key;

    history = state.history
      .filter((it) => (it.type === 'route' ? it.key !== currentKey : false))
      .concat({ type: TYPE_ROUTE, key: currentKey });
 }
```

Effectively removing items from the navigator history and this will eventually cause some other problems
In my example I have two routes, I had navigated from Screen1 to Screen2 resulting in a state with something like this
```
{
  history: [
    {type: 'route', key: 'Screen1_oMQzABaTEyYuwldTFjm'},
    {type: 'route', key: 'Screen2-G0I3-ygQTX-IhaGxnQlDQ'}
  ]
  index: 1
}
```
The new history created in that line mentioned at TabRouter is
```
 [
   {type: 'route', key: 'Screen2-G0I3-ygQTX-IhaGxnQlDQ'},
   {type: 'route', key: 'Screen1_oMQzABaTEyYuwldTFjm'}
 ]
```
Instead of adding Screen1 again, it removed all history before that route and then added the new path (consistent with what drpiou found. This later causes a second issue when actually modifying the browser history.

On [useLinking.tsx](https://github.com/react-navigation/react-navigation/blob/16f3462fb258e7e1264d3eb3f4f6c3a93381e01e/packages/native/src/useLinking.tsx#L569) at line 531 there's a function called every time the state changes and then triggers a change in the browser history.
And from line 569 it's this
```
    const historyDelta =
      (focusedState.history
        ? focusedState.history.length
        : focusedState.routes.length) -
      (previousFocusedState.history
        ? previousFocusedState.history.length
        : previousFocusedState.routes.length);

    if (historyDelta > 0) {
      // If history length is increased, we should pushState
      // Note that path might not actually change here, for example, drawer open should pushState
      history.push({ path, state });
    } else if (historyDelta < 0) {
      // If history length is decreased, i.e. entries were removed, we want to go back

      const nextIndex = history.backIndex({ path });
      const currentIndex = history.index;

      try {
        if (nextIndex !== -1 && nextIndex < currentIndex) {
          // An existing entry for this path exists and it's less than current index, go back to that
          await history.go(nextIndex - currentIndex);
        } else {
          // We couldn't find an existing entry to go back to, so we'll go back by the delta
          // This won't be correct if multiple routes were pushed in one go before
          // Usually this shouldn't happen and this is a fallback for that
          await history.go(historyDelta);
        }

        // Store the updated state as well as fix the path if incorrect
        history.replace({ path, state });
      } catch (e) {
        // The navigation was interrupted
      }
    } else {
      // If history length is unchanged, we want to replaceState
      history.replace({ path, state });
    }
 ```
 It is checking changes in the state history, if the new history is bigger, it pushes the new path, if it's smaller it uses `history.go` to the active path, removing previous paths. The problem comes when they are the same length, as in this example, because it is doing a `replace` and now if I do a `back` using the browser button the history is not what I would be expecting.
 
 Hopefully this brings some light to the issue, sadly I don't have the time to dive even deeper and make actual changes since there might be some other cases where `replace` is the way to go and I'm not aware of those.

**Comment by mikehardy** [comment] 2022-02-22 17:44
@satya164 there is some example code here and a really in-depth code analysis on a subtle back / history issue - you may be able to snipe this one given the information or at minimum you might have the context on this bit:

> there might be some other cases where [state history] replace is the way to go and I'm not aware of those.

**Comment by CarlosHdez** [comment] 2022-03-14 18:11
After some more exploration found another workaround.
I noticed that it was possible to keep the drawer's store history synced with the browser's by using a custom store like this.
```
const CustomRouter = (options) => {
	const router = DrawerRouter(options);

	return {
		...router,
		getStateForAction(state, action, options) {
			switch (action.type) {
				case 'NAVIGATE': {
				        // Get the state the normal NAVIGATE action would produce (this results in an unreliable state.history
					const result = router.getStateForAction(state, action, options);
					if (!result) {
						return null;
					}
					const route = state.routes[result.index ?? 0];
					// Make sure the history array has a new element for the newest route visited 
					const newState = {
						...result,
						history: [
							...state.history,
							{
								type: TYPE_ROUTE,
								key: `${route.name}-${nanoid()}`
							}
						]
					};
					// Closes the drawer after navigation, on mobile
					if (result !== null && result.index !== state.index) {
						return {
							...newState,
							history: newState.history.filter((it) => it.type !== 'drawer'),
						};
					}
					return newState;
				}
				default:
					return router.getStateForAction(state, action, options);
			}
		}
	};
};
```

A couple of caveats from this solution:
- Since it's not possible to simply pass a new router to a Navigator, a [Custom Navigator](https://reactnavigation.org/docs/custom-navigators) is required and since I'm not modifying the existing Drawer one, I had to copy/paste code from [this](https://github.com/react-navigation/react-navigation/blob/main/packages/drawer/src/navigators/createDrawerNavigator.tsx) file but replacing line 114 with this custom router ( a nice feature to request would be to add the possibility to provide custom routers to existing navigators)
- This is highly based on my requirements so I suggest reviewing the override of the `navigate` action.
- This was not tested against nested navigators so don't know if other problems will show up.

**Comment by conzett** [comment] 2022-04-14 02:14
This has been reproduced many times with different examples - not stale. How can we bring this to the maintainer's attention or at a minimum get the "needs repro" tag removed?

**Comment by mikehardy** [comment] 2022-04-14 02:50
Maybe post a snack that shows it? At least on react-native-paper a bot sees the snack and removes the label. 
Judging from commit activity @satya164 is the person we need to give it a look, but also judging from the commit activity they are very busy! Is there a PR related to this already? I don't see one linked, that's the very best way to get attention + get it resolved

**Comment by CarlosHdez** [comment] 2022-04-14 02:53
I'd love to give a PR, sadly I've also been a bit busy

**Comment by conzett** [comment] 2022-04-14 14:46
> Maybe post a snack that shows it? At least on react-native-paper a bot sees the snack and removes the label.

@mikehardy Apologies, I could have sworn someone had already done so but it doesn't look like it! I've made one here using @pruski's code:

https://snack.expo.dev/ooJOXuwPX

> Is there a PR related to this already? I don't see one linked, that's the very best way to get attention + get it resolved

Totally understand everyone being busy and appreciate all the work that has gone into this! We have set aside time previously for this issue and worked to get a PR ready but it's been difficult to debug and we're not sure exactly what the behavior is supposed to be. It really felt like we needed the input or guidance of a maintainer or core contributor before continuing to sink more time into it, if that makes sense.

**Comment by sreuter** [comment] 2022-06-09 03:56
Running into this since upgrading to Expo SDK45, likely because we also bumped react-navigation to a newer version as part of this. So it seems to be a regression. Maybe we can pinpoint which release of react-navigation introduced this behaviour.

**Comment by danielyaa5** [comment] 2022-06-14 02:10
Also having this issue sdk 45

**Comment by sreuter** [comment] 2022-06-15 10:03
@satya164 Could you have a look at this? This is becoming a massive issue for many, with no good workaround available at the moment. A repro has also been provided.

**Comment by hirvesh** [comment] 2022-06-29 06:04
Observing the same behaviour as reported.

**Comment by satya164** [comment] 2022-06-29 14:37
After reading all the comments, this isn't a bug. This looks like a misunderstanding of how `navigate` works.

The [`navigate`](https://reactnavigation.org/docs/navigation-actions/#navigate) action can act as both adding a new screen, or going back depending on the scenario. If you call `navigate('ScreenName')` and the screen exists in the history, it'll go back to the screen in history (equivalent to calling `navigation.goBack`). This is documented behavior and has existed since React Navigation 2.0. The browser's history is updated accordingly - entries are removed since you're going back.

If this isn't the behavior you want, and you always want to add a new screen, there are 2 options:
- Use `push` instead of `navigate` which will always add a new screen and won't go back to an existing screen
- Use the [`getId`](https://reactnavigation.org/docs/screen/#getid) prop on `Screen` to add a new screen when necessary

@CarlosHdez please open a new issue for the tabs/drawer. It's different from the original issue.

**Closed by satya164** 2022-06-29 14:37 UTC
Labels: bug, platform:web, package:stack, repro provided

**Comment by danielyaa5** [comment] 2022-07-12 21:14
@satya164 Can you provide some more help here. Specifically how would we get traditional back behavior when clicking on tabs?

**Comment by JBaczuk** [comment] 2022-07-12 22:03
> After reading all the comments, this isn't a bug. This looks like a misunderstanding of how `navigate` works.
> 
> The [`navigate`](https://reactnavigation.org/docs/navigation-actions/#navigate) action can act as both adding a new screen, or going back depending on the scenario. If you call `navigate('ScreenName')` and the screen exists in the history, it'll go back to the screen in history (equivalent to calling `navigation.goBack`). This is documented behavior and has existed since React Navigation 2.0. The browser's history is updated accordingly - entries are removed since you're going back.
> 
> If this isn't the behavior you want, and you always want to add a new screen, there are 2 options:
> 
> * Use `push` instead of `navigate` which will always add a new screen and won't go back to an existing screen
> * Use the [`getId`](https://reactnavigation.org/docs/screen/#getid) prop on `Screen` to add a new screen when necessary
> 
> @CarlosHdez please open a new issue for the tabs/drawer. It's different from the original issue.

Where exactly is this documented? I don't see this behavior explained on this page: https://reactrouter.com/docs/en/v6/hooks/use-navigate

**Comment by JamesHemery** [comment] 2022-12-09 18:03
Any news to solve this problem ?

**Comment by edkimmel** [comment] 2024-10-22 23:44
> After reading all the comments, this isn't a bug. This looks like a misunderstanding of how `navigate` works.
> 
> The [`navigate`](https://reactnavigation.org/docs/navigation-actions/#navigate) action can act as both adding a new screen, or going back depending on the scenario. If you call `navigate('ScreenName')` and the screen exists in the history, it'll go back to the screen in history (equivalent to calling `navigation.goBack`). This is documented behavior and has existed since React Navigation 2.0. The browser's history is updated accordingly - entries are removed since you're going back.
> 
> If this isn't the behavior you want, and you always want to add a new screen, there are 2 options:
> 
> * Use `push` instead of `navigate` which will always add a new screen and won't go back to an existing screen
> * Use the [`getId`](https://reactnavigation.org/docs/screen/#getid) prop on `Screen` to add a new screen when necessary
> 
> @CarlosHdez please open a new issue for the tabs/drawer. It's different from the original issue.

Note: this comment is incorrect for 6.x.  Push still looks up the existing screen by ID and will reuse it if found in the back stack.  Changing getID to be always unique causes the back button to create a new page on back, erasing any state captured in the components including scroll positions.

The push action can be patched to not do this ID lookup, or I believe this behavior has been removed in 7.
