### ISSUE TITLE
react-native-tab-view (material-top-tabs) indicator not scroll with page in new architecture 

### ISSUE THREAD

**Issue by dengcqw** [react-navigation/react-navigation#12052] opened 2024-07-08 12:45 UTC
### Current behavior

https://github.com/react-navigation/react-navigation/assets/679859/8b36d5c6-1057-4cf3-b777-fddec9274e41

### Expected behavior

--

### Reproduction

--

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |6.6.13
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by JuGit-pk** [comment] 2024-07-19 07:38
i am facing the same issue, i tried with some things, but still having this issue.

**Comment by dev-ugurkontel** [comment] 2024-07-20 17:31
Same problem in new architecture.

**Comment by dev-ugurkontel** [comment] 2024-07-20 17:32
I encountered the same problem in the new architecture and I'm still looking for a solution.
[package.json](https://github.com/user-attachments/files/16321809/package.json)

**Comment by alextbogdanov** [comment] 2024-07-29 07:47
Same issue here!

**Comment by satya164** [comment] 2024-07-29 12:53
Duplicate of #10932

**Closed by satya164** 2024-07-29 12:53 UTC
Labels: bug, needs repro, platform:android
