### ISSUE TITLE
cardStyle: { backgroundColor: 'transparent' } turns background black in ios

### ISSUE THREAD

**Issue by jasekiw** [react-navigation/react-navigation#4759] opened 2018-07-24 20:11 UTC
### Current Behavior

- The background of a screen is black on ios. On android is it transparent

### Expected Behavior

- The background should be transparent

### How to reproduce
Add `cardStyle: { backgroundColor: 'transparent' }` to your createStackNavigator config.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.1
| react-native     | 0.55.2
| node                | 8.11.1
| npm                 | 5.8.0

I am relying on this to show a background image behind all of my screens. It works fine on android and the image shows through but it is black on ios.

**Comment by brentvatne** [comment] 2018-07-25 04:32
i'm closing this issue because we don't say anywhere that we support this behavior and it's not something we are interested in supporting. i am very curious about your use case though and open to being convinced, will reopen if so.

**Closed by brentvatne** 2018-07-25 04:32 UTC

**Comment by jasekiw** [comment] 2018-07-25 13:22
@brentvatne Here is a design that I have been tasked to implement. I would show more pages but this is for a client.

As you can see there is a background image behind the screen. This same image stays behind all the pages of the app.  

![mockup](https://user-images.githubusercontent.com/4037224/43202492-a870efd4-8fe9-11e8-96c7-7d16199b6f5c.png)

I've tried a work around by applying the image to every page but in ios the image displays gray while loading. On every page change the image would then turn gray and back to the image again as it reloads the image.

The current work around is to add `transitionConfig: () => ({containerStyle: {}})` to the `createStackNavigator` config. Although this is a work around I would like to propose this to be officially supported because designs like this are not uncommon.

The only issue that having a transparent background causes is that the contents slightly overlap on the page change animation. I am okay with this as it doesn't look too bad and it only happens for a very short amount of time.

Here are some other closed issues of users who also want this feature 
https://github.com/react-navigation/react-navigation/issues/2713
https://github.com/react-navigation/react-navigation/issues/3803

#3803 You mentioned got moved to a feature request but with no link. 

I'd like to keep this open until we merge a pr in.

What are your thoughts?

**Comment by compojoom** [comment] 2018-08-04 14:28
@jasekiw - would you mind explaining what you did exactly. I'm having a modal and I want the modal to have a transparent background, but I'm failing. 

I have this modal:
```
  const MainAppNavigator = createStackNavigator(
    {
      Main: {
        screen: MainStack,
      },
      latestActivitiesCalendar: {
        screen: LatestActivitiesCalendar
      },
      shareOptions: {
        screen: ShareOptions
      }
    },
    {
      mode: 'modal',
      headerMode: 'none',
      cardStyle: {backgroundColor: 'transparent'},
      transitionConfig: () => ({
        containerStyle: {
        }
      }),
    }
  )
```

when the modal transitions I have a transparent background, but once the animation finishes, the background becomes gray (the default one from stackView)

<img width="397" alt="grafik" src="https://user-images.githubusercontent.com/693770/43677507-a0b83782-980b-11e8-930a-eaf73934fb16.png">

the gray background needs to be transparent.

@brentvatne - why are you guys not interested in this? This is a very common pattern to have a some options at the bottom of the screen and dismiss it when clicking in the transparent part.

**Comment by marcosmartinez7** [comment] 2018-08-14 20:32
@brentvatne

for me seems a really common use case

supose that you want to set a imagebackground or a lineargradient as a background of all your screens

yo can do it screen by screen, but altering the styling of your react components, but it will not take the Header part of the drawer, only the scene.. so the scene will take a color and the drawer header another.. 

also, for iphone X, maybe you want to put your content into a SafeArea, and the rest of the view that is not part of the safe area must be able to be styled.. 

i think that the problem is that the styles that applies to the Scenes dindt apply to the drawer header..

i dont know if you understand my example, if you dont let me know and i will came up with an example 

kind regards
marcos

**Comment by esanguinetti** [comment] 2018-08-14 21:57
@brentvatne 
I need to add support for iPhone X layout.
I have a Higher Order Component with a custom Background, which varies according to the view, and a SafeAreaView wrapping the navigator.
I have the same issue as @jasekiw is working on Android but not on IOS.
Could you consider reopening the issue?
I am using react-navigation version 2.11.2 
Regards 
Elisa

**Comment by Leeds-eBooks** [comment] 2018-08-15 09:29
@compojoom I have just encountered your problem as well – the apparent grey background that appears to animate in after the new screen has finished transitioning into view is actually because **the underneath-view is animating to `opacity: 0`**. I wonder why this was decided? I suppose it's to make the transitions look more native-like.

To fix this, you just need to set `opacity: 1` in the `cardStyle`. So, currently, the whole solution to have transparent screens is:

```js
{
  cardStyle: {
    backgroundColor: 'transparent',
    opacity: 1,
  },
  transitionConfig: () => ({
    containerStyle: {
      backgroundColor: 'transparent',
    },
  })
}
```

If it helps the team decide to make this easier and more futureproof, my use case is modals with a nice blurview background, still showing through some of the underlying view. Hardly an edge case!

**Comment by compojoom** [comment] 2018-08-16 10:54
@Leeds-eBooks - thanks! Can't believe I missed the opacity. That solves my case as well.

**Comment by brentvatne** [comment] 2018-08-21 18:48
what people are wanting here is a modal navigator that works differently from stack. we definitely want to support this and you can discuss more in https://github.com/react-navigation/rfcs/issues/15

**Comment by bang88** [comment] 2018-09-26 09:52
I want change the card backgroundColor dynamically. eg. If I have changed from Theme A to Theme B and then I need the card's BackgroundColor changes too.

```
transitionConfig: () => ({
    containerStyle: {
      backgroundColor: 'transparent',
    },
  })
``` 
If I change my stack configurations like above it works but have another problem If we go back or go to another screen the screen is transparent when transitioning.

**Comment by brentvatne** [comment] 2018-09-26 15:16
the latest version of react-navigation (2.17.0) has a config option for this: https://github.com/react-navigation/react-navigation-stack/commit/a380437f354ab05be0932c826e9c0e8a6bd59147

**Comment by bang88** [comment] 2018-09-27 01:28
Does this means that I should set backgroundColor for each screen instead of set it for root view only.

```tsx
        <ThemeProvider value={theme}>
          <View
            style={{ flex: 1, backgroundColor: theme.containerBackgroundColor }}
          >
            <StateGuard
              onAppAlive={() => {
                // ios
                clearBadge()
              }}
            />
            <RootApp screenProps={{ theme }} />
          </View>
        </ThemeProvider>
```

**Comment by brentvatne** [comment] 2018-09-29 19:47
@bang88 - yes

**Comment by sapjax** [comment] 2018-11-30 10:44
> @bang88 - yes

I still need to add `opacity:1` in `cardStyle`, otherwise it's not transparent, even though I set the `transparentCard: true`,  this only happend on Android.

**Comment by JKillian** [comment] 2019-02-12 18:43
I hit the same issue as @sapjax; I also had to add `cardStyle: { opacity: 1 }` in order to get `transparentCard` to work correctly on Android.

**Comment by euroclydon37** [comment] 2019-04-18 19:34
Ran into this. But when I set `cardStyle: { opacity: 1 }`, the card doesn't transition in the way it used to. It just snaps onscreen.

**Comment by jhoanborges** [comment] 2019-07-17 21:22
same issue.

**Comment by MonkeyMoneyFrance** [comment] 2019-08-01 14:04
try this : 
    headerMode: 'none',
    mode: 'modal',
    transparentCard: true,
    navigationOptions: {
      header : null,
      gesturesEnabled: false
    },
    cardStyle: {
      // makes transparentCard work for android
      opacity: 1.0
    },

**Comment by simonbq** [comment] 2019-09-26 18:06
> Ran into this, today. But when I set `cardStyle: { opacity: 1 }`, the card doesn't transition in the way it used to. It just snaps onscreen.

Same here as of today.

**Comment by ColinaLozito** [comment] 2019-10-10 16:29
for me work only adding `transparentCard: true, `
like this 

```
{
    mode: "modal",
    transparentCard: true,
    cardStyle: {
      backgroundColor: "transparent"
    },
    transitionConfig: () => ({
      screenInterpolator: mytransition
    })
  
```

**Comment by spsaucier-bakkt** [comment] 2020-02-14 20:31
The best solution for me is in their docs now: https://reactnavigation.org/docs/en/stack-navigator.html#transparent-modals

**Comment by stefantrinh1** [comment] 2021-02-08 03:40
I tried a few things on here none worked for me. I wanted a linear gradient on ever page. I tried to put this in the parent component and make the background transparent. this did not work for me. drove me insane.

I found cardOverlay in the doc and made a component in that and sent iot back using zIndex behind everything and did some css to make it appear on the background

`
// screenOptions
  cardOverlayEnabled: true,
  cardOverlay: () => (
    <LinearGradient
      // Background Linear Gradient
      colors={['red', 'blue']}
      style={styles.background}
    />
  ),
  cardStyle: {
    backgroundColor: 'transparent',
    opacity: 1,
  },

// styles
const styles = StyleSheet.create({
  background: {
    position: 'absolute',
    left: -100,
    right: 0,
    top: 0,
    bottom: 0,
    height: 700,
    zIndex: -10,
  },
})
`

**Comment by ghasemikasra39** [comment] 2021-12-08 11:01
I am using react-navigation **6** and have a nested tab navigator with:
```javascript
sceneContainerStyle={{
            backgroundColor: 'transparent',
          }}
```

and its parent stack navigator with:
```javascript
options={{
   cardStyle: {backgroundColor: 'transparent'},
   presentation: 'transparentModal'
              }}
```

But the background is still not transparent.

**Comment by smccamley** [comment] 2024-07-31 20:56
One common use case for this is to have the navigation UI vary independently of the content.
Check out the app the Tesla built and demoed at the latest Expo and react event.

Their content is a 3D animation that changes independently of the navigation and the 3D view is mounted behind the Nav component. We do a similar thing in our app.

Expo supports it out of the box. But Expo's ability to edit the transition spec of the navigator is buggy and a little restrictive. It would be great if you guys could make this work easily.
