### ISSUE TITLE
The Drawer in ReactNavigation is not smooth

### ISSUE THREAD

**Issue by caelmeCj** [react-navigation/react-navigation#5659] opened 2019-03-06 04:48 UTC
When opening, the drawer is not very smooth, there is some kind of pause before being completely opened or closed. A perf problem I guess. Is there anyone who also faces this issue? Have you fixed it? Or is there another way to avoid that?

What I use is:
"react": "16.6.3",
"react-native": "0.57.8",
"react-navigation": "^3.3.0",
"react-native-gesture-handler": "^1.0.16"

**Comment by eriveltonelias** [comment] 2019-03-06 10:09
hey there,

duplicate of https://github.com/react-navigation/react-navigation/issues/5287

**Closed by eriveltonelias** 2019-03-06 10:09 UTC
