### ISSUE TITLE
onStateChange triggered twice when the drawer opened

### ISSUE THREAD

**Issue by Chan-picle** [react-navigation/react-navigation#10599] opened 2022-05-18 08:34 UTC
### Current behavior

onStateChange triggered twice when the drawer opened. This doesn't always appear in all drawers, but it definitely appears on some drawers in my app. Has anyone encountered this problem?

### Expected behavior

onStateChange triggered once when state changed

### Reproduction

 onStateChange={async () => {//}}

### Platform

- [X] Android
- [X] iOS
- [ ] Web

### Packages

- [X] react-navigation-​drawer
- [ ] react-navigation-​stack
- [ ] react-navigation-​tabs

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| react-navigation                       | 5.9.3
| react-native                           | 0.63.4

**Comment by bviebahn** [comment] 2022-05-19 03:41
I encounter the same issue when navigating using `useLinkTo`. `onStateChange` is called twice with exactly the same state.

"@react-navigation/core": "^6.2.1"
"@react-navigation/native": "^6.0.10"

**Comment by TheMiksa** [comment] 2022-05-20 18:43
Hey there! I have same issue(
my repo can  demonstrate the issue:
https://github.com/TheMiksa/FriendsChat

**Comment by jeffcad** [comment] 2022-05-22 01:05
Is this related to the problem with the drawer sometimes hesitating/double-taking when trying to bring it out? It has something to do with the latest versions of react-native-reanimated. I solved it by using the legacy implementation prop from the docs.

**Comment by kacperkapusciak** [comment] 2022-06-23 14:36
Hi @TheMiksa, @jeffcad 
Could you upgrade the drawer to the newest version (v6.4.2) and check if the issue still occurs?

Cheers

**Comment by jeffcad** [comment] 2022-06-23 21:08
@kacperkapusciak I think the problem is fixed with 6.4.2. I removed the useLegacyImplementation prop and tried about 200 times to bring out the drawer, and did not see any trouble. I used to have a problem about 1 in every 5 times, so I'm confident that it works. Thanks for your attention!

**Comment by martincalvert** [comment] 2022-06-27 03:21
Can confirm as well my drawer toggling issues were resolved by upgrading the following:
```
react-navigation/native@6.0.8 => 6.0.10
react-navigation/drawer@6.3.1 => 6.4.2 
```

**Comment by kacperkapusciak** [comment] 2022-06-27 09:57
Thanks!

**Closed by kacperkapusciak** 2022-06-27 09:57 UTC
Labels: bug, platform:android, platform:ios, version-4, repro provided
