### ISSUE TITLE
TabNavigator issuse with rtl 

### ISSUE THREAD

**Issue by bhram** [react-navigation/react-navigation#3318] opened 2018-01-21 07:33 UTC
hi all , 
i have issuse with application support rtl

I18nManager.forceRTL(true);
I18nManager.allowRTL(true);

the tabs not selected correctly when swipe , i try to disable swipe in tabs 
    swipeEnabled: false,

but the tabs page no showing up when click on it ? 

| software         | version
| ---------------- | -------
| react-navigation  |  1.0.0-beta.25
| react-native      | 0.52.0
| node             | v8.9.3
| npm or yarn      | yarn

**Comment by kelset** [comment] 2018-01-22 09:32
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-22 09:32 UTC
