### ISSUE TITLE
HeaderRight and HeaderLeft header Navigation option hidden

### ISSUE THREAD

**Issue by bwoodlt** [react-navigation/react-navigation#3263] opened 2018-01-12 11:00 UTC
I'm using react-navigation headerRight and headerLeft option and passing TouchableOpacity to the buttons. But strangely enough, when an onPress is added to the TouchableOpacity button, it hides the button. This issue exist on in Android. Have tried everything possible.

Has anyone experienced this issue? Any idea how to resolve? Thanks!

**Comment by kelset** [comment] 2018-01-12 11:54
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-12 11:54 UTC
