### ISSUE TITLE
RouteName is changed but Screen is not changed.

### ISSUE THREAD

**Issue by kkotkkio** [react-navigation/react-navigation#3621] opened 2018-02-28 07:19 UTC
Process is "RootStackNavigator -> Some Navigator -> Display Some Screen"

Entire code of RootNavigation
```
import {Notifications} from 'expo';
import React from 'react';
import {StackNavigator} from 'react-navigation';
import {connect} from 'react-redux';
import JoinNavigator from './JoinNavigator';
import MainTabNavigator from './MainTabNavigator';

const RootStackNavigatorWrap = (initialRouteName) => {
  const RootStackNavigator = StackNavigator(
    {
      Main: {
        screen: MainTabNavigator,
      },
      Join: {
        screen: JoinNavigator,
      }
    },
    {
      ...initialRouteName,
      navigationOptions: ({ navigation }) => ({
        header: null
      }),
    }
  );
  return <RootStackNavigator/>
};

export class RootNavigator extends React.Component {

  constructor(props) {
    super(props)
  }

  state = {
  };

  componentWillMount() {
    console.log(this.props.app.initialRouteName);
    //This display 'Join'
  }

  render() {
    return <RootStackNavigatorWrap initialRouteName={this.props.app.initialRouteName}/>;
  }

  _handleNotification = ({origin, data}) => {
    console.log(`Push notification ${origin} with data: ${JSON.stringify(data)}`);
  };
}

const mapStateToProps = ({user, app}) => {
  return {'user' : user, 'app' : app};
};
export default connect(mapStateToProps)(RootNavigator)
```

Entire code of some child navigator (Join Navigator)
```
import React from 'react';
import IntroScreen from '../screens/join/IntroScreen';
import LoginScreen from '../screens/join/LoginScreen';
import RegisterScreen from '../screens/join/RegisterScreen';
import RegisterEmailScreen from '../screens/join/RegisterEmailScreen';
import AskStep1 from '../screens/join/AskStep1';
import AskStep2 from '../screens/join/AskStep2';
import AskStep3 from '../screens/join/AskStep3';
import AskStep4 from '../screens/join/AskStep4';
import {StackNavigator} from 'react-navigation';
import {connect} from 'react-redux'
import {hiddenStatusBar} from '../actions'

const JoinStackNavigator = StackNavigator(
  {
    Intro: {
      screen: IntroScreen
    },
    Register: {
      screen: RegisterScreen
    },
    RegisterEmail: {
      screen: ({ navigation }) => <RegisterEmailScreen screenProps={{ rootNavigation: navigation }} />
    },
    Login: {
      screen: LoginScreen
    },
    AskStep1: {
      screen: AskStep1
    },
    AskStep2: {
      screen: AskStep2
    },
    AskStep3: {
      screen: AskStep3
    },
    AskStep4: {
      screen: AskStep4
    },
    AskStep5: {
      screen: AskStep1
    },
    AskStep6: {
      screen: AskStep1
    }
  },
  {
    initialRouteName: 'RegisterEmail',
    navigationOptions: ({navigation}) => ({
      header: null
    })
  }
);

export class JoinNavigator extends React.Component {

  render() {
    return (
      <JoinStackNavigator
        onNavigationStateChange={(prevState, currentState) => {
          this._getCurrentRouteName(currentState)
        }}
      />
    );
  }

  _getCurrentRouteName(navState) {
    if (navState.hasOwnProperty('index')) {
      this._getCurrentRouteName(navState.routes[navState.index])
    } else {
      console.log("Current Route Name:", navState.routeName);
      let regExp = /^AskStep/;
      if(navState.routeName.match(regExp)){
        this.props.hiddenStatusBar();
      }
    }
  }

}

const mapStateToProps = ({app}) => {
  return app;
};

const mapDispatchToProps = dispatch => {
  return {
    hiddenStatusBar: () => {
      dispatch(hiddenStatusBar(true))
    }
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(JoinNavigator);
```

So, InitialRouteName is RegisterEmail.
Summary to entire code RegisterEmail.

```
import React from 'react';
import {Platform, View, TextInput, StyleSheet, Text, Dimensions, TouchableOpacity, Keyboard} from 'react-native';
import {Button} from 'react-native-elements';
import {connect} from 'react-redux'
import ScaleImage from 'react-native-scalable-image';
import {scale, moderateScale, verticalScale} from '../../utils/scaling';
import CustomHeader from '../../components/CustomHeader';
import {MaterialCommunityIcons, Feather, MaterialIcons} from '@expo/vector-icons';
import {KeyboardAwareScrollView} from 'react-native-keyboard-aware-scroll-view'
import { firebaseLogin, hiddenStatusBar } from '../../actions'

export class LoginScreen extends React.Component {

  static navigationOptions = {
    header: null
  };

  constructor(props) {
    super(props);
  }

  _onPressJoin = () => {
    //Go next
    this.props.screenProps.rootNavigation.navigate('AskStep1');
  };

  render() {
    return (
      <View style={s.container}>
          <Button
            title="Next Button"
            onPress={this._onPressJoin}/>
      </View>
    );

  }
}

function mapStateToProps({ app }) {
  const { hiddenStatusBar } = app;
  return { hiddenStatusBar };
};

export default connect(mapStateToProps)(LoginScreen)
```

First, "this.props.navigate('AskStep1');" is not working.
This is changed routeName but real screen is not changed.

So, I tried to pass rootNavigation in screenProps  like this
"this.props.screenProps.rootNavigation.navigate('AskStep1');"

But this is same. 

Why do you think this is?
Help needs.. Thank you..

### My Environment

{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "test": "node ./node_modules/jest/bin/jest.js --watch"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "expo": "^25.0.0",
    "firebase": "^4.10.1",
    "moment": "^2.20.1",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-native-awesome-alerts": "^1.0.6",
    "react-native-elastic-image-slider": "^1.0.0",
    "react-native-elements": "^0.19.0",
    "react-native-gifted-chat": "^0.3.0",
    "react-native-image-zoom-viewer": "^2.0.18",
    "react-native-keyboard-aware-scroll-view": "^0.4.4",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-responsive-grid": "^0.40.6",
    "react-native-scalable-image": "^0.2.2",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-swiper": "^1.5.13",
    "react-navigation": "^1.0.0-beta.27",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "jest-expo": "^25.0.0",
    "redux-devtools": "^3.4.1"
  }
}

**Comment by matthamil** [comment] 2018-02-28 15:49
:wave: Hello! Thanks for the issue, and sorry you are experiencing issues. As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, we require that you provide a runnable example that reproduces the bug on [Snack](https://snack.expo.io) or in a separate repository. Please try to minimize the extraneous code and focus on reproducing the bug.

We're closing any issues that do not have reproducible examples. Do not take this personally :). 

Please create a new issue with a reproducible example and one of the maintainers/collaborators would be glad to look at it!

If you find that your issue is due to redux, please file an issue at https://github.com/react-navigation/react-navigation-redux-helpers.

**Closed by matthamil** 2018-02-28 15:49 UTC
