### ISSUE TITLE
DrawerNavigation embedded in StackNavigator sometimes allows stack "back" gesture (video)

### ISSUE THREAD

**Issue by ryanvanderpol** [react-navigation/react-navigation#1908] opened 2017-06-16 20:38 UTC
### Current Behavior
I have the following navigation structure:

```
StackNavigator
  - SplashScreen (component)
  - LoginScreen (component)
  -  MainNavigator (DrawerNavigator)
    - HomeScreen (StackNavigator)
      - ChildScreen (component)
    - SecondaryHomeScreen (StackNavigator)
      - SecondaryChildScreenScreen (component)
```

So, the flow for the user is that they see the splash screen first, then the login screen.  After logging in, they are directed into the main part of the app.  the main part of the app consists of two screens that are each `StackNavigators`, contained within a `DrawerNavigator`.  The idea here is that when you're at the "root" screens you can navigate around with the drawer menu, but once you start interacting with one of those "root" screens you get into a stack and have to use the "back" function to get out to access the drawer again.

This works pretty well for the most part, but occasionally when on one of the "root" screens, the swipe gesture pops me back to `LoginScreen` instead of opening the drawer.  See this video:

![react-navigation-drawer](https://user-images.githubusercontent.com/1936460/27243528-5e62ec3e-52b0-11e7-81f4-b5a0fef2b12e.gif)

Here you can see the sequence from `SplashScreen` --> `LoginScreen` --> `HomeScreen` --> `ChatScreen`  and backwards.  The first time I use the swipe gesture from the `HomeScreen`, the drawer opens up as expected. The second time, you can see the drawer opens up but it appears like a screen and when the drawer opens fully, it actually pops me back to `LoginScreen`

### Expected Behavior

When using the swipe back gesture on a `DrawerNavigator` screen the drawer should always open up and it should never pop back in the stack.

### Your Environment

"react": "16.0.0-alpha.6",
"react-native": "^0.44.0",
"react-navigation": "^1.0.0-beta.11"

**Comment by ryanvanderpol** [comment] 2017-06-24 15:37
This is happening to me very consistently.  Am I doing something wrong?  How do I prevent the back gesture on the `DrawerNavigator` from popping the top card off the stack?  

I'm going to have to move to a different navigation module if I can't resolve this.

**Comment by amanthegreatone** [comment] 2017-06-25 20:56
https://github.com/react-community/react-navigation/issues/156

**Comment by kelset** [comment] 2017-11-12 11:24
Pinging OP @ryanvanderpol  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by KPSoftec** [comment] 2017-11-14 12:44
Hey kelset 

I m using react native versions as follows:-
    "react": "16.0.0-beta.5",
    "react-native": "^0.49.5",
    "react-navigation": "^1.0.0-beta.15"

I'm also facing the same issue with my solution as well....

I m facing problem with Drawer navigation and stack navigation
i have two screens (Screen-A and Screen-B ) and there routes are defined in both the navigation stack 
Drawer as well as Stack
and both the screens have menu button on their nav-header...

but when i navigate to Screen-B from Screen-A via drawer navigation, then on Screen-B drawer is available and getting open via menu button...

but when i navigate from screen -A to Screen-B via button available on Screen-A using stack navigation, then on menu button click the drawer doesn't gets open in-place of that it navigate to back i.e Screen-A....

Any solution to solve this and make these two navigation's work parallel..

**Comment by KPSoftec** [comment] 2017-11-14 13:08
what i found is.


There should be a separate routes for drawer navigation and stack navigation.

By doing this drawer works fine and forward flow of application also works fine. 

But when i m trying to go back in drawer navigation it doesn't works.


Lets Say, 


There are 5 screens 
A ,B, C, D, E


A is Login
 
B is Home 

C is Profile 

D is Share
 
E is Logout
 


Stack routes contains 
Screen A and D


Drawer routes contains remaining screens.

Now the flow is 

A-> B-> C-> D
 works fine


A-> B-> C-> D-> C not works it moves to B as B is the first screen on Drawer navigation....

If you add B, C, D in stack routes then drawer won't get open in B, C, D... but going back functionality works fine as routes are inside stack.

**Comment by KPSoftec** [comment] 2017-11-16 05:59
here you will find yours solution
basically you need to define routes in screens as they are needed

here is the solution attached....
try it once
[Learning.zip](https://github.com/react-community/react-navigation/files/1477460/Learning.zip)

**Comment by danieloprado** [comment] 2018-03-16 12:34
Any updates or workaround?

When I try to navigate from Welcome (outside the drawer) to Event (inside), the app navigate to the initial route of drawer (Home) instead of Event. The verison 1.0.0-beta.21 works perfectly.

My navigator:
```ts
const appDrawer = DrawerNavigator({
  Home: { screen: HomePage },
  Profile: { screen: ProfileDetails },
  Informative: { screen: InformativeListPage },
  Event: { screen: EventListPage },
  ChurchReport: { screen: ChurchReportListPage },
  Church: { screen: ChurchPage },
  Dev: { screen: DevPage },
}, {
    initialRouteName: 'Home',
    contentComponent: SideMenu,
    contentOptions: {
      inactiveTintColor: 'black',
      activeTintColor: variables.accent,
      ...(variables.platform === 'ios' ? {
        activeBackgroundColor: variables.toolbarDefaultBg
      } : {})
    }
  });

export const Navigator: NavigationContainer = StackNavigator({
  Welcome: { screen: WelcomePage },
  Home: { screen: appDrawer },
  Profile: { screen: appDrawer },
  ProfileEdit: { screen: ProfileEditPage },
  Informative: { screen: appDrawer },
  InformativeDetails: { screen: InformativeDetailsPage },
  Event: { screen: appDrawer },
  EventDetails: { screen: EventDetailsPage },
  ChurchReport: { screen: appDrawer },
  ChurchReportForm: { screen: ChurchReportFormPage },
  Church: { screen: appDrawer },
  Dev: { screen: appDrawer }
}, {
    headerMode: 'none',
    initialRouteName: 'Welcome',
  });
```

Welcome.tsx
```ts
 this.navigation.navigate('Event');
```
Event from onNavigationChange
```json
{
  "key": "StackRouterRoot",
  "isTransitioning": false,
  "index": 1,
  "routes": [
    {
      "routeName": "Welcome",
      "key": "id-1521203423638-0"
    },
    {
      "routes": [
        {
          "routes": [
            {
              "key": "Home",
              "routeName": "Home"
            },
            {
              "key": "Profile",
              "routeName": "Profile"
            },
            {
              "key": "Informative",
              "routeName": "Informative"
            },
            {
              "key": "Event",
              "routeName": "Event"
            },
            {
              "key": "ChurchReport",
              "routeName": "ChurchReport"
            },
            {
              "key": "Church",
              "routeName": "Church"
            },
            {
              "key": "Dev",
              "routeName": "Dev"
            }
          ],
          "index": 0,
          "isTransitioning": false,
          "key": "DrawerClose",
          "routeName": "DrawerClose"
        },
        {
          "key": "DrawerOpen",
          "routeName": "DrawerOpen"
        },
        {
          "key": "DrawerToggle",
          "routeName": "DrawerToggle"
        }
      ],
      "index": 0,
      "isTransitioning": false,
      "routeName": "Event",
      "key": "id-1521203423638-1"
    }
  ]
}
```

**Comment by danieloprado** [comment] 2018-03-16 13:09
I've tested all version until 1.2.0, this bug was introduced in 1.2.1.

**Comment by danieloprado** [comment] 2018-03-16 13:10
Maybe here:
https://github.com/react-navigation/react-navigation/commit/8fc8f3b8f78cf80248ddcb1847d78b830a33eb2c

**Comment by brentvatne** [comment] 2018-05-01 00:55
hi all, can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!

**Closed by brentvatne** 2018-05-01 00:55 UTC
Labels: bug, component: Drawer, gesture
