### ISSUE TITLE
Type error when passing component with params

### ISSUE THREAD

**Issue by EricMcRay** [react-navigation/react-navigation#7012] opened 2020-01-10 13:42 UTC
I am getting `Type 'NavigationParams' is not assignable to type 'Params'.` error when I create component with `NavigationStackScreenComponent<Params>` like:

```
const SomeScreen: NavigationStackScreenComponent<Params> = (props) => { ... }

createStackNavigator({ some: SomeScreen })
```

I think there is wrong typing on `createStackNavigator`. On 'StackNavigationProp' parameters should be any to prevent fallback to default values which cause a mismatch. Line reference:

https://github.com/react-navigation/stack/blob/1621f5495a8408ef336caebb47c4787e460f83b4/src/navigators/createStackNavigator.tsx#L19

**Comment by satya164** [comment] 2020-03-17 09:11
Duplicate of #6516

**Closed by satya164** 2020-03-17 09:11 UTC
Labels: package:stack, version-4
