### ISSUE TITLE
Stack navigation is having component re-rendering issue 

### ISSUE THREAD

**Issue by Pradeep-DCPL** [react-navigation/react-navigation#3227] opened 2018-01-05 08:34 UTC
Hi All,

We are using the stack navigation for the first time and we are facing the issue that it re-render the component for multiple time.

**React-native version -** 0.47.1

**React Navigation version -**  - 1.0.0-beta.15

**Below is the scenario that causing this issue** - For Example we have two screen 'Home' and 'Asset'.

Initially we are on screen 'Home' then we navigate to Screen 'Asset' after that when we come back to screen "Home" then componentDidMount functional of screen "Home" calls for 2 times 

Now Again we did same navigation "Home" to "Asset" and then "Asset" to "Home" after this  componentDidMount functional of screen "Home" calls for 3 times and  it always incremented by one in the same navigation process.

We are using the below code
`const HomeScreenStack = StackNavigator({
    HomeScreen: {
        screen: HomeScreen,
        navigationOptions: ({ navigation }) => ({
            title: 'Home'
        })
    }
})

const AssetScreenStack = StackNavigator({
    AssetContainer: {
        screen: AssetContainer,
        navigationOptions: ({ navigation }) => ({
            title: 'Assets'
        })
    }
})

export const Root = DrawerNavigator(
{
        Home: { screen: HomeScreenStack },
        Asset: { screen: AssetScreenStack },
        },
      {
           initialRouteName: 'LoginScreen',
           drawerWidth: 250,
          drawerBackgroundColor: '#6889bb',
          contentOptions: {
                labelStyle: {
                color: 'white'
            }
        },
        contentComponent: (props) => (
            <ScrollView>
                <DrawerItems ['Home', 'Asset'] />
            </ScrollView>
        )
    }
})`

Our App performance is based on this so your help can do a magic for us. 

Thanks DCPL Team

**Comment by kelset** [comment] 2018-01-05 11:41
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-05 11:41 UTC
