### ISSUE TITLE
Unable to resolve module './DrawerLayout' when using the latest version

### ISSUE THREAD

**Issue by kufii** [react-navigation/react-navigation#5564] opened 2019-02-06 03:39 UTC
When running through expo with version 3.1.4 I get the following error

`Unable to resolve "./DrawerLayout" from "node_modules\react-navigation-drawer\dist\views\DrawerView.js"`

When downgrading to 3.0.9 it works fine.

my package.json dependencies: 
```javascript
  "dependencies": {
    "expo": "^32.0.0",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-action-button": "^2.8.5",
    "react-native-elements": "^1.0.0",
    "react-native-modal": "^7.0.2",
    "react-native-root-toast": "^3.0.2",
    "react-navigation": "^3.1.4",
    "react-navigation-collapsible": "^3.0.3",
    "react-navigation-slide-from-right-transition": "^1.0.4",
    "tcomb-form-native": "^0.6.20"
  }
```

**Comment by brentvatne** [comment] 2019-02-06 04:42
looks like something is being cached in the packager, you'll want to clear that. you can try closing packager and running `expo start -c`, if that doesn't fix it then:
 
`m -rf node_modules && rm package-lock.json && rm yarn.lock`
`npm install` or `yarn`
`expo start -c`

if that doesn't fix it then create a new issue with a reproducible example.

**Closed by brentvatne** 2019-02-06 04:42 UTC

**Comment by ginsan95** [comment] 2019-02-06 12:09
Same, I had this issue as well. I am using not using expo. After clear cache, problem still remains

**Comment by cwagner22** [comment] 2019-02-06 14:39
Same issue, tried clearing everything...

**Comment by c316** [comment] 2019-02-06 15:30
I resolved this by pinning react-navigation to 3.0.9 `"react-navigation": "3.0.9",` in my package.json file. Then doing an `npm install` and starting the app again.

**Comment by cwagner22** [comment] 2019-02-06 16:36
Looks like these commands did the trick for me:
`watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro* && rm -rf $TMPDIR/haste-* && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-`
`rm -rf node_modules && npm install`
`react-native run-ios -- --reset-cache` (Not for Expo)

I also did `Hardare > Reset All Content and Settings` from the ios simulator but I don't think that's the reason.

**Comment by brentvatne** [comment] 2019-02-06 16:48
thanks for sharing @cwagner22!

**Comment by kufii** [comment] 2019-02-06 20:36
@cwagner22 this fixed it for me too, thanks!
