### ISSUE TITLE
Bottom TabBar always visible

### ISSUE THREAD

**Issue by jddk1** [react-navigation/react-navigation#5228] opened 2018-11-12 11:07 UTC
Hello everyone,

I'm using the default "BottomTabNavigator" from "react-navigation", and it is working for what I want at least in some cases. 

My current problem is that I want that BottomTab to be visible in all the application screens, however there are some screens that cannot display this Bottom TabBar. 

I would like to known if I could be missing something that might help me solve this situation?

I as well have tried to get the "BottomTabNavigator" default styles to create my own BottomTabBar, but till now without success (always some configuration missing, to allow a fully own BottomTabBar).

Next, I will write how my app is structured, let me know if the information I provided is clear, or if you might need any other information in order to help?

- DrawerNavigator
  - BottomTabNavigator
    - Stack1
      - Screen1
      - Screen2
    - Stack3
      - Screen3
      - Screen4
    - Stack3
      - Screen5
      - Screen6
  - Stack3
    - Screen3
    - Screen4
  - Stack3
    - Screen5
    - Screen6

Thanks.

**Comment by pzatorski** [comment] 2018-11-12 11:57
Hey @jddk1. It is always good to create the example with https://snack.expo.io/ + information about version of react-navigation which you are using.

If you want to see your BottomTabBar in all the application screens you should place all of the screens under BottomTabBarNavigator.

Following your example:

- DrawerNavigator
  - BottomTabNavigator
    - Stack1
      - Screen1
      - Screen2
    - Stack2
      - Screen3
      - Screen4
    - Stack3
      - Screen5
      - Screen6
    - Stack4
      - Screen7
      - Screen8
    - Stack5
      - Screen9
      - Screen10

If that is not the answer to your question, please correct me.
Thank you

**Comment by jddk1** [comment] 2018-11-12 13:11
Hi @pzatorski , thanks for the tip about the [](https://snack.expo.io/).

Ok, I understand about the use of all screens under the "BottomTabBarNavigator", but in my case, I want to be able to move between them, but I don't want to create an option on "BottomTabBarNavigator" for each of the above "Stacks". 

Explaining better what could solve my problem, it would be something that, even if I have all those stacks on the "BottomTabBarNavigator", I would like to be able to hide some stacks on the BottomTabBarNavigator, while others were visible. Basically be able to specify what stacks I want to be shown on "BottomTabBarNavigator", in spite of it was all stacks within.

There are any options on "BottomTabBarNavigator", that allow me to set the inner stacks to show on Tab or hide them?

Thanks.

**Comment by Shrek53** [comment] 2018-11-14 12:06
I think this is duplicate of #4214

**Comment by eriveltonelias** [comment] 2018-11-14 12:10
Thanks @jddk1 @Shrek53 

and please, read this https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

**Closed by eriveltonelias** 2018-11-14 12:10 UTC
