### ISSUE TITLE
Header "back" arrow sometimes doesn't display on iOS

### ISSUE THREAD

**Issue by farhanmannan** [react-navigation/react-navigation#2918] opened 2017-11-06 19:01 UTC
### Current Behavior
The bug is that the header "back" arrow intermittently doesn't appear (the text still does) in my nested TabNavigator.

Sometimes it seems to pop up once and then when I go "next" and then "back", it's fixed. But sometimes it seems to get "stuck" that way on multiple levels. The button always works though.

The navigators are nested three deep. In the following code snippet I have removed all the irrelevant screens. So I'm concerned about "Learn" and "DailyContent" and "DailyContentStage". It is a bit confusing because DailyContentStage is a top-level component. 

![img_2426](https://user-images.githubusercontent.com/603598/32458408-444dc92e-c324-11e7-90cf-bb9c9c73ca32.jpeg)
![img_2425](https://user-images.githubusercontent.com/603598/32458410-446dbd56-c324-11e7-8cf8-41636781fa07.PNG)

```
// this navigator contains the track tabs: Weight, Steps and Sleep
const LearnTabs = TabNavigator(
  {
    DailyContent: { screen: DailyContentContainer, navigationOptions: { tabBarLabel: 'Daily Content' } },
    Recipes: { screen: RecipesContainer, navigationOptions: { tabBarLabel: 'Recipes' } },
  },
  {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'top',
    initialRouteName: 'DailyContent',
    tabBarOptions: { ...topTabBarOptions },
  },
);

// this navigator contains the track tabs: Weight, Steps and Sleep
const TrackTabs = TabNavigator(
  {
    Weight: { screen: WeightContainer, navigationOptions: { tabBarLabel: 'Weight' } },
    Steps: { screen: StepsContainer, navigationOptions: { tabBarLabel: 'Steps' } },
    Sleep: { screen: SleepContainer, navigationOptions: { tabBarLabel: 'Sleep' } },
  },
  {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'top',
    initialRouteName: 'Weight',
    tabBarOptions: { ...topTabBarOptions },
  },
);

// this navigator contains the main tabs: Home, Track, Chat, Learn, Settings
const MainTabs = TabNavigator(
  {
    Learn: { screen: LearnTabs, navigationOptions: { tabBarLabel: 'Learn' } },
  },
  {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    initialRouteName: 'Home',
  },
);

// this is the top-level app navigator
const AppNavigator = StackNavigator(
  {
    MainTabs: { screen: MainTabs },
    DailyContentStage: { screen: DailyContentStageContainer },  // MainTabs/Learn/DailyContent
  },
  {
    initialRouteName: 'Loading',
  },
);

export default AppNavigator;
```

### Expected Behavior
- Back arrow should always be present as part of back button 
![img_2427](https://user-images.githubusercontent.com/603598/32458388-314cd0cc-c324-11e7-9332-2cd427b471a2.PNG)

I guess it's something to do with the deep nesting but any and all thoughts welcome. Thank you!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.45.1
| node             |  v8.5.0
|  yarn      | 1.0.2

**Comment by kelset** [comment] 2017-11-06 21:34
Hey thanks for reporting.
It looks like you are running an old version of... well, everything. Can you try updating at least our lib? Latest release is `beta.19`

**Comment by farhanmannan** [comment] 2017-11-06 22:35
Ok will update in the morning and see if that fixes it, thanks.

**Comment by farhanmannan** [comment] 2017-11-07 14:35
With beta.19 I still get the same issue (pictured). What is the oldest version of RN you would recommend upgrading to? (My build is broken after trying to go straight to latest) 
![react-navigation beta 19 react-native 0 45 1](https://user-images.githubusercontent.com/603598/32498878-d05fc2ec-c3c8-11e7-9341-5877bfb41751.png)

**Comment by kelset** [comment] 2017-11-07 15:15
I'm currently using 0.49.

**Comment by vance-liu** [comment] 2017-11-08 09:28
Check [this](https://github.com/react-community/react-navigation/blob/6e4afe2153264491838687436899340dfd6ee6a4/src/views/Header/Header.js#L142), same AppNavigator like you @farhanmannan . 
`
    if (props.scene.index === 0) {
          return null;
    }
`
The scene index is aways 0!!!

**Comment by farhanmannan** [comment] 2017-11-08 16:43
Huh, interesting. Thanks @vance-liu ... I usually *do* see the leftComponent / back arrow though... so when it's not coming up, I guess that means the scene index is going wrong. Have you had this issue?

**Comment by vance-liu** [comment] 2017-11-09 02:33
Yep, I have same issue, my AppNavigator just like 
--AppNavigator
    --StackNavigator
        --TabNavigator
        --StackNavigator
        --other StackNavigator
I log the scene 
`
{
  "index": 0,
  "isActive": true,
  "isStale": false,
  "key": "scene_id-1510194470111-4",
  "route": {
    "type": "Navigation/NAVIGATE",
    "routeName": "Main",
    "index": 1,
    "routes": [
      {
        "routes": [
          {
            "key": "Home",
            "routeName": "Home"
          },
          {
            "key": "Me",
            "routeName": "Me"
          }
        ],
        "index": 0,
        "routeName": "HomeNavigator",
        "key": "Init-id-1510194470111-3"
      },
      {
        "key": "id-1510194470111-5",
        "routeName": "Search"
      }
    ],
    "key": "id-1510194470111-4"
  }
}
`
SO that the scene index is always 0. That is a real bug. @farhanmannan @kelset

**Comment by vance-liu** [comment] 2017-11-09 02:44
using
| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.50.3

I test in bata 15, 16, 17, 19, and just 15 is ok.

**Comment by outaTiME** [comment] 2017-11-13 14:02
Hi guys, sometimes the back icon render slows ... this capture is from simulator but the same effect on iPhone device.

im running on expo 22 with last version of react navigation (1.0.0-beta.19)

![screen recording 2017-11-13 at 10 51 am](https://user-images.githubusercontent.com/140472/32729329-0c42da36-c862-11e7-98c4-25d5cfa1617c.gif)

**Comment by alpcoskun** [comment] 2017-12-07 17:38
This is not ios only. I have same bug in Android. The button always works but sometimes its never render.
![screenshot_20171207-203309](https://user-images.githubusercontent.com/17393603/33729296-335f28ce-db8e-11e7-8aeb-6966689c91e3.png)
Device is Samsung Galaxy S6.

**Comment by oliveroneill** [comment] 2017-12-13 11:55
I'm also seeing this issue but only when in 'Release' build of iOS

**Comment by lukewlms** [comment] 2017-12-18 15:12
@kelset Thanks for pointing out the thread.  No solutions in sight here?  This is 100% preventing us from deploying our Android app which is a severe problem for us.

**Comment by lukewlms** [comment] 2017-12-18 15:24
In my testing, the button always works, it's just invisible on my Samsung Galaxy Tab S2 (visible on Pixel emulator).  If I press the region where the button *should* appear, navigate back happens.

However, not having a Back button is still a blocking issue for deploying our app.

**Comment by leecrossley** [comment] 2018-01-17 14:14
As a temporary workaround, you could define your own back button. I have my own conditional logic that shows/hides it. Renders quickly and every time.

```
navigationOptions: (props) => ({
  headerLeft: <Icon
    name="arrow-left"
    onPress={() => { props.navigation.goBack(); }}
  />,
}),
```

**Comment by otaviogaiao** [comment] 2018-01-31 20:43
I'm having the same problem where the back button is rendering slowly on iOS simulator. It's not happening on Android.

**Comment by limianwang** [comment] 2018-04-23 05:48
I am having the same issue, and I'm wondering if anyone had a solution regarding this?

**Comment by otaviogaiao** [comment] 2018-04-23 10:07
@limianwang as stated above, writing my own back arrow component fixed the issue for me

**Comment by limianwang** [comment] 2018-04-23 15:19
@octaviancorlade Ah I see. I was poking around as I was doing debugging, and I also noticed that for some reason, when I used redux, my state wasn't set correctly which caused `props.screen.index === 0`. Once I fixed that, it seems to be better. Still slow, but renders within 1 second.

I'll try to give it my own back arrow. Thanks!

**Comment by bellindj** [comment] 2018-05-05 13:07
@leecrossley thanks for the workaround. Will you expand on how you implemented it? I was hoping I could just plug it into the StackNavigator, but I get an "Element type is invalid" error.

`export const HomeNavigator = StackNavigator({
  Home: {
    screen: HomeScreen
  },
  TaskOverview: {
    screen: TaskOverviewScreen,
    navigationOptions: props => ({
      title: "Task Overview",
      headerLeft: (
        <Icon
          name="arrow-left"
          onPress={() => {
            props.navigation.goBack();
          }}
        />
      )
    })
  },
});`

**Comment by brentvatne** [comment] 2018-05-08 00:10
if you use expo you should include the assets from react-navigation in your `assetBundlePatterns` so the images are bundled with your app when you build a standalone app. the easiest way to do this is to just bundle all assets that your app uses: https://github.com/expo/new-project-template/blob/6d4c5636de573852dfd2f7715cfa152fd9c84f89/app.json#L20-L22. to fix it in development mode within expo, you can cache the assets locally as per [this guide](https://docs.expo.io/versions/v27.0.0/guides/preloading-and-caching-assets). we do this in the navigationplayground example app, so you can copy that code from [here](https://github.com/react-navigation/react-navigation/blob/ec1694f909f895b2be60c5d44b4fb5b278032aff/examples/NavigationPlayground/js/App.js#L171-L178).

if you are not using expo and you have encountered this issue in release mode, please create a new issue and describe how we can reproduce it.

given that we aren't doing anything different here than loading an image (potentially over the network when not bundled with the binary), i'm going to close this issue.

**Closed by brentvatne** 2018-05-08 00:10 UTC
Labels: bug, component: Stack
