### ISSUE TITLE
@react-navigation/drawer doesn't work when debug with react-native-debugger 

### ISSUE THREAD

**Issue by PankoArtem** [react-navigation/react-navigation#10311] opened 2022-01-30 21:01 UTC
### Current behavior

When i choose debug with chrome inside ios simulator I am getting blank screen. but when i stop debugging all content shows as it have to. Also same behaviour if debugger is opened in chrome

### Expected behavior

I expect to have opportunity to use debugger with drawer-navigation

### Reproduction
repo with issue https://github.com/PankoArtem/weatherapp

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [@react-navigation/bottom-tabs
@react-navigation/material-bottom-tabs
@react-navigation/material-top-tabs
@react-navigation/stack] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.7
| @react-navigation/drawer               |6.2.0
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.10.2
| react-native-gesture-handler           |2.2.0
| react-native-reanimated                |2.3.1
| react-native                           |0.67.1
| node                                   |14.7.6
| yarn                            |1.22.17

**Comment by raajnadar** [comment] 2022-01-31 11:59
[Read this](https://reactnavigation.org/docs/troubleshooting/#app-is-not-working-properly-when-connected-to-chrome-debugger)

Check this document first.

**Comment by satya164** [comment] 2022-02-01 06:21
Duplicate of #10253

**Closed by satya164** 2022-02-01 06:21 UTC
Labels: bug, package:drawer, platform:ios, repro provided
