### ISSUE TITLE
NPM Installation Error

### ISSUE THREAD

**Issue by deciomontanhani** [react-navigation/react-navigation#5784] opened 2019-04-06 23:09 UTC
I'm trying to do this:
react-native init SimpleApp
cd SimpleApp
npm install --save react-navigation

And during the npm install, i got this error:

`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-navigation%2fnative - User not found
npm ERR! 404
npm ERR! 404  '@react-navigation/native@~3.3.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-navigation'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

The log file: 
`30 http fetch GET 404 https://registry.npmjs.org/@react-navigation%2fnative 1840ms
31 http fetch GET 404 https://registry.npmjs.org/@react-navigation%2fnative 537ms
32 silly fetchPackageMetaData error for @react-navigation/native@~3.3.0 404 Not Found - GET https://registry.npmjs.org/@react-navigation%2fnative - User not found
`

I tried "npm config set registry https://registry.npmjs.com/" and didn't work.

I don't know what to do, please help thankyou

**Comment by matthamil** [comment] 2019-04-07 16:11
I can't reproduce this. Are you still experiencing this problem @deciomontanhani ?

**Comment by matthamil** [comment] 2019-04-07 16:14
This is likely a problem with your npm CLI. I'm going to close this issue since I cannot reproduce. If you continue to experience this problem, check to see if you can install other packages via npm.

**Closed by matthamil** 2019-04-07 16:14 UTC

**Comment by deciomontanhani** [comment] 2019-04-28 21:04
Hi! Thanks @matthamil , the problem was solved. In my .npmrc file there was some configurations like user credentials, that blocked me to download the packages.
