### ISSUE TITLE
headerTitle re-renders multiple times

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [react-navigation/react-navigation#6220] opened 2019-08-27 12:38 UTC
### Current Behavior

> What code are you running and what is happening?

I'm running a simple code which implements a custom header title (example provided below).
Every time the header gets re-rendered multiple times (2 on the first page, 7 on the second one and 9 on the third page).
It looks the number of re-renders depends on how many pages are in the same stack.

Code:
```import React from 'react';
import { createStackNavigator, createAppContainer } from 'react-navigation';
import { TextInput, TouchableOpacity } from 'react-native';

const PageStack = createStackNavigator(
  {
    Page: ({ navigation }) => <TouchableOpacity style={{ width: 200, height: 200, backgroundColor: 'red' }} onPress={() => navigation.navigate('Page1')} />,
    Page1: ({ navigation }) => <TouchableOpacity style={{ width: 200, height: 200, backgroundColor: 'blue' }} onPress={() => navigation.navigate('Page2')} />,
    Page2: ({ navigation }) => <TouchableOpacity style={{ width: 200, height: 200, backgroundColor: 'green' }} onPress={() => navigation.navigate('Page')} />,
  },
  {
    defaultNavigationOptions: {
      headerTitle: () => console.log('Rendering Header') || <TextInput />,
    },
    initialRouteName: 'Page',
  }
);


const App = createAppContainer(PageStack);
export default App;
```

### Expected Behavior

> What do you expect should be happening?

The header should be rendered once per page.

### Your Environment

| software         | version
| ---------------- | -------
react-navigation | 3.11.0
 react-native | 0.59.10

**Comment by satya164** [comment] 2019-08-27 13:21
You shouldn't care about how many times a component is rendered. Closing since this is expected behavior

**Closed by satya164** 2019-08-27 13:21 UTC
