### ISSUE TITLE
Multiple instances of the same view

### ISSUE THREAD

**Issue by risaac** [react-navigation/react-navigation#6015] opened 2019-06-18 16:25 UTC
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?

What is happening is that I'm navigating away from a screen and when I comeback to that screen I have two instances of the same view running. If I keep navigating away and coming back it starts stacking, I have seen it stack up up to 3+ instances of the same view. How I noticed this is happening is because I have a listener listening for scan events that I'm subscribing on  componentDidMount. Once this event fires all instances of the same view fire off, it becomes hell. Any help or guidance to resolve this issue would be much appreciated. 

Below is my tree structure for the navigation, I added unmountInactiveRoutes to all navigators to see if that would remedy the issue, but it didn't.    

`
const P = createStackNavigator(
  {
    screen1: View,
    screen2: View,
    screen3: View,
    screen4: View
  },
  {
    headerMode: "none",
    navigationOptions: {
      header: "none"
    },
    unmountInactiveRoutes: true
  }
);

const PA = createStackNavigator(
  {
    screen1: View,
    screen2: View,
    screen3: View,
    screen4: View,   
    screen5: View,
    Screen6: View
  },
  {
    headerMode: "none",
    navigationOptions: {
      header: "none"
    },
    unmountInactiveRoutes: true
  }
);

const S = createMaterialBottomTabNavigator(
  {
    T1: {
      screen: View,
      navigationOptions: {
        tabBarIcon: () => <FontAwesome name="" size={24} color="white" />
      }
    },
    T2: {
      screen: View,
      navigationOptions: {
        tabBarIcon: () => <FontAwesome name="" size={24} color="white" />
      }
    }
  },
  {
    initialRouteName: "T1",
    activeColor: "white",
    inactiveColor: "white",
    barStyle: { backgroundColor: "#113751" },
    unmountInactiveRoutes: true
  }
);

const AppScreens = createDrawerNavigator(
  {
    R: { screen: R },
    PA: {
      screen: PA,
      navigationOptions: {
        drawerIcon: () => (
          <FontAwesome name="" size={20} color="#113751" />
        )
      }
    },
    P: {
      screen: P,
      navigationOptions: {
        drawerIcon: () => (
          <FontAwesome name="" size={24} color="#113751" />
        )
      }
    },
    SO: { screen: View },
    PI: {
      screen: PI,
      navigationOptions: {
        drawerIcon: () => {
          return <FontAwesome name="" size={24} color="#113751" />;
        }
      }
    },
    S: {
      screen: S,
      navigationOptions: {
        drawerIcon: () => {
          return <FontAwesome name="" size={24} color="#113751" />;
        }
      }
    },
    Logout: {
      screen: ({ navigation }) => {
        {
          Alert.alert("Message", "Are you sure you want to log out?", [
            {
              text: "Yes",
              onPress: () => {
                navigation.navigate("Auth");
                clean();
              }
            },
            {
              text: "No",
              onPress: () => {
                navigation.goBack();
              }
            }
          ]);
        }
        return (
          <View style={{ flex: 1 }}>
            <SafeAreaView forceInset={{ top: "always", horizontal: "never" }} />
          </View>
        );
      },
      navigationOptions: {
        drawerIcon: () => {
          return <FontAwesome name="" size={24} color="#113751" />;
        }
      }
    }
  },
  {
    initialRouteName: "S",
    drawerPosition: "Left",
    drawerBackgroundColor: "#f5f4f7",
    contentOptions: {
      labelStyle: {
        color: "#113751"
      }
    },
    unmountInactiveRoutes: true
  }
);

const AppNavigator = createSwitchNavigator(
  {
    Auth: AuthView,
    ForgotPass: ForgotPassword,
    NewPass: NewPassword,
    Home: AppScreens
  },
  { unmountInactiveRoutes: true }
);

const AppContainer = createAppContainer(AppNavigator);`

- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?

I expect for the views to have one single instance at all times.  

- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     |0.58.5
| node             |v8.11.2
| yarn      | 1.10.1

**Comment by matthamil** [comment] 2019-06-20 14:21
Can you put your code snippet into a [Snack](https://snack.expo.io/) or in a public repo? Thank you for the snippet you provided, but a runnable example makes it easier for the maintainers to investigate and respond to reports :)

**Comment by eriveltonelias** [comment] 2019-06-30 03:17
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.

**Closed by eriveltonelias** 2019-06-30 03:17 UTC
Labels: needs repro

**Comment by Slapbox** [comment] 2019-07-19 23:24
I'm not clear [if this is the same issue](https://stackoverflow.com/questions/57120564/assign-two-react-navigation-routes-to-the-same-instance-of-the-same-component), but it's very aggravating and confusing. The docs suggest there should only be once instance unless a key is passed.

**Comment by matthamil** [comment] 2019-07-21 00:30
@Slapbox if you are reporting a bug, please open a new issue. Thanks!

**Comment by Slapbox** [comment] 2019-07-21 21:12
@matthamil, can you let me know if I understand the intended behavior so I can be sure I'm reporting a bug and not just misunderstanding? The docs only mention in one place, and I'm 99% sure I'm interpreting it correctly, but maybe not.

**If I point multiple routes to the same component, they should all share one instance of that component, right?** If so, I'll definitely open up a new issue and provide whatever info I can. Thanks @matthamil!

**Comment by satya164** [comment] 2019-07-22 08:50
What do you mean "point multiple routes to the same component"?

Regardless, component instances cannot be shared. So pretty sure you're misunderstanding.

**Comment by risaac** [comment] 2019-07-22 13:19
@matthamil I haven't been able to provide you with an example of the code given my current time constraints and can't post up the current code. I'll try today to create a small example of what I have so you guys can see.

**Comment by Slapbox** [comment] 2019-07-22 19:34
@satya164 what I mean to have two routes that go to the same place, but simply have different labels.

```js
createDrawerNavigator({
  FirstScreen: {
    screen: MyComponent
    },
  SecondScreen: {
    screen: MyComponent
  }
})
```

So I have a component that shows some content and I want to open the same instance of that component (or navigator) on `FirstScreen` and `SecondScreen` in the example above. If component instances can't be shared, I'm definitely misunderstanding, and more than I thought. [In v1, the `key` prop seemed to be used for referencing instances of the same component](https://gist.github.com/vonovak/ef72f5efe1d36742de8968ff6a708985). Is that not possible anymore, or am I misunderstanding what the `key` did in the first place?

I'm sorry that my reply has gotten a bit more expansive than I intended. I definitely don't want this to veer into asking for support, I'm just trying to understand what the intended behavior is so I can determine if this is a bug or not. I was under the impression from the docs that sharing component instances across routes was the default behavior and I was just having trouble, so hearing it's not even possible led me to have some additional questions.

**Comment by matthamil** [comment] 2019-07-22 20:59
What is your use-case for having the same screen for two different route names? @Slapbox

**Comment by satya164** [comment] 2019-07-22 21:57
@Slapbox No it's not going to share the same instance. They are 2 different screens, doesn't matter if you're using the same component or not.

**Comment by Slapbox** [comment] 2019-07-24 20:32
@matthamil the use case is to show the same screen/component with a different set of options passed to the screen, so it can display a different set of data. The component is pretty heavy, especially on mounting.

It's easy enough to trigger that change somewhere else besides the `DrawerItems`, but the UI gets very clunky. I'd just insert my own non-navigation children into the Drawer where I wanted these items, but the position I need them in is in-between two `DrawerItems`, and I'm not sure how I can reference each individual item, since `<DrawerItems />` is a single component and not a set of children I can map over and insert my own items in-between.

I know we're way beyond the scope of the issue tracker and into StackOverflow territory. Since you asked though, I wanted to lay out my use case in case the team feels this might be a common need (or in case I'm overlooking something simple.) 

But if you have any advice, I'd certainly welcome it!

**Comment by satya164** [comment] 2019-07-24 20:39
You should use custom component for drawer which renders few buttons and update the state of your component using an event emitter/redux or something on clicking buttons in the drawer. Don't use multiple screens if all you want is to have filters for the same screen.

If you render 2 components, they are going to be 2 instances even if you refer to the same component function. That's just how React works. Nothing specific to React Navigation.
