### ISSUE TITLE
InputAccessoryView not appearing when using drag to go back.

### ISSUE THREAD

**Issue by hlandao** [react-navigation/react-navigation#8916] opened 2020-09-28 19:31 UTC
**Current Behavior**

- What code are you running and what is happening
Running react-navigation with stack navigation. In some cases when dragging back to a screen with an InputAccessoryView, the InputAccessoryView does not appear. I found out that dragging half-way, releasing, and then dragging again causes the issue. Using `navigation.goBack()` work flawlessly.

I read in iOS forums that it may happen also in native apps, and the way to fix it is to invoke `becomeFirstResponder()` on `viewDidAppear`. However, this is not possible with react-native/react-navigation/react-native-screens.

Has anyone run into a similar issue?
Thanks!

- Include a screenshot or video if it makes sense.
Link to video:
https://drive.google.com/file/d/17YPl9g5SHYzjwUbQk99jmb8sHepdU6Nz/view?usp=sharing

**Expected Behavior**

- What do you expect should be happening?
When going back to a screen with InputAccessoryView, it should always appear.

- Include a screenshot or video if it makes sense.

**How to reproduce**
1. Create stack navigation
2. Create a screen with InputAccessoryView
3. Navigate to another screen
4. Start dragging to go back
5. Don't complete the drag, release and stay on the same screen
6. Drag again and go back
7. You returned to the first screen with the InputAccessoryView but it does not appear

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 |
| @react-navigation/native       |  5.7.5
| @react-navigation/stack        | 5.9.2
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 2.0.1
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| node                           | 12.18.4
| npm or yarn                    | 6.14.6

**Comment by hlandao** [comment] 2020-09-28 19:40
Updated to @react-navigation/native#5.7.5 and @react-navigation/stack#5.9.2 and the bug still repeats.

**Comment by satya164** [comment] 2020-11-28 02:01
Closing since you didn't provide a repro to be able to debug the issue and the provided video isn't accessible. Please open a new issue if you have a minimal repro which I could take a look at.

**Closed by satya164** 2020-11-28 02:01 UTC
Labels: bug, needs repro, package:stack

**Comment by timothyerwin** [comment] 2023-06-24 00:31
@satya164 I can confirm this problem still exists. the inputaccessoryview will disappear when switching stacks and when navigating back it won't reappear. you can see it working correctly in whatsapp for an example.

**Comment by audn** [comment] 2023-12-18 04:01
> @satya164 I can confirm this problem still exists. the inputaccessoryview will disappear when switching stacks and when navigating back it won't reappear. you can see it working correctly in whatsapp for an example.

did you find a fix for this?
