### ISSUE TITLE
[iOS/native-stack] Header shadow not shown if header transparent is true

### ISSUE THREAD

**Issue by alamothe** [react-navigation/react-navigation#10845] opened 2022-09-15 20:39 UTC
### Current behavior

On iOS by default, header shadow is shown, both in iOS apps and in `react-navigation`. 

However, in `react-navigation` when we set that header is transparent:
```tsx
    <Stack.Navigator screenOptions={{
		  headerTransparent: true,
		  headerBlurEffect: "systemChromeMaterialLight",
    }}>
```
Suddenly header shadow is not shown anymore. This is inconsistent with native iOS apps, e.g. iMessage.

### Expected behavior

Whether header shadow is shown or not, should not depend on `headerTransparent` property.

It should be controlled by `headerShadowVisible` property, like this library intended.

### Reproduction

https://snack.expo.dev/@alamothe/no-header-shadow

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.12
| @react-navigation/native-stack         | 6.8.0
| react-native-safe-area-context         | 4.2.4
| react-native-screens                   | 3.11.1
| react-native-gesture-handler           | 2.2.1
| react-native-reanimated                | 2.8.0
| react-native                           | 0.68.2
| expo                                   | 45.0.8
| node                                   | v16.17.0
| npm or yarn                            | 8.15.0

**Comment by maging-studio** [comment] 2022-10-12 14:53
If you set `headerTransparent` to `true` and set the background color close to transparent, for example `rgba(255,255,255,0.1`), then the bottom shadow will be displayed correctly. 

This config fixes the issue
```
screenOptions={{
    headerShadowVisible: true,
    headerBlurEffect: 'regular',
    headerStyle: {
        backgroundColor:
            Platform.OS === 'ios' //
                ? 'rgba(255,255,255,0.1)'
                : 'white',
    },

    headerLargeTitle: true,
    headerLargeTitleShadowVisible: false,
    headerLargeStyle: {
        backgroundColor: colors.grayBgColor,
    },
}}
```

**Comment by alamothe** [comment] 2022-10-13 10:45
Weird, it doesn't work for me.

**Comment by objectivecosta** [comment] 2022-11-10 15:14
@alamothe fixed this in https://github.com/react-navigation/react-navigation/pull/10993. Thanks for reporting, it led me to find the issue pretty quickly!

**Comment by objectivecosta** [comment] 2022-11-10 15:21
@maging-studio this is a bug in react-navigation, it should work without workarounds... Check https://github.com/react-navigation/react-navigation/pull/10993 ;)

**Comment by objectivecosta** [comment] 2022-11-14 20:24
Not a bug but can now be overriden to allow the native behavior: https://github.com/react-navigation/react-navigation/pull/10993#pullrequestreview-1179684610

Can this be closed as resolved @satya164?

**Closed** 2022-11-14 20:42 UTC
Labels: bug, platform:ios, repro provided
