### ISSUE TITLE
When using a dark theme, the page transition animation has a strange white line at the edge of the screen

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/react-navigation#7690] opened 2020-02-28 11:05 UTC
**Current Behavior**

When using a black theme, the page transition animation has a strange white line at the edge of the card

https://moon.fm/dist/stack-bug.mp4

**Expected Behavior**

no white line

**How to reproduce**
dark theme

```js

 {
    transitionSpec: {
      open: TransitionSpecs.TransitionIOSSpec,
      close: TransitionSpecs.TransitionIOSSpec,
    },
    ...TransitionPresets.SlideFromRightIOS,
    cardOverlayEnabled: true,
    cardShadowEnabled: false,
    transparentCard: true,
  }
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Android
| @react-navigation/native       |
| @react-navigation/stack        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by AlexanderPPetrov** [comment] 2020-03-01 07:04
A workaround for @react-navigation/material-top-tabs
tested only on android device but solving the glitch:
  sceneContainerStyle={{
                                     backgroundColor: 'transparent',
                                     marginLeft: -1
                                 }}

**Comment by WoLewicki** [comment] 2020-03-04 09:20
@gaodeng does @AlexanderPPetrov answer fix your issue so I can close it?

**Comment by gaodeng** [comment] 2020-03-04 10:14
@WoLewicki 
Hi, I haven't tried his method. But even if it works, it's workaround, not a fix。

**Comment by macrozone** [comment] 2020-03-19 11:57
the same problem occures when you just try to style the cards, a small 3px white line on the left side is visible

**Comment by frankyjuang** [comment] 2020-03-24 21:20
> I had a similar issue while using @react-navigation/material-top-tabs. The strange line appeared between the screens a workaround that I did for android was:
> sceneContainerStyle={{
> backgroundColor: 'transparent',
> marginLeft: -1
> }}

Having the same issue. Not sure how to apply the workaround for stack screen

**Comment by jpshelley** [comment] 2020-04-06 21:39
Possibly related to this https://github.com/react-navigation/react-navigation/issues/7221 as we're seeing the same thing with a: StackNav inside a -> MaterialTopTab inside a -> SwitchNav
Thoughts?

**Comment by jpshelley** [comment] 2020-04-07 16:35
this fixed it for me, it was the shadow mentioned in #7221 
```
function interpolatorWithFixedShadow({
  current,
  next,
  inverted,
  layouts: { screen },
}: StackCardInterpolationProps): StackCardInterpolatedStyle {
  let toReturn = CardStyleInterpolators.forHorizontalIOS({
    current,
    next,
    inverted,
    layouts: { screen },
  });
  console.log(toReturn);
  toReturn.shadowStyle = null;
  return toReturn;
}
```

**Comment by frankyjuang** [comment] 2020-04-14 16:00
After digging around a while, I found the root cause. 
A default background color is applied to card content in CardContainer here.
https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/views/Stack/CardContainer.tsx#L186

And the same background color is also applied to card shadow view here. 
https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/views/Stack/Card.tsx#L520

For me, setting shadowStyle to null (@jpshelley 's suggestion) is not enough since the default background color is also applied to the content view. What i did to workaround is just set the background color of card style to match my own dark mode background.  

Not sure how to fix this properly. Maybe just don't apply the default background color for people not using the builtin theme system?

**Comment by michaelknoch** [comment] 2020-04-15 16:40
the custom interpolator from @jpshelley does not work for me. Maybe i am missing something. I am also only experiencing the flicker on the left side of the header. No flicker at all beside the content.

[flicker.mov.zip](https://github.com/react-navigation/react-navigation/files/4482528/flicker.mov.zip)

**Comment by satya164** [comment] 2020-04-15 16:52
You can set a custom background color for the card with `cardStyle`. The shadow can be disabled with `cardShadowEnabled: false`.

Overall I'd recommend setting the theme to dark when you need dark theme for `NavigationContainer` as well as your own app. It's less work and you don't need to set background color or shadow color separately.

**Closed by satya164** 2020-04-15 16:52 UTC
Labels: bug, needs more info, package:stack

**Comment by michaelknoch** [comment] 2020-04-15 17:27
i was able to fix all flicker issues by defining a theme in the `NavigationContainer` thanks for this @satya164 !

**Comment by josuenm** [comment] 2022-06-27 23:21
### I had the same problem, hope it helps others.
#### OBS: I'm using Typescript. If you are using Javascript delete the DefaultTheme import and delete the "as typeof DefaultTheme" in the NavigationContainer

Import your NavigationContainer:
`import { NavigationContainer, DefaultTheme } from '@react-navigation/native';`

Set a theme with your app's background color or just set it to transparent:
  `const MyTheme = {
    dark: false,
    colors: {
      background: 'rgb(12, 12, 12)',
    },
  };`

Place your theme in the NavigationContainer:
`<NavigationContainer theme={MyTheme as typeof DefaultTheme}>
        <Route />
</NavigationContainer>`

**Comment by ibrahim-friendly-url** [comment] 2025-02-04 20:57
@satya164 https://csser.space/questions/tips-for-eliminating-extremely-fine-light-and-dark-borders-from-a-navigation-bar
