### ISSUE TITLE
Typing doesn't work in deeply nested navigators (typescript)

### ISSUE THREAD

**Issue by chrispaynter** [react-navigation/react-navigation#8116] opened 2020-04-24 04:52 UTC
**Current Behavior**
Using React Navigation 5.0 [typescript documentation](https://reactnavigation.org/docs/typescript/), one seems to  only be able to achieve typing on the first level screen when using the `navigate` function. You lose type safety once you start navigating to nested screens, as well as lack the convenience of having intellisense help you construct nested route paths.

I can't find a way out of the box to make this work.

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1684083/80175571-9c60d300-85fe-11ea-8c5f-b0d6e26e6b5b.png">

**Expected Behavior**

Ideally, we should be able to get type checking working all the way down the nested hierarchy (I have this working in a prototype, see below).

_1- typed screen names_
<img width="725" alt="image" src="https://user-images.githubusercontent.com/1684083/80175637-cc0fdb00-85fe-11ea-8c0d-ca213c57703e.png">

_2- typed screen specific param lists_
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1684083/80175667-e21d9b80-85fe-11ea-85b5-6f8a26a84442.png">

_3- full type safety on nested route_
<img width="634" alt="image" src="https://user-images.githubusercontent.com/1684083/80175674-eb0e6d00-85fe-11ea-8473-4c33ba6f536b.png">

**How to reproduce**
Follow the steps as per [documentation](https://reactnavigation.org/docs/typescript/) - 
In the most basic nested structure you will see that you cannot gain type safety below the first level of screens (as per first screenshot above)

**Proposed Solution**
I've been able to make the desired functionality work (as per the screen shots above) with some type helpers. However, I'm not sure of the broader implications of taking this approach with the framework in general.

Would love some feedback.

If this approach looks to be something worthwhile pursuing for the library, I'm happy to craft a PR.

```
// A helper type to enable us to strongly type nested
// screens.
export type ScreenType<ParamList, ParamListKey extends keyof ParamList> = {
  screen: ParamListKey;

  // This could be made to be optional, however we lose the type safety
  // on screens that do indeed have params. So we are keeping this required
  // but it is nullable so you can just set it to undefined
  params: ParamList[ParamListKey];
};

export type ParamScreens<ScreenParamList, OwnParams = {}> = {
  [T in keyof ScreenParamList]: ScreenType<ScreenParamList, T> & OwnParams;
};

/**
 * This function takes your params list for your stack / tab
 * navigatior, and converts it so that you can use it to
 * strongly type nested screen paramaters.
 */
export type ConvertParamsIntoScreenTypes<
  ScreenParamList, // Param list as per https://reactnavigation.org/docs/typescript/#type-checking-the-navigator
  OwnParams = {} // Any extra params that this route should include
> = ParamScreens<ScreenParamList, OwnParams>[keyof ParamScreens<
  ScreenParamList
>];

```

In use, we extend the approach in the documentation, but instead of declaring our params directly on the param list keys, we actually convert the nested screen's own param list into the parent param list, using `ConvertParamsIntoScreenTypes`. This pattern works recursively, allowing us to strongly type n-levels of nesting and achieve type safety.

```
export type OnboardStackParamList = {
  Verify: { user: FirebaseAuthTypes.UserCredential };
  Welcome: undefined;
};

export type AppModalStackParamList = {
  Onboard: ConvertParamsIntoScreenTypes<OnboardStackParamList>;
};
```

**Comment by zanona** [comment] 2020-05-18 12:49
Thanks for opening this issue and the possible solution, @chrisheninger

**Comment by Guuz** [comment] 2020-09-21 08:50
What's the thought of the dev's on this? Any TypeScript project that wants to use documented syntax like below runs into this issue.
```js
navigation.navigate('NavigatorName', {screen: 'ScreenName', params: someParamsForScreenName})
```
https://reactnavigation.org/docs/params/#passing-params-to-nested-navigators
https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator

**Comment by satya164** [comment] 2020-09-21 15:06
Duplicate of #6931

**Closed by satya164** 2020-09-21 15:06 UTC
Labels: bug, package:stack

**Comment by ChamaraWP** [comment] 2024-04-28 10:55
I'm still having this issue in v6.is there any proper way to solve this
Let's say we have another nesting level like this export type 
`RootStackParamList = {   Root: NavigatorScreenParams<MainStackParamList>; };` 
`export type MainStackParamList = {   Home: NavigatorScreenParams<HomeStackParamList>;   Users: NavigatorScreenParams<UsersStackParamList>;   //other stacks that I have }; `
Is this the correct way to make the navigate type if we have another nesting level? I encountered an issue with the types when using navigation.navigate().
the suggestion was not suggesting  for this Home, User

**Comment by Raspberry-pi22** [comment] 2025-02-02 08:27
https://typescripter.space/questions/how-to-extract-a-type-from-a-nested-type-using-typescript



check the answer provided
