### ISSUE TITLE
White background in transition effect

### ISSUE THREAD

**Issue by sameterdem** [react-navigation/react-navigation#9593] opened 2021-05-17 06:30 UTC
There is a white background when transitions between screens.

https://user-images.githubusercontent.com/11645194/118441489-efb62f80-b6f1-11eb-8c20-5ab2dac691d7.mp4

I expect there is no white background when I switch between screens

[Snack](https://snack.expo.io/@sameterdem/react-navigation-white-line)

This didn't work for me #8734 

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.9.4
| @react-navigation/stack        | 5.14.5
| react-native-gesture-handler   | 1.10.3
| react-native-safe-area-context | 3.2.0
| react-native-screens           | 3.2.0
| react-native                   | 0.64.1
| expo                           |
| node                           | 12.22.1
| npm or yarn                    | npm

**Comment by asmailov** [comment] 2021-05-17 08:39
We experience the same issue after running `expo upgrade`.

**Comment by siarheipashkevich** [comment] 2021-05-19 06:58
I have the same issue, expo 41. Do you find any solution?

**Comment by Devince** [comment] 2021-05-22 10:02
I also encounter this problem, using cardstyleinterpolators.ForhorizontalIOS, the head is colored, and the return will have white flicker（Android）

**Comment by zhuanghongji** [comment] 2021-05-24 07:02
I degrade react-native-screens version to `^2.18.1` to avoid this problem.

**Comment by hedia-m** [comment] 2021-05-24 19:19
@zhuanghongji 's solution works (I had react-native-screens version 3.0.0)

**Comment by satya164** [comment] 2021-05-31 23:26
Please don't open duplicate issues. Closing as duplicate of #8734

**Closed by satya164** 2021-05-31 23:26 UTC
Labels: bug, package:stack, repro provided
