### ISSUE TITLE
Native Stack header not respecting safe area on Android

### ISSUE THREAD

**Issue by bitttttten** [react-navigation/react-navigation#7721] opened 2020-03-03 18:57 UTC
**Current Behavior**

With `createNativeStackNavigator` from `@react-navigation/native-stack`, on Android the header does not respect the safe area of the phone and the view goes below the status bar:

![Screenshot 2020-03-03 at 19 54 02](https://user-images.githubusercontent.com/19930241/75809294-de9d2f00-5d88-11ea-8935-d158b92dcbd5.png)

```js
const Screen = () => {
	return (
		<Stack.Navigator
			initialRouteName="Recipes"
			screenOptions={{
				headerStyle: { backgroundColor: `green` },
				headerTintColor: `white`,
				headerRight: HeaderRight,
			}}
		>
			<Stack.Screen
				name="Recipes"
				component={Recipes}
				options={{
					headerTitle: "Recipes",
				}}
			/>
			<Stack.Screen
				name="B"
				component={B}
				options={{
					headerTitle: "B",
				}}
			/>
		</Stack.Navigator>
	)
}
```

**Expected Behavior**

To look like it does on iOS

![Screenshot 2020-03-03 at 19 55 10](https://user-images.githubusercontent.com/19930241/75809332-ebba1e00-5d88-11ea-9a2b-784739b55e17.png)

**Your Environment**

```js
  "dependencies": {
    ..
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.5",
    "@react-navigation/drawer": "^5.0.7",
    "@react-navigation/material-bottom-tabs": "^5.0.7",
    "@react-navigation/native": "^5.0.5",
    "@react-navigation/native-stack": "^5.0.5",
    "@react-navigation/stack": "^5.0.5",
    ..
    "react": "~16.9.0",
    "react-i18next": "^11.3.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-appearance": "^0.3.2",
    "react-native-easy-toast": "^1.2.0",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-htmlview": "^0.15.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-paper": "^3.6.0",
    "react-native-picker-select": "^6.5.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-render-html": "^4.2.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-shimmer-placeholder": "https://github.com/tomzaku/react-native-shimmer-placeholder.git#expo",
    "react-native-stars": "^1.1.6",
    "react-native-super-grid": "^3.1.2",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^8.1.2",
    ..
  },
```

**Comment by enheit** [comment] 2020-03-03 19:11
Duplicate of https://github.com/software-mansion/react-native-screens/issues/360

**Comment by bitttttten** [comment] 2020-03-03 19:29
Thanks!

**Comment by WoLewicki** [comment] 2020-03-04 07:38
Native Stack is no longer maintained by React Navigation.

**Closed by WoLewicki** 2020-03-04 07:38 UTC
Labels: bug
