### ISSUE TITLE
Navigation works half the time for particular page

### ISSUE THREAD

**Issue by MrShakes** [react-navigation/react-navigation#3194] opened 2017-12-28 00:49 UTC
I'm navigating to a new page and from that page I'm trying to go back preferably using `.goBack()` or otherwise navigate to another page using `NavigationActions.reset()`.
Problem is either of these work less than half the time, the other times it shows this error: `undefined is not an object (evaluating '_this5.props.navigation.goBack') `, the few times it does work usually requires a few taps as well

The navigation props should be accessible on the page all the time due to the fact that I navigate directly to that page using `this.props.navigation.navigate('Chat');`

 My Environment
| ---------------- | -------
| react-navigation | ^1.0.0-beta.19
| react-native     | https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz
| node             | 6.10.2
| npm or yarn      | 3.10.10

**Comment by kelset** [comment] 2017-12-29 10:55
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2017-12-29 10:55 UTC
