### ISSUE TITLE
Closing drawer and navigating takes you to original screen

### ISSUE THREAD

**Issue by joel-bitar** [react-navigation/react-navigation#5146] opened 2018-10-18 11:07 UTC
### Current Behavior

When navigating from a drawer to a stack above the drawer the drawer isn't closed automatically. This might not be a bug although often a desired behaviour (since using a stack navigator as parent is the [recommended](https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens) solution to hide the drawer) . So to get around this I'm closing the drawer and navigating at the same time. This has worked fine with react-navigation 2.3.1 but when i updated to 2.17.0 this is broken. When you attempt to close the drawer and navigate at the same time it will first  start to close the drawer and navigate. But when the drawer is closed and the "Navigation/DRAWER_CLOSED" event is received it will navigate you back to the original screen.

### Expected Behavior

I expect it to work as before - that the drawer is closed and you are taken to the desired screen and not automatically navigated back to the original screen when the drawer closes.

### How to reproduce

Snack with 2.17.0 showing the bug:
https://snack.expo.io/@bennyb/react-navigation-drawer-bug

Same snack with 2.3.1 showing that it used to work:
https://snack.expo.io/@bennyb/react-navigation-drawer-2.3.1

Steps to reproduce in the snack:
1. Open the drawer by either swiping from the right or clicking the "open drawer" button.
2. In the drawer click the "close drawer and navigate to registerscreen1" button.
3. Notice that the drawer is closing, and you are navigating but once the drawer is closed you will be taken back to first screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.0

I would also be glad to receive any tips of workarounds. It's not viable to move around my stacks/screens that shouldn't have a drawer down to inside the drawerNavigator and use 'locked-closed' since this would lead to other problems and it's not the recommended way of doing it anyway. And leaving the drawer open in the background generates other issues with android back button (seems like the back is comsumed by the drawer in some way resulting in weird behaviour). I will see if I can create a snack for that issue also.

**Comment by jsaraiva** [comment] 2018-10-31 18:09
Having the exact same issue. The last version that worked is 2.4.1 (2.5.0 exhibits this bug), from what I could tell in my own code.

**Comment by brentvatne** [comment] 2018-10-31 22:57
this has the same root cause as https://github.com/react-navigation/react-navigation/issues/5183

this commit may fix it: https://github.com/react-navigation/react-navigation-core/commit/2f2329f33b0a35af1ccc460a85d268e255886e2b - but i have no plan to backport this to the react-navigation@2.x.

you can confirm that this is fixed by looking at this snack which is the same as yours but i just updated react-navigation to 3.0.0-alpha.18

**Closed by brentvatne** 2018-10-31 22:57 UTC
