### ISSUE TITLE
TextInput auto blur on first focus (Android only) 

### ISSUE THREAD

**Issue by megantaylor** [react-navigation/react-navigation#11342] opened 2023-04-21 19:02 UTC
### Current behavior

I think this is the same issue described in this issue here: https://github.com/satya164/react-native-tab-view/issues/1181

I have tabs with buttons that display an input with autoFocus when clicked. If this is on a non-initial tab, the keyboard opens and immediately closes when I click the button to display the input. This only happens the first time, if I manually focus after keyboard has closed itself, the keyboard stays up.

Setting `animationEnabled={false}` on the TabView on android fixed this behavior, but isn't really a solution.

### Expected behavior

The keyboard should open when input appears and is autoFocused and should stay up until some action blurs the input or user manually closes the keyboard.

### Reproduction

https://snack.expo.dev/@reachvote/react-native-tab-view-android-input-focus-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
├─ @react-navigation/bottom-tabs@6.5.5
├─ @react-navigation/core@6.4.6
├─ @react-navigation/drawer@6.6.0
├─ @react-navigation/elements@1.3.15
├─ @react-navigation/material-top-tabs@6.6.0
├─ @react-navigation/native@6.1.4
├─ @react-navigation/routers@6.1.6
└─ @react-navigation/stack@6.3.14
└─ react-native-safe-area-context@4.4.1
└─ react-native-screens@3.18.2
└─ react-native-gesture-handler@2.8.0
└─ react-native-reanimated@2.12.0
└─ react-native-tab-view@3.3.0
└─ react-native-pager-view@6.0.1
├─ react-native@0.70.5
├─ expo@47.0.8
| node                                   | v16.10.0
| yarn                            | 1.22.19

**Comment by megantaylor** [comment] 2023-04-21 19:36
issue still exists after updating

**Comment by GiannisPapa** [comment] 2023-04-26 14:35
Same issue here...

**Comment by trungtruc91** [comment] 2023-04-29 05:32
Same issue here...

**Comment by alyosha** [comment] 2023-05-09 08:08
ditto

**Comment by alyosha** [comment] 2023-05-09 08:20
seems maybe dupe of https://github.com/react-navigation/react-navigation/issues/11128 ?

**Comment by alyosha** [comment] 2023-05-09 08:22
also this https://github.com/react-navigation/react-navigation/issues/10397

**Closed** 2023-06-30 14:37 UTC
Labels: bug, platform:android, repro provided, package:react-native-tab-view
