### ISSUE TITLE
NavigationActions.Back() triggers componentDidMount 

### ISSUE THREAD

**Issue by rbadr** [react-navigation/react-navigation#3623] opened 2018-02-28 15:34 UTC
### Current Behavior

- Navigating back really quickly from a screen using the android back button or NavigationActions.Back() to previous screens causes some screens to be remounted then unmounted again.

### Expected Behavior

- componentDidMount shouldn't be called when navigating back to the previous screen

### How to reproduce

- The issue is reproducible on Android using the [NavigationPlayground App](https://github.com/react-navigation/react-navigation/tree/master/examples/NavigationPlayground).
- Add componentDidMount to display an alert on MyProfileScreen  ([SimpleStack.js](https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/SimpleStack.js))

```js
type MyProfileScreenProps = {
  navigation: NavigationScreenProp<*>,
};
class MyProfileScreen extends React.Component<MyProfileScreenProps> {
  static navigationOptions = ({ navigation }) => ({
    headerBackImage: navigation.state.params.headerBackImage,
    headerTitle: `${navigation.state.params.name}'s Profile!`,
    // Render a button on the right side of the header.
    // When pressed switches the screen to edit mode.
    headerRight: (
      <Button
        title={navigation.state.params.mode === 'edit' ? 'Done' : 'Edit'}
        onPress={() =>
          navigation.setParams({ mode: navigation.state.params.mode === 'edit' ? '' : 'edit' })
        }
      />
    ),
  });

  componentDidMount() {
    Alert.alert('COMPONENT DID MOUNT')
  }
  componentWillUnmount() {
    Alert.alert('COMPONENT WILL UNMOUNT')
  }

  render() {
    const { navigation } = this.props;
    return (
      <MyNavScreen
      banner={`${navigation.state.params.mode === 'edit' ? 'Now Editing ' : ''}${
        navigation.state.params.name
      }'s Profile`}
      navigation={navigation}
    />
    );
  }
}
```
- Tap the Stack Example
- Tap Push a profile screen (for example navigate through 6 profiles)
- Tap quickly to many times the android back button to get back to the HomeScreen
- You'll see the alert notifying that the screen is mounted/unmounted again

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.2.1
| react-native     | 0.52
| node             | 8.9.4
| npm or yarn      | yarn

Might be related to https://github.com/react-navigation/react-navigation/issues/3592

**Comment by satya164** [comment] 2018-02-28 18:19
Duplicate of #3592

**Closed by satya164** 2018-02-28 18:19 UTC

**Comment by kahurangitama** [comment] 2018-05-08 13:07
I have an opposite problem. I'd like to re-grab a list of items from server when I go back from item details view. How can I do this?

**Comment by brentvatne** [comment] 2018-05-08 17:16
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!
