### ISSUE TITLE
Missing typing of navigating to nesting screens

### ISSUE THREAD

**Issue by frankyjuang** [react-navigation/react-navigation#7847] opened 2020-03-21 09:20 UTC
**Current Behavior**

https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator

```js
navigation.navigate('Root', { screen: 'Settings' });
navigation.navigate('Root', {
  screen: 'Settings',
  params: { user: 'jane' },
});
```

Manually define screen in Root params is needed. Otherwise, typescript warns Type '{ screen: string; }' is not assignable to type 'undefined'.ts(2345)

**Expected Behavior**

Root params can be inferred from RootStackParamList. Maybe add a new type

```typescript
type NavigatorParam<T extends ParamListBase> = {
  [K in keyof T]: { screen: K; params: T[K] };
}[keyof T];
```

**How to reproduce**

See current behavior. 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5.1.0|
| react-native                   |0.61.5|
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment] 2020-03-23 15:40
Duplicate of #6931

**Closed by satya164** 2020-03-23 15:40 UTC
Labels: bug
