### ISSUE TITLE
DrawerNavigator doesn't reset nested StackNavigator

### ISSUE THREAD

**Issue by Rhysjc** [react-navigation/react-navigation#2883] opened 2017-11-02 11:58 UTC
### Current Behavior
- When tapping a `DrawerItem` in a `DrawerNavigator` with each route being a `StackNavigator`, the stack is not reset. In the below example, navigating from `stack1Screen1` to `stack1Screen2`, tapping the `DrawerItem` for `Second`, then tapping the `DrawerItem` for `First` will open up `stack1Screen2` rather than `stack1Screen1`.
```
const stack1 = StackNavigator(
  {
    stack1Screen1: {
      Screen: Stack1Screen1
    },
    stack1Screen2: {
      Screen: Stack1Screen2
    }
  }
);

const stack2 = StackNavigator(
  {
    stack2Screen1: {
      Screen: Stack2Screen1
    },
    stack2Screen2: {
      Screen: Stack2Screen2
    }
  }
);

const drawer = DrawerNavigator(
  {
    First: {
      Screen: stack1
    },
    Second: {
      Screen: stack2
    },
  }
);
```
- I have implemented a custom drawer component, using the same navigation logic the built in component uses. Replacing the logic with the below `reset` action results in a key not defined error.
```
this.props.navigation.dispatch(NavigationActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'Second' })]
}));
```

### Expected Behavior
- Tapping the `DrawerItem` should reset the `StackNavigator` it relates to.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `1.0.0-beta.15`
| react-native     | `0.43`
| node             | `6.10.3`
| npm or yarn      | `3.10.10`

**Comment by kelset** [comment] 2017-11-02 12:47
Hey thanks for reporting.

The reset method has some known issue at the moment, we are working on it; in the meantime, here are some other issues related to this, maybe you can find something useful there until a proper fix is in place:

* https://github.com/react-community/react-navigation/issues/2291
* https://github.com/react-community/react-navigation/issues/2317

And probably this PR could be helpful: https://github.com/react-community/react-navigation/pull/1384 please leave a comment there if it works for you, we'll try to review & merge.

**Comment by Rhysjc** [comment] 2017-11-02 15:16
@kelset None of the workarounds in #2291 and #2317 solved the problem for me. I'm in the process of upgrading my react-native versions so I can't check out that PR just yet.

**Comment by jonbcampos** [comment] 2017-11-06 03:35
+1 watching

**Comment by dgonzalezr** [comment] 2017-11-07 14:20
+1

**Comment by kelset** [comment] 2017-11-07 14:27
@jonbcampos & @dgonzalezr please don't write useless "+1" comments. You can use the 👍 emoji or subscribe to the issue if you want to be updated.

Moreover, I am still waiting for @Rhysjc to let us know if the issue is still present in newer versions of the lib and/or if that PR fixes his issue.

**Comment by jonbcampos** [comment] 2017-11-07 16:49
@kelset thank you, yes I meant to subscribe and watch. I will see if I have time to put something together too. Currently, I am seeing this issue though with the most recent released code.

**Comment by Rhysjc** [comment] 2017-11-07 17:02
@kelset I'm on the latest release (`1.0.0-beta.19`) now, and still have the same problem. I tried out #1384 but it didn't solve my problem - I think because I'm trying to reset a stack within a `DrawerNavigator` rather than a `StackNavigator`

**Comment by Rhysjc** [comment] 2017-11-08 12:42
@kelset Any ideas on this?

The default behaviour in `1.0.0-beta.19` is to navigate to the route for the tapped `DrawerItem`, then navigate to the first screen if the route is a `StackRouter` (this was introduced in #1914). I really think that the sub action should be a `Reset` rather than a `Navigate`. However if I do this I get the `There is no route defined for key...` error that has been reported in a few issues here.

Going back to the example in my first post, the current behaviour means that when I tap the `DrawerItem` for `First`, we end up with a stack of `stack1Screen1` -> `stack1Screen2` -> `stack1Screen1`. If I modify the source so that the sub action is a `Reset`, I get `There is no route defined for key stack1Screen1. Must be one of: 'stack2Screen1','stack2Screen2'`. Why would it be looking for keys in the stack that we've just navigated away from?

If you can point me in the right direction I'm happy to put a PR in for this.

**Comment by dbyilmaz** [comment] 2017-11-14 10:29
Hey @Rhysjc ,
Did you solve the problem?

**Comment by Rhysjc** [comment] 2017-11-14 10:47
@dbyilmaz Nope! I can't find any way to fix the issue. It seems like a really key behaviour that's missing from the library. I've put it to one side for now to work on something else, hoping that it'll be fixed in an upcoming release given how many issues there are relating to this.

**Comment by dbyilmaz** [comment] 2017-11-14 12:04
@Rhysjc thanks for your answer. Our project has the same problem. There are no solutions. I think it is big bug :/  Are you using react navigation with redux?. When I use without redux, there is not any problem.

**Comment by Rhysjc** [comment] 2017-11-14 17:44
@dbyilmazv I am using Redux but I haven't followed the Redux Integration guide so it shouldn't make a difference for me.

**Comment by jonbcampos** [comment] 2017-11-14 18:33
@kelset I created a quick demo that highlights the issue. You'll see if you run the demo that there isn't an issue with the navigator.navigate, the issue only comes up with the reset action. Below is a link to the repo.

https://github.com/jonbcampos/ReactNavBug

**Comment by dbyilmaz** [comment] 2017-11-14 20:03
@Rhysjc My navigation structure is here https://github.com/dbyilmaz/drawer .  Can you look my issue ? https://github.com/react-community/react-navigation/issues/2970 Maybe you can tell me a solution :)

**Comment by dbyilmaz** [comment] 2017-11-14 20:07
@Rhysjc  My navigation structure is here https://github.com/dbyilmaz/drawer. Can you look my issue https://github.com/react-community/react-navigation/issues/2970.  Maybe you can tell me a solution:)

@jonbcampos your link is craches.

**Comment by kelset** [comment] 2017-11-14 23:34
Thanks for all the feedback & code & snack guys, we'll try to take a look at it asap.
Sorry but this week & this upcoming weekend I am really short on time for the repo, so can't tackle this properly.

@dbyilmaz can you please close your issue in favour of this one? It looks to me like they are mostly the same, and I'd like to keep the redundancy low (but I may be wrong)

**Comment by nico1510** [comment] 2017-12-21 07:02
I created a PR which should solve this here https://github.com/react-community/react-navigation/pull/3164

**Comment by Cre3z** [comment] 2018-01-17 13:08
@Rhysjc have you found a solution for this one yet? I am encountering the same problem as stated initially, any help would be appreciated.

**Comment by vonovak** [comment] 2018-01-27 19:39
this should be fixed with https://github.com/react-navigation/react-navigation/commit/8e0fdc67b83d86da1d0deee63cbc41c93907b78e

**Closed by vonovak** 2018-01-27 19:39 UTC
Labels: bug, component: Drawer, help wanted, related: reset

**Comment by montao** [comment] 2018-03-26 03:16
I have been trying to navigate from a draweritem to a tabbed view. The app crashes. It only happens if there is a stack i.e. if I navigate from the first view then I can navigate back using the draweritem. 

I think that react navigation has a new record in making navigation incomprehensible. How can we know what works?
