### ISSUE TITLE
this.props.navigation.dispatch(NavigationActions.back({key: '***'})) error

### ISSUE THREAD

**Issue by zlei123456** [react-navigation/react-navigation#3277] opened 2018-01-16 02:30 UTC
I have Components (A , B, C. D),  my navigation stack as :
_A -> B -> C -> D -> E._
I want to go back Component C . I read the doc, my code as:
`**this.props.navigation.dispatch(NavigationActions.back({key: 'C'}));**`

but go back Component B, I debug react-navigation code and find a error (may be not ).

here is code :
```
  if (action.type === NavigationActions.BACK) {
    const key = action.key;
    let backRouteIndex = null;
    if (key) {
      const backRoute = state.routes.find(
        (route: NavigationRoute) => route.key === key
      );
      /* $FlowFixMe */
      backRouteIndex = state.routes.indexOf(backRoute);
    }
    if (backRouteIndex == null) {
      return StateUtils.pop(state);
    }
    if (backRouteIndex > 0) {
      return {
        ...state,
        routes: state.routes.slice(0, backRouteIndex),
        index: backRouteIndex - 1,
      };
    }

```
code : "backRouteIndex = state.routes.indexOf(backRoute)", backRouteIndex = 2.  

width code :    ```
   return {
        ...state,
        routes: state.routes.slice(0, backRouteIndex),
        index: backRouteIndex - 1,
      };
```
state.routes = [ A, B ] ; state.index = 1.
so the current router is B.

I think this code: 
```
    if (backRouteIndex > 0) {
      return {
        ...state,
        routes: state.routes.slice(0, backRouteIndex),
        index: backRouteIndex - 1,
      };
    }
```
 to change ;
```
    if (backRouteIndex > 0) {
      return {
        ...state,
        routes: state.routes.slice(0, backRouteIndex+1),
        index: backRouteIndex,
      };
    }
```

    "react": "16.0.0",
    "react-native": "0.51.0",
"react-navigation": "^1.0.0-beta.21",
    "redux": "^3.7.2",
    "redux-actions": "^2.2.1",

**Comment by kelset** [comment] 2018-01-16 08:26
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-16 08:26 UTC
