### ISSUE TITLE
Correct way of navigation upon receiving push notification  background and foreground

### ISSUE THREAD

**Issue by shekharskamble** [react-navigation/react-navigation#3653] opened 2018-03-04 06:26 UTC
Hi I have developed 

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by matthamil** [comment] 2018-03-04 18:47
Duplicate of #3654

**Closed by matthamil** 2018-03-04 18:47 UTC
