### ISSUE TITLE
Routes navigates, and returns back to previous route automatically

### ISSUE THREAD

**Issue by Adetiwa** [react-navigation/react-navigation#3275] opened 2018-01-15 16:33 UTC
Hello. I just discovered this as I started a new react native project, with native base.
Whenever I click a button to go to a new route, it goes, then returns to the previous route after a few seconds.
This is a simple button to navigate to a route
<Button transparent onPress={() => this.props.navigation.navigate(ROUTENAME)}/>
I then fixed temporaily using this function to route,
	this.props.navigation.dispatch(NavigationActions.reset({
					index: 0,
					key: null,
					actions: [NavigationActions.navigate({ routeName: 'ROUTENAME' })]
				}))
However, it the error occurs again on another route.
Even so, when opening the side menu, it closes itself. 
I'd really appreciate a fix ASAP.

**Comment by kelset** [comment] 2018-01-16 08:24
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-16 08:24 UTC
