### ISSUE TITLE
React Native's exported SafeAreaView not working as expected in stack navigator with header: null 

### ISSUE THREAD

**Issue by fbartho** [react-navigation/react-navigation#4165] opened 2018-05-08 17:23 UTC
### Current Behavior

Neither `react-navigation:SafeAreaView` nor `react-native:SafeAreaView` appear to be working correctly / consistently when used with `react-navigation@2.0.0` on an iPhone X device (and you have disabled the built-in header in your StackNavigator using header: null).

To phrase it another way: when disabling the standard Navigation Bar as provided by a StackNavigator, and simply wanting to have a custom widget that is at the top of a screen, but doesn't get occluded by device-cutouts, SafeAreaView no longer works within `react-navigation@2.0.0`

### Expected Behavior

Using `react-navigation@1.5.12` both above-referenced SafeAreaView implementations function as expected on an iPhone X device, presenting your content correctly inset when necessary.

### How to reproduce

Example A:

Using a fork of react-navigation [located here](https://github.com/fbartho/react-navigation-broken-safearea-demo), I modified the SafeAreaView example

1. insert a button wrapped in `<SafeAreaView …/>` https://github.com/fbartho/react-navigation-broken-safearea-demo/blob/179f3998e4cd6383f393a8222b79a9a13e40ad59/examples/SafeAreaExample/screens/createDumbStack.js#L59-L61
2. setting the header to null: https://github.com/fbartho/react-navigation-broken-safearea-demo/blob/master/examples/SafeAreaExample/screens/createDumbStack.js#L41
3. Launch and run this example on an iPhone X.
4. Click "Basic Tabs (commonly used).
5. Notice that "I am a teapot" slides behind the iPhone X cutout.
6. Notice when you repeat the above after changing the react-navigation dependency to 1.5.x that I am a teapot is visible below the iPhone X header bar.

_Screenshots or video can be reproduced on request_

Example B:

1. Create a hierarchy of Navigators containing a Screen (in my case StackNavigator(configured for Modals)<-TabNavigator<-StackNavigator<-ScreenA )
2. Make sure none of your StackNavigators have a visible header. `header: null`
3. Wrap the content of your ScreenA in a SafeAreaView
4. Load this app structure on an iPhone X device.
5.a Notice how the top content of your screen slides behind your device cutout.
5.b Notice how the top content is inset below the device cutout when using `react-navigation@1.5.12`

Example C.

1. Create the above hierarchy
2. Present a screen modally as a peer of the TabNavigator, but present it quickly on launch. -- Notice how it lays out as expected.
3. Present a different screen modally (ModalB) as a peer of TabNavigator, but present it after dismissing the first modal, and then tapping on content inside ScreenA.
4. Notice how the SafeAreaView protecting ModalB fails to inset ModalB's top content.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0
| react-native     | 0.55.3
| node             | 9.11.1
| npm or yarn      | 1.6.0

**Comment by brentvatne** [comment] 2018-05-08 17:30
is there no way you can provide a repro of this that we can just run on https://snack.expo.io?

**Comment by brentvatne** [comment] 2018-05-08 17:33
I suspect the issue is related to the following: https://github.com/react-navigation/react-navigation/blob/ec1694f909f895b2be60c5d44b4fb5b278032aff/src/views/StackView/StackViewLayout.js#L470-L485

there's a negative `marginTop` in order to support transitioning between screens with and without headers without layout jump. we might need to revisit this approach.

you can work around with `forceInset={{top: 'always'}}`

**Comment by brentvatne** [comment] 2018-05-08 17:42
running example here: https://snack.expo.io/ryTKZD10G

**Comment by brentvatne** [comment] 2018-05-08 17:44
cc @skevy - curious if you have any ideas how we can resolve this

**Comment by fbartho** [comment] 2018-05-08 18:30
@brentvatne I couldn't figure out how to get the Example app from the react-navigation repo to work in Snack, it was throwing errors at me declaring that decorators didn't work (withNavigation), and I don't know how to get Snack to demonstrate an iPhone X device, so that also wouldn't help with reproduction of the issue.

**Comment by brentvatne** [comment] 2018-05-08 20:02
@fbartho - you can run snacks on your local ios simulator or on your phone. I just copy and pasted the link you shared and exported the result of calling createDumbNavigator rather than the function

**Comment by brentvatne** [comment] 2018-05-08 21:50
looked into this and it's only happening with the react-native SafeAreaView.

notice that it works as expected in this example: https://snack.expo.io/SyXCcq1Cz
but if you replace the SafeAreaView there with the one from react-native, then it doesn't work

I'm not super concerned about this personally because you shouldn't use React Native's built-in SafeAreaView anyhow, it's pretty half baked (admittedly, so is React Navigation's, but we will work on that soon).

If anyone wants to look into this or can provide a repro where React Navigation SafeAreaView doesn't work in this context, let me know!

**Comment by townmulti** [comment] 2018-05-09 10:55
Just want to add that React Navigation SafeAreaView behaves differently when you are already in a call and open the app. Once the call ends the top margin goes away and then there is no space between the StatusBar. I will try it with your snack and see if I can duplicate this issue.

**Comment by brentvatne** [comment] 2018-05-09 15:19
@townmulti - can you create an issue on https://github.com/react-community/react-native-safe-area-view about that?

**Comment by fbartho** [comment] 2018-05-10 19:53
Hi @brentvatne -- I was able to verify that the `react-navigation:SafeAreaView` works the example I provided, but it does not work in my real application. I don't understand the nuance that's different between my application and the example here.

My navs:
```
NoNavBarStack
➡️TabBar ➡️ Stack ➡️ ScreenA
➡️ ModalA
```
ModalA in my case is now using `react-navigation:SafeArea` but still slides behind the iPhoneX cutout.

`forceInset={{top: 'always'}}` does  fix the problem, but it seems like brittle magic to rely on that?  I don't exactly know what the correct purpose of that prop is for.

**Comment by brentvatne** [comment] 2018-05-10 19:58
@fbartho - can you provide a repro case for that?

**Comment by fbartho** [comment] 2018-05-10 20:28
I'll see what I can do this weekend, sorry I can't provide one sooner. I'm being chased by deadlines at the office.

**Comment by townmulti** [comment] 2018-05-10 21:33
I didn't have `forceInset={{top: 'always'}}` prop set. It seems to be working now, if problem persists pass that I will create an issue on react-native-safe-area-view. Thanks @brentvatne

**Comment by ortonomy** [comment] 2018-05-13 01:27
For those seeing this issue that were unaware that ``react-navigation`` also includes its own ``SafeAreaView`` for use inside navigators:

https://reactnavigation.org/docs/en/handling-iphonex.html

> To fix this issue you can wrap your content in a ``SafeAreaView``, which can be imported from react-navigation.

**Comment by export-mike** [comment] 2018-06-04 23:31
@ortonomy Option 2 works for me thanks.

**Comment by matthewhartman** [comment] 2018-06-05 21:49
I can confirm using `<SafeAreaView>` from `react-navigation` and adding ` forceInset={{top: 'always'}}` fixes the problem for me too :+1: 

Thanks @brentvatne for this suggestion!

**Comment by brentvatne** [comment] 2018-06-28 00:55
moving to umbrella issue

**Closed by brentvatne** 2018-06-28 00:55 UTC
Labels: bug, component: Stack, help wanted

**Comment by truthglow** [comment] 2018-11-13 20:48
> I can confirm using `<SafeAreaView>` from `react-navigation` and adding ` forceInset={{top: 'always'}}` fixes the problem for me too 👍
> 
> Thanks @brentvatne for this suggestion!

In my case I just used `<SafeAreaView>` from `react-navigation` without add more things, and it fixed the issue (y)

**Comment by arnaudambro** [comment] 2020-07-15 14:12
For people coming here and still not working, here is a tip: I had to add `<StatusBar translucent={false} >` to make things work for me

**Comment by IshankReddy** [comment] 2025-03-27 01:51
I have the same issue with my code <SafeAreaView forceInset={{ top: 'always' }}> is just not working
