### ISSUE TITLE
Android headerRight and headerLeft images are too close to edges

### ISSUE THREAD

**Issue by caltv** [react-navigation/react-navigation#3360] opened 2018-01-25 17:10 UTC
When I use headerRight and headerLeft images on Android the images are too close to the border, but if I use a "right:" value to move them in they disappear behind the black background of the header. My code is below. Is there a way around this?

![boder](https://user-images.githubusercontent.com/219204/35402017-28345808-01f3-11e8-89c1-2e4772bb648a.png)

```
static navigationOptions = ({ navigation }) => ({
    title: 'Home',
    headerRight: ( 
      <TouchableOpacity onPress={() => navigation.navigate( 'Info' )}>
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
          <Image
            style={styles.imageForButtonInfo}
            source={require('../img/info.png')}
          />
        </View>
      </TouchableOpacity>
    ),
    headerLeft: (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', }}>
        <Image
          style={styles.imageForHomeHeader}
          source={require('../img/home.png')}
        />
      </View>
    ),
    headerStyle: styles.header,
    headerTitleStyle: styles.headerTXT,

  });
```

**Styles**

```
header: {
    backgroundColor: 'black',
  },
  headerTXT: {
    alignSelf:'center',  
    fontFamily: 'SlatePro-Medium',
    fontSize: 22,  
    color: 'white',
    textAlign: 'center',
  },
  imageForButtonInfo: {
    width: 28, height: 28, 
    right: (Platform.OS === 'ios') ? 10 : 0,
    bottom: (Platform.OS === 'ios') ? 5: 0 
  },
```

**Comment by kelset** [comment] 2018-01-26 08:21
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-26 08:21 UTC
