### ISSUE TITLE
headerRight Button in React Navigation Sporadically Fails to Trigger onPress

### ISSUE THREAD

**Issue by BKazimy** [react-navigation/react-navigation#12315] opened 2024-12-03 21:18 UTC
### Current behavior

I’m experiencing an issue where a headerRight button added via setOptions in React Navigation doesn’t consistently trigger its onPress handler. Below are the relevant code snippets, environment details, and what I’ve tried so far.

Here is my custom made button:

```
function IconButton({ onPress, icon, color }) {
    return <Pressable 
        onPress={onPress} 
        style={({pressed}) => [
            pressed && styles.pressed,
        ]}
    >
        <Ionicons name={icon} size={24} color={color} />
    </Pressable>
}
```

Here is the button's usage:

```
    function changeFavoriteStatusHandler() {
        console.log("pressed!")
        if (mealIdsFavorite) {
            favoriteMealCtx.removeFavorite(mealId);
        } else {
            favoriteMealCtx.addFavorite(mealId);
        }
    }

    useEffect(() => {
        navigation.setOptions({
            headerRight: () => (
                <View>
                <IconButton 
                    onPress={changeFavoriteStatusHandler} 
                    icon={mealIdsFavorite ? 'star' : 'star-outline'}
                    color="white"
                />
                </View>
            ),
        });
    }, [navigation, changeFavoriteStatusHandler]);

```

Everything is working as expected except the `onPress` 

### Expected behavior

This button should log `pressed!` and add and remove items to favorit list whenever i tap it. But it only dose so once in a while, and i guess its effected by some page loading or so.

can Any one help me with this?

### Reproduction

https://github.com/BKazimy/Learn/blob/main/RN-food-app/screens/MealDetailScreen.js

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^7.0.13
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |^7.0.18
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |^7.0.13
| @react-navigation/native-stack         |^7.1.9
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |~4.1.0
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |~3.16.1
| react-native-pager-view                |
| react-native                           |0.76.3
| expo                                   |^52.0.14
| node                                   |v18.20.5
| npm or yarn                            |npm

**Comment by satya164** [comment] 2024-12-03 21:20
Duplicate of #12039

**Closed by satya164** 2024-12-03 21:20 UTC
Labels: bug, needs repro, platform:android
