### ISSUE TITLE
Getting warning: “componentWillUpdate is deprecated and will be removed in the next major version” when using the react navigation's navigationOptions

### ISSUE THREAD

**Issue by rohankangale2011** [react-navigation/react-navigation#6134] opened 2019-07-28 14:46 UTC
I am facing a very strange issue while developing a react native app. I wanted to use navigation for which i added "react-navigation" library. Although, when i am setting the navigationOptions for a route, i am getting the below warning:
    
    componentWillUpdate is deprecated and will be removed in the next major version.

More specifically, it comes when i tried to add the below line:

    headerRight: (
          <Button>
            <Icon active name="md-color-filter" style={{
                color: '#333'
              }}/>
          </Button>
          )

The code for the navigationOptions is:

    navigationOptions: () => {
      return {
        title: 'App_Name',
        headerRight: (
          <Button>
            <Icon active name="md-color-filter" style={{
                color: '#333'
              }}/>
          </Button>
          )
        }
      }

And the respective screen component(HomeComponent) is:
  
    import React,{useEffect,useState} from 'react';
    import {View,Dimensions, Alert} from 'react-native';
    import ListComponent from './list/list.component';
    import {HOME_SAMPLE_ITEMS} from '../../../constants/data';

    function HomeComponent(props: any) {

     return (
      <View>
       <ListComponent data={HOME_SAMPLE_ITEMS}/>
      </View>
     )
    }
    
    export default HomeComponent;

To be noted, i am using the following versions:

    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-device-info": "^2.3.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^3.11.1"

Can someone please help me resolve the same. Thanks in advance.

**Comment by vonovak** [comment] 2019-07-29 06:23
hi! I'm assuming the problem is in the `Button` component. I'm going to close the issue as it dos not follow the issue template. Please open a new one if problem persists, and follow the issue template. Thanks.

**Closed by vonovak** 2019-07-29 06:23 UTC
