### ISSUE TITLE
Navigating from a Headerless Screen to a Headered Screen

### ISSUE THREAD

**Issue by LouisJS** [react-navigation/react-navigation#3442] opened 2018-02-06 11:55 UTC
### Current Behavior

In a StackNavigator, if you navigate from a Headerless View to another one that implements a Header, the transition animation is quite dirty

### Expected Behavior

Transition handled in a better way or a choice in the Transition implementation (Fade in or something)

### Your Environment

| software         | version
| ---------------- | -------
| "react-navigation" | "^1.0.0-beta.29"
| "react-native" | "0.52.0"
| node | v9.5.0 |
| npm or yarn |   4.6.1   |

**Comment by kelset** [comment] 2018-02-06 12:09
Duplicate of https://github.com/react-navigation/react-navigation/issues/2732

**Closed by kelset** 2018-02-06 12:09 UTC
