### ISSUE TITLE
Deep linking: Detect if URI already opened

### ISSUE THREAD

**Issue by paulpopiel** [react-navigation/react-navigation#2913] opened 2017-11-06 03:40 UTC
### Current Behavior
If a deep-link is clicked twice, the app stacks the target screen onto the stack twice (meaning the back button will cycle through the 'same' screen twice).

### Expected Behavior
Would be nice if react-navigation detected whether the target screen was already opened (with the same params) and if so just opened the app and didn't add the same screen to the stack again.

Alternatively is there any way to hook into or detect a deep-link being opened and cancel/reject it by doing the check ourselves?

EDIT: or +1 to the following feature request:
https://github.com/react-community/react-navigation/issues/1812

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.17
| react-native     | 0.49.3

**Comment by kelset** [comment] 2017-11-06 10:01
Thanks for reporting. Yeah I guess this is related to that FR but, still, sort of a bug.

Btw can it be that this is sort of related to https://github.com/react-community/react-navigation/issues/2599? Mmmmm

**Comment by paulpopiel** [comment] 2017-11-06 16:38
Don't believe it is related to https://github.com/react-community/react-navigation/issues/2599.

Worth noting it only happens on iOS, as Android seems to re-load the app (and hence reset the nav stack) when a deep link is used. 

In a way it is working as intend depending on your perspective, it just keeps adding screens to the stack. However if you keep clicking the same deep link it will just keep adding the same screen to the stack over and over again... which seems undesirable.

**Comment by kelset** [comment] 2017-11-08 10:16
Just realized, this is probably a duplicate of #2904 - @paulpopiel can you confirm it? If so can you close this in favor of the other one?

**Comment by satya164** [comment] 2020-06-29 13:25
Closing since this shouldn't be an issue in the latest version.

**Closed by satya164** 2020-06-29 13:25 UTC
Labels: bug, version-4

**Comment by zaptrem** [comment] 2021-01-16 07:35
I'm having this issue on the latest version. Can you let future people know what change/new feature resolved this?

**Comment by satya164** [comment] 2021-01-16 14:12
> @satya164 I'm having this issue on the latest version. Can you let future people know what change/new feature resolved this? 

This a 3 year old issue is for React Navigation 1 beta. Latest version is 5 and almost everything has changed since then. If your have a bug with the latest version, then please open a new issue with a repro.

**Comment by zaptrem** [comment] 2021-01-17 02:58
> > @satya164 I'm having this issue on the latest version. Can you let future people know what change/new feature resolved this?
> 
> This a 3 year old issue is for React Navigation 1 beta. Latest version is 5 and almost everything has changed since then. If your have a bug with the latest version, then please open a new issue with a repro.

Sadly all the more recent repeat issues were closed as duplicates on this one. This issue was closed less than 8 months ago. I would just open a new issue, but based on what you said I'd prefer not to as it might be working as intended (I couldn't find any documentation on this specific case).

This is the end of the trail for most of the Google results for this issue, so I thought it might be a good idea to ask for a note here for future searchers. 

Can you let us know the intended behavior for linking to the same page twice with different params? Should it open two of the same screen? Change the params for the current one? Delete the current one and render a new one? Do nothing? If my behavior actually doesn't match we can go from there. Thanks for any info you can provide,

**Comment by satya164** [comment] 2021-01-17 03:06
> Can you let us know the intended behavior for linking to the same page twice with different params

The same as `navigate`, which is updating params if the screen exists, otherwise push a new one. The behavior of navigate can be customized with https://reactnavigation.org/docs/screen#getid
