### ISSUE TITLE
Reset action leaves first screen on the stack

### ISSUE THREAD

**Issue by krsnik93** [react-navigation/react-navigation#3062] opened 2017-12-01 13:10 UTC
I am using the following structure:
    

    const Navigator = StackNavigator({
        Login: { screen: LoginScreen },
        Cognito: { screen: CognitoScreen },
        Skills: {
            screen: SkillsScreen,
            path: 'app/:next'
        },
        Bot: { screen: BotScreen }
    });

The Cognito screen contains a WebView that deep links to Skills screen. The Skills and Bot screens contain a logout button which should reset the stack and end up back at Login screen. The action used is:

    onSelect={() => {
        const resetAction = NavigationActions.reset({
            index: 0,
            actions: [
                NavigationActions.navigate({
                    routeName: 'Login',
                    params: {}
                })
            ]
        });
        navigation.dispatch(resetAction);
    }}

I am using the same index throughout the whole app.

### Current Behavior
After logging out and pressing back, there is another Login screen on the stack. So if the user:

1. starts the app
2. logs in
3. uses the app for a while
4. logs out (but does not exit the app)
5. repeat steps 2-4 N times

he/she will be left with N Login screens on the stack (and needs to press back N times to pop them all and exit the app). In other words, it appears to me that the reset action keeps the bottom screen on the stack, instead of clearing the stack fully.

### Expected Behavior
After logging out there should be only one Login screen on the stack.

Am I misusing the index attribute (always using the same value)? Is the deep link messing up the reset operation?

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.48.2
| node             | 8.4.0
| npm | 5.3.0

**Comment by kelset** [comment] 2017-12-01 13:25
1. you are using a really old version of the library, can you try upgrading to latest and report back if it still happens?
1. it looks to me this is actually a duplicate of https://github.com/react-community/react-navigation/issues/2904

**Comment by krsnik93** [comment] 2017-12-01 14:07
I updated the library to 1.0.0-beta.21. The problem persists.

I don't think it's the same issue as #2904. I am not using push notifications nor closing the app at any moment.

**Comment by vonovak** [comment] 2017-12-03 12:02
@krsnik93 what if you add `key: null`?

```
NavigationActions.reset({
      index: 0,
      key: null, // here's the hack
      actions: [
        NavigationActions.navigate({
          type: 'Navigation/NAVIGATE',
          routeName,
          params,
        }),
      ],
    })
```

**Comment by krsnik93** [comment] 2017-12-04 08:31
@vonovak Nope, still stacking. I also tried goBack() using Cognito screen key (with the understanding that it's goBackFrom, and not goBackTo)...

**Comment by vonovak** [comment] 2017-12-04 14:36
@krsnik93 can you post a repro on snack?

**Comment by krsnik93** [comment] 2017-12-05 16:07
Here is an example that produces the same bug:

https://snack.expo.io/B1pfmSNZf

If you reach the Skills screen and log out N times, you'll be left with N Login screens on the stack. I believe that when the app is opened from that WebView using deep linking, a new stack gets created, instead of a push happening on the existing one.

**Comment by maxschmeling** [comment] 2017-12-11 22:12
@vonovak in case it's helpful, I was having a similar issue and the `key: null` hack fixed it or me.

My issue was that the rendered route (index 0) was itself a stack navigator inside the root stack navigator. When I would reset to a different route on the root navigator, it would error saying the only valid routes were the routes on the nested navigator. Adding `key: null` let the reset work against the root like I was expecting.

**Comment by krsnik93** [comment] 2018-01-09 08:50
Just wanted to add that I solved my problem by setting android:launchMode="singleTask" in the manifest (the problem was affecting only Android version of the app).

**Comment by kelset** [comment] 2018-01-09 12:10
Closing since OP fixed its issue

**Closed by kelset** 2018-01-09 12:10 UTC
Labels: needs more info, related: reset
