### ISSUE TITLE
Undefined is not an Object (evaluatig'_native.NavigationHelperContext.Provider')

### ISSUE THREAD

**Issue by harshit741** [react-navigation/react-navigation#8170] opened 2020-05-01 11:22 UTC
I was trying to make a material top tab navigator but encountered an error. I did exactly shown in docs still cant find the error here is code of my navigator screen.

```
function Home() {
    return (
      <View>
            <Appbar.Header>
                <Appbar.Action icon="home" />
                <Appbar.Content title="Home" />
            </Appbar.Header>
            <NavigationContainer independent={true}>
            <Tab.Navigator>
                <Tab.Screen name="Current Location" component={CurrentLoc} />
                <Tab.Screen name="India" component={IndiaStat} />
            </Tab.Navigator>
            </NavigationContainer>
      </View>
  );
}
```
Here is the [screenshot](https://i.stack.imgur.com/y533a.jpg) of the error.

**Comment by raajnadar** [comment] 2020-05-01 12:26
Duplicate of https://github.com/react-navigation/react-navigation/issues/8169

**Closed by raajnadar** 2020-05-01 12:26 UTC
Labels: bug, package:material-top-tabs
