### ISSUE TITLE
createDrawerNavigator and withNavigation error

### ISSUE THREAD

**Issue by nikitatrifan** [react-navigation/react-navigation#4416] opened 2018-06-04 08:28 UTC
### Current Behavior
Hi guys! I'm trying to use `DrawerNavigatior` instead of `StackNavigatior`, because I need a menu for my app. But I got an error: `Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. The wrapped component is unable to get access to navigation from props or context.`

#### Here is the code of my app (simplified) below:
index.js
```js
const RootStack = createDrawerNavigator(
    {
        Training,
        Exercise,
    },
    {
        initialRouteName: 'Training',
        contentComponent: Drawer,
        drawerPosition: 'right',
    }
);

export default () => (
    <AppLoader>
        <Root>
            <RootStack />
        </Root>
    </AppLoader>
)
```
Training.js
```js
export default () => (
    <Container>
        <Header />
    </Container>
)
```
Header.js
```js
@withNavigation
export default class Header extends React.Component {
    render() {
        const { goBack } = this.props.navigation;
        return (
            <View>
                <Button onPress={goBack}>Go Back</Button>
            </View>
        )
    }
}
```

### Expected Behavior

It works with `createStackNavigator` but with `createDrawerNavigator` doesn't.
![simulator screen shot - iphone 8 - 2018-06-04 at 14 25 32](https://user-images.githubusercontent.com/11634956/40906633-34d72b50-6803-11e8-8de2-e512bb043385.png)

How can I solve this problem? Thanks.

**Comment by destpat** [comment] 2018-06-04 14:46
I have same problem with createBottomTabNavigator, i fixed it in changing my react version from 16.4.0 to 16.2.0

https://stackoverflow.com/questions/50491127/invariant-violation-with-only-some-navigators-react-navigation/50666381

**Comment by brentvatne** [comment] 2018-06-04 19:35
@ericvicenti - ping

**Comment by Lie8466** [comment] 2018-06-06 05:48
I got the same error.

```
import { withNavigation } from 'react-navigation';

class PushNotificationController extends React.Component {
    render() {
        return null;
      }
}

export default withNavigation(PushNotificationController);
```
![2018-06-06_13-45-12](https://user-images.githubusercontent.com/29086796/41019171-1a1c2f52-6990-11e8-8438-c4e004c73a96.png)

**Comment by brentvatne** [comment] 2018-06-06 20:46
@Lie8466 - can you give some context for that? a full runnable example on https://snack.expo.io would help

**Comment by Lie8466** [comment] 2018-06-07 06:13
@brentvatne 
Here is the simple example [https://github.com/Lie8466/react-native-withNavigation](https://github.com/Lie8466/react-native-withNavigation)

`react-native run-ios` will got this error because I used withNavigation in `react-native-withNavigation/src/utils/PushNotificationController.js`. Actually I want to do something related to navigation in PushNotificationController.js and don't konwn how.

Thanks a lot

**Comment by eugrdn** [comment] 2018-06-07 20:05
I guess I have similar kind of the problem, but with the createSwitchNavigator, after updated React from 16.2 to 16.3. For example in render I have this stuff

```
const Layout = createSwitchNavigator();
return (
     <View>
          <Layout />
     </View>
);
```

Then I've got a error
![2018-06-07 22 47 43](https://user-images.githubusercontent.com/16277984/41123324-f1d77548-6aa6-11e8-8599-4a709288a1fb.png)

**Comment by brentvatne** [comment] 2018-06-07 20:38
@eugrdn - can you share an example on https://snack.expo.io or in a github repo? mcve please (https://stackoverflow.com/help/mcve)

**Comment by connercms** [comment] 2018-06-08 15:23
I have a similar case where my app entry point looks like 
```
<View style={{ flex: 1 }}>
    <Navigation />
    <NotificationController />
</View>
```

Where navigation is a drawer that has other nested navigators and such that make up the application. Notification controller is a component on the same level so that it is always mounted and able to listen for and handle incoming notifications. On some notifications, I want to navigate to a screen inside the Navigation component. Notification controller is also attached to redux store so perhaps I'm just hooking it up incorrectly, but 

`export default connect(mapStateToProps, mapDispatchToProps)(
  withNavigation(NotificationsController)
)` 

and 

`export default withNavigation(connect(mapStateToProps, mapDispatchToProps)(
  NotificationsController)
)` 

both give the error above

**Comment by brentvatne** [comment] 2018-06-08 16:27
@eugrdn - can you share an example on https://snack.expo.io or in a github repo? mcve please (https://stackoverflow.com/help/mcve)

**Comment by nikitatrifan** [comment] 2018-06-08 22:36
@brentvatne I wrote [this simple example](https://snack.expo.io/BkuZmF_xm) with the problem. Try to change createStackNavigator to createDrawerNavigator at App.js. Will it work?

**Comment by brentvatne** [comment] 2018-06-08 23:05
that's great, thanks @nikitatrifan

**Comment by brentvatne** [comment] 2018-06-08 23:26
this is fixed in react-navigation-drawer@0.3.0. i updated the version that we use in react-navigation accordingly, but i haven't released a new version of react-navigation with it yet - i'll do that next week. if you want to work around this for now you can do `npm install react-navigation-drawer@0.3.0 --save` and `import { createDrawerNavigator } from 'react-navigation-drawer';`

**Closed by brentvatne** 2018-06-08 23:26 UTC
Labels: discussion required, needs response from maintainer

**Comment by nikitatrifan** [comment] 2018-06-09 04:15
@brentvatne I did update [the example](https://snack.expo.io/Skm5bROgm) to `react-navigation-drawer@0.3.0` as you said and error on initial rendering was gone, but there is no transition animation between screens and button `Go Back` at `AboutScreen` doesn't work. Just tap `Go To About Screen` button, then `Go Back` and make sure it will not work. 

Look under the hood of `Go Back` button which uses the `withNavigation` function.

```js
import { withNavigation } from 'react-navigation'

const Header = ({ navigation }) => (
  <Button
    onPress={() => navigation.goBack()}
    title="Go Back"
    color="#841584"
  />
);

export default withNavigation(Header)

**Comment by brentvatne** [comment] 2018-06-09 05:32
I believe you may be confused about how drawer navigator works. That is expected behaviour. It does not support going back currently or any animation to transition

**Comment by nikitatrifan** [comment] 2018-06-09 06:38
@brentvatne sorry didn't know about that. So okay then

**Comment by brentvatne** [comment] 2018-06-09 18:38
animations, no. back button handling configuration, yeah. you can open pr here if you want to add https://github.com/react-navigation/react-navigation-drawer

**Comment by wg-d** [comment] 2021-12-18 07:26
> destpat

I have same issue but I have no idea to choose the react version as target to downgrade it.

Here is package.json file.

`{
  "name": "RiteHaulerDriver",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "lint": "eslint .",
    "lint:fix": "eslint . --fix",
    "prettier": "prettier --write '*.js'",
    "format-code": "yarn run prettier"
  },
  "dependencies": {
    "@mapbox/polyline": "^1.0.0",
    "@ptomasroos/react-native-multi-slider": "^0.0.14",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/cli-platform-ios": "3.0.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/netinfo": "^4.4.0",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-community/viewpager": "^4.1.6",
    "@react-native-picker/picker": "^1.9.2",
    "apisauce": "^0.14.3",
    "async": "^2.6.0",
    "axios": "^0.21.0",
    "base-64": "^0.1.0",
    "lodash": "^4.17.10",
    "moment": "^2.22.1",
    "prop-types": "^15.6.1",
    "react": "16.9.0",
    "react-devtools": "^4.8.2",
    "react-native": "0.63.2",
    "react-native-a-beep": "^1.0.6",
    "react-native-actionsheet": "^2.4.2",
    "react-native-background-timer": "2.0.0",
    "react-native-beep-tone": "^1.0.2",
    "react-native-clean-project": "^3.4.0",
    "react-native-cli": "^2.0.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-firebase": "^5.6.0",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-htmlview": "^0.13.0",
    "react-native-image-picker": "^0.26.10",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-image-progress": "^1.1.1",
    "react-native-image-resizer": "^1.0.0",
    "react-native-intl-phone-input": "^1.2.26",
    "react-native-iphone-x-helper": "^1.0.3",
    "react-native-keyboard-manager": "^4.0.13-7",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-loading-spinner-overlay": "^1.1.0",
    "react-native-maps": "0.27.1",
    "react-native-message-bar": "^2.0.10",
    "react-native-modal": "^6.0.0",
    "react-native-notification-sounds": "^0.5.2",
    "react-native-openanything": "^0.0.6",
    "react-native-picker-select": "^8.0.2",
    "react-native-progress": "^4.1.2",
    "react-native-progress-bar-animated": "^1.0.6",
    "react-native-progress-timer": "^1.0.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^1.13.0",
    "react-native-router-flux": "4.0.0-beta.27",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^2.10.1",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-search-box": "^0.0.18",
    "react-native-simple-toast": "^1.1.2",
    "react-native-sound": "^0.11.0",
    "react-native-sounds-beep": "0.0.1",
    "react-native-star-rating": "^1.0.9",
    "react-native-svg": "10.0.0",
    "react-native-swipeout": "^2.3.3",
    "react-native-swiper": "^1.6.0-nightly.3",
    "react-navigation": "^4.4.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.0",
    "redux-storage": "^4.1.2",
    "redux-storage-decorator-filter": "^1.1.8",
    "redux-storage-engine-reactnativeasyncstorage": "^1.0.5",
    "remote-redux-devtools": "^0.5.12",
    "remotedev": "^0.2.9",
    "remotedev-server": "^0.3.1",
    "reselect": "^3.0.1",
    "seamless-immutable": "^7.1.3",
    "victory-native": "30.0.0"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.3.1",
    "jest": "24.3.1",
    "metro-react-native-babel-preset": "0.53.0",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}`
