### ISSUE TITLE
Resetting parent stack state from nested stack creates UI bug on Android

### ISSUE THREAD

**Issue by emeraldsanto** [react-navigation/react-navigation#8046] opened 2020-04-15 17:31 UTC
**Current Behavior**

Let's start with my navigation structure:

- GlobalStack (modal mode)
    - BootstrapScreen
    - AuthenticationStack
    - DrawerNavigator
        - BottomTabNavigator
            - HomeStackNavigator
            - FavouritesStackNavigator
            - SearchStackNavigator
            - ExploreStackNavigator
            - SettingsStackNavigator
    - Popup
    - BottomSheet
    - ImageViewer

When the app starts up, the BootstrapScreen is shown and initializes a few things, then navigates to the AuthenticationStack. The problem happens when a user logs in and I try to reset the current state to only render the DrawerNavigator (I don’t want users to be able to go back to the authentication stack). I’m using the following code:

```js
props.navigation.reset({
    routes : [
        { name : Route.APP_DRAWER }
    ]
});
```

This snippet works like a charm on iOS, however on Android I can see the initial screen (HomeScreen) for a few milliseconds before the screen turns completely white. Using props.navigation.navigate(Route.APP_DRAWER); works but allows users to go back, which I don’t want. When pressing the back button using this approach, I still end up seeing the same white screen

**Expected Behavior**

It should take me to the `initialRoute` specified on my `DrawerNavigator`, just like it does on iOS.

**How to reproduce**

Simply nest two different `StackNavigator` inside a global app `StackNavigator` and try to reset from one to the other, much like the old `SwitchNavigator` used to work.

EDIT: I made a sample [app](https://github.com/emeraldsanto/nested-stack-bug) demonstrating the bug.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.1.5
| @react-navigation/stack        | 5.2.10
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.62.0
| expo                           | N/A
| node                           | 12.12.0
| npm or yarn                    | 6.14.4

**Comment by emeraldsanto** [comment] 2020-04-15 18:17
@satya164 Thanks for labeling correctly, I've just tried creating a Snack but I can't get any of the dependencies to install. I've also tried to run the Snack examples in the docs and encountered the same issue.

**Comment by satya164** [comment] 2020-04-15 19:43
create a repo on github if you cannot create a snack

**Comment by emeraldsanto** [comment] 2020-04-16 16:59
I've uploaded a repo containing a very minimal example at [emeraldsanto/nested-stack-bug](https://github.com/emeraldsanto/nested-stack-bug). At first I wasn't able to reproduce and I tried many different setups for a good hour and a half until I realized I hadn't called `enableScreens()` on my demo app. Whenever I add that line, I'm able to reproduce the bug so I believe this issue should maybe be transferred to the appropriate repo?

**Comment by emeraldsanto** [comment] 2020-04-16 18:15
I've narrowed it down to version `2.4.0` and `2.5.0` of `react-native-screens`. Downgrading to `2.3.0` seems to fix the issue for now.

**Comment by WoLewicki** [comment] 2020-04-27 13:02
@emeraldsanto can you repro it in the newest version of `react-native-screens`? And if so, can you be more specific on what the issue is exactly and how to reproduce it in your repo?

**Comment by emeraldsanto** [comment] 2020-04-27 13:47
@WoLewicki Morning! I can update the version and try it out. Everything's explained in the `README`. You simply have to add `enableScreens()` in `index.js`, run the app and click on the button to navigate.

**Comment by WoLewicki** [comment] 2020-04-27 14:47
In README, there is written that 
>the initial route for the desired stack will briefly show up then disappear.

But there is only one screen in the stack we are navigating to so the initial route is the screen that appears and stays there. Am I wrong?

**Comment by emeraldsanto** [comment] 2020-04-27 18:19
There is indeed only one screen on the `ProfileStack` route, it doesn't matter because the problem seems to be that the nested Stack stops rendering its children (the header is still showing). It is important to note that this problem only occurs on Android. I'll be uploading a GIF of the issue shortly to better highlight the problem.

**Comment by emeraldsanto** [comment] 2020-04-27 18:49
I've updated the `react-native-screens` version to `2.7.0` and the issue no longer seems to be relevant. I believe this can be closed.

**Comment by WoLewicki** [comment] 2020-04-28 08:29
Great! So I am closing it. Feel free to comment if something is wrong.

**Closed by WoLewicki** 2020-04-28 08:29 UTC
Labels: bug, library:react-native-screens, package:stack
