### ISSUE TITLE
Deeplinking bug when a stack navigator is nested inside a Drawer Navigator

### ISSUE THREAD

**Issue by santhoshvai** [react-navigation/react-navigation#9507] opened 2021-04-16 02:04 UTC
## Current Behavior

If a drawer-screen with stack navigator is nested inside a drawer navigator and then deeplinked to a screen within the stack navigator with a parameter, the parameter is still present when we navigate to the screen without passing the parameter.

## Expected Behavior

When we navigate to the screen without passing any parameter, the parameter has to be undefined.

## How to reproduce

**Repo:** https://github.com/santhoshvai/ReactNavigationDeeplinkBugRepro

### Setup

```
npm i --legacy-peer-deps
npx pod-install ios
npx react-native run-ios
```

### Open detail screen with deeplink with param 'id=123'

```
xcrun simctl openurl booted "mychat://detail?id=123"
```

**we should see `{ id: 123 }` being shown on the screen**

![image](https://user-images.githubusercontent.com/3846977/114960141-bbd3ba00-9e66-11eb-869a-70e7defc5919.png)

### Go back to Main screen

![image](https://user-images.githubusercontent.com/3846977/114960368-2dac0380-9e67-11eb-81af-fc2492710891.png)

### Tap the button `Go to Details with id '789'`

We should see `{ id: 789 }` being shown on the screen

![image](https://user-images.githubusercontent.com/3846977/114960413-44eaf100-9e67-11eb-9aab-0955e24c3b84.png)

### Go back to Main screen again. Now tap the button `Go to Details without id`

**We still see `{ id: 123 }` being shown on the screen. The expected behaviour here is that the id is undefined.**

### Expected behaviour is seen when deeplinking is not used.

- Now do a full reload. And tap the button `Go to Details with id '789'`. We should see `{ id: 789 }` being shown. Then if we tap the button `Go to Details without id`, we see that the id is undefined as expected. This is the same behaviour I expect after deeplinking too but instead `{ id: 123 }` param is being remembered.

## Your Environment

| software                 | version |
| ------------------------ | ------- |
| iOS or Android           | ios 14.3  |
| @react-navigation/drawer | ^5.12.5 |
| @react-navigation/native | ^5.9.4  |
| @react-navigation/stack  | ^5.14.4 |
| react-native             | 0.64.0  |
| node                     | 14.15.0 |
| npm or yarn              | npm     |

**Note:** I tried it on v6 and was able to reproduce as well

**Comment by mayank-budhiraja** [comment] 2021-04-28 07:21
Hello! Can I take this issue? Thanks

**Comment by ngtrhieu** [comment] 2021-05-01 05:21
Tried reproduce the problem here: https://github.com/ngtrhieu/react-navigation/tree/ngtrhieu/fix/9507-deep-linking-bug

Some observation:
```
Array [                            // Routes of the Drawer router, only have 1 screen
  Object {
    "key": "MainStack-PN39Rw6bZpHvGNcvu480z",
    "name": "MainStack",
    "params": Object {   // After deeplink, the MainStack screen params will permanently be set
      "initial": true,
      "params": Object {
        "id": "123",
      },
      "path": "detail?id=123",
      "screen": "Detail",
      "state": undefined,
    },
    "path": undefined,
  },
]
Array [                               // Routes inside the inner navigator, which is a stack and can have 2 screens
  Object {
    "key": "Main-KCh88MZ3ZUDDA5Nnwh0V5",
    "name": "Main",
    "params": undefined,
  },
  Object {
    "key": "Detail-0mgXq9pxf7NnF1keMSxXs",
    "name": "Detail",
    "params": Object {       // When navigate with empty param, this param will takes the param of the DrawerNavigator
      "id": "789",
    },
    "path": undefined,
  },
]
```

**Comment by satya164** [comment] 2021-05-31 23:41
Params are merged in React Navigation 5. So this is expected behavior. This behavior is changed in React Navigation 6 and params are no longer merged by default. So I'm closing this.

**Closed by satya164** 2021-05-31 23:41 UTC
Labels: bug, repro provided

**Comment by DrRefactor** [comment] 2021-06-18 12:32
why is this closed?
as per original description:
> Note: I tried it on v6 and was able to reproduce as well

How to workaround this, besides downgrading to react-navigation4?
How to reset these params? It's really annoying, because of this unexpected params preservation, user always see's some old content, when entering screen without params...

**Comment by Decezaris** [comment] 2021-08-24 15:02
You can try to use LinkButtons [here](https://reactnavigation.org/docs/5.x/use-link-props). Worked for me.

**Comment by marin-leonard** [comment] 2023-06-15 07:11
This is still an issue...

**Comment by HildeWSerpicoDev** [comment] 2024-08-01 13:31
Just ran into the issue as well, v6
