### ISSUE TITLE
ScreenProps coming in as undefined for TabView but fine for Header/CardStack

### ISSUE THREAD

**Issue by mujavidb** [react-navigation/react-navigation#2972] opened 2017-11-13 16:40 UTC
I have an application built with a route TabNavigator and multiple Stack navigations as such:

```
/TabNavigator
    /StackNavigator - 1
        ...screens
    /StackNavigator - 2
        ...screens
```

Following [the redux integration guide](https://reactnavigation.org/docs/guides/redux) I set up all of my TabNavigators and StackNavigators with redux.

### Current Behavior
When I set `tabBarVisible: false` on a screen in its `navigationOptions`, this has no effect on the tabBar, so it doesn't hide. 

I looked into this and it turns out in the `TabView` the `screenProps` are coming in `undefined`.

I don't see why this could be happening since the `screenProps` come in just fine in the Header/CardStack when the title is rendered.

### Expected Behavior
The screenProps are coming in correctly and being passed down to the TabBarComponent.

Would really appreciate thoughts on this issue, as it's affecting my production app. I would like to implement a workaround at least in my local copy, and if all is successful, maybe send in a PR.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.48.0
| node             | 7.4
| npm or yarn      | 4.6.1

**Comment by kelset** [comment] 2017-11-14 16:34
Thanks for reporting, we'll try to look into that but surely a PR would help greatly :)

**Comment by NSShentu** [comment] 2017-11-15 10:57
screenProps can't pass function , is it?

**Comment by mujavidb** [comment] 2017-11-15 12:42
@kelset I'll give it a look this weekend.

@NSShentu what do you mean?

**Comment by NSShentu** [comment] 2017-11-15 12:48
@mujavidb when i do like this:
<Stack screenProps={
a = ()=>{console.warn('1');}
}/>

Nothing in this.props.screenProps............

BUT.........

<Stack screenProps={
a = 'a'
}/>

it can get "a" by this.props.screenProps

**Comment by satya164** [comment] 2018-01-04 05:44
Looks like duplicate of #1848

**Comment by kelset** [comment] 2018-01-04 09:08
Agreed, it's a duplicate. Closing in favour of #1848

**Closed by kelset** 2018-01-04 09:08 UTC
Labels: bug, component: Tabs
