### ISSUE TITLE
Params not being passed when navigating between Stacks (repro included)

### ISSUE THREAD

**Issue by davideweaver** [react-navigation/react-navigation#143] opened 2017-02-01 22:12 UTC
I use the following code to create an initial screen that does not have a NavBar but pushes on a stack that contains a floating NavBar. When navigating to the second stack, params are being passed. It doesn't appear that those params are being passed to the new screen. This can be seen in the attached screenshot. **undefined** should not be showing.

![image](https://cloud.githubusercontent.com/assets/737309/22528214/4da99ff2-e8a0-11e6-9267-ee0f6027a5b5.png)

**index.ios.js**
```
import React, { Component } from 'react';
import { StackNavigator } from "react-navigation"
import { AppRegistry, Text, View, Button } from 'react-native';

class FirstView extends Component {
  render() {
    const {navigate} = this.props.navigation;
    return (
      <View style={{marginTop:20}}>
        <Text>First View</Text>
          <Button title="Second" onPress={() => navigate("HeaderStack", {name:"Jo"})} />
      </View>
    );
  }
}

class SecondView extends Component {
  render() {
    const {state} = this.props.navigation;
    var name = state.params ? state.params.name : "<undefined>";
    return (
      <View><Text>Second View: {name}</Text></View>
    );
  }
}

const HeaderStack = StackNavigator({
  SecondView: { screen: SecondView }
}, {
    headerMode: "float",
});

const NoHeaderStack = StackNavigator({
  FirstView: { screen: FirstView },
  HeaderStack: { screen: HeaderStack }
}, {
  headerMode: "none"
});

AppRegistry.registerComponent('ParamsRepo', () => NoHeaderStack);
```

Is this a bug, or is there another way to accomplish the same thing?

**Comment by ElliottJRo** [comment] 2017-02-01 22:26
I think you're running into this problem because your `SecondView` is nested in a `StackNavigator` so state params aren't being passed into the children.

Have you tried replacing HeaderStack with SecondView when defining NoHeaderStack? ie:
```
const NoHeaderStack = StackNavigator({
  FirstView: { screen: FirstView },
  HeaderStack: { screen: SecondView }
}, {
  headerMode: "none"
});
```

**Comment by davideweaver** [comment] 2017-02-01 22:32
@ElliottJRo What you suggest does work correctly. That doesn't accomplish the UI I'm looking for though.

**Comment by ElliottJRo** [comment] 2017-02-01 22:45
@davideweaver hmm so what you need to do is somehow pass the params from `HeaderStack = StackNavigator()` to `SecondView extends Component()` which should be possible.. Just cant find where I read it before

**Comment by ElliottJRo** [comment] 2017-02-01 23:41
hey @davideweaver try this:
```
<Button title="Second" onPress={() => navigate("HeaderStack",{},
  {
    type: "Navigate",
    routeName: "SecondView",
    params: {name:"Jo"}
  }
)} />
```

Whats going on is -> we navigate to "HeaderStack" and then set a second "Navigate" action to be handled by the child router (which is the "HeaderStack" `Navigator`). [reference](https://reactnavigation.org/docs/navigators/navigation-prop)

**Comment by satya164** [comment] 2017-02-01 23:42
It's expected behaviour right now, but I agree that's it's confusing. cc @ericvicenti @skevy

**Comment by davideweaver** [comment] 2017-02-02 00:37
@ElliottJRo Thanks for the code. Now that I see it the docs make sense.

**Comment by ilaif** [comment] 2017-02-06 14:25
I still can't get this working.

I have a Drawer inside a Stack, and I'm trying to navigate between two screens in the Drawer.
Tried all combinations, how would you call navigate from Notifications to Main with params in the following setup:
```js
const MainNavigator = DrawerNavigator({
    Main: {screen: Main},
    Notifications: {screen: Notifications},
});

const SplashStackNavigator = StackNavigator({
    Login: {screen: Login},
    MainNavigator: {screen: MainNavigator}
}, {
    initialRouterName: 'Login',
    headerMode: 'none',
});
```

I've tried:
```js
this.props.navigation.navigate('Main', {param: 'param'});
this.props.navigation.navigate('MainNavigator', {}, {
    type: "Navigate",
    routeName: "Main",
    params: {param: 'param'},
});
```

And in all cases inside Main constructor:
```js
const navParams = this.props.navigation.state.params;
```
is undefined.

Thanks.

**Comment by davideweaver** [comment] 2017-02-06 20:22
@ilaif it looks like you're calling the same way I have it working. I haven't tried it with a Drawer Navigator though. That may behave differently than a TabsNavigator. The only other thing I see different, which shouldn't matter, is that I'm using destructuring when accessing **params**:

```
const { state } = this.props.navigation;
var title = state.params.session.title;
```

Maybe try dumping your navigation when the target page loads:

```
componentDidMount() {
  console.log("NAV: ", this.props.navigation)
}
```

**Comment by jamesisaac** [comment] 2017-02-07 12:41
This workaround doesn't really make sense to me (nor can I even get it to work).

To take an example which I imagine would be quite a common use case: say the main navigator of my app is a StackNavigator, with the main screen being a ListView of contacts.  When I click a contact, I want to navigate to a screen with sliding tabs (TabNavigator), where each tab displays a different piece of info about that contact.

With this nested navigate action workaround, the best I can hope for is that I can pass the contactId param to one of the tabs.  (Which would cause an error on the other tabs unless `lazyLoad: false`).  Perhaps I could dispatch the [SetParams](https://reactnavigation.org/docs/navigators/navigation-prop) action on each of the tabs, but that seems a bit silly.

What I think would make a lot more sense here is if I could simply call `naviagion.navigate('ContactTabNavigator', { contactId: id })`, and have that param automatically passed down to all the nested screens.

**Comment by JulianKingman** [comment] 2017-03-09 13:34
I have the latest version and am still having this problem.

Root navigator:
````javascript
const AppNavigator = StackNavigator({
  MainDrawer: {screen: MainDrawer},
}, {
  navigationOptions: {}
});
````

MainDrawer: 
````javascript
const MainDrawer = DrawerNavigator({
  Home: {screen: Home},
  PastIncidents: {screen: PastIncidents},
  NewIncident: {screen: NewIncident},
}, {
  navigationOptions: {...},
  drawerPosition: 'right',
  contentOptions: {
    style: {
    },
  },
});
````

on `Home`:
````javascript
navigation.navigate('NewIncident', {incidentId});
````

The incidentId is not passed to the NewIncident component. Ideas?

**Comment by fwchen** [comment] 2017-04-06 11:12
i have same problem

**Comment by nonameolsson** [comment] 2017-04-06 13:31
I experience the same issue. 

In my container:
```
  onPress(data) {
    this.props.navigation.navigate('NewsItem', { news: data })
  }
```
I am sure that data is a valid object. It has worked before, and during debugging. 

And in my `NewsItem` screen:
```
....
  render() {
    const { navigate } = this.props.navigation;
    const { title, date, text, image } = this.props.navigation.state.params.news
```

Here is the result. The state only contains `key`and `routeName`.
![screen shot 2017-04-06 at 15 30 57](https://cloud.githubusercontent.com/assets/1493018/24756999/1bd0ffa0-1ade-11e7-8418-f4feb08c2bfe.png)

**Comment by JulianKingman** [comment] 2017-04-10 19:19
Looks like this may get fixed by this PR: https://github.com/react-community/react-navigation/pull/969

**Comment by grabbou** [comment] 2017-04-26 15:19
Yeah, looks like this issue was a duplicate of the ones mentioned by the PR. That should be fixed in latest master.

**Comment by satya164** [comment] 2017-04-26 15:26
The linked issues seem different.

**Comment by grabbou** [comment] 2017-04-26 15:29
You are right. I got confused by one of the commits that talks about Drawer https://github.com/react-community/react-navigation/issues/143#issuecomment-285352224. Drawer should work fine.

**Comment by TGNC** [comment] 2017-05-04 11:17
The issues seems to be fixed for `TabNavigator` in `^1.0.0-beta.9`.
However, this only work for `NavigationActions.navigate()` request. 
Trying to make the same navigation but with `NavigationActions.reset` instead - did not worked

**Comment by naomipol** [comment] 2017-07-04 10:35
The workaround mentioned above does not fit my navigation structure as well.

I have a main DrawerNavigator where each route is a StackNavigator. The StackNavigator has an initial route configured so when I route to the stack I get that screen.

```js
const DrawerNav = DrawerNavigator({
  Home: { screen: HomeScreen, },
  Document: { screen: DocumentStack}},
  {
    initialRouteName: 'Home'
  });
```

```js
const DocumentStack = StackNavigator({
    List: { screen: ListScreen },
    Details: { screen: DetailsScreen }
  },{
    initialRouteName: 'List',
  });
```


When navigate to the stack and do an additional navigation to that (initial) screen, I get the screen with a back button - and when I press it, it goes back to the exact screen but without the parameter.

```js
navigate('Document', {},
      {
        type: "Navigate",
        routeName: "List",
        params: {list: 'orders'}
      })
```
Screen shot after navigation: (The list page is second in navigation stack and has a back button)

![image](https://user-images.githubusercontent.com/9568753/27826689-a88b07be-60bc-11e7-9c16-b439a71018d9.png)

Screen shot after I press the back button: (The list name is empty - because no params)

![image](https://user-images.githubusercontent.com/9568753/27826713-c79c9e60-60bc-11e7-9659-41f57099b84c.png)


Is this going to be fixed
Is there any other solution in the mean time?

**Comment by jordanmkoncz** [comment] 2017-07-06 00:51
@TGNC I've created a separate issue since this one has been closed and appears to be for a different problem. See https://github.com/react-community/react-navigation/issues/2073.

**Comment by dmr07** [comment] 2017-07-08 16:34
+1. Also getting undefined params when navigating from one stack to a screen in a nested stack.

**Comment by smitthakkar1** [comment] 2017-07-13 21:30
Any Solution to this ? Facing the same problem

**Comment by yukkeechang** [comment] 2017-07-14 00:26
I have this issue too +1

**Comment by smitthakkar1** [comment] 2017-07-14 19:38
This might help and work for me.

On Screen1 I am passing the data while navigating to Screen2 like this:

<TouchableHighlight
onPress = {() => { this.props.navigation.navigate('CandidateProfile', user = {i}) }} />

On Screen 2, I am receiving this data which is "i" here,

const {i} = this.props.navigation.state.params;

I have constructor on both component and which is like this :

constructor(props){
    super(props);
    this.state = {};
}
Hope helps you guys. This took so much time.

**Comment by yukkeechang** [comment] 2017-07-15 19:58
Thing is, I'm passing this param from one screen and trying to display it a few screens away in my stack nav and accessing the param value there gives me an undefined :(

**Comment by agersoncgps** [comment] 2017-07-21 01:29
Still looking for a concrete way to do this...

**Comment by yash2code** [comment] 2017-07-23 16:01
none of the soln worked   .... if anyone solved it please help : [SO](https://stackoverflow.com/questions/45266362/sending-the-navigation-params-as-props-to-other-component)

**Comment by Himujjal** [comment] 2017-08-25 13:03
**Temporary Solution:** Redux or any other Flux Library would definitely help here where you have to dispatch the prop to the main store. Then in the screen where we would have to navigate to just get the prop from the store. This is a workaround and does not actually solve the problem. I am still looking for a solution to this problem. Let me update the Redux Code after I have tried it myself.

**Comment by Himujjal** [comment] 2017-08-25 15:49
I was having the same problem and solved it using Redux. This is what Redux does best. Solve global problems in an applications.

We have to dispatch the `name` to the redux store first when you try to navigate. Then on the next screen where we are navigating to, just retrieve the `name` object from the store and use it wherever you like.

First `npm i -S redux` to your application.

Then modify the code as below:

Here is the full code: 
```
import {createStore} from 'redux';
import React, { Component } from 'react';
import { StackNavigator } from "react-navigation"
import { AppRegistry, Text, View, Button } from 'react-native';

//This is the reducer:
const setName = (state = {}, action) => {
    switch(action.type){
        case 'SET_NAME': return {name: action.name};
        default: return state;
    }
}

//Create a new store:
const store = createStore(setName, {name:''});

class FirstView extends Component {
 _navigation(name){
    store.dispatch({
            type: 'SET_NAME',
            name
        });
 }


  render() {
    const {navigate} = this.props.navigation;
    return (
      <View style={{marginTop:20}}>
        <Text>First View</Text>
            {/*Pass the name to this._navigation(name) as argument*/}
          <Button title="Second" onPress={() => this._navigation(name)} />
      </View>
    );
  }
}

class SecondView extends Component {
    constructor(){
    super();
    this.state = {name : store.getState().name}
    }
  render() {
    var name = this.state.name;
    name = name ? name : "<undefined>";
    return (
      <View><Text>Second View: {name}</Text></View>
    );
  }
}

const HeaderStack = StackNavigator({
  SecondView: { screen: SecondView }
}, {
    headerMode: "float",
});

const NoHeaderStack = StackNavigator({
  FirstView: { screen: FirstView },
  HeaderStack: { screen: HeaderStack }
}, {
  headerMode: "none"
});

AppRegistry.registerComponent('ParamsRepo', () => NoHeaderStack);
```
I haven't yet run this code. But it should work fine. It worked in another application I made. Please tell me if I have to improve this code anymore.

**Comment by spencercarli** [comment] 2017-08-28 01:34
Hi! In an effort to get the hundreds of issues on this repo under control I'm closing issues tagged as questions. Please don't take this personally - it's simply something we need to do to get the issues to a manageable point. If you still have a question I encourage you to re-read the docs, ask on StackOverflow, or ask on the #react-navigation Reactiflux channel. Thank you!

**Comment by rtman** [comment] 2017-08-31 05:03
@spencercarli this seems like a bug not a question, it would be great if you could comment on this as I am also seeing this issue when reseting the stack and trying to pass props between nested navigators.

**Comment by mleduque** [comment] 2017-09-19 13:38
I ahev the same problem, but there's someone tagging issues as question, then explaining they're close issues tagged as question, so I suppose there never will be fixes.

@Himujjal that's not a solution, there is a conceptual difference between global state and parameters and your workaround conflates them.

**Comment by nonameolsson** [comment] 2017-10-27 15:40
This one shouldn't be closed, since it's just not a question. It's a discussion about how solving this problem when passing params. @spencercarli

**Comment by hoaibkdn** [comment] 2017-11-16 11:25
How to pass multi params? I only pass a params like that `navigation.navigate(ROUTES.WORKOUT_DETAILS, {currentDay: currentDay})}`
but can not `onPress={() => navigation.navigate(ROUTES.WORKOUT_DETAILS, { currentDay: currentDay, equipments: this.props.equipments})}`

**Comment by yasir-netlinks** [comment] 2017-11-26 09:58
Hi , I am facing the same issue not being able to pass Params.
Top Level Stack
```
const routeConfiguration = {
    Login: { screen: Login },
    Home: { screen: HomeWrapper,
        navigationOptions: {
            header: null
        }    
    },
    UserInfo: { screen: UserFormsTabBar, 
        navigationOptions: {
            header: null
        } 
    },
    Profile: { screen: ProfilePage },
}
```
I am trying to navigate from `Profile` to `UserInfo`. Now `UserInfo` is a `Tab Navigator`. However, each Tab in this navigator is in turn in its own `Stack Navigator` (which I believe the reason for not being able to see Params).
So when I log in `FirstTab` there are no Params passed. Can someone help ?

**Comment by nonameolsson** [comment] 2017-11-28 17:23
Thanks for opening this one again @spencercarli !

**Comment by tinOfBeans** [comment] 2017-11-28 19:26
Is there a solution to this? Tried all suggestions from above but nothing works. Im trying to pass props between two screens under DrawerNavigation.

**Comment by zeroFruit** [comment] 2017-12-08 05:06
I logged every navigation state (everytime I navigate to other screen) and made my own react-navigation helper functions.

```javascript
// MyComponent.js
const renderHeader = (params) => <Header params={ params } />;

class MyComponent extends Component {
  static navigationOptions = {
    header: ({ navigation }) => renderHeaderWithNavigation(navigation)(renderHeader)
  }

  componentDidMount() {
    const params = { ... };
    setParamsToNavigation(this.props, params);
  }
}
```

```javascript
// Router.js
export const navigateTo = (props, to, params = {}) => {
  props.navigation.navigate(to, params);
};

export const setParamsToNavigation = (props, params) => {
  props.navigation.setParams({ ...params });
};

export const renderHeaderWithNavigation = (navigation) => {
  const params = getParamsFromNavigationState(navigation.state);
  
  return (renderHeaderMethod) => {
    return renderHeaderMethod(params);
  };
};

// recursive function
export const getParamsFromNavigationState = (state) => {
  if (hasPath(state, 'index')) {
    const { index, routes } = state;
    return getParamsFromNavigationState(routes[index]);
  } else {
    return hasPath(state, 'params') ? state.params : null;
  }
};
```

And if I want to pass params to other screen as props, I used HOC
```javascript
export const mapNavigateParamsToProps = (WrappedComponent) => {
  return class MappedComponent extends Component {
    static navigationOptions = WrappedComponent.navigationOptions;

    render() {
      const { navigation } = this.props;
      const { state: { params } } = navigation;
      return <WrappedComponent { ...this.props } { ...params } />;
    }
  };
};
```

**Comment by kkkelicheng** [comment] 2018-01-02 12:49
I have a similar problem
My views structure like this
```
const MainView = TabNavigator(
    {
        Home: {
            screen:HomePage        
        },
        Tab2: {
            screen:Tab2     
        },
        Tab3:{
            screen:Tab2        
        }
    },
    configs
}

const navRoutes = {
    Main: {
        screen:MainView           
    },
    Other1:{
		screen:Other1
    },
    Other2:{
		screen:Other2
    },
}

export const MainNavigator =
    StackNavigator(navRoutes,configs)
}
```
Now in page `Other2`(from Home navigate Other1 and  navigate Other2).
```
const setParamsAction = NavigationActions.setParams({
            params: {title:"haha"},
            key: homePagekey
        });
        this.props.navigation.dispatch(
            setParamsAction
        );
```
When I goBack `Home`, I can not get params from navigation。
I guess `tabNavigator` and `stackNavigator` params  is not  related。
How can resolve this problem?

**Comment by Dror-Bar** [comment] 2018-01-10 09:22
I would like to share a similar problem where I couldn't pass params to my DrawerNavigator, as well as my solution. This is a specific case but it might help somebody.

## Before
Structure:
```
const MyStack = StackNavigator({
    Login: {screen: Login},
    Home: {screen: Home}
    // more screens...
});
export const MyDrawer = DrawerNavigator({
    Main: { screen: MyStack }
},
    { contentComponent: MyMenu }
);
```
In Home Screen:
```
openMenu() {
      this.props.navigation.navigate('DrawerOpen', userName);
 }
```
In MyMenu:
```
render() {
   const userName = this.props.navigation.state.params;
   return (
       <View>
              <Text>{userName}</Text>
              // more stuff
       </View>
    );
}
```
this.props.navigation.state.params is undefined.

I figured that you can only send navigation props when navigating to a new screen - 'DrawerOpen' does not count for this. To solve this I had to change my structure a little bit, instead of having the DrawerNavigator as the root drawer, I have a StackNavigator as the root drawer.
## After
```
const MyStack = StackNavigator({
  Home: {screen: Home},
  // more screens...
});

const MyDrawer = DrawerNavigator({
  Main: { screen: MyStack }
},
  { contentComponent: MyMenu }
);

export const RootStack = StackNavigator({
  Login: {screen: Login},
  Drawer: {
     screen: MyDrawer,
     navigationOptions: { header: null } } //Prevent double header
});
```
Now in Login screen I navigate to Drawer like this:
```
_login() {
    this.props.navigation.navigate('Drawer', { userName: userName });
}
```
In MyMenu (which is part of 'Drawer'):
```
render() {
  const { userName } = this.props.navigation.state.params;
  return (
    <View>
          <Text>{userName}</Text>
          // more stuff
    </View>
  );
}
```
It works!

**Comment by Diwei-Chen** [comment] 2018-01-29 07:21
We have a similar setting as https://github.com/react-navigation/react-navigation/issues/143#issuecomment-346996467

What we found is the latest version `1.0.0-beta.27` doesn't work, but version `1.0.0-beta.21` works for us.

**Comment by naomipol** [comment] 2018-01-29 07:49
I would like to share a work around for the problem I mentioned in my [comment](https://github.com/react-navigation/react-navigation/issues/143#issuecomment-312845034) above, maybe it will help somebody:

```js
// my stack navigator
const DocumentStack = StackNavigator({
    List: { screen: ListScreen },
    Details: { screen: DetailsScreen }
  },{
    initialRouteName: 'List',
  });

// create a wrapper component for stack navigator
// and pass params and rootNavigation via screenProps
// (solution!!!)
class DocumentsStackNav extends Component {
 render() {
  const { navigation } = this.props;
  return <DocumentStack 
	   screenProps={{
	        params: navigation.state.params,
	        rootNavigation: navigation
	  }}/>
}

// my drawer navigator - were 'Document' references the wrapper component
const MenuDrawer = DrawerNavigator({
  Home: { screen: HomeScreen },
  Document: { screen: DocumentsStackNav },
},
{
  initialRouteName: 'Home',
})

// now we can simply navigate to DocumentsStack passing params
navigation.navigate('Document', params)

// and access them in the ListScreen (initialRoute of DocumentStack)!!!!
// we also have access to the DrawerNavigator's navigation 
// if we would like to navigate to a different drawer item from here...
class ListScreen extends Component {
  render() {
    const { params, rootNavigation } = this.props.screenProps;
  }
}
```

This solution works great for me! No need for extra navigation action, and the most important, access params!!!

**Comment by brentvatne** [comment] 2018-02-10 19:47
I copied the exact code from the initial post into a Snack and it works as expected: https://snack.expo.io/HyhE2T38G

I imagine this has been resolved, please create a new issue and follow the updated issue template if you're still having problems! :)

**Closed by brentvatne** 2018-02-10 19:47 UTC
Labels: bug, help wanted

**Comment by wellyshen** [comment] 2018-02-11 08:28
I wrap my three stackNavigators in a TabNavigator. Then I pass a param from one of the stackNavigator through `navigation.navigate('DestinationRouteName', { ... })`. I can't get the passed param from the `DestinationRouteName` stackNavigator.

react-navigation: v1.0.0
react-native: v0.53.0
node: v9

**Comment by bartolkaruza** [comment] 2018-02-12 08:50
@wellyshen I'm sure you meant to tag someone else :)

**Comment by carlos-proogresa** [comment] 2018-02-13 08:23
Something very similar happens to me like @wellyshen, my provisional solution is to work with version **react-navigation@1.0.0-beta.21**

**Comment by sethnkruse** [comment] 2018-02-14 01:02
did the beta version allow you to pass params between nested navigators using state.props? @carlos-proogresa 

having trouble with this issue right now as well

**Comment by wellyshen** [comment] 2018-02-14 02:32
See I tell u guys!

**Comment by carlos-proogresa** [comment] 2018-02-14 16:02
@sethnkruse, I feel my English because I'm using a translator. I hope I'm answering your question.

I am currently passing parameters from one screen to another with the version I have discussed.

A piece of code from my _router.js_ file:

```
const HomeStack = StackNavigator({
  Home: { 
    screen: HomeContainer,
    navigationOptions: ({ navigation }) => ({  
      headerStyle: {
        backgroundColor: (navigation.state.params.section.backgroundColor),
      },
      headerTitleStyle: {
        color: 'white',
      },
      headerTintColor: 'white',      
    }),
  }, 

  
...


const HomeTabs = TabNavigator({
  HomeStack: { screen: HomeStack },
  ChatStack: { screen: ChatStack },
  ProfileStack: { screen: ProfileStack },
  NotificationStack: { screen: NotificationStack },
}, {
  navigationOptions: { 
    gesturesEnabled: false,
  },
  swipeEnabled: false, // TODO: Cambiar a true
  backBehavior: true,
  tabBarOptions: {
    showLabel: false,
  },
  initialRouteName: 'NotificationStack',
  headerMode: 'none',
});

export const RootStack = StackNavigator({
  Splash: { 
    screen: SplashContainer,
    navigationOptions: { header: null },
  },
  LoginStack: { screen: LoginStack },
  SectionStack: { screen: SectionStack },
  HomeTabs: { screen: HomeTabs },
}, {
  transitionConfig: () => ({
      screenInterpolator: (props) => (fade(props))
  }),
  headerMode: 'none',
  initialRouteName: 'Splash',
});
```

It all starts in _RootStack_ and from _Splash_ I navigate to _HomeTabs_ by passing parameters. _HomeTabs_ is a TabNavigator that contains _HomeStack_ and finally _Home_ is my screen where I consume these parameters. 

From _SplashScreen_ the code I use to navigate and send parameters:

```
const resetAction = NavigationActions.reset({
  index: 0,
  key: 'HomeTabs',
  actions: [ 
    NavigationActions.navigate({ routeName: 'HomeTabs', params: { section } })
  ]
});

navigation.dispatch(resetAction);
```

In _HomeScreen_ I use them with:

```
static navigationOptions = ({ navigation }) => ({    
    tabBarIcon: ({ focused, tintColor }) => (
      <MaterialIcon 
        name='store'
        size={ 25 }
        color={ focused ? navigation.state.params.section.backgroundColor : tintColor }
      />
    ),
});
```

And that's all, I hope it's understood.

**Comment by dihan** [comment] 2018-03-11 11:08
the issue I found with @carlos-proogresa method is that if you are using TabNavigator the screen does not go to that specific tab/stack but just another screen in its own stack.

**Comment by animaonline** [comment] 2018-03-16 19:29
Still getting this when navigating from one StackNavigator to another, this is easily reproducible so why is has the issue been closed?

**Comment by montao** [comment] 2018-03-18 17:20
Not working. I can clearly see that params are not being passed and that the state object does not contain the params object even though I set it. I tried everything. It is not working.

**Comment by aaron25mt** [comment] 2018-04-11 20:57
Has any found a solution to this issue? Have tried every solution in this thread and nothing's working for me.

**Comment by SoldierCorp** [comment] 2018-04-18 23:46
More than a year and still not fixed, wow!

**Comment by brentvatne** [comment] 2018-04-19 07:55
please create a new issue and follow the issue template, this one is old and before the current maintainers started working on it
