### ISSUE TITLE
Jerky transition on stack navigation when screen with hidden navigation bar pushes screen with a visible navigation bar (iOS only)

### ISSUE THREAD

**Issue by bkvirendra** [react-navigation/react-navigation#3415] opened 2018-02-03 04:13 UTC
### Current Behavior

- What code are you running and what is happening?
I am using the react navigation lib with the stack navigation (iOS only). I currently have a screen (home screen) that has its navigation bar hidden to provide more scrollable space. I have included the screenshot of my home screen. 
The tiles on the home screen are links to detail screen (as shown below). 
Issue: It seems on pushing the detail screen on stack upon the user click, the transition that occurs is strange. The react navigation adds the navigation bar (although it's only for the transition purpose) to the home screen. This is visible only during the transition animation when the user swipes back from the detail screen to go back to home screen (which is around a second or so). Have included the screenshot of the transition itself. The animation is jerky since the navigation bar is visible only during the transition & upon finishing it hides it from the screen.

- Include a screenshot if it makes sense.
(Home Screen)
![img_1617](https://user-images.githubusercontent.com/1097043/35762839-ad0cff68-0896-11e8-9488-9f24f3f2cc7f.PNG)

(Detail Screen)
![img_1619](https://user-images.githubusercontent.com/1097043/35762841-afdc59a0-0896-11e8-81a5-4a265c164500.PNG)

(Transition screenshot, from home screen to detail screen)
![img_1618](https://user-images.githubusercontent.com/1097043/35762836-a229f01a-0896-11e8-9633-e88aa6363271.PNG)

### Expected Behavior

- What do you expect should be happening?
I am not sure if this is the expected behaviour of the lib itself that, a screen with a hidden navigation bar pushing a screen with the navigation bar, requires to have the navigation bar shown for the transition. Is it possible to somehow to control this transition, so it hides this jerky transition? 

### How to reproduce
Include a root screen with the navigation bar hidden & push a screen with the navigation bar visible. The jerky transition of showing navigation bar & hiding that occurs between the push & also the swipe back is the issue. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.49
| node             | 8.9.4
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment] 2018-02-03 17:52
@bkvirendra - thanks for the info! could you possibly post a video recording of this? It's hard to see from the screenshots

**Comment by kelset** [comment] 2018-02-03 18:17
Looks to me like a duplicate of https://github.com/react-navigation/react-navigation/issues/2732 - if so please @bkvirendra close this issue and comment on the other one to reduce redundancy.

**Closed** 2018-02-03 19:08 UTC
Labels: needs more info
