### ISSUE TITLE
refreshing & onRefresh property for FlatLists not working for 3.12.1

### ISSUE THREAD

**Issue by bobber205** [react-navigation/react-navigation#6232] opened 2019-08-29 16:42 UTC
### Current Behavior
Upgraded to 3.12.1 yesterday morning without much thought. Eventually I tracked down that day's new bug of all loading spinners for our Flatlists and refreshing by pulling down on our refresh lists suddenly stopped working. Downgrading to 3.12.0 fixed the issue.

`onRefresh` wasn't even being called when pulling down, though the "space" was created above the list like normal. Setting refreshing to true when initially loading data was also broken.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest 0.16.x
| node             | 11.x
| npm or yarn      | latest yarn

**Comment by matthamil** [comment] 2019-09-02 18:07
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Thanks!

**Comment by satya164** [comment] 2019-09-16 10:54
Closing due to no repro. Please post a minimal runnable repro if you think this is still an issue.

**Closed by satya164** 2019-09-16 10:54 UTC
Labels: needs repro
