### ISSUE TITLE
Unable to pass params to DrawerNavigator

### ISSUE THREAD

**Issue by Dror-Bar** [react-navigation/react-navigation#3250] opened 2018-01-09 15:27 UTC
Greetings,

Using react-navigation, I can easily pass params using this.props.navigation.navigate('screenName', params), and then getting those params using this.props.navigation.state.params. But this is not possible with DrawerNavigator.

---

### Current Behavior
My structure looks like this:
```
import MyMenu from './MyMenu';

const MyStack = StackNavigator({
    Login: {screen: Login},
    Home: {screen: Home}
    // more screens...
});
export const MyDrawer = DrawerNavigator({
    Main: { screen: MyStack }
},
    { contentComponent: MyMenu }
);
```
In Login screen I have a login function - on successful login the user navigates to Home screen with user name as param. When the user opens the menu I want a text to show the user name.

in Home screen I have the function:
```
openMenu() {
      this.props.navigation.navigate('DrawerOpen', userName);
 }
```
In MyMenu I have:
```
render() {
   const userName = this.props.navigation.state.params;
   return (
       <View>
              <Text>{userName}</Text>
              // more stuff
       </View>
    );
}
```
But this.props.navigation.state.params is undefined.

### Expected Behavior
this.props.navigation.state.params should be defined in DrawerNavigation.

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.51.0
| node             | v8.9.1
| npm or yarn      | npm 5.6.0

**Comment by kelset** [comment] 2018-01-09 16:15
Duplicate of https://github.com/react-navigation/react-navigation/issues/143

**Closed by kelset** 2018-01-09 16:15 UTC

**Comment by Dror-Bar** [comment] 2018-01-10 09:08
Alright, after spending so much time on this, I finally found a solution. Simply put, you can only send navigation props when navigating to a new screen - 'DrawerOpen' does not count for this.

To solve this I had to change my structure a little bit, instead of having the DrawerNavigator as the root drawer, I have a StackNavigator as the root drawer.

Before:
```
const MyStack = StackNavigator({
  Login: {screen: Login},
  Home: {screen: Home}
  // more screens...
});

export const MyDrawer = DrawerNavigator({
  Main: { screen: MyStack }
},
  { contentComponent: MyMenu }
);
```
After:
```
const MyStack = StackNavigator({
  Home: {screen: Home},
  // more screens...
});

const MyDrawer = DrawerNavigator({
  Main: { screen: MyStack }
},
  { contentComponent: MyMenu }
);

export const RootStack = StackNavigator({
  Login: {screen: Login},
  Drawer: { screen: MyDrawer }
});
```
Now in Login screen I navigate to Drawer like this:
```
_login() {
    this.props.navigation.navigate('Drawer', { userName: userName });
}
```
And finally in MyMenu (which is part of 'Drawer'):
```
render() {
  const { userName } = this.props.navigation.state.params;
  return (
    <View>
          <Text>{userName}</Text>
          // more stuff
    </View>
  );
}
```
It works!

**Comment by Sasikiran234reddy** [comment] 2018-07-20 12:39
can you please send me code for this actions 
I have implemented all the way as you said again it is alerting with the same error.............. please help me guide me to succeed  in this 
my Gmail:  sasikiranreddy001@gmail.com
please mail me about passing params to drawer..

**Comment by Dror-Bar** [comment] 2018-07-22 07:32
I've posted all of the relevant code - could you post here your code for:

1) Routers
2) Drawer component

You are using a custom contentComponent for menu right?

**Comment by Sasikiran234reddy** [comment] 2018-07-22 07:54
Hi

 I am using custom component  in  app.js and in the return statement I am
returning the drawermenu

Could you please help me

**Comment by serpel** [comment] 2018-11-26 02:30
> Alright, after spending so much time on this, I finally found a solution. Simply put, you can only send navigation props when navigating to a new screen - 'DrawerOpen' does not count for this.
> 
> To solve this I had to change my structure a little bit, instead of having the DrawerNavigator as the root drawer, I have a StackNavigator as the root drawer.
> 
> Before:
> 
> ```
> const MyStack = StackNavigator({
>   Login: {screen: Login},
>   Home: {screen: Home}
>   // more screens...
> });
> 
> export const MyDrawer = DrawerNavigator({
>   Main: { screen: MyStack }
> },
>   { contentComponent: MyMenu }
> );
> ```
> After:
> 
> ```
> const MyStack = StackNavigator({
>   Home: {screen: Home},
>   // more screens...
> });
> 
> const MyDrawer = DrawerNavigator({
>   Main: { screen: MyStack }
> },
>   { contentComponent: MyMenu }
> );
> 
> export const RootStack = StackNavigator({
>   Login: {screen: Login},
>   Drawer: {
>     screen: MyDrawer,
>     navigationOptions: { header: null } } //Prevent double header
> });
> ```
> Now in Login screen I navigate to Drawer like this:
> 
> ```
> _login() {
>     this.props.navigation.navigate('Drawer', { userName: userName });
> }
> ```
> And finally in MyMenu (which is part of 'Drawer'):
> 
> ```
> render() {
>   const { userName } = this.props.navigation.state.params;
>   return (
>     <View>
>           <Text>{userName}</Text>
>           // more stuff
>     </View>
>   );
> }
> ```
> It works!

You are my Hero!!!!

**Comment by rochebleue** [comment] 2018-12-04 13:14
I copied your code but I can't manage to make it work, and I don't see any difference.

App.js : 
`
const MyStack = createStackNavigator({
  Home: {screen: HomeScreen},
  // more screens...
});

const MyDrawer = createDrawerNavigator({
  Main: { screen: MyStack }
},
  { contentComponent: DrawerMenu }
);

export const RootStack = createStackNavigator({
  Login: {screen: LoginScreen},
  Drawer: {
    screen: MyDrawer,
    navigationOptions: { header: null } } //Prevent double header
});

const AppContainer = createAppContainer(RootStack);

export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
}
`

Login page : 
` _loginToApi() {
    this.props.navigation.navigate('Drawer', { userName: 'userName' });
}`

and : 
`        <Button
          title="Login-"
          onPress={ () => this._loginToApi() }
        />`

Homescreen : 
`
  render() {
      const  userName  = this.props.navigation.getParam('userName', '0');
  return (
    <View>
          <Text>{userName}</Text>
    </View>
  );
}`

I've been on it for two days.

**Comment by serpel** [comment] 2018-12-04 13:21
> I copied your code but I can't manage to make it work, and I don't see any difference.
> 
> App.js :
> 
> ```
> 
> const MyStack = createStackNavigator({
>   Home: {screen: HomeScreen},
>   // more screens...
> });
> 
> const MyDrawer = createDrawerNavigator({
>   Main: { screen: MyStack }
> },
>   { contentComponent: DrawerMenu }
> );
> 
> export const RootStack = createStackNavigator({
>   Login: {screen: LoginScreen},
>   Drawer: {
>     screen: MyDrawer,
>     navigationOptions: { header: null } } //Prevent double header
> });
> 
> const AppContainer = createAppContainer(RootStack);
> 
> export default class App extends React.Component {
>   render() {
>     return <AppContainer />;
>   }
> }
> ```
> Login page :
> 
> ```
>  _loginToApi() {
>     this.props.navigation.navigate('Drawer', { userName: 'userName' });
> }
> ```
> and :
> 
> ```
> <Button
>           title="Login-"
>           onPress={ () => this._loginToApi() }
>         />
> ```
> Homescreen :
> 
> ```
>   render() {
>       const  userName  = this.props.navigation.getParam('userName', '0');
>   return (
>     <View>
>           <Text>{userName}</Text>
>     </View>
>   );
> }
> ```
> I've been on it for two days. I get '0' as a result on the HomeScreen.
> 
> Note : when I use :
> `const { userName } = this.props.navigation.state.params;`
> 
> I get the error "undefined is not an object". I don't know if it's related.

I have something like that, maybe can help you https://github.com/Grintsys/WISApp/blob/master/App/Navigation/AppNavigation.js

**Comment by Dror-Bar** [comment] 2018-12-04 13:30
@rochebleue 
My example was for react-navigation pre 2.x, yours is 3.x. It's very possible a small change in syntax or something similar changes the behaviour. Regardless, it should definitely be possible in the new version. It's hard for me to say on top of my head what's wrong with your code. I see you are trying to access the param from "HomeScreen". Can you access it from "DrawerMenu"?

**Comment by rochebleue** [comment] 2018-12-04 14:17
Thanks for your replies.

@Dror-Bar 

I've managed to get the variable in HomeScreen, writing : 
```
 _loginToApi() {
    this.props.navigation.navigate('Home', { test: 'toto' });
}
```
Instead of
```
 _loginToApi() {
    this.props.navigation.navigate('Drawer', { test: 'toto' });
}
```
The infortunate thing is, my drawer won't open now, so I cannot check if the variable is available inside of it.

@serpel 
Thanks for your code. I've implemented it, reducing and adapting it.

App.js
```
import { StackNavigator, TabNavigator } from "react-navigation"

const TabStack =  createStackNavigator({
  BeastList: { screen: HomeScreen },
  }
)

const MyDrawer = createDrawerNavigator(
  {
    Home: { screen: TabStack }
  },
  { contentComponent: DrawerMenu }
)

const RootStack = createStackNavigator({
  Login: { screen: LoginScreen },
  Drawer: {
    screen: MyDrawer,
    navigationOptions: { header: null },//Prevent double header
  }
})

const AppContainer = createAppContainer(RootStack);

export default AppContainer;
```

Login 
```
_loginToApi() {
      this.props.navigation.navigate(
        'BeastList', 
      {
        test: 'titi',
      }
      );
  }
}
```

Home
```
    const  test  = this.props.navigation.getParam('test', '0');
  

    return (
      <View style={{ flexDirection: "column", flex: 1}}>
      <Text>{test}</Text>
```

The variable is passed to BeastList screen but the drawer won't open anymore.

**Comment by Dror-Bar** [comment] 2018-12-04 14:35
The drawer won't open because you're navigating directly to the screen, bypassing the Drawer. So you don't really wanna do that.

**Comment by rochebleue** [comment] 2018-12-04 14:57
Oh, I see.

So, I put my previous code again 

```
this.props.navigation.navigate(
        'Drawer', 
      {
        userToken: responseJson.data.token,
        userId: responseJson.data.id,
        userName: responseJson.data.pseudo,
        userMoney: responseJson.data.money,
        userLevel: responseJson.data.level,
        userXp: responseJson.data.current_xp,
        userDiamonds: responseJson.data.diamonds,
        test: 'titi',
      }
```

As a result, absolutely none of the props is passed to the screen.
And the drawer still won't open.

**Comment by Dror-Bar** [comment] 2018-12-04 15:00
@rochebleue 
You seem to have issues other than passing params. But I don't understand one thing - did the drawer open before and now it doesn't? or did it never open?

**Comment by rochebleue** [comment] 2018-12-04 15:05
@Dror-Bar 

The drawer opened before - When I had my own navigation in AppJs : 
```
// Sub stacks
const DocumentScreens = createStackNavigator(
  {
    EntryDoc: EntryDocsScreen,
    Forum: ForumScreen,
    FAQ: FAQScreen,
    TopicList: TopicListScreen,
    TopicContent: TopicContentScreen
  },
  {
    defaultNavigationOptions: {headerRight: ( <CustomHeader test={'testa'} /> )}
  }
);
const ShopScreens = createStackNavigator(
  {
    EntryMarket: EntryShopScreen,
    Market: MarketScreen
  },
  {
    defaultNavigationOptions: {headerRight: ( <CustomHeader test={'testb'} /> )}
  }
);
const HomeScreens = createStackNavigator(
  {
    BeastList: HomeScreen,
    ViewBeast: ViewBeastScreen
  },
  {
    defaultNavigationOptions: {headerRight: ( <CustomHeader test={'testc'} /> )}
  }
);
const InventoryScreens = createStackNavigator(
  {
    Main: InventoryScreen
  }
);
// Main drawers
const Drawers = createDrawerNavigator(
  {
    Home: {screen: HomeScreens},
    Markets: ShopScreens,
    Inventory: InventoryScreens,
    Documents: DocumentScreens
  },
  {
    drawerPosition: 'right',
    drawerType: 'front',
    drawerWidth: 100,
    defaultNavigationOptions: {
      headerRight: ( <CustomHeader test={'teste'} /> )
    },
    contentComponent: DrawerMenu
  }
);


// Login page
const Root = createStackNavigator(
  {
    Login: LoginScreen,
    Home: Drawers
  },
  {
    initialRouteName: "Login",
    headerMode: 'none',
    navigationOptions: {
      headerVisible: false
    }
  }
);

const AppContainer = createAppContainer(Root);


export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
}
```

Back then, I navigated directly to BeastList in my _loginToApi() function.
I was able to get the drawer and all the props passed in the second argument.
However, the drawer itself didn't get any prop, all of them were undefined.

**Comment by Dror-Bar** [comment] 2018-12-04 15:18
You don't need so many StackNavigators inside Drawers. Try to make a single StackNavigator for all the internal screens and use it in Drawers. For example:

```
const SubStacks = createStackNavigator(
  {
    EntryDoc: EntryDocsScreen,
    Forum: ForumScreen,
    FAQ: FAQScreen,
    TopicList: TopicListScreen,
    TopicContent: TopicContentScreen,
    EntryMarket: EntryShopScreen,
    Market: MarketScreen,
    BeastList: HomeScreen,
    ViewBeast: ViewBeastScreen,
    Main: InventoryScreen
  },
  {
    defaultNavigationOptions: {headerRight: ( <CustomHeader/> )}
  }
);
```
And inside Drawers:
```
const Drawers = createDrawerNavigator(
  {
    SubStacks: SubStacks
  },
  {
    drawerPosition: 'right',
    drawerType: 'front',
    drawerWidth: 100,
    defaultNavigationOptions: {
      headerRight: ( <CustomHeader /> )
    },
    contentComponent: DrawerMenu
  }
);
```
Notice I also changed the route "Home" inside Drawers to "SubStacks" because there was already a route called "Home" in the Root StackNavigator and that could possibly have caused problems. After doing this try navigating to "Home" again and passing props and see if you can access them.

**Comment by rochebleue** [comment] 2018-12-04 15:52
@Dror-Bar 
It's much more readable, thank you very much.
However, when I navigate to "Home" from Login page, not a single prop is passed unless I directly call "BeastList" in this.props.navigation.navigate() (which you told me, I shouldn't do).

**Comment by Dror-Bar** [comment] 2018-12-04 16:33
I just checked the snack and I have no idea why it doesn't work. It definitely works with this structure in React Navigation 2.x (which I'm using right now).

So, it's possible there's a bug in 3.x. Now that you have a snack I suppose a maintainer can look at this.

**Comment by Dror-Bar** [comment] 2018-12-04 16:36
@kelset

**Comment by kelset** [comment] 2018-12-04 16:52
Well, given that I closed this issue almost a year ago, I'd suggest to open a new issue, following the template, with a minimal repro (since, also, when this issue was open we were in v1.x and now it's 3.x)

**Comment by rochebleue** [comment] 2018-12-04 17:03
Thanks, I'll do it.
