### ISSUE TITLE
Hiding Tab Bar Dynamically

### ISSUE THREAD

**Issue by joecaraccio** [react-navigation/react-navigation#3270] opened 2018-01-13 14:24 UTC
I have seen Issue threads on this in the past, but are there any current solutions to hiding the tab bar dynamically? I know you can hide it for a preset tab view, but is there a solution with say redux?

**Comment by kelset** [comment] 2018-01-15 09:10
Duplicate of https://github.com/react-navigation/react-navigation/issues/888

**Closed by kelset** 2018-01-15 09:10 UTC
