### ISSUE TITLE
Conflict with KeyboardAvoidingView

### ISSUE THREAD

**Issue by khudratov** [react-navigation/react-navigation#9884] opened 2021-08-28 14:19 UTC
### Current behavior

When i open keyboard input must go to top with keyboard but input go to top with -(navigation header) in iPhone 12 

https://user-images.githubusercontent.com/58653980/131220931-a8608958-cfd1-47b9-85e3-5459e192f5c0.mov

when i hide header it works correctly

### Expected behavior

input must go to top with keyboard when keyboard opening

### Reproduction

https://github.com/khudratov/bug-navigation.git

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by raajnadar** [comment] 2021-08-28 18:02
https://reactnative.dev/docs/keyboardavoidingview#keyboardverticaloffset

Pass the header height to this prop.

https://reactnavigation.org/docs/elements/#useheaderheight

**Comment by khudratov** [comment] 2021-08-28 18:25
thx you raajnadar it helped but useheaderheight when state updates firstly return zero its hide my input too.

**Comment by AshotN** [comment] 2022-01-18 23:53
@raajnadar I am experiencing a similar issue, using `useHeaderHeight` on an iPhone 13 Pro simulator.

At first the function returns 103 which is correct, but then it returns 56. The 56 causes a portion of the View to be behind the keyboard

For some further context, this is happening inside a modal

**Comment by raajnadar** [comment] 2022-01-19 10:54
I am closing this as this is not a bug in the library, it is mostly due to how the screens are designed. In most cases this is due to improver height calculation so the keyboard does not get correct value to offset.

**Closed by raajnadar** 2022-01-19 10:54 UTC
Labels: bug, package:stack, platform:ios, repro provided
