### ISSUE TITLE
TypeError: undefined is not an object (evaluation_native.NavigationhelpersContext.Provider

### ISSUE THREAD

**Issue by ajiehatajie** [react-navigation/react-navigation#8225] opened 2020-05-09 20:05 UTC
Error same for  Material Bottom Tab Navigator and  createMaterialTopTabNavigator

```
Fatal Error: TypeError undefined is not an object (evaluating _native.NavigationHelpersContext.Provider )
```

```
import * as React from 'react';
import {Text, View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

function HomeScreen() {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Settings!</Text>
    </View>
  );
}

const Tab = createMaterialBottomTabNavigator();
export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator
        initialRouteName="Feed"
        activeColor="#e91e63"
        style={{backgroundColor: 'tomato'}}>
        <Tab.Screen
          name="Feed"
          component={HomeScreen}
          options={{
            tabBarLabel: 'Home',
            tabBarIcon: ({color}) => (
              <MaterialCommunityIcons name="home" color={color} size={26} />
            ),
          }}
        />
        <Tab.Screen
          name="Notifications"
          component={SettingsScreen}
          options={{
            tabBarLabel: 'Updates',
            tabBarIcon: ({color}) => (
              <MaterialCommunityIcons name="bell" color={color} size={26} />
            ),
          }}
        />
        <Tab.Screen
          name="Profile"
          component={SettingsScreen}
          options={{
            tabBarLabel: 'Profile',
            tabBarIcon: ({color}) => (
              <MaterialCommunityIcons name="account" color={color} size={26} />
            ),
          }}
        />
      </Tab.Navigator>
    </NavigationContainer>
  );
}


```
OS Windos 10
version
```
"react-native": "0.62.2",
"@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/google-signin": "^4.0.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.8.0",
    "@react-native-firebase/app": "^6.7.1",
    "@react-native-firebase/dynamic-links": "^6.7.1",
    "@react-navigation/bottom-tabs": "^5.2.7",
    "@react-navigation/compat": "^5.1.9",
    "@react-navigation/drawer": "^5.5.0",
    "@react-navigation/material-bottom-tabs": "^5.2.1",
    "@react-navigation/material-top-tabs": "^5.2.1",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.13",
 "react-native-paper": "^3.10.1",
    "@react-navigation/material-bottom-tabs": "^5.2.1",
```

**Comment by ajiehatajie** [comment] 2020-05-10 09:06
Done Update to Latest Version

**Comment by radadiyarushita** [comment] 2020-05-10 17:31
Fixed I've updated the yarn version.
`yarn upgrade`

**Comment by raajnadar** [comment] 2020-05-11 05:55
Closing since the issue is resolved!

**Closed by raajnadar** 2020-05-11 05:55 UTC
Labels: bug, package:material-bottom-tabs

**Comment by robindesu** [comment] 2020-07-08 16:21
After the upgrade I had to install "@react-native-community/toolbar-android" and run the pod install.
