### ISSUE TITLE
Theme change not being applied to header of NativeStack for `presentation: "modal"`

### ISSUE THREAD

**Issue by JacobJaffe** [react-navigation/react-navigation#10206] opened 2021-12-21 05:07 UTC
### Current behavior

When changing themes on iOS, the theme is not applied to the header of a NativeStack Screen which is behind a `presentation: "modal"` screen. This only applies to the screen *directly behind the modal screen* -- e.g. If a modal is in front of two tabs, only the in-focus tab has this issue. Additionally, the issue goes away after swapping to a different screen and back again.

It works correctly on other presentations. 

I've attempted to hack around this by directly setting the `options: { headerStyle }`, however this doesn't fix it -- it seems like the header just isn't getting triggered to rerender at *all* when under the modal screen. 

I've included a Snack of this behavoir, here's the code:

<details>
  <summary>Code Reproduction</summary>

```js
import * as React from 'react';
import { Text, View, Switch, TouchableOpacity, StyleSheet } from 'react-native';

import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { DefaultTheme, DarkTheme } from '@react-navigation/native';

const Stack = createNativeStackNavigator();

export default function App() {
  const [theme, setTheme] = React.useState('light');
  return (
    <NavigationContainer theme={theme === 'dark' ? DarkTheme : DefaultTheme}>
      <Stack.Navigator>
        <Stack.Screen
          name="Home"
          component={({ navigation }) => (
            <View style={styles.Container}>
              <TouchableOpacity
                style={styles.Button}
                onPress={() => {
                  navigation.navigate('Settings');
                }}>
                <Text> Open Settings </Text>
              </TouchableOpacity>
            </View>
          )}
        />
        <Stack.Screen
          options={{
            presentation: 'modal',
          }}
          name="Settings"
          component={() => (
            <View style={styles.Container}>
              <Text> Dark Mode: </Text>
              <Switch
                value={theme === 'dark'}
                onValueChange={(isDark) =>
                  void setTheme(isDark ? 'dark' : 'light')
                }
              />
            </View>
          )}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

const styles = StyleSheet.create({
  Container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Button: {
    padding: 12,
    backgroundColor: 'gray',
    borderWidth: 1,
    borderRadius: 12,
    width: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```
</details>

### Expected behavior

The theme provider should update the header component of the screen underlying the modal-presentation screen.

### Reproduction

https://snack.expo.dev/@jacobjaffe/react-navigation---presentation-modal-theme-bug

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.0.6"
| @react-navigation/native-stack         | "^6.2.5"

**Comment by JacobJaffe** [comment] 2021-12-21 23:55
![2021-12-20 20 55 28](https://user-images.githubusercontent.com/25315679/147012473-0451eb0e-ef40-4b1b-9492-a470a753618b.gif)

^ Here's a GIF of the bug.

**Comment by satya164** [comment] 2021-12-22 10:50
cc @WoLewicki

**Comment by WoLewicki** [comment] 2021-12-22 12:48
I believe it is a duplicate of https://github.com/software-mansion/react-native-screens/issues/1225, so I will close it. The proposed fix can be found in connected PR. If it does not work, please comment the mentioned issue.

**Closed by WoLewicki** 2021-12-22 12:48 UTC
Labels: bug, platform:ios, repro provided, package:native-stack

**Comment by JacobJaffe** [comment] 2021-12-22 17:01
Ah, yeah, that's the same issue. Thank you sharing that!
