### ISSUE TITLE
React navigation shows blank screen

### ISSUE THREAD

**Issue by Digant312** [react-navigation/react-navigation#3333] opened 2018-01-23 06:21 UTC
I'm using "react-navigation" with Expo app building environment, and I got blank screen, no any error just blank screen.

Here's my code for `App.js` 
```import Expo from 'expo';
import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { TabNavigator, StackNavigator } from 'react-navigation';

import AuthScreen from './screens/AuthScreen';
import WelcomeScreen from './screens/WelcomeScreen';
import DeckScreen from './screens/DeckScreen';
import MapScreen from './screens/MapScreen';
import ReviewScreen from './screens/ReviewScreen';
import SettingsScreen from './screens/SettingsScreen';

class App extends Component {
  render() {
    const MainNavigator = TabNavigator({
      welcome: { screen: WelcomeScreen },
      auth: { screen: AuthScreen},
      main: {
        screen: TabNavigator({
          map: { screen: MapScreen},
          deck: {screen: DeckScreen}, 
          review: {
            screen: StackNavigator({
              review: { screen: ReviewScreen},
              setting: {screen: SettingsScreen}
            })
          }
        })
      }
    });


    return (
      <View style={styles.container}>
        <MainNavigator /> 
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex:1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default App;
```

Developement environment:

    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
    "react-navigation": "^1.0.0-beta.27"

Can you please help me to solve this out?

Thanks!

**Comment by bingxuelover** [comment] 2018-01-23 07:16
I always write "const MainNavigator" outside the class component. Are you sure WelcomeScreen is not blank.

**Comment by kelset** [comment] 2018-01-23 08:38
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-23 08:38 UTC

**Comment by Digant312** [comment] 2018-01-23 09:19
@bingxuelover , thanks for the reply, WelcomeScreen has <Text> element and ir works when I show it, but when I'm using it with react-navigation it doesn't working.

Here's code of project:
https://digant_im@bitbucket.org/digant_im/job_search.git

**Comment by Digant312** [comment] 2018-01-23 09:21
@kelset , thanks for the reply,  here's the Expo preview link:
https://expo.io/@digant312/jobsearch

**Comment by Digant312** [comment] 2018-01-23 10:02
I got the solution.
I've applied alignItems: 'center' styling to container , which is default styling in Expo application, 
I removed it, and it's working perfect.

**Comment by rafaelpizzaia** [comment] 2018-05-11 15:03
@Digant312, same issue here. Removing the alignItems from app style worked for me too!

**Comment by monsiong123** [comment] 2018-08-08 16:46
@Digant312 you commit your code to bitbucket ? I still can't run on my android by referring to your code in bitbutket.

**Comment by Johncy1997** [comment] 2018-09-26 05:43
In my case, before loading the initialroute, the app shows blank screen for 2 or 3 seconds. The initial component loading takes time i think. Can someone tell me, what should i do to remove the blank screen.

**Comment by brayanL** [comment] 2019-03-07 22:04
I had the same black screen working with createSwitchNavigator, i set `backgroundColor: '#fff'` on the root app thats, works like a charm, that is a very weird mistake.

**Comment by pavlo-paliychuk-insighty** [comment] 2019-06-01 15:09
@Johncy1997 you could do SplashScreen.hide() when the loading stops so that you don't see any blank screens.

**Comment by wasiqkhan** [comment] 2020-10-08 18:49
removing alignItems:"center" will fix it

**Comment by MananDesai54** [comment] 2021-01-17 09:14
finding solution from 1hr finally got it

**Comment by kylemccurley** [comment] 2021-01-19 14:05
What finally worke for me was removing `<SafeAreaView>` from my component. After replacing `SafeArea`, it returned to behaving as normal

**Comment by Elektropepi** [comment] 2021-02-13 18:41
For me the root View didn't have any height, so I needed to add `flex: 1` to the styles.

**Comment by Danc-0** [comment] 2022-07-24 22:03
> For me the root View didn't have any height, so I needed to add `flex: 1` to the styles.

Thanks. This one worked for me too.

**Comment by lhh3105** [comment] 2024-03-26 02:05
> @Digant312bạn cam kết mã của mình với bitbucket? Tôi vẫn không thể chạy trên Android của mình bằng cách tham khảo mã của bạn trong bitbutket. Và cũng xóa AlignItems: 'center'

you found the solution for this. i also meet this problem and stucking in it. Can you help me?

**Comment by Ra3bl** [comment] 2024-07-10 14:21
the solution is to separete Auth Cheking file and root file  (app.tsx ) :


**Auth Cheking File  - routes/AppRoutes.tsx**

```
const AppRoutes = () => {
  const { isLoading, isAuthenticated } = useAppSelector((state) => state.auth);
  const dispatch = useAppDispatch();

  useEffect(() => {
    const checkAuth = async () => {
      await dispatch(checkAuthStatus());
    };
    checkAuth();
    
  }, [dispatch]);


  if (isLoading) {
    return <SplashScreen />;
  }

  if (!isAuthenticated) {
    return <AuthStackNavigator />;
  }

  return <MainStackNavigator />;
  
};
```

**Root App File  -   ./App.tsx**

```
App = ( ) => {
 ...
...
 return (
    <Provider store={Store}>
      <StatusBar barStyle="dark-content" translucent backgroundColor="transparent" />
	  <NavigationContainer
      theme={{
        ...DefaultTheme,
        colors: { ...DefaultTheme.colors, background: 'rgb(255, 255, 255)' },
      }}
      linking={linking}>

      <AppRoutes />
	  </NavigationContainer>
    </Provider>
  );
}
```

### NOTE : do not use <NavigationContainer> at the Auth checking file this wath fire this problem ( blank screen )
