### ISSUE TITLE
Unable to pass params on web

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#2563] opened 2017-09-10 01:08 UTC
In order to get this library working on web, I've copied `BrowserAppContainer.js` directly from the react navigation website source code as instructed to do so via several other issue threads. I've finally got it working, but when I navigate to a screen and pass a params object into the `navigation.navigate` method, the params are not showing up on the destination screen:

```js
// origin screen
navigation.navigate(SOME_SCREEN, {some: 'params'});

// destination screen
console.log(navigation.state.params) // undefined
```

Is it possible to pass `params` on websites? If so, how? Is there an additional tweak that I need to make to [`BrowserAppContainer.js`](https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js) to make this happen?

**Comment by spencercarli** [comment] 2017-09-12 01:16
I've never used it on the web before but my guess would be that params aren't being passed in the getStateForAction function. Check out the the [`StackRouter`](https://github.com/react-community/react-navigation/blob/master/src/routers/StackRouter.js#L92)'s - maybe you'll be able to spot the difference

**Comment by kelset** [comment] 2017-12-10 12:55
Pinging OP @joncursi since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

(and, as already stated in other issues, web is currently frozen)

**Comment by joncursi** [comment] 2017-12-10 16:13
Still an issue on latest version

**Comment by remon-georgy** [comment] 2017-12-22 22:51
I can confirm that props passed by `navigate` are _not_ accessible through `navigation.state.params`, on web.

**Comment by brentvatne** [comment] 2018-02-10 20:09
we don't officially support web at the moment, sorry.

**Closed by brentvatne** 2018-02-10 20:09 UTC
Labels: bug, web
