### ISSUE TITLE
Drawer changes in #1803 causes undocumented breaking changes to drawernavigators

### ISSUE THREAD

**Issue by sebirdman** [react-navigation/react-navigation#3148] opened 2017-12-19 01:29 UTC
### Current Behavior
- create a single drawer navigator in beta 22
- do not specify drawerOpenRoute, drawerCloseRoute, or drawerToggleRoute in the drawer changes

### Expected Behavior
- drawerOpenRoute, drawerCloseRoute, and drawerToggleRoute should have a default set that matches the previous routes defined in beta 21
- alternatively, i would expect that this change would be documented as either a breaking change in release notes, or at described in react-navigation docs.

**Comment by HunDunDM** [comment] 2017-12-19 04:03
I think this [PR](https://github.com/react-community/react-navigation/pull/3151) is useful. But I don't know how to deal with the errors about `flow`.

**Comment by HunDunDM** [comment] 2017-12-19 06:13
The problem is that if you do not set `DrawerNavigatorConfig` when you are using it, then `drawerOpenRoute`, `drawerCloseRoute` and `drawerToggleRoute` will be set by default. But if you set other parameters when you originally used it, like `contentComponent`, you have to manually set the above three parameters. I do not think this is the desired effect.

**Comment by benevbright** [comment] 2017-12-19 14:48
+1

>  I do not think this is the desired effect.

**Comment by sonaye** [comment] 2017-12-19 14:49
Adding
```javascript
drawerOpenRoute: 'DrawerOpen',
drawerCloseRoute: 'DrawerClose',
drawerToggleRoute: 'DrawerToggle'
```
to the drawer configs fixed the issue for me.

**Comment by benevbright** [comment] 2017-12-19 14:51
Thanks @sonaye it works.

**Comment by bourgois** [comment] 2017-12-19 14:59
`Adding

drawerOpenRoute: 'DrawerOpen',
drawerCloseRoute: 'DrawerClose',
drawerToggleRoute: 'DrawerToggle'
to the drawer configs fixed the issue for me.`

**Comment by TheMarsGuy** [comment] 2017-12-19 15:51
This also happens in 1.0.0-beta.19.

**Comment by outaTiME** [comment] 2017-12-19 17:40
update will be released soon?

**Comment by wachunei** [comment] 2017-12-19 18:40
I think this might be related. Some recent merges have been bringing a lot of errors. 
https://github.com/react-community/react-navigation/issues/3148

**Comment by wookelvin** [comment] 2017-12-19 22:54
This absolutely fixed it for me. Thanks.

**Comment by meetajhu** [comment] 2017-12-20 08:58
@sonaye 

Thanks

What i did

```
const MainDrawerExample = DrawerNavigator({
  Drafts: {
    screen: DrawerExample,
  },
}, {
headerMode: 'screen',
  drawerPosition: 'right',
 drawerOpenRoute: 'DrawerOpen',
drawerCloseRoute: 'DrawerClose',
drawerToggleRoute: 'DrawerToggle',
});
```

**Comment by Longsight** [comment] 2017-12-20 16:47
I think the issue here is that the default route names are now defined in the `config` object's defaults, which by convention should be an empty object, as **any** DrawerNavigatorConfig object overrides them whether it then defines sensible values or not. Since `config` is merged with `DefaultDrawerConfig` in DrawerNavigator.js, there's no reason these default names shouldn't be on `DefaultDrawerConfig` instead.

**Comment by loo41** [comment] 2017-12-25 09:05
Thank you, this bug has bothered me for two days

**Comment by loo41** [comment] 2017-12-25 09:06
Version upgrade, good pit

**Comment by DavidBabel** [comment] 2017-12-25 12:14
Thanks for the help, lost a log of time in the documentation for this issue.
This need a way better documentation.

**Comment by kelset** [comment] 2017-12-29 10:08
> This need a way better documentation.

I've actually modified the Release Notes for this version to mention this change - https://github.com/react-navigation/react-navigation/issues/3149#issuecomment-353749560

**Comment by cyphire** [comment] 2017-12-29 16:25
Good catch, this worked for me.

drawerOpenRoute: 'DrawerOpen',
drawerCloseRoute: 'DrawerClose',
drawerToggleRoute: 'DrawerToggle'

**Comment by WilliamAnputra** [comment] 2018-01-02 07:02
Thanks man, you saved me.

**Comment by zhouyingkai1** [comment] 2018-01-09 02:58
thanks

**Comment by kelset** [comment] 2018-01-09 12:22
Quick update, we have merged a PR to master that should fix this issue (#3152)

**Comment by ilhamsafiudin** [comment] 2018-01-11 18:15
thanks..

**Comment by ZackTRobertson** [comment] 2018-01-12 08:01
@meetajhu

Oh my thank you for that!!!! 8 hours of banging my head against a wall!

**Comment by kelset** [comment] 2018-01-12 08:27
Closing since `beta.25` has the fix merged.

**Closed by kelset** 2018-01-12 08:27 UTC
Labels: bug, component: Drawer
