### ISSUE TITLE
Deeplinks opening wrong screen

### ISSUE THREAD

**Issue by sadikyalcin** [react-navigation/react-navigation#9196] opened 2021-01-04 14:12 UTC
I have 2 deeplinks; 1st to the index screen and the 2nd to the detail screen. When they are clicks the first time, they both open the correct screen.

```
<a href="myscheme://sitevideos">Index</a>
<a href="myscheme://sitevideos/node/{id}">Detail<a/>
```

After tapping both links, the second time I tap on the `Index` link, the app navigates to the `Detail` screen all the time.

```
const linking = {
  prefixes: ['myscheme://'],
  config: {
    screens: {
      Home: 'home',
      SiteVideos: {
        initialRouteName: 'SiteVideos',
        path: 'sitevideos',
        screens: {
          SiteVideosViewer: 'node/:nid',
        },
      },
    },
  },
};
```

The logs captured on link tap:

```
href:  myscheme://sitevideos (Correct => Navigates to Index)
href:  myscheme://sitevideos/node/707 (Correct => Navigates to Detail)
href:  myscheme://sitevideos (Incorrect => Navigates to Detail)
href:  myscheme://sitevideos/node/707 (Correct => Navigates to Detail)
```

https://user-images.githubusercontent.com/8109619/103543481-84806500-4e96-11eb-8493-e561d0176431.mov

**Expected Behavior**

The app should navigate to the correct screen and respect the path of the links.

**How to reproduce**

Create a simple app with two links that navigates to the a stack navigator - index screen and a detail screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | 5.8.10
| react-native                   | 0.63.3
| expo                           | NA
| node                           | v12.10.0
| npm or yarn                    | yarn 1.13.0

**Comment by satya164** [comment] 2021-01-04 14:22
There's no `Detail` screen your config, so I assume it's `SiteVideosViewer`.

You have `SiteVideosViewer` nested inside `SiteVideos`. You have the path `sitevideos` assigned to the parent screen `SiteVideos`, and navigating to that URL navigates to the parent screen which has `SiteVideoViewer` rendered and it doesn't destroy it's state. This is expected behavior and not a bug.

If you want to navigate to the nested `SiteVideos` screen which is your initial route (please don't use the same name for parent and child screens, it's confusing), you need to assign the path to that screen instead of the parent screen.

```js
const linking = {
  prefixes: ['myscheme://'],
  config: {
    screens: {
      Home: 'home',
      SiteVideos: {
        initialRouteName: 'SiteVideos',
        screens: {
          SiteVideos: 'sitevideos',
          SiteVideosViewer: 'sitevideos/node/:nid',
        },
      },
    },
  },
};
```

**Closed by satya164** 2021-01-04 14:22 UTC
Labels: bug
