### ISSUE TITLE
Testing custom header buttons and title

### ISSUE THREAD

**Issue by joe307bad** [react-navigation/react-navigation#9487] opened 2021-04-08 05:24 UTC
I am trying to set up a test using `@testing-library/react-native` and React navigation. I am trying to test that my header has the correct title and I am also trying to test by navigating using a custom header with a custom back button. Here is my code:
```

/// Main Stack
const MainStack = () => {
  return (
      <Stack.Navigator
          headerMode="float"
          detachInactiveScreens={true}
          screenOptions={{
            header: (props) => <MainHeader testID="MainHeader" {...props} />,
            headerShown: true,
            headerStyle: {
              backgroundColor: Color.FRAMEWORK_ORANGE
            }
          }}
      >
        <Stack.Screen ....
      </Stack.Navigator>
  );
};

  /// Custom Header
const MainHeader = (props: any) => {
  const { title, currentRouteName } = useAppNavigation();

  return (
      <Appbar
          testID={`MainHeader.${title}`}
          style={{ backgroundColor: Color.FRAMEWORK_ORANGE, flexDirection: 'row' }}
      >
        <Appbar.Action
            testID="BackButton"
            icon="chevron-left"
            color={Color.WHITE}
            onPress={goBack}
        />
        <Appbar.Content testID="HeaderTitle" color={Color.WHITE} title={title} />
        <Appbar.Action
            testID="HamburgerMenuButton"
            icon="bars"
            color={Color.WHITE}
            onPress={navigation.openDrawer}
        />
      </Appbar>
  );
};

  
  /// Drawer 
<Drawer.Navigator
    drawerPosition="right"
    drawerContent={(props) => <SideMenu {...props} />}
    screenOptions={{
      headerShown: false
    }}
>
  <Drawer.Screen name="MainStack" component={MainStack} />
</Drawer.Navigator>

/// Test
it('Can navigate properly', async () => {
  const store = testHelpers.createMockStore({
    session: { apiUrl: 'http://localhost', reduxStorageLoaded: true }
  });
  const component = (
      <Provider store={store}>
        <PaperProvider settings={{ icon: Icon }}>
          <NavigationContainer ref={navigationRef}>
            <RootStack.Navigator>
              <RootStack.Screen
                  name="FrameworkFlow"
                  component={DrawerStack}
                  options={{ headerShown: false }}
              />
            </RootStack.Navigator>
          </NavigationContainer>
        </PaperProvider>
      </Provider>
  );

  const { findByTestId, findByText } = render(component);

  const hamburgerMenuButton = await findByTestId('HamburgerMenuButton');
  fireEvent.press(hamburgerMenuButton);

  const aboutMenuItem = await findByTestId('SideMenuItem.About');
  fireEvent.press(aboutMenuItem);

  const backButton = await findByTestId('BackButton');
  fireEvent.press(backButton);

  expect(await findByText('Sign In')).toBeTruthy();
});

  ```
  
  For some reason `backButton` brings back multiple items. It is the same issue if I try to target the title element in `MainHeader`. Its seems as if my custom header is being rendered anew every time I navigate to a new screen. How can I test that my screen has the proper title? Why is my custom header rendering a brand new component every time I navigate through screens?

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | N/A
| @react-navigation/native       |5.9.3
| @react-navigation/stack        |5.14.3
| react-native-gesture-handler   |1.10.3
| react-native-safe-area-context |3.2.0
| react-native-screens           |3.0.0
| react-native                   |0.63.2
| expo                           |N/A
| node                           |v14.15.0
| npm or yarn                    |yarn@1.22

**Comment by joe307bad** [comment] 2021-04-08 05:26
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.3`, latest: `5.9.4`)
> * `@react-navigation/stack` (found: `5.14.3`, latest: `5.14.4`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Issue still exists after I upgrade.

**Comment by satya164** [comment] 2021-04-08 05:54
Please open an issue in the react native testing library repo. It currently doesn't respect accessibility props when querying for elements which returns elements which aren't visible to user or screen readers, so they need to add support for that.

**Comment by joe307bad** [comment] 2021-04-08 12:13
Thanks @satya164 . So I shouldn't use react native test library with react navigation? Any suggestions on how to test that the header title is correct?

**Comment by satya164** [comment] 2021-04-13 08:28
> So I shouldn't use react native test library

You should ask for this to be supported. Relevant issue: https://github.com/callstack/react-native-testing-library/issues/659

**Comment by mzabolotnia** [comment] 2023-01-20 12:33
I'm facing the same issue, trying to add accessibility id for the title of the page, so it can be located with appium inspector. Currently, when trying to pass accessibility attributes, the name of the element changes, although the identifier is not defined while inspecting. Sample code is: 

const accessibleTitle = <Text accessible={true} accessibilityLabel="test" testID="test">test</Text>;
navigation.setOptions({ title: accessibleTitle });

Unfortunately, the title doesn't become located on the screen.

@joe307bad Have you figured out how to solve your issue? Is there any info if react-native is going to support accessibility for the page titles?

**Comment by Nagibaba** [comment] 2023-12-05 12:30
I exported the component (header) and tested it by rendering it in test files. Works as intended

**Comment by grgmo** [comment] 2024-12-13 16:48
i know this is old post and https://github.com/callstack/react-native-testing-library/issues/970 is working as expected

@joe307bad did you ever get around this? without having to use unique `back` `testId` or `accessibilityLabel` for each screen? 

When i debug the screen using `@testing-library/react-native` (attached below) i can see why it gets multiple back buttons because the header is outside of the `RNScreen` and `@testing-library/react-native` is only ignoring whatever's inside `accessibilityElementsHidden`, since the header is outside it fails to ignore the back button

@satya164 not entirely sure but should `accessibilityElementsHidden` be on the `RNScreen` level? or is this something to do with `@testing-library/react-native` rendering it incorrectly?


![Image](https://github.com/user-attachments/assets/41773496-0435-40c4-86f5-985df2271f6a)

**Comment by satya164** [comment] 2024-12-13 17:25
@grgmo with native stack header a11y is managed by the native components so these props aren't set. it needs to be investigated to see what can be done. please open a new issue for that.

I'm closing this one since the original issue is fixed as testing library now supports a11y props and it works correctly on all other navigators.

**Closed by satya164** 2024-12-13 17:25 UTC
Labels: bug, package:stack
