### ISSUE TITLE
Hidden Drawer Item showing space

### ISSUE THREAD

**Issue by harshitraghav** [react-navigation/react-navigation#8379] opened 2020-06-04 05:56 UTC
```
render() {
    return (
      <Drawers.Navigator
        drawerContent={props => <CustomDrawerContent {...props} />}
        drawerContentOptions={{
          activeTintColor: Colors.white,
          itemStyle: {
            marginHorizontal: 0,
            marginTop: 0,
          },
        }}>
        <Drawers.Screen
          name="Home"
          component={Home}
          options={{
            title: null,
            drawerIcon: () => null,
            drawerLabel: () => null,
          }}
        />
        <Drawers.Screen
          name="Settings"
          component={Settings}
        />
        <Drawers.Screen
          name="Support"
          component={CustomerSupport}
        />
      </Drawers.Navigator>
    );
  }
```

I have hidden my drawer item by setting drawerLabel to null but still, I can see space at the position of drawer item I have hidden.

**Comment by raajnadar** [comment] 2020-06-05 13:00
Duplicate of https://github.com/react-navigation/react-navigation/issues/8041

**Closed by raajnadar** 2020-06-05 13:00 UTC
Labels: bug, package:drawer
