### ISSUE TITLE
[Linking] * path matching component does not get the route matched

### ISSUE THREAD

**Issue by jayshah123** [react-navigation/react-navigation#9335] opened 2021-02-18 13:14 UTC
**Current Behavior**

In case of linking config, a match all screen can be provided via `*`, see code below,
 but how would that component know what path caused it to show up?
We should allow the component matched with the path to have the corresponding path as a prop.

**Expected Behavior**

Matching component should receive a path prop that matched

**How to reproduce**

```
const config = {
  screens: {
    Home: {
      initialRouteName: 'Feed',
      screens: {
        Profile: 'users/:id',
        Settings: 'settings',
      },
    },
    NotFound: '*',
  },
};
```
`NotFound` screen has no way to know what path matched for it to show up.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |5.9.2
| react-native                   |0.63.2
| expo                           |NA
| node                           |10
| npm or yarn                    |6

**Comment by satya164** [comment] 2021-02-18 14:46
Duplicate of #9102

**Closed by satya164** 2021-02-18 14:46 UTC
Labels: bug
