### ISSUE TITLE
[Stack v5.2.13] `replace` and `reset` do not work when called right after the `initialRoute` is mounted

### ISSUE THREAD

**Issue by douglasjunior** [react-navigation/react-navigation#8112] opened 2020-04-23 16:03 UTC
**Current Behavior**

`replace` and `reset` do not work when called right after the `initialRoute` is mounted.

Example:

```js
const StartScreen = ({ navigation }) => {
    useEffect(() => {
         navigation.replace('MyScreen');
         // or
         navigation.reset({ routes: [{ name: 'MyScreen' }] });
    }, []);

    return <View />
};
```

That is, the new screen is mounted, but the previous one is not destroyed.

**Expected Behavior**

- replace: destroy the current screen and open a new one.
- reset: destroy all opened screens and open a new one.

**How to reproduce**

I tried to create a reproduction in Snack: https://snack.expo.io/@douglasjunior/reset-after-mount (take a look at `screens/StartScreen.js` file)

> But `react-navigation` is not working on Snack, not even the documentation examples. 🤷‍♂️
> 
> I get the error:
> 
> ```
> Device: (0:0) Cannot assign to read only property 'exports' of object '#<Object>'
>   Evaluating module://@react-navigation/native.js
>   Evaluating module://App.js.js
>   Loading module://App.js
> ```

When the app starts, the StartScreen.js is called and we need to check if the user is logged in. If so, then open the Home, otherwise open the Login.

In this navigation we need to close `StartScreen` and open the next screen.

We have used this same behavior since react-navigation v2 and we never had any problems.

Our workaround is to add a `setTimeout` to delay the navigation dispatch, but I think it is not the best solution.

```js
useEffect(() => {
     setTimeout(() => {
         navigation.replace('MyScreen');
     }, 500);
}, []);
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both |
| @react-navigation/native       | 5.1.6 |
| @react-navigation/stack.       | 5.2.13 |
| react-native                   | 0.62.2 |
| expo                           | 37.0.0 |
| node                           | 8.16.0 |
| npm or yarn                    | yarn |

**Comment by douglasjunior** [comment] 2020-04-23 16:19
I noticed that the navigation state is updated twice, as follows:

1 dispatch:

```json
{
  "navState": {
    "stale": false,
    "type": "stack",
    "key": "stack-gocaN4gauyw8A7b6Ht3I_",
    "index": 0,
    "routeNames": [
      "Start",
      "Login",
      "Home"
    ],
    "routes": [
      {
        "key": "Start-weL3K4aEPxA_jXeAqr6Q9",
        "name": "Start"
      }
    ]
  }
}
```

2 dispatch: 

```json
{
  "navState": {
    "stale": false,
    "type": "stack",
    "key": "stack-tmweG0E0JXf3I8uWi7E9P",
    "index": 0,
    "routeNames": [
      "Start",
      "Login",
      "Home"
    ],
    "routes": [
      {
        "name": "Login",
        "key": "Login-C70aGEOyam8Vt0ZJwYt3H"
      }
    ]
  }
}
```

3 dispatch:

```json
{
  "navState": {
    "stale": false,
    "type": "stack",
    "key": "stack-tmweG0E0JXf3I8uWi7E9P",
    "routeNames": [
      "Start",
      "Login",
      "Home"
    ],
    "index": 1,
    "routes": [
      {
        "name": "Login",
        "key": "Login-C70aGEOyam8Vt0ZJwYt3H"
      },
      {
        "key": "Start-weL3K4aEPxA_jXeAqr6Q9",
        "name": "Start"
      }
    ]
  }
}
```

**Comment by cristianoccazinsp** [comment] 2020-04-24 18:02
Same issue maybe? https://github.com/react-navigation/react-navigation/issues/8120 

Looks like it was introduced with 5.2.12

**Comment by douglasjunior** [comment] 2020-04-24 18:28
Yes, it seems to be the same.

Worked fine with `"@react-navigation/stack": "5.2.11"`, thanks for the tip.

**Comment by douglasjunior** [comment] 2020-04-24 20:47
The "minimal repo" is on the issue description 🤦‍♂️

https://snack.expo.io/@douglasjunior/reset-after-mount

**Comment by satya164** [comment] 2020-04-24 20:59
And like you said, it doesn't run. How is it better than same text in the issue?

**Comment by douglasjunior** [comment] 2020-04-24 21:13
Thanks for the feedback.

Sorry, I can't do that right now.

**Comment by joaovpmamede** [comment] 2020-04-24 22:23
You shouldn't have closed this @douglasjunior because the issue is still present and works fine with `"@react-navigation/stack": "5.2.11"` like you said.

**Comment by cristianocca** [comment] 2020-04-24 22:29
Definitely, don't close it unless it's fixed :D

**Comment by douglasjunior** [comment] 2020-04-24 22:43
Sorry guys, but I have already spent many hours trying to find and report this problem, (including trying to find the problem in the snack).

I am unable to provide more information at this time, if anyone can, I would appreciate it.

**Comment by cristianoccazinsp** [comment] 2020-04-24 22:47
I have no experience with snacks or expo so I can't spend too much time on it. If we had some snack already prepared with a few basic screens / interactions, perhaps it would be easier. However, it seems that the core of the issue is very obvious; switching screens "too fast" / with a timeout will break the stack.

**Comment by satya164** [comment] 2020-06-15 17:41
Closing since there's no runnable repro to debug. Please open a new issue with a minimal repro if you're still having problems.

**Closed by satya164** 2020-06-15 17:41 UTC
Labels: bug, needs repro
