### ISSUE TITLE
resetOnBlur doesn't work as expected with createStackNavigator

### ISSUE THREAD

**Issue by mitaxe** [react-navigation/react-navigation#7255] opened 2020-02-06 10:08 UTC
**Current Behavior**

- Add 2 random screens inside the createBottomTabNavigator
- Place `createStackNavigator` inside the createBottomTabNavigator and switch `resetOnBlur` to 'true'

When you leave stack navigator and switch to another createBottomTabNavigator screen your  first screen inside the createBottomTabNavigator renders in the background (componentDidMount triggers).

**Expected Behavior**

createBottomTabNavigator screen is not rendering in the background

**Your Environment**
    "react-navigation": "^4.0.10",
    "react-navigation-animated-switch": "^0.4.0",
    "react-navigation-drawer": "~1.4.0",
    "react-navigation-props-mapper": "^1.0.1",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.0",
    "react-navigation-transitions": "^1.0.12",

**Comment by satya164** [comment] 2020-03-18 14:57
`resetOnBlur` only resets the screen, it doesn't unmount it. Closing since this is the expected behaviour.

**Closed by satya164** 2020-03-18 14:57 UTC
Labels: package:bottom-tabs, version-4
