### ISSUE TITLE
flex don't work correctly in TabNav with  on IOS

### ISSUE THREAD

**Issue by cnhuye** [react-navigation/react-navigation#3215] opened 2018-01-04 00:42 UTC
### Current Behavior

I found "animationEnabled" option for TabNav seems break View flex width.

I have a simple code just a View in a TabNav. and 3 columns in a row, column width ratio is  2:1:1.

screen like this : 

![image](https://user-images.githubusercontent.com/486552/34544632-70e607fe-f122-11e7-9018-63ed91cfa2fc.png)

BUT if i set "animationEnabled:true" in TabNavigator options, the column width just wrong:

![image](https://user-images.githubusercontent.com/486552/34544673-a6458384-f122-11e7-86b4-4a87780ab4d2.png)

the code:

```
class MainScreen extends Component<{}> {
  render() {
    return (
      <View style={{flex: 1,marginTop:50}}>
            <View style={[styles.main_row,{}]}>
              <View style={[styles.col2]}>
                <Text>col1</Text>
              </View>
              <View style={[styles.col1]}>
                <Text>col2 content</Text>
              </View>
              <View style={[styles.col1]}>
                <Text>col3 content haha</Text>
              </View>
            </View>

      </View>
    );
  }
}

const TabNav = TabNavigator({
  MainTab: {
    screen: MainScreen,
  },
}, {
  tabBarPosition: 'bottom',
  animationEnabled: true,  // *** WITH this line, columns flex have a wrong width , WITHOUT this, works fine ***
});

export default TabNav;

const styles = StyleSheet.create({
  main_row:{
    height:40,
    flexDirection:'row',
    borderWidth:1,
    borderColor:"#fff",
    flexWrap:'nowrap',
  },
  text:{
    margin:10,
    textAlign:'center',
  },
  col1:{
    flex:1,borderWidth:1, borderColor:"#fff",
    backgroundColor:"#ccc",
  },
  col2:{
    flex:2,borderWidth:1, borderColor:"#fff",
    backgroundColor:"#fff",
  },
});

```

No problem on ANDROID.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.51.0
| node             | 7.10.0
| npm or yarn      | 0.24.5

**Comment by satya164** [comment] 2018-01-04 05:26
Duplicate of #1964

**Closed by satya164** 2018-01-04 05:26 UTC
