### ISSUE TITLE
How to dispatch / setParams to StackNavigator screen?

### ISSUE THREAD

**Issue by Tom29** [react-navigation/react-navigation#2312] opened 2017-08-04 20:24 UTC
I wanna set param to particular screen, but didn't work.
My scheme like this:

TabNavigator
- Message (is StackNavigator)
- - List
- - Detail
- Profile
- Setting

Now, i can `setParams` from Profile to Setting screen by this code
```
this.props.navigation.dispatch(NavigationActions.setParams({
			params: { reload: true },
			key: "Setting",
		}))
```
then Setting screen detect changes by using `componentDidUpdate`, but couldn't do the same with **Message > List screen** with `key:"List"`

How do i do it?

I need to notice to all screens about event like user has been logged out, so every screen need to re-render.

**Comment by toninho** [comment] 2017-08-11 19:43
I have the same problem here

**Comment by loug38** [comment] 2017-08-16 22:24
I'm fairly certain that this should work.

`this.props.navigation.navigate('Setting', {reload: true});`

**Comment by spencercarli** [comment] 2017-08-18 21:40
So if I'm understanding this correctly it works in all cases _except_ when you're trying to set params of a screen in a nested navigator? You've tried this, correct?

```javascript
this.props.navigation.dispatch(NavigationActions.setParams({
  params: { reload: true },
  key: "List",
}))
```

A running example of this issue would be very helpful!

**Comment by nonameolsson** [comment] 2017-10-27 18:09
I am facing this issue also. Did you solve it?

**Comment by kelset** [comment] 2017-11-12 11:31
Pinging OP @Tom29 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by nonameolsson** [comment] 2017-11-12 22:31
@kelset I am still having this issue, and it seems that other also are having it. It doesn't seem able at all to pass params / set params to a TabNavigator nested in a StackNavigator.

**Comment by murtuzamac** [comment] 2017-12-09 16:13
@Tom29 

"then Setting screen detect changes by using componentDidUpdate, but couldn't do the same with Message > List screen with key:"List""

How are you doing this ? Whats the code in your Setting's componentDidUpdate ?

**Comment by mazusheng** [comment] 2017-12-14 03:21
InteractionManager.runAfterInteractions(() => {this.props.navigation.dispatch(NavigationActions.setParams({
  params: { reload: true },
  key: "List",
}))
});
works for me!

**Comment by CarlosWirama** [comment] 2018-01-29 07:38
i've tried this with InteractionManager.runAfterInteractions and without it, neither of them worked for me

**Comment by JulianKingman** [comment] 2018-03-21 23:18
@kelset if I understand correctly, this is because the setParams action doesn't search routes recursively, per here: https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L366

Is that correct? If so, making that recursive wouldn't be so hard, would it? I could make a PR.

**Comment by kelset** [comment] 2018-03-22 08:51
👋 @JulianKingman - sorry I'm not maintaining this lib anymore & this issue is pre-v1.0, so not sure this is still applicable.
Moreover the team is currently working on v2.0 (you can check `master` for that) already so I suggest you take a look at the latest changes first.

**Comment by JulianKingman** [comment] 2018-03-22 14:42
OK, thanks. It seems I was wrong, in any case, nested routes are handled. It seems the problem is the wrong key somehow...

**Comment by brentvatne** [comment] 2018-03-22 19:18
please create a new issue if you find a bug with the approaches suggested here!

**Closed** 2018-03-22 19:18 UTC
Labels: bug
