### ISSUE TITLE
Swipe is crashing my app

### ISSUE THREAD

**Issue by preduseldavid** [react-navigation/react-navigation#8380] opened 2020-06-04 09:57 UTC
### Issue Description

Swipe is crashing my app sometimes when I am on the first screen and I swipe left, or on the latest screen swiping right; I attached an image with the error.

---
### Environment
* React Native Navigation version: 
    "react-navigation": "^4.3.9",
    "react-navigation-tabs": "^2.8.13",
    "@react-navigation/material-top-tabs": "^5.2.9",
    "@react-navigation/native": "^5.5.0",
    "@react-navigation/stack": "^5.4.1",

* React Native version: 0.62.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device: Samsung Galaxy S6 Edge; OS Version: Android Version 7.0; Both Debug and Release

![WhatsApp Image 2020-06-04 at 10 36 00](https://user-images.githubusercontent.com/47463852/83729456-4eed7200-a650-11ea-806e-bcb6303b20a4.jpeg)

**Comment by raajnadar** [comment] 2020-06-04 10:06
Make sure react native gesture handler is installed and properly configured.

**Comment by preduseldavid** [comment] 2020-06-04 10:20
yes, it is installed and configured, this issue appears sometimes, not all the time, so I guess it's a bug.

**Comment by satya164** [comment] 2020-06-15 17:49
Duplicate of https://github.com/react-navigation/react-navigation/issues/7722

**Closed by satya164** 2020-06-15 17:49 UTC
Labels: bug, needs repro, package:material-top-tabs
