### ISSUE TITLE
Unable to pass a function as a param to the next screen in NavigationOptions

### ISSUE THREAD

**Issue by Kush5900** [react-navigation/react-navigation#3236] opened 2018-01-07 15:00 UTC
i am able to to pass a function to the next screen as a param in the render function as you can see the codes below

```
   render(){
      return (
        <View style={styles.container}>
        <View style={styles.titlewrapper}>
        
        <Text style={styles.titleinfo}><Icon name="add-circle" style={{color:"#039BE5"}}/> Customize your own feed </Text>
        </View>
          <TouchableOpacity onPress={()=> requestAnimationFrame(()=>{ this.props.navigation.navigate('topic', {onNavigateBack: this.handleOnNavigateBack.bind(this)
}) }) }
          >
           <View style={styles.buttoncontainer}>
             <Text style={styles.buttontext}>Get started</Text>
             </View>
          </TouchableOpacity>
       </View>
     
      );
    }
```
as you can see i can pass the function "handleOnNavigateBack" as onNavigateBack param to topic screen and its working but i can't achieve this in NavigationOptions as you can see it below 

```
 static navigationOptions = ({ navigation }) => {
      const { params = {} } = navigation.state;
      return{
        headerStyle:{
            elevation:0 
           },
        headerTitle:  (
          <Image style={{ height: responsiveHeight(6), width: responsiveWidth(30), alignSelf:'center' }} source={require('../images/logo-header2.png')}/>
      ),
        headerLeft: <TouchableOpacity  onPress={ () => navigation.navigate('DrawerOpen')  } ><Icon name="menu" style={{paddingLeft:15 }} size={35}/></TouchableOpacity>,
        headerRight: <TouchableOpacity  onPress={ () => navigation.navigate('topic', {
          onNavigateBack: this.handleOnNavigateBack.bind(this)  }) }><Icon name="create" style={{paddingRight:15 }} size={35}/></TouchableOpacity>,
       
        } 
      };
```
i have tried every thing but it seems not to work, any help will be appreciated !

software | version
-- | --
react-navigation | 1.0.0-beta.19
react-native | 0.49.5

**Comment by kelset** [comment] 2018-01-08 21:54
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-08 21:54 UTC

**Comment by Kush5900** [comment] 2018-01-09 09:46
1.i don't think to update to the latest is not required because maybe it's my low knowledge or library bug.
2.it happens on android (not yet try on IOS ).
3.yes
4.yes,it happens when debugger is  on and off
