### ISSUE TITLE
Navigate to tab from parent stack create a new route/context

### ISSUE THREAD

**Issue by aknad** [react-navigation/react-navigation#3804] opened 2018-03-20 11:42 UTC
### Current Behavior
when we navigate from a stack screen to a tab a new route is created every time
we noticed it checking the redux state:

![screen shot 2018-03-20 at 12 34 11](https://user-images.githubusercontent.com/7056879/37652214-1ac630f2-2c3b-11e8-9601-9b00e7ebfbf4.png)

as you can see the 'Main' route is duplicated
in [this snack](https://snack.expo.io/@aknad/tab-to-stack-to-tab) we made a simplified version without redux and we noticed that the context changes every time we navigate to the B tab without using tabs

### Expected Behavior
_navigate_ should go to the original tab route

### How to reproduce
in [this snack](https://snack.expo.io/@aknad/tab-to-stack-to-tab) when you tap on "Go to C" within the A tab, the context changes

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.51.0
| node             | 6.2.2
| npm      | 4.5.0

**Comment by brentvatne** [comment] 2018-03-20 16:33
hi there! thanks for pointing this case out. it's a bit of an awkward one currently. you'd be best off doing this until we come up with a more elegant approach:

```
this.props.navigation.goBack();
this.props.navigation.navigate('B');
```

**Comment by Kisepro** [comment] 2018-03-21 06:40
@brentvatne Is there a common reason with navigating between the same stack navigator re-constructing always the screen also ?

I guess this is more an expected behaviour for the stack but I can't figure out technically why does this happen and how to avoid it ?

**Comment by aknad** [comment] 2018-03-21 14:53
adding goBack solves the duplicate route problem but shows a blank screen
this is similar to the behaviour described here:
https://github.com/react-navigation/react-navigation/issues/1627
as suggested in that thread, with _swipeEnabled: true_ it seems to works but we'd like to disable tab swiping

any idea?

**Comment by aknad** [comment] 2018-03-22 10:22
I think the problem is related to this:
https://github.com/react-navigation/react-navigation/issues/3592
but my component is never being mounted
Probably the goBack transition is not ended when navigate is fired, as you can see in this redux log:

![screen shot 2018-03-22 at 11 15 44](https://user-images.githubusercontent.com/7056879/37764838-f707423a-2dc2-11e8-97f1-16ad5211a4af.png)

In fact, adding a 1 second timeout before the navigate call seems to works but the UX is terrible

**Comment by aknad** [comment] 2018-03-22 16:39
version 1.5.7 seems to solves the blank tab issue

**Comment by brentvatne** [comment] 2018-03-22 19:17
🆗 sounds like the issue is resolved in that case

**Closed** 2018-05-07 22:39 UTC
