### ISSUE TITLE
Cannot reset nested navigator when resetting root one

### ISSUE THREAD

**Issue by JCMais** [react-navigation/react-navigation#3031] opened 2017-11-22 15:54 UTC
Imagine that we have the following structure
```
const ChildNavigatorA = StackNavigator({
  ScreenA: {
    screen: ScreenA,
  },
  ScreenB: {
    screen: ScreenB,
  },
});
const ChildNavigatorB = StackNavigator({
  ScreenC: {
    screen: ScreenC,
  },
  ScreenD: {
    screen: ScreenD,
  },
});
const AppNavigator = StackNavigator({
  Home: {
    screen: RandomHomeComponent,
  },
  ScreenA: {
    screen: ChildNavigatorA,
  },
  ScreenC: {
    screen: ChildNavigatorB,
  },
});
```

Let's say that I'm on `ScreenA` and navigate to `ScreenC`.

The navigation state will look like this:
```
  navigation: {
    index: 2,
    routes: [
      {
        routeName: 'Home',
        key: 'Init-id-1511364125347-0',
      }
      {
        index: 0,
        routes: [
          {
            routeName: 'ScreenA',
            key: 'Init-id-1511364125347-1',
          },
        ],
        key: 'id-1511364125347-2',
        routeName: 'ScreenA'
      },
      {
        index: 0,
        routes: [
          {
            routeName: 'ScreenC',
            key: 'Init-id-1511364125347-3',
          }
        ],
        key: 'id-1511364125347-4',
        routeName: 'ScreenC'
      }
    ],
    allOptions: {
      navigationOptions: {
        header: null
      }
    }
  },
```

Now, the user did something on `ScreenC`, and I would like to reset their navigation state, so it was like they were going from `Home` => `ScreenA` => `ScreenB`, so I call:

```
navigation.dispatch(
  NavigationActions.reset({
    key: null,
    index: 1,
    routeName:  'Home',
    actions: [
      NavigationActions.navigate({
        routeName: 'Home',
      }),
      NavigationActions.navigate({
        routeName: 'ScreenA',
        action: NavigationActions.reset({
          index: 1,
          routeName: 'ScreenA',
          actions: [
            NavigationActions.navigate({
              routeName: 'ScreenA',
            }),
            NavigationActions.navigate({
              routeName: 'ScreenB',
            }),
          ],
        }),
      }),
    ],
  }),
);
```

### Current Behavior
The navigation is resetted only up to `ScreenA`, that is, the initial route (since it's the first route) of the nested navigator `ChildNavigatorA`. The `action` used in the navigate action is ignored completely.

State (removed some properties so it's easier to read):
```
  navigation: {
    index: 1,
    routes: [
      {
        routeName: 'Home',
        key: 'Init-id-1511364125347-0',
      }
      {
        index: 0,
        routes: [
          {
            routeName: 'ScreenA',
            key: 'Init-id-1511364125347-1',
          },
        ],
        key: 'id-1511364125347-2',
        routeName: 'ScreenA'
      },
    ],
    allOptions: {
      navigationOptions: {
        header: null
      }
    }
  },
```` 

### Expected Behavior

State is correctly set to:

```
  navigation: {
    index: 2,
    routes: [
      {
        routeName: 'Home',
        key: 'Init-id-1511364125347-0',
      }
      {
        index: 1,
        routes: [
          {
            routeName: 'ScreenA',
            key: 'Init-id-1511364125347-1',
          },
          {
            routeName: 'ScreenB',
            key: 'Init-id-1511364125347-2',
          },
        ],
        key: 'id-1511364125347-3',
        routeName: 'ChildNavigatorA'
      },
    ],
    allOptions: {
      navigationOptions: {
        header: null
      }
    }
  },
```` 

### Why it happens / How to fix

This happens because of this check:
https://github.com/react-community/react-navigation/blob/2f0e386a2493d3d786bc466ea3e05a29d69bfd23/src/routers/StackRouter.js#L101-L115

The `action.action` is being ignored there, and just setting the nested navigator to their initial route.

This can be fixed by replacing the body of this `if`, with the following:

```js
         if (action.action && action.action.type === NavigationActions.RESET) {
            const resetAction = action.action;
            const newState = {
              index: resetAction.index,
              routes: resetAction.actions.map(
                (childAction: NavigationNavigateAction) => {
                  const router = childRouters[childAction.routeName];
                  if (router) {
                    console.log('getStateForAction#reset-router');
                    const data = {
                      ...childAction,
                      ...router.getStateForAction(childAction),
                      routeName: childAction.routeName,
                      key: _getUuid(),
                    };
                    console.log(router, childAction, data);
                    console.log('/getStateForAction#reset-router');
                    return data;
                  }
                  const route = {
                    ...childAction,
                    key: _getUuid(),
                  };
                  console.log('getStateForAction#reset-non-router');
                  console.log(childAction, route);
                  console.log('/getStateForAction#reset-non-router');
                  delete route.type;
                  return route;
                }
              ),
            };
            console.log('getStateForAction#reset');
            console.log(resetAction, newState);
            console.log('/getStateForAction#reset');
            return newState;
          } else {
            return {
              index: 0,
              routes: [
                {
                  ...action,
                  type: undefined,
                  key: `Init-${_getUuid()}`,
                },
              ],
            };
          }
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.50
| node             | 8

Is that correct? Should I send a PR? Are you guys willing to accept it?

**Comment by kelset** [comment] 2017-11-22 16:44
Thanks for reporting.
Currently there are already a few issues open related to reset & nested navigators (like https://github.com/react-community/react-navigation/issues/2670). That said, there is also a PR related to what you are proposing: https://github.com/react-community/react-navigation/pull/1888

And this other PR is probably also related to the overall "behavioural issue": https://github.com/react-community/react-navigation/pull/2544

If my quick diagnose is correct, please review and comment those PRs so that it will help us in the reviewing process (knowing that somebody has tested them aside from us).

**Comment by GaudamThiyagarajan** [comment] 2018-03-27 15:13
is this live? looks like the bug still exists

**Comment by GaudamThiyagarajan** [comment] 2018-03-28 06:14
@JCMais  do you have a branch that I could use temporarily for now?

**Comment by brentvatne** [comment] 2018-05-01 00:53
if this is still an issue can someone post a link to a snack that reproduces it please?

**Comment by apengstrom** [comment] 2018-05-01 18:37
This issue exists and has been reported (and shut down by devs) multiple times, from what I see in my research into the reported bugs. I'd absolutely love to post a snack that reproduces it, however, I am currently unable to do so as the project I am working in is under an NDA.

This only started happening when I updated the project's libs to the latest a couple weeks ago, using Redux and React Navigation. My goal is to reset the navigation stack, but instead of resetting it to the previous initial route, I want to reset it to a different route. Instead, it keeps setting the first initial route.

If I console.log() the action, in my main reducer file, I see the proper route. But once I run the navigation reset, it resets it to the original route. This is the code:

console.log('RESET_NAV: ', JSON.stringify(action.route));
debugger;

      nextState = AppNavigator.router.getStateForAction(
        NavigationActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({
              routeName: action.route,
              params: action.params ? action.params : undefined
            })
          ]
        })
      );
      
console.log('RESET_NAV: ', nextState);
debugger;

nextState contains the initial route when the application loads, instead of the one specified in the action.route debugger statement above. Please advise...

**Comment by apengstrom** [comment] 2018-05-01 20:04
Currently the routeName "Login" - which it should be "Start Screen" as I'm trying to reset it to "Start Screen", is being generated from node_modules/react-navigation/src/routers/StackRouter.js.

It is being defined here:

const initialRouteName = stackConfig.initialRouteName || routeNames[0];

on line 48. This is set whenever I call to reset.

Thoughts? @brentvatne

**Comment by apengstrom** [comment] 2018-05-03 15:07
I resolved the issue in my app by just re-engineering how I navigated through the initial loading processes. Where I used to reset the navigation from the login screen to the app home screen, if the user was logged in, I ended up removing the loading screen and moving it into the login screen, displaying the loading screen if the user was logged in and then just routing to the home page instead of resetting the navigation. The home page was also configured to not show a back button, so there's no confusion on the user's end.

So for me this issue does not pertain any longer, however, it would be nice to figure out why the reset function does what it does, as it was not ideal.

**Comment by JCMais** [comment] 2018-10-06 14:00
I cannot confirm if this still happens on latest react navigation, but it was easily reproducible using the code on the original issue. So if anyone can test it it would be great

**Comment by slorber** [comment] 2018-10-26 16:35
@apengstrom @JCMais according to what I see, it has been a change of behavior, don't know exactly when. getStateForAction will only work for reset action if you pass a 2nd arg state argument, which is somehow confusing imho.

I've made a PR so that it works like before, you can check the details here: https://github.com/react-navigation/react-navigation/pull/5175

**Closed** 2019-09-16 10:58 UTC
Labels: bug, needs repro, related: reset
