### ISSUE TITLE
MaterialTopTabNavigator page location error

### ISSUE THREAD

**Issue by YHQiu** [react-navigation/react-navigation#5786] opened 2019-04-07 03:10 UTC
Hi sir or madam,
I found a problem which the MaterialTopTabNavigator always show the first page don't the initial Page. I have three page in the MaterialTopTabNavigator,PageA , PageB and PageC, the PageB is the initial page. but when I access the tabNavigator , the PageA always show in front.

### Current Behavior

- What code are my running and what is happening?

`
import React from 'react'
import {Text, AppRegistry, View} from 'react-native'
import {createAppContainer,createMaterialTopTabNavigator,createStackNavigator} from 'react-navigation'

export default class NavigatorTest {
    
}

export class PageA extends React.Component{

    render(): React.ReactNode {
        return (
            <Text>
                This is PageA
            </Text>
        )
    }

}

export class PageB extends  React.Component{

    render(): React.ReactNode {
        return (
            <Text onPress={()=>{
                this.props.navigation.navigate("PageD")
            }}>
                This is PageB + Tap it for jump to PageD
            </Text>
        )
    }

}

export class PageC extends React.Component{

    render(): React.ReactNode {
        return (
            <Text>
                This is PageC
            </Text>
        )
    }

}

export class PageD extends React.Component{

    render(): React.ReactNode {
        return (
            <Text>
                This is PageD
            </Text>
        )
    }

}

const PageBNavigator = createStackNavigator({
    PageB:{
        screen:PageB,
        navigationOptions: {
            headerTitle:"PageB",
            headerStyle:{
                backgroundColor:"blue",
            },
            header:null,
        }
    },
    PageD:{
        screen:PageD,
        navigationOptions: {
            headerTitle:"PageD",
            headerStyle:{
                backgroundColor:"blue",
            }
        }
    }
})

const MainTab = createMaterialTopTabNavigator({
    PageA:{
        screen:PageA
    },
    PageB:{
        screen:PageBNavigator,
    },
    PageC:{
        screen:PageC
    },
},{
    initialRouteName:"PageB",
    navigationOptions: {
        headerTitle:"MainTab",
        headerStyle:{
            backgroundColor:"blue",
        }
    }
})

const MainNavigator = createStackNavigator({
    MainTab:{
        screen:MainTab
    },
},{
    initialRouteName:"MainTab",
    navigationOptions: {
        headerTitle:"Test",
        headerStyle:{
            backgroundColor:"blue"
        }
    }
})

const MainContainer = createAppContainer(MainNavigator)

AppRegistry.registerComponent("HomePage",()=>MainContainer)

`
- Include a screenshot if it makes sense.
<img width="391" alt="errorShow" src="https://user-images.githubusercontent.com/12265929/55677980-94b38b00-5924-11e9-8a8c-9d789468222d.png">

![MaterialTopTabNavigatorIssue](https://user-images.githubusercontent.com/12265929/55677853-2a015000-5922-11e9-9fc5-b00c44ff2393.gif)

### Expected Behavior

- What do you expect should be happening?
The initial Page should be shown PageB rather than PageA!  

### How to reproduce
If you interest my issue, please reproduce it use my code.

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.6.1
| react-native     | 0.59.2
| react | 16.6.3
| react-navigation-redux-helpers | 2.0.9
| react-native-root-modal | 3.1.1
| react-native-root-toast | 3.0.2
| node             | v11.6.0
| yarn      | 1.13.0
| System macOS Majava  | 10.14.2
| Device iPhone 6S simulator | 12.1

**Comment by matthamil** [comment] 2019-04-07 03:51
Duplicate of https://github.com/react-navigation/react-navigation/issues/5754

**Closed by matthamil** 2019-04-07 03:51 UTC

**Comment by YHQiu** [comment] 2019-04-08 00:58
Thank you.I have solution it.
