### ISSUE TITLE
this.props.navigation.navigate is not being called

### ISSUE THREAD

**Issue by fahadhaq** [react-navigation/react-navigation#3143] opened 2017-12-17 09:48 UTC
Apologies for posting this here. I will try to clearly explain the issue here.

In my app I have the following setup for Navigation

 - StackNavigator
   - StackNavigator  -> Lets call this A
   - StackNavigator  -> Lets call this B
      - DrawerNavigator
          - TabNavigator

For my app I am using a custom component to create the TabNavigator which uses some logic to display different set of tabs when a user logs in based on permission. For the DrawerNavigator I use a contentComponent to create all the menu items.  Both of the components creates correctly and displays the correct menu / Tab items. The issue I am having is that in the DrawerNavigator I have a signout button which when called needs to redirect the user to the a login page which is part of StackNavigator A. 

I know the signout button works if I move all the code into my Primary nav page, doing this requires me to have static TabNavigator for all users, which is not ideal. 

Here is my code as I have it currently for the primary nav

```
const DrawerNavigation = StackNavigator({
  DrawerStack: { screen: TabNavigatorScreen }
}, {
    headerMode: 'none',
    navigationOptions: ({ navigation }) => ({
      headerStyle: { backgroundColor: '#D31F26' },
      title: '',
      gesturesEnabled: false
    })
  })

const LoginStack = StackNavigator({
  LoginScreen: { screen: LoginScreen, navigationOptions: ({ navigation }) => ({ headerBackTitle: 'back', headerTintColor: 'white', headerLeft: menuButton(navigation) }) }
}, {
    // Default config for all screens
    headerMode: 'float',
    navigationOptions: {
      headerTitleStyle: { color: '#fff' },
      // header: (props) => <ImageHeader {...props} />,
      headerStyle: styles.header
    }
  })

// Manifest of possible screens
const PrimaryNav = StackNavigator({
  loginStack: { screen: LoginStack },
  drawerStack: { screen: DrawerNavigation }
}, {
    // Default config for all screens
    headerMode: 'none',
    initialRouteName: 'loginStack',
    transitionConfig: noTransitionConfig
  })

export default PrimaryNav
```

Here is the code for the TabNavigatorScreen

```
var TabNavTest = TabNavigator(
                this.state.Routes, {
                    // Default config for all screens
                    initialRouteName: 'MyCardStack',
                    lazy: true
                })

                var DrawerStack = DrawerNavigator({
                    TabNav: { screen: TabNavTest },
                    HelpSupportScreen: { screen: HelpSupportScreen },
                    AccountScreen: { screen: AccountScreen },
                    CustomWebViewScreen: { screen: CustomWebViewScreen },
                    ReprintCardSuccessScreen: { screen: ReprintCardSuccessScreen },
                    ReprintCardPaymentScreen: { screen: ReprintCardPaymentScreen },
                    ReprintCardScreen: { screen: ReprintCardScreen },
                    ReprintCardStartScreen: { screen: ReprintCardStartScreen },
                    PushNotificationScreen: { screen: PushNotificationScreen }
                  }, {
                      gesturesEnabled: false,
                      contentComponent: DrawerContainerScreen
                    })
                  

            return (

                <DrawerStack />
```

As mentioned above the Signout link is under DrawerContainerScreen.

When I click the signout the logout method calls correctly and I can see all the debug code but the following line inst being called.

`this.props.navigation.navigate('LoginScreen')`

Not seeing any errors either.

Now comes the weird part. When I move the following code out of the TabNavigatorScreen and put it in the PrimarNav page signout works perfectly fine but the opendrawer function no longer opens my menu.

Here is the changed code for PrimaryNav

```

//This const was the one moved back from the TabNavigatorScreen 
const DrawerStack = DrawerNavigator({
  TabNav: { screen: TabNavigatorScreen },
  HelpSupportScreen: { screen: HelpSupportScreen },
  AccountScreen: { screen: AccountScreen },
  CustomWebViewScreen: { screen: CustomWebViewScreen },
  ReprintCardSuccessScreen: { screen: ReprintCardSuccessScreen },
  ReprintCardPaymentScreen: { screen: ReprintCardPaymentScreen },
  ReprintCardScreen: { screen: ReprintCardScreen },
  ReprintCardStartScreen: { screen: ReprintCardStartScreen },
  PushNotificationScreen: { screen: PushNotificationScreen }
}, {
    gesturesEnabled: false,
    contentComponent: DrawerContainerScreen
  })


const DrawerNavigation = StackNavigator({
  DrawerStack: { screen: DrawerStack }
}, {
    headerMode: 'none',
    navigationOptions: ({ navigation }) => ({
      headerStyle: { backgroundColor: '#D31F26' },
      title: '',
      gesturesEnabled: false
    })
  })

const LoginStack = StackNavigator({
  LoginScreen: { screen: LoginScreen, navigationOptions: ({ navigation }) => ({ headerBackTitle: 'back', headerTintColor: 'white', headerLeft: menuButton(navigation) }) }
}, {
    // Default config for all screens
    headerMode: 'float',
    navigationOptions: {
      headerTitleStyle: { color: '#fff' },
      // header: (props) => <ImageHeader {...props} />,
      headerStyle: styles.header
    }
  })

// Manifest of possible screens
const PrimaryNav = StackNavigator({
  loginStack: { screen: LoginStack },
  drawerStack: { screen: DrawerNavigation }
}, {
    // Default config for all screens
    headerMode: 'none',
    initialRouteName: 'loginStack',
    transitionConfig: noTransitionConfig
  })

export default PrimaryNav
```

Not really sure why its not opening my drawer item from the above code or calling the this.props.navigation.navigate('LoginScreen') from the code I currently have. 

Does all the screen needs to be defined under one component? Not sure what I am missing here. Also please let me know if this doesnt make sense. I have spent about a week going over my code trying to fix this. There is no error being shown for either of those two cases I have explained here. Thanks in advance

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.21
| react-native     | 0.47.2
| node             | 
| npm or yarn      | npm

**Comment by kelset** [comment] 2017-12-17 15:31
If I'm not mistaking what you are saying, 

> this.props.navigation.navigate('LoginScreen')

Is being called from `Signout`, which you say is
>  link is under DrawerContainerScreen

But in the code you shown, `DrawerContainerScreen` is not a route in either navigators. So it's not wired to a navigator, not getting the `props.navigation`. Which could explain why it's not working.

Have you tried using the [Navigation Actions](https://reactnavigation.org/docs/navigators/navigation-actions) instead?

**Comment by fahadhaq** [comment] 2017-12-17 18:25
DrawerContainerScreen is part of the DrawerNavigator as contentComponent shown below.

```
var DrawerStack = DrawerNavigator({
                    TabNav: { screen: TabNavTest },
                  }, {
                      gesturesEnabled: false,
                      contentComponent: DrawerContainerScreen
                    })
```

I will try out what you have suggested. But the signout works if all the Navigators are defined in one container ie. if they are all in the PrimaryNav component.

**Comment by bmakuh** [comment] 2017-12-18 23:19
I am also seeing this issue. In my case, I have a custom TabNavigator (that uses iOS segment-style tabs) nested inside of one of my screens. Calling `navigate()` within this custom navigator does nothing.

**Comment by fahadhaq** [comment] 2017-12-19 00:39
I tried the Navigation Action and still nothing.

**Comment by kelset** [comment] 2017-12-19 09:02
> DrawerContainerScreen is part of the DrawerNavigator as contentComponent shown below.

Exactly.
Which means that it's not a route, but an option (argument-wise). Reason why it doesn't have `this.props.navigation`.

I suggest you or @bmakuh to create a [Snack](https://snack.expo.io/) reproducing the issue.

**Comment by mssio** [comment] 2017-12-19 09:29
I also have this problem, my navigate function is not working after upgrading from 1.0.0-beta.21 to 1.0.0-beta.22. Downgrading back to 1.0.0-beta.21 make it works. For now I just downgrade the react-navigation, because I must finish my app as soon as possible.

**Comment by fahadhaq** [comment] 2017-12-19 09:52
I think there's a bit of confusion here. Signout is just a linl, which calls the navigation. The navigation goes to loginscreen. LoginScreen route is defined but its under LoginStack

```
const LoginStack = StackNavigator({
  LoginScreen: { screen: LoginScreen, navigationOptions: ({ navigation }) => ({ headerBackTitle: 'back', headerTintColor: 'white', headerLeft: menuButton(navigation) }) }
}, {
    // Default config for all screens
    headerMode: 'float',
    navigationOptions: {
      headerTitleStyle: { color: '#fff' },
      // header: (props) => <ImageHeader {...props} />,
      headerStyle: styles.header
    }
  })
```

The same signout button / link works if I move the entire Navigator under one component. So if I move DrawerNavigator and TabNAvigator to primaryNav the signout works.

Hope this clarifythe issue

**Comment by fahadhaq** [comment] 2017-12-19 10:04
Also there are other links in the DrawerContainerScreen that works fine. So not sure why this would be any different.

**Comment by bmakuh** [comment] 2018-01-03 22:56
@kelset I apologize for the delay; here's a snack reproducing the issue. I've left comments in the code explaining expected/actual behavior and why it happens.
https://snack.expo.io/SJUtyJoXf

**Comment by erwan-lcs** [comment] 2018-01-04 12:24
Same here my `this.props.navigation.navigate('nestedRouteName');` doesn't do anything since 1.0.0-beta.22
I had to downgrade to magically make it work again `yarn upgrade react-navigation@1.0.0-beta.21`

My Navigator structure: 

```
 render() {
        const MainTabNavigator = TabNavigator({
            welcome: { screen: WelcomeScreen },
            auth: { screen: AuthScreen },
            main: {
                screen: DrawerNavigator({
                    notifications: {
                        screen: StackNavigator({
                            notificationList: { screen: NotificationListScreen },
                            notificationDetails: { screen: NotificationDetailsScreen }
                        },
                      {
                        initialRouteName: 'notificationList'
                      })
                    },
                    //Had to embed this screen into its own navigator to display the header
                    settingsContainer: {
                        screen: StackNavigator({
                            settings: { screen: SettingsScreen }
                        })
                    }
                }, {
                    contentComponent: DrawerContainer,
                    initialRouteName: 'notifications',
                    navigationOptions: {
                        //tabBarVisible: false,
                        headerMode: 'none',
                        drawerOpenRoute: 'DrawerOpen',
                        drawerCloseRoute: 'DrawerClose',
                        drawerToggleRoute: 'DrawerToggle'
                    }
                })
            }
        }, {
            navigationOptions: {
                tabBarVisible: false
            },
            lazy: true, //a fix for nested Android screens
            swipeEnabled: false
        });

        return (
            <Provider store={store}>
                <View style={styles.container}>
                    <MainTabNavigator />
                </View>
            </Provider>
        );
    }
```


Trying to call the navigate from `auth: { screen: AuthScreen }`.
I've noticed that navigating to a same level route works on beta 22:
`this.props.navigation.navigate('sameLevelRoute'); `OK
`this.props.navigation.navigate('nestedRoute'); `FAIL (nothing happens, no error, no stop)

**Comment by sahil290791** [comment] 2018-01-08 16:23
Same case as @erwan-lcs , I am on beta 23.

**Comment by bmakuh** [comment] 2018-01-08 16:29
I figured out a way to hack around it for now, which is by passing `navigation` in through `screenProps`, since that's the only prop the StackNavigator will accept: https://reactnavigation.org/docs/navigators/stack#Navigator-Props

**Comment by mssio** [comment] 2018-01-09 12:15
My case is related to this issue #3149

**Comment by mturki** [comment] 2018-01-16 13:57
Same case as @erwan-lcs , I am on beta 26.

**Comment by sahil290791** [comment] 2018-01-17 12:16
@erwan-lcs I was also getting the same issue, where the code never showed any error but it just did not navigate, and then in the docs I found out that if we wrap a **navigator** inside a component, we need to wire **navigator** into the navigation tree, which makes the **component** navigation-aware and it passes the navigation object down.

> 
To wire **MainScreenNavigator** into the navigation tree, we assign its router to the wrapping component. This makes **NavigatorWrappingScreen** "navigation aware", which tells the parent navigator to pass the navigation object down. Since the **NavigatorWrappingScreen's** router is overridden with the child navigator's router, the child navigator will receive the needed navigation.
```
class NavigatorWrappingScreen extends React.Component {
  render() {
    return (
      <View>
        <SomeComponent/>
        <MainScreenNavigator navigation={this.props.navigation}/>
      </View>
    );
  }
}
NavigatorWrappingScreen.router = MainScreenNavigator.router;
```

In your case I see that you are wrapping **MainTabNavigator** inside a component:
```
// try defining MainTabNavigator outside of the component
// const MainTabNavigator = TabNavigator({ });
class MyComponent extends Component {
 // -------
  render() {
     // ----------
      return (
            <Provider store={store}>
                <View style={styles.container}>
                    <MainTabNavigator />
                </View>
            </Provider>
        );
   }
}
// wire MainTabNavigator to the navigation tree:
MyComponent.router = MainTabNavigator.router;
// the above wiring made the navigate action work
```

Then you can just use: `this.props.navigation.navigate('some_screen');`

**Comment by AntonPuko** [comment] 2018-01-17 22:24
@sahil290791 thanks, this works..but it's soooo stupid that we have to do it :/

**Comment by sahil290791** [comment] 2018-01-18 05:03
@AntonPuko yes things change a bit after wiring it up, but the navigation method starts working.

**Comment by brentvatne** [comment] 2018-02-07 21:57
we should clarify this in docs, made an issue https://github.com/react-navigation/react-navigation.github.io/issues/33

**Closed by brentvatne** 2018-02-07 21:57 UTC
Labels: needs more info

**Comment by ShunYamada** [comment] 2018-02-24 06:33
Same Issue
