### ISSUE TITLE
StackRouter App.router.getStateForAction returns wrong state for action type: "Navigation/INIT"

### ISSUE THREAD

**Issue by danielmarino24i** [react-navigation/react-navigation#7637] opened 2019-03-22 09:12 UTC
StackRouter App.router.getStateForAction returns wrong state for action type: "Navigation/INIT" when providing a previousState, at least for browser.

![Screenshot 2019-03-22 at 10 05 36](https://user-images.githubusercontent.com/35027703/54812033-6da15c00-4c8a-11e9-940a-fc86319d888d.png)

It returns the lastState as it is:
![Screenshot 2019-03-22 at 10 09 10](https://user-images.githubusercontent.com/35027703/54812180-ca9d1200-4c8a-11e9-8118-a6cde9e439a2.png)

react-navigation: 3.5.0
react-navigation/@core: 3.2.0

**Comment by satya164** [comment] 2020-03-20 12:59
Closing since this is expected behaviour to return existing state instead of initializing it again if it was already initialized.

**Closed by satya164** 2020-03-20 12:59 UTC
Labels: package:core, version-4
