### ISSUE TITLE
React Navigation 5 | Connot update a component from inside the function body of a different component. (useNavigationCache.tsx))

### ISSUE THREAD

**Issue by bennodev19** [react-navigation/react-navigation#8677] opened 2020-08-05 07:26 UTC
**Current Behavior**
After every Screen switch in a **StackNavigator** (BottomTabNavigator works quite fine) I get this warning.. 
It doesn't seem to change anything on the current state of the app but its annoying.

<img width="1680" alt="Bildschirmfoto 2020-08-05 um 09 23 19" src="https://user-images.githubusercontent.com/57860196/89383747-5509d880-d6fd-11ea-86ba-cd044d6ff60b.png">

**Expected Behavior**
No warnings at all

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | every version both platforms
| @react-navigation/native       | 5.7.3
| react-native                   | 0.63.2 | upgraded from 0.62 (in 0.62 this warning doesn't appear)
| expo                           | not using
| node                           | v13.0.1
| npm or yarn                    | npm 6.14.7

**Comment by SrBrahma** [comment] 2020-08-07 15:51
When I have this issues, I put the code present in the root of the component inside a useEffect and it gets fixed

**Comment by BennoDev1** [comment] 2020-08-10 05:57
> When I have this issues, I put the code present in the root of the component inside a useEffect and it gets fixed

I have no logic in my components at all so there is no need for that.. 
In addition this issue get caused from react-navigation and not directly from my code..

**Comment by castalonirenz** [comment] 2020-08-17 17:17
Same issue with me 
![image](https://user-images.githubusercontent.com/13584669/90424327-849ee480-e0f0-11ea-849e-92b44c02a03b.png)

**Comment by taymeric** [comment] 2020-09-30 08:30
I had the same issue. It was caused by a `navigation.setOptions(...)` call. As @SrBrahma  suggested, putting the call in a useEffect solves the issues.

**Comment by satya164** [comment] 2020-10-02 14:37
Closing due to incomplete info and no repro.

**Closed by satya164** 2020-10-02 14:37 UTC
Labels: bug, needs more info

**Comment by dgellow** [comment] 2020-10-04 18:15
@taymeric Did you move the `navigation.setOptions(...)` into the `useEffect`, or both `const navigation = useNavigation<...>()` AND `navigation.setOptions(...)`?

**Comment by taymeric** [comment] 2020-10-05 06:09
@dgellow I didn't have `useNavigation()` as `navigation` came from props. I assume you should just put setOptions in useEffect.

**Comment by dgellow** [comment] 2020-10-05 09:14
I can confirm, that's the solution. Thank @taymeric!

```ts
	const navigation = useNavigation()
	useLayoutEffect(() => {
		navigation.setOptions({
			headerLeft: () => <BackButton back={navigation.goBack} />,
		})
	}, [navigation])
```
