### ISSUE TITLE
Drawer does not close after selecting item

### ISSUE THREAD

**Issue by JenilynnB** [react-navigation/react-navigation#11988] opened 2024-05-15 17:14 UTC
### Current behavior

When using a drawer navigator with nested stack navigators and selecting an item, the selected screen will appear, but the drawer will not close.

This happens on iOS devices with "Reduce Motion" and "Prefer Cross-Fade Transitions" enabled.

https://github.com/react-navigation/react-navigation/assets/8279125/cf056b02-7907-452f-a366-c73d943cb29f

### Expected behavior

The drawer should close when an item is selected

### Reproduction

https://snack.expo.dev/@jbrandes/authentic-yellow-apple

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.12
| @react-navigation/drawer               | 6.6.15
| @react-navigation/stack                | 6.3.29
| react-native-safe-area-context         | 4.10.1
| react-native-screens                   | 3.31.1
| react-native-gesture-handler           |2.16.1
| react-native-reanimated                |3.10.1
| react-native                           | 0.74.1
| expo                                   | 51.0.5

**Comment by JenilynnB** [comment] 2024-05-15 17:21
Confirmed. Issue still exists.

**Comment by JenilynnB** [comment] 2024-05-15 17:23
Oops. Didn't mean to close.

**Comment by Eonfuzz** [comment] 2024-05-16 04:23
This is currently happening in our expo project too since migrating to expo51

**Comment by drewjoh** [comment] 2024-05-17 03:56
This is happening for me as well since updating to SDK 51 on iOS.  
Does not happen in the simulator, but does happen when installed on a device via Test Flight.

Oddly for me, tapping a menu item in the drawer twice does close it.

**Comment by JenilynnB** [comment] 2024-05-20 17:11
Also now having reports of some Android users experiencing the same issue with their "Reduce Animations" setting turned on.

**Comment by DivyaniPatel96** [comment] 2024-05-30 07:59
Hello, Did any one got resolution for this issue? I am also facing same issue for iOS.

**Comment by tipleavalentin** [comment] 2024-05-30 19:37
Also happens on my end. react-native@0.74.1, expo@51.0.9, react-native-reanimated@3.10.1, @react-navigation/drawer@6.6.15.
It took me a while to figure how to reproduce the issue on Android, it happens only when animations are disabled.
Did someone found a fix?
Thanks!

**Comment by Eonfuzz** [comment] 2024-06-05 00:15
@tipleavalentin  We've messed around with the newer reanimated / expo versions to no success so far. I think we'll have to wait until a maintainer works on the project. For now has anyone reverted Expo versions successfully?

**Comment by nympheastudio** [comment] 2024-06-07 13:27
for me the bug disapear when updating to 6.6.15 : 

    "@react-navigation/drawer": "6.6.15",
    "@react-navigation/native": "^6.1.17",
    "expo": "^51.0.8",

**Comment by JenilynnB** [comment] 2024-06-10 19:23
Still experiencing the issue with those versions. This is becoming a huge annoyance in my project and rolling back was a big undertaking, so I edited the Drawer component myself to make it work in the meantime. Here's what worked for me.

In the file `node_modules/@react-navigation/drawer/src/views/modern/Drawer.tsx` in the `toggleDrawer` function add `reduceMotion: ReduceMotion.Never` to the animation configuration and add `ReduceMotion` as an import from `react-native-reanimated`

      translationX.value = withSpring(translateX, {
        velocity,
        stiffness: 1000,
        damping: 500,
        mass: 3,
        overshootClamping: true,
        restDisplacementThreshold: 0.01,
        restSpeedThreshold: 0.01,
        reduceMotion: ReduceMotion.Never
      });

**Comment by tipleavalentin** [comment] 2024-06-11 16:51
> Still experiencing the issue with those versions. This is becoming a huge annoyance in my project and rolling back was a big undertaking, so I edited the Drawer component myself to make it work in the meantime. Here's what worked for me.
> 
> In the file `node_modules/@react-navigation/drawer/src/views/modern/Drawer.tsx` in the `toggleDrawer` function add `reduceMotion: ReduceMotion.Never` to the animation configuration and add `ReduceMotion` as an import from `react-native-reanimated`
> 
> ```
>   translationX.value = withSpring(translateX, {
>     velocity,
>     stiffness: 1000,
>     damping: 500,
>     mass: 3,
>     overshootClamping: true,
>     restDisplacementThreshold: 0.01,
>     restSpeedThreshold: 0.01,
>     reduceMotion: ReduceMotion.Never
>   });
> ```

Hi! 
Thank for your solution. 
While this works fine on the development live run on the final build (android) it doesn't apply. I also added the property in 3 other places in node_modules/drawer folders (js compiled code) and still doesn't work.
Did you managed to fix this? 
Thanks!

**Comment by JenilynnB** [comment] 2024-06-13 22:48
Thank you for this. I hadn't done a build, only pushed an update with `eas update`

My attempts to get this to work while building on expo servers (rather than local builds) aren't working, but I'd rather not spend more time on this. Will rely on the update until the package is fixed.

**Comment by sethjhs9** [comment] 2024-06-16 18:35
Another workaround is to tell reanimated that it's not on "reduced motion" device:
In
`node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/RNRuntimeDecorator.cpp`
hardcode the environment variable to false:
```
rnRuntime.global().setProperty(
      rnRuntime, "_REANIMATED_IS_REDUCED_MOTION", false);
```

**Comment by hunaidee007** [comment] 2024-06-17 17:35
Any update on this? Still facing the issue and do not want to mess with the default builds.

**Comment by mihaibulic2** [comment] 2024-06-21 21:43
There is workaround that I'm using. I hope that a) it helps others and b) if there is a problem with it (aside from its ugliness) someone can point it out:

**THEORY**
So somewhere in the drawer code there are some assumptions that animations take time. When those are off, stuff gets broken for whatever reason. So, what if we just skipped state transitions altogether?? The key is the `defaultStatus` property, where we can choose the state the drawer renders in when it 1st renders and the `key` property, which if it every changes, forces React to rerender the component in whatever state we want. Now, the only missing piece is knowing when to do this, and that's where `NavigationContainer.onStateChange` comes in!

**CODE**
Ok ok, that's all well and good but how about some code!
```typescript
const [drawerBumpKeyHACK, setDrawerBumpKeyHACK] = useState(0);
const [showDrawerHACK, setShowDrawerHACK] = useState(false);

return (
	<NavigationContainer
      ref={navigationRef}
      onStateChange={(state) => {
        const route = state?.routes?.[state?.index];
        if (!route) {
          return;
        }

        // HACK! If reduced animation is on, the drawer doesn't always open or close:
        // https://github.com/react-navigation/react-navigation/issues/11988
        // As a workaround: force rerendering the drawer w/ the proper default state set if:
        //  - reduced Motion is on
        //  - this state change involves the 'drawer' screen (ie not modals)
        //  - the latest change (based on the history) is routing to EITHER:
        //    - a screen
        //    - opening/closing the drawer
        // Note: manually dispatching a close drawer event doesn't work: 
        //     ie this: navigationRef.current?.dispatch(DrawerActions.closeDrawer());
        if (reduceMotionEnabled && route.state?.type === 'drawer') {
          const history = route.state?.history;
          const last = history?.[history.length - 1];
          if (last) {
            if (last['type'] === 'route') {
              setShowDrawerHACK(false);
              setDrawerBumpKeyHACK((existing) => existing + 1);
            } else if (last['type'] === 'drawer') {
              setShowDrawerHACK(last['status'] === 'open');
              setDrawerBumpKeyHACK((existing) => existing + 1);
            }
          }
        }
      }} >
      <Stack.Navigator>
        <Stack.Screen
          key={`drawer-screen-${reduceMotionEnabled ? drawerBumpKeyHACK : 'default'}`}
          name={'drawer'}
        >
          {() => (
            <Drawer.Navigator
              initialRouteName={'testItem1'}
              defaultStatus={reduceMotionEnabled && showDrawerHACK ? 'open' : 'closed'}>

              <Drawer.Screen
                name={'testItem1'}
                component={MyScreen1}
              />
              <Drawer.Screen
                name={'testItem2'}
                component={MyScreen2}
              />
            </Drawer.Navigator>
		  )}

		</Stack.Screen>
	</Stack.Navigator>
</NavigationContainer>);
```

For knowing when reduced motion is enabled: in my experience useReduceMotion() doesn't work consistently
when it's used in multiple components, so I use AccessibilityInfo instead and get it myself.
``` typescript
// const reduceMotionEnabled = useReduceMotion(); // from react-native-reanimated
const [reduceMotionEnabled, setReducedMotionEnabled] = useState<boolean>(false);
useEffect(() => {
  AccessibilityInfo.isReduceMotionEnabled().then(setReducedMotionEnabled);
  const reducedMotionListener = AccessibilityInfo.addEventListener('reduceMotionChanged', (event) => {
    setReducedMotionEnabled(event.valueOf());
  });

  return () => {
    reducedMotionListener.remove();
  };
}, []);
```

**Comment by claudiofus** [comment] 2024-07-14 17:20
I had the same problem on Android after upgrade to Expo 51, the issue is resolved using these in my case:
```
"@react-navigation/drawer": "^6.7.0",
"@react-navigation/native": "^6.1.17",
"@react-navigation/stack": "^6.4.0",
"react-native-reanimated": "~3.14.0"
```

**Comment by satya164** [comment] 2024-07-14 18:50
Fixed via https://github.com/react-navigation/react-navigation/commit/c2caf87bc5df50f665442fbb0c42794cad793a3a

**Closed by satya164** 2024-07-14 18:50 UTC
Labels: bug, platform:android, platform:ios, repro provided
