### ISSUE TITLE
The 'navigation' object hasn't been initialized yet

### ISSUE THREAD

**Issue by har2008preet** [react-navigation/react-navigation#6879] opened 2020-02-18 07:08 UTC
**Current Behavior**

- Navigating by creating Service.

**Expected Behavior**

- Navigation should happen

**How to reproduce**
**app.tsx**
```
let App = inject("globalStore")(observer((props) => {

    enableScreens();

    React.useEffect(() => {

        isMountedRef.current = true;
        console.log("isNavigation Mounted: ", isMountedRef.current)

        return () => isMountedRef.current = false;
    }, [])

 

    return (

        <NavigationContainer ref={navigationServiceRef}>
            <RootNavigator
                {...this.props}/>
        </NavigationContainer>

    );
}));
export default App;

```

**NavigationService.ts**
```
import { NavigationActions, StackActions } from '@react-navigation/compat';

import * as React from 'react';

export const isMountedRef = React.createRef();

export const navigationServiceRef = React.createRef();

export function navigate(name, params) {
    if (isMountedRef.current && navigationServiceRef.current) {
        console.log("Navigation Should happen")
        try {
            navigationServiceRef.current.navigate("App", params);
        }catch(e){
            console.log("NavigationDebug Error: ", e)
        }
    } else {

    }
}

export default {
    navigate
};

```

I am getting:

> NavigationDebug Error:  Error: The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting. You can ensure that all navigators have mounted after the callback to 'useEffect' is called in your root component. See https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html#handling-initialization for more details.
    at dispatch (BaseNavigationContainer.tsx:202)
    at Object.acc.<computed> [as navigate] (BaseNavigationContainer.tsx:245)
    at Object.navigate (NavigationService.ts:34)
    at SplashScreen.redirectUser (splash-screen.tsx:232)
    at SplashScreen.proxiedMethod (createPrototypeProxy.js:44)
    at _callee2$ (splash-screen.tsx:296)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android 10
| @react-navigation/native       |5.0.5
| react-native                   |0.60.0
| expo                           |NA
| node                           |v13.6.0
| npm or yarn                    |yarn 1.21.1

**NOTE:** I am upgrading from 4.x.x via https://reactnavigation.org/docs/en/upgrading-from-4.x.html and https://reactnavigation.org/docs/en/compatibility.html

**Comment by Entryist** [comment] 2020-02-22 02:29
Encountered the same on RN 61.5. My terribly hacky workaround was to wrap navigate() in a setTimeout with 100 ms delay.

**Comment by satya164** [comment] 2020-02-22 02:51
Can you provide a repro to show when the happens?

**Comment by mohanadarafe** [comment] 2020-02-23 18:36
I have the same problem!

**Comment by har2008preet** [comment] 2020-02-24 09:18
sure @satya164 , will create snack and share it.

**Comment by satya164** [comment] 2020-03-18 14:32
Closing due to no repro. Please comment with repro to re-open.

**Closed by satya164** 2020-03-18 14:32 UTC
Labels: bug, needs repro

**Comment by alexandra-oshmyanskaya** [comment] 2020-03-26 03:33
Here is a repro.

https://snack.expo.io/@iserzhan/the-'navigation'-object-hasn't-been-initialized-yet-%7C-react-navigation

**Comment by satya164** [comment] 2020-03-26 11:04
@alexandra-oshmyanskaya https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization

**Comment by uusa35** [comment] 2020-04-10 16:35
same issue here !! anyone solved this

**Comment by uusa35** [comment] 2020-04-10 16:38
https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization 

i already did what mentioned above but still same error occurs 

The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted,

**Comment by SaeedZhiany** [comment] 2020-04-14 09:34
@satya164 

I'm facing this problem in RN 0.62.2 and react-navigation 5.x.x.

In my case, this only happens when the Fast refresh feature is enabled and I change some part of my code. it's probably a debug phase problem and should not happens in production, but it's very annoying because it makes the Fast refresh useless to development.

**Comment by gastondisacco** [comment] 2020-04-20 18:38
Same happening over here.

**Comment by gastondisacco** [comment] 2020-04-20 19:28
Facing same issue over here. Tried all doc says related with initialization. (https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization)


software | version
-- | --
iOS or Android | iOS
@react-navigation/native | 5.0.5
react-native | 0.61.0
expo | 3.18.6
node | v12.16.1
npm or yarn | 1.22.4

**Comment by superguineapig** [comment] 2020-05-05 01:06
Hi, I know this issue is closed, but I'm also having the same problem.

I did some experiments, and it looks like there is different behavior between a `class` component and a `function` component that leads to async initialization of the `navigation ref`

I put together a snack (based on the official documentation) that demonstrates this. Swap the commented `App` component to see the difference in behavior.

https://snack.expo.io/H3O3jaNxi

I'm a bit surprised that there is a difference between `useEffect` and `componentDidMount` in this regard. The v5 docs only mention using the functional `useEffect` style, but as someone who is converting over from v4 and mostly `class components`, this is a bit of a 'gotcha'.

Hope this helps.

**Comment by lapico** [comment] 2020-05-12 16:18
Same here, what's suggested in the doc is not working.

https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization

**Comment by gilbertl** [comment] 2020-05-12 16:40
> Encountered the same on RN 61.5. My terribly hacky workaround was to wrap navigate() in a setTimeout with 100 ms delay.

This works for me, although 0ms is enough.

**Comment by lapico** [comment] 2020-05-12 17:54
I don't know if this can help someone but I solved it by reversing the problem :

Instead of "navigating-without-navigation-prop" and "handling-initialization", I made the navigation prop available to my component by nesting it in another stackNavigator.

No need for a RootNavigation object and the code is also more logical in a sense...

**Comment by Bardiamist** [comment] 2020-06-08 03:09
> // You can decide what to do if the app hasn't mounted
    // You can ignore this, or add these actions to a queue you can call later

Why every app should handle it. Queue shold be created by `react-navigation`.
Also isn't clear lifecycle for me. When app can be unmounted? I thought that app can be unmounted only once one close.

**Comment by patrickreiner** [comment] 2020-07-21 03:26
+1 on this, I followed what is says here:

https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization

still getting the initialization error

**Comment by meshaabi** [comment] 2020-09-14 14:19
solved it like this, if it helps anyone
`let dispatchQueue = [];
export const dispatch = action => {
  if (navigationRef.current?.dispatch) {
    setTimeout(() => navigationRef.current.dispatch(action));
    return true;
  } else {
    dispatchQueue.push(action);
    setTimeout(() => {
      dispatchQueue = dispatchQueue.filter(value => {
        return !dispatch(value);
      });
    });
    return false;
  }
};
`

**Comment by Anurag-Srivastav** [comment] 2020-12-04 10:07
Doing the same with RN.5.. still getting the initialization error..
Followed what it says
https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization
still getting the initialization error

**Comment by upngo** [comment] 2020-12-10 21:53
`<NavigationContainer ref={navigationRef} onReady={() => { alert('navigationRef.current.dangerouslyGetState())}>...</NavigationContainer>`  returns `undefined`

onReady is returning when we the navigationRef is set, but before it can be used
It's not until the state is defined that the navigator is actually initialised and can be used

**Comment by gretzky** [comment] 2021-03-10 17:59
This issue is still happening. Repro: https://snack.expo.io/jnwNvrRLS

**Comment by hsavit1** [comment] 2021-03-29 14:15
issue still happens even if you're not using useLinking

**Comment by dale-french** [comment] 2021-04-02 10:55
Happens even when following https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization

**Comment by Alexddsilva** [comment] 2021-04-20 19:31
Still happens, this part of documentation is broken
https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization

**Comment by hsavit1** [comment] 2021-04-20 19:39
i think a key for this fix is to make sure that the navigation is "ready" . there's an `onReady` prop for the navigation container

**Comment by DeveloperDanX** [comment] 2021-04-29 10:50
> Encountered the same on RN 61.5. My terribly hacky workaround was to wrap navigate() in a setTimeout with 100 ms delay.

I have the same problem and your hacky solution seems to be a good workaround for now. ¿Did you found another one? :)

**Comment by richardwu** [comment] 2021-05-25 15:22
I have a state var that is set to `true` when `onReady` is called, but I am still experiencing this error in production.

I tried the timeout and it doesn't seem to work in my instance.

My use case here is for navigating to a certain screen when handling notifications: the error seems to occur only when the app has not previously been loaded.

**Comment by tomtargosz** [comment] 2021-06-24 22:21
Getting this error as well when attempting to use a deeplink is used to open the app when it's not running in the background. The setTimeout of 0 "works" but I'd really like to avoid that.

**Comment by chengqing97** [comment] 2021-07-01 10:01
Hey I've got a workaround here! 

It is basically set "isReady" variable to true only when the first screen inside the navigator is mounted.

This is a simplified version of my code when I am working with deep linking which I want to navigate to a screen immediately after the navigator is ready.

```
import React, { useEffect, useState } from "react";
import { createStackNavigator } from "@react-navigation/stack";
import { LogBox } from "react-native";

const Stack = createStackNavigator();

const MainStack = () => {
  const [navigatorIsReady, setNavigatorIsReady] = useState(false);

  useEffect(() => {
    if (navigatorIsReady) RootNavigation.navigate("Screen2");
  }, [navigatorIsReady]);

  LogBox.ignoreLogs(["Non-serializable values were found in the navigation state"]);

  return (
    <Stack.Navigator>
      <Stack.Screen name="Screen1" component={Screen1} initialParams={{ setNavigatorIsReady }} />
      <Stack.Screen name="Screen2" component={Screen2} />
      <Stack.Screen name="Screen3" component={Screen3} />
    </Stack.Navigator>
  );
};

export default MainStack;
```
And then in Screen1:
```
const Screen1 = ({ route }) => {
  const setNavigatorIsReady = route.params.setNavigatorIsReady;

  useEffect(() => {
    setNavigatorIsReady(true);
  }, []);
  
  return (
    <View>
      <Text>This is screen 1</Text>
    </View>
  )
}
```
I'm passing setState as params and ignoring the warning because I'm not accessing the state somewhere else and I didn't use state persistence or React Navigation's deep link as stated in the [Official Docs](https://reactnavigation.org/docs/troubleshooting/#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state). But you can use React Context as well :)

**Comment by jojonarte** [comment] 2021-07-29 16:41
Can confirm that this is still happening on the latest

**Comment by pollie80** [comment] 2021-08-24 03:14
My error was that I was missing this ref: ```<NavigationContainer ref={navigationRef}>```

**Comment by oktaysenkan** [comment] 2021-10-04 13:15
Try this, it's works for me.

```js
InteractionManager.runAfterInteractions(() => {
  navigationRef.current?.navigate('AnotherScreen');
});
```

**Comment by mschaefer-gresham** [comment] 2021-12-22 15:01
Having same issue and setTimeout is not working. Why is this issue closed?

**Comment by oktaysenkan** [comment] 2022-03-26 10:32
I created new library for handling navigation initialization

**[react-native-wait-navigation](https://github.com/oktaysenkan/react-native-wait-navigation)**

**Comment by jzxchiang1** [comment] 2022-03-30 02:59
I still see this after setting a state variable in NavigationContainer's `onReady`, and then calling `navigationRef.current?.navigate` only when that state variable becomes true in a useEffect.

Nothing seems to work (on iOS)

**Comment by azizmobarak** [comment] 2022-04-27 11:01
I have the same issue , React Native 67 and Navigation 6.x

**Comment by sudipstha08** [comment] 2022-04-28 12:16
Facing the same issue

**Comment by albert-hajdu-mondd-io** [comment] 2022-05-04 11:11
I had the same issue like a lot of commenters. Tried to navigate upon receiving notifications. Tried the NavigationContainer's ref using the docs https://reactnavigation.org/docs/navigating-without-navigation-prop#handling-initialization

The suggested createNavigationContainerRef "didn't work" I used useNavigationContainerRef instead, as @azizmobarak suggested. Now it works like it should. Not sure what's the actual bug here maybe they should just review their docs?

@react-navigation/native 6.0.8

**Comment by JoshWeiner** [comment] 2022-05-06 10:33
Would either of you @albert-hajdu-mondd-io or @azizmobarak be able to provide some sort of reproduction as to how you implemented this change? Within the framework given in the react-navigation documentation I was unable to reproduce a successful solution with the information you provided.

**Comment by albert-hajdu-mondd-io** [comment] 2022-05-06 16:02
@JoshWeiner something like this:

```
export const App = () => {
  const navigationRef = useNavigationContainerRef()

  const navigate = (name: any, params: any) => {
    if (navigationRef.isReady()) {
      navigationRef.navigate(name, params)
    }
  }

  useEffect(() => {
    Notifications.events().registerNotificationOpened((notification: Notification, completion) => {
      navigate(...)
      completion()
    })
  }, [])

  return (
    <NavigationContainer ref={navigationRef}>
      ...
    </NavigationContainer>
  )
}
```

**Comment by YuriVini** [comment] 2022-05-25 16:41
For who is getting this error in a jest test. That's what I did...

```
const { getByTestId } = render(
      <RecoilRoot>
        <NavigationContainer ref={navigationRef}>
          <ComponentHere {...props} />
        </NavigationContainer>
      </RecoilRoot>
    );

const yourTextID = getByTestId('yourTextID');

setTimeout(() => {
      fireEvent.press(yourTextID);
}, 1000);
```

**Comment by mikhail-talkshoplive** [comment] 2022-07-28 06:47
why this issue closed?  if app opened and user click universal link, navigationRef.isReady() - is always false, even after 10 second timeout

**Comment by oktaysenkan** [comment] 2022-07-28 08:04
> why this issue closed? if app opened and user click universal link, navigationRef.isReady() - is always false, even after 10 second timeout https://reactnavigation.org/docs/deep-linking/ "If the app was already open, the deep link needs to update the state to reflect the incoming link" - how to update if navigationRef.isReady() = false?

checkout this library

[https://github.com/oktaysenkan/react-native-wait-navigation](https://github.com/oktaysenkan/react-native-wait-navigation)

**Comment by mtnt** [comment] 2022-07-28 08:11
> checkout this library
> 
> https://github.com/oktaysenkan/react-native-wait-navigation

Why you made the lib to fix an issues of another one? If you know how to fix, just make a PR =)

**Comment by mikhail-talkshoplive** [comment] 2022-07-29 12:59
> > why this issue closed? if app opened and user click universal link, navigationRef.isReady() - is always false, even after 10 second timeout https://reactnavigation.org/docs/deep-linking/ "If the app was already open, the deep link needs to update the state to reflect the incoming link" - how to update if navigationRef.isReady() = false?
> 
> checkout this library
> 
> https://github.com/oktaysenkan/react-native-wait-navigation

thanks, your package solved my problem

**Comment by azizmobarak** [comment] 2022-07-29 22:06
> I have the same issue , React Native 67 and Navigation 6.x
> 
> have just fixed it , this is an example 
> 
> ```
> const navigationRef = useNavigationContainerRef();
>  const yourRefName = useRef<any>(); // add some type
> 
> const onStateChanged = () => {
>     yourRefName.current  = navigationRef.getCurrentRoute(); // use ref here to change value
>   };
> 
>   const onNavigationReady = () => {
>     routeNameRef.current = navigationRef.getCurrentRoute(); // initialise ref 
>   };
> 
>   return (
>     <NavigationContainer
>       ref={navigationRef} // link navigation to the container
>       onReady={onNavigationReady}
>       onStateChange={onStateChanged}
>     >
> ....
> </NavigationContainer>
> 
> ```

My code here solves the issue , don t use extra code or inject new libraries ext...

**Comment by angmarb** [comment] 2022-11-08 13:10
My team have experienced "The 'navigation' object hasn't been initialized yet" error inside `onReady` callback. The problem was with conditional rendering inside `NavigationContainer`, like:
```
<NavigationContainer>
  if (condition1) {
   return <StackNavigator1>;
  }
  if (condition2) {
   return <SomeScreen>;
  }
  if (condition3) {
   return <StackNavigator2>;
  }
</NavigationContainer>
```
rewriting it so every stack is stable with a navigation container solved the issue:
```
  if (condition1) {
   return 
     <NavigationContainer>
      <StackNavigator1> 
   </NavigationContainer>
  }
  if (condition2) {
   return <SomeScreen>;
  }
  if (condition3) {
   return 
     <NavigationContainer>
      <StackNavigator2> 
   </NavigationContainer>
  }
```
Hope that helps someone.

**Comment by adamchenwei** [comment] 2023-03-17 22:29
Dont need to use 3rd party lib, dont wrapper multi navigator with navigationcontainer, dont do wait.
Just make sure all your screens inside a navigator are NOT wrapped within a conditional toggle. you shouldn't see it appear again. At least thats what helped me. Hope it helps u, or someone 🤷

**Comment by arinze090** [comment] 2023-03-30 15:19
I fixed mine by doing this

import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

// state variables
const [isFirstLaunch, setIsFirstLaunch] = useState(null);
const navigationRef = createNavigationContainerRef();

  // To show the onboarding screen on just first launch
  useEffect(() => {
    let isMounted = true;
    if (isMounted) {
      AsyncStorage.getItem('alreadyLaunched').then(value => {
        if (value === null) {
          AsyncStorage.setItem('alreadyLaunched', 'true');
          setIsFirstLaunch(true);
          console.log('isFirstLaunch');
        } else {
          setIsFirstLaunch(false);
          console.log('notIsFirstLaunch');
        }
      });
    }
    return () => {
      isMounted = false;
    };
  }, []);
  
  
    // Displaying the app component on several conditions
  if (isFirstLaunch === null) {
    return null;
  } else if (isFirstLaunch === true) {
    return (
      <NavigationContainer ref={navigationRef}  headerMode="none">
        <Stack.Screen name="Onboarding" component={OnboardingScreen}  />
        <Stack.Screen name="Home" component={MainScreen}  />
      </NavigationContainer>
    );
  } else {
    return (
      <NavigationContainer ref={navigationRef}  headerMode="none">
        <Stack.Screen name="Home" component={MainScreen}  />
      </NavigationContainer>
    );
  }



I hope this helps someone

**Comment by arinze090** [comment] 2023-03-30 15:21
`import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

// state variables
const [isFirstLaunch, setIsFirstLaunch] = useState(null);
const navigationRef = createNavigationContainerRef();

// To show the onboarding screen on just first launch
useEffect(() => {
let isMounted = true;
if (isMounted) {
AsyncStorage.getItem('alreadyLaunched').then(value => {
if (value === null) {
AsyncStorage.setItem('alreadyLaunched', 'true');
setIsFirstLaunch(true);
console.log('isFirstLaunch');
} else {
setIsFirstLaunch(false);
console.log('notIsFirstLaunch');
}
});
}
return () => {
isMounted = false;
};
}, []);

// Displaying the app component on several conditions
if (isFirstLaunch === null) {
return null;
} else if (isFirstLaunch === true) {
return (

<Stack.Screen name="Onboarding" component={OnboardingScreen} />
<Stack.Screen name="Home" component={MainScreen} />

);
} else {
return (

<Stack.Screen name="Home" component={MainScreen} />

);
}`

**Comment by NorbertSanpruch** [comment] 2023-03-31 11:07
I am facing the same issue with deep links and push notifications. I've created a function that checks if the navigationRef is ready and returns a promise.

```
  const waitForNavigationToBeReady = () => {
    const checkIfReady = (resolve: (value: unknown) => void) => {
      if (navigationRef.isReady()) {
        resolve(true);
      }

      setTimeout(() => {
        checkIfReady(resolve);
      }, 25);
    };

    return new Promise(resolve => {
      checkIfReady(resolve);
    });
  };
```
It checks if navigation is ready each 25 ms. Then in my handleDeepLink function I do
```
  const handleDeepLink = async () => {
    await waitForNavigationToBeReady();
    navigationRef.navigate();
  };
```

Hope it helps someone.

**Comment by 2sem** [comment] 2023-04-26 23:56
I met this problem when I modify font size in the setting app.
So I solved it by calling navigation dispatch in a timeout.
```
setTimeout(() => {
      NavigationService.replace({
        routeName: targetScreen,
        params: {
          ...
        },
      })
    }, 0)
```

**Comment by 2sem** [comment] 2023-05-02 01:09
This is not error, I can't catch it.
This problem is occurred when I modify font size in the settings app on android device.

This is so weird, I tried to call on 'focus' event in the first screen.
However problem was not disappeared.

So I had to resolve with setTimeout.

**Comment by vincentmegia** [comment] 2023-10-05 12:05
For Jest what's weird this worked for me, normally we don't need instance of Stack.Navigator

`
<NavigationContainer ref={navigationRef}>
      <Provider store={store}>
        <Login />
      </Provider>
      <Stack.Navigator>
        <Stack.Screen name='someScreen' component={SomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
`

**Comment by m-korkut** [comment] 2023-10-24 07:52
I still get the error.
isReady() function returns false in all cases.

**Comment by DavidKnight-Bluescape** [comment] 2023-11-15 09:12
> My error was that I was missing this ref: `<NavigationContainer ref={navigationRef}>`

Thank you - this was not explicitly mentioned in the docs, and is a crucial step. Maybe its obvious to folks who have been using this library for a while, but was not for me.

**Comment by HugoBounoua** [comment] 2024-03-28 17:00
SOLUTION:
Your initialization is correct:
```
<NavigationContext.Provider value={isNavigationContextReady ? navigationRef.current : null}>
     <NavigationContainer ref={navigationRef} onReady={() => setIsNavigationContextReady(true)}>
         ....
```
But your usage is not.
You are referencing the navigation like this and it's good:
```
const appNavigation: NavigationContainerRef<AppNavigationScreens> | null = useAppNavigation() as NavigationContainerRef<AppNavigationScreens> | null;
```
And you use it automatically without a user event (which normally takes a few seconds..) before the navigation is ready.
But the problem is that the navigation might not be ready when you USE it.
What you want to be doing is waiting for the navigation to actually tell you it's ready, like so:
```useEffect(() =>
    {
        if(appNavigation && appNavigation.isReady())
            appNavigation.navigate("IT_IS_SAFE_TO_NAVIGATE");
        else
           console.log(`AppNavigation is not ready yet...`);
    }, [appNavigation?.isReady()]);

**Comment by maik-emanoel** [comment] 2025-08-11 12:36
> I am facing the same issue with deep links and push notifications. I've created a function that checks if the navigationRef is ready and returns a promise.
> 
> ```
>   const waitForNavigationToBeReady = () => {
>     const checkIfReady = (resolve: (value: unknown) => void) => {
>       if (navigationRef.isReady()) {
>         resolve(true);
>       }
> 
>       setTimeout(() => {
>         checkIfReady(resolve);
>       }, 25);
>     };
> 
>     return new Promise(resolve => {
>       checkIfReady(resolve);
>     });
>   };
> ```
> 
> It checks if navigation is ready each 25 ms. Then in my handleDeepLink function I do
> 
> ```
>   const handleDeepLink = async () => {
>     await waitForNavigationToBeReady();
>     navigationRef.navigate();
>   };
> ```
> 
> Hope it helps someone.

This solution solved the issue to me. Thanks, man.
