### ISSUE TITLE
Bottom bar floats above and then goes back to its correct position at first render.

### ISSUE THREAD

**Issue by Morritz** [react-navigation/react-navigation#9616] opened 2021-05-24 15:33 UTC
**Current Behavior**

When bottom tab bar appears it is not in correct place but above it, and then after a while drops into right position.
**Expected Behavior**

It should be on this bottom position closest to the edge by default, and not above.

**How to reproduce**

https://github.com/Morritz/bottomtab_repro_reactnavigation5

 + snack
https://snack.expo.io/K8N9V2DWG

This repo has required code to reproduce, it is made from blank react native app, only app.js is modified and
results are as described in "Current Behaviour" on my real device and emulator,
The only device that didnt have problems with it so far is phone when android controls back home etc. are not on the screen but on offscreen touchable part (maybe it has something to it).

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | 5.9.4
| @react-navigation/bottom-tabs | 5.11.11
| react-native-screens          | 3.2.0
| react-native                  | 0.64.1
| expo                          |  no
| node                          |
| npm or yarn                   |

![](https://i.gyazo.com/21e024296223548372d0f545be54dc32.gif)

**Comment by Morritz** [comment] 2021-05-24 20:42
Another reproduction:
https://snack.expo.io/K8N9V2DWG

**Comment by satya164** [comment] 2021-05-25 10:29
Looks like it's caused by wrapping of the navigator in `Layout` from ui-kittens. Closing since this only happens from third-party lib code.

**Closed by satya164** 2021-05-25 10:29 UTC
Labels: bug, package:bottom-tabs, repro provided

**Comment by Morritz** [comment] 2021-05-25 12:29
> Looks like it's caused by wrapping of the navigator in `Layout` from ui-kittens. Closing since this only happens from third-party lib code.

No it is not `Layout`.
Here with removed: https://snack.expo.io/I09TcmbIr

**Comment by Morritz** [comment] 2021-05-26 00:01
This issue **is not dependent on third-party libraries.**
+Snack: https://snack.expo.io/BIX_dg1VT   /w  simplest setup.

**Comment by Vinnecent** [comment] 2021-06-07 19:51
I have the same problem.
It can be reproduced with the Snack provided by the "Minimal example of tab-based navigation" of the react navigation guide page https://reactnavigation.org/docs/tab-based-navigation/

**Comment by Morritz** [comment] 2021-06-07 23:20
> I have the same problem.
> It can be reproduced with the Snack provided by the "Minimal example of tab-based navigation" of the react navigation guide page https://reactnavigation.org/docs/tab-based-navigation/

Try this as workaround for now https://github.com/react-navigation/react-navigation/issues/9623#issuecomment-849084445

**Comment by shmakovmd** [comment] 2022-10-22 09:35
I solved this problem by adding fixed height to "tabBarStyle" and to custom buttons style ("tabBarButton")

Before:
![before (2)](https://user-images.githubusercontent.com/94179397/197332201-7bc65f68-5502-4b9c-92a2-5d9a63f4e102.gif)
After:
![after (1)](https://user-images.githubusercontent.com/94179397/197332195-9c8b9fe7-d73f-4b92-90f1-f2005f29db03.gif)
