### ISSUE TITLE
'getStateForAction' has two actions at the navigator beginning

### ISSUE THREAD

**Issue by llwcy8801** [react-navigation/react-navigation#4387] opened 2018-05-31 10:07 UTC
### Current Behavior

I made a Navigator just like this
```
const Navigator = createStackNavigator({
    Tab: {
      screen: createBottomTabNavigator({
        { Home: { screen: HomeScene } },
        { Follow:{ screen: FollowScene } }
      }, {
        initialRouteName: 'Home'
      })
    }
  }, {
    initialRouteName: 'Tab'
  }
)
Navigator.router.getStateForAction = (action, state) => {
  console.log(action)
  return defaultGetStateForAction(action, state)
}
```
The first time i change home to follow, it will have two actions. Should it be just once?
![image](https://user-images.githubusercontent.com/16318164/40777909-d5770c60-6501-11e8-96cd-ef8311746551.png)

### Expected Behavior

It should be just one action at the navigator beginning

### Your Environment

| software         | version
| react-navigation | 2.0.4
| react-native     | 0.55.3
| node             | 9.4.0
| yarn      | 1.5.1

**Comment by brentvatne** [comment] 2018-05-31 19:34
cc @ericvicenti

**Comment by ericvicenti** [comment] 2018-05-31 19:55
This behavior is strange and I'll look into it. But it shouldn't matter how many times the reducer gets called, it just returns the next state. Sometimes the reducer will get called while the navigator isn't even active. This is by design- the router is just meant to return the new state based on an action and the previous state.

**Comment by JarRySW** [comment] 2018-06-01 02:47
I use 'getStateForAction' to judge the user has logged in or not by adding a route.
Use like this.
![image](https://user-images.githubusercontent.com/16318164/40817991-971b5d6e-6587-11e8-8517-603757b27b93.png)
The first time i change Home to Follow the reducer gets called twice. And the two actions are same they all route to follow. So it will open LoginScene twice. But after that, all changes will just call the reducer once. I just feel strange.
Thank you for the reply!

**Comment by satya164** [comment] 2020-06-29 14:00
Closing since like @ericvicenti said, how many times a reducer gets called shouldn't matter.

**Closed by satya164** 2020-06-29 14:00 UTC
Labels: bug, version-4
