### ISSUE TITLE
`useDrawerStatus` hook returns multiple times during the swipe guesture

### ISSUE THREAD

**Issue by likeSo** [react-navigation/react-navigation#10036] opened 2021-10-12 07:05 UTC
### Current behavior

> I need a new drawer instance every time the drawer opens, so i used the `useDrawerStatus` hook.
> Everytime the hook returns 'open', i return the actual `drawerContent` otherwise i return null
>
> ```tsx
> export default function ProductFilterDrawer(props: ProductFilterDrawerProps) {
>   const drawerStatus = useDrawerStatus();
>   return drawerStatus === 'open' ? <DrawerContent {...props} /> : null;
> }
> ```

**But the `drawerContent` sometimes shows a white blank because the `useDrawerStatus` hook returns `close` even the drawer background already display, which i am swiping from screen right edge**
![Simulator Screen Shot - iPhone 12 Pro - 2021-10-12 at 13 41 31](https://user-images.githubusercontent.com/12247340/136904049-63e1624c-64ba-4da3-923e-e17efd1d8633.png)

### Expected behavior

When the white background display, the `useDrawerStatus` hook should always return 'open'
Otherwise, it should always return 'close'

### Reproduction

https://snack.expo.dev/@likeso/drawer-content-problem

### Platform

- [ ] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.5 
| @react-navigation/bottom-tabs          | ^6.0.8
| @react-navigation/drawer               |^6.1.7
| @react-navigation/material-bottom-tabs |-
| @react-navigation/material-top-tabs    |^6.0.5
| @react-navigation/stack                |^6.0.10
| @react-navigation/native-stack         |-
| react-native-safe-area-context         |3.2.0
| react-native-screens                   |~3.4.0
| react-native-gesture-handler           |~1.10.2
| react-native-reanimated                |~2.2.0
| react-native-tab-view                  |^3.1.1
| react-native-pager-view                |5.0.12
| react-native                           |0.63.2
| expo                                   |~42.0.1
| node                                   |v14.17.5
| npm or yarn                            |yarn

**Comment by likeSo** [comment] 2021-10-30 03:54
Thank you! Just `return <DrawerContent {...props} />;` surely resolve the UI problem, and that is what i did before.
But this is drawer used for filter, i need to read all conditions from context when it mounts and **clears all UNSAVED states** after it unmounts.
So i need always init a new instance after the `useDrawerStatus ()` returns `open`
To do that, i have these ways:
- Use `useDrawerStatus ()`, and read states from context, then clears all  unsaved states one by one;
  - It is a stupid way
- Use `useDrawerStatus ()`, and return a new instance every time it returns `open`
  -  The drawer content sometimes disappeared before it closed, it's a problem.
- Ask React Navigation team, add a `unmountDrawerContentWhenClose` prop
  - I created a feature request in canny before, they suggest me the second way

There is no perfect way to do that now, I need help

**Comment by zed-shawn** [comment] 2021-11-01 16:29
From what I understand as per your requirements, you can still display the UI for filters at all times, and use useDrawerStatus() to clear the Unsaved states after it closes. 

As in, store all the saved+ unsaved states in a temp variable and render the UI based on it. Due to this, when the user taps outside the Drawer, and useDrawerStatus() returns close instantly, the user would still see the UI that was being rendered before closing. Then put a timeout for whatever the animation duration is, and after that time, you can run your logic to clear unsaved states.

As for rendering the UI while the drawer opens, you can display the default settings, and once it's fully opened, animate the filters to their state.

Alternatively, you can use skeleton placeholders to give a loading feel, but that won't be applicable while closing.

I know all of this feels like a hackjob, which it partly is, but since the React Navigation team has already passed on it for now, these would be the quickest way to get going.

**Comment by likeSo** [comment] 2021-11-04 09:10
I think the real problem is that **this hook reports the wrong status** while i am swipping.
Surely i can clear all status after this hook returns 'close', But my temporary may be cleared prematurely due to the wrong status of drawer content.

**Comment by galbeiroc** [comment] 2021-11-05 18:52
**Drawer status is now a string instead of a boolean [*Docs Drawer*](https://reactnavigation.org/docs/drawer-based-navigation/)

Previously, the status of drawer was a boolean (true | false) to signify the open and closed states. It's now a string with the values open and closed. 

_useIsDrawerOpen_ -> _useDrawerStatus_

If you would like to determine if drawer is open or closed, you can do the following:

```
import { useDrawerStatus } from '@react-navigation/drawer';

// ...

const isDrawerOpen = useDrawerStatus() === 'open';
```

**Comment by likeSo** [comment] 2021-11-06 10:54
@galbeiroc Yes i know that, but my point is that the hook reports multiple times during my finger swipe the drawer content!
It is not reporting the correct status of the drawer!
Please refer to my repro

**Comment by satya164** [comment] 2021-11-06 13:29
The hook is working as designed. The status of the drawer isn't determined until you lift your finger - it could close or open, which is impossible to predict while you're swiping. The status is known once you lift your finger, or when you open/close the drawer via a button.

Re-rendering things while the drawer is animating can also cause frame drops in the animation and will also not be an instant which will cause visible flicker with UI suddenly changing.

You should re-consider your design whether you really need to do this, or there are other ways to achieve what you want (e.g. clearing the state when the drawer is closed). Though UX-wise it seems weird that filters are cleared upon closing the drawer.

If you really need to do this, you can subscribe to the animation progress using `useDrawerProgress()` which will report an animated value/shared value (depending on the version of reanimated you are using) with `0` for closed, `1` for open and non-zero values while it's not fully open or closed. Please refer to reanimated docs on how to subscribe to animated value.

**Closed by satya164** 2021-11-06 13:29 UTC
Labels: bug, package:drawer, platform:web, package:stack, platform:ios, repro provided
