### ISSUE TITLE
statusBar blink and take the wrong color on view change

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#7977] opened 2020-04-08 08:50 UTC
In react-navigation v5 alpha, when I navigate between views, I have my statusBar color blinking.

Its final state is often not the one desired, while in development and working on the view, it get's to the right color after hot reload, but when navigating, it's often the dark theme that win.

Even if I use in the next view:

```jsx
<StatusBar barStyle="light-content" translucent={true} backgroundColor="transparent" />
```

This happen in expo SDK36 application.

How can I fix this?

**Comment by raajnadar** [comment] 2020-05-17 06:12
Closing this since I am not able to reproduce this issue & no repro from your side.

**Closed by raajnadar** 2020-05-17 06:12 UTC
Labels: needs repro

**Comment by itwen02** [comment] 2021-08-18 02:22
Generally, it can be reproduced on Huawei mobile phones

**Comment by mehedirana** [comment] 2022-01-10 06:07
<StatusBar barStyle="light-content" translucent={true} backgroundColor="transparent" />
 Here, culprit translucent ={true}, If I switch true to false. It will be perfect. But I didn't find any solution yet. I need transparent 
app status bar in Android and IOS
