### ISSUE TITLE
this.props.navigation.dispatch(NavigationActions.back({key: '***'})) error 

### ISSUE THREAD

**Issue by zlei123456** [react-navigation/react-navigation#3274] opened 2018-01-15 14:02 UTC
i find a error, 
back to a Component ,but back to this component of order -1

      if (action.type === NavigationActions.BACK) {
        const key = action.key;
        let backRouteIndex = null;
        if (key) {
          const backRoute = state.routes.find(
            (route: NavigationRoute) => route.key === key
          );
          /* $FlowFixMe */
          backRouteIndex = state.routes.indexOf(backRoute);
        }
        if (backRouteIndex == null) {
          return StateUtils.pop(state);
        }
        if (backRouteIndex > 0) {
          return {
            ...state,
            routes: state.routes.slice(0, backRouteIndex),
            index: backRouteIndex - 1,
          };
        }

this code "backRouteIndex = state.routes.indexOf(backRoute)",this result is start with 0, but  this function of 'state.routes.slice' no contain end index. so router z order -1.

**Comment by kelset** [comment] 2018-01-15 14:09
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-15 14:09 UTC
