### ISSUE TITLE
iOS : can't press while scrolling inside a swipeEnabled TabNavigator

### ISSUE THREAD

**Issue by Kernael** [react-navigation/react-navigation#2458] opened 2017-08-24 08:52 UTC
### Current Behavior

Only in iOS :

Given a `FlatList` and any kind of touchable, inside a `TabNavigator` with `swipeEnabled: true`,
the `onPress` prop of the touchable will not trigger while the `FlatList` is scrolling.

The bug does not occur with `swipeEnabled: false`

Router code : 

```
const Tabs = TabNavigator({
  A: { screen: ScreenA },
  B: { screen: ScreenB },
  C: { screen: ScreenC },
}, {
  swipeEnabled: true,
});

const AppRouter = StackNavigator({
  Main: { screen: Tabs },
}, {
  headerMode: 'none',
});
```

Screen A code :

```
import React from 'react';
import { View, FlatList, Text, TouchableOpacity } from 'react-native';
import uuid from 'uuid/v4';

const data = Array(150).fill(0).map(() => uuid())

class ScreenA extends React.PureComponent {
  render() {
    return (
      <View style={{ flex: 1, marginTop: 200 }}>
        <TouchableOpacity onPress={() => console.log('pressed')}>
          <View style={{ width: 500, height: 30, backgroundColor: 'red' }} />
        </TouchableOpacity>
        <FlatList
          ref={userList => (this._userList = userList)}
          data={data}
          renderItem={({ item }) => <Text>{item}</Text>}
          keyExtractor={item => item}
        />
      </View>
    );
  }
}

export default ScreenA;
```

### Expected Behavior

The touchable's action should trigger even when the FlatList is scrolling.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | #5e075e1 (beta12)
| react-native     | 0.46.1
| node             | 8.4.0
| npm or yarn      | 0.27.5

**Comment by kelset** [comment] 2017-12-03 10:59
Pinging OP @Kernael  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by Kernael** [comment] 2017-12-04 08:06
Hello @kelset,

I can still reproduce this bug : https://snack.expo.io/SJLpxtfbf

Code :

```
import React from 'react';
import { View, FlatList, Text, TouchableOpacity } from 'react-native';
import uuid from 'uuid/v4'; // 3.1.0
import { TabNavigator, StackNavigator } from 'react-navigation' // 1.0.0-beta.21

const data = Array(150).fill(0).map(() => uuid())

class ScreenA extends React.PureComponent {
  render() {
    return (
      <View style={{ flex: 1, marginTop: 200 }}>
        <TouchableOpacity onPress={() => this._userList.scrollToOffset({ offset: 0, animated: true })}>
          <View style={{ width: 500, height: 30, backgroundColor: 'red' }} />
        </TouchableOpacity>
        <FlatList
          ref={userList => (this._userList = userList)}
          data={data}
          renderItem={({ item }) => <Text>{item}</Text>}
          keyExtractor={item => item}
        />
      </View>
    );
  }
}

const Tabs = TabNavigator({
  A: { screen: ScreenA },
}, {
  swipeEnabled: true,
});

const AppRouter = StackNavigator({
  Main: { screen: Tabs },
}, {
  headerMode: 'none',
});

export default class App {
  render() {
    return (
      <AppRouter />
    );
  }
}
```

**Comment by satya164** [comment] 2017-12-28 17:04
This is likely an issue with React Native rather than anything specific to tab navigator.

**Comment by kohkimakimoto** [comment] 2018-01-13 01:23
I have same issue. and In my environment, this issue also occurs with `swipeEnabled: false`.

**Comment by kohkimakimoto** [comment] 2018-01-14 06:01
I have been struggling with this issue for few days. Now I think that this issue is caused by React Native unresolved problem that related to https://github.com/facebook/react-native/issues/10822

Detail:

In the react-navigation, this issue is caused by the code using default `renderPager`. 

See https://github.com/react-navigation/react-navigation/blob/v1.0.0-beta.26/src/views/TabView/TabView.js#L208

If we don't set `animationEnabled: false` or `swipeEnabled: false`, react-navigation doesn't execute above code. The `renderPager` is `undefined`. `react-native-tab-view` that is used in the react-navigation uses default renderPager: `TabViewPagerScroll` (in iOS). 

See https://github.com/react-native-community/react-native-tab-view/blob/v0.0.74/src/TabViewAnimated.js#L44

The `TabViewPagerScroll`'s render method returns a React component that wrapped by `ScrollView`. 

See https://github.com/react-native-community/react-native-tab-view/blob/v0.0.74/src/TabViewPagerScroll.js#L128

Therefore, if we use `FlatList` in the TabNavigator, we use nested `ScrollView`. This situation has a problem: https://github.com/facebook/react-native/issues/10822

Workaround 1:

Set `animationEnabled: false` and `swipeEnabled: false`.

Workaround 2:

Wrap your `FlatList` by `ScrollView`. like the following

```
<ScrollView>
    <FlatList 
      data={data}
      renderItem={({ item }) => <Text>{item}</Text>}
      ...
    />
</ScrollView>
```

**Comment by brentvatne** [comment] 2018-06-28 00:41
hiya! if this is still an issue for you, please repost to https://github.com/react-navigation/react-navigation-tabs :) thanks for all of the info you shared above @kohkimakimoto!

**Closed by brentvatne** 2018-06-28 00:41 UTC
Labels: bug, component: Tabs
