### ISSUE TITLE
Navigation crashed on latest version 3.9.1

### ISSUE THREAD

**Issue by Techdojo** [react-navigation/react-navigation#5905] opened 2019-05-10 13:34 UTC
I'm suffering from exactly the same issue as described by @dukemai in Nov 2018 (see https://github.com/react-navigation/react-navigation/issues/5244).

The issue was closed after the OP commented that he was able to fix the issue by downgrading react-native.
However I have tried to replicate his solution to no avail (as have others @beng970804) and as per the request by @brentvatne I've creating a new issue.

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

Using TypeScript - I've created a switchNavigator with an initial auth check and two nested stack navigators as per the auth flow guide on the react navigation website.

```
const AuthStack = createStackNavigator({
    Login: LoginScreen,
});

const AppStack = createStackNavigator({
    Home: HomeScreen,
    Cause: CauseDetails,
    Retailer: RetailerDetails,
});

export default createAppContainer(
    createSwitchNavigator({
        Loading: LoadingScreen,
        AuthStack: AuthStack,
        AppStack: AppStack
    },{
        initialRouteName: 'Loading'
    })
);

```
In the `LoadingScreen` component any attempt to navigate to either the `AuthStack` or the `AppStack` or any of their child screens using 

```
  componentDidMount() {
    setTimeout(() => {
      this.props.navigation.navigate('Login');
    }, 2000);
  }
```
(this is to simulate the response from an Axios authentication call to be added later)
will immediately crash with an `TypeError: undefined is not an object(evaluating 'this._callListeners.bind')` and show a stacktrace that is almost identical to the one posted by the OP (see attached)
![Screenshot 2019-05-09 at 15 20 00](https://user-images.githubusercontent.com/296893/57529761-9ad6c600-732d-11e9-9b5b-192492077bda.png)

If I move all the screens into the root of the switch navigator such as 
```
export default createAppContainer(
    createSwitchNavigator({
        Loading: LoadingScreen,
        Login: LoginScreen,
        Home: HomeScreen,
        Cause: CauseDetails,
       Retailer: RetailerDetails,
    },{
        initialRouteName: 'Loading'
    })
);
```
Then the above navigation works perfectly.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

I expect to be able to navigate in to and out of child navigators using the examples specified.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

Bootstrap a basic app using 

```
react-native init testNav
cd testNav
npm install react-navigation --save
npm install react-native-gesture-handler --save
react-native link react-native-gesture-handler
```
and implement the code pattern above

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | 0.59.5
| node             | 10.15.3
| npm or yarn      | npm 6.4.1

package.json
```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "lint": "tslint src/**/*.ts*",
    "tsc": "tsc",
    "clean": "rimraf build",
    "build": "npm run clean && npm run tsc && mkdir build/src/assets && cp -R src/assets build/src",
    "watch": "npm run build -w",
    "watchAndRunAndroid": "concurrently \"npm run watch\" \"npm run android\"",
    "buildRunAndroid": "npm run build && npm run watchAndRunAndroid ",
    "watchAndRunIOS": "concurrently \"npm run watch\" \"npm run ios\"",
    "buildRunIOS": "npm run build && npm run watchAndRunIOS ",
    "watchAndStart": "concurrently \"npm run watch\" \"npm run start\"",
    "buildAndStart": "npm run build && npm run watchAndStart ",
    "updateSnapshots": "jest --updateSnapshot"
  },
  "dependencies": {
    "@types/react-native-vector-icons": "^6.4.0",
    "axios": "^0.18.0",
    "build": "^0.1.4",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-paper": "^2.15.2",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.9.1",
    "react-redux": "^7.0.3",
    "redux": "^4.0.1",
    "redux-axios-middleware": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "@types/jest": "^24.0.12",
    "@types/react": "^16.8.15",
    "@types/react-dom": "^16.8.4",
    "@types/react-native": "^0.57.51",
    "@types/react-test-renderer": "^16.8.1",
    "babel-jest": "^24.7.1",
    "concurrently": "^4.1.0",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3",
    "rimraf": "^2.6.3",
    "ts-jest": "^24.0.2",
    "tslint": "^5.16.0",
    "typescript": "^3.4.5"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by yasir-lateef** [comment] 2019-05-10 17:21
Facing the same issue after upgrading to RN 0.59, but in a slightly different manner. SwitchNavigator works fine in the debug mode but in release mode, first attempt to navigate to TabNavigator causes the App to close without any crash report. However, restarting the app works fine and the TabNavigator gets loaded fine.

`export default createAppContainer(
createSwitchNavigator(
  {
	LoadingScreen: LoadingScreen,
    MainApp: HomeScreen,
    LandingScreen: LandingScreen
  },
  {
    initialRouteName: 'LoadingScreen',
  }
)
);`

**Comment by eriveltonelias** [comment] 2019-05-13 13:15
hi! please make your code runnable either on https://snack.expo.io or in a project i can clone from github, without any extraneous code

**Comment by Techdojo** [comment] 2019-05-15 16:10
@eriveltonelias - thanks for the response. Here's a link to a github project you can clone.
https://github.com/Techdojo/brokenReactNavigationIssue
It's a standard setup, just follow the instructions in the readme.
The routes are setup in src/Router.tsx

Any questions feel free to post a comment.
Thanks 
👍

**Comment by satya164** [comment] 2019-05-16 09:04
It happens because of your babel configuration. You're compiling class properties in loose mode which can produce different non spec-compliant results. https://github.com/Techdojo/brokenReactNavigationIssue/blob/6425aae5c848226cb6260da25a40dec6b7922f5e/babel.config.js#L3

Removing this line makes it run. I'm closing the issue since it's not a bug in React Navigation.

**Closed by satya164** 2019-05-16 09:04 UTC
Labels: needs repro

**Comment by Techdojo** [comment] 2019-05-16 09:31
@satya164 Thanks for the heads up 👍 I'll get that change made in our app codebase 😀

**Comment by Techdojo** [comment] 2019-05-16 11:07
@satya164 - I tried your fix by removing that line and it didn't make any difference (see attached screengrab), any chance of getting this issue re-opened?
![Screenshot_1558004582](https://user-images.githubusercontent.com/296893/57849377-0fe54800-77d3-11e9-9d98-3c03241c536b.png)

**Comment by satya164** [comment] 2019-05-16 11:13
You need to reset metro cache. `react-native start --reset-cache`. I ran your project locally and it worked with this change.

**Comment by Techdojo** [comment] 2019-05-16 12:52
@satya164 - That fixed the issue for me, many thanks 👍 💯 😀

**Comment by jonlambert** [comment] 2019-05-23 18:55
I'm getting the same issue here, unfortunately not fixed by running with the `--reset-cache` flag. My `babel.config.js` file looks like this:

```js
module.exports = {
  presets: ['module:metro-react-native-babel-preset', 'mobx']
};
```

Any hints would be greatly appreciated 😅

**Comment by satya164** [comment] 2019-05-23 19:03
Remove the `mobx` preset: https://github.com/zwhitchcox/babel-preset-mobx/blob/master/index.js#L5
