### ISSUE TITLE
FlatList Bottom Row of Grid Partially Hidden Behind TabBar

### ISSUE THREAD

**Issue by geirman** [react-navigation/react-navigation#3467] opened 2018-02-07 23:04 UTC
### Current Behavior

I have a typical gallery of images, but the bottom row is partially hidden behind the TabBar. 

        <View style={styles.galleryContainer}>
          <FlatList
            data={submissions[activeGallery]}
            keyExtractor={item => `${item.taskCode}_${item.submissionId}`}
            renderItem={({ item }) =>
              item.photoUrl && <Thumbnail eventId={event.id} photoUrl={item.photoUrl} style={{ paddingLeft: gutter, paddingBottom: gutter }} />
            }
            numColumns={columnCount}
          />
        </View>

Here's a visual...

<img width="841" alt="2018-02-07_1457" src="https://user-images.githubusercontent.com/1640318/35946188-b33dba24-0c17-11e8-8ac8-6f576c3110db.png">

### Expected Behavior

This doesn't seem to be happening on other FlatLists where I'm rendering card views rather than grid

<img width="865" alt="2018-02-07_1459" src="https://user-images.githubusercontent.com/1640318/35946221-cf1c4134-0c17-11e8-8f88-d5ba335af0cf.png">

### How to reproduce
Pretty sure you'll see this if you simply create a flat list and render a bunch of thumbnails as I have. I did try removing the `numColumns` so that they rendered in a single (long) column, but the issue persisted which confuses me a bit. I thought it might have something to do with the `numColumns` being defined, but nope. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.27
| react-native     | https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz
| node             | v8.2.1
| npm or yarn      | yarn 1.2.1, npm 5.3.0

**Comment by brentvatne** [comment] 2018-02-07 23:59
hey @geirman! sorry for being a stickler on this one but we do say in the issue template that a Snack or Github repo reproducing it is required. if we need to dig in and try to re-create the bug (often it can't be reproduced when we try) before even investigating a fix that takes up the time of maintainers (only a few) versus the time of people reporting issues (many hundreds). I'm happy to look at this when you have a Snack or Github repo reproducing it! thanks

**Comment by kelset** [comment] 2018-02-08 09:55
Wild guesses:
1. have you tried with a iPhone nonX simulator?
1. maybe related to how the single Image is styled? (fixed dimension or there's some resizing going on)?

**Comment by geirman** [comment] 2018-02-08 17:10
Thx Brent, I didn't read closely enough, but I'll see if I can repo this with a minimal case. If not, would it be good enough to give you (or your designate) temporary access to my private repo?

**Comment by ericvicenti** [comment] 2018-02-08 20:04
Can you try applying some borders to tell if it really goes behind the tab bar, or if FlatList is clipping it? Is it possibly a FlatList bug with numColumns mode?

**Comment by geirman** [comment] 2018-02-08 20:56
Thanks Eric, here's a few gifs that will hopefully be helpful. I got [started on a snack](https://snack.expo.io/@geirman/issue-tabnavigation-flatlist), but I'm not having any luck reproducing it so far, and for some odd reason I can't get the `TabBarBottom` component to render on Android. So, I'm not sure if there's a fundamental problem with the snack preventing me from reproducing the issue or if there's a fundamental problem in my code. I'll come back to this and give it another try later, but a magic number will get me by for now.

Incidentally, I'm seeing this consistently on every device I've tested on (iPhone X Simulator, physical iPhone 6, plus two physical android devices [moto z, moto x]). It doesn't seem to be an issue with `numColumns` as I noted above. This was my original thought. But when I remove that, the problem still exists (see last gif). And it goes away with the magic number as you'd expect. Incidentally, I chose a magic number that is the same as [tabBarCompact's Value](https://github.com/react-navigation/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L272). As you can see, it works great. A

Also, each image is 90x90, hard coded. I saw a comment here earlier by Lorenzo (now deleted) wondering about whether there was some resizing shenanigans going on.  


### Here's the expected behavior (with magic number hack)
![2018-02-08_1230 - issue with magic number](https://user-images.githubusercontent.com/1640318/35996653-ef78e0ae-0ccb-11e8-8c9f-5ba14b46b6a1.gif)

### Here's the actual behavior (without magic number hack)
![2018-02-08_1230 - issue without magic number](https://user-images.githubusercontent.com/1640318/35996654-ef9d49d0-0ccb-11e8-9257-870c35ec1155.gif)

### Here's a demonstration without `numColumns`
![yna3tg4pbg](https://user-images.githubusercontent.com/1640318/35996914-bbed9dd2-0ccc-11e8-86c9-3e2caf7b872c.gif)

**Comment by brentvatne** [comment] 2018-02-08 21:40
thank you @geirman! the issue with the tab bar bottom was that the config needs to be an object rather than a function -- https://snack.expo.io/B1B67B5IM.

**Comment by brentvatne** [comment] 2018-02-08 22:02
I'll close this because it seems like we can't reproduce the issue, please feel free to open a new issue with the repro if you can find out how!

**Closed by brentvatne** 2018-02-08 22:02 UTC
Labels: needs repro

**Comment by ericvicenti** [comment] 2018-02-08 22:04
I'd like to see this issue reproduced without flat list next time. If the tab bar covers everything, and thats the wrong behavior, we can fix that!

**Comment by geirman** [comment] 2018-02-08 23:31
@brentvatne thanks for fixing the navOptions. At first I didn't understand what you meant because the function returned an object, but then I realized in order for that to work I would have had to call it as a function like this...

```
const Tabs = TabNavigator(routeConfigs, navOptions());
```

# Doh! 

@ericvicenti I'll let you know if I come across that scenario as well 👍

**Comment by FrancescoBonizzi** [comment] 2022-04-10 05:55
> @brentvatne thanks for fixing the navOptions. At first I didn't understand what you meant because the function returned an object, but then I realized in order for that to work I would have had to call it as a function like this...
> 
> 
> 
> ```
> 
> const Tabs = TabNavigator(routeConfigs, navOptions());
> 
> ```
> 
> 
> 
> # Doh! 
> 
> 
> 
> @ericvicenti I'll let you know if I come across that scenario as well 👍 

At the end did you find a solution without the magic number?

**Comment by KeaganStevens** [comment] 2022-08-24 08:53
The problem often has to do with margin, or more specifically vertical margin. Try removing all vertical margin on screen and see what if it looks as expected.
