### ISSUE TITLE
Where can I see the release note of beta 27?

### ISSUE THREAD

**Issue by wellyshen** [react-navigation/react-navigation#3302] opened 2018-01-18 14:02 UTC
I have not upgrade to beta 27, because I'm waiting for the release note but where is it?

**Comment by kelset** [comment] 2018-01-18 14:19
Hi @wellyshen! It looks like this is not a bug of the library nor a feature request, so I'll close it.

That said, release notes are not generated automatically, one of the maintainers have to write them - so it can happen that it takes a bit of time. You can always check the [commits on master](https://github.com/react-navigation/react-navigation/commits/master) to get an idea of what changed since last release. By the look of it it was a [simple revert](https://github.com/react-navigation/react-navigation/commit/8cf2953115b16296fa205e9fa2e571df9b3f4438).

If you believe that you are experiencing a bug or have a feature request, please open a new Issue following the dedicated template or submit a PR.

**Closed by kelset** 2018-01-18 14:19 UTC
