### ISSUE TITLE
DrawerPosition set to right not showing

### ISSUE THREAD

**Issue by eskiesirius** [react-navigation/react-navigation#8484] opened 2020-06-20 19:52 UTC
**Current Behavior**

When setting the position to right, then trying to open the drawer.. it will just make the background dim but the display of drawer is not showing

**Expected Behavior**

it should open the drawer from the right side

**How to reproduce**

just set the drawerPosition to right

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       |  ^5.5.1
| @react-navigation/drawer       |  ^5.8.2
| react-native-reanimated        |  ^1.9.0
| react-native-gesture-handler   |  ^1.6.1
| react-native-safe-area-context |  ^3.0.3
| react-native-screens           | ^2.8.0
| react-native                   | 0.62.2

**Comment by eskiesirius** [comment] 2020-06-21 14:06
Here is my Main
```
const Drawer = createDrawerNavigator()
const DrawerScreen = () => (
	<Drawer.Navigator 
		drawerStyle={{
	    width: Dimensions.get('window').width * 0.6,
	  }}
		drawerContent={(props) => <SideMenu {...props} />}
	>
		<Drawer.Screen name="HomeTab" component={BottomTabScreen}/>
	</Drawer.Navigator>
)

const Master = () => {

	return (
		<SafeAreaView style={{ flex: 1 }}>
			<DrawerScreen />
		</SafeAreaView>
	)
}
```

My drawer
```
<DrawerContentScrollView {...props} style={{ backgroundColor: '#7A426A' }}>
			<View style={styles.container}>
				<View style={styles.profile_container}>
					<Image source={{uri: `data:image/gif;base64,${userProfile ? userProfile.image_1920 : ''}`}} style={styles.avatar}/>
					<Text style={styles.username_text}>{userProfile ? userProfile.display_name : ''}</Text>
				</View>
				<View style={styles.menu_container}>
					<DrawerItem
						label="Account Settings"
						labelStyle={styles.menu_text}
					/>
					<DrawerItem
						label="Notifications"
						labelStyle={styles.menu_text}
					/>
					<DrawerItem
						label="Wallet"
						labelStyle={styles.menu_text}
					/>
					<DrawerItem
						label="Logout"
						onPress={() => Logout()}
						labelStyle={styles.menu_text}
					/>
				</View>
				<View style={styles.footer}>
					<Image source={require('../../../../assets/images/medux_logo.png')}/>
				</View>
			</View>
		</DrawerContentScrollView>

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: '#7A426A',
	},
	profile_container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 20
	},
	avatar: {
		height: 100,
		width: 100,
		borderRadius: 50,
		marginBottom: 10
	},
	username_text: {
		color: '#FFFFFF',
		fontSize: 14,
		fontFamily: 'OpenSans-Bold',
		marginBottom: 20
	},
	menu_container: {
		flex: 1,
		backgroundColor: 'white',
	},
	menu_text: {
		color:'#707070',
		fontSize: 16,
		fontFamily: 'Gilroy-ExtraBold',
	},
	footer: {
		flex: 1,
		justifyContent: 'flex-end',
		alignItems: 'center',
		height: Dimensions.get('window').height * 0.43,
		backgroundColor: 'white',
		paddingBottom: 50
	}
})
```
My tab navigation
```
<View style={styles.container}>
	  {state.routes.map((route, index) => {
		const { options } = descriptors[route.key];
		const label =
		  options.tabBarLabel !== undefined
			? options.tabBarLabel
			: options.title !== undefined
			? options.title
			: route.name;

		const isFocused = state.index === index;

		const onPress = () => {
		  const event = navigation.emit({
			type: 'tabPress',
			target: route.key,
			canPreventDefault: true,
		  });

		  if (!isFocused && !event.defaultPrevented) {
			navigation.navigate(route.name);
		  }
		};

		const onLongPress = () => {
		  navigation.emit({
			type: 'tabLongPress',
			target: route.key,
		  });
		};

		let icon

		if (route.name == 'Home')
			icon = require('../../../../assets/images/tab-icons/home.png')
		else if (route.name == 'Doctors')
			icon = require('../../../../assets/images/tab-icons/doctor.png')
		else if (route.name == 'Appointments')
			icon = require('../../../../assets/images/tab-icons/calendar.png')
		else if (route.name == 'Prescriptions')
			icon = require('../../../../assets/images/tab-icons/notepad.png')
		else
			icon = require('../../../../assets/images/tab-icons/flask.png')

		return (
			<TouchableOpacity
				accessibilityRole="button"
				accessibilityStates={isFocused ? ['selected'] : []}
				accessibilityLabel={options.tabBarAccessibilityLabel}
				testID={options.tabBarTestID}
				onPress={onPress}
				onLongPress={onLongPress}
				style={styles.touchable_container}
			>
				<View style={styles.menu_container}>
					<View style={{flex: 1, alignItems: 'center',justifyContent: 'flex-end'}}>
						<Image source={icon} />
						<Text style={styles.menu_text}>
							{label}
						</Text>
					</View>
					<View style={{flex: 0.4, alignItems: 'center',justifyContent: 'center'}}>
						<View style={{
							width: 17,
							borderWidth: isFocused ? 1 : 0,
							borderColor: '#FFFFFF',
							borderRadius: 4,
						}} />
					</View>
				</View>
		  </TouchableOpacity>
		);
	  })}
	</View>

const styles = StyleSheet.create({
	container: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#7A426A',
		height: Dimensions.get('window').height * 0.13
	},
	touchable_container: {
		flex: 1,
		alignItems: 'center',
	},
	menu_container: {
		alignItems: 'center',
	},
	menu_text: {
		fontSize: 7,
		color: '#FFFFFF',
		fontFamily: 'OpenSans-Regular',
		textAlign: 'center'
	}
})
```

**Comment by geekrepos** [comment] 2020-06-29 20:36
Are you working on this??
Please open my issue (#8374 ) too, it's not solved yet.

**Comment by eskiesirius** [comment] 2020-06-29 23:14
same...

**Comment by raajnadar** [comment] 2020-06-30 12:41
Try this snack it work properly https://snack.expo.io/@raajnadar/f835a8.

Make sure you are using the latest package version https://github.com/react-navigation/react-navigation#package-versions.

Clear the metro cache `npx react-native run-android` or `expo start -c`

**Comment by raajnadar** [comment] 2020-06-30 12:48
@eskiesirius I am closing this issue.

**Closed by raajnadar** 2020-06-30 12:48 UTC
Labels: bug, needs repro, package:drawer

**Comment by geekrepos** [comment] 2020-07-01 17:10
> Try this snack it work properly https://snack.expo.io/@raajnadar/f835a8.
> 
> Make sure you are using the latest package version https://github.com/react-navigation/react-navigation#package-versions.
> 
> Clear the metro cache `npx react-native run-android` or `expo start -c`

@raajnadar I have modified your snack to https://snack.expo.io/3Mswy0K1Z . Please have a look at it. Its not working.
Its the same issue #8374

**Comment by eskiesirius** [comment] 2020-07-02 16:02
Please close this issue.. it is already fixed in the new version.. thank you

**Comment by yazmnh87** [comment] 2020-07-10 18:36
I had this issue, the default action is opening on the left, after changing it I had to relaunch the app in the simulator and then it worked properly]

**Comment by ElieudoMaia** [comment] 2020-08-08 11:12
As @yazmnh87 said, just change the position in your code and restart the app server that will work correctly.
Necessary process both in the simulator and in the expo client app.

**Comment by geekrepos** [comment] 2020-08-08 11:16
@ElieudoMaia  can you please transform and correct code in this snack. 
https://snack.expo.io/3Mswy0K1Z

and show me how should I do. Please

**Comment by thaque20** [comment] 2020-08-19 12:28
Thanks @yazmnh87 , It worked perfectly fine for me.

**Comment by ryanjwessel** [comment] 2020-08-28 12:34
There are many issues related to `drawerPosition='right'` not working as expected, which is what drew me here as well. 

It wasn't until @yazmnh87 's suggestion that I realized you have to reload the Metro bundle in order to see any content in the drawer navigator.

Is this something that can be added to the docs? Something like:

```
drawerPosition
Options are left or right. Default is left position.
If you change this value, you will need to relaunch your app for the drawer to work properly.
```

Ideally, the drawer would still work when switching the position prop, but I have not looked at the source code for this functionality.

**Comment by linhld123** [comment] 2020-09-29 09:26
I think drawerPosition='right' has issues, when I use drawerPosition="right" worked fine for me.

**Comment by spacesuitdiver** [comment] 2020-10-08 22:43
> There are many issues related to `drawerPosition='right'` not working as expected, which is what drew me here as well.
> 
> It wasn't until @yazmnh87 's suggestion that I realized you have to reload the Metro bundle in order to see any content in the drawer navigator.
> 
> Is this something that can be added to the docs? Something like:
> 
> ```
> drawerPosition
> Options are left or right. Default is left position.
> If you change this value, you will need to relaunch your app for the drawer to work properly.
> ```
> 
> Ideally, the drawer would still work when switching the position prop, but I have not looked at the source code for this functionality.

Thank you for taking the time to post this in this issue, you just saved me from mass confusion.

**Comment by geekrepos** [comment] 2020-10-15 10:18
> I had this issue, the default action is opening on the left, after changing it I had to relaunch the app in the simulator and then it worked properly]



> There are many issues related to `drawerPosition='right'` not working as expected, which is what drew me here as well.
> 
> It wasn't until @yazmnh87 's suggestion that I realized you have to reload the Metro bundle in order to see any content in the drawer navigator.
> 
> Is this something that can be added to the docs? Something like:
> 
> ```
> drawerPosition
> Options are left or right. Default is left position.
> If you change this value, you will need to relaunch your app for the drawer to work properly.
> ```
> 
> Ideally, the drawer would still work when switching the position prop, but I have not looked at the source code for this functionality.

In previous versions of react navigation till 4.X, there is no need to relaunch the app you can switch drawer position on the fly. So why in this 5.X version we need to restart app.

**Comment by Ruturaj2728** [comment] 2021-07-06 11:56
to open the drawer from the right side just add: drawerType="back" and drawerPosition="right"

It's working for me without relaunch an app

**Comment by ankitpmi** [comment] 2021-07-06 11:58
> to open the drawer from the right side just add: drawerType="back" and drawerPosition="right"
> 
> It's working for me without relaunch an app

right, it's working

**Comment by sam9010** [comment] 2021-09-08 08:59
screenOptions={{drawerPosition: 'right' }}

for example

<Drawer.Navigator
          screenOptions={{drawerPosition: 'right' }}
      >
        <Stack.Screen name="Main" component={Main} />
      </Drawer.Navigator>

**Comment by nhanta0408** [comment] 2021-10-01 17:03
[IT WORKS FOR ME]
I also had this problem and solved it successfully.
I spent 1 days trying many different ways that shown by many guys, but does not work.
I used drawer navigation 6.x and I recognized there is something was missed.
------------------------
If you read the Getting Started documentation carefully, you will see a step that adding some code for java file MainActivity of android folder.
https://reactnavigation.org/docs/getting-started
After that, restart the Metro and run-android again.
I tried that and it  works.
Good luck

**Comment by 11AA8R4** [comment] 2021-11-02 10:22
deprected `drawerPosition="right"`
actual `screenOptions = {{ drawerPosition:'right' , headerShown:false}}`

**Comment by emadbaqeri** [comment] 2021-11-02 10:28
> deprected `drawerPosition="right"` actual `screenOptions = {{ drawerPosition:'right' , headerShown:false}}`

What do you mean by this, can you clarify this  a bit more?

**Comment by Brysonmk1984** [comment] 2021-11-09 16:51
> deprected `drawerPosition="right"` actual `screenOptions = {{ drawerPosition:'right' , headerShown:false}}`

@11AA8R4 Thank you! none of the other answers worked for me.

@emadbaqeri , If you're using the deprecated style === drawerPosition="right", you need to remove it and use the screenOptions prop to set drawerPosition:"right".

**Comment by emadbaqeri** [comment] 2021-11-10 09:08
> > deprected `drawerPosition="right"` actual `screenOptions = {{ drawerPosition:'right' , headerShown:false}}`
> 
> @11AA8R4 Thank you! none of the other answers worked for me.
> 
> @emadbaqeri , If you're using the deprecated style === drawerPosition="right", you need to remove it and use the screenOptions prop to set drawerPosition:"right".

Thanks for your attention I have tested all the possibilities and finally I have figured out that the problem is the catch when we are running the app in debug mode, I have cleared the cache and uninstalled the debug version of the app from  the emulator then the issue was gone

**Comment by mashebang** [comment] 2021-11-12 14:32
> screenOptions = {{ drawerPosition:'right' , headerShown:false}}

this worked fine for me, thanks

**Comment by DevVibhor** [comment] 2022-01-09 05:17
This worked for me as well 
`screenOptions={{drawerPosition: 'right'}}` for version `"@react-navigation/drawer": "^6.1.8"`

**Comment by mukash** [comment] 2022-03-11 13:41
I added an issue related to drawer navigation, it kind of an odd behavior, would appreciate the help Thanks

https://stackoverflow.com/questions/71435167/drawer-navigation-position-right?noredirect=1#comment126263402_71435167

**Comment by 11AA8R4** [comment] 2022-03-11 14:31
> I added an issue related to drawer navigation, it kind of an odd behavior after adding position right, would appreciate the help Thanks
> 
> https://stackoverflow.com/questions/71435167/drawer-navigation-position-right
as of -v "@react-navigation/drawer": "^6.3.1"
Probably their gonna fix this soon, but for now:
`screenOptions={{drawerPosition:'right',headerShown:false,drawerStyle:{right:0}}}`
