### ISSUE TITLE
navigate from a page without a navigation bar to a page with a navigation bar, the previous page flashes

### ISSUE THREAD

**Issue by longdw** [react-navigation/react-navigation#3395] opened 2018-01-31 15:08 UTC
###navigate from a page without a navigation bar to a page with a navigation bar, the previous page flashes

```
const RouteConfigs = {
    Login: {
        screen: LoginScreen,
        navigationOptions: {
            header: null
        }
    },
    Netset: {
        screen: NetsetScreen
    }
}
```
**in Login.js navigate like this:**
`this.props.navigation.navigate('Netset')`

![123](https://user-images.githubusercontent.com/4987178/35630104-6719996a-06db-11e8-986f-dec99fa2232a.gif)

### run in ios

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.27
| react-native     |0.52.1
| node             |7.2.1
| npm or yarn      |1.3.2

**Comment by kelset** [comment] 2018-01-31 15:35
duplicate of https://github.com/react-navigation/react-navigation/issues/2732

**Closed by kelset** 2018-01-31 15:35 UTC
