### ISSUE TITLE
StackNavigator needs cardStyle

### ISSUE THREAD

**Issue by a-koka** [react-navigation/react-navigation#2575] opened 2017-09-13 15:51 UTC
### Current Behavior
`StackNavigator` displays white background behind `absolute` positioned transparent images and `TextInputs`. Adding a cardStyle with any `backgroundColor` fixes the issue.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.46.4
| node             |  6.10.0

**Comment by matthamil** [comment] 2017-09-15 00:58
Could you flesh out this RFC a little more? Would this be something that would fall under [`navigationOption`](https://reactnavigation.org/docs/navigators/navigation-options)s

**Comment by a-koka** [comment] 2017-09-15 15:09
Sure! Below is a fully working example. Seems like a corner case with `absolute` positions and `shadowOpacity`. Notice how un-commenting the `cardStyle` fixes the issue.

    import React, { Component } from 'react';
    import {
      AppRegistry,
      Image,
      View
    } from 'react-native';

    import { StackNavigator } from 'react-navigation';

    class HomeScreen extends React.Component {
      static navigationOptions = {
        title: 'Welcome'
      };
      render() {
        const { navigate } = this.props.navigation;
        return (
          <View style={{flex: 1}}>
            <Image style={{position: 'absolute', top: 0, bottom: 0, left: 0, right: 0}} source={{uri: 'https://static.pexels.com/photos/33109/fall-autumn-red-season.jpg'}} />
            <View style={{position: 'absolute', bottom: 100, shadowOpacity: 0.2}}>
              <Image style={{width: 300, height: 100}} source={{uri: 'https://discoversdkcdn.azureedge.net/postscontent/logo-578x270.png'}} />
            </View>
          </View>
        );
      }
    }

    const SimpleApp = StackNavigator({
      Home: { screen: HomeScreen },
    }, {
      headerMode: 'none',
      // cardStyle: { backgroundColor: 'transparent' }
    });

    AppRegistry.registerComponent('SimpleApp', () => SimpleApp);

**Comment by kelset** [comment] 2017-12-10 13:00
Pinging OP @a-koka since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by a-koka** [comment] 2017-12-10 16:05
Yes, this is still a problem in version `^1.0.0-beta.21`.

**Comment by brentvatne** [comment] 2018-02-10 20:09
I don't understand what the problem is here &mdash; I just copied the example over to https://snack.expo.io/@react-navigation/issue-2575 and it does what I would expect it to do. Can you re-create this issue and follow the new issue template? Thanks!

**Closed by brentvatne** 2018-02-10 20:09 UTC
Labels: bug, component: Stack
