### ISSUE TITLE
Modal incorrectly flying in from right to left instead of from bottom to top

### ISSUE THREAD

**Issue by quadsurf** [react-navigation/react-navigation#3332] opened 2018-01-23 03:24 UTC
the docs claim that the default animation for a modal is supposed to be 'bottomToTop' ... but the modal never does that, it always flies in from right to left. Whether I rely on the expected default, or declare the transition's direction explicitly, it doesn't matter, it still always flies the modal in from the right whether direction is declared or not.

I need the modal to fly in from the bottom, please. Here is my setup:

(I'm running react-navigation@1.0.0-beta.27, react-native@0.52)
```
const ModalNavigator = StackNavigator(
  {
    Root: { screen:Claims }
  },
  {
    initialRouteName: 'Root',
    headerMode: 'none',
    mode: 'modal',
    direction: 'bottomToTop',
    navigationOptions: {
      gesturesEnabled: true
    }
  }
)

const RootStack = StackNavigator(
  {
    Root: { screen: AuthState },
    LoggedOut: { screen: Login },
    LoggedIn: { screen: TabNav },
    Messages: { screen: Messages },
    Claims: { screen: ModalNavigator }
  },
  {
    initialRouteName: 'Root',
    headerMode: 'none'
  }
)
```

**Comment by kelset** [comment] 2018-01-23 08:37
Closing because you haven't followed the issue template; please open a new one that follows the template.
I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-23 08:37 UTC
