### ISSUE TITLE
Drawer does not close when clicking outside of drawer

### ISSUE THREAD

**Issue by keviny8312** [react-navigation/react-navigation#6405] opened 2019-10-22 08:19 UTC
Hi all, this is the code I am running:

```javascript
import React from 'react';
import MapView from 'react-native-maps';
import { StyleSheet, Text, View, Dimensions, SafeAreaView, ScrollView, Button, Image, TouchableOpacity } from 'react-native';
import { createDrawerNavigator, DrawerNavigatorItems, DrawerItems } from 'react-navigation-drawer';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import HomeScreen from './screens/HomeScreen'
import SettingsScreen from './screens/SettingsScreen'
import MapScreen from './screens/MapScreen'

class App extends React.Component {
  toggleDrawer = () => {
    //Props to open/close the drawer
    this.props.navigationProps.toggleDrawer({
    });
  };
  render() {
    return (
      <View style={{ flexDirection: 'row' }}>
        <TouchableOpacity onPress={this.toggleDrawer.bind(this)}>{}
          <Image
            source={require('./icons/drawer_icon.png')}
            style={{ width: 25, height: 25, marginLeft: 5 }}
          />
        </TouchableOpacity>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    //Pick one of the below colors for the background, maybe relate to the theme?
    backgroundColor: '#40ffc2',
    backgroundColor: '#ff6640',
    backgroundColor: '#ffc940',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapStyle: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  footerContainer: {
    padding: 20,
    backgroundColor: 'lightgrey',
  },
});

``
const HomeScreen_StackNavigator = createStackNavigator({
  //All the screen from the Screen1 will be indexed here
  Home: {
    screen: HomeScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Demo Screen 1',
      headerLeft: <App navigationProps={navigation} />,
      headerStyle: {
        backgroundColor: '#FF9800',
      },
      headerTintColor: '#fff',
    }),
  },
});
 
const SettingsScreen_StackNavigator = createStackNavigator({
  //All the screen from the Screen2 will be indexed here
  Settings: {
    screen: SettingsScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Settings Screen',
      headerLeft: <App navigationProps={navigation} />,
      headerStyle: {
        backgroundColor: '#FF9800',
      },
      headerTintColor: '#fff',
    }),
  },
});

const MapScreen_StackNavigator = createStackNavigator({
  //All the screen from the Screen2 will be indexed here
  Map: {
    screen: MapScreen,
    navigationOptions: ({ navigation }) => ({
      title: 'Map Screen',
      headerLeft: <App navigationProps={navigation} />,
      headerStyle: {
        backgroundColor: '#FF9800',
      },
      headerTintColor: '#fff',
    }),
  },
});

const CustomDrawerContentComponent = (props) => (
  <ScrollView>
    <SafeAreaView
      style={styles.container}
      forceInset={{ top: 'always', horizontal: 'never' }}
    >
      <DrawerItems {...props} />
    </SafeAreaView>
  </ScrollView>
   
);

const MyDrawerNavigator = createDrawerNavigator({
  Home: {
    screen: HomeScreen_StackNavigator,
    navigationOptions: {
      drawerLabel: 'Home Screen',
    },
  },
  Settings: {
    screen: SettingsScreen_StackNavigator, 
    navigationOptions: {
      drawerLabel: 'Settings Screen',
    },
  },
  Map: {
    screen: MapScreen_StackNavigator,
    navigationOptions: {
      drawerLabel: 'Map Screen',
    },
  }
},  
  {
    drawerWidth: 300

});
 
 export default createAppContainer(MyDrawerNavigator);

```
When I run this code, swiping in from the left and clicking outside of the drawer allows for the drawer to closer properly. However, when using a menu button I assigned to open the drawer, clicking outside of it does not close it when the drawer opens fully. On the other hand, if the outside of the drawer is clicked before the drawer gets to open fully, then it will close.

When the drawer opens via the menu button, and the drawer opens fully, I should be able to close it simply by clicking the background.

I saw in this issue [https://github.com/react-navigation/react-navigation/issues/5508](url), and they mentioned that they needed to fully install by opening MainActivity.java. Since I am working out of react native via Expo, I don't have access to the native code, and I'd prefer to not eject. Any pointers in the right direction is greatly appreciated.

| software         | version
| ---------------- | -------
| react-navigation | 4.x
| react-native     | 0.59.8
| node             | 10.16.3
| npm or yarn      | 6.9.0

**Comment by club9822** [comment] 2019-10-23 05:19
eject expo is inevitable . do it now and test.
duplicate of 
Duplicate of [5959](https://github.com/react-navigation/react-navigation/issues/5959)#

**Comment by Anil300298** [comment] 2019-10-23 09:49
yeah, even I am facing the same issue !!

**Comment by kikeztw** [comment] 2019-11-01 00:19
"react": "16.11.0",
"react-native": "0.61.2",
"react-navigation": "^4.0.10",

this worked for me 
add this to  MainActivity.java


```
import com.facebook.react.ReactActivity;
 // add this
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;**
/* ------------------------------ */

public class MainActivity extends ReactActivity {

    @Override
    protected String getMainComponentName() {
        return "Example";
    }

   // add the below
   +  @Override
   +  protected ReactActivityDelegate createReactActivityDelegate() {
   +    return new ReactActivityDelegate(this, getMainComponentName()) {
   +      @Override
   +      protected ReactRootView createRootView() {
   +       return new RNGestureHandlerEnabledRootView(MainActivity.this);
   +      }
   +    };
   +  }
}
```

**Comment by bijomon-tolexo** [comment] 2019-12-08 12:01
@kikeztw already having  this in MainActivity.java but not working.

**Comment by kikeztw** [comment] 2019-12-08 16:10
@bijomon-tolexo  Did you try to delete the app and reinstall it after editing the MainActivity.java? sometimes the change is not seen until you reinstall the app in the emulator

**Comment by ThailanHigor** [comment] 2020-02-02 02:56
This worked for me.
https://reactnavigation.org/docs/en/getting-started.html#installation

**Comment by usmanramay** [comment] 2020-02-14 07:49
in the index.js of your project:

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'

AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));

**Closed** 2020-02-15 18:21 UTC
Labels: version-4

**Comment by ogntech** [comment] 2020-09-15 20:38
> "react": "16.11.0",
> "react-native": "0.61.2",
> "react-navigation": "^4.0.10",
> 
> this worked for me
> add this to MainActivity.java
> 
> ```
> import com.facebook.react.ReactActivity;
>  // add this
> + import com.facebook.react.ReactActivityDelegate;
> + import com.facebook.react.ReactRootView;
> + import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;**
> /* ------------------------------ */
> 
> public class MainActivity extends ReactActivity {
> 
>     @Override
>     protected String getMainComponentName() {
>         return "Example";
>     }
> 
>    // add the below
>    +  @Override
>    +  protected ReactActivityDelegate createReactActivityDelegate() {
>    +    return new ReactActivityDelegate(this, getMainComponentName()) {
>    +      @Override
>    +      protected ReactRootView createRootView() {
>    +       return new RNGestureHandlerEnabledRootView(MainActivity.this);
>    +      }
>    +    };
>    +  }
> }
> ```

Worked for me! Thanks!

**Comment by santosgabriel** [comment] 2021-05-07 13:39
I had a difference situation here and the above answers didn't work for me. So I did the below and it's working again.

I updated the package `react-native-reanimated` to version 2, which starts to give me the following warn in the console:
`Reanimated: interpolate from V1 has been renamed to interpolateNode.`

The drawer then starts to working only when calling programmatically with open and close. The solution was downgrade it to version 1.

In case this help someone else, don't forget to also run:
`cd ios && pod install`
`cd android && ./gradlew clean`

**Comment by kkureli** [comment] 2021-08-13 11:36
For me the problem was debugger mode was active. When I disabled debugger, it worked

**Comment by HanKienjd** [comment] 2022-01-07 09:45
> For me the problem was debugger mode was active. When I disabled debugger, it worked

Thanks

**Comment by asinha0609** [comment] 2022-09-16 06:49
> For me the problem was debugger mode was active. When I disabled debugger, it worked

Correct....

**Comment by ali-kashan-sc** [comment] 2022-12-13 10:52
not usefull

**Comment by ROSHANSEBASTIAN** [comment] 2022-12-26 14:39
@ali-kashan-sc 
Did you find any fix?

**Comment by ravindraguptacapgemini** [comment] 2023-06-29 11:26
@kkureli @usmanramay tried your fixes but still no luck.
This issue is still there with version 6.6.2 of @react-navigation/drawer, please suggest a fix. Temporary fix was to remove line 39 of file node_modules/@react-navigation/drawer/src/views/modern/Overlay.tsx:
`      pointerEvents: active ? 'auto' : 'none',
`
This issue is happening from long time but there is no proper solution.
