### ISSUE TITLE
App re-renders after POST

### ISSUE THREAD

**Issue by benwilburn** [react-navigation/react-navigation#3569] opened 2018-02-22 06:50 UTC
# Issue
In the `Home1Test` component you can see a `<Button />`, within the `onPress()` prop I have a POST request. -- This actually fires and _works_; However, as you can see, I'm not manually navigating/setting state anywhere afterwards. Despite this, my app re-renders and I'm back to the `Home1Home` route.

###### _(this is a generic example of my code but it still has the same problem)_
To reproduce this issue: run `create-react-native-app whatever-you-want-to-call-it`, `yarn add react-navigation axios` then copy/paste the below code in `App.js` and import the above.

I don't understand why my app is re-rendering based on the POST request. Any help would be appreciated.

```
export default class App extends React.Component {
  render() {
    return (
      <Tabs />
    );
  }
}

class Home1Home extends React.Component {
  state = {
    tests: {}
  }
  componentWillMount() {
    axios.get('http://localhost:3000/tests').then(res => this.setState({ tests: res.data }))
  }

  render() {
    const { navigation } = this.props
    return (
      <View>
        <Button title={'Go To Test'} onPress={() => navigation.navigate('Home1Test')} />
      </View>
    )
  }
}

const Home1Test = ({ navigation }) => (
  <View>
    <Button title={'Post and go home'} onPress={() => {
        axios.post('http://localhost:3000/tests', { 'testy': 'testy' })
      }} />
  </View>
)

const Home1 = new StackNavigator({
  Home1Home: {
    screen: Home1Home
  },
  Home1Test: {
    screen: Home1Test
  }
})

const Tabs = new TabNavigator({
  Home1: {
    screen: Home1
  },
})
```

**Comment by brentvatne** [comment] 2018-02-22 07:33
hello! i cannot reproduce this. I do not have the server that you are running locally but that should be irrelevant. please reproduce this on [snack](https://snack.expo.io). I copied your code there and added the imports, you can start from there: https://snack.expo.io/HJ-mGenDM

**Comment by matthamil** [comment] 2018-02-22 07:34
Hey @benwilburn :wave: I converted your code into a runnable [Snack](https://snack.expo.io/S1LPMx3PM); however, I can't reproduce the problem you describe. This doesn't look like a problem with react-navigation, but rather, a problem with a component setting state based on a lifecycle method like `componentWillMount()`. I'm taking a guess here because I can't reproduce the behavior you describe.

**Comment by matthamil** [comment] 2018-02-22 07:34
Looks like you beat me to it @brentvatne :).

**Comment by benwilburn** [comment] 2018-02-22 17:49
@matthamil I have commented the `componentWillMount()` code out (I accidentally included it here). It still re-renders on POST.

**Comment by matthamil** [comment] 2018-02-22 18:44
Can you modify the Snack so that it reproduces the problem? @benwilburn

**Comment by benwilburn** [comment] 2018-02-22 18:57
I'm working on getting a basic api to call from to do just that ^^ I will let you know when it's finished.

**Comment by brentvatne** [comment] 2018-02-23 23:02
cool. please create a new issue with the example when you get a chance to. i suspect you won't be able to re-create it so i will close this :)

**Closed by brentvatne** 2018-02-23 23:02 UTC
Labels: needs repro

**Comment by sienkashing** [comment] 2018-07-23 11:58
Funnily enough I also encountered this same behaviour when testing an axios POST request, but:
1) It was to a json-server
2) Connected to a json file in my react native project
3) With my device (not emulator) connected to the metro package manager
4) With "Live Reload" enabled.

So as you can imagine, every time I ran the axios Post method to the json-server, it updates data of the json file and it triggers an app reload. When I pieced it all together, I literally facepalmed when I discovered what was happening. 

Not sure if this is helpful for OP, but I did land on this thread when I faced this issue initially. My fix was just [blacklisting](https://stackoverflow.com/questions/41813211/how-to-make-react-native-packager-ignore-certain-directories) my test folder from metro packager (so it doesn't auto reload my app on save) which had the json file which json-server was updating.

**Comment by amkorousagi** [comment] 2021-01-13 07:42
@sienkashing 
Thank you for your solution. my json file exists in App project directory, too(like your description). now I know why App is reloaded. I saved a time to search not existing error thank for you. (it was natural thing in React's realtime-compilation or debug)

**Comment by see-king** [comment] 2021-03-03 10:41
> Funnily enough I also encountered this same behaviour when testing an axios POST request, but:
> 
> 1. It was to a json-server
> 2. Connected to a json file in my react native project
> 3. With my device (not emulator) connected to the metro package manager
> 4. With "Live Reload" enabled.
> 
> So as you can imagine, every time I ran the axios Post method to the json-server, it updates data of the json file and it triggers an app reload. When I pieced it all together, I literally facepalmed when I discovered what was happening.
> 
> Not sure if this is helpful for OP, but I did land on this thread when I faced this issue initially. My fix was just [blacklisting](https://stackoverflow.com/questions/41813211/how-to-make-react-native-packager-ignore-certain-directories) my test folder from metro packager (so it doesn't auto reload my app on save) which had the json file which json-server was updating.

Ahh, thank you so much! 
I was uploading files within a gitignored folder in /public and ruled out everything in the flow that could've caused the reload, but it never occurred to me it could've been app rebuild ))

**Comment by amkorousagi** [comment] 2021-03-22 07:56
if POST request creating new resource or changing .json file at your local directory,
React reload your page for apply the "changes". (that is reason React is supported real-time debugging)

Solution:
separate .json file  from your react app directory !

**Comment by diegofandino** [comment] 2025-04-25 03:42
> if POST request creating new resource or changing .json file at your local directory,
> 
> React reload your page for apply the "changes". (that is reason React is supported real-time debugging)
> 
> 
> 
> Solution:
> 
> separate .json file  from your react app directory ! 

But how did you call it into the yarn dev or npm start? or do you try to say have json server global and try to have two terminals? 

I try to have json file in same project and use it into the same, but yeah, always this re render app 🫠
