### ISSUE TITLE
Custom Transitioner only animates once when useNativeDriver is true

### ISSUE THREAD

**Issue by Slessi** [react-navigation/react-navigation#3157] opened 2017-12-19 09:46 UTC
### Current Behavior

I am using `Transitioner` to create a custom `StackNavigator`. When using `useNativeDriver: true` in my transition configuration, the animation for the transition only runs the first time. When set to `false`, it works as expected.

> *Note*: Whilst setting it to `false` does fix my problem, I get choppy performance on Android without it, even in production mode.

### Expected Behavior

I expect transition animations to be performed every time I navigate when `useNativeDriver: true`, not just the first time.

### Problem Details

Below is a screen cap of the problem and the code for my `NavigationView`. Note how the first transition is animated, whilst future ones are not (the 'back' navigation should be animated too)

![Screencap of problem](https://i.stack.imgur.com/9BMdd.gif)

```javascript
render() {
    return (
        <Transitioner
            configureTransition={this._configureTransition}
            navigation={this.props.navigation}
            render={this._render}
        />
    );
}

_configureTransition = () => {
    return { useNativeDriver: true };
}

_render = (transitionProps) => {
    return transitionProps.scenes.map(scene => this._renderScene(transitionProps, scene));
}

_renderScene = (transitionProps, scene) => {
    const { layout, position } = transitionProps;
    const { index } = scene;

    const translateX = position.interpolate({
        inputRange: [index - 1, index, index + 1],
        outputRange: [layout.initWidth, 0, 0],
    });

    const animationStyle = {
        position: 'absolute',
        width: '100%',
        height: '100%',
        backgroundColor: '#FFF',
        transform: [{ translateX }],
    };

    const Scene = this.props.router.getComponentForRouteName(scene.route.routeName);

    return (
        <Animated.View key={scene.key} style={animationStyle}>
            <Scene />
        </Animated.View>
    );
}
```

### Attempts

Tried possible workarounds mentioned in [this issue](https://github.com/facebook/react-native/issues/13550), i.e. `backgroundColor: "transparent"` (or other colours) to the animated view or `perspective: 1000`  in the transform array, but had no effect on my problem.

I have [posted](https://stackoverflow.com/questions/47868664/react-navigation-transition-animations-with-usenativedriver-only-run-first-time) on StackOverflow but no responses yet.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.3
| node             | 8.9.2
| yarn      | 1.3.2

Problem recreate-able on

| device         | system version
| ---------------- | -------
| iPhone X (Simulator) | 11.2
| iPhone 6s     | 11.2
| OnePlus One             | 7.1.2

**Comment by Sikter** [comment] 2018-02-03 20:58
Hi Slessi, I'm doing something similar (custom navigator with Transitioner) and I have a very similar issue. So far I think the culprit is the fact that the position property is always 0 if you set the useNativeDriver to true. 
You can see this if you log the transitionProps position value in your renderScene function.
One way around this is to write your animations so that you interpolate progress property.

I still haven't figured out why this happens and would appreciate greatly if someone could point us on how to fix this. Thanks.

**Comment by brentvatne** [comment] 2018-02-07 21:57
hi there! please provide a full example on https://snack.expo.io for us to try this out, thanks!

**Comment by brentvatne** [comment] 2018-02-08 03:21
I was able to reproduce this with the [CustomTransitioner](https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTransitioner.js) example by just adding `useNativeDriver: true` to [_configureTransition](https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTransitioner.js#L59-L64).

**Comment by chrfalch** [comment] 2018-02-10 13:08
I implemented a temporary solution that I'm using in my custom transitioner. When using `useNativeDriver: true` I manually update the position's value in my `onTransitionEnd` callback:

```js
_onTransitionEnd(props) {
    props.position.setValue(props.navigation.state.index);
}
```

**Comment by Slessi** [comment] 2018-02-12 09:41
Nice on @chrfalch, seems to work for me too

**Comment by chrfalch** [comment] 2018-02-13 07:55
I've later added the following sanity check:

```js
_onTransitionEnd(props) {
  if(this._configureTransition().useNativeDriver)
      props.position.setValue(props.navigation.state.index);
}
```

**Comment by janmarsicek** [comment] 2018-02-22 16:06
Hey all,

I encountered a similar problem that occurs when setting `useNativeDriver: true`. Solved by registering a listener to `transitionProps.position `

```
this.position.addListener(() => {});
```

Remember to remove the listener on unmount.

**Comment by satya164** [comment] 2020-01-04 00:17
Closing since `Transitioner` has been removed in lastest react-navigation-stack.

**Closed by satya164** 2020-01-04 00:17 UTC
Labels: bug, component: Stack, component: Transitioner
