### ISSUE TITLE
Screen not changing after navigation iOS 

### ISSUE THREAD

**Issue by mike-niemand** [react-navigation/react-navigation#6451] opened 2019-11-13 19:40 UTC
I've been using this library for sometime and have apps that have been using it for over a year. Today I got a report that it doesn't switch from the loading screen to a drawer intermittently on iOS. I set about investigating and found that this is true however I can't understand why.

Setup as follows:

Loader:

Plain screen that loads some data. Once loaded it switches to the Drawer:

    setLoaded() {
        this.props.navigation.navigate('Drawer')
    }

    render() {
        return <Loader setLoaded={this.setLoaded} />
    }

Drawer: 

Standard drawer with multiple screens. When rendered I console.log('Drawer Rendered')

App Container:

    const AppNavigator = createStackNavigator({
        Loading: { screen: Loading },
        Drawer: { screen: DrawerLayout }
    }, {
        headerMode: 'none'
    });

    const AppContainer = createAppContainer(AppNavigator);

    class App extends React.Component {
        render() {
            return (
                <Provider store={Store}>
                    <AppContainer />
                </Provider>
            );
        }
    }

Now the weird bit is that it does log the 'Drawer Rendered' in the Drawer screen but it never shows it. So it is navigating but the 'Loader' screen is always shown.

I have tried a switch navigator and even rewritten the Drawer but nothing helps. It is iOS only and it is intermittent.

Am I missing something simple?

**Comment by romit07** [comment] 2019-11-13 21:12
I am having similar issue on ios, getting a grey screen

**Comment by infostreams** [comment] 2019-11-14 10:30
I had this problem as well - it turns out I was manually starting 'react-native-screens' (version 2.0.0-alpha.6) with 'enableScreens()' but that's no longer necessary now that screens is included with react-navigation. In fact, it was causing this problem. So, I removed the following code

```js
import { enableScreens } from 'react-native-screens'

// improve performance of react navigation
enableScreens()
```

from my code, and then my screens started rendering again 🎉

**Comment by mike-niemand** [comment] 2019-11-14 14:51
Hmmm. I'm no using react-native-screens. I can confirm this is an issue as I'm getting more reports of it but intermittent.

**Comment by mike-niemand** [comment] 2019-11-14 16:20
OK. My issue is somewhere else and has nothing to do with react-navigation. I can successfully navigate to a blank page.

**Comment by peterkuiper** [comment] 2019-11-22 13:22
> I had this problem as well - it turns out I was manually starting 'react-native-screens' (version 2.0.0-alpha.6) with 'enableScreens()' but that's no longer necessary now that screens is included with react-navigation. In fact, it was causing this problem. So, I removed the following code
> 
> ```js
> import { enableScreens } from 'react-native-screens'
> 
> // improve performance of react navigation
> enableScreens()
> ```
> 
> from my code, and then my screens started rendering again 🎉

Do you have a source for that? Would love to read about this.

**Comment by satya164** [comment] 2019-11-22 13:28
> but that's no longer necessary now that screens is included with react-navigation

You still need to call `enableScreens()` manually if you want to enable it.

**Comment by otaviogaiao** [comment] 2019-12-08 23:56
facing the same issue when trying to change route in a switch navigator. Sometimes it works, sometimes it doesn't. No error is thrown.

**Comment by otaviogaiao** [comment] 2019-12-09 01:40
> OK. My issue is somewhere else and has nothing to do with react-navigation. I can successfully navigate to a blank page.

What was your issue? I'm facing the same problem, and I don't know where else to look

**Comment by tijunoi** [comment] 2020-02-04 09:51
Having an issue where I'm navigating from a Screen A inside a Stack to Screen B inside the same stack. When react-native-screens is enabled, if navigating to B before A is fully rendered and visible, when navigating back to A the screen will be blank. The header shows, though.
When react-native-screens is disabled it works.
I use the `didFocus` navigation event on Screen A to navigate to Screen B under certain conditions. The problem is `didFocus` subscription is called before the screen's UIViewController is attached to the view hierarchy, so when I navigate, it will never show the screen when I navigate back.

**Comment by WoLewicki** [comment] 2020-04-17 07:34
@tijunoi does the issue still exist in RNScreens 2.5.0 and if so, could you provide a repo/snack with the minimal needed configuration so I could work on it?

**Comment by tijunoi** [comment] 2020-04-17 09:18
@WoLewicki Just updated to 2.5.0. Seems the issue is gone. Don't know why we didn't update earlier. 
Thank you!

**Comment by WoLewicki** [comment] 2020-04-17 09:21
Great! I am closing it then.

**Closed by WoLewicki** 2020-04-17 09:21 UTC
Labels: library:react-native-screens, version-4
