### ISSUE TITLE
isMounted(...) is deprecated warning

### ISSUE THREAD

**Issue by jsina** [react-navigation/react-navigation#3956] opened 2018-04-11 10:21 UTC
I've get an "isMounted(...) is deprecated in plain javascript react classes" error with this dependencies, I wanna know that is there any problem with react-navigation with with ```"react": "16.3.1",``` or not?
```
  "dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-navigation": "^1.5.11"
  },
```

**Comment by codler** [comment] 2018-04-11 10:53
I get the same warning after upgrading to react native 0.55.2

**Comment by jsina** [comment] 2018-04-11 10:55
@codler I think it's for some changing in new version of react. I've find the link below. but the problem is for react-navigation api, because it's used some deprecated method.
https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b

**Comment by kk412027247** [comment] 2018-04-11 15:50
I also get the same warning, still can't fix it

**Comment by Ayyagaries** [comment] 2018-04-11 15:54
Same here this is what  I see 
![simulator screen shot - iphone 6 - 2018-04-11 at 09 28 22](https://user-images.githubusercontent.com/32522186/38628328-b743ad82-3d76-11e8-94c9-f7d608cab198.png)

**Comment by matgsan** [comment] 2018-04-12 01:02
Same problem here

**Comment by kk412027247** [comment] 2018-04-12 01:44
I add this code to index.js, so that i can ignore this warnning.
```
import { AppRegistry, YellowBox } from 'react-native';
YellowBox.ignoreWarnings(['Warning: isMounted(...) is deprecated', 'Module RCTImageLoader']);
```

**Comment by hhw3KevinHou** [comment] 2018-04-12 02:14
I got this too, and searched whole react-navigation in node_modules did not find 'isMounted()'.   Weird.

**Comment by Rah1x** [comment] 2018-04-12 05:27
@hhw3KevinHou 
![image](https://user-images.githubusercontent.com/841857/38657892-f0230f68-3e65-11e8-90c4-aadb2640a56d.png)

**Comment by Rah1x** [comment] 2018-04-12 05:30
If you look at this entry, it was indicative enough that its going away since 2015!!. and here we are in 2018 still using it:
https://github.com/moreartyjs/moreartyjs/issues/84

**Comment by hhw3KevinHou** [comment] 2018-04-12 05:56
@Rah1x    looks like isMounted() is not in react-navigation directory.

**Comment by Rah1x** [comment] 2018-04-12 06:03
@hhw3KevinHou 
true, however this issue only came just right now as I updated react-navigation of a fine app

**Comment by derekbar90** [comment] 2018-04-12 06:14
Can confirm this issue as well.

**Comment by PanRada** [comment] 2018-04-12 11:44
have same happend on new app

**Comment by OkancanCosar** [comment] 2018-04-12 16:26
+1

**Comment by allanleonardjr** [comment] 2018-04-12 16:47
Same issue here. I followed the instructions offered by 






@kk412027247

**Comment by mechanizzed** [comment] 2018-04-13 00:44
Same issue here

`"react": "16.3.1",  
  "react-native": "0.55.2",`

**Comment by MahbbRah** [comment] 2018-04-13 02:47
Same issue....

`
"react": "16.3.1",
"react-native": "0.55.2",
`

**Comment by capozzid** [comment] 2018-04-13 12:25
Same here,

`"react": "16.3.1", "react-native": "0.55.2",`

**Comment by mateoguzmana** [comment] 2018-04-13 15:31
Same issue here
`"react": "^16.2.0",
    "react-native": "^0.55.2"`

**Comment by brendancboyle** [comment] 2018-04-13 22:52
Can confirm this is either a bug with react-navigation, or react-navigation precipitates this bug in one of its dependencies. I created a new project and added steps to reproduction: https://github.com/brendancboyle/react-navigation-bug-3956

**Comment by titusRalali** [comment] 2018-04-14 10:30
same here `"react-native": "0.55.2",
    "react-navigation": "^1.5.11",`

**Comment by TitusEfferian** [comment] 2018-04-14 10:31
same here `"react-native": "0.55.2",
    "react-navigation": "^1.5.11",`

**Comment by charleycesar** [comment] 2018-04-14 22:28
same here "react-native": "0.55.2"

**Comment by HambaTuhan** [comment] 2018-04-15 05:14
same here "react-native": "0.55.2"

**Comment by benoist** [comment] 2018-04-15 08:45
https://github.com/react-navigation/react-navigation/blob/master/src/createNavigationContainer.js#L81 could this be the culprit of the warning?

**Comment by AandersonL** [comment] 2018-04-15 15:39
same here "react-native": "0.55.2"

**Comment by asafari72** [comment] 2018-04-15 19:51
how to fix this?
i've update component with `npm install `
my dependencies is :
```
{
"react": "^16.3.1",
    "react-native": "^0.55.2",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.11"
}
```

**Comment by sequencer08** [comment] 2018-04-16 06:56
I have the same issue. Any fix for this?

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.11.1
  Yarn: Not Found
  npm: 3.10.10
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: ^0.55.2 => 0.55.2

**Comment by RomanISWG** [comment] 2018-04-16 13:07
Same issue here. 
RN 0.55.2, 
React 16.3.1, 
React Navigation 1.5.11

**Comment by TheGreatAndrew** [comment] 2018-04-16 20:42
wow just in 6 days and there are that much people having same issues. 
Btw, same issue here.

**Comment by brentvatne** [comment] 2018-04-16 20:43
hello! I am on vacation and this is not an urgent issue @TheGreatAndrew - it is a warning that you can happily ignore or filter out from the yellowbox. I can address it when I'm back next week, or someone else can do it before then

**Comment by TheGreatAndrew** [comment] 2018-04-16 20:45
naw, i did not complain, just feeling suprise. Really great library you have it there.

**Comment by brentvatne** [comment] 2018-04-16 20:50
:)

**Comment by feroce92** [comment] 2018-04-17 00:48
~ node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js
3518 line change

**Comment by zhaiduo** [comment] 2018-04-17 02:54
When I put drawerNavigation in tabNavigation, same YellowBox alert. 
RN 0.55.2,
React 16.3.1,
React Navigation 1.5.8

**Comment by bingfeng1225** [comment] 2018-04-17 08:58
same here 
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-native-root-toast": "^3.0.1",
    "react-navigation": "^1.5.11"

**Comment by TPXP** [comment] 2018-04-17 09:35
Guys I think the maintainers have enough data about this bug, could you stop posting "me too" comments which generates tons of notifications ? If you have the same problem, just put a :+1: to the first comment and subscribe to notifications :wink:

**Comment by brentvatne** [comment] 2018-05-01 00:31
react-navigation does not use `isMounted()`, this is coming from somewhere inside react-native itself

**Closed by brentvatne** 2018-05-01 00:31 UTC
