### ISSUE TITLE
animation of navigation exist a small stick movement from bottom to top when set height of  headerStyle

### ISSUE THREAD

**Issue by iloveyumiforever** [react-navigation/react-navigation#4639] opened 2018-07-04 08:45 UTC
### Current Behavior
set hight of headerStyle
```
navigationOptions = ({ navigation }) => {

return({
      headerStyle: {
        backgroundColor: themeColor,
        height: HEIGHT,
        paddingBottom: PADDING
      }
...
}
```
Its behavior like this below video, the animation of navigation act like existing a small diff from bottom to top in a moment
https://youtu.be/sYREjBp5x7U

### Expected Behavior

Expect like this below video, act fluently, actually if I didn't set height of headerStyle, the animation of navigation act fluently
https://youtu.be/UkcU0LnCsis

### How to reproduce

set height of headerStyle

### Your Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: 1.7.0
  npm: 6.1.0
  react-navigation: ^2.3.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by brentvatne** [comment] 2018-07-05 22:39
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please post a link to a snack that reproduces this and i'll be happy to investigate.

**Comment by eriveltonelias** [comment] 2018-08-31 14:06
Hi! 

as @brentvatne said, we require that you provide a runnable example. I'll close this, but you still need help, please create a new issue.

**Closed by eriveltonelias** 2018-08-31 14:06 UTC
Labels: needs repro
