### ISSUE TITLE
navigation.navigate does not navigate if called instantly with useEffect

### ISSUE THREAD

**Issue by RRaideRR** [react-navigation/react-navigation#10803] opened 2022-08-30 16:18 UTC
### Current behavior

When standing on ScreenA (red screen), I cannot instantly navigate to ScreenB (blue screen). I fire the command `navigation.navigate('ScreenB')` but nothing happens. If I wait for a ms (e.g. with `setTimeout`), everything works fine.

This problem occurs 
- sometimes on the provided Snack 
- on my local machine testing with the iOS simulator
- on my local machine testing with my Android simulator

When using fastRefresh it works after the refresh.

https://user-images.githubusercontent.com/3411292/187486494-7f4e2aec-c19d-4f08-8f94-efbd2d521e4e.mov

```
import React, { useEffect } from 'react';
import {  View,  } from 'react-native';
import { useNavigation } from '@react-navigation/native';

export default function ScreenA() {
  const navigation = useNavigation();
  useEffect(() => {
    navigation.navigate('ScreenB')
  }, []);


    return (
            <View style={{flex: 1, backgroundColor: 'red'}} />
    );
}
```

### Expected behavior

If I call `navigation.navigate('ScreenB')`, I expected the navigation to take place.

### Reproduction

https://snack.expo.dev/@raider/navigation-issue

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.10
| @react-navigation/stack                |^6.2.1
| react-native-safe-area-context         |4.2.4
| react-native-screens                   |~3.11.1
| react-native-gesture-handler           |~2.2.1
| react-native                           |0.68.2
| expo                                   |45

**Comment by RRaideRR** [comment] 2022-08-30 16:29
Yes. However, on my expo-dev-client I achieve that (in my opinion wrong behavior) 100% of the time. In Expo snack it occurs rarely. 

Is there a certain time limit that I need to wait until I can navigate?

**Comment by raajnadar** [comment] 2022-08-30 16:37
Why do you even need to do that? What is the use case? Why quickly navigate to another without even viewing the previous?

**Comment by RRaideRR** [comment] 2022-08-30 17:44
That's an excellent question. 

The use case in the production app is that ScreenB is actually a modal that is on top of ScreenA (so the user should still see something from ScreenA).

**Comment by raajnadar** [comment] 2022-08-30 20:03
Why not use this?

https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator

**Comment by RRaideRR** [comment] 2022-08-30 20:40
Hi and thanks for your help so far. I'm not exactly seeing how this is going to help me :-(. 

ScreenA and ScreenB are located in the same StackNavigator. Even if screen B would be in a nested navigator, I don't understand how the navigation to a nested navigator would help me then. Would you suggest that ScreenA still triggers the "nested" navigation?

**Comment by raajnadar** [comment] 2022-09-03 11:44
As you have custom navigation requirements & none of the built-in APIs fit in your structure you need to use this API https://reactnavigation.org/docs/navigation-prop/#advanced-api-reference

More info on how to create the navigation state https://reactnavigation.org/docs/navigation-state/

Create your navigation state & dispatch it

I am closing this if you need to discuss more it is better to create a discussion topic and keep this only for issues only.

**Closed by raajnadar** 2022-09-03 11:44 UTC
Labels: bug, platform:android, platform:ios, repro provided

**Comment by raajnadar** [comment] 2022-09-05 14:03
You are expecting to navigate to a screen with a sibling screen in its history so it is a custom requirement

**Comment by johanblumenberg** [comment] 2022-10-04 17:46
Hi @raajnadar

I've ran into the exact same issue, and there are a few things in your explanation that I don't understand.

How can it be a custom navigation requirement to navigate between sibling screens?
Looking at the reproduction that @RRaideRR provided, it looks a lot like the first example in the documentation: https://reactnavigation.org/docs/hello-react-navigation

Here Screen A is the "Home" screen and Screen B is the "Settings" screen. They are both sibling screens in the root navigator. The next part of the documetnation is about navigation between screens, and it is explained how you can navigate from "Home" to "Settings", keeping "Home" in the history so you are able to press back and you are back to the "Home" screen.

How is this different from the example that @RRaideRR describes?

The other thing that I don't understand is if this is a custom navigation requirement, how come it works if you do the navigation from a button click or even from a react effect if you do it in a timeout, the only time it is not working is when you do it directly in the effect?

**Comment by raajnadar** [comment] 2022-10-04 18:23
You didn’t understand `navigator.navigate()` is used to navigate from one screen to another, if you pass a screen as param it will navigate to its nested screen, not the sibling.

If you want the sibling screen in the history,

1. You need to do two `navigator.navigate()` manually like button press

or

2. Create your own state and dispatch once which you cannot do with `navigator.navigate()` API as it can only navigate to a screen or nested screen, not a sibling

If you are in the root you can use the reset API

https://reactnavigation.org/docs/navigation-prop/#reset

Check this StackOverflow question https://stackoverflow.com/questions/73791870/how-to-nested-navigate-between-bottom-tabs-in-react-navigation-6

**Comment by johanblumenberg** [comment] 2022-10-04 20:07
> You didn’t understand navigator.navigate() is used to navigate from one screen to another, if you pass a screen as param it will navigate to its nested screen, not the sibling.

If I understand you correctly, what you are saying is that the first examle in the documentation is wrong? Because it is trying to navigate between two sibling screens, and according to you that is not how it works.

https://reactnavigation.org/docs/hello-react-navigation/#configuring-the-navigator and https://reactnavigation.org/docs/navigating#navigating-to-a-new-screen

> Check this StackOverflow question https://stackoverflow.com/questions/73791870/how-to-nested-navigate-between-bottom-tabs-in-react-navigation-6

This question is about something different. It involves a more complicated setup where you have two screens with nested navigators, and you want to navigate from one screen to one of the nested screens in the other screen. So to switch to the sibling screen and a nested screen within that, I can see that you need to use `reset` or some more advanced navigation.

The reproducible example https://snack.expo.dev/@raider/navigation-issue is much simpler. It only contains two screens in a single navigator.

**Comment by raajnadar** [comment] 2022-10-04 20:37
Check my demo to understand how to handle this scenario, if you read my comments I told a similar approach https://snack.expo.dev/@raajnadar/stack-reset-to-navigate-to-the-sibling-screen

> If I understand you correctly, what you are saying is that the first examle in the documentation is wrong? Because it is trying to navigate between two sibling screens, and according to you that is not how it works.

All the examples are correct, in the repro OP wants to navigate programmatically in `useEffect` if you read the comments they can navigate with a slight delay

My solution is to fire one navigation action and open the main screen next its sibling screen instead of firing a navigation action manually and then running another in `useEffect`

> The reproducible example https://snack.expo.dev/@raider/navigation-issue is much simpler. It only contains two screens in a single navigator.

You can still use `.reset` it is not about complexity it is about what an API is designed to do, you can navigate to the sibling screen with `navigation.navigate` but you need to fire it twice, let that be manually on button press or `useEffect`

**Comment by johanblumenberg** [comment] 2022-10-04 21:26
ok, now I understand what you mean.

When you are saying that the navigation in question is custom navigation requirement, you are not talking about the navigation from Screen A to its sibling screen Screen B. You are taling about the combined operation of navingating from a clean state to the state where both Screen A and Screen B are visible.
You are not saying that the solution is to change the call to `.navigate()` in the react effect to a call to `.reset()`, you are saying that the solution is to replace *both* the default navigation to Screen A and the navigation to Screen B.

**Comment by johanblumenberg** [comment] 2022-10-04 21:29
> You need to do two navigator.navigate() manually like button press

I think that this is what we have tried, except that when the second `navigator.navigate()` is within a react effect then it doesn't work.

**Comment by johanblumenberg** [comment] 2022-10-04 21:37
So it would probably work to use a call to `.reset()` to add both Screen A and Screen B in one command.

However, if Screen B is a modal to be shown only under a certain condition, it requires that all code that is navigating to Screen A also knows about this condition so it can prepare the correct reset command.

It would be a lot easier to be able to easily navigate within a react effect. Then I could encapsulate the logic within Screen A.

**Comment by raajnadar** [comment] 2022-10-05 10:30
One reason it does not work with `useEffect` might be the screen is still not mounted and available to navigate, as the OP added a small delay to solve it.

> However, if Screen B is a modal to be shown only under a certain condition, it requires that all code that is navigating to Screen A also knows about this condition so it can prepare the correct reset command.

If you have some conditions to check it will surely take some time to execute till that time the screen must be mounted, if you want a more performant stack nav you can use https://reactnavigation.org/docs/native-stack-navigator/

> It would be a lot easier to be able to easily navigate within a react effect. Then I could encapsulate the logic within Screen A.

You can try discussing it for the next major release here https://github.com/react-navigation/react-navigation/discussions/10506 or in the discord channel

**Comment by dallasnorton** [comment] 2023-02-28 02:41
I have read through this thread multiple times and not grasping how to solve my issue which is very similar to the stated problem. 

I have a route that has an optional parameter (`welcome: 'welcome/:inviteCode?',`), if the parameter is present I want to advance them to `acceptInvite`, if not then I want the user to stay on the initial route and continue through the application and onboarding screen process. 

My use case for this situation is accepting invites to my application. If the user is already logged in then skip the sign up steps and take them to the `acceptInvite` screen instead of having them flow through the onboarding experience and then accepting the invite.

Maybe I should not be trying this pattern and there are better patterns to do what I am wanting. Any help would be appreciated.

**Comment by rusty120** [comment] 2023-05-10 16:21
I encountered this issue as well. Similar use case, a user following a deep link with a parameter for a resource which is not found (`user/:userId`). When this happens, I want to simply pop the user back to the home screen. Not ideal, but I was able to get this working like so:

```
  const user = ...  // an object or null if not found
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (user === null) {
      if (notFound) {
        popToTop();
      } else {
        setNotFound(true);
      }
    }
  }, [user, notFound, popToTop]);
```

The other option would be to move the logic to see if `user` exists into the `linking` config. That might've worked as well, but I wanted to keep the logic for finding a user by ID isolated to this screen.

**Comment by nelsonsvo** [comment] 2023-05-24 16:25
Hi had a similar issue,

kind of sucks but added another useEffect to check when the screen mounted and then used this in the subsequent useEffect
`const [mounted, setMounted] = useState(false);
  const { isSignedIn, user } = useUser();

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted && user && user.unsafeMetadata.new === true) {
      navigation.navigate("Onboarding");
    }
  }, [user, mounted]);`

**Comment by ranjitAcelucid** [comment] 2023-09-20 08:38
Hii @raajnadar ,

Have you solve the issue?

Thanks

**Comment by scd8418** [comment] 2024-01-26 21:18
Plus one the the issues as described here. In my case, A modal menu is display. When a selection is made, the code closes the modal, sets a state in the parent screen, and then uses that state in componentDidUpdate() to initiate navigation to another screen.

I'm forced to set a timeout of 500ms before the navigation will work. This is true regardless of which screen I navigate to. With a shorter delay (or no delay) the navigate() call is ignored without an error. Really seems like a bug.

**Comment by eddietex** [comment] 2024-09-11 19:50
I’m encountering the same issue in a slightly different scenario when handling push notifications with deep links. Here’s my flow:

User receives a push notification while the app is closed and opens it.
The app loads, processes the notification, but the user is not authenticated yet. We store the notification payload in global state to handle later.
After authentication, in an authenticated stack navigator, we retrieve the payload in useEffect. If it contains deep link data, we call navigate(...).
At this point, navigation fails (same behavior as OP). Interestingly, adding a 1000ms timeout resolves it, but this feels more like a hack.
I’ve tried isReady() on the navigation ref, but it doesn’t help. Has anyone experienced a similar flow or found a more robust solution besides using arbitrary timeouts? Any guidance would be appreciated!

**Comment by eddietex** [comment] 2024-09-11 20:08
For the record, I achieved similar results to using `setTimeout()`, but by wrapping the navigation call within `InteractionManager.runAfterInteractions()`. This approach feels less "hacky" and more reliable.

**Comment by vhakulinen** [comment] 2024-11-28 03:42
> For the record, I achieved similar results to using `setTimeout()`, but by wrapping the navigation call within `InteractionManager.runAfterInteractions()`. This approach feels less "hacky" and more reliable.

I was able to use the same workaround: postpone navigation in `useEffect` by wrapping it in `runAfterInteractions`.
