### ISSUE TITLE
error message missing important information

### ISSUE THREAD

**Issue by lasthrun** [react-navigation/react-navigation#3228] opened 2018-01-05 10:17 UTC
**Problem**
i have a react native app with redux, and using redux to control the react navigation.
but i have a bad use case that i let the page navigate to itself. it show a odd error, that the navigation object become NULL.
i waste a lot of time to debug it, and i don't get any useful information from the error message.
i prefer error message should show 'do not support navigation to itself' or somethings like this.

**Comment by kelset** [comment] 2018-01-05 11:41
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-05 11:41 UTC
