### ISSUE TITLE
RectButton & TouchableOpacity (from react-native-gesture-handler) are pressable through overlay in a transparent modal.

### ISSUE THREAD

**Issue by Kailash23** [react-navigation/react-navigation#8706] opened 2020-08-11 19:21 UTC
**Current Behavior**
-  I am using a transparent modal in my application [link](https://reactnavigation.org/docs/stack-navigator/#transparent-modals). The button components from `react-native-gesture-handler` are pressable through the overlay. Working fine with the Button components from `react-native`.

**Expected Behavior**

- They should not be pressable through the overlay.

**How to reproduce**

https://snack.expo.io/@kailash23/react-navigation-v5-modal-bug

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.6.1
| react-native                   |
| expo                           | 38.0.0
| node                           |
| npm or yarn                    |

**Comment by Kailash23** [comment] 2020-08-11 19:28
Still the same issue.

**Comment by aquile** [comment] 2020-11-13 11:33
@Kailash23 did you find a solution?

**Comment by Kailash23** [comment] 2020-11-14 06:03
I have replaced RectButton (from react-native-gesture-handler) with Pressable  (from React Native).

**Comment by satya164** [comment] 2020-11-24 13:16
Duplicate of #8515

**Closed by satya164** 2020-11-24 13:16 UTC
Labels: bug, library:react-native-gesture-handler
