### ISSUE TITLE
action generated by getActionForPathAndParams (when using nested TabNavigator within StackNavigator) pushes on Stack, instead of changing Tab [redux]

### ISSUE THREAD

**Issue by faceyspacey** [react-navigation/react-navigation#1508] opened 2017-05-14 19:23 UTC
### Current Behavior
Using the example here:
https://reactnavigation.org/docs/intro/nesting

if you generate an action from `SimpleAppStack.router.getActionForPathAndParams('Home/All')` and then you dispatch that action, `SimpleAppStack.router.getStateForActionOriginal(action, state)` pushes a route onto the Stack, rather than changes the index of the nested TabNavigator. 

An action like this is generated:

```js
routeName: "Home",
type: "Navigation/NAVIGATE",
action: {
  routeName: "All",
   type: "Navigation/NAVIGATE"
}
```

The typical one is this:

```js
action: undefined,
params: undefined,
routeName: "All",
type: "Navigation/NAVIGATE"
```

The resulting state looks like this:
![screen shot 2017-05-14 at 12 28 16 pm](https://cloud.githubusercontent.com/assets/154732/26037087/ebc50df2-38a0-11e7-9259-7aa1bbf4561d.png)
*notice the stack has 2 routes pushed, when it should have 1. In addition it has the TabRouter state nested a second time within that 2nd item on the stack. It does however have the `index` correctly set in that TabRouter state, and so the correct tab appears, but there is a `back` button in the top left since the StackNavigator first pushed it.*

This sorta stuff needs to work correctly for things like `Linking` to work. It seems there is still a lot of things to workout with using paths. I've noticed a few other such issues. Basically using paths as input isn't guaranteed to result in the same state as when you do the reverse and request the path as output via `getPathAndParamsForState`.

### Expected Behavior
The tab changes from `Recent` to `All`. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  44
| node             |  v7.7.2
| npm or yarn      | Yarn

**Comment by faceyspacey** [comment] 2017-05-14 20:02
My hunch is the following:

The developers figured this at least works for deep-linking (as it does show the correct scene), and it's general enough for nesting all sorts of navigators/routers. But it's still not something any pro product wants to happen. I think the only solution is to build into `getActionForPathAndParams` various cases where it detects the kind of child router nested, and if it detects, for example, it's a `TabRouter`, it then dispatches a flat action, eg:

```js
action: undefined,
params: undefined,
routeName: "All",
type: "Navigation/NAVIGATE"
```

**Comment by faceyspacey** [comment] 2017-05-14 21:35
I've come up with a fix that works for the concrete scenario from the documentation (StackRouter -> TabRouter):

*getStateForAction:*
```js
//...
if (
        action.type === NavigationActions.NAVIGATE &&
        childRouters[action.routeName] !== undefined
      ) {
        const childRouter = childRouters[action.routeName];
        let route;
        if (childRouter) {
          const childAction = action.action ||
            NavigationActions.init({ params: action.params });

          route = {
            params: action.params,
            ...childRouter.getStateForAction(childAction),
            key: _getUuid(),
            routeName: action.routeName,
          };

          const index = state.routes.length - 1 // new!
          route.key = state.routes[index].key // new!
          return StateUtils.replaceAtIndex(state, index, route) //new!
        } else {
          route = {
            params: action.params,
            key: _getUuid(),
            routeName: action.routeName,
          };
        }
        return StateUtils.push(state, route);
      }
```

In addition, the code right there is blatantly incorrect in that it checks for `childRouter` twice. The second `else` assignment to `route` is unnecessary. 

So now, basically my change where I do `StateUtils.replaceAtIndex` instead of `StateUtils.push` needs to be assessed to see if it breaks other use cases. Basically I gotta test whether if DrawerRouter or another StackRouter doesn't jive with as a child router with this change.

**Comment by faceyspacey** [comment] 2017-05-14 22:02
UPDATE:

So the below code only does the replace if the parentRoute stays the same. My hunch and hope is that this can be applied to any type of nested child router. 

```js
const index = state.routes.length - 1
const parentRoute = state.routes[index]

if (action.routeName === parentRoute.routeName 
    && shallowEqual(action.params, parentRoute.params)) {
            route.key = parentRoute.key
            return StateUtils.replaceAtIndex(state, index, route)
}
```

**Comment by faceyspacey** [comment] 2017-05-14 22:16
Here's the PR:

https://github.com/react-community/react-navigation/pull/1515

If anyone else could take a look at it I'd appreciate it, as I'm new to the codebase.

**Comment by ericvicenti** [comment] 2018-02-19 11:01
I think the best fix for this is to make sure that getActionForPathAndPrams returns an idempotent navigate action with a key for the stack, and an inner action for the tabs.

So unfortunately I think that #1515 isn’t the best approach on this, because it may introduce unexpected behavior, and the root cause is probably within getActionForPAthAndParams. 

I hope to come back and fix this soon, and I can guide anybody who wants to help fix it now.

**Comment by brentvatne** [comment] 2018-03-07 00:24
@ericvicenti - I believe that this will be solved by https://github.com/react-navigation/rfcs/pull/25

**Closed** 2018-05-08 01:07 UTC
Labels: bug
