### ISSUE TITLE
Nested stack navigator inside Animated Switch issue on android 

### ISSUE THREAD

**Issue by LydGol90** [react-navigation/react-navigation#7228] opened 2019-11-18 11:51 UTC
I am having an issue with createAnimatedSwitchNavigator in android only (iOS works great). If I have stack navigator nested inside my animated switch navigator, the stack doesn't appear.

Example code to reproduce:

```
const RegistrationStack = createStackNavigator(
  {
    Welcome: WelcomeScreen,
  },
  {
    initialRouteName: 'Welcome'
  },
);


const SwitchNavigator = createAnimatedSwitchNavigator(
  {
    Loading: LoadingScreen,
    Registration: RegistrationStack
  },
  {
    initialRouteName: 'Loading',
    transitionViewStyle: { backgroundColor: 'white' },
    transition: (
      <Transition.Together>
        <Transition.Out
          type="slide-bottom"
          durationMs={400}
          interpolation="easeIn"
        />
        <Transition.In type="slide-bottom" durationMs={500} />
      </Transition.Together>
    ),
  },
);
```

Implementing the code above, I see the LoadingScreen and then I see the transition happen but it then just shows a white screen (which is the transition view). Changing from an animated switch navigator to a normal switch navigator everything works fine. Also if I just have a screen rather than a stack navigator in the switch navigator everything also works fine. Have done some additional debugging and the WelcomeScreen inside the stack is not rendering at all.

For example this works fine:
```
const SwitchNavigator = createAnimatedSwitchNavigator(
  {
    Loading: LoadingScreen,
    Registration: WelcomeScreen
  },
  {
    initialRouteName: 'Loading',
    transitionViewStyle: { backgroundColor: 'white' },
    transition: (
      <Transition.Together>
        <Transition.Out
          type="slide-bottom"
          durationMs={400}
          interpolation="easeIn"
        />
        <Transition.In type="slide-bottom" durationMs={500} />
      </Transition.Together>
    ),
  },
);
```

Was wondering if anyone else was seeing this issue or if I am just implementing something wrong!

Many thanks!

**Comment by WoLewicki** [comment] 2020-04-17 07:38
Hey, can anyone confirm if the issue still exist in the newest versions of packages? And if so, can someone provide a repo/snack with minimal needed configuration to reproduce the issue?

**Comment by satya164** [comment] 2020-04-23 12:33
Closing since you didn't provide a repro. Please open a new issue with repro if you still have problems.

**Closed by satya164** 2020-04-23 12:33 UTC
Labels: library:react-native-screens, needs more info, package:animated-switch, version-4
