### ISSUE TITLE
Blank white screen using react navigation after upgrading react native and expo on deployment

### ISSUE THREAD

**Issue by AhadCove** [react-navigation/react-navigation#3057] opened 2017-11-29 16:33 UTC
Hey,

Sorry if this may be more of an issue with expo, but I didn't have a problem before and it works without react-navigation so I hoped to find help here

## **Environment**
software | version
-- | --
react-navigation | 1.0.0-beta.21
react-native | 0.50.3
node | 8.1.3
yarn | 1.2.1

## **Current Behavior**

I updated my app to the new react native and expo(v23.0.4) and I started having trouble with react navigation. When publishing my app with expo I am only getting a blank white screen.
I tried reverting back to the previous beta 13 version of react-navigation and I still can't get it pass the blank white screen.
The app works perfectly locally, but it's only when I deploy it so my team can use the app where we get the white screen. Also if I deploy it without react-navigation the app works perfectly.

This is happening on IOS, I haven't tested it on Android yet

## **Expected Behavior**

For the app to work as it does locally as it does when deployed.

**Comment by kelset** [comment] 2017-11-29 16:40
Weird issue for sure; thanks for reporting.

Can you create a repo that reproduces the issue in any way?

cc @brentvatne @davepack any idea what could be causing this?

**Comment by AhadCove** [comment] 2017-11-29 16:56
Yes, I will try to reproduce the issue

**Comment by orel91** [comment] 2017-11-29 17:17
I am having the exact same issue except I am using the react-native cli.

**Comment by AhadCove** [comment] 2017-11-29 18:24
So while I was trying to recreate the issue I found where my problem lied. It was actually the module: ```react-native-global-props```
I'm digging into the module to see where and why it's breaking the app now

**Comment by p0d3r** [comment] 2017-12-11 15:27
i am also having the same issue. what was the exact problem? @AhadCove

**Comment by AhadCove** [comment] 2017-12-12 00:37
@p0d3r are you using react-native-global-props?
if so for me it was something wrong with setCustomView.
just don't use it, I dug into the module and couldn't find where the problem lied, so I just didn't use it

**Comment by mightym** [comment] 2017-12-12 00:50
Same issue here. I'm using `react-native-router-flux": "^4.0.0-beta.23",` which is based on react-navigation. Works fine when running through expo, but stop working (white screen) when js debug is on. Or as standalone iOS app.

**Comment by orel91** [comment] 2017-12-12 08:34
In my case, I did some code refactoring in the routing and updated React Native and React Navigation to their latest versions.

**Comment by sachabest** [comment] 2017-12-27 01:57
Having the same issue after the expo v24 upgrade with no `global-props` installed. Anyone else have a solution?

**Comment by fourcolors** [comment] 2017-12-28 01:42
I'm having the same issue here. Using CRNA with react-native `0.50.3` and react `16.2.0`

**Comment by parachute-dev** [comment] 2017-12-29 09:34
@sachabest Did you get a resolution to this? I'm struggling with it too

**Comment by AhadCove** [comment] 2017-12-30 14:19
If you all are using other modules, try to remove them one by one and see if you notice any change. Some of these modules aren't updated correctly. For me it was ```global-props```. Maybe if we find a trend we can get this figured out

**Comment by parachute-dev** [comment] 2017-12-30 14:28
@AhadCove 

I removed the DrawerNavigator on React Navigation and it works as normal now. I'm using the StackNavigator as the base navigation. I wasn't really DrawerNavigator, so this has turned out ok for me.

This was working just fine on a build ~12 days ago, building with Expo with the same code. Renders just fine on iOS simulator, and on iOS with the expo app. Going to a whitescreen when built and in the app store.

**Comment by AhadCove** [comment] 2017-12-30 14:58
@parachute-dev yeah now that you mention it, I do remember at the time when I removed the Drawer navigator it fixed it. But, in my case I needed the drawer, so I put it back and looked for another problem. That's what led me to that module. It may be a combination of the module I was using and the drawer

**Comment by parachute-dev** [comment] 2017-12-30 15:42
what modules are you using just now? We could compare packages?

**Comment by sachabest** [comment] 2017-12-30 17:17
@parachute-dev 'npm i --save uglify-es@3.2.2' and force the version to 3.2.2 (remove the ^) in your package.json. Via https://github.com/facebook/react-native/issues/17348#issuecomment-354520237

**Comment by AhadCove** [comment] 2017-12-30 17:32
For me it was ```"react-native-global-props": "^1.1.3"```

**Comment by quyentran-agilityio** [comment] 2018-01-03 08:12
I got same issue. Any solutions? :(

**Comment by igagen** [comment] 2018-01-03 17:52
Same issue here...

**Comment by igagen** [comment] 2018-01-03 17:55
Should this issue be re-opened?

**Comment by parachute-dev** [comment] 2018-01-03 18:02
Yes, I'd say so...  I'm getting reports of this still happening on my app
in iOS - nothing on android.

[image: Parachute] <http://www.thisisparachute.com/> *David R. Bova *-
*Technical
Director at Parachute*

*Address:* 4 Lansdowne Crescent, Glasgow G20 6NQ
*Tel:* 0141 357 4556 | *Mobile:* 07514 645179
david@thisisparachute.com | http://www.thisisparachute.com
<http://thisisparachute.com/>

[image: Twitter] <http://twitter.com/thisisparachute>[image: Facebook]
<http://www.facebook.com/thisisparachute>[image: Pinterest]
<http://pinterest.com/thisisparachute>
*Confidentiality Note: *This email may contain confidential and/or private
information. If you received this email in error please delete and notify
sender.

**Comment by AhadCove** [comment] 2018-01-03 19:29
@igagen Yeah I think that would be best for now

**Comment by igagen** [comment] 2018-01-03 19:32
Cool, thanks!

**Comment by igagen** [comment] 2018-01-03 19:33
For what it's worth I've tried pinning uglify at uglify-es@3.2.2 and that did not resolve this issue.

**Comment by parachute-dev** [comment] 2018-01-03 19:50
I'm not using drawer navigator anymore and I'm still getting this. I still
think it's something to do with the way the routing is setup because I can
see some screens getting rendered.

Anyone want to share current packages?

Best
David

**Comment by igagen** [comment] 2018-01-03 22:14
software | version
-- | --
react-navigation | 1.0.0-beta.22
react-native | 0.51.0
expo | 24.0.2

**Comment by igagen** [comment] 2018-01-04 05:15
Ok, @parachute-dev I think it is actually uglify-es. I just hadn't cleaned out my old install of it. Updating to 3.2.2 fixed it for me.

**Comment by victorileaf** [comment] 2018-01-04 06:46
Issue is not related to expo i think.

Same issue for me. app works perfectly alright in simulator but shows blank screen (Instead of showing custom tab navigator) 

Issue occurred when i updated my project to 0.51.0 from an old version.

Updating uglify-es to 3.2.2 fixed it for me. npm i --save uglify-es@3.2.2 

Working config
react-navigation | 1.0.0-beta.22
react-native | 0.51.0
uglify-es | 3.2.2

**Comment by kelset** [comment] 2018-01-04 08:57
Since it looks like (again) it's not the repo causing the issue but some other packages, I'm closing this.

**Closed by kelset** 2018-01-04 08:57 UTC
Labels: help wanted, needs more info

**Comment by rajat-ttn** [comment] 2018-05-16 06:14
uglify-es@3.2.2 didn't work for me. I am still facing this problem

my dependencies versions:-

**Environment:**
  OS: macOS Sierra 10.12.6
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 6.0.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

**Packages: (wanted => installed)**
  expo: ^27.0.0 => 27.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz => 0.55.2
  "react-navigation": "^2.0.1" ====> 2.0.1

**Comment by georgiosd** [comment] 2019-01-11 15:13
Why is this closed? We are still having this issue, when the app has been open for a while
