### ISSUE TITLE
TypeError:expected dynamic type 'double',but had type null

### ISSUE THREAD

**Issue by nicolit** [react-navigation/react-navigation#3291] opened 2018-01-17 12:03 UTC
Hi I have a bug, whenever I try to setParams is crashes. screenshot is attached.  Only when the setParams line in componentDidMount is set in comment it works ok.

`export default class ReviewsScreen extends Component { 
  static navigationOptions = props => {
    const { navigation } = props;
    const { params = {} } = navigation.state;
    let _headerRight = DishReviewsScreen.shareButton(navigation);
    if (params.isSharing) {
      _headerRight = <ActivityIndicator />;
    }
    return {
      title: 'Reviews',
      headerTitleStyle: { color: lightTheme.headerTitle },
      headerStyle: AppStyles.navigationHeaderStyle,
      headerLeft: DishReviewsScreen.backButton(navigation),
      headerTintColor: lightTheme.headerBackButton,
      headerRight: _headerRight,
    };
  };

  static shareButton = navigation => {
    const { params = {} } = navigation.state;
    return (
      <TouchableOpacity
        style={{ marginRight: 10 }}
        onPress={() => {
          params.shareItem ? params.shareItem : () => null;
        }}>
            <Icon
      name={'md-share'}
      type={'ionicon'}
      color={'black'}
      size={24}
      iconStyle={{marginRight: 8}}
    />
      </TouchableOpacity>
    );
  };

  static backButton = navigation => {
    const { key } = navigation.state;
    return (
      <TouchableOpacity
        style={{ marginLeft: 10 }}
        onPress={() => {
          navigation.dispatch(NavigationActions.back({ key }));
        }}>
            <Icon
      name={'md-arrow-back'}
      type={'ionicon'}
      size={24}
      color={'black'}
      iconStyle={{marginLeft: 8}}
    />
      </TouchableOpacity>
    );
  };

constructor(props) {
    super(props);
this.onBackPress = this.onBackPress.bind(this);
this._shareItem = this._shareItem.bind(this);
  }
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
    **this.props.navigation.setParams({ shareItem: this._shareItem }); // ----> this does not work**
  }
  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }
  onBackPress() {
    const { navigation } = this.props;
    const navState = navigation.state;
    if (navState && navState.key) {
      let { key } = navState;
      navigation.dispatch(NavigationActions.back({ key }));
      //navigation.goBack( key );
      return true;
    } else {
      return false;
    }
  }
  _shareItem = () => {
    // Update state, show ActivityIndicator
    this.props.navigation.setParams({ isSharing: true });
    const { itemReducer } = this.props;
    const { id, icon } = itemReducer;
    shareItem(id, icon).then(() => {
      this.props.navigation.setParams({ isSharing: false });
    });
  };
render(){
return (
      <View style={{ backgroundColor: 'transparent' }}></View>);
}
}
`
### Current Behavior:
when this screen is rendered and mounted, it crashes.
### Expected Behavior
the share button was suppose to be attched to the "shareItem" param in componentDidMount method.
I made the same way as the example on the official site: https://reactnavigation.org/docs/intro/headers

### Your Environment- from package.json
    "react": "^16.2.0",
    "react-native": "^0.51.0",
    "react-navigation": "^1.0.0-beta.27",
    "react-redux": "^5.0.6",
    "redux": "^3.6.0",
    "node": "v6.11.2",
    "npm": "5.6.0",
I'm using Mint OS (Linux), Vscode IDE to debug remotely, running on OnePlus5 (Android 8).
![photo5981241705350933419](https://user-images.githubusercontent.com/10170174/35042004-8694cabe-fb8f-11e7-94fc-0d77271a824f.jpg)

**Comment by kelset** [comment] 2018-01-17 12:11
Duplicate of https://github.com/react-navigation/react-navigation/issues/2387

**Closed by kelset** 2018-01-17 12:11 UTC
