### ISSUE TITLE
Nested TabNavigator doesn't render tab on first click

### ISSUE THREAD

**Issue by sbleon** [react-navigation/react-navigation#3665] opened 2018-03-05 18:38 UTC
(Sorry for submitting this here even if it happens only with redux integration on. I'm able to fix the problem by tweaking `ResourceSavingSceneView`. I don't know if there's a way to fix the problem in the `react-navigation-redux-helpers` package.) PR will come shortly, to this repo.

#### Preconditions:
- a TabNavigator is nested under a SwitchNavigator
- The TabNavigator is the default view
- Redux integration is on

#### Behavior
When I click on an inactive tab for the first time, it does not render (i.e. the `render()` method of the screen is not called). Subsequent navigations to that tab work correctly.

![issue](https://user-images.githubusercontent.com/198711/36992823-1a25742c-207a-11e8-8ad0-aeb48db7716c.gif)

My example code is at https://github.com/sbleon/react-navigation-test-case .

### Expected Behavior

- The inactive tab should become active and render correctly the first time I click it.

### How to reproduce

My example code is at https://github.com/sbleon/react-navigation-test-case . The simple repro instructions are in the README.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.52.0
| node             | 9.6.1
| npm or yarn      | yarn 1.5.1

**Comment by brentvatne** [comment] 2018-03-05 18:55
duplicate of the following:

https://github.com/react-navigation/react-navigation-redux-helpers/issues/10
https://github.com/react-navigation/react-navigation-redux-helpers/issues/7

if the solutions there don't work for you then please re-create the issue on that repo. this isn't a bug in resourcesavingsceneview, the tabnavigator doesn't receive the events that it expects and so it doesn't know that the second tab has been focused.

**Closed by brentvatne** 2018-03-05 18:55 UTC

**Comment by sbleon** [comment] 2018-03-05 19:01
Thanks so much, @brentvatne ! I should have looked over in that repo for this issue. I'll try to submit a PR to update the ReduxExample app if there isn't already one.

**Comment by brentvatne** [comment] 2018-03-06 00:26
thanks! :)
