### ISSUE TITLE
Reset Action is not working inside componentDidMount Function

### ISSUE THREAD

**Issue by dsouzaedison** [react-navigation/react-navigation#3220] opened 2018-01-04 12:21 UTC
My task is to verify if a cookie is valid on page load. If the validation fails, redirect user to Login page. I am throwing error when the validation fails. But when the reset action is performed, the page doesn't seem to be redirected. 

```
componentDidMount() {
        const cookie = this.props.screenProps.cookie;

        return fetch(AUTH_URL, {
            method: 'GET',
            headers: {
                "Cookie": cookie
            }
        })
            .then((response) =>  {
            if(response.headers.map['content-type']['0'] === 'text/html; charset=utf-8') //HTML response represents auth failure in my case
                throw new Error;
            else return response.json()
            })
            .then((responseJson) => {
                //SOME LOGIC
                return responseJson;
            })
            .catch((error) => {
                // console.error(error);
                const resetAction = NavigationActions.reset({
                    index: 0,
                    type: 'Reset',
                    actions: [
                        NavigationActions.navigate({routeName: 'Login'})
                    ]
                })
                this.props.navigation.dispatch(resetAction)
            });
    }
```

I tried adding breakpoints, control enters catch block, but no redirection is seen on screen.

**Comment by kelset** [comment] 2018-01-04 12:52
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-04 12:52 UTC
