### ISSUE TITLE
Scroll to top function for tabBarOnPress (using class method in navigationOptions)

### ISSUE THREAD

**Issue by carsonwah** [react-navigation/react-navigation#2955] opened 2017-11-10 08:56 UTC
I am trying to implement "scroll to top" functionality for a tab, just like any news feed. However after some research, I still cannot find any satisfying implementatioin for this. 

### Current Behavior
```javascript
import { store as ReduxStore } from 'somewhere';

const AppNavigator = TabNavigator({
  TabA: { screen: StackNavigatorA },
  TabB: {
    screen: StackNavigatorB,
    navigationOptions: ({ navigation }) => ({
      tabBarOnPress: (scene, jumpToIndex) => {
        const { route, index, focused } = scene;
        if (route.index === 0) {
          ReduxStore.dispatch(fetchSomething());
          // HOW: Sroll to top here???
        }
        jumpToIndex(1);
      }
    })
  }
});
```

I am using redux to dispatch a ajax call. But how to scroll to top after that? Suppose I have a ScrollView in mainScreen of StackNavigatorB, but we don't have any access to class methods there. 

I have thought of passing class methods by `setParams`.

```javascript
componentWillMount() {
  this.props.navigation.setParams({
    scrollToTop: this._scrollToTop,
  });
}
```

But as far as I know, `({ navigation })` in `navigationOptions` of `TabNavigator` and `StackNavigator` are different, so we cannot use `setParam` to pass class methods from components to `TabNavigator`. Only `StackNavigator` can capture the methods.

I have seen other related issues but none provides a way to accomplish this.

https://github.com/react-community/react-navigation/issues/210
https://github.com/react-community/react-navigation/issues/314
https://github.com/react-community/react-navigation/issues/991
https://github.com/react-community/react-navigation/pull/1335

### Expected Behavior
Provide a way to access class methods of components in "`TabNavigator` -> `StackNavigator` 
 -> `Component`" structure.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.47, with expo sdk 20.0.0
| node             | v6.11.0
| yarn      | 1.0.2

**Comment by carsonwah** [comment] 2017-11-10 09:26
I have found the solution. Actually after `setParams`, the params will sit inside route.routes[n].params._yourMethod.

Inside component:

```
componentWillMount() {
  this.props.navigation.setParams({
    scrollToTop: this._scrollToTop,
  });
}

_scrollToTop = () => {
  if (!!this.orderList) {
    this.orderList.scrollToOffset({ offset: 0, animated: true });
  }
}
```

In navigator:
```
tabBarOnPress: (scene, jumpToIndex) => {
  const { route, index, focused } = scene;

  if (route.index === 0) { // inside 1st screen of stacknavigator
    ReduxStore.dispatch(someAction());

    // Scroll to top
    const navigationInRoute = route.routes[0];
    if (!!navigationInRoute && !!navigationInRoute.params && !!navigationInRoute.params.scrollToTop) {
      navigationInRoute.params.scrollToTop();
    }

  }
  jumpToIndex(1); // Exit
},
```

Just remember to check carefully because `setParams` is async function. Also, `params` will not be available on the 1st press if you have set `lazy` option for `TabNavigator`, because the component is not even mounted at that time.

Hope this can help anyone trying to accomplish this functionality.

**Comment by kelset** [comment] 2017-11-10 10:05
Hey thanks for the comments and suggestion.
I think this could be turned into a documentation PR, would love to see that (or an example, or a Snack) in the docs or the readme.

**Comment by carsonwah** [comment] 2017-11-10 14:22
@kelset Thanks for looking into this. I don't know where I should put it in the documentation. I have written a [Snack](https://snack.expo.io/HJp9mEQkG) as a minimum example. Please feel free to use it wherever you see fit.

**Comment by eballeste** [comment] 2018-01-05 00:19
Thank you so much carsonwah for pointing me in the right direction!

**Comment by eballeste** [comment] 2018-01-06 02:55
Although I noticed that when you use setParams like this to access the methods of a screen, using the reset action causes all of the screens to mount/unmount indefinitely. Have you experienced this yourself @carsonwah???

**Comment by eballeste** [comment] 2018-01-11 04:02
this fixes it:
```javascript
componentWillMount() {
  InteractionManager.runAfterInteractions(() => {
      this.props.navigation.setParams({
      scrollToTop: this._scrollToTop,
    });
  })
}
```

**Comment by mmckinley8** [comment] 2018-01-25 02:05
@carsonwah 's solution should be the accepted method. Thank you!

**Comment by carsonwah** [comment] 2018-02-06 10:29
@eballeste Sorry, I missed your comment. Yes, I have! I had also opened an issue about this.

https://github.com/react-navigation/react-navigation/issues/2421

Seems still no solution yet.

**Comment by brentvatne** [comment] 2018-02-07 20:39
hello! yeah this is silly, you should get this behavior for free out of the box. i plan to work on this soon

**Comment by carsonwah** [comment] 2018-02-08 05:30
@brentvatne Thanks for looking into this. Yeah I think so. If there are several ScrollView in different pages, the code will become very complicated.

When you work on this, please also consider the very common “back to 1st screen in the stack” behaviour.

**Comment by danlin604** [comment] 2018-02-13 23:02
Is this option working as of 1.0.3?

`tabBarOnPress: (scene, jumpToIndex) => {
  console.log('Tab is pressed!') 
},`

I am using it for my `HomeScreen` Component inside a `static navigationOptions`. The expected outcome is that console.log is ran, but nothing happens. Eventually, I want to scroll back to the top of the flatlist on tab press (pressing on the tab icon). I crawled through the solutions and issues, but I am unable to get tabBarOnPress to respond.

**Comment by carsonwah** [comment] 2018-02-14 18:24
@danlin604 It should work in v1.0.3. Could you share more related code of your implementation?

If you are using `TabNav -> Screen` instead of `TabNav -> StackNav -> Screen`, I guess maybe your `navigationOptions` is somehow overrided. You may also consider this and test a bit more.

**Comment by danlin604** [comment] 2018-02-14 18:40
I managed to find a workaround without `tabBarOnPress`. We are using a `tabBarComponent` and I can `setParam` a function ref in the child component for the parent's `onPress`.

```
const MainNav = TabNavigator({
      ...
    }, {
      tabBarComponent: ProtrudingTabBar,
      ...
      navigationOptions: ({ navigation }) => ({
        tabBarOnPress: (scene, jumpToIndex) => {
           console.log('Tab is pressed!')
        }
    })
})
```

However, I am still confused as to why tabBarOnPress is unresponsive.

**Comment by brentvatne** [comment] 2018-02-23 23:08
moving this to https://github.com/react-navigation/react-navigation/issues/3588

**Closed by brentvatne** 2018-02-23 23:08 UTC
Labels: component: Stack, component: Tabs, critical

**Comment by marceloHashzen** [comment] 2018-03-14 14:54
I tweaked the method a little to work with newer versions of react navigation (not sure if this was the cause of the errors, but anyway...):

I've added a check to see if the previous scene was the same of the actual scene, and then scroll to top.

```
const tabBarOnPress = ({ scene, jumpToIndex, previousScene }) => {
  const { route, index } = scene;

  if (route.key === previousScene.key) {
    const stackNavigation = route.routes[0];
    if (!!stackNavigation && !!stackNavigation.params && !!stackNavigation.params.scrollToTop) {
      stackNavigation.params.scrollToTop();
    }
  }

  jumpToIndex(index);
};
```

**Comment by MaheshNandam** [comment] 2018-04-25 07:01
Guys, This is perfectly working for me on both Android and ios,

```
static navigationOptions = ({ navigation }) => {
       return {
            tabBarOnPress: ({previousScene, scene, jumpToIndex}) => {
                const { route, index, focused} = scene;
                
                if(focused){
                    navigation.state.params.scrollToTop()
                }
                jumpToIndex(0)
            }
        }
 };


componentDidMount(){ 
       this.props.navigation.setParams({
           scrollToTop: this.callScrollToTop.bind(this)
        })
 }

callScrollToTop() {
        this.listView.scrollTo();
}

//Inside component
 <ListView ref={ref => this.listView = ref} />
```

**Comment by carsonwah** [comment] 2018-04-25 07:47
@MaheshNandam Be careful this only works when your structure is `TabNavigator` -> `Component`.

It won't work if it is `TabNavigator` -> `StackNavigator` -> `Component`. In this case, you have find your component's `navigation` through `route.routes[n]`.

**Comment by MaheshNandam** [comment] 2018-04-25 07:53
Hey @carsonwah,

Thanks for your clarification, 

In addition, my structure is TabNavigator -> Component.

**Comment by tobbbe** [comment] 2018-08-16 08:49
Updated for react-navigation v2 (scene, jumpToIndex has been removed https://github.com/react-navigation/react-navigation/issues/4164) with `TabNavigator `-> `StackNavigator `-> `Component` structure:

```
tabBarOnPress: () => {
    // Scroll to top
    if (navigation.state.index === 0) {
        const navigationInRoute = navigation.getChildNavigation(navigation.state.routes[0].key);

        if (!!navigationInRoute && navigationInRoute.isFocused() && !!navigationInRoute.state.params && !!navigationInRoute.state.params.scrollToTop) {
          navigationInRoute.state.params.scrollToTop();
        }
        else {
          navigation.navigate(navigation.state.key)
        }
    }
}
```

and then in `StackNavigator` component:
```
componentDidMount() {
    this.props.navigation.setParams({
      scrollToTop: () => {
        this.scrollViewRef.scrollTo({ x: 0, y: 0, animated: true })
      }
    })
  }
```

**Comment by avengyy** [comment] 2018-09-20 08:01
> Updated for react-navigation v2 (scene, jumpToIndex has been removed #4164) with `TabNavigator`-> `StackNavigator`-> `Component` structure:
> 
> ```
> tabBarOnPress: () => {
>     // Scroll to top
>     if (navigation.state.index === 0) {
>         const navigationInRoute = navigation.getChildNavigation(navigation.state.routes[0].key);
> 
>         if (!!navigationInRoute && navigationInRoute.isFocused() && !!navigationInRoute.state.params && !!navigationInRoute.state.params.scrollToTop) {
>           navigationInRoute.state.params.scrollToTop();
>         }
>         else {
>           navigation.navigate(navigation.state.key)
>         }
>     }
> }
> ```
> and then in `StackNavigator` component:
> 
> ```
> componentDidMount() {
>     this.props.navigation.setParams({
>       scrollToTop: () => {
>         this.scrollViewRef.scrollTo({ x: 0, y: 0, animated: true })
>       }
>     })
>   }
> ```

Thanks for the solution! @tobbbe 

Also refined with pop to root of stack if tabBar is pressed again when tab is already focused and not on root page of the stacks (stack in tab). 

Such it behaves more as intended, hope it helps anyone in need!

```
if (navigation.isFocused() && navigation.state.index > 0) {
    // Pop to root on tab bar pressed if already focused on the tab
    navigation.popToTop();
  } else {
    // Scroll to top if at root of tab
    const navigationInRoute = navigation.getChildNavigation(
      navigation.state.routes[0].key
    );

    if (
      !!navigationInRoute &&
      navigationInRoute.isFocused() &&
      !!navigationInRoute.state.params &&
      !!navigationInRoute.state.params.scrollToTop
    ) {
      navigationInRoute.state.params.scrollToTop();
    } else {
      navigation.navigate(navigation.state.key);
    }
  }
```

In component

```
componentWillMount() {
  this.props.navigation.setParams({
    scrollToTop: () =>
      this.scrollViewRef.scrollTo({ x: 0, y: 0, animated: true })
  });
}
```
```
<ScrollView ref={ref => (this.scrollViewRef = ref)}></ScrollView>
```

**Comment by jjg77** [comment] 2019-03-05 05:13
Does anyone have  working version of this for react-navigation v3?

**Comment by mmjd** [comment] 2019-04-06 20:45
calling setParams in componentWillMount leads to infinite render loop

**Comment by eballeste** [comment] 2019-04-08 20:09
componentWillMount is deprecated

**Comment by JoeM-RP** [comment] 2019-04-22 19:57
Slightly modified the solution proposed by @avengyy + @tobbbe for `react-navigation 3.8.1`:

TabBarNavigator.js
```javascript
tabBarOnPress: () => {
  // Scroll to top
  if (navigation.state.params && navigation.state.params.scrollToTop) {
    navigation.state.params.scrollToTop();
  }
}
```

SomeTabPage.js
```javascript
class SomeTabPage extends Component<Props> {
  scrollView : ScrollView;

  componentWillMount() {
    this.props.navigation.setParams({
      scrollToTop: this.scrollToTop,
    });
  }

  scrollToTop = () => {
    if (this.scrollView) {
      // Scroll to top of ScrollView. Syntax will vary for FlatList, et al
      this.scrollView.scrollTo({ x: 0, y: 0, animated: false });
    }
  }

  render(){
    return(<ScrollView style={styles.listContainer} ref={ref => { this.scrollView = ref; }}>);
  }
}
```

CC: @jjg77

**Comment by AdrianMrn** [comment] 2020-01-23 14:10
I made a custom hook for this:

```tsx
import { FlatList } from "react-native";
import { useRef, useEffect } from "react";


export default function useScrollToTop<ListItem>(navigation: NavigationProp) {
    const listRef = useRef<FlatList<ListItem>>(null);

    function scrollToTop() {
        if (listRef.current) {
            listRef.current.scrollToOffset({ offset: 0, animated: true });
        }
    }

    useEffect(() => {
        navigation.setParams({ scrollToTop });
    }, [listRef.current]);

    return listRef;
}
```

Usage:
```tsx
const listRef = useScrollToTop<ListItem>(navigation);

return (
    <FlatList ref={listRef} />
);
```

And in the Navigation options:
```tsx
defaultNavigationOptions: {
    tabBarOnPress: ({ navigation, defaultHandler }) => {
        defaultHandler();

        // When on a screen and pressing the tab again, try to scroll to the top
        if (navigation.isFocused()) {
            const scrollToTop = navigation.getParam('scrollToTop', null);

            if (scrollToTop) {
                scrollToTop();
            }
        }
    },
},
```

**Comment by sbkl** [comment] 2020-07-23 03:23
Or use the built-in scrollTopTop [react-navigation-use-scroll-to-top](https://reactnavigation.org/docs/use-scroll-to-top)

**Comment by AdrianMrn** [comment] 2020-07-27 08:05
@sbkl Yep, that one's definitely the go-to nowadays. If I recall correctly, it didn't exist when I last posted in this thread.

**Comment by warrioru** [comment] 2021-01-21 11:35
useScrollToTop didn't work for me as my TabNavigator is within a StackNavigator.

My solution was to use the useIsFocused hook:

```
import {useIsFocused} from '@react-navigation/native';

const ref = React.useRef<ScrollView>(null);
  const isFocused = useIsFocused();
  useEffect(() => {
    isFocused && ref?.current?.scrollTo({y: 0, animated: true});
  }, [isFocused]);

```

**Comment by sjonchhe** [comment] 2021-01-28 04:05
https://reactnavigation.org/docs/use-scroll-to-top

**Comment by farhadeidi** [comment] 2024-11-01 13:10
I’ve created a gist to solve this problem in expo router tabs

https://gist.github.com/farhadeidi/d9f3af865d4f58d9e5c0c9dc4cc4ee6d
