### ISSUE TITLE
[iOS] New Issue in v1.5.6 - BottomTabBar icon visibility issue (showLabel:false) on Vertical mode in v1.5.6

### ISSUE THREAD

**Issue by malonguwa** [react-navigation/react-navigation#3757] opened 2018-03-15 07:17 UTC
@brentvatne 
thanks for the quick fix and reply for my previous issue  (https://github.com/react-navigation/react-navigation/issues/3754) - [iOS] BottomTabBar icon visibility issue (showLabel:false) when rotate screen to landscape from v1.5.0 to v1.5.4

## Current Behavior
..... BUT after install your latest release version 1.5.6..... there is new issue....
landscape mode is ok now.... the vertical mode has the same layout issue again......

please see my screenShot
![verticalissue](https://user-images.githubusercontent.com/2183780/37448996-9fe8cb36-2863-11e8-8e0d-e15c754b4bba.jpeg)

## More Info
FYI 1.5.5 works well both on landscape and vertical modes...........

You may need to init a new project in your local, run in the simulator to see the layout issue.

Please refer my demo code [just a TabBarNvigator with two screens] for
https://snack.expo.io/@lma/tabbarbottomlayoutissue

This is how I init my demo project.
`react-native init --version="0.50.3" TabBarBottomLayoutIssue
`

I think this commit cased the issue

https://github.com/react-navigation/react-navigation/commit/42230634fd0995b194b3120bff3c0c24407c5f2c

## Environment
react-native: 0.50.3
react-navigation: 1.5.6

**Comment by wellyshen** [comment] 2018-03-15 13:12
yea, tab icons invisible again in v1.5.6....

**Comment by brentvatne** [comment] 2018-03-15 17:21
fixed in 1.5.7

**Closed by brentvatne** 2018-03-15 17:21 UTC

**Comment by uinz** [comment] 2018-03-27 15:52
![simulator screen shot - iphone x - 2018-03-27 at 23 48 26](https://user-images.githubusercontent.com/12208108/37978851-a5e409a0-3219-11e8-8c3c-13af3803c595.png)
![simulator screen shot - iphone x - 2018-03-27 at 23 48 28](https://user-images.githubusercontent.com/12208108/37978853-a6255c48-3219-11e8-9443-a20dc587097e.png)


```json
{
  "react-navigation": "^1.5.8",
  "react-native": "0.54.2"
}
`

tab icons invisible when landscape left or right

**Comment by uinz** [comment] 2018-03-28 01:26
![simulator screen shot - iphone x - 2018-03-28 at 09 25 10](https://user-images.githubusercontent.com/12208108/38003430-12a1ba2e-326a-11e8-9557-f1d54bd53944.png)
works fine @1.5.5

**Comment by brentvatne** [comment] 2018-03-28 01:28
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
