### ISSUE TITLE
Upgrade to 5.1.5 cuases error when launching App

### ISSUE THREAD

**Issue by emclab** [react-navigation/react-navigation#7998] opened 2020-04-10 03:41 UTC
**Current Behavior**
After upgrading to latest react-navigation 5.1.5 from 5.1.3, there is error when launching app with `npx react-native run-android` (same without npx):

error: bundling failed: SyntaxError: C:\D\code\js\emps_fe615\node_modules\@react-navigation\bottom-tabs\src\index.tsx: Unexpected token (15:12)

  13 |  * Types
  14 |  */
> 15 | export type {
     |             ^
  16 |   BottomTabNavigationOptions,
  17 |   BottomTabNavigationProp,
  18 |   BottomTabBarProps,
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░ 98.5% (927/934), failed.

::ffff:127.0.0.1 - - [10/Apr/2020:04:35:24 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"

Here is the dependencies in package.json

"dependencies": {
    "@react-native-community/async-storage": "^1.8.0",
    "@react-native-community/cli-platform-android": "^4.1.1",
    "@react-native-community/datetimepicker": "^2.2.2",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "@react-navigation/bottom-tabs": "^5.2.6",
    "moment": "^2.24.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-audio": "^4.3.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-device-info": "^5.5.3",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-gifted-chat": "^0.13.0",
    "react-native-image-picker": "^2.3.0",
    "react-native-image-resizer": "^1.2.0",
    "react-native-keychain": "^4.0.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-modal": "^11.5.4",
    "react-native-modal-datetime-picker": "^8.3.0",
    "react-native-navbar": "^2.1.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-segmented-control-tab": "^3.4.1",
    "react-native-sound": "^0.11.0",
    "react-native-vector-icons": "^6.6.0",
    "socket.io-client": "2.1.1"
  },

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 8.1
| @react-navigation/native      5.1.5
| react-native                   0.61.5
| expo                           |
| node                           12.15.1
| npm or yarn                    1.22

**Comment by Ankit-sagar32** [comment] 2020-04-10 06:33
Encountered the same issue.

![image](https://user-images.githubusercontent.com/38493436/78968764-04a1b600-7b23-11ea-9440-eee8dc05f718.png)

Please suggest the last working compatible version for native, stack and drawer, it seems downgrading is also not working for me, due to compatibility mismatch.

**Comment by raajnadar** [comment] 2020-04-10 06:53
Follow this steps https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611377210

Check other issues before creating a new one.

**Comment by satya164** [comment] 2020-04-10 14:01
Duplicate of #7978

**Closed by satya164** 2020-04-10 14:01 UTC
Labels: bug
