### ISSUE TITLE
The transition is very laggy when navigation from (to) the screen with WebView

### ISSUE THREAD

**Issue by yuoppp** [react-navigation/react-navigation#3529] opened 2018-02-15 15:24 UTC
### Current Behavior

I have a WebView component on the page. When I'm trying to navigate from that screen or navigate to that screen, the transition is laggy on Android devices. Even if the page I'm navigating to from the webview screen is empty (nothing to render) the transition lags.

### Expected Behavior

Smooth transition

### How to reproduce

Put native WebView component on the screen. 

I have google maps with clusterized points loaded in my webivew. If i remove points and leave the map blank, the transition becomes less laggy, but still unacceptable for production.

I have read lots of issues here and here is short q & a:

1) not dev mode
2) release build
3) no conosle.* outputs
4) no redux logs
5) js thread drops to 12+- fps
6) ui thread dropping frames 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | @1.0.0-beta.16
| react-native     | 0.52.2
| node             |  9.4.0
| npm or yarn      | 5.6.0

testing on the real Android device with android 6.0 on it

**Comment by yuoppp** [comment] 2018-02-15 15:43
Here is more important Info:

The navigation structure is

TabNavigator:
--- Tab1
       --- Stack1
            ---WebViewScreen
            ---SecondScreen
--- Tab2
       --- Stack2

The transition lags when navigating from 'WebViewScreen' to 'SecondScreen'

If I remove tabbar completely:

Stack1
   ---WebViewScreen
   ---SecondScreen


everything works fine.

**Comment by brentvatne** [comment] 2018-02-17 17:47
please provide an example on https://snack.expo.io that reproduces this, or link to a github repo that reproduces this without any extraneous code

**Comment by brentvatne** [comment] 2018-02-22 02:43
closing this because there is no repro case.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Closed by brentvatne** 2018-02-22 02:43 UTC
Labels: needs repro
