### ISSUE TITLE
headerBackTitle prop breaks with Expo v48.0.0

### ISSUE THREAD

**Issue by FNG-2002** [react-navigation/react-navigation#11303] opened 2023-03-24 10:42 UTC
### Current behavior

When navigating from one screen to another there appears a headerLeft with a chevron left and the title of the previous screen. The prop `headerBackTitle` is supposed to change that text to something custom. Currently with version v48 of expo it displays the previous screens name despite defining `headerBackTitle`.

Home Screen             |  Details Screen
:-------------------------:|:-------------------------:
![grafik](https://user-images.githubusercontent.com/36012999/227499020-736268a6-097b-495b-8874-982052ddd3d3.png)  |  ![grafik](https://user-images.githubusercontent.com/36012999/227499153-0b33f8e2-30b2-47db-8b7e-0633f7eda2bd.png)

### Expected behavior

With version v47 of expo it displays the previous screens name and a custom title if `headerBackTitle` is defined.

Home Screen             |  Details Screen
:-------------------------:|:-------------------------:
![grafik](https://user-images.githubusercontent.com/36012999/227499020-736268a6-097b-495b-8874-982052ddd3d3.png)  |  ![grafik](https://user-images.githubusercontent.com/36012999/227499566-4cc0846e-3014-4b36-914c-14bb5351041f.png)

### Reproduction

https://snack.expo.dev/@bossfg/headerbacktitle-v47

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/native-stack         | 6.9.12
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | 3.18.0
| react-native                           | 0.71.4
| expo                                   | 48

**Comment by xiaomaodml** [comment] 2023-03-27 08:41
I had the same problem

**Comment by fabio-alvarenga** [comment] 2023-03-29 01:30
Seems to be related to https://github.com/software-mansion/react-native-screens/pull/1726, which was merged recently and will be coming soon to `react-navigation`

**Comment by itajenglish** [comment] 2023-04-21 01:34
+1

**Comment by itajenglish** [comment] 2023-04-24 13:19
Hi Guys, I created a [patch file](https://gist.github.com/itajenglish/5c8f61e19b829f07fb3220da69fa5b82) of the fix merged in the react-native-screens [PR](https://github.com/software-mansion/react-native-screens/pull/1726) that @fabio-alvarenga mentioned. I will however warn that I experienced nested navigators still showing back titles but navigating to root screens no longer shows. See the comment I left [here](https://github.com/software-mansion/react-native-screens/pull/1726#issuecomment-1518935590). Hope this helps for now until we get a fix.

**Comment by wkoutre** [comment] 2023-05-22 00:46
I've found that, without any patch, adding a `headerLeft` component results in the expected behavior.

**Comment by itajenglish** [comment] 2023-05-22 00:50
> I've found that, without any patch, adding a `headerLeft` component results in the expected behavior.

@wkoutre The patch solves the issue if you don't have nested navigators. If you do then you wouldn't need the patch, simply adding a `headerLeft` component to all screens that need to go back would solve the issue.

**Comment by kacperkapusciak** [comment] 2023-06-22 07:38
Fixed in `react-native-screens@3.21.1` and `@react-navigation/native-stack@6.9.13`. 

`react-native-screens` 3.21 in coming in the next Expo SDK 49 release

Cheers ✌️

**Closed by kacperkapusciak** 2023-06-22 07:38 UTC
Labels: bug, library:react-native-screens, platform:ios, repro provided
