### ISSUE TITLE
createDrawerNavigator:  Problem Passing Params between Navigators

### ISSUE THREAD

**Issue by romuloprandini** [react-navigation/react-navigation#5072] opened 2018-10-06 16:52 UTC
### Current Behavior

- What code are you running and what is happening?

I'm trying to use a DrawerNavigation combined with several independent StackNavigation, and I'm trying to navigate between those StackNavigation passing parameters, but the parameter is only passed to screen on same StackNavigation.

Example:
Structure:
<pre>
DrawerNavigation:
  |-- first: StackNavigation:
      |-- screen1: Screen1
      |-- screen2: Screen2
 |-- other: StackNavigation
      | --screen3: Screen3
</pre>

On Screen 1 (first) when we call `props.navigation.navigate('other', {someParam: 'Some Param'})` on the Screen 3 (other) no param is received

But, on Screen 1 (first) when we call `props.navigation.navigate('screen2', {someParam: 'Some Param'})` on the Screen2 (screen2) the someParam is received

### Expected Behavior

- What do you expect should be happening?

Receive the navigation param independently where is the screen, if it is inside or outside the Navigation.

### How to reproduce

Demo:
https://snack.expo.io/@romuloprandini/drawer-navigation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     |  16.4.1
| node             | 8.12
| npm or yarn      |  6.4

**Comment by zigzactly** [comment] 2018-10-10 09:02
I had a variant to your issue. This [solution](https://github.com/react-navigation/react-navigation/issues/143#issuecomment-361164542) worked for me.

Wrapper class and passing the param down via props. Its a bit of a hassle but it works.

**Comment by eriveltonelias** [comment] 2018-10-17 12:33
Hi @romuloprandini! 

Can you confirm if the @zigzactly solution works for you too?

**Comment by romuloprandini** [comment] 2018-10-21 15:19
Hi @eriveltonelias,

I cannot confirm if the workaround work since I decided to put all the screens in the same navigator and used navigation.push to call another screen.

Actually, I'm using the react-navigation only for navigation, because in most screens I have manually drawn the header (because I want to show/hide or expand/contract the header).

**Comment by eriveltonelias** [comment] 2018-10-24 14:07
Sure, I'll close this but ping me if you need help and thanks @zigzactly!

**Closed by eriveltonelias** 2018-10-24 14:07 UTC

**Comment by xgenem** [comment] 2019-04-14 15:11
I can confirm the issue is still present with the latest release. :'(
