### ISSUE TITLE
Hardware back button on android doesn't work on the first press

### ISSUE THREAD

**Issue by AnyByte** [react-navigation/react-navigation#9364] opened 2021-02-25 17:31 UTC
**Current Behavior**

Hardware back button only works on the second click when navigating from drawer to other stack pages.

**Expected Behavior**

I expect it to go back on the first click and without abusing
```
useFocusEffect(
    useCallback(() => {
      const onBackPress = () => {
        props.navigation.goBack();
        return true;
      };

      BackHandler.addEventListener("hardwareBackPress", onBackPress);

      return () =>
        BackHandler.removeEventListener("hardwareBackPress", onBackPress);
    }, [])
  );
```
on every screen after navigating from the drawer

**How to reproduce**

I made a quick reproducible demo
https://snack.expo.io/@anybyte/react-navigation-bug

1. Pull drawer from the left
2. Press on red "test" text
3. Press hardware back button to go back
4. It goes back only on the second press

**Your Environment**
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.9.3
| react-native                   | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
| expo                           | ^40.0.0
| node                           | v14.15.3
| npm or yarn                    | Yarn

**Comment by AnyByte** [comment] 2021-02-25 17:36
Yes issue still exists after upgrading to the latest version.

**Comment by Andr3wi77e** [comment] 2021-02-26 06:39
I have a similar problem. Back button works on the first press when navigating from drawer's screens, but works only on the second press when navigating from drawer to the same stack screen

**Comment by raajnadar** [comment] 2021-03-07 20:30
I can confirm this is happening for the hardware back key, but the stack bar back is working properly.

**Comment by marcaaron** [comment] 2021-04-02 00:41
In our case (and also yours from the look of the snack @AnyByte), it only seems like the back button does not work because we have a `DrawerNavigator` set up as a screen in a stack navigator with other screens that present above it. 

The `BackHandler` subscription in the `DrawerView` has no knowledge that a screen has been presented above it and closes the drawer instead of going back. It toggles a couple of times and the `goBack()` behavior we want eventually occurs.

https://github.com/react-navigation/react-navigation/blob/4b8155386b3723ed3e7c34d809ecec1d19f6bf00/packages/drawer/src/views/DrawerView.tsx#L122-L137

Presenting a screen above the drawer will **not** reset the `BackHandler` in the `DrawerView` since the `DrawerView` doesn't re-render. However, closing the drawer **will** reset it.

So, another work around is to put the "other stack pages" inside the `DrawerNavigator`. Then when you are navigating from the drawer to some other screen the drawer will close to display the other screen. 

However, if you wanted to re-open the drawer again then you'd still need some kind of custom back handler to prevent the event from bubbling to the drawer. The default behavior of the back button is to return to the bottom of the stack and not re-open the drawer again.

It seems like there is no satisfying answer, but hopefully this context helps someone else who has a similar issue.

**Comment by marcaaron** [comment] 2021-04-02 18:09
And seems like this commit also will fix the issue once published? cc @satya164 

https://github.com/react-navigation/react-navigation/commit/5ae0badc44b576d464f8841822a911b18a698403

**Comment by satya164** [comment] 2021-04-02 18:10
@marcaaron yes it should

**Closed** 2021-05-15 21:02 UTC
Labels: bug, repro provided

**Comment by hotaryuzaki** [comment] 2021-12-20 11:42
i have same issue, but with bottom tab bar
