### ISSUE TITLE
Extra blank space was displayed while using Bottom Tab Navigator in android 5.0

### ISSUE THREAD

**Issue by cnmmbd** [react-navigation/react-navigation#8320] opened 2020-05-24 08:43 UTC
**Current Behavior**
Extra blank space was displayed while using Bottom Tab Navigator in android 5.0

**Expected Behavior**
Bottom Tab displayed correctly.

**How to reproduce**
Using Bottom Tab Navigator in android 5.0

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| Android                | 5.0
| @react-navigation/native      |5.2.3
| @react-navigation/bottom-tabs |5.3.3
| react-native-screens          |2.7.0
| react-native                  |0.62.2
| expo                          |
| node                          |
| npm or yarn                   |

![Screenshot_1590307195](https://user-images.githubusercontent.com/47287843/82749648-37ef8a00-9ddd-11ea-9270-ae03fedda926.png)

```
export default function App() {
    return (
        <NavigationContainer>
            <Tab.Navigator 
                screenOptions={({route})=>({
                    tabBarIcon:({focused,color,size})=>{
                        let iconName;
                        if(route.name==="Home") {
                            iconName=focused
                                ?"ios-information-circle"
                                :"ios-information-circle-outline";
                        } else if(route.name==="Settings") {
                            iconName=focused
                                ?"ios-list-box"
                                :"ios-list";
                        }

                        return (<Ionicons name={iconName} color={color} size={size} />);
                    }
                    
                })}

                tabBarOptions={{
                    activeTintColor:"#4f467e",
                    inactiveTintColor:"gray"
                }}

            >
                <Tab.Screen name="Home" component={PlayerScreen} />
                <Tab.Screen name="Settings" component={FileScreen} />
            </Tab.Navigator>
        </NavigationContainer>
    );
```

**Comment by cnmmbd** [comment] 2020-05-24 09:01
still the same with the latest version @react-navigation/native 5.4.3 and @react-navigation/bottom-tabs 5.5.0

**Comment by raajnadar** [comment] 2020-05-24 11:36
Duplicate of  https://github.com/react-navigation/react-navigation/issues/8063

**Closed by raajnadar** 2020-05-24 11:36 UTC
Labels: bug, package:bottom-tabs

**Comment by IamMasterWayne** [comment] 2020-10-04 06:09
+1

**Comment by whitehourse** [comment] 2022-03-23 13:21
how to fix this use command
**yarn remove react-native-safe-area-context**
then run command
**yarn add react-native-safe-area-context**

23/03/2022 version is **"react-native-safe-area-context": "^4.2.2",**

**Comment by fummeys** [comment] 2024-05-27 17:30
Use this 
`
            screenOptions={{
                tabBarActiveTintColor: '#ffffff',
                tabBarStyle: {
                    backgroundColor: '#2a7e72',
                    borderColor: '#2a7e72'
                },

`
the color should be the background of the App's screen. It works for me
