### ISSUE TITLE
Crash getChildNavigation() with undefined childRoute

### ISSUE THREAD

**Issue by barbieri** [react-navigation/react-navigation#4610] opened 2018-06-30 15:12 UTC
I'm getting a crash at `getChildNavigation()`:

```js
  function getChildNavigation(navigation, childKey, getCurrentParentNavigation) {
    const children =
      navigation._childrenNavigation || (navigation._childrenNavigation = {});

    const childRoute = navigation.state.routes.find(r => r.key === childKey);
    // --- childRoute is undefined as it wasn't found
  
    if (children[childKey] && children[childKey].state === childRoute) {
      return children[childKey];
    }

    const childRouter = getChildRouter(navigation.router, childRoute.routeName);
    // --- crashes as childRoute is undefined
```
My navigation is:

 - AppNavigator
   - LoggedNavigator
     - SwitchNavigator (but could also be a Stack)
       - MyModal (goes to MyStackedRoute with params + key)
     - StackNavigator
       - MyStack (another StackNavigator)
         - MyStackedRoute (initial and final route)

Events:
 1.  start at MyStackedRoute without key/params
 2.  navigate to MyModal (not a sibling!)
 3. navigate to MyStackedRoute WITH a key + params

# How to Reproduce

Note that it's not always reproducible at first, in this case reload the app and try again. It seems to be related to some timing issues as animations (modal/card) and depth make it easier to reproduce (marked in the code below).

Snack: https://snack.expo.io/BkDqnMrfm

Code:

```js
import React from 'react';
import { View, Text, Button } from 'react-native';
import {
  createSwitchNavigator,
  createStackNavigator,
  withNavigationFocus,
} from 'react-navigation';

const MyStackedRoute = ({ navigation }) => (
  <View>
    <Text>{'click "Show Modal",\nthen "Crash!" to trigger the crash'}</Text>
    <Button
      title="Show Modal"
      onPress={() => navigation.navigate({ routeName: 'MyModal' })}
    />
  </View>
);
MyStackedRoute.navigationOptions = { title: 'MyStackedRoute' };

// withNavigationFocus() is important to trigger the bug, as it will
// try to evaluate navigation.isFocused(), which will call getChildNavigation()
// which doesn't find the childRoute in the stack anymore
const MyModal = withNavigationFocus(({ isFocused, navigation }) => (
  <View>
    <Text>{`isFocused: ${isFocused}\nNow click "Crash!"`}</Text>
    <Button
      title="Crash!"
      onPress={() =>
        navigation.navigate({
          routeName: 'MyStackedRoute',
          params: { value: 'A Value' } /* there must be a parameter */,
          key: 'new' /* there must be a key */,
        })
      }
    />
  </View>
));
MyModal.navigationOptions = { title: 'MyModal' };

// I could reproduce without MyStack, but not as easy
const MyStack = createStackNavigator({ MyStackedRoute });
MyStack.navigationOptions = { title: 'MyStack' };

const StackNavigator = createStackNavigator({ MyStack });
StackNavigator.navigationOptions = { title: 'StackNavigator' };

const SwitchNavigator = createSwitchNavigator({ MyModal });
SwitchNavigator.navigationOptions = { title: 'SwitchNavigator' };

const LoggedNavigator = createStackNavigator(
  {
    StackNavigator,
    SwitchNavigator,
  },
  {
    initialRouteName: 'StackNavigator',
    mode:
      'modal' /* modal seems important, likely because animation takes longer? */,
  }
);
LoggedNavigator.navigationOptions = { title: 'LoggedNavigator' };

// a top level navigator seems to be important, easier to reproduce
export default createStackNavigator({ LoggedNavigator });
```

**Comment by barbieri** [comment] 2018-06-30 15:13
it's easier to reproduce using iOS due the `modal: 'animation'` and timing differences.

**Comment by jamsch** [comment] 2018-07-03 02:09
Pretty sure that there's a race condition somewhere. I can reproduce this issue by pressing the back button quickly after visiting a specific screen that calls `navigaiton.setParams({})` on "componentDidMount" & "componentDidUpdate".

**Comment by barbieri** [comment] 2018-07-03 02:20
very likely and I'm not sure if the mistake is keeping the old route around (and if that is something we can control) or not checking the `childRoute` and later on the returned `navigation === undefined` in the user functions. If we better check `childRoute`, then what to return to outside (ie: user app) callers?

**Comment by jamsch** [comment] 2018-07-03 02:30
I'll come up with my own reproducible example as well to make sure it's not just an issue on my end

**Comment by jamsch** [comment] 2018-07-03 04:00
Here should be a way to replicate it, no code yet

1. Initial route
2. Navigate to "DashboardScreen"
3. Press Back button
4. Navigate/BACK event called, Navigation pops "DashboardScreen" and removes the route (with key: "id-1530589222245-5") from state.
5. `componentDidUpdate` triggers on "DashboardScreen" as it's not yet unmounted
6. "DashboardScreen" calls `navigation.isFocused()`
7. `isFocused()` calls `getCurrentParentNavigation()` is called in `react-navigation/src/getChildNavigation.js:87:32` 
8. Child key "id-1530589222245-5" no longer exists because it's removed from the state (in this example, "id-1530589222245-5")
9. `getChildNavigation(navigation, childKey, getCurrentParentNavigation)` uses the following to find the child route with the old child key that no longer exists:
```
// getChildNavigation.js
const childRoute = navigation.state.routes.find(r => r.key === childKey);
// childRoute = undefined
//...
const childRouter = getChildRouter(navigation.router, childRoute.routeName); // error!
```

**Comment by brentvatne** [comment] 2018-07-03 18:33
@ericvicenti

**Comment by ericvicenti** [comment] 2018-07-03 19:01
Thanks for the clear bug report! This will be fixed in the next release

**Closed** 2018-07-03 19:03 UTC
