### ISSUE TITLE
Swiping back with velocity only works one way

### ISSUE THREAD

**Issue by deiucanta** [react-navigation/react-navigation#6744] opened 2020-02-05 13:36 UTC
**Behavior**

https://www.youtube.com/watch?v=NSYIVcvPd08

**How to reproduce**

- start swipe back
- cancel swiping by moving the pointer quickly to the left

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |^5.0.0-alpha.35
| @react-navigation/stack        |^5.0.0-alpha.71
| react-native-gesture-handler   |^1.5.6
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment] 2020-02-12 11:31
Duplicate of #6782

**Closed by satya164** 2020-02-12 11:31 UTC
Labels: package:stack
