### ISSUE TITLE
gestureResponseDistance Doesn't work -- 

### ISSUE THREAD

**Issue by bobber205** [react-navigation/react-navigation#6199] opened 2019-08-20 16:54 UTC
`gestureResponseDistance` seems to only work when specified on a screen level, not a stack navigator level.

```
const ActivityStack = createStackNavigator(
    {
        MainNotificationScreen: MainNotificationScreen,
        AccountScreenNavigation: AccountScreen,
        AccountScreenFollowerLists: AccountScreenFollowerLists,
        ViewItemReviewScreenNotification: {
            screen: ViewItemReviewScreenNotification, 
            navigationOptions: {
                gestureResponseDistance: { horizontal: 400 }
            }
        },
        FollowerListScreen: FollowerListScreen,
        ListContentsAccountScreen: ListContentsAccountScreen,
    },
    {
        navigationOptions: {
            gestureResponseDistance: { horizontal: 400 }
        }
    }
);
```

This is my shortest stack navigator and I don't really wanna have to change all of them to include this gestureResponseDistance option. It'd be nice to specify this on the root level of the stack navigator instead.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest
| node             | 10.x
| npm or yarn      | latest yarn

**Comment by matthamil** [comment] 2019-08-20 18:57
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by satya164** [comment] 2019-09-16 10:54
Closing due to no repro. Please post a minimal runnable repro if you think this is still an issue.

**Closed by satya164** 2019-09-16 10:54 UTC
Labels: needs repro
