### ISSUE TITLE
Navigation icons are disappearing when clicking on a icon

### ISSUE THREAD

**Issue by Gardezi1** [react-navigation/react-navigation#3249] opened 2018-01-09 13:26 UTC
Hello guys I'm facing a problem. whenever I click on a icon the icon disappears and never return. I don't know what is it that is going wrong. I saw some question related to this issue so I think this might be a bug or I may be wrong. Please can somebody tell me what is it that is going wrong. Here is the code 

const HomeScreen = StackNavigator({
  Home: {screen: HomeScreen},
  ListAllScreen: {screen: ListAllScreen},
  DetailScreen: {screen: DetailScreen},
})

export default NavigatorRouter({
    Default: {
      screen: ({navigation}) => <HomeScreen screenProps={{rootNavigation: navigation}}/>,
      navigationOptions: {
        header: null,
        tabBarIcon: ({tintColor}) => <TabBarIcon icon={Images.homeScreenIcon} tintColor={tintColor}/>,
      }
    }
}

### Your Environment

| react-navigation | 1.0.0-beta.22
| node             | v8.9.1
| npm      | 5.5.1

**Comment by kelset** [comment] 2018-01-09 13:36
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Comment by Ajith-Pandian** [comment] 2018-01-09 13:37
@Gardezi1 Please provide more information. Which icon are you talking about? Is it `tabBarIcon`?.
You have StackNavigator in the beginning. From where `NavigatorRouter` came from. What it really does? Provide full snippet and steps to reproduce.

**Closed by kelset** 2018-01-09 13:36 UTC

**Comment by Gardezi1** [comment] 2018-01-10 06:58
sorry for the not providing the question as the template you provided but I figured out what was going wrong. 

and the solution is weird. My cell phone time was a bit behind my computer time. When I made both of them same it started working 

Again I apologize for not following the template
