### ISSUE TITLE
iOS StatusBar paddingTop

### ISSUE THREAD

**Issue by songxiaoliang** [react-navigation/react-navigation#3240] opened 2018-01-08 06:45 UTC
TabNavigator interface, when set the header: null, the status bar in iOS will appear on the height of the pitch, very ugly, do not know how to remove this spacing. Look forward to get a quick reply

￼
![1515393853139](https://user-images.githubusercontent.com/6975588/34661123-6becbcf8-f482-11e7-89e0-5ed701e2290f.jpg)

react-navigation: 1.0.0-beta.23
react-native:  0.44.3

**Comment by Ajith-Pandian** [comment] 2018-01-08 11:15
@songxiaoliang `header` is used to set TabBar/Toolbar.  In your image, you highlighted `StatusBar` in a red box. 
If you set `header: null` it will remove TabBar/Toolbar. If you want to remove that bar you should use `StatusBar` component ,

```js
// add this import at top
import { StatusBar } from "react-native";

const AppWithoutStatusBar = () => (
  <View style={{ flex: 1 }}>
    <StatusBar hidden={true} />
    <App /> //Your app component
  </View>
);

export default AppWithoutStatusBar;
````

I think it will help. 
If your problem is not solved, Please provide code snippet.

**Comment by songxiaoliang** [comment] 2018-01-08 11:26
@Ajith-Pandian thank you. setting hidden ={ true } causes the status bar to be completely hidden, but the effect I want is as follows: 
![wx20180108-192617](https://user-images.githubusercontent.com/6975588/34668778-d080cf66-f4a9-11e7-8099-d793e7494421.png)

Looking forward to your reply

**Comment by Ajith-Pandian** [comment] 2018-01-08 11:43
@songxiaoliang Use `translucent` to make transparent statusbar. 
```js
import { StatusBar } from "react-native";

const AppWithoutStatusBar = () => (
  <View style={{ flex: 1 }}>
    <StatusBar translucent={true} /> // note 'translucent' here
    <App /> //Your app component
  </View>
);

export default AppWithoutStatusBar;
````

**Comment by songxiaoliang** [comment] 2018-01-08 11:53
@Ajith-Pandian This is the way it is now, and the words I originally raised would appear in this way

**Comment by Ajith-Pandian** [comment] 2018-01-08 12:07
@songxiaoliang I think, you uploaded some images on this [comment](https://github.com/react-navigation/react-navigation/issues/3240#issuecomment-355947170). But nothing is uploaded. I'm not understanding `This is the way it is now, and the words I originally raised would appear in this way` this line without images.

**Comment by songxiaoliang** [comment] 2018-01-08 12:50
@Ajith-Pandian sorry，I mean, I use this way：

 <StatusBar translucent={true} />

there will be such a problem：
￼
![wx20180108-192617](https://user-images.githubusercontent.com/6975588/34671420-78a0cc7c-f4b5-11e7-9b3c-8257d11ed997.png)

**Comment by songxiaoliang** [comment] 2018-01-08 12:51
@Ajith-Pandian sorry，I mean, I use this way：

 <StatusBar translucent={true} />

there will be such a problem：
![1515415778474](https://user-images.githubusercontent.com/6975588/34671447-9d75cb6a-f4b5-11e7-9a33-ad6f8ceccba6.jpg)

**Comment by songxiaoliang** [comment] 2018-01-08 12:51
I mean, I use this way：

 <StatusBar translucent={true} />

there will be such a problem：
![1515415778474](https://user-images.githubusercontent.com/6975588/34671467-bbab1202-f4b5-11e7-9768-8c3aba68c1f9.jpg)

**Comment by Ajith-Pandian** [comment] 2018-01-08 13:33
@songxiaoliang try
 ```js
<StatusBar translucent={true} backgroundColor='transparent' />
````

**Comment by songxiaoliang** [comment] 2018-01-08 13:50
@Ajith-Pandian Invalid, or not

**Comment by kelset** [comment] 2018-01-08 21:57
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also add a repo that reproduces the issue.

**Closed by kelset** 2018-01-08 21:57 UTC

**Comment by Ajith-Pandian** [comment] 2018-01-09 10:16
@songxiaoliang  Provide code snippet related to this screen. Please follow [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Nargle30** [comment] 2019-07-30 10:12
If it's still an issue and all the answers aren't solutions, you can try to add a <View style={{backgroundColor:'some_color', height:'some_height'}}/> tag above <StatusBar/> tag. 
It will let you to color the StatusBar in 'some_color'
If you need to do that only for some exact device, use lib react-native-device-info
Mb it's the worst solution...
