### ISSUE TITLE
Incorrect component lifecycle when navigating components

### ISSUE THREAD

**Issue by bred7** [react-navigation/react-navigation#3592] opened 2018-02-24 09:58 UTC
### Current Behavior

Navigating back from a component then quickly navigating to a new component causes the first component to unnecessarily remount then unmount again.

### Expected Behavior

- The first component's componentDidUnmount method should be called only

### How to reproduce

The issue is reproducible on the iOS simulator using the NavigationPlayground App.
- Tap the Stack Example row
- Tap the "Go back" row from the Home Screen
- Quickly and as soon as the transition has complete hit the "Tabs Example" row (this needs to be timed just right in order to reproduce the issue but is easily reproduced once you get the timing right)
- Put a breakpoint or log in the Stack Example MyHomeScreen component and you'll see the the component is mounted/unmounted again

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.2
| react-native     | 0.53.3
| node             | 9.2.0
| npm or yarn      | 1.3.2

**Comment by brentvatne** [comment] 2018-02-24 20:07
cc @ericvicenti, seems like some transitioner thing, fun

**Comment by brentvatne** [comment] 2018-02-24 20:19
confirmed that this is fairly easy to repro by just adding an `alert` to `componentDidMount` in `SimpleStack.js` and following the above repro steps

**Comment by rbadr** [comment] 2018-02-27 11:16
I have also the same problem on Android

**Comment by janziemba** [comment] 2018-03-09 15:28
Same here. This also causes re-destroying redux form which is a huge problem.

<img width="473" alt="screen shot 2018-03-09 at 4 07 37 pm" src="https://user-images.githubusercontent.com/4710865/37214892-bc0ba7f4-23b6-11e8-88f7-25c8bae99760.png">

**Comment by brentvatne** [comment] 2018-03-09 19:02
I'm in the process of refactoring Transitioner and will hopefully get to the bottom of this in the process

**Comment by shekharskamble** [comment] 2018-03-17 06:40
@brentvatne - sorry to push you like this but is there any development on this? our release has stuck because of this issue.

**Comment by ericvicenti** [comment] 2018-03-17 06:54
Unfortunately we haven't managed to fix this yet- the current transitioner code is pretty difficult to work with. For your current release it would be best to work around the issue or use a different version of the library. Sorry about the difficulty!

**Comment by shekharskamble** [comment] 2018-03-20 12:56
@ericvicenti - which is the recommended stable version I should go for?

**Comment by joshyhargreaves** [comment] 2018-04-06 19:10
I have a slightly different scenario to the issue described here & the action after the `back` action is triggered programatically.
The remount was triggering some analytics code, which wasn't ideal.
One slightly crude solution seems to be running the secondary action after the first action transition is complete using `InteractionManager.runAfterInteractions`.

**Comment by shekharskamble** [comment] 2018-05-02 09:05
@ericvicenti @brentvatne - any updates on this?

**Comment by brentvatne** [comment] 2018-05-08 01:12
moving this to an umbrella issue to consolidate several issues that report the same thing

**Closed by brentvatne** 2018-05-08 01:12 UTC
Labels: bug

**Comment by pitchourou** [comment] 2019-02-15 03:16
Guys any update on this issue ??

**Comment by odnarb** [comment] 2020-02-25 14:51
Just ran into this. Pretty simple to reproduce in my app.

From activity A, I have the app goto activity B.
Then I create a back button handler in actvity B. Doesn't matter how long we wait.
The back button handler merely returns true. I can see in logs that the componentDidMount() function for activity A fires before my back button handler gets fired.
