### ISSUE TITLE
'header' cannot be defined as a function in navigation options for screen using react-18next

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#3204] opened 2017-12-31 12:33 UTC
I am trying to set the screen title.
I am using 'react-i18next' package and when I try this, inside my stack navigator, I am getting:

I am using:
RN: 0.48.4
react-navigation: ^1.0.0-beta.21

```
ScreenA: {
    screen: ScreenAContainer,
    navigationOptions: () => ({
        title: translate(`${'stringCode'}`),
    }),
},
```
and I am getting:
![image](https://user-images.githubusercontent.com/28925534/34461625-7010f7a0-ee37-11e7-81fe-7a896c4526ea.png)

**Comment by kelset** [comment] 2017-12-31 17:18
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

Moreover, there was already an issue like this, I highly suggest you follow what's written there: https://github.com/react-navigation/react-navigation/issues/1047

**Closed by kelset** 2017-12-31 17:18 UTC
