### ISSUE TITLE
core-js symbol polyfill breaks Android back button

### ISSUE THREAD

**Issue by wKovacs64** [react-navigation/react-navigation#5171] opened 2018-10-24 22:48 UTC
### Current Behavior

When using a `StackNavigator` from `react-navigation`, the physical/virtual back button on Android devices stops working correctly after importing the `Symbol` polyfill from `core-js`. Pressing the back button will exit the app rather than go back a screen.

### Expected Behavior

The back button should navigate to the previous screen in the stack rather than exiting the app.

### How to reproduce

Add the following to an otherwise working app:
```js
import 'core-js/fn/symbol'
```

Navigate to some screen where you'd expect to be able to press the back button to return to the previous screen. Press the back button on your Android device (or emulator). It will exit the app instead of returning to the previous screen.

Here is a Snack, but for some reason the problem will not be observable online - **you must export it and run it locally to see the issue**.

https://snack.expo.io/@wkovacs64/symbol-back

### Additional Comments

Certain modules (e.g. `firebase`, parts of the GraphQL suite, etc.) rely on the `Symbol` global for certain functionality, which does not exist in the old version of JavaScriptCore included in `react-native` at this time. The `core-js` symbol polyfill (`core-js/fn/symbol`) is either being included as a third-party dependency or people stumble upon it as a fix for a module that doesn't depend on it explicitly and they include it themselves. It's the popular choice, possibly because `react-native` already includes `core-js`, and it is recommended in many issues across GitHub for various `Symbol`-related errors in RN apps.

One `react-navigation` user [narrowed down](https://github.com/react-navigation/react-navigation/issues/1603#issuecomment-396036621) their broken Android back button issue to a recent version bump in the popular `firebase` package. As you can see in [this diff](https://github.com/firebase/firebase-js-sdk/compare/firebase@5.0.3...firebase@5.0.4#diff-b99e2877a7a2ef11cdb7eab24041475f), that's precisely when Firebase added the `core-js/fn/symbol` polyfill.

I don't know how this would be a `react-navigation` problem, as a quick GitHub search didn't turn up the use of `Symbol` here (although I could've missed it). But I'm also not sure how to log an issue with `core-js` for such a specific scenario like this without more information. There is an alternative polyfill, `es6-symbol`, which does not break the Android back button functionality (using `import 'es6-symbol/implement'`), so I guess it's some kind of conflict between the `core-js` implementation and `react-navigation`? If this issue doesn't belong here, my apologies - just wanted to get this in front of some eyes that might be more familiar with what's going on here. Thanks.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.3, 2.13.0, 2.18.1
| react-native     | 0.55.4 (Expo SDK v29, v30)
| node             | 9.x, 10.x, 11.x
| npm or yarn      | yarn 1.10.1

**Comment by brentvatne** [comment] 2018-10-24 23:36
wow, thank you so much for tracking this down to the root cause! now this we can work with :)

**Comment by brentvatne** [comment] 2018-10-24 23:41
fwiw, the next version of Expo (31) will include a much newer version of JSC with native Symbol so this won't be a problem anymore. https://github.com/react-community/jsc-android-buildscripts

I think perhaps we should suggest that anyone using this library on Android should use Expo SDK 31 or higher (when it is released next week or so) or install that package in their project. We don't have any novel use of the back button in this library either so probably anyone using React Native in general should use the updated version of JSC.

**Comment by ikhilko** [comment] 2018-10-29 19:07
@brentvatne & @wKovacs64 I'm experiencing pretty the same problem. But it was related not to react-navigation, but to another package that goes with symbol polyfill. So, I have a lot of research on this issue and now can bring a light on this problem.
@wKovacs64 this issue is not related to react-navigation itself, because it's just uses an RN build-in module [BackHandler](https://github.com/react-navigation/react-navigation-native/blob/master/src/createAppContainer.js#L85).

The problem is in conflict of RN build in polyfill for Set/Map implementations and applying Symbol polyfill in runtime.

Let me describe it a little bit deeper:
- You used react-navigation stack
- react-navigation stack used BackHandler module
- BackHandler module [used Set](https://github.com/facebook/react-native/blob/0.57-stable/Libraries/Utilities/BackHandler.android.js#L21) which is [polyfilled](https://github.com/facebook/react-native/blob/master/Libraries/vendor/core/Set.js) by RN itself
- All subscriptions of hardware buttons are stored in Set created at initialization time (react-navigation subscription also stored here).
-  And everything is working well until you applied a new Symbol polyfill which broke Set functionality.
[This line](https://github.com/facebook/react-native/blob/0.57-stable/Libraries/Utilities/BackHandler.android.js#L25) used Symbol.iterator under the hood, and because of Set was created before new polyfill applied it simply becomes not iterable.
- So, as a result BackHandler subscriptions set are broken, and when hardware button pressed there is no subscriptions, so it's simply calls default behavior (close app).

Sorry, for such long description, hope it's useful to understand a root of problem.

Currently I don't know exactly from which side it should be fixed.. But looks like anyway applying polyfill (which patched global Symbol) at runtime is not a good idea

**Comment by brentvatne** [comment] 2018-10-29 19:13
yup, spot on. can you try installing https://github.com/react-community/jsc-android-buildscripts in your project and let me know if it resolves your issue?

**Comment by ikhilko** [comment] 2018-10-29 19:14
@wKovacs64 for your case I can only suggest to 
```
import 'core-js/fn/symbol'
import 'core-js/fn/symbol/iterator'
``` 
as soon as JS started to execute (so BackHandler will create Set with already patched Symbol.iterator under the hood)

**Comment by ikhilko** [comment] 2018-10-29 19:23
> yup, spot on. can you try installing https://github.com/react-community/jsc-android-buildscripts in your project and let me know if it resolves your issue?

Sorry, I unable to use updated JSC version because of brownfield app (updating JSC requires [upping Android SDK min version](https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app)).

**Comment by ikhilko** [comment] 2018-10-29 19:42
@wKovacs64 Ok, got it, looks like RN Set/Map polyfills applied a lot earlier before core-js in the start of App..

**Comment by ikhilko** [comment] 2018-10-29 20:11
@wKovacs64 after digging a little bit deeper :)  I can suggest for you to add also:
```
import 'core-js/es6/map'
```

This line will override global.Map methods to use newly Symbol.iterator values, and looks like code inside RN BackHandler will work again.
But anyway, including core-js polyfill can broke something else inside RN. So, maybe you will need to include more things from core-js to fix all problems.

**Comment by ikhilko** [comment] 2018-10-29 20:20
Anyway, this is not react-navigation specific issue. A similar issue in RN repo https://github.com/facebook/react-native/issues/15902

**Comment by wKovacs64** [comment] 2018-10-29 20:29
@ikhilko I actually lucked out with my current app and was able to remove the code that used `Symbol` so I no longer need the polyfill at the moment. I'm also in a good spot to upgrade to Expo 31 with the new JSC when it's released, so I primarily opened the issue to shed some light on it for other weary travelers. 🙂 I agree that it is not a react-navigation issue (although people will likely end up here, as the Back button not working is a common manifestation of the problem).

We can close this if you want, @brentvatne? Not sure where you want to go with this (aside from waiting for Expo 31), given what we know now.

**Comment by brentvatne** [comment] 2018-12-01 02:10
expo 31 is out now which includes the latest jsc, I created an issue on our docs to explain suggest that people install latest jsc-android too, so yeah let's close this

**Closed by brentvatne** 2018-12-01 02:10 UTC
