### ISSUE TITLE
Previous params exist after navigate again

### ISSUE THREAD

**Issue by aliazizi** [react-navigation/react-navigation#5902] opened 2019-05-09 22:49 UTC
### Current Behavior

I have tab navigation that have two screen `A` and `B`
In `B` I have button to navigate to `A` with extra param.
So there is two way to go to `A`, with tabnavigation and with `navigate` method with params.

When I'm going from button and then go back and navigate with tab navigate, the param is exist and I cant figure out that which route user enter `A`

### Expected Behavior

When navigate from tabnavigate the params should be empty and not having the previous one

I know that's because componenet `A` not unmounted but the params should be empty in tab navigation.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | 0.59.5
| node             |
| npm or yarn      |

**Comment by eriveltonelias** [comment] 2019-05-13 13:16
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!

**Comment by aliazizi** [comment] 2019-05-13 16:04
@eriveltonelias it's actually unexpected behavior and it's a bug

**Comment by aliazizi** [comment] 2019-05-14 19:09
@eriveltonelias actually I'm solve my problem before sending post with redux store, but still It's bug, I not looking for getting help from you! I'm just saying it's a bug, params from navigate should updated after navigate from different route.

**Comment by dphaener** [comment] 2019-07-29 16:50
@aliazizi I agree with you. If this isn't a bug, and it's the desired behavior, I'd like to push back on that. When navigating and explicitly passing params, I would expect them to be ephemeral, and not persist on the next explicit navigation call.

During testing, I have noticed that if I explicitly pass a param, then it will be overwritten. It seems as if the params are being explicitly merged when navigating. 

If I am navigating *back*, then yes I would expect the params to persist, but not when I am navigating from a different screen.

@eriveltonelias I think this at least merits discussion and re-opening this ticket. It is very unexpected behavior, IMO.

**Comment by eriveltonelias** [comment] 2019-10-11 03:47
thanks @dphaener and @aliazizi, 

could someone try again using the latest version ? 

and please add a reproducible example on https://snack.expo.io/

**Comment by satya164** [comment] 2019-10-11 13:30
This is expected behaviour. Params are the state of a screen. If you are navigating to an existing screen, we wouldn't destroy its state. This lets other screens easily pass data to an existing screen without resulting in that screen's data being destroyed.

If you don't want a screen to keep its state, you can always replace the screen with a new one or explicitly overwrite the params. If params are not merged by default, then it's not possible to achieve this behaviour when you need it.

Regardless, this isn't a bug, so I'm closing this issue.

If you think this behaviour is problematic, then open an RFC here: https://github.com/react-navigation/rfcs describing why it's problematic and how the change would be useful.

**Closed by satya164** 2019-10-11 13:30 UTC
Labels: needs repro

**Comment by eriveltonelias** [comment] 2019-10-11 14:49
yeah, you're right @satya164, sorry! 

my mistake.
