### ISSUE TITLE
Page not remounting when route parameter changed

### ISSUE THREAD

**Issue by kocagozcem** [react-navigation/react-navigation#5819] opened 2019-04-17 09:56 UTC
### Current Behavior
I have 2 pages. Let's call them A and B. I have some cards on page A and has touchable opacities on cards to navigate to page B with a different id (using this id for getting data from the server).
`<TouchableOpacity style={styles.button} onPress={() => this.props.navigation.navigate('pageB',{id:this.props.id})} >
   <Text>PageB</Text>
</TouchableOpacity>`
It works well on first navigate. But when I navigate back to page A (by using side menu) and select another navigation button to navigate page B (different parameter) it navigates me to the same page with first navigate.

### Expected Behavior
Remount the page.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^3.6.1"
| react-native     | "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
| node             | v10.15.3
| npm or yarn      | Npm: 6.9.0 - Yarn: 1.15.2

**Comment by kgnadinger** [comment] 2019-04-17 13:25
Since you are using navigate, it creates Page B on the first go and when you "re"-navigate to page B again, it reuses that early page since you never popped it. If you are using componentDidMount in Page B to load your data, it will do that on the first go since the class for page B is created, but since you just navigate to it on the second go, componentDidMount is never called because it's already mounted.

If you are using a side menu, I'd recommend pushing to page B each time and resetting your stack when you navigate back to page A.

**Comment by matthamil** [comment] 2019-04-17 18:20
Closing because the answer above should guide you down the right path. The issue is due to a misunderstanding of stacks in react-navigation and not a bug. Check out the following on stacks:

https://reactnavigation.org/docs/en/stack-navigator.html
https://reactnavigation.org/docs/en/stack-actions.html

Hope this helps!

**Closed by matthamil** 2019-04-17 18:20 UTC
