### ISSUE TITLE
react-navigation demo crashes on goBack

### ISSUE THREAD

**Issue by Sharcoux** [react-navigation/react-navigation#4944] opened 2018-09-03 09:54 UTC
### Current Behavior

The code is the second demo code from this page:

https://reactnavigation.org/docs/en/headers.html#using-params-in-the-title

When using the "try this code" button, if you navigate through the app and then try to use the go back arrow, you get this error: `undefined is not a function`

### Expected Behavior

- What do you expect should be happening?

goBack should not crash...

### How to reproduce

Go to:

https://reactnavigation.org/docs/en/headers.html#using-params-in-the-title

Press: "try this code"
Press: "Tap to Play"
Press: "Go to details"
Press the arrow on the top left corner

**Comment by vonovak** [comment] 2018-09-08 23:31
hi! Thanks for reporting, this is caused by using an old react-navigation dep in package.json [in the snack](https://snack.expo.io/@react-navigation/using-params-in-title-v2). Using latest works. I'm not sure who has access to these snacks, but I guess @brentvatne does.

**Comment by vonovak** [comment] 2018-09-25 10:50
Closing, this is fixed. Thanks for reporting!

**Closed by vonovak** 2018-09-25 10:50 UTC
