### ISSUE TITLE
Strange margin TransitionPresets.ModalPresentationIOS

### ISSUE THREAD

**Issue by francescorusso2** [react-navigation/react-navigation#8165] opened 2020-05-01 05:50 UTC
**Current Behavior**

I'm using the latest version of react-navigation with custom header and custom transition.

It generates a strange margin sometimes.

<img width="486" alt="Schermata 2020-04-29 alle 08 59 28" src="https://user-images.githubusercontent.com/62027616/80784866-c5451300-8b7e-11ea-8398-e67f4f06a2a5.png">

**Expected Behavior**

<img width="486" alt="Schermata 2020-04-29 alle 08 59 50" src="https://user-images.githubusercontent.com/62027616/80784960-076e5480-8b7f-11ea-8c07-6b8bf37a5cd8.png">

**How to reproduce**

    const screenOptions = {
      ...TransitionPresets.ModalPresentationIOS,
      cardOverlayEnabled: true,
      gestureEnabled: true,
    };

    const options = {
      header: ({ scene, previous, navigation }) => (
        <ModalHeader scene={scene} previous={previous} navigation={navigation} />
      ),
    };

**Comment by SleeplessByte** [comment] 2020-05-08 00:21
I can consistently reproduce this by using:

- custom header + non-opaque background (any opacity != 1 will do)
- stack navigator
- navigate _back_.

The top of the screen will flash the exact margin you're showing in your screenshot as well.

**Comment by Ashoat** [comment] 2020-05-15 15:59
Thanks for this report @SleeplessByte. I'd like to investigate further but I need to be able to repro first. Could you set up a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) in the form of an [Expo Snack](https://snack.expo.io/) or a `react-native init`'d repo hosted on GitHub?

**Comment by satya164** [comment] 2020-05-23 17:03
Closing since you didn't provide a runnable repro. Please open a new issue if you have a runnable repro.

**Closed by satya164** 2020-05-23 17:03 UTC
Labels: bug, needs repro, package:stack
