### ISSUE TITLE
react navigation headerComponent

### ISSUE THREAD

**Issue by fangkyi03** [react-navigation/react-navigation#3238] opened 2018-01-08 02:17 UTC
"react": "^16.0.0-alpha.6",
    "react-native": "0.44.3",
    "react-navigation": "^1.0.0-beta.11"
   "dva": "1.3.0-beta2",
![image](https://user-images.githubusercontent.com/30390014/34656946-1afedae0-f45c-11e7-8e95-cbaa23509a19.png)
![image](https://user-images.githubusercontent.com/30390014/34656961-3908deaa-f45c-11e7-8d45-17ceb1573157.png)

![image](https://user-images.githubusercontent.com/30390014/34657027-e26ca378-f45c-11e7-9035-4d91b3aed539.png)

**Supplementary instructions**
WarningToList is TabBarComponent 

**Problem description**

Hello, I met a big problem in the use of my side.

Let's start with a specific case

I am a iPad development project

Now we need to use a display effect

Because react navigation does not have a headerComponent attribute

So this way is done right here.

But it turns out that this will have a big problem.

One effect I'm going to implement now is that the viewBack page is backfired from an external navigationActions.back.

Because each stackNavigation has a stackRouter, but when you launch back message here, the tabComponent inside is not in the father's routerList.

GetStateForAction can't find it at all when it searches. It can only recognize the parent level. So when you launch back, it becomes a parent page and returns instead of which page is selected by tabBar.

Then I used this way to do the same effect but found that the fundamental breakpoints didn't come in.

Solve the problem of how to solve the problem without modifying the react navigation source code

**Comment by Ajith-Pandian** [comment] 2018-01-08 10:55
@fangkyi03 Take a look at this library. https://www.npmjs.com/package/react-navigation-utils.

You can use `withHeader()` to provide custom header.

```js
// add this import statement at top
import { withHeader } from "react-navigation-utils";

let WarningToListWithHeader = withHeader(WarningToList, () => (
  <WarningHeader />
));

const router = StackNavigator({
  WarningToListRoot: { screen: WarningToListWithHeader }
});
````

**Comment by kelset** [comment] 2018-01-08 21:54
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-08 21:54 UTC
