### ISSUE TITLE
Gestures propagated on (blurred) stack screens

### ISSUE THREAD

**Issue by isuert** [react-navigation/react-navigation#9792] opened 2021-08-05 16:56 UTC
### Current behavior

The attached example consists of two screens: a home screen and a modal screen stacked on top, using nested navigators. The home screen contains a bottom sheet that closes when a drag-down gesture is applied to it. When the bottom sheet is closed, "bottom sheet closed" will be logged on the console.

Notice that when the modal screen is opened we can still close the bottom sheet by applying the gesture mentioned above, even though the home screen is blurred and is covered by the modal screen. The modal is kept transparent to understand better what's happening underneath, but the same behavior is observed even when the modal is not transparent (in this case we can check the console logs)

https://user-images.githubusercontent.com/13037224/128390188-38fce701-7ce6-4f92-a72f-fb27f34e6e55.mp4

Somehow when the modal view component (contained within the modal screen component) has a background color the bug does not happen. To try this uncomment line 60 of `App.js` in the project on Snack.

The same thing happens also in React Navigation 6 without using nested navigators. [Here](https://snack.expo.dev/@isuert/react-navigation-v6---gesture-issue) is a Snack with the same example using v6.

### Expected behavior

Gestures should not be propagated on stack screens in background.

### Reproduction

https://snack.expo.dev/@isuert/react-navigation-v5---gesture-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.6
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 5.14.7
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | ~3.4.0
| react-native-gesture-handler           | ~1.10.2
| react-native-reanimated                | ~2.2.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   | 42.0.0
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment] 2021-08-05 17:05
Duplicate of #8515

**Closed by satya164** 2021-08-05 17:05 UTC
Labels: bug, package:stack, platform:android, repro provided
