### ISSUE TITLE
Gradient Color For TabNavigator

### ISSUE THREAD

**Issue by alankarsaini** [react-navigation/react-navigation#4863] opened 2018-08-16 09:33 UTC
I want to set Gradient Colored tabs. But unable to do.

**Comment by eriveltonelias** [comment] 2018-08-18 17:50
Hi @alankarsaini. 

Did you try to create a custom TabNavigator and apply the gradient? 

Please follow this discussion, maybe can help you. 

https://github.com/react-navigation/react-navigation/issues/2601

**Comment by CrazyPython** [comment] 2018-08-20 15:56
This GitHub issues is only for reporting bugs. If the issue isn't a bug report, please close the issue. 

@ericvicenti Perhaps there should be an FAQ for customizing React Navigation, something to guide people to create custom navigators so less issues appear here.

**Comment by brentvatne** [comment] 2018-08-21 21:56
maybe someone could implement `renderBackground` for tabs, like the similar property in stack. either way yeah this is a feature request :) boilerplate reply below

<hr />

hi there! if you'd like to see this feature in react navigation, please [create a feature request](https://react-navigation.canny.io/feature-requests) for it. thanks!

**Closed by brentvatne** 2018-08-21 21:56 UTC

**Comment by wardjk87** [comment] 2019-10-15 19:07
I found a solution using expo Linear Gradient:

`   tabBarComponent: (props) => {
      return (
        <View style={{ height: 98 }}>
          <LinearGradient
            colors={['#f5f5f5', '#DBDBDB']}
            start={[1, 0]}
            end={[0, 0]}
            style={{flex: 1, padding: 15, borderRadius: 5}}>
            <BottomTabBar {...props} style={{backgroundColor: 'transparent' }}/>
          </LinearGradient>
        </View>
      );
    },`

**Comment by ymekuria** [comment] 2020-07-17 07:01
Thanks @wardjk87! Here is an updated solution for v 5.xx that utilizes the tabBar prop in the Tab.Navigator component (ie. const Tab = createBottomTabNavigator(); ) and v5 packages.  

import { BottomTabBar } from ''@react-navigation/bottom-tabs'';
import { LinearGradient } from 'expo-linear-gradient';

      tabBar={(props) => {
        return (
          <LinearGradient
            colors={['#f5f5f5', '#DBDBDB']}
            start={[1, 0]}
            end={[0, 0]}
          >
            <BottomTabBar
              {...props}
              style={{ backgroundColor: 'transparent' }}
            />
          </LinearGradient>
        );
      }}

**Comment by kacem22** [comment] 2020-09-08 02:35
@ymekuria i tried this solution (without expo) but i'm facing a problem since the tabBar is custom and i lose the indicator below each tab when it is focused, so i'm thinking about adding a borderBottomWidth with a white color when the tab is focused the second problem that i should animate the indicator while using gesture-handler it's really a headache

**Comment by mohity777** [comment] 2020-11-06 17:28
> @ymekuria i tried this solution (without expo) but i'm facing a problem since the tabBar is custom and i lose the indicator below each tab when it is focused, so i'm thinking about adding a borderBottomWidth with a white color when the tab is focused the second problem that i should animate the indicator while using gesture-handler it's really a headache

You dont lose the indicator below each tab. The indicator actually will take the same color and it look as it is disappeared but it is actually there. Try adding changing indicator style then u will see -
    <Tab.Navigator
tabBarOptions={{
        indicatorStyle: {backgroundColor: 'red'}
}}>

**Comment by kacem22** [comment] 2020-11-06 23:28
> > @ymekuria i tried this solution (without expo) but i'm facing a problem since the tabBar is custom and i lose the indicator below each tab when it is focused, so i'm thinking about adding a borderBottomWidth with a white color when the tab is focused the second problem that i should animate the indicator while using gesture-handler it's really a headache
> 
> You dont lose the indicator below each tab. The indicator actually will take the same color and it look as it is disappeared but it is actually there. Try adding changing indicator style then u will see -
> <Tab.Navigator
> tabBarOptions={{
> indicatorStyle: {backgroundColor: 'red'}
> }}>

i didn't notice that, i appreciate your help, thnx

**Comment by keomalima** [comment] 2020-11-26 21:34
> import { BottomTabBar } from ''@react-navigation/bottom-tabs'';
> import { LinearGradient } from 'expo-linear-gradient';

I tried this but I get a sort of a rectangle inside my tab, any idea why?

**Comment by kamal-hossain** [comment] 2020-11-29 01:52
> I found a solution using expo Linear Gradient, after coming across this 'dead-end'. Hopefully this helps someone else:
> 
> import { BottomTabBar } from 'react-navigation-tabs';
> import { LinearGradient } from 'expo-linear-gradient';
> 
> ` tabBarComponent: (props) => { return ( <LinearGradient colors={['#f5f5f5', '#DBDBDB']} start={[1, 0]} end={[0, 0]}> <BottomTabBar {...props} style={{backgroundColor: 'transparent' }} /> </LinearGradient> ); },`

# Thank you very much man!!

**Comment by murtazaezzy007** [comment] 2021-09-30 10:05
> Thanks @wardjk87! Here is an updated solution for v 5.xx that utilizes the tabBar prop in the Tab.Navigator component (ie. const Tab = createBottomTabNavigator(); ) and v5 packages.
> 
> import { BottomTabBar } from ''@react-navigation/bottom-tabs''; import { LinearGradient } from 'expo-linear-gradient';
> 
> ```
>   tabBar={(props) => {
>     return (
>       <LinearGradient
>         colors={['#f5f5f5', '#DBDBDB']}
>         start={[1, 0]}
>         end={[0, 0]}
>       >
>         <BottomTabBar
>           {...props}
>           style={{ backgroundColor: 'transparent' }}
>         />
>       </LinearGradient>
>     );
>   }}
> ```

THANKS A TON MAN! THIS SAVED MY DAY!

**Comment by DhRiTiD** [comment] 2022-05-23 13:18
Hi! im using materialTopTabNavigator here and this is my code...
please help me add gradient into my tabs 

```import React, { Component } from "react";
import { StyleSheet } from "react-native";
import { RFValue } from "react-native-responsive-fontsize";
import Ionicons from "react-native-vector-icons/Ionicons";

import { createMaterialTopTabNavigator } from "@react-navigation/material-top-tabs";

import Feed from "../screens/Feed";
import CreatePost from "../screens/CreatePost";

const Tab = createMaterialTopTabNavigator();

const TabNavigator = () => {
  return (
    <Tab.Navigator
      screenOptions={({ route }) => ({
        tabBarIcon: ({ focused, color, size }) => {
          let iconName;
          if (route.name === "Feed") {
            iconName = focused ? "book" : "book-outline";
          } else if (route.name === "Create Post") {
            iconName = focused ? "create" : "create-outline";
          }
          return (
            <Ionicons
              name={iconName}
              color={color}
              size={RFValue(30)}
              style={styles.icon}
            />
          );
        },
        tabBarStyle: styles.topTabStyle,
      })}
      tabBarOptions={{
        indicatorStyle: {
          backgroundColor: "transparent",
        },
        showLabel: false,
        activeTintColor: "purple",
        inactiveTintColor: "grey",
      }}
    >
      <Tab.Screen name="Feed" component={Feed} />
      <Tab.Screen name="Create Post" component={CreatePost} />
    </Tab.Navigator>
  );
};

export default TabNavigator;

const styles = StyleSheet.create({
  topTabStyle: {
    justifyContent: "center",
    alignItems: "justify",
    backgroundColor: "pink",
    height: "12%",
    width: "100%",
    borderTopLeftRadius: 0,
    borderBottomRightRadius: 200,
    overflow: "hidden",
    position: "absolute",
  },
  icon: {
    height: RFValue(40),
    width: RFValue(40),
  },
});
```

**Comment by deeksha-geeky** [comment] 2023-03-17 13:41
Placing this before Tab.Navigator worked for me!
```
 <LinearGradient
        colors={["#7162DB", "#473D97", "#433897"]}
        style={{
          left: 0,
          right: 0,
          bottom: 0,
          height: "10%",
        }}
      />
```
