### ISSUE TITLE
Deep Linking broken from 2.6.0 to 2.13.0

### ISSUE THREAD

**Issue by dpogoda** [react-navigation/react-navigation#4977] opened 2018-09-11 14:05 UTC
### Current Behavior

After updating the `yarn.lock` file, deep linking broke in our app. (Deep link opened the app, but didn't navigate to the configured path)
Adding `Linking.addEventListener('url', console.warn)` to `App.js` proved, that the app did receive the url with a correct path.
The problem occurred on both Android and iOS.

### Expected Behavior

The app should open the configured route. If downgrading to `react-navigation 2.5.5` deep linking works as expected.

### How to reproduce

Implement an app and configure paths, then open the app via a corresponding deep link.
Be sure to clean all possible caches and lock files.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.0 - 2.13.0
| react-native     | 0.56.1
| node             | 10.1.0
| yarn      | 1.6.0

### Additional note

I built the app on different environments and even build servers. The issue stayed the same.

Does anybody else have similar problems or a setup where deep links work as expected with the latest `react-navigation` version? I'd appreciate if someone could confirm the issue or help me resolve it.

**Comment by brentvatne** [comment] 2018-09-11 14:19
There were a bunch of fixes in 2.7.0 which @ericvicenti didn't consider 'breaking changes' because they corrected what he thought was broken behavior, it's possible that this behavior was relied on in your app. Check out the release notes: https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md#fixed-8

If you can share more information and preferably a minimal reproducible example we can look into the specifics. Thanks!

**Comment by brentvatne** [comment] 2018-10-01 18:05
closing because we didn't get a reproducible example but we can investigate if you get around to creating one and then open a new issue. thanks!

**Closed by brentvatne** 2018-10-01 18:05 UTC

**Comment by benseitz** [comment] 2019-03-25 16:16
If someone reads this:
The problem was, that the linked screen was nested inside another navigator.
Prior to `v2.6.0` this wasn't a problem, but since then thee app opened but didn't navigate to the screen. Defining a `path: '' ` on every parent navigator fixes this!

You can read more about this in detail here: [https://github.com/react-navigation/react-navigation/issues/1527#issuecomment-439201168](https://github.com/react-navigation/react-navigation/issues/1527#issuecomment-439201168)
