### ISSUE TITLE
migrating beta-27 to beta-30 gives error on app start

### ISSUE THREAD

**Issue by jacargentina** [react-navigation/react-navigation#3436] opened 2018-02-05 20:26 UTC
### Current Behavior

- What code are you running and what is happening?
Simply starting the app
- Include a screenshot if it makes sense.
<img width="341" alt="captura de pantalla 2018-02-05 a la s 17 23 04" src="https://user-images.githubusercontent.com/517228/35827067-76091880-0a99-11e8-96dd-90662b2b2d6d.png">

### Expected Behavior

- What do you expect should be happening?
App should start and work just fine
- Include a screenshot if it makes sense.
Normal app shot not needed

### How to reproduce

Migrating app from beta-27 to beta-30

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.30
| react-native     | ^0.53.0
| node             | 9.4.0
| npm      | 5.6.0

**Comment by kelset** [comment] 2018-02-05 21:34
Duplicate of https://github.com/react-navigation/react-navigation/issues/3437

**Closed by kelset** 2018-02-05 21:34 UTC
