### ISSUE TITLE
DrawerNavigator with config throws `TypeError: Cannot read property 'routeName' of undefined`

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [react-navigation/react-navigation#3232] opened 2018-01-06 11:47 UTC
The drawer navigator works fine when I don't pass a config. but when i pass a config it starts throwing undefined routeName Error.

![image](https://user-images.githubusercontent.com/21335564/34639377-33fb8bfe-f305-11e7-83c8-4edfc790793f.png)

in the above image if I remove 
```
{
  contentComponent: SideMenu,
  drawerWidth: 300
}
```

then it works fine. I'm sure its not issue with side menu because even config as of  
```
{
  drawerWidth: 300
} 
```
throws error

**Comment by kelset** [comment] 2018-01-06 15:04
1. you haven't followed the issue template
1. duplicate of issue reported in https://github.com/react-navigation/react-navigation/issues/3149 and https://github.com/react-navigation/react-navigation/issues/3148 - for which we have written in the release notes how to interact with it

**Closed by kelset** 2018-01-06 15:04 UTC
