### ISSUE TITLE
Nested tabs swiping

### ISSUE THREAD

**Issue by onlydave** [react-navigation/react-navigation#1442] opened 2017-05-10 12:27 UTC
After Update react-native-tab-view #1327 . Nested tabs on android don't swipe correctly. Video below and example added to the playground in the fork below.

Maybe related to https://github.com/react-native-community/react-native-tab-view/issues/225

Other swiping examples work just not nested.

Video: https://www.youtube.com/watch?v=dGDYaI6fsbE

Code: https://github.com/onlydave/react-navigation/tree/nestedTabs

@satya164

**Comment by satya164** [comment] 2017-05-10 12:31
This looks like the same as https://github.com/react-native-community/react-native-tab-view/issues/225

This seems to be a very old bug with ViewPager https://github.com/expo/ex-navigation/issues/415

**Comment by satya164** [comment] 2017-05-10 12:34
Also when you say nested, is it `swipeEnabled={true}` inside `swipeEnabled={false}` or `swipeEnabled={false}` inside `swipeEnabled={true}` ?

**Comment by onlydave** [comment] 2017-05-10 12:36
swipeEnabled={true} inside swipeEnabled={false}

**Comment by satya164** [comment] 2017-05-10 12:38
Thanks. Yeah, seems like that setup should trigger the bug

**Comment by allmaxgit** [comment] 2017-06-20 03:45
Some problem.
Swipe of nested tab navigator not works in first tab of main tab navigator.
Helps only config: ```{
  swipeEnabled: false,
  animationEnabled: false
}``` for nested tab navigator.
@satya164 have ideas?

**Comment by jamesalways** [comment] 2017-08-24 16:40
Same issue!!! Please fix it! Thanks!

**Comment by juan-quiver** [comment] 2017-08-31 13:01
Same issue here, any progress on this one?

**Comment by qbolec** [comment] 2017-09-05 13:47
We have resources (time) to help with this issue, but I would need some hints on where to start.

**Comment by SamiChab** [comment] 2017-10-16 13:59
Same issue here

**Comment by richy486** [comment] 2017-10-18 14:11
This appears to be an issue for me with `swipeEnabled={true}` inside `swipeEnabled={false}` on release builds of Android only, not on debug Android builds or any iOS builds.

react-native: version: 0.48.4
react-navigation: 1.0.0-beta.15

Tested on 
- Device: Samsung Galaxy S7 edge, Android 6.0.1
- Emulator: Nexus 5X, Android 7.1.1

**Comment by kelset** [comment] 2017-10-28 12:57
Sadly this looks like it's only fixable at `react-native` && `react-native-tab-view` level. Hopefully v70 of tab-view has the fix, and it will be integrated into `beta.16`.

**Comment by AKMaS** [comment] 2017-11-13 09:56
current:
        react-native-cli: 2.0.1
        react-native: 0.49.3
        react-native-tab-view@0.0.70
        react-navigation@1.0.0-beta.19
it  runs normally when i seted swipeEnabled={false} inside swipeEnabled={false},but the inside one just can't swipe,it's not what i want. did i miss something and  what should i do?

**Comment by MaheshNandam** [comment] 2018-04-11 12:04
react : 16.0.0
react-native - 0.50.4
react-navigation- 1.5.10

activeTintColor stuck while tap and swipe, please fix this issue?

**Comment by brentvatne** [comment] 2018-05-01 00:27
hi there! if this is still an issue, can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!

**Closed by brentvatne** 2018-05-01 00:27 UTC
Labels: bug, on hold
