### ISSUE TITLE
Deeplinking stops at tabNavigator

### ISSUE THREAD

**Issue by frankenthumbs** [react-navigation/react-navigation#4599] opened 2018-06-28 17:53 UTC
### Current Behavior

It seems like tabNavigator is not forwarding a deeplink url if the tab selected is the deeplink url.

This is the current structure of my navigators:
```
- Stack Navigator (pops up things modally)
    └ Tab Navigator (with 5 tabs)
        └ Stack Navigator (within each tab so we can push with tabs showing)
```

So lets say that the tab navigator is showing 5 tabs and the News tab is highlighting

| Home | News | Games | Friends | Music |
|---|---|---|---|---|
|   | ^ selected |   |   |   |

lets say that the news stack has an article screen inside of it.

If i try to deeplink to `appname://MainStack/News/Article?articleId=123` while the news tab is highlighted, then the app will not go to the article screen within the news tab.

### Expected Behavior

- The deeplink should allow you to travel to the article tab even when the news tab is highlighted/selected.

### How to reproduce

- i will put a sample if requested

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.3
| react-native     | 0.53.3
| node             | 8.9
| npm or yarn      | 1.6

**Comment by frankenthumbs** [comment] 2018-07-02 19:26
Hey @JoseVf, i created a repo recreating the issue i'm seeing.. i'll start digging around the code to see if i can find the issue.
https://github.com/frankenthumbs/react-navigation-deeplink

**Comment by JoseVf** [comment] 2018-07-03 15:43
Idk if it's related, but your code have some strange behaviors like the following one...

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22102736/42229988-73a9de84-7ead-11e8-8c91-ddb572242e26.gif)

🤔

**Comment by frankenthumbs** [comment] 2018-07-03 23:32
@JoseVf weird what version of ios/device were you simulating? not getting same behavior on simulated iphone 8 plus running 11.4

**Comment by JoseVf** [comment] 2018-07-04 03:47
Same as yours, iPhone 8 plus iOS 11.4

**Comment by sintylapse** [comment] 2018-07-05 14:04
Reproduced @frankenthumbs's issue in his repository and didn't find the bug that @JoseVf has

**Comment by sintylapse** [comment] 2018-07-05 17:18
Found the solution: don't use Home/News/News route naming, use Home/News/NewsIndex instead

**Comment by hegelstad** [comment] 2018-07-07 22:02
Try this:

```javascript
import React, { Component } from 'react';
import { Linking } from 'react-native';

export default function(Comp, uriPrefix) {
  const router = Comp.router;
  return class extends Component {
    static router = router;

    _urlToPathAndParams(url: string) {
      const params = {};
      const delimiter = uriPrefix || '://';
      let path = url.split(delimiter)[1];
      if (!path) {
        path = url;
      }
      return {
        path,
        params
      };
    }

    _handleOpenURL = (url) => {
      const parsedUrl = this._urlToPathAndParams(url);
      if (parsedUrl) {
        const { path, params } = parsedUrl;
        const action = router.getActionForPathAndParams(path, params);
        if (action) {
          if (action.action) {
            if (action.action.action) {
              this.props.navigation.dispatch(action.action.action);
            } else {
              this.props.navigation.dispatch(action.action);
            }
          } else {
            this.props.navigation.dispatch(action);
          }
        }
      }
    };

    componentDidMount() {
      Linking.addEventListener('url', ({ url }: { url: string }) => {
        this._handleOpenURL(url);
      });

      Linking.getInitialURL().then(
        (url: string) => url && this._handleOpenURL(url)
      );
    }

    componentWillUnmount() {
      Linking.removeEventListener('url', this._handleOpenURL);
    }

    render() {
      return <Comp {...this.props} />;
    }
  };
}
```

It works for 3 steps down. Add more nested actions if you need more than 3 steps down.

**Comment by ericvicenti** [comment] 2018-07-11 06:56
Hey folks, I'm doing some improvement on deep linking behavior right now. If you want to see if your issue is fixed, feel free to try out the code in here https://github.com/react-navigation/react-navigation/pull/4671

I'm going to close this issue because there is no simple clear way for me to reproduce this bug. The fix is coming soon and hopefully this problem will be resolved. In the mean time, feel free to open another issue which shows how I can easily reproduce the problem

**Closed by ericvicenti** 2018-07-11 06:56 UTC
Labels: deep linking, needs repro

**Comment by charpeni** [comment] 2018-08-06 14:12
Replicated in #4820.

**Comment by abdulbasit1248** [comment] 2019-01-30 12:36
it stops because you cannot set initialroutename dinamically. So one solution is that you can save the index of tab in redux and navigate between tabs using those index. like on changing tab you can save tab index as 
onNavigationStateChange = (prev, next) => {
    this.props.saveTabIndex(next.index)
  }
And if you want to open the specific tab from link you can do this
this.props.saveTabIndex.navigate(2)
In this way .the index of tab is set to 2 and when your tab navigator appears .it will automatically navigate to second tab
