### ISSUE TITLE
in stack navigation touch on screen it access root screen touch.

### ISSUE THREAD

**Issue by RONAKDHOLARIYA** [react-navigation/react-navigation#7757] opened 2020-03-09 06:02 UTC
Sorry for my poor english. Here I notice that in rn navigation v5.
if you use button or touchable opacity in root screen then you push other screen and it's totally blank and you touch on the screen so it access root screen button or touchable opacity.

**Comment by RONAKDHOLARIYA** [comment] 2020-03-12 07:32
here I share my issue video link
https://drive.google.com/open?id=12Mz_FvIcQm4N9_UfRDEwMdN3HSpfb7me

**Comment by satya164** [comment] 2020-03-17 09:01
please fill the issue template properly and describe what the issue is with a repro.

**Comment by satya164** [comment] 2020-04-08 10:01
Closing due to no repro.

**Closed by satya164** 2020-04-08 10:01 UTC
Labels: needs repro

**Comment by cenzovit** [comment] 2020-04-10 21:00
Running into this issue consistently when using react-native-jitsi-meet (video call module). Seems related to: https://github.com/skrafft/react-native-jitsi-meet/issues/85. Somehow touches on the top view in a stack navigator is triggering touches on screens below it.
