### ISSUE TITLE
Blank Screen Issue on Android

### ISSUE THREAD

**Issue by RE-N-Y** [react-navigation/react-navigation#1805] opened 2017-06-09 01:50 UTC
There were some similar issues with blank screen behaviors with react-navigation. I tried setting all my screen style to either device with and height or flex: 1. I never used remote JS debugging with my device so I am sure that's not the cause of this issue. But strangely enough, when I run my code on ios emulator everything works fine (except the transition speed is terrible but it loads the content)
No error logs are shown.... just a blank screen so I'm a little bit lost where to start with. But what's even more confusing is that the navigation works perfectly when I first navigate down, but it shows a blank screen when I do the same thing again.

To be more specific:

Router.js

```
import React from 'react';
import StartScreen from './screens/StartScreen';
import QuizScreen from './screens/QuizScreen';
import AchievementScreen from './screens/AchievementScreen';
import StatusScreen from './screens/StatusScreen';
import SelectScreen from './screens/SelectScreen';
import DeckScreen from './screens/DeckScreen';
import { StackNavigator, TabNavigator } from 'react-navigation';

const stackNavigatorOption = {
	headerMode: 'none'
};

const tabNavigatorOption = {
	animationEnabled: false,
	swipeEnabled: false,
	tabBarOptions: {
		activeTintColor: '#fff',
		inactiveTintColor: 'rgba(255,255,255,0.5)',
		showLabel: false,
		style: {
			backgroundColor: 'rgba(255, 255, 255, 0.3)',
			position: 'absolute',
	    	left: 0,
	    	right: 0,
	    	bottom: 0,
	    	height: 50
		}
	}
};

const Router = StackNavigator({
	start: { screen: StartScreen },
	main: {
		screen: TabNavigator({
			status: { screen: StatusScreen },
			pack: {
				screen: StackNavigator({
					deck: { screen: DeckScreen },
					mode: { 
						screen: StackNavigator({
							select: { screen: SelectScreen },
							quiz: { screen: QuizScreen }
						},stackNavigatorOption)
					}
				},stackNavigatorOption)
			},
			achievement: { screen: AchievementScreen }
		},tabNavigatorOption)
	}
},stackNavigatorOption);

export { Router };
```

So I start with StartScreen, navigate to pack, navigate to deck, navigate to select, navigate to quiz.
Then, I navigate up to deck. Everything is fine until here.... Then, when I navigate to select, I get a blank screen....

My environment:

"expo": "17.0.0",
"react": "16.0.0-alpha.6",
"react-native": "https://github.com/expo/react-native/archive/sdk-17.0.0.tar.gz",
"react-navigation": "^1.0.0-beta.11"
Testing Android Version: 7.0

Note: I'm using redux to dispatch NavigationActions to navigate.

**Comment by bennygenel** [comment] 2017-06-16 08:23
I have a sort of a similar problem and I also can't figure out what causes it.

I have bit of a complicated navigation. Bunch of nesting navigators. And also a separate StackNavigator. I use that navigator inside Settings Screen's render. This way I get a smaller navigation between settings options. (Hope I managed to explain)

Sort of goes like this;

```
const SettingsNavigator = StackNavigator({
  initialScene:{
    screen:Settings,
  },
  Account:{
    screen:Account,
  },
  About:{
    screen:About,
  },
  DeleteUser:{
   screen:DeleteUser,
  }
},{
  headerMode:'none'
});

const InitialNavigation = TabNavigator({
  Main: {
    screen:StackNavigator({
      MainTab:{
        screen: StackNavigator({
          MainTabStack:{
            screen:TabNavigator({
              Items: {
                screen: TabNavigator({
                  Inbox:{
                    screen:ItemInbox,
                  },
                  Sent:{
                    screen:ItemSent,
                  },
                }),
              },
              Friends: {
                screen: Friends,
              }
            }),
          },
          SingleItem:{
            screen: SingleItem,
          },
          Profile:{
            screen:Profile,

          },
          MyProfile:{
            screen:MyProfile,
          },
          TermOfUse:{
            screen:TermOfUse,
          },
          PrivacyPolicy:{
            screen:PrivacyPolicy,
          }
        }),
      },
      CreateItem:{
        screen:CreateItem,
      },
      SelectLocation:{
        screen:PlacePicker,
      },
      SelectUser:{
        screen:SelectUser
      }
    },{
        headerMode: 'none',
        mode: 'modal'
    }),
  },
  Loading:{
    screen:LoadingScreen,
  },
  Login: {
    screen:LoginWrapperNavigator,
  },
},{
  initialRouteName:'Loading',
  backBehavior:'none',
  swipeEnabled:false,
  animationEnabled:false,
  lazy:true,
});

```

This works perfectly on iOS. Every scene renders and shows perfectly. Problem is kind of strange. When I run the app on Android (Emulator and real device) on first start scenes renders correctly besides the settings navigator. I thought it was because of a styling issue until I realize that when I refresh the app ("R,R") Inbox Tab shows up but nothing renders on the screen. Just blank screen. I put down some console logs and saw that SectionList renders and iterates items. Also the navigations stops working. I can't even change the tabs. I switch to the Friends tab and the title changes but the screen sticks with the Inbox. 

If I kill the app and restart it again it works fine again. So I thought maybe its a debugging issue so I tried with the release version. This time I found out that if I close the app with the hardware back button and start it again it does the same thing when it does refreshing the app. But again when I kill the app and start it again it works fine.

Sorry for the detailed and boring explanation. I really don't know where to start looking so I tried to explain as much as I can.

----------------------------
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-navigation": "^1.0.0-beta.11"
    Android Version: 7.1.1 & 6.0.1

**Comment by bennygenel** [comment] 2017-06-17 09:28
**UPDATE:** I found out that my problem is caused by animation and swipe.
I disabled swipe and animation tabviews and it started working just fine.

```
{
  swipeEnabled:false,
  animationEnabled:false,
}
```

**Comment by yash2code** [comment] 2017-06-19 18:08
same issue : ````
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import LoginAnimation from './src/LoginAnimation'
import { TabNavigator } from "react-navigation";

const MainScreenNavigator = TabNavigator({
  Recent: { screen: LoginAnimation },
  All: { screen: AllContactsScreen },
});


export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <MainScreenNavigator/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
`

**Comment by RE-N-Y** [comment] 2017-06-22 03:38
Thanks for the comment bennygenel, I tried to implement it with my code, but it seems that setting swipeEnabled and animationEnabled to false, but it doesn't seem to fix the issue with blank screen with StackNavigators since those props are for tabNavigators

**Comment by yash2code** [comment] 2017-06-22 04:28
Actually its the issue with style  .I've solved this in two apps like this:

```javascript
import { StyleSheet, Text, View, Dimensions} from 'react-native';
import { Constants } from 'expo'
```

```html
<View style={styles.container}>
        <MainScreenNavigator style={{ width: Dimensions.get('window').width }}/>
   </View>
```
```javascript
         const styles = StyleSheet.create({
                container: {
                             flex: 1,
                             paddingTop: Constants.statusBarHeight,
                             backgroundColor: '#F5FCFF',
                                 }
                                                               });
```

**Comment by FredyC** [comment] 2017-07-09 21:13
It seems the issue #2106 I've made is similar to this one. I am not sure anymore it's just styling issue, but something is wrong there for Android.

**Comment by swellingt0n** [comment] 2017-08-03 17:00
I am having the same issue, but with a really simple set of two stack navigators. I am updating the state from redux, by navigating from the initial route directly to the Profile screen, as in the below stacks. It briefly renders the profile, but then goes blank.

```
var homeAction =  NavigationActions.navigate('Home');
var homeState = getStateForAction(homeAction, state);
var profileAction =  NavigationActions.navigate('Profile');
nextState = getStateForAction(profileAction, homeState);
return nextState
```

```
OuterStack - name: 'Outer', initialRoute: 'Login'
	Login
	Inner
InnerStack - name: 'Inner', initialRoute: 'Home'
	Home
	Profile
```

**Comment by nachod6692** [comment] 2017-08-07 22:24
Setting the options `swipeEnable ` and `animationEnabled `to `false ` seemed to fixed the issue when reloading the navigation state (my implementation is integrated with Redux).  

**RootNavigator**: 
```
const options = {
    //This was a hack to enable the screen after a redux rehydrate
    animationEnabled: false,
    swipeEnabled: false,
};

const RootNavigator = TabNavigator({
      login: { screen: LoginScreen },
      main: { screen: MainNavigator },
}, options);`
```

Nested **MainNavigator**:
```
const options = {
    swipeEnabled: false,
    
};

const MainNavigator = TabNavigator({
      surveys: { screen: SurveysScreen },
      section: { screen: SectionScreen }
}, options);
```

**Comment by gananggww** [comment] 2017-10-31 18:16
Just  not! use View Tag on Navigator like :
`export default class App extends Component<{}> {
  render() {
    return (
        <Navigator/>
    );
  }
}
`

**Comment by kelset** [comment] 2017-11-12 10:37
Pinging OP @RE-N-Y  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by sun2rise** [comment] 2017-11-13 13:48
version v1.0.0-beta.19 and still have this problem..

**Comment by kelset** [comment] 2017-11-13 14:05
@sun2rise what do you mean? Can you provide a Snack that reproduces this issue?

**Comment by sun2rise** [comment] 2017-11-13 14:20
hi @kelset! tnx for your fast response, unfortunately my app has a quite complex routing and I am afraid that reproduce it in a snack would be very long and meaningless.

I can tell you this: after a purchase, when I return to my home page sometimes it is completely blank (header too) but when I tap around the screen, if I tap, for example, on a button, it works and it can open another sceen, then when i go back the home is there without any problem.

Other times the page is rendered but i see it like as if a white semi-transparent overlay is present or just like as if a fade-in effect was not complete.

**Comment by kelset** [comment] 2017-11-13 14:41
> reproduce it in a snack would be very long and meaningless.

Not meaningless. At all.

The more complex the case, the hardest is to understand where the issue comes from. And since we maintainers have a finite amount of time we can dedicate to investigating issues, being able to reproduce a bug is fundamental.

Moreover, by asking who report a bug to create a dedicate repo/snack can lead to finding out that the issue [wasn't in the library in the first place](https://github.com/react-community/react-navigation/issues/2882#issuecomment-341437055).

That said, thanks for the description.
I'll keep the issue open.

**Comment by sun2rise** [comment] 2017-11-13 15:22
@kelset you're just right, it will only take ages, anyway i will try to do it, thanks.

**Comment by FredyC** [comment] 2017-11-13 16:36
@kelset There is a reproduced bug of blank screen using Snack in the issue #2106 from me. Chances are if that one is fixed, this might be fixed as well.

**Comment by kelset** [comment] 2017-11-13 16:54
Ah gotcha. Yeah looks like they are the same issue, so I'll close the other one in favor of this and link here the Snack - thanks for creating it @FredyC:

https://snack.expo.io/SJE4iferZ

**Comment by Gumija** [comment] 2017-11-20 08:44
I can reproduce this problem with StackNavigator when called like this:
```
navigation.dispatch(NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({routeName: 'nextRoute'})
  ]
}))
```
This does not happen every time, only sporadically and comes up less on release than in debug.
The screen gets blank but the buttons still react. When navigated back the originally blank screen it appears as usual.

**Comment by wprater** [comment] 2017-11-22 08:31
this seems to be happening on https://github.com/mjyoung/react-native-mobx-boilerplate

**Comment by shamsy** [comment] 2017-11-22 21:14
AlignItems: 'center' style caused the same issue for me:

const tabNavigator = TabNavigator(TabRoutesConfig, {
  tabBarPosition: 'top',
  animationEnabled: true,
  swipeEnabled: true,

  tabBarOptions: {
    activeTintColor: '#e91e63',
    labelStyle: {
      fontSize: 16,
    },
    style: {
      /*alignItems: 'center'*/
    },
  }
});

Commenting it solved my problem on android ... It was working just fine on iOS

**Comment by evanjmg** [comment] 2017-11-23 01:41
rotating my android phone fixes this. Anyone have any better workarounds?

**Comment by sun2rise** [comment] 2017-11-27 09:42
I'm sorry, AlignItems: 'center' is irrelevant to me

**Comment by Gumija** [comment] 2017-12-01 08:47
About StackNavigator:
I cannot reproduce this blank screen when `transitionConfig` is set e.g. like this:
```
transitionConfig: () => ({
  screenInterpolator: CardStackStyleInterpolator.forFade,
}),
```
Blank screen happens when `screenInterpolator` is set to the default `CardStackStyleInterpolator.forFadeFromBottomAndroid` animation.

This probably means that there is an obscure bug in `CardStackStyleInterpolator.forFadeFromBottomAndroid`.

**Comment by jacklj** [comment] 2017-12-06 17:01
@kelset here's a minimal Snack showing the bug (on Android) - if you uncomment out these two lines:
```
    // swipeEnabled: false,
    // animationEnabled: false,
```
then it works on Android.

**Comment by procoder317** [comment] 2017-12-07 06:20
I am also facing the same issue is their any proper work around I want to use the swipeEnabled as true props

**Comment by elforce001** [comment] 2017-12-21 23:41
I have the same issue. I created a demo app just to try it out. Everything works fine except Navigation part.

package.json:
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^23.0.0",
    "react": "16.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-23.0.0.tar.gz",
    "react-navigation": "^1.0.0-beta.19"
  }
}

App.js

class App extends React.Component {
    render() {
            const MainNavigator = StackNavigator({
            welcome: { screen: WelcomeScreen }
        });

        return (
            <View style={styles.container}>
                <MainNavigator />
            </View>
        );
    }
}

WelcomeScreen.js

class WelcomeScreen extends Component {
	render() {
		return (
			<View>
				<Text>WelcomeScreen</Text>
				<Text>WelcomeScreen</Text>
				<Text>WelcomeScreen</Text>
				<Text>WelcomeScreen</Text>
				<Text>WelcomeScreen</Text>
				<Text>WelcomeScreen</Text>
			</View>
		);
	}
}

export default WelcomeScreen;

**Comment by wprater** [comment] 2017-12-22 01:01
the Snack will repro this issue for me.  It seems to render on the device, but not on the emulator.

**Comment by erick2014** [comment] 2018-01-21 04:57
I followed the instruction given by @gananggww  and  it worked, I had something like:

```
import RootNavigator from './components/rootNavigator/rootNavigator';

export default class App extends Component {
	render() {
		return (
			<View><RootNavigator /></View>
		);
	}
}

```

And I just removed the View wrapping component, and it worked
```

import RootNavigator from './components/rootNavigator/rootNavigator';

export default class App extends Component {
	render() {
		return (
			<RootNavigator />
		);
	}
}
```

rootNavigator file:

```
import { StackNavigator } from 'react-navigation';
import ProductList from '../productList/productList';
import ProductDetail from '../productDetail/productDetail';

const RootNavigator = StackNavigator(
	{
		products: {
			screen: ProductList
		},
		productDetail: {
			screen: ProductDetail
		},
	}
)

export default RootNavigator;
```

**Comment by brentvatne** [comment] 2018-02-07 21:27
it sounds like @erick2014 had a solution. this is a pretty long thread, if there is a specific issue identified here that still exists, please spin it off into a new issue and follow the issue template, thanks!

**Closed** 2018-02-07 21:26 UTC
Labels: bug
