### ISSUE TITLE
Custom Drawer not rerender

### ISSUE THREAD

**Issue by JayricMok** [react-navigation/react-navigation#3297] opened 2018-01-18 09:04 UTC
Style `styles.draweritemstxt_active` and `styles.draweritemstxt_inactive` not set / rerender when I try to choose other drawer item.

**Navigator.js**

	const MainDrawer = DrawerNavigator({
	    Event: { screen: EventScreen },
	    Wallet: { screen: WalletScreen},
	    Profile: { screen: ProfileScreen},
	    Contact: { screen: MemberContactScreen},
	    Reward: { screen: MemberRewardScreen},
	},{
	  contentComponent: props => <DrawerScreen {...props} />
	});

**DrawserScreen.js**

	const DrawserScreen = props => {
	    let totalitem = props.items;
	    return(
	      <ScrollView style={{backgroundColor:'#000'}}>
	        <SafeAreaView forceInset={{ top: 'always', horizontal: 'never' }}>
              {
                totalitem.map((ritem,i)=>{
	                let txtstyle = null;
	                if(props.activeItemKey == ritem.key){
	                  txtstyle = styles.draweritemstxt_active;
	                }else{
	                  txtstyle = styles.draweritemstxt_inactive;
	                }
	                return(
	                  <TouchableHighlight key={i} activeOpacity={0.9} onPress={()=> props.navigation.navigate(ritem.key)} style={styles.draweritems}>
	                    <View>
	                      <Text style={txtstyle}>{_convertRouteToTitle(ritem.routeName)}</Text>
	                    </View>
	                  </TouchableHighlight>
	                );
                })
              }
	        </SafeAreaView>
	      </ScrollView>
	    );
	}

    export default DrawserScreen;

**Comment by kelset** [comment] 2018-01-18 09:24
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-18 09:24 UTC
