### ISSUE TITLE
Header Title on Android not rendering right.

### ISSUE THREAD

**Issue by moficodes** [react-navigation/react-navigation#7724] opened 2020-03-04 00:55 UTC
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.
Was going through the examples in the docs.

```
import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
    </View>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

This is the first example for Navigation.

but the issue seems to be on android
**Expected Behavior**
On iPhone 11 Pro Max it looks fine. But on One Plus 3 the Title just shows `Ho...` 

- What do you expect should be happening?
The Title shows "Home"
- Include a screenshot or video if it makes sense.
![Screenshot_20200303-194845](https://user-images.githubusercontent.com/14829780/75833798-22436900-5d88-11ea-8a1c-705f138a08b1.jpg)

**How to reproduce**
Ran it on an android device I had lying around.
- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | Oxygen OS 9.0.6, Android 9
| @react-navigation/native       | ^5.0.9
| @react-navigation/stack        | ^5.1.1
| react-native-gesture-handler   | ~1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | ~36.0.0
| node                           | v12.16.1
| yarn                    | 1.22.0

**Comment by jeremyhallden** [comment] 2020-03-04 14:22
This is probably related to this?
https://github.com/facebook/react-native/issues/15114#issuecomment-592162431

**Comment by WoLewicki** [comment] 2020-03-04 15:47
Based on the @jeremyhallden reply, the issue is not related to React Navigation, I am closing it.

**Closed by WoLewicki** 2020-03-04 15:47 UTC
Labels: bug, package:stack
