### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by wavemirani** [react-navigation/react-navigation#7994] opened 2020-04-09 21:26 UTC
after update the version "@react-navigation/native": "^5.0.9", to "@react-navigation/native": "^5.1.5", 

error: bundling failed: SyntaxError : .../node_modules/@react-navigation/stack/src/index.tsx: Unexpected token (51:12)

  49 |  * Types
  50 |  */
> 51 | export type {
     |             ^
  52 |   StackNavigationOptions,
  53 |   StackNavigationProp,
  54 |   StackHeaderProps,

**Comment by mitchellbutler** [comment] 2020-04-09 21:33
If it helps, I'm having the same issue with the `@react-navigation/drawer` package.

**Comment by lejsue** [comment] 2020-04-10 02:18
agree with @mitchellbutler , related to that commit. I just upgraded @react-navigation/material-top-tabs from 5.1.7 to 5.1.8, then build failed, and shown "Unexpected token" which is pointed to the line "export type {". 
I checked the release note, the different between 5.1.7 and 5.1.8 is just only added the commit: b71de6c.

**Comment by raajnadar** [comment] 2020-04-10 06:56
Follow this steps https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611377210

Check other issues before creating a new one. Please close the issue.

**Comment by satya164** [comment] 2020-04-10 14:01
Duplicate of #7978

**Closed by satya164** 2020-04-10 14:01 UTC
Labels: bug, package:stack

**Comment by AflakIqbal** [comment] 2020-06-24 15:06
i have the same issue

**Comment by rsvsaha** [comment] 2020-06-24 19:11
I am also having the same issue.

**Comment by serdarde** [comment] 2020-07-04 22:17
this solved my issue:
**npm i -D @babel/core @babel/runtime**

be sure that you use those actual versions:
"@babel/core": "^7.10.4",
"@babel/runtime": "^7.10.4",

see: https://stackoverflow.com/a/62289551/1981420

**Comment by Stephen2** [comment] 2020-08-15 06:43
Upgrade `@babel/core` in your project

**Comment by masf4dhil** [comment] 2021-02-24 08:00
> Upgrade `@babel/core` in your project

Thanks this work for me

**Comment by jsbls** [comment] 2021-03-12 16:32
For everybody who can't make it work, this tends to happen if `expo-cli` is globally installed. If it is, try this:

`yarn global add @babel/core`
Or its npm equivalent
`npm install -g @babel/core`

**Comment by raajnadar** [comment] 2021-03-12 19:05
Don't install npm modules as global it is a security threat.
