### ISSUE TITLE
@react-navigation/drawer@6.3.1 progress missing and useDrawerProgress() undefind 

### ISSUE THREAD

**Issue by abdullaziz89** [react-navigation/react-navigation#10443] opened 2022-03-19 11:57 UTC
### Current behavior

1. progress is missing when call drawerContent props
2. when try to use hook useDrawerProgress() in Drawer.Screen throw (no default value)

### Expected behavior

progress Reanimated Node that represents the animated position of the drawer (0 is closed; 1 is open).

according to react native drawer documentation.

### Reproduction

https://github.com/abdullaziz89/DrawerProgress

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                           | version |
| --------------------------------- | ----------- |
| @react-navigation/native               | "^6.0.8"     |
| @react-navigation/drawer              |  "^6.3.1"    |
| react-native-safe-area-context     | "3.3.2"       |
| react-native-screens                       | "~3.10.1"   |
| react-native-gesture-handler         | "~2.1.0"     |
| react-native-reanimated                 | "~2.3.1"     |
| react-native                                      | "0.64.3"    |
|react|"17.0.1"|
|react-dom|"17.0.1"|
|react-native-web| "0.17.1"|
| expo                                                  | "~44.0.0"  |
|expo-status-bar| "~1.2.0"|
| node                                                  | "16.14.0"   |
| npm                                                   | "8.3.1"       |

**Comment by bfricka** [comment] 2022-03-31 00:39
FYI @abdullaziz89 There's a typo in your example code. Line 25, App.js, should be `drawerContent=`, but it's `drawContant=`

**Comment by satya164** [comment] 2022-03-31 09:08
Closing as duplicate of #10073

**Closed by satya164** 2022-03-31 09:08 UTC
Labels: bug, package:drawer, platform:android, platform:ios, repro provided
