### ISSUE TITLE
[v4][Android] mode: modal, leaving white screen after closed screen (modal)

### ISSUE THREAD

**Issue by alimek** [react-navigation/react-navigation#7732] opened 2020-03-05 13:16 UTC
**Current Behavior**

- What code are you running and what is happening?
I have definition for main routing and Main (Drawer with BottomTabs) and lots of modals,
```createStackNavigator(
 createStackNavigator( {
    Main,
    ...modals,
  },
  {
    headerMode: 'none',
    mode: 'modal',
    initialRouteName: 'Main',
    defaultNavigationOptions: {
      ...navigatorStyle,
      gestureEnabled: false,
    },
  },
);
```

after update to `react-navigation-stack: 2.2.0` setting `mode: 'modal` on Android is leaving while screen every time when my modal is closed. It is not happening for `2.1.~` version and its not happening when I remove `enableScreens()` from `react-native-screens`.

**Expected Behavior**

Once modal is closed it should be fully closed instead of having white space.
![See Example](https://user-images.githubusercontent.com/4248465/75985561-6e0b2500-5ee4-11ea-8b6f-b9ed27d71381.png)

**How to reproduce**

will try to create repo

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android|
| react-navigation               |^4.0.10|
| react-navigation-stack         |^2.2.3|
| react-navigation-tabs          |^2.5.6|
| react-navigation-drawer        |^2.2.2|
| react-native-reanimated        |^1.7.0|
| react-native-gesture-handler   |^1.4.1|
| react-native-safe-area-context |^0.7.3|
| react-native-screens           |^2.2.0|
| react-native                   |0.61.5|

**Comment by satya164** [comment] 2020-04-08 10:02
Closing due to no repro.

**Comment by alimek** [comment] 2020-04-17 08:22
@satya164 sorry for long reply, but we had to postpone our migration to RN `0.62.X` and generally deps update.

Yesteday i sucessfully updated to `0.62.2` and all latest version of `react-navigation` as well as `react-native-screens`, looks like problem is still there.

This time i created repo:  https://github.com/alimek/react-navigation-stack-bug

I have not tested iOS from this repo, but Android bug is reproduced.

Let me know if anything else i can help

**Comment by alimek** [comment] 2020-04-19 10:49
btw, do we still need to have label `needs-repo` ?

**Comment by WoLewicki** [comment] 2020-04-21 07:37
Looks like the issue is resolved by https://github.com/software-mansion/react-native-screens/pull/471 and the issue alone is a duplicate of https://github.com/software-mansion/react-native-screens/issues/238. The problem is the same `FragmentManager` between many `ScreenContainer`s, which happens because of the usage of Stack navigator with `'mode' = 'modal'`. Can you confirm that applying the change fixes the bug?

**Comment by alimek** [comment] 2020-04-21 09:17
@WoLewicki just tested that and I can confirm issue is no longer happening, will use `patch-package` for now and expecting new `RNS` release soon 🎉 

thanks!

**Comment by WoLewicki** [comment] 2020-04-21 09:22
Great! I am closing it then. Feel free to comment if you have any suggestions.

**Closed by WoLewicki** 2020-04-21 09:22 UTC
Labels: bug, library:react-native-screens, version-4
