### ISSUE TITLE
StackNavigator state persists after unmounting

### ISSUE THREAD

**Issue by crobinson42** [react-navigation/react-navigation#7783] opened 2020-03-11 16:40 UTC
**Current Behavior**

- What code are you running and what is happening?

When navigating from a Drawer.Screen to another with the option `unmountOnBlur = true`, navigating to a _nested_ Drawer.Screen that is a StackNavigator then navigating away and then back to the same Drawer.Screen, even though the StackNavigator is unmounted, the StackNavigator's state persists when remounting.

[https://snack.expo.io/@coryrobinson42/(v5)-navigate-from-stack-to-stack-in-drawernavigator](https://snack.expo.io/@coryrobinson42/(v5)-navigate-from-stack-to-stack-in-drawernavigator)

**Expected Behavior**

- What do you expect should be happening?

When StackNavigator unmounts, it's state should be completely reset before the next time it mounts/renders.

- Include a screenshot or video if it makes sense.

[https://www.youtube.com/watch?v=iFEc5E8d3DQ](https://www.youtube.com/watch?v=iFEc5E8d3DQ)

**How to reproduce**

[https://snack.expo.io/@coryrobinson42/(v5)-navigate-from-stack-to-stack-in-drawernavigator](https://snack.expo.io/@coryrobinson42/(v5)-navigate-from-stack-to-stack-in-drawernavigator)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.0.5
| @react-navigation/stack        | latest
| react-native-gesture-handler   | 1.0.0
| react-native-safe-area-context | latest
| react-native-screens           | 2.0.0-beta.0
| react-native                   | latest
| expo                           | 0.35

**Comment by satya164** [comment] 2020-03-11 16:45
Duplicate of #6915

**Closed by satya164** 2020-03-11 16:45 UTC
Labels: bug, package:stack

**Comment by crobinson42** [comment] 2020-03-11 16:55
@satya164 I don't think this should be closed. The NavigationContainer's state persists the StackNavigator after it's unmounted and the docs say the state will be reset with `unmountOnBlur`

### unmountOnBlur

> Whether this screen should be unmounted when navigating away from it. Unmounting a screen resets any local state in the screen as well as state of nested navigators in the screen. Defaults to false.

**Comment by satya164** [comment] 2020-03-11 16:58
How is this different from the issue I linked?

> The NavigationContainer's state persists the StackNavigator after it's unmounted

Can you provide a repro for this?

**Comment by crobinson42** [comment] 2020-03-11 17:08
@satya164 I provided a Snack link and a video showing the issue.

**Comment by satya164** [comment] 2020-03-11 17:13
> I provided a Snack link and a video showing the issue

That doesn't mean that `NavigationContainer` persists navigator's state.

This is exactly same as the issue I marked as duplicate of.
