### ISSUE TITLE
Stack navigator still switches components from the background

### ISSUE THREAD

**Issue by karol-bisztyga** [react-navigation/react-navigation#8951] opened 2020-10-15 07:06 UTC
**Current Behavior**

Doing following steps:
- create stack navigator
- go to a specific component
- just tap on some area where previously was other component to choose
It still navigates to the component from the list which is in the background. It does not happen on the simulator but it does when run on the phone(Android 7.0 to be verified on newer).

<details>
<summary>Code</summary>

```
import { createBrowserApp } from "@react-navigation/web";
import React from "react";
import {
  FlatList,
  Platform,
  StyleSheet,
  Text,
  View,
  YellowBox,
} from "react-native";
import { RectButton, ScrollView } from "react-native-gesture-handler";
import { createAppContainer, createSwitchNavigator } from "react-navigation";
import { createStackNavigator } from "react-navigation-stack";

YellowBox.ignoreWarnings(["Calling `getNode()`"]);

const A = () => {
  return (
    <View style={{backgroundColor: 'red', width: 100, height: 100}}>
      <Text>Welcome to component A</Text>
    </View>
  );
};
const B = () => {
  return (
    <View>
      <Text>Welcome to component B</Text>
    </View>
  );
};
const C = () => {
  return (
    <View>
      <Text>Welcome to component C</Text>
    </View>
  );
};
const D = () => {
  return (
    <View>
      <Text>Welcome to component D</Text>
    </View>
  );
};


const data = [A, B, C, D];
const SCREENS = {};
data.forEach((item) => {
  SCREENS[item.name] = {
    screen: item,
    title: `Screen ${item.name}`,
  };
});

function MainScreen({ navigation }) {
  const data = Object.keys(SCREENS).map((key) => ({ key }));
  return (
    <FlatList
      style={styles.list}
      data={data}
      ItemSeparatorComponent={ItemSeparator}
      renderItem={(props) => (
        <MainScreenItem
          {...props}
          screens={SCREENS}
          onPressItem={({ key }) => navigation.navigate(key)}
        />
      )}
      renderScrollComponent={(props) => <ScrollView {...props} />}
    />
  );
}

MainScreen.navigationOptions = {
  title: "Example",
};

export function ItemSeparator() {
  return <View style={styles.separator} />;
}

export function MainScreenItem({ item, onPressItem, screens }) {
  const { key } = item;
  return (
    <RectButton style={styles.button} onPress={() => onPressItem(item)}>
      <Text style={styles.buttonText}>{screens[key].title || key}</Text>
    </RectButton>
  );
}

const StackApp = createStackNavigator(
  {
    Main: { screen: MainScreen },
    ...SCREENS,
  },
  {
    initialRouteName: "Main",
    headerMode: "screen",
  }
);

const ExampleApp = createSwitchNavigator({
  StackApp,
});

export const styles = StyleSheet.create({
  list: {
    backgroundColor: "#EFEFF4",
  },
  separator: {
    height: 1,
    backgroundColor: "#DBDBE0",
  },
  buttonText: {
    backgroundColor: "transparent",
  },
  button: {
    flex: 1,
    height: 60,
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
  },
});

const createApp = Platform.select({
  web: (input) => createBrowserApp(input, { history: "hash" }),
  default: (input) => createAppContainer(input),
});

export default createApp(ExampleApp);


```

</details>

![20201015_085335](https://user-images.githubusercontent.com/59833830/96087572-58230100-0ec4-11eb-9a89-88625f656a84.gif)

**Expected Behavior**

It should not navigate when already is in some component from the list.

**How to reproduce**

`create-react-native-app`

Full code's above, also `package.json`:

<details>
<summary>package.json</summary>

```
{
  "main": "index.js",
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
    "@react-navigation/web": "^1.0.0-alpha.9",
    "expo": "~39.0.2",
    "expo-splash-screen": "~0.6.2",
    "expo-status-bar": "~1.0.2",
    "expo-updates": "~0.3.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "~2.10.1",
    "react-native-unimodules": "~0.11.0",
    "react-native-web": "~0.13.12",
    "react-navigation": "^4.4.2",
    "react-navigation-stack": "^2.8.4"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "babel-jest": "~25.2.6",
    "jest": "~25.2.6",
    "react-test-renderer": "~16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

</details>

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5.7.6
| @react-navigation/stack        |5.9.3
| react-native-gesture-handler   |1.8.0
| react-native-safe-area-context |3.1.8
| react-native-screens           |2.10.1
| react-native                   |0.63.3
| expo                           |39.0.2
| node                           |14.5.0
| npm or yarn                    |1.22.4

**Comment by karol-bisztyga** [comment] 2020-10-15 08:33
The issue persists

**Comment by lame-dev** [comment] 2020-10-16 18:32
Same issue. 

Differences with your code of OP:
- using `TouchableOpacity` components instead of `RectButton`,
- components are not in a `FlatList`, but just a regular `View`,
- navigation between screens using `naviation.push()`.

The screen that is been navigated to has a `ScrollView` component. If you touch somewhere within this screen on the position of the `TouchableOpacity` components from the previous screen, it activates the `onPress()` functions from this `TouchableOpacity` component of the previous screen. Really weird and serious.

But if there is a touchable object on the same position within the next screen, nothing weird seems to happen.

Problem persists in both the simulator (Pixel 2, API 28), as well as on the phone (OnePlus 3T, Android 9).

```
@react-navigation/native: 5.7.2,
@react-navigation/stack: 5.8.0,
```

**Comment by satya164** [comment] 2020-10-20 09:57
Duplicate of https://github.com/react-navigation/react-navigation/issues/8515

**Closed by satya164** 2020-10-20 09:57 UTC
Labels: bug, package:stack
