### ISSUE TITLE
Headbar jumps after startup load.

### ISSUE THREAD

**Issue by Acetyld** [react-navigation/react-navigation#7665] opened 2020-02-25 17:25 UTC
https://gyazo.com/35756d862b09879d477302e8a74bf62e

This is the problem we have right now. As you see after the reload the headerbar jumps downwords and then goes back to its own place

If someone could take a look, that would be lovely.

Using **newest version** of React-navigation.
And just updated all packages but problem still present

**Comment by harveyconnor** [comment] 2020-02-26 01:56
having the same issue. When I change tabs it does it every now and then.

**Comment by gavinangym** [comment] 2020-02-26 04:34
Same here

**Comment by harveyconnor** [comment] 2020-02-26 04:39
I had this issue whilst using Material bottom tabs. Once I changed to the standard bottom tabs, the issue was gone.

**Comment by Acetyld** [comment] 2020-03-02 14:33
Fixed it by enabling transparant toolbar (the most top bar of the phone it self)

**Comment by WoLewicki** [comment] 2020-03-18 15:29
@Acetyld so can I close the issue then?

**Comment by raajnadar** [comment] 2020-04-30 11:24
Looks like the issue is resolved I am closing it!

**Closed by raajnadar** 2020-04-30 11:24 UTC
Labels: bug
