### ISSUE TITLE
How to add animation to reset action

### ISSUE THREAD

**Issue by leogeng** [react-navigation/react-navigation#3357] opened 2018-01-25 09:50 UTC
### Current Behavior

- What code are you running and what is happening?
No animation when navigating view by 'Reset' action 

### Expected Behavior

- What do you expect should be happening?
Animation happen when navigating view by 'Reset' action

**Comment by kelset** [comment] 2018-01-25 11:42
Duplicate of https://github.com/react-navigation/react-navigation/issues/2390

**Closed by kelset** 2018-01-25 11:42 UTC
