### ISSUE TITLE
The component for route must be a React component

### ISSUE THREAD

**Issue by varunchandran333** [react-navigation/react-navigation#3326] opened 2018-01-22 12:57 UTC
The component for route 'Sign' must be a React component. For example:

import MyScreen from './MyScreen';
...
Sign: {
  screen: MyScreen,
}

You can also use a navigator:

import MyNavigator from './MyNavigator';
...
Sign: {
  screen: MyNavigator,
}

This is the ERROR showing
------------------------------------------------------------------------------------------------------------------------------

I was creating a Login page, where i need to switch to pages with Login and Signup.
I am including full code.Please guide me on this.
-------------------------------------------------------------------------------------------------------------------------------

App.js
--------

import React,{Component} from 'react';
import { AppRegistry, StyleSheet, Text, View,StatusBar} from 'react-native';

import { StackNavigator } from 'react-navigation';

import Login from './App/src/pages/Login';
import SignUp from './App/src/pages/SignUp';

export default class myapp extends Component{
render(){
    return(
        <View style={styles.container}> 
         <StatusBar
          backgroundColor='#1c313a'
         barStyle='light-content'  
          />
           <Login/>
        </View>
    )
}
 
}

const styles = StyleSheet.create({
container:{
    flex:1,
    backgroundColor:'#455a64',
    alignItems:'center',
    justifyContent:'center'
}
});
 

AppRegistry.registerComponent('myapp', () => myapp);

---------------------------------------------------------------------------------------------------------------------------------

Login.js
---------

import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, View, StatusBar } from 'react-native';

import { StackNavigator } from 'react-navigation';
import SignUp from '../pages/SignUp';

import Logo from '../component/Logo';
import Form from '../component/Form';
class Login extends Component {

    static navigationOptions = {
        title: 'Login',
    };

    openSignup() {
        this.props.navigation.navigate('Sign');
    }

    render() {
        return (
            <View style={styles.container}>
                <Logo />
                <Form type='Login' />
                <View style={styles.signUpTextView}>
                    <Text style={styles.signUpText}>
                        Don't Have an Account Yet?
                </Text>
                    <Text style={styles.signUpButton} onPress={this.openSignup.bind(this)}>
                        SignUp
                </Text>
                </View>
            </View>
        )
    }

}

export default Project1 = StackNavigator(
    {
        Sign: { screen: SignUp },

        Log: { screen: Login },
    });

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#455a64',
        alignItems: 'center',
        justifyContent: 'center'
    },
    signUpTextView: {
        flexGrow: 1,
        alignItems: 'flex-end',
        justifyContent: 'center',
        paddingVertical: 16,
        flexDirection: 'row',
    },
    signUpText: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 16
    },
    signUpButton: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '500',

    },
});
--------------------------------------------------------------------------------------------------------------------------------

SignUp.js
------------

import React, { Component } from 'react';
import { AppRegistry, StyleSheet, Text, View, StatusBar } from 'react-native';

import { StackNavigator } from 'react-navigation';

import Login from '../pages/Login';

import Logo from '../component/Logo';
import Form from '../component/Form';
class SignUp extends Component {

    static navigationOptions = {
        title: 'SignUp',
    };

    openLogin() {
        this.props.navigation.navigate('Log');
    }

    render() {
        return (
            <View style={styles.container}>
                <Logo />
                <Form type='SignUp' />
                <View style={styles.signUpTextView}>
                    <Text style={styles.signUpText}>
                        Already have an Account?
                </Text>
                    <Text style={styles.signUpButton} onPress={this.openLogin.bind(this)}>
                        Login
                </Text>
                </View>
            </View>
        )
    }

}

export default Project2 = StackNavigator(
    {
        Sign: { screen: SignUp },

        Log: { screen: Login },
    });

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#455a64',
        alignItems: 'center',
        justifyContent: 'center'
    },
    signUpTextView: {
        flexGrow: 1,
        alignItems: 'flex-end',
        justifyContent: 'center',
        paddingVertical: 16,
        flexDirection: 'row',
    },
    signUpText: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 16
    },
    signUpButton: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '500',

    },
});

-----------------------------------------------------------------------------------------------------------------------------

I didnt find the issue.please guide me on this.
I dont know how 

export default Project1 = StackNavigator(
    {
        Sign: { screen: SignUp },

        Log: { screen: Login },
    });
this is implemented.
Where to add.

**Comment by kelset** [comment] 2018-01-22 14:37
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-22 14:37 UTC

**Comment by varunchandran333** [comment] 2018-01-23 04:17
Closing because you haven't followed the issue template??? How to do that??

**Comment by varunchandran333** [comment] 2018-01-23 04:21
have you tried updating to the latest release? i am working with latest
does it happen only on Android/iOS? i tested in android only
does it happen on both Debug and Release modes? i am a starter and just started. not a professional experienced developer. just learning

does it happen with Debugger On or Off? Both? i dont know

Can you provide a GIF or a repo or a snack to reproduce this issue? i have copy pasted the total code. in the issue . my 3 pages.

**Comment by varunchandran333** [comment] 2018-01-23 09:13
I got the answer. I have just removed 1 and 3 line from index.js .
import { AppRegistry } from 'react-native'; //these lines
import App from './App';
AppRegistry.registerComponent('myapp', () => App); //these lines

**Comment by 3DEsprit** [comment] 2018-03-23 19:01
Just for the sake of providing an answer, this will happen when the imported Component has not been properly exported. Looking at the above code, it looks like SignUp is lacking an export.

**Comment by mxdi9i7** [comment] 2018-05-27 21:58
I had the same issue and I've discovered that if I create the stack navigator in the same file as the component the error always pops up, I'd need to write my stack navigators from a different file for it to recognize the component as a real react component.
not sure if this is a bug...

**Comment by Shazam14** [comment] 2018-05-29 15:21
This is also my issue now, I can't seem to find that index.js!

**Comment by xanderberkein** [comment] 2018-06-12 09:29
I had this issue when I didn't export my ChildNavigator (located in another file) as default. I had multiple Navigators in one file, so I couldn't export them as default.

Changing `export { ChildNavigator }` to `export default ChildNavigator` fixed my problem.

**Comment by samirph** [comment] 2018-07-30 02:16
Glad an answer was provided.

The docs just seem to show all the classes in a single file, didn't see any official example splitting screens in different files, not even splitting screen components. 

That happens in the docs of many other frameworks, they show the code but you have no clue where it should be put in.

**Comment by yugandhar-pathi** [comment] 2018-08-22 22:45
This is a peculiar problem!!
I had an default export as follows in one of my class ..

export default class Login extends Component {
 ...
}

//It gave me this error ..
//And the error is resolved when ...

class Login extends Component {
 ...
}
export default Login;

**Comment by alexpchin** [comment] 2018-09-02 02:35
@yugandhar-pathi Getting this as well...

**Comment by ZackLeonardo** [comment] 2018-09-29 07:40
in the validateRouteConfigMap.js:
`if (
      !screenComponent ||
      (typeof screenComponent !== 'function' &&
        typeof screenComponent !== 'string' &&
        !routeConfig.getScreen)
    ) {
      throw new Error(`The component for route '${routeName}' must be a React component....`

so:
you could try this: 
`() => <YOUR COMPONENT/>`

**Comment by sudarshanc** [comment] 2018-10-31 06:00
const MyNavigator = createStackNavigator(
  {
    RouteNameOne: {
      screen:() => <HomeScreen/>
    },
    RouteNameTwo: {
      screen:() => <NewScreen/>
    },
  },
  {
  initialRouteName: 'RouteNameOne',
  }
);
This worked for me.

**Comment by tarunmehta-quovantis** [comment] 2018-11-13 06:57
in my case I was exporting child(Composite) component as export default ChildComponent,
when I removed default. it worked .
might it help someone

**Comment by nandorojo** [comment] 2019-01-05 20:47
> ```
> const MyNavigator = createStackNavigator(
>   {
>     RouteNameOne: {
>       screen:() => <HomeScreen/>
>     },
>     RouteNameTwo: {
>       screen:() => <NewScreen/>
>     },
>   },
>   {
>   initialRouteName: 'RouteNameOne',
>   }
> );
> ```
> This worked for me.

This worked for me as well. Not sure where the problem for me – I suspect it is because I was using Redux's `connect` HOC.

**Comment by paranoia1906** [comment] 2019-01-09 20:45
Had the same issues. Was able to resolve by importing my Navigator from separate file. 

App.js 
```javascript
//...
import AppContainer from './navigator/MyNavigator';
//...
export default class App extends React.Component {
  render() {
    return <AppContainer />
  }
}
```

myNavigator.js
```javascript
import  AuthScreen  from '../screens/Auth';
import  HomeScreen  from '../screens/Home';
import { createStackNavigator, createAppContainer } from "react-navigation";

const AppNavigator = createStackNavigator(
  {
    Home: HomeScreen,
    Auth: AuthScreen
  },
  {
    initialRouteName: "Home"
  }
);
const AppContainer = createAppContainer(AppNavigator);
export default AppContainer;
```

Using default exports on all files.

**Comment by faawaz1** [comment] 2019-01-18 23:00
> Had the same issues. Was able to resolve by importing my Navigator from separate file.
> 
> App.js
> 
> ```js
> //...
> import AppContainer from './navigator/MyNavigator';
> //...
> export default class App extends React.Component {
>   render() {
>     return <AppContainer />
>   }
> }
> ```
> 
> myNavigator.js
> 
> ```js
> import  AuthScreen  from '../screens/Auth';
> import  HomeScreen  from '../screens/Home';
> import { createStackNavigator, createAppContainer } from "react-navigation";
> 
> const AppNavigator = createStackNavigator(
>   {
>     Home: HomeScreen,
>     Auth: AuthScreen
>   },
>   {
>     initialRouteName: "Home"
>   }
> );
> const AppContainer = createAppContainer(AppNavigator);
> export default AppContainer;
> ```
> 
> Using default exports on all files.

Thank you , it's working with me

**Comment by besil** [comment] 2019-01-23 20:43
> I had this issue when I didn't export my ChildNavigator (located in another file) as default. I had multiple Navigators in that one file, so I exported these Navigators as named exports.
> 
> Changing `export { ChildNavigator }` to `export default ChildNavigator` fixed my problem.

This worked for me, without removing nothing from index.js.
Very strange, thank you for this comment

**Comment by dihan** [comment] 2019-07-10 17:51
Seems this is also caused for the Redux 7.1.0

`https://stackoverflow.com/questions/55792970/using-react-redux-connect-method-in-react-navigation-show-error-the-component-f`

**Comment by krizpoon** [comment] 2019-09-02 05:16
I had the same problem. But since there are a lot of screens to convert from Objects to functions, I ended up writing a wrapper for this:

```
const wrapComponent = Comp => {
    return (props) => <Comp { ...props }/>;
};

const MyStackNavigator = (routeConfig, stackConfig) => {

    const newRouteConfig = {};
    const keys = Object.keys(routeConfig);
    for (let key of keys) {
        const route = routeConfig[key];
        if (typeof route.screen !== 'function') {
            newRouteConfig[key] = { ...route, screen: wrapComponent(route.screen) };
        }
        else {
            newRouteConfig[key] = route;
        }
    }

    return StackNavigator(newRouteConfig, stackConfig);
};
```

**Comment by kesepara** [comment] 2019-10-11 09:54
For those of you who is trying to write createBottomTabNavigator with [ ] array symbol, don't do it. It is the reason for you to get that error!

**Comment by briangonzalez** [comment] 2019-10-22 05:50
@kesepara Can you explain? Maybe show some example code?

**Comment by junocs** [comment] 2019-11-07 07:51
> This problem also happens when you have circular dependencies. I for example had helper function in router file and scene imported it. When I moved this function to a seperate helper class, everything started working

This solves my problem

**Comment by MichaelRSilva** [comment] 2019-12-22 21:06
> ```
> const MyNavigator = createStackNavigator(
>   {
>     RouteNameOne: {
>       screen:() => <HomeScreen/>
>     },
>     RouteNameTwo: {
>       screen:() => <NewScreen/>
>     },
>   },
>   {
>   initialRouteName: 'RouteNameOne',
>   }
> );
> ```
> 
> This worked for me.

This way, the 'navigation' attribute is not automatically entered on the first screen. Do you know how to add it?

Example: If my first screen is Splash, inside the builder, props.navigation...

**Comment by AmitPandya007** [comment] 2019-12-29 12:04
While using the import for my screen I had mistakenly used it like below:
**import {HomeScreen} from '../src/screens/HomeScreen';**

which needs to be like:
**import HomeScreen from '../src/screens/HomeScreen';**

this resolved my error.

**Comment by gurudewan** [comment] 2020-02-11 20:06
Just make sure you declare the thing/stack/screen/component you're referring to **before** you refer to it and this works.

(This is why some people above said that importing it from a different file fixed their issue - imports are always at the top of the file)

**Comment by yilmazt81** [comment] 2020-04-21 13:36
Use like this .. fucking react i spend hours 


const AutoStack = createBottomTabNavigator(
    {
        SignUp :SignUpScreen,
        SignIn: SignInScreen    
    },
    {
        initialRouteName:'SignUp'
    }
);

**Comment by pankajkmr036** [comment] 2021-08-13 12:18
I faced this issue while using latest version of react-redux (v7.x.x) with a very old version of react-navigation (v1.x.x).
The primary issue is that react redux connect HOC  returns an object rather a function wheres older navigation/routing libraries of react and react-native expect their screens.routes to be React components.

Release notes of react-redux 7.0.1 ( (https://github.com/reduxjs/react-redux/releases/tag/v7.0.1))  states as follows: 

```Note: connect now uses React.memo() internally, which returns a special object rather than a function. Any code that assumed React components are only functions is wrong, and has been wrong since the release of React 16.6. If you were using PropTypes to check for valid component types, you should change from PropTypes.func to PropTypes.elementType instead.```

To overcome this followed these steps
```const ConnectDashboard = connect(
  mapStateToProps,
  mapDispatchToProps
)(Dashboard);

export default class DashboardScreen extends Component {
  render() {
    return <ConnectDashboard {...this.props} />;
  }
}```

1. Passing my React component to HOC connect
2. Wrapping this returned object in another React component to keep it compatible with my navigation library.
3. Using this wrapper component as my navigation screen.
