### ISSUE TITLE
beta 14+ padding issues with TabNavigator

### ISSUE THREAD

**Issue by Morriz** [react-navigation/react-navigation#2805] opened 2017-10-22 12:29 UTC
### Current Behavior, after switching to beta 14 or higher:
- renders tab bar icons lower, as if it has extra padding on top, and they are rendered partly over the labels
- labels on tabs without icons (`showIcon: false`) are not correctly placed in the center, but instead also seem to suffer from extra padding on top (the labels stay in the same place as when they DO have an icon)

### Expected Behavior
- tab bar icon should be correctly placed above the labels
- labels on tabs without icons should be placed in the center

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.14
| react-native     | 0.49
| node             | 8.5.0
| npm or yarn      | 65.3.0

**Comment by Morriz** [comment] 2017-10-22 12:52
I tested this on:
- a real iOS 11.1 beta 4 device
- simulator iPhone X with iOS 11
- simulator iPhone 8 with iOS 11

**Comment by Morriz** [comment] 2017-10-22 13:02
Also, if I switch to a TabBarTop component, it renders short labels without icons in the middle, but on overflow it does not correct positioning and stays at the same coordinates

**Comment by spencercarli** [comment] 2017-10-23 01:16
This one is my fault...

> renders tab bar icons lower, as if it has extra padding on top, and they are rendered partly over the labels
I haven't seen this behavior. Do you have any styling modifications to the text and/or icons of your tabbar?

> Also, if I switch to a TabBarTop component explicitly, it renders short labels without icons in the middle ok, but with long labels that wrap it does not correct positioning and stays at the same coordinates
Could you open a separate issue for this?

**Comment by benoitvasseur** [comment] 2017-10-24 09:32
> renders tab bar icons lower, as if it has extra padding on top, and they are rendered partly over the labels

I had this issue in iOS 11 only. I fixed it by removing a `marginTop: 0` in the tabbar's label style.

**Comment by spencercarli** [comment] 2017-10-25 01:15
Was this something that you had added to your styles or that the library has?

**Comment by almirfilho** [comment] 2017-10-25 01:56
I'm having this same issue, but in my case it gets screwed just in iOS 11+. 
It looks like there's an additional element wrapping the contents of each tab, and we can't touch it. =/

**Comment by almirfilho** [comment] 2017-10-25 02:06
__iOS 10.3:__
<img width="387" alt="screen shot 2017-10-24 at 4 04 20 pm" src="https://user-images.githubusercontent.com/532254/31976779-22bfa4c0-b8d5-11e7-906c-30d644c52203.png">

__iOS 11.0:__
<img width="388" alt="screen shot 2017-10-24 at 4 04 40 pm" src="https://user-images.githubusercontent.com/532254/31976781-25fdf2ea-b8d5-11e7-9e4e-4fc47826fddb.png">

**Comment by benoitvasseur** [comment] 2017-10-25 08:02
@spencercarli 

That was something in my styles.

To Reproduce :
TabNavigator.js
```
{
    tabBarPosition: 'bottom',
    tabBarOptions: {
      activeTintColor: colorConsts.activeTintColor,
      inactiveTintColor: colorConsts.inputStyleHideo,
      pressColor: colorConsts.activeTintColor,
      showIcon: true,
      iconStyle: styles.icon,
      style: styles.tabBar,
      upperCaseLabel: false,
      labelStyle: styles.labelTabBar,
      indicatorStyle: styles.indicatorTabBar,
    },
  },
```

styles.js

```
icon: {
    width: 25,
    height: 25,
  },

tabBar: {
    height: 52,
    borderColor: colorConsts.loginTextColor,
    borderWidth: 0.5,
    backgroundColor: colorConsts.tabBarBackground,
  },

  labelTabBar: {
    width: Dimensions.get('window').width * (1 / consts.nbOngletTabBar),
    fontSize: 12,
    marginTop: 0, // <- This is the guilty one in my case, simply removed it and it worked as expected on iOS 10 & 11
  },

  indicatorTabBar: {
    backgroundColor: colorConsts.activeTintColor,
  },
```

Hope it helps

**Comment by almirfilho** [comment] 2017-10-25 20:22
I didn't have any `margin` properties on mine. 
Fixed it with _position absolute_ on both icon and label though, very inelegant, but ¯\\\_(ツ)\_/¯.

**Comment by spencercarli** [comment] 2017-10-26 01:28
Can someone provide a demo of this issue? I can't reproduce (here's a [snack demoing the correct behavior](https://snack.expo.io/S1Pe92CTZ))

**Comment by brunolemos** [comment] 2017-10-26 01:45
Same issue on 1.0.0-beta.13+ (but not on 1.0.0-beta.12):

### Screen shot from iOS 11:
![image](https://user-images.githubusercontent.com/619186/32026063-66347860-b9c1-11e7-8930-dddfa34f8459.png)


### Screen shot from iOS 9:
![image](https://user-images.githubusercontent.com/619186/32026051-568b731e-b9c1-11e7-9003-5c6698cc6079.png)

**Comment by brunolemos** [comment] 2017-10-26 02:13
@spencercarli I just copy and pasted the code from your [snack](https://snack.expo.io/S1Pe92CTZ) and I could reproduce it, so maybe if you try on you mac emulator you should too:

<img src="https://user-images.githubusercontent.com/619186/32031849-64ffc096-b9e2-11e7-86d1-1f40deec78f1.png" height="600" />

**Comment by brunolemos** [comment] 2017-10-26 02:24
@spencercarli I was able to reproduce the issue by wrapping your TabIcon with a `View`.
Snack: https://snack.expo.io/BJybwp0T-

```diff
MySettingsScreen.navigationOptions = {
  tabBarLabel: 'Settings',
  tabBarIcon: ({ tintColor, focused }) => (
+    <View>
      <Ionicons
        name={focused ? 'ios-settings' : 'ios-settings-outline'}
        size={26}
        style={{ color: tintColor }}
      />
      
+      { /* other components here, e.g. badge */ }
+    </View>
  ),
};
```

**Comment by spencercarli** [comment] 2017-10-28 15:03
So the issue only occurs when overriding the default? In your case (@brunolemos) I would think you would have to add the appropriate styles to get the view to render the icon in the correct spot.

Does anyone have any proposed solutions for this? From what I can tell it's mostly an issue of how people are customizing it, but would be open to making it easier to use.

**Comment by almirfilho** [comment] 2017-10-30 20:23
@spencercarli Yep, mine is customized too. But, considering it wasn't breaking in prior versions, and that it is behaving differently between iOS 10 and 11, I still would consider this a bug. Nonetheless, would be the "appropriate styles" for that matter? Because I could fix it putting some styles, but it was still breaking in iOS 10.

**Comment by lucasferreira** [comment] 2017-10-30 21:52
Is that possibile (or viable) to do something like this:

```
MySettingsScreen.navigationOptions = {
  tabBarLabel: 'Settings',
  tabBarIcon: ({ tintColor, focused, **style** }) => (
    <View style={style}>
      <Ionicons
        name={focused ? 'ios-settings' : 'ios-settings-outline'}
        size={26}
        style={{ color: tintColor }}
      />
    </View>
  ),
};
```

Like the other know props passed _(tintColor and focused)_, is it possible to pass some default style prop with the appropriate default style to use in custom Views?

**Comment by kelset** [comment] 2017-11-03 09:09
Hey @Morriz, we released `beta.17`; does your issue still happen in the latest version?

**Comment by jonas-arkulpa** [comment] 2017-11-03 14:33
@kelset Unfortunately, updating to beta.17 doesn't fix the issue for us.

In our case it also doesn't help to specify the height of the surrounding view (as @brunolemos commented). We have to do special margins for iOS 11, which isn't an optimal solution.

**Comment by spencercarli** [comment] 2017-11-03 16:11
I've got a repro and am hoping to have a PR open in regards to this today. Hoping it's a simple, automatic fix

**Comment by spencercarli** [comment] 2017-11-03 16:54
Alright, I haven't been able to find a solution that completely fixes this while still ensuring things working correctly in landscape. That being said I did find a potentially simple solution that you can implement in your app.

In the wrapping `View` in the tabBarIcon add a `justifyContent: 'center'` and it's working fine for me (for both portrait and landscape). I'm not sure how that will work with your other components, like badges, though (would love some feedback from all of you to see if it works)

Here's a demo: https://snack.expo.io/r10SAfcAZ

For anyone interested, [this is the problem line](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L145). If you can think of a way to make portrait and landscape work and be able to handle nested components I'm all ears!

**Comment by albinekb** [comment] 2017-11-08 13:33
I have worked around the issue by forcing `height: 40` on my `tabBarIcon`, works for me 👍

**Comment by guoliang1206** [comment] 2017-11-09 03:33
1.0.0-beta19 has issue same. 
On iPad with iOS 11 landscape mode,

![2017-11-09 11 27 32](https://user-images.githubusercontent.com/12846676/32587153-b2a42ed0-c541-11e7-91ff-5164e2b5b631.png)

**Comment by spencercarli** [comment] 2017-11-09 17:56
@guoliang1206 did you try the solution I posted earlier?

**Comment by guoliang1206** [comment] 2017-11-10 01:39
@spencercarli Yes ,I had try it like this, in portrait it works well, but in landscape mode, it still has problem.
` "react-navigation": "^1.0.0-beta.19",`,(also do the uninstall and restall)
```
 tabBarIcon: ({tintColor, focused}) => (
            <View style={{justifyContent: 'center'}}>
                <Image style={{width: 20, height: 20,}}
                       source={focused ? selected : normal}/>
            </View>
        ),
```
and the problem(Both simulator and device, iPhoneX and iPad)
![2017-11-10 9 35 29](https://user-images.githubusercontent.com/12846676/32638556-d7cc91e8-c5fa-11e7-910c-d87411636594.png)

**Comment by llamaluvr** [comment] 2017-11-10 19:33
@spencercarli I added some examples of my icon badge wrapper component to your original Snack here: [https://snack.expo.io/@llamaluvr/rn-beta.14+-wrapped-tab-bar-icon-with-badge-demo](https://snack.expo.io/@llamaluvr/rn-beta.14+-wrapped-tab-bar-icon-with-badge-demo). In short, what happens with the badge is... interesting. With justifyContent: 'center', my badge goes from the top right to the bottom right. With height: 26, it says in the top right. Going back to justifyContent: 'center', if I change my absolute positioning from top to bottom, it's back up in the top right.

I don't know what it all means, but here it is in case if gives you any ideas :-)

**Comment by gomdolkim** [comment] 2017-11-14 07:43
I had the problem when I use tabBarLabel with `Text` component. 
I changed showLabel to `false. 
```
  {
    tabBarOptions: {
      showLabel: false,
      showIcon: true
    }
  }
```

then I added label in `tabBarIcon`. 

```
    navigationOptions: { header: null,
      tabBarIcon: ({ tintColor, focused }) => (
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
          <Image source={focused ? require('../images/active.png') :
              require('../images/inactive.png')} />
          <Text style={{color: tintColor, fontSize: 12}}>Label</Text>
        </View>
       )
    }
```

**Comment by guoliang1206** [comment] 2017-11-14 08:21
@gomdolkim Do you have see that two labels under the icon?

**Comment by Leimi** [comment] 2017-11-14 09:01
Hi,

I also have trouble making my use case work with iOS 11. Thanks to everyone for the tips of going around the problem here and there. I personally didn't make any of them work for now (though I didn't try your simple but clever workaround @gomdolkim). I guess it's also because I'm not that confortable with debugging react native styles yet. Anyway!

My use case is: the focused tab in the tabbar has a label and an icon while all other unfocused tabs have only the icon. I have trouble trying to make the "icon-only" tabs be vertically aligned with the "icon+text" tab. The alignment works without any trouble on Android.

**Comment by MoOx** [comment] 2017-11-15 08:12
FYI in my case, (I am new to tabbar navigator) I "just" wanted a vector icon (so `<Icon />` which is text) and I had to specify width and height of my component

```js
class HomeScreen extends React.Component {
  static navigationOptions = {
    tabBarIcon: ({ tintColor }) => (
      <View style={{
        justifyContent: "center",
        height: 40,
        width: 40,
      }}>
        <Icon name="home" color="blue" size={24} />
      </View>  
    ),
```

**Comment by gomdolkim** [comment] 2017-11-16 12:25
@guoliang1206 no. I only see one label because I changed `showLabel` to false in `tabBarOptions`.

**Comment by gomdolkim** [comment] 2017-11-16 12:37
It could be helpful for you to look at the following code is full one what I am doing. 

```
import { TabNavigator, TabBarBottom } from 'react-navigation';

const Navigator = TabNavigator(
  {
    FirstTabName: { screen: FirstTabScreen,
    navigationOptions: { header: null,
      tabBarIcon: ({ tintColor, focused }) => (
       <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
          <Icon name="home" szie={24} />
          <Text style={{color: tintColor, fontSize: 12}}>FirstTab</Text>
        </View>
      )
    } },
    SecondTabName: { screen: SecondTabScreen,
    navigationOptions: { header: null,
      tabBarIcon: ({ tintColor, focused }) => (
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
            <Icon name="home" szie={24} />
            <Text style={{color: tintColor, fontSize: 12}}>SecondTab</Text>
        </View>
       )
    } },
  },
  {
    initialRouteName: 'FirstTabName',
    tabBarPosition: 'bottom',
    tabBarComponent: TabBarBottom,
    animationEnabled: true,
    tabBarOptions: {
      showLabel: false,
      showIcon: true,
      style: {
        height: 54,
        backgroundColor: '#f5f5f5'
      },
      activeTintColor: activeTintColor
    }
  }
);
```

**Comment by michbil** [comment] 2017-11-21 20:53
The problem seems to be localized in this region of TabBarBottom.js:
```
const useHorizontalTabs = majorVersion >= 11 && isIos;
```
that's why it reproducable only in ios11,
when useHorizontalTabs is set, this code
```
 <TabBarIcon
        position={position}
        navigation={navigation}
        activeTintColor={activeTintColor}
        inactiveTintColor={inactiveTintColor}
        renderIcon={renderIcon}
        scene={scene}
        style={showLabel && useHorizontalTabs ? {} : styles.icon}
      />
``` 
initializes TabBarIcon with empty style and we have everything skewed.

**Comment by albinekb** [comment] 2017-11-22 10:59
Nice find @michbil 👍 Please tell me if there's anything I can do to help, investigating this or sending a PR 🙏

**Comment by michbil** [comment] 2017-11-22 11:49
@albinekb After some research, it seems to be bug was introduced in [#2676](https://github.com/react-community/react-navigation/pull/2676), i have idea how to fix it. Will run all required checks and will prepare PR.

**Comment by michbil** [comment] 2017-11-22 23:16
Okay, problem seems to be little more complicated than I initially thought. Need some thought to propose good solution. Its more coincidence, that bug is reproducible only in iOS 11, in many cases, TabBar display not perfect on older iOS version too.
To summarize cases when the problem appears:
1. Your icon doesn't have proper style height set. Remedy - check and fix your icon height
2. You are using custom tabBarLabel **component**.  If your tabBarLabel is a component, original tabBarLabel is replaced with your component, so we have style problems and you lose animation as well.
Code of tabBarBottom responsible for the label display
```
if (typeof label === 'string') {
      return (
        <Animated.Text
          style={[styles.label, { color, marginLeft, marginTop }, labelStyle]}
          allowFontScaling={allowFontScaling}
        >
          {label}
        </Animated.Text>
      );
    }

    if (typeof label === 'function') { // if you passed component, Animated will be replaced.
      return label({ ...scene, tintColor });
    }
```
So if you are overriding tabBarLabel as component, think twice, in most cases it's sufficient to override labelStyle in TabNavigator options and pass tabBarLabel as string

**Comment by PeterLocas** [comment] 2017-11-23 02:14
@gomdolkim you method only works for ios ,android Deson t work

**Comment by Aaaaaaaty** [comment] 2017-11-27 03:26
I find that when we use ```useHorizontalTabs``` to distinguish between ios11 and other versions, ``` const LABEL_TOP_MARGIN = 15;```in [L150](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L150) and ```icon: {
    flexGrow: 1,
  }```in [L272](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L272) will be respectively in these two places(L150,L272). If we set ```LABEL_TOP_MARGIN = 0``` and delete``` flexGrow = 1```, the effect will be the same in any versions. Likes below picture:
![image](https://user-images.githubusercontent.com/15126694/33249438-1bbe1294-d2f0-11e7-8560-ebdfc3539f9d.png)

 So I don't understand What is the ```useHorizontalTabs``` meaning for or Why we want to distinguish ios11. Is there someone can give me a explanation.

**Comment by michbil** [comment] 2017-11-27 06:49
useHorizontalTabs is used for this: 
![image](https://user-images.githubusercontent.com/1105429/31591574-84e1fb8a-b1e6-11e7-8df2-a3e74b3d3eaf.gif)

**Comment by Aaaaaaaty** [comment] 2017-11-27 07:49
@michbil So what is the different ios11 and other versions by using ```useHorizontalTabs```? Because I think the bug is from ```useHorizontalTabs```

**Comment by michbil** [comment] 2017-11-27 08:07
@Aaaaaaaty I tried to fix code, but stock code gives best result. Problem most likely with your icon style or your label style. Just follow the rules from my post 4 days ago and you will be fine.

**Comment by Aaaaaaaty** [comment] 2017-11-27 10:17
@michbil Okay, except ```useHorizontalTabs```,  I also have some questions about ```icon: {
    flexGrow: 1,
  }```in [L272](https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js#L272). When I delete that, icon will go to the bottom in any versions like the picture I placed before. This result is also decided by ```useHorizontalTabs```. These problem happening without setting my own icon or label style.

**Comment by ahmetcetin** [comment] 2017-11-29 10:57
in iPhoneX, icon and text is not vertically centered, here is the screenshot:

![](https://user-images.githubusercontent.com/5046786/33370778-d615725e-d4f8-11e7-9091-a69767854ae7.png)

I close the issue #3055 on favor of this one, as suggested by @keiset.

**Comment by albinekb** [comment] 2017-11-29 11:44
@ahmetcetin looks like your left icon is taller than the right?

**Comment by ahmetcetin** [comment] 2017-11-29 11:48
@albinekb not really, they are 'open-book' and 'area-graph' icons from Entypo. (https://oblador.github.io/react-native-vector-icons/)

**Comment by spencercarli** [comment] 2017-12-01 20:28
It's possible icons can be different heights - make sure you specify the height on your icon.

**Comment by qinfensky** [comment] 2017-12-04 16:07
I met this problem at iOS 11, and the other versions were normal. I want to know what's the reason, the version is v1.0.0-beta.21. Passing developers, what are your plans?

**Comment by shobhakartiwari** [comment] 2018-01-13 07:07
I face similar issue in iOS 11.2 and finally used this and issue **Resolved**  

> TabIcon along with Label

 static navigationOptions = {
        title: 'Settings',
        tabBarIcon: ({ focused, tintColor }) =>
            <Image source={focused ? require('../../assets/menu/settings_on.png') : require('../../assets/menu/settings.png')} />
};

**Comment by nagusampath** [comment] 2018-01-29 07:40
![screenshot_20180127-121904](https://user-images.githubusercontent.com/34878486/35498742-836247d0-04f5-11e8-9b46-4e20886082eb.png)
tab navigator is overlapping in the screen.

**Closed** 2018-02-07 21:17 UTC
Labels: bug

**Comment by ravirajn22** [comment] 2018-03-07 12:52
There is a prop called `adaptive` (from v1.0.0-beta.31) in TabBarBottom, which defaults to `true` on iOS >= 11. This `adaptive` prop is used to determine if u want horizontal mode, i.e Tab label and icon side by side instead of one over the other. Set this prop to `false` in your tabBarOptions. This should make your tab consistent with all version of iOS. I think we better remove that horizontal mode (Cause of this bug) feature from this library until other important common issues are fixed. Also how come this prop never appear in this doc?.

**Comment by brentvatne** [comment] 2018-03-09 19:26
@ravirajn22 - can you create a new issue that follows the issue template and describes this problem in detail? the issue described here is very old, so I'm going to lock it
