### ISSUE TITLE
prevent android back button closes keyboard and perform navigate/back

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#3347] opened 2018-01-24 08:38 UTC
When keyboard is open/visible clicking on back button close/hide the keyboard and not navigating back

### Current Behavior
I am using the code from #1349 by @mbret.

I tried 2 approaches:

1. listen to `hardwareBackPress` event - but it does not fire

2. use `onBlur` callback - I hoped it will be called when the keyboard is not visible, i.e the textInput is out of focus.

I want to avoid using keyboard `keyboardDidHide` event 

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | 0.52
| node             | 8.9.3
| yarn      | 1.3.2

**Comment by mbret** [comment] 2018-01-24 09:34
This is not a bug and is the expected behavior from back press when keyboard is opened on Android. This has nothing to do with react-navigation.

If you want to go back whenever you press back to hide the keyboard I'm not sure you can do that with react-native. You will probably need to use native code.

But again I would advise you to not do that and respect some Android standards.

**Comment by kelset** [comment] 2018-01-24 09:51
Closing since @mbret answered properly.

**Closed by kelset** 2018-01-24 09:51 UTC
