### ISSUE TITLE
Black screen is cased by push/pop

### ISSUE THREAD

**Issue by musicode** [react-navigation/react-navigation#3426] opened 2018-02-04 10:59 UTC
react-native: 0.52.0

react-navigation: 1.0.0-beta.29

![image](https://user-images.githubusercontent.com/2732303/35776760-6adce642-09dd-11e8-8685-8f852f346483.png)

**Comment by musicode** [comment] 2018-02-04 10:59
![image](https://user-images.githubusercontent.com/2732303/35776770-8dc71c72-09dd-11e8-836b-6f834c4db7e3.png)

**Comment by kelset** [comment] 2018-02-04 12:05
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-02-04 12:05 UTC

**Comment by musicode** [comment] 2018-02-05 12:36
1. yes
2. iOS, I dont know how about android
3. both
4. no
5. I found that when i push and pop quickly, it will happen.
