### ISSUE TITLE
Button can't press again in the header

### ISSUE THREAD

**Issue by javahuang** [react-navigation/react-navigation#3441] opened 2018-02-06 08:14 UTC
### Current Behavior

``` js
const MainNavigator = StackNavigator(
  {
    HomeNavigator: { screen: Home },
    Camera: { screen: Camera},
  },
  {
    headerMode: 'float',
    navigationOptions: {
      gesturesEnabled: true,
    },
  }
)

class Home extends Component {
  static navigationOptions = ({ navigation }) => {
    const { navigate } = navigation
    return {
      title: 'Meeting',
      headerRight:
        <TouchableOpacity onPress={() => navigate('Camera')}><Image
          style={{ width: 26, height: 26, marginRight: 20 }}
          source={require('../images/qr-scanner.png')}
        /></TouchableOpacity>,
      tabBarIcon: ({ focused, tintColor }) => (
```
![jietu20180206-161358 2x](https://user-images.githubusercontent.com/3992393/35848349-cca67a06-0b58-11e8-8f54-68a6b67adf2d.jpg)

I press the headRight to the Camera the first time,then i back to the Home with the gesture,and i can't press the headRight again.But if i back to the Home with the back button, it works.

### Expected Behavior

press the headerRight to the Camera every time with the gesture

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | react-navigation@1.0.0-beta.29
| react-native     | react-native@0.52.0
| node             | 8.9.0
| npm or yarn      | 4.6.1

**Comment by kelset** [comment] 2018-02-06 08:36
Duplicate of https://github.com/react-navigation/react-navigation/issues/3423

**Closed by kelset** 2018-02-06 08:36 UTC
