### ISSUE TITLE
Dynamic nested TabNavigator: cannot read property 'foreach' of undefined

### ISSUE THREAD

**Issue by raarts** [react-navigation/react-navigation#3598] opened 2018-02-25 09:05 UTC
### Current Behavior

This probably is a feature request.

Swapping out a nested tabnavigator for another one on the fly does not work, and results in:

(And I'm still not well-versed enough in React Navigation to create a PR for this..)

```
react-dom.development.js?cada:8305 The above error occurred in the <withCachedChildNavigation(TabView)> component:
    in withCachedChildNavigation(TabView) (at TabNavigator.js:34)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at WebMainTabNavigator.js:33)
    in AppRootTabNavigator (at SceneView.js:17)
    in SceneView (at ResourceSavingSceneView.js:62)
    in div (created by View)
    in View (at ResourceSavingSceneView.js:55)
    in div (created by View)
    in View (at ResourceSavingSceneView.js:46)
    in ResourceSavingSceneView (at TabView.js:32)
    in div (created by View)
    in View (at TabViewPagerPan.js:251)
    in div (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent (at TabViewPagerPan.js:238)
```

### Expected Behavior

I need it to work.

### How to reproduce

https://snack.expo.io/@raarts/cannot-read-property-'foreach'-of-undefined

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.2
| react-native     | 0.52.0
| node             | 8.9.4
| npm or yarn      | 1.3.2

**Comment by Tommos0** [comment] 2018-03-07 13:04
I have the same issue:
https://snack.expo.io/S1XkMPTOf

It happens when a Navigator gets passed the `navigator` prop from a parent element that got this passed because it is a screen of a parent Navigator.
e.g.
```
screen: SubNav /> // OK
screen: (props) => <SubNav navigation={props.navigation} /> // Crash
```

**Comment by Tommos0** [comment] 2018-03-07 13:37
I do needs this kind of behaviour. The situation is that my SubNav is not a direct child of MainNav, eg.
```
MainNav
--|View
--|--|Header
--|--|SubNav
```
I'm gonna solve the problem by having seperate Navigators, each with its own state. It will however complicate navigation from/to different components in my app (as the right `navigation` object will have to be used).

**Comment by Tommos0** [comment] 2018-03-07 13:56
Mentions of same:
https://github.com/react-navigation/react-navigation/issues/335#issuecomment-290226709
https://github.com/react-navigation/react-navigation/issues/90
https://stackoverflow.com/questions/47848999/redux-with-react-navigation-nested-navigators-typeerror-undefined-is-not-an-ob

**Comment by xanderberkein** [comment] 2018-03-12 15:35
Bumped into the same issue. Like Tommos0 said, passing the navigation prop manually results in this error.
I can't to solve this by using separate Navigators with its own state, since my child navigator needs the `navigation` of its parent to know if it is focussed or not.

**Comment by Tommos0** [comment] 2018-03-15 10:47
@xanderberkein does it also crash if you pass the navigator under a differently named property? If you just need the child to have access to the parents `navigation`, this might work for your situation.
Eg.
```javascript
screen: (props) => <ChildNav nav={props.navigation} />
//instead of
screen: (props) => <ChildNav navigation={props.navigation} />
```

**Comment by xanderberkein** [comment] 2018-03-15 10:59
@Tommos0 That was indeed how I solved my problem at first. However, the child screen needs this navigation prop as `navigation` to know if it is focused or not.

Please see my snack to make it more clear:
https://snack.expo.io/@x11n/listeners-in-nested-navigators

If you uncomment line 73 and comment line 72, everything works just fine. When you change tabs and go back to the first tab, the StackScreen inside the tab knows it is being focussed (as you can see in the logs). In my app, I need a screen in between the two navigators though.
If you uncomment line 77 now, with your proposed solution, you will notice that Stack1 and Stack2 don't realize they lose and regain focus when you switch tabs.

**Comment by jdeanwaite** [comment] 2018-03-22 01:03
I am experiencing this issue as well. In order to allow my app to navigate freely from nested pages to any other page, I need to pass in the navigation prop to my tab navigator. 

```
MainStack
    - Page1
        - View
            - Tabs 
                - Tab
                    - ATabbedPage (this is where the problem lies when passing in navigation to individual pages.)
                        - SubView1
    - Page2
        - SubView2
```

I want to be able to navigate from SubView1 to Subview2. Without the ability to pass the `navigation` prop to the

**Comment by Tommos0** [comment] 2018-03-23 10:54
After going through the code a little bit, I think I have it figured out. There are two types of `navigation` props with a different form of `state`.
First one gets passed if the child (screen) is itself a `Navigation` object:
```javascript
state: { 
  key: 'StackRouterRoot',
  isTransitioning: false,
  index: 0,
  routes: [ [Object] ] 
}
```
If the child is a React Component it gets passed this as state:
```javascript
state: {
  routeName: 'Home',
  key: 'id-0-0'
}
```
Since there is no `routes` in the second case, we get an Error when trying to iterate over it.

I think the solution is to make your React component a Navigator by giving it the `router` prop of its child Navigator. To transform my example before:
Bad:
```javascript
...
screen: (props) => <ChildNav navigation={props.navigation} />
...
```
Good:
```javascript
const screenWithNav = (props) => <ChildNav navigation={props.navigation} />;
screenWithNav.router = ChildNav.router;
...
screen: screenWithNav
...
```
Perhaps a warning can be added if someone attempts to do what we did, since it appears to be confusing to several people.

**Comment by i2chris** [comment] 2018-03-25 00:31
How would you do a similar thing in this situation?

```
  render() {
    return <ProjectTabs navigation={this.props.navigation} screenProps={{ project, samples }} />
  } 
```
Where ProjectTabs is a TabNavigator({..})

Thanks

**Comment by ericvicenti** [comment] 2018-03-25 14:39
Hey folks, really sorry that we haven't documented this well so far. When you render one navigator inside another, without exposing the router, the navigators will not know how to talk to each-other.

@brentvatne has written up a doc that explains what the problem is: https://v2.reactnavigation.org/docs/common-mistakes.html#explicitly-rendering-more-than-one-navigator

You can also see more details about custom navigators here: https://v2.reactnavigation.org/docs/custom-navigators.html#extending-navigators

These docs will be released as part of the upcoming v2 launch

We have some warnings coming up that will hopefully make this more clear: 
https://github.com/react-navigation/react-navigation/pull/3819
https://github.com/react-navigation/react-navigation/pull/3823

**Closed by ericvicenti** 2018-03-25 14:39 UTC
