### ISSUE TITLE
React Navigation Tabs not Clickable with absolute position

### ISSUE THREAD

**Issue by toeurtenh** [react-navigation/react-navigation#5994] opened 2019-06-11 13:34 UTC
I have made navigation bottom tab background color transparent by adding 

    tabBarOptions: {
      style: {
        backgroundColor: 'rgba(0, 0, 0, 0.7)', // TabBar background
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
      }
    }

but when I click on other tabs it doesn't work but when I remove abosolute from position it works but the background is not transparent.

and ideas? please help

**Comment by mujavidb** [comment] 2019-06-11 16:18
I've having this same issue in version `3.11.0`.

**Comment by toeurtenh** [comment] 2019-06-12 08:04
@mujavidb have you solved?

**Comment by mujavidb** [comment] 2019-06-12 10:14
@toeurtenh I reverted library back to `3.0.9` for now.

**Comment by kpratik2015** [comment] 2019-06-15 18:06
> @toeurtenh I reverted library back to `3.0.9` for now.

This worked for me. I wonder what made it break but for some reason I didn't notice this until after I made the apk.

**Comment by mujavidb** [comment] 2019-06-16 09:23
It seems to be android only. Navigation in iOS works fine.

**Comment by toeurtenh** [comment] 2019-06-18 15:56
have still not figured it out

**Comment by matthamil** [comment] 2019-06-20 14:19
Thanks for this issue @toeurtenh , and thank you for the code snippet.

Can you provide a reproducible example as a [Snack](https://snack.expo.io/) or in a public repo? Something one of the maintainers can use w/o bootstrapping a new React Native app

**Comment by mujavidb** [comment] 2019-06-21 19:58
@matthamil I made [a snack here](https://snack.expo.io/@sequiter/navigation-problem-example). Run on Android to see issue.

**Comment by toeurtenh** [comment] 2019-06-24 07:42
@matthamil sorry I don't use snack. @mujavidb thank you for making the snack, hope we get a solution from maintainer.

**Comment by r3dwc** [comment] 2019-07-04 02:49
I met the same issue. Has someone solved this problem?

**Comment by ethanyuwang** [comment] 2019-07-24 01:29
have the same issue here

**Comment by learnyst** [comment] 2019-07-24 08:46
have same issue, any solutions?

**Comment by kartikpr** [comment] 2019-07-24 11:44
Same issue here lads , any solutions would be appreciated

**Comment by ethanyuwang** [comment] 2019-07-24 17:43
I have also tried 3.0.9. The problem still exists.

**Comment by neonsec** [comment] 2019-08-01 00:55
@mujavidb  rolling back to 3.0.1 also worked for me! looks like this issue is still not resolved yet.

**Comment by mcmar** [comment] 2019-08-15 20:07
Not sure what's going on here or why comments are being mysteriously deleted. Does anyone know anything about when this will be fixed?

**Comment by mcmar** [comment] 2019-08-15 20:39
It's not this repo. It's `react-navigation/tabs` and this is the commit that broke it:
https://github.com/react-navigation/tabs/commit/2a1d7538d65e79b90c572cf078d0534e1cacc13d#diff-a8d6ae7794fbc09aaea535c1c7103754

**Comment by mcmar** [comment] 2019-08-15 20:43
Best option is to add a `containerStyle` prop to `react-navigation-tabs`. Then add `position: 'absolute', zIndex: 1` to `containerStyle`

**Comment by mcmar** [comment] 2019-08-15 21:00
@satya164 Fix implemented in this PR https://github.com/react-navigation/tabs/pull/154

**Comment by mcmar** [comment] 2019-08-15 21:38
Until this gets merged and published, feel free to use my fork https://www.npmjs.com/package/@mcmar/react-navigation-tabs
```
import { createBottomTabNavigator } from '@mcmar/react-navigation-tabs';
```

**Comment by ntkzwane** [comment] 2019-08-16 17:24
> Best option is to add a `containerStyle` prop to `react-navigation-tabs`. Then add `position: 'absolute', zIndex: 1` to `containerStyle`

This worked for me! Thanks!! Just one thing to not in case someone else falls into the same trap, if you add these styles to the `react-navigation-tabs`, then remove the `absolute` position on `tabBarOptions.style.position`.

**Comment by matthamil** [comment] 2019-08-17 17:01
> Not sure what's going on here or why comments are being mysteriously deleted. Does anyone know anything about when this will be fixed?

Comments like "+1" and "I am also experiencing this" were removed since they only add noise to GitHub issues.

**Comment by MackHatfield** [comment] 2019-08-21 23:39
I was able to remedy this by making sure to specify width in the style object of tabBarOptions. I realized after throwing a border around the tabs that it had any empty width so it would make since that it wasn't touchable.
```
    tabBarOptions: {
      activeTintColor: '#FFFFFF',
      inactiveTintColor: '#F8F8F8',
      style: {
        width: '100%',
        position: 'absolute',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        marginTop: EStyleSheet.value('5.25rem'),
        borderWidth: 1,
        borderColor: 'red'
      },
    }

**Comment by zubko** [comment] 2019-11-11 10:14
Another temporary solution would be to use https://www.npmjs.com/package/patch-package and to apply the fix in the source code of react-navigation/tabs while the PR isn't accepted.

**Comment by satya164** [comment] 2019-11-18 00:19
It's already fixed with latest tabs https://github.com/react-navigation/tabs/releases/tag/v2.5.6

**Closed by satya164** 2019-11-18 00:19 UTC
Labels: component: Tabs

**Comment by ShuKTan** [comment] 2019-11-25 20:44
@satya164 Its not working.

I am using 
"react-navigation-tabs": "^2.6.0",
"react": "16.8.6",
"react-native": "0.60.5",

**Comment by muzhaqi16** [comment] 2022-02-25 21:39
I am currently facing the same issue with "react-navigation/bottom-tabs": "^6.2.0",
