### ISSUE TITLE
On navigating to an existing screen in stack, using navigation.navigate or goBack, results in a blank screen

### ISSUE THREAD

**Issue by paul-apacio** [react-navigation/react-navigation#7938] opened 2020-04-02 16:53 UTC
**On navigating to an existing screen in stack, using navigation.navigate or goBack, results in a blank screen**

`...<NavigationContainer>
     <Stack.Navigator headerMode='none' screenOptions={{gestureEnabled: true, lazy: false, swipeEnabled: true}}>
       <Stack.Screen name="Loading" component={Loading} />
       <Stack.Screen name="MainPage" component={MainPage} />
       <Stack.Screen name="Login" component={Login} />
       <Stack.Screen name="SignUp" component={SignUp} />
       <Stack.Screen name="CreateCollectible" component={CreateCollectible} />
       <Stack.Screen name="TestPage" component={TestPage} />
     </Stack.Navigator>
   </NavigationContainer>...`
`...<Button transparent onPress={()=>{console.log("Going back");navigation.goBack()}}>
            <Icon name='arrow-back' />
          </Button>...`
- Include a screenshot or video if it makes sense.

**On navigating to an existing screen in stack, using navigate or goBack, the old screen or previous screen is visible**

- Normal backward navigating is expected

**How to reproduce**

Very simple to reproduce. A stackNavigator with more than one page. Use goBack or navigation.navigate(previous page) on a live Android 10 device.

Note: this only occurs when you use those functions. Using the gesture back, the default back action in the header, or the device back button or native gesture works fine.

**How to temporarily fix**

setting animationEnabled to false in screenOptions circumvents the issue, but obviously loses the function, or turn off gestures helps, but circumvents that feature.

`<Stack.Navigator headerMode='none' screenOptions={{gestureEnabled: true, lazy: false, swipeEnabled: true, animationEnabled: false}}>`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 |10|
| @react-navigation/native       |latest|
| @react-navigation/stack        |latest|
| react-native-gesture-handler   |latest|
| react-native-safe-area-context |latest|
| react-native-screens           |latest|
| react-native                   |latest|
| node                           |latest|
| npm or yarn                    |latest|

**Comment by jefersonjuliani** [comment] 2020-04-03 21:04
It's because "gestureEnabled: true".... I have the same issue

**Comment by sshapoval** [comment] 2020-04-06 09:51
Yep, I have the same issue

**Comment by paul-apacio** [comment] 2020-04-06 15:39
Ah, you're right. Animations are fine, turning off gestures it works.

**Comment by nicolaelia** [comment] 2020-04-15 07:32
Possibile duplicate of #7848 .
Had the same issue and setting `gestureEnabled: false` solved it.

**Comment by satya164** [comment] 2020-04-16 22:35
Please don't use "latest" as version in the issue template and use actual version.

**Comment by durdevic** [comment] 2020-04-18 15:55
Hi @satya164, 

I'm also posting this here for easier access.

On expo it works, but if you put the same code on clean npx project and run it on device, it creates the same error. Here is the zip you can test it and a video with behaviour I get on my device

You can clone this one to test it
https://github.com/durdevic/navitest

Video: 
![navitest](https://user-images.githubusercontent.com/2753836/79642160-34446400-819c-11ea-987b-a3fe4c52d899.gif)

Expo with the case here: 
https://snack.expo.io/@ukiand1/react-navigation-5---android-goback()-bug

**Comment by IkeLutra** [comment] 2020-04-20 09:49
I have narrowed it to these versions of `react-navigation-stack` which correspond to these versions of `@react-navigation/stack`.

**Good**
`react-navigation-stack` : `v2.0.16`
`@react-navigation/stack` : `^5.0.0-alpha.62`

**Bad**
`react-navigation-stack` : `v2.1.0`
`@react-navigation/stack` : `^5.0.0-alpha.66`

**Comment by JakubPod** [comment] 2020-04-21 08:55
I have the same issue. navigation.goBack() results in the blank screen while gestureEnabled is true. Here's my simple workaround:
`  const _onPress = () => {
        navigation.setOptions({ gestureEnabled: false });
        setTimeout(() => {
            onPress();
        }, 0);
    };`
It allows using the gesture and animation on screen as well as closing the screen using a goBack method.

**Comment by drager** [comment] 2020-04-21 13:51
Having the same issue. Gets a blank screen if I double tap on a header button that calls `navigation.goBack()` on Android. Works fine on iOS. Have all the latest versions of all packages.

**Comment by svengiebel** [comment] 2020-04-21 14:13
@JakubPod thx for sharing a workaround!  👍

**Closed** 2020-04-22 13:18 UTC
Labels: bug, needs more info, package:stack
