### ISSUE TITLE
Android left header text unexpectedly renders with different font size on different devices

### ISSUE THREAD

**Issue by lukewlms** [react-navigation/react-navigation#3142] opened 2017-12-16 22:19 UTC
### Current Behavior

In emulator, the Android back arrows shows correctly.  On my Samsung Galaxy Tab S2, they don't render at all!  No special code here - just standard StackNavigator, the back button is added automatically.

Works correctly in Pixel emulator:
![image](https://user-images.githubusercontent.com/19214773/34074764-21b3e9dc-e284-11e7-8e85-3088458dab6b.png)

But back button is totally missing on Galaxy Tab:
![image](https://user-images.githubusercontent.com/19214773/34074777-91e89b9e-e284-11e7-9145-015aaed8b4c8.png)

Similarly, my X close button (just using unicode X character) looks good on emulator:

![image](https://user-images.githubusercontent.com/19214773/34074779-a9417996-e284-11e7-8135-917482da9cd7.png)

But for some reason is tiny on the Galaxy Tab:

![image](https://user-images.githubusercontent.com/19214773/34074784-b83dce18-e284-11e7-9af3-e941b3bcb9b8.png)

For the latter, here's my code (as noted, the Back button missing has no associated component code b/c the back button is generated automatically).

```
// ...
      headerLeft: (
        <HeaderButton onPress={dismissStack} text="✕" />
      ),
// ...

export const HeaderButton = (props: IHeaderButtonProps) => {
  return (
    <TouchableOpacity
      {...props}
      style={{
        height: 44,
        justifyContent: "center",
      }}
    >
      <Text
        style={{
          fontSize: 17,
          paddingHorizontal: 10,
          color: props.disabled ? "gray" : "black",
          ...props.textStyle,
        }}
      >
        {props.text}
      </Text>
    </TouchableOpacity>
  );
};

```

### Expected Behavior
- Back buttons should appear for all Android screens where goBack is possible.
- Left Header should display at same size relative to header text on all Android devices

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |     v1.0.0-beta.17
| react-native     |     0.49.5
| node             | 8.9.0
| npm or yarn      | 1.3.2

Thank you!

**Comment by carsonwah** [comment] 2017-12-17 12:05
I have also had some experience on the disappearing of back button before. I tried to look into the source code but could not find any code importing the Android back icon. Would like to investigate more once I know the logic.

[HeaderBackButton.js](https://github.com/react-community/react-navigation/blob/363f93fc4d449f180dca05079b13a27c274fdd0a/src/views/Header/HeaderBackButton.js#L70)
[Back button pngs](https://github.com/react-community/react-navigation/tree/363f93fc4d449f180dca05079b13a27c274fdd0a/src/views/assets)

-----

For the close button, you are using Text and fontSize to define the button. On different devices, the style of the text seems to behave differently, which is unexpected. 

This inconsistency happens on different versions of Android. Here is my test on genymotion simulator. Hope this help someone to investigate more.

Code: https://snack.expo.io/HyHXDRXff

![demo](https://user-images.githubusercontent.com/25053707/34079269-8ceaeeda-e365-11e7-81c8-e09b40151b4d.png)

**Comment by kelset** [comment] 2017-12-17 15:23
Duplicate of https://github.com/react-community/react-navigation/issues/2918
Please move your comments over there to reduce redundancy

**Comment by carsonwah** [comment] 2017-12-17 20:42
@kelset I think the second part of this issue is not related to #2918 . It's about some inconsistencies on Android for rendering custom components in header.

**Comment by kelset** [comment] 2017-12-17 23:39
Oh ok gotcha, I'll reopen this.

**Comment by lukewlms** [comment] 2017-12-18 16:54
For now we're working around this by using an Ionicon from RN Vector Icons, rather than the square Unicode X character.  The Ionicon renders at the same size across devices, unlike the character.

**Comment by carsonwah** [comment] 2017-12-18 17:55
@lukewlms What is the Android version of your Galaxy Tab S2? This should help investigating why the character looks different.

**Comment by lukewlms** [comment] 2017-12-18 20:11
7.0 on that device.

**Comment by brentvatne** [comment] 2018-02-23 23:12
as far as I can tell this isn't an issue with react-navigation. if the font size is changing between devices then that is more of a concern with react-native itself. does anyone have more info here? i'm going to close this but please create a new issue if it turns out to be related to react-navigation.

**Closed by brentvatne** 2018-02-23 23:12 UTC
Labels: bug, component: Stack
