### ISSUE TITLE
[BUG] Build fails with syntax error in "material-top-tabs/src/index.tsx"

### ISSUE THREAD

**Issue by AbhiShrek** [react-navigation/react-navigation#8017] opened 2020-04-13 00:38 UTC
**Current Behavior**

In my react-native project, i added a small test code the way it mentioned in [material-top-tab-navigator docs](https://reactnavigation.org/docs/material-top-tab-navigator)

But the build fails with the following error :

![Screenshot 2020-04-13 at 5 54 55 AM](https://user-images.githubusercontent.com/11253347/79083365-82480a80-7d4b-11ea-823a-d7b4e8033861.png)

- What code are you running and what is happening?
```
import React, { Component } from 'react';
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
import SettingsScreen from './SettingsScreen'
import SearchScreen from './SearchScreen'

const Tab = createMaterialTopTabNavigator();

export default class MyListsScreen extends Component {
    constructor(props) {
        super(props);
    }
 
    render() {
        return (
            <Tab.Navigator>
                <Tab.Screen name="Home"     component={SearchScreen} />
                <Tab.Screen name="Settings" component={SettingsScreen} />
            </Tab.Navigator>
        )
    }
}

```

**Expected Behavior**
Build passes !!

**How to reproduce**

This [example](https://snack.expo.io/?platform=android&name=Tab%20navigation%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fnative%40%5E5.1.3%2C%40react-navigation%2Fbottom-tabs%40%5E5.2.4%2C%40react-navigation%2Fdrawer%40%5E5.3.4%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.1.6%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.1.6%2C%40react-navigation%2Fstack%40%5E5.2.6%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E0.7.3%2Creact-native-screens%40%5E2.4.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fmaterial-top-tab-based-navigation-minimal.js), given in docs page itself fails

![Screenshot 2020-04-13 at 6 07 46 AM](https://user-images.githubusercontent.com/11253347/79083628-1cf51900-7d4d-11ea-9dae-cdc04ded1838.png)

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | iOS
| @react-navigation/native            | 5.1.5
| @react-navigation/material-top-tabs | 5.1.8
| react-native-tab-view               | 2.14.0
| react-native                        | 0.62.2
| expo                                | ---
| node                                | 13.12.0
| npm                          | 6.14.4
| yarn                           | 1.22.4

**Comment by sacrarat** [comment] 2020-04-13 06:23
Bump. Having the exact issue when trying to run the Drawer Navigator in Android. Builds successfully on web.

![image](https://user-images.githubusercontent.com/26276250/79097031-4df73d00-7d91-11ea-84c6-244fa3960604.png)

**Comment by sacrarat** [comment] 2020-04-13 11:35
Was able to solve my issues my deleting my node modules, package lock and then re installing all the react navigation libraries making sure to update to the latest versions.

**Comment by saasha10** [comment] 2020-04-13 14:04
I have the same problem...

I just using NavigationContainer 

`   7 | export { default as StackRouter, StackActions } from './StackRouter';
   8 |
>  9 | export type {
     |             ^
  10 |   StackActionHelpers,
  11 |   StackActionType,
  12 |   StackRouterOptions,`

**Comment by satya164** [comment] 2020-04-13 14:09
Duplicate of #7978

Solution https://github.com/react-navigation/react-navigation/issues/7978#issuecomment-610934738

**Closed by satya164** 2020-04-13 14:09 UTC
Labels: bug, package:material-top-tabs
