### ISSUE TITLE
Icon or Images color not change contentOptions  activeTintColor or  inactiveTintColor wont affect on icon/Images

### ISSUE THREAD

**Issue by nitin0331** [react-navigation/react-navigation#3301] opened 2018-01-18 12:56 UTC
Icon or Images color not change in drawer using contentOptions  activeTintColor or  inactiveTintColor. It wont affect on icon/Images and work properly with drawerLabel but now with drawerIcon
below is my sample code  i m also tried to styles with in  image { focused: false,tintColor: '#1999CE' },{ focused: true,tintColor: '#ffffff' } its also not working 
`  const AppDrawerNavigation = DrawerNavigator({

              Home: {
                screen: HomeScreen,
                 navigationOptions: {
                  drawerLabel: 'Home',
                  drawerIcon: () => (
                    <Image
                      source={require('./src/images/rocket.png')}
                      style={[{ focused: false,tintColor: '#1999CE' },{ focused: true,tintColor: '#ffffff' }]}
                    />
                  ),
                  }
              },
              WebViews: {
                screen: WebViewScreen,
              },
              UserList: {
                screen: UserListScreen,
              },
              SwipeCard: {
                screen: SwipeCardScreen,
               },
            },
            {
             navigationOptions: {
              headerMode: 'none'
            },
            drawerPosition: 'left',
            drawerWidth: 200,
            contentOptions: {
![device-2018-01-18-182527](https://user-images.githubusercontent.com/2297146/35099173-0993f23a-fc7d-11e7-8774-5011af4e1737.png)
![device-2018-01-18-182549](https://user-images.githubusercontent.com/2297146/35099175-09f68954-fc7d-11e7-8dc6-09006f735e73.png)

              activeTintColor :'#ffffff',
               inactiveTintColor :'#1999CE',
              activeBackgroundColor :'#1999CE',
              inactiveBackgroundColor :'#ffffff',
            }
          }

          );`

**Comment by kelset** [comment] 2018-01-18 13:59
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-18 13:59 UTC
