### ISSUE TITLE
It doesn't hide the drawer view with drawerPosition='right'

### ISSUE THREAD

**Issue by daminhtung** [react-navigation/react-navigation#8814] opened 2020-09-07 08:47 UTC
**Current Behavior**

```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { NavigationContainer, useNavigation, DrawerActions } from '@react-navigation/native';
import { createDrawerNavigator } from '@react-navigation/drawer'
import { createStackNavigator } from '@react-navigation/stack'

const { Navigator, Screen } = createStackNavigator()

export const Home: React.FC = () => {
  return (
    DrawerNav()
  )
}

export const Home1: React.FC = () => {
  const nav = useNavigation()
  const handleOnPress = () => {
    nav.dispatch(DrawerActions.toggleDrawer())
  }

  return (
    <View>
      <Text>Home 1</Text>
      <Button title='Toogle Drawer' onPress={handleOnPress} />
    </View>
  )
}

const Drawer = createDrawerNavigator()

export default function App() {

  return (
    <NavigationContainer>
      {Root()}
    </NavigationContainer>
  );
}

function DrawerNav() {
  return (
    <Drawer.Navigator openByDefault={true} drawerPosition='right' edgeWidth={100}>
      <Drawer.Screen name="Drawer" component={Home1} />
    </Drawer.Navigator>
  );
}

function Root() {
  return (
    <Navigator>
      <Screen
        key={'root'}
        name={'Root'}
        component={Home}
      />
    </Navigator>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```
- Video:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6220517/92367087-2cbc3200-f120-11ea-9c02-50bc7a222614.gif)

**Expected Behavior**

- It should hide the bottom scrollbar when the drawer closed (work like when set `drawerPosition='left'`)

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native   |  5.7.3
| @react-navigation/drawer  | 5.9.0
| react-native-reanimated     | 1.13.0
| react-native-gesture-handler   | 1.8.0
| react-native-safe-area-context | 3.1.7
| react-native-screens         | 2.10.1
| react-native                  | 0.62.2
| expo                          | 38.0.9
| node                           | 12.16.3
| npm or yarn                   | 1.22.4

**Comment by davelms** [comment] 2020-12-27 21:54
I'm seeing the same behaviour.

@react-navigation/native   5.8.10
@react-navigation/drawer  5.11.4

**Comment by raajnadar** [comment] 2021-03-13 16:20
Duplicate of #8415

**Closed by raajnadar** 2021-03-13 16:20 UTC
Labels: bug, package:drawer
