### ISSUE TITLE
Stack Screen bottom border radius

### ISSUE THREAD

**Issue by hevar** [react-navigation/react-navigation#10232] opened 2021-12-31 00:40 UTC
### Current behavior

When using Stack navigation within a Bottom tab navigation on IOS with `TransitionPresets.ModalPresentationIOS` there is a bottom border radius (as shown in the attached image below).

I'm guessing the issue is due to the card style interpolator:
[SOURCE](https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L166-L178)

It's understandable that the same border radius is applied to all corners for performance gains, and changing bottom border radius to 0 makes the animation quite clunky but so is the current behaviour. 

![Screenshot 2021-12-31 at 01 23 57](https://user-images.githubusercontent.com/9890748/147796150-3f6b54d4-0ff7-4763-bf32-c8bddfd560c4.png)
7

https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L166-L17

### Expected behavior

Render modal without border radius when used with bottom tab navigation.

### Reproduction

none.

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/drawer               | -
| @react-navigation/material-bottom-tabs | - 
| @react-navigation/material-top-tabs    | - 
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.2.0
| react-native-tab-view                  |  - 
| react-native-pager-view                | -
| react-native                           | 0.64.3
| expo                                   | 43.0.2
| node                                   | v16.9.1
| npm or yarn                            |  yarn 1.22.10

**Comment by vonovak** [comment] 2022-01-03 10:19
closing as duplicate of https://github.com/react-navigation/react-navigation/issues/9933

thank you :)

**Closed by vonovak** 2022-01-03 10:19 UTC
Labels: bug, package:stack, needs repro, platform:ios
