### ISSUE TITLE
BottomTabNavigator goes behind native Android navigation

### ISSUE THREAD

**Issue by sofianegargouri** [react-navigation/react-navigation#5976] opened 2019-06-04 13:45 UTC
### Current Behavior

![image](https://user-images.githubusercontent.com/4323986/58883924-b0969b80-86df-11e9-9866-5e0ec5fa549d.png)

### Expected Behavior

The BottomTabNavigator should be over the Android Navigation

![image](https://user-images.githubusercontent.com/4323986/58883787-6a413c80-86df-11e9-8566-60c19940ee16.png)

### How to reproduce

- Just create a BottomTabNavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.4.1
| react-native     | 0.59.8
| node             | 11.12.0
| yarn      | 1.15.2

**Comment by vonovak** [comment] 2019-06-04 22:26
> Just create a BottomTabNavigator

hi @sofianegargouri, this is not a runnable repro, please follow the issue template and provide a runnable repro, eg. in https://snack.expo.io/

thank you!

**Comment by sofianegargouri** [comment] 2019-06-05 09:00
Well,  can't reproduce it on Snack unfortunately. Just figured out it only happens on some devices

**Comment by vonovak** [comment] 2019-06-05 10:03
@sofianegargouri in that case we'll need the code that makes this happen and some list of devices / emulators that reproduce this - otherwise this is hard to fix from our side. Thanks.

**Comment by satya164** [comment] 2019-06-05 10:46
In vanilla RN apps, content is not drawn behind the navigation bar. You have to enable it explicitly with `android:fitsSystemWindows` and `android:windowTranslucentNavigation`.

When you're drawing content behind the navigation bar, it's not possible for us to detect it since React Native doesn't expose any APIs for it. You need to ensure that your content has appropriate padding manually, for example, for bottom bar:

```
barStyle: { paddingBottom: 48 }
```

Closing since this happens because of your theme code of the app and not a bug in react navigation.

**Closed by satya164** 2019-06-05 10:46 UTC
Labels: needs repro

**Comment by eriodesign** [comment] 2019-12-17 15:51
open  **android/app/src/main/res/values/styles.xml**
remove **<item name="android:windowTranslucentNavigation">true</item>**

**Comment by eriodesign** [comment] 2019-12-17 15:52
open **android/app/src/main/res/values/styles.xml**
remove `<item name="android:windowTranslucentNavigation">true</item>`
