### ISSUE TITLE
Keyboard hides immediately after clicking on TextInput

### ISSUE THREAD

**Issue by petrkrejcik** [react-navigation/react-navigation#8462] opened 2020-06-17 07:15 UTC
**Current Behavior**

I have two screens with _Stack navigator_ and an _InputText_ on the second screen. When I navigate on the second screen and focus the input the keyboard disappears immediately.

Video: https://drive.google.com/file/d/1Tsk6U6_SzVLT9SLI3wcYF36e55Xz8kZg/view?usp=sharing

**Expected Behavior**

The keyboard should stay opened after focus.

**How to reproduce**

https://snack.expo.io/@soincon/keyboard-blur-example

**Your Environment**

See the snack.

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 8
| @react-navigation/native                 | 5.5.1
| react-native                   | 37.0.1

**Comment by raajnadar** [comment] 2020-06-17 08:00
Duplicate of https://github.com/react-navigation/react-navigation/issues/8414

**Closed by raajnadar** 2020-06-17 08:00 UTC
Labels: bug, package:stack

**Comment by atakanbayil** [comment] 2023-09-08 08:23
"@react-navigation/native-stack": "^6.9.13",    "@react-navigation/material-top-tabs": "^6.6.3", stil persists. I have 5 screens text input at the middle If I change one left or one right then I move middle screen and focus text input keyboard comes up and closes immediately as in milliseconds. I tried so many things but couldn't come up with any solutions. Interesting side of problem if I move to leftmost or rightmost screen then move to the middle screen it focuses the text input and keyboard does not close. please help !!
