### ISSUE TITLE
Attempted import error: 'shouldUseActivityState' is not exported from 'react-native-screens'.

### ISSUE THREAD

**Issue by Albert-Gao** [react-navigation/react-navigation#8993] opened 2020-10-27 05:05 UTC
After upgrading to 

```bash
    "@react-navigation/bottom-tabs": "^5.9.2",
    "@react-navigation/drawer": "^5.9.3",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
```

There are warnings after building, for an expo managed flow SDK 39, env setup are as below:

```bash
    "expo-cli": "^3.28.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.0.tar.gz",
    "react-native-screens": "~2.10.1",
```

![image](https://user-images.githubusercontent.com/18282328/97258808-2758a980-187e-11eb-8e37-675ad1cb6f9f.png)

It seems relates to this PR

https://github.com/react-navigation/react-navigation/pull/8805

My questions are:
- does this matter?
- Is this a missing type in the `react-native-screens`
- does this require to run with a specific version of `react-native-screens`?

@WoLewicki What am I missing here?

**Comment by gorbypark** [comment] 2020-10-27 09:50
I have a project that just started giving me the same error after upgrading.  I believe everything is the latest versions.  I am not using expo, but a project created using `react-native init` with react 17.0.1 and react-native 0.63.3 (basically the newest versions of everything).

- "@react-navigation/bottom-tabs": "^5.10.0",
- "@react-navigation/native": "^5.8.0",
- "@react-navigation/stack": "^5.10.0",

**Comment by gorbypark** [comment] 2020-10-27 10:06
I'm not a TypeScript expert, but looking at ResourceSavingScene.tsx line 6 there is
```ts
import {
  Screen,
  screensEnabled,
  // @ts-ignore
  shouldUseActivityState,
} from 'react-native-screens';
```
which to me seems like the author knows this import might fail and is telling typescript compiler to ignore the error, so possibly something like this would work
```js
import {
  Screen,
  screensEnabled,
  // @ts-ignore
  shouldUseActivityState,  // eslint-disable-line
} from 'react-native-screens';
```
I'm not sure if the typescript compiler would strip that out during the build phase, though?

**Comment by WoLewicki** [comment] 2020-10-27 10:12
Yes, the `shouldUseActivityState` is a determiner of the new version of `react-native-screens` that is about to be released, but it does not change anything on the web since `react-native-screens` is not used there. You are using web too, @gorbypark ?

**Comment by gorbypark** [comment] 2020-10-27 10:21
> You are using web too, @gorbypark ?
@WoLewicki Yup I am using web!

**Comment by QaysTrad** [comment] 2020-10-27 10:30
`   "@react-navigation/drawer": "^5.10.0",
    "@react-navigation/native": "^5.8.0",
    "@react-navigation/stack": "^5.10.0"`

Same Issue here, try to use react native web `"react-native-web": "^0.14.4"`

**Comment by WoLewicki** [comment] 2020-10-27 11:18
These lines should produce a warning. The problem with your setup @gorbypark is that you are using `create-react-app` which fails the build on warnings and I am not sure I can help with that, unfortunately.

**Comment by WoLewicki** [comment] 2020-10-27 11:21
I am closing it then. Feel free to comment if you have any questions.

**Closed by WoLewicki** 2020-10-27 11:21 UTC
Labels: bug, package:bottom-tabs

**Comment by gorbypark** [comment] 2020-10-27 12:02
If anyone else using react-scripts/create-react-app stumbles upon this, you can monkey patch `./node_modules/@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene.js` and remove the `shouldUseActivityState` import.  So change 
```js
import { Screen, screensEnabled // @ts-ignore
, shouldUseActivityState } from 'react-native-screens';
```
to 
```js
import { Screen, screensEnabled } from 'react-native-screens';
```
This seems to work even for native builds, but no guarantees it won't break something in the future as the new version of react-native-screens is released.

**Comment by gorbypark** [comment] 2020-10-27 13:12
Here's a better and more durable method, although there might be some unintended side-effects
- add react-app-rewired to your project: `yarn add react-app-rewired`
- change your `package.json` web run script to use react-app-rewired, so change `"web": "react-scripts start"` to `"web": "react-app-rewired start"`
- create a file named `config-overrides.js` in the root of your project with the following code
```js
module.exports = module.exports = function override(config) {
  config.module.rules.push({
    test: /\.(js?)$/,
    use: {
      loader: 'babel-loader',
    },
  });

  return config;
};
```

**Comment by moedeveloper** [comment] 2020-11-03 22:48
how did you solve it ?

**Comment by MohammadAzimi** [comment] 2020-11-04 11:10
> Here's a better and more durable method, although there might be some unintended side-effects (works great in my project, though!)
> 
> * add react-app-rewired to your project: `yarn add react-app-rewired`
> * change your `package.json` web run script to use react-app-rewired, so change `"web": "react-scripts start"` to `"web": "react-app-rewired start"`
> * create a file named `config-overrides.js` in the root of your project with the following code
> 
> ```js
> module.exports = module.exports = function override(config) {
>   config.module.rules.push({
>     test: /\.(js?)$/,
>     use: {
>       loader: 'babel-loader',
>     },
>   });
> 
>   return config;
> };
> ```

I think you are actually overriding the default create-react-app webpack config. But babel-loader is in the default config. see the link. so what's the difference? I'm so much confused.
Isn't  'babel-plugin-react-native-web' enough?
@gorbypark

**Comment by gorbypark** [comment] 2020-11-04 13:52
> babel-loader is in the default config. [see the link](https://github.com/facebook/create-react-app/blob/ff19e0a6d22ba070f5b4c3b511edb4e8d4995686/packages/react-scripts/config/webpack.config.js#L348). so what's the difference?

Yup, this is overriding the default webpack config.  It's (as far as I know) making babel-loader use it's defaults, since we are not passing in any extra options.  The create-react-app webpack config is quite complex and difficult to follow, so I'm not exactly sure which rule is causing the problem, to be honest.  I stripped out all the ts/jsx/mjs/etc extensions so hopefully this touches as little as possible.

**Comment by LorhanSohaky** [comment] 2020-12-06 19:14
How to fix this when use expo?

**Comment by wbasmi** [comment] 2020-12-09 01:34
This is a workaround:

- Create a JS file in your root folder, name it **fix-web.js**
- Write in this code

```
(() => {
  try {
    const filePath = require.resolve(
      '@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene.js',
    );

    const code = fs.readFileSync(filePath).toString();
    fs.writeFileSync(
      filePath,
      code.replace(
        `import { Screen, screensEnabled // @ts-ignore,
shouldUseActivityState } from 'react-native-screens';`,
        `import { Screen, screensEnabled } from 'react-native-screens';`,
      ),
    );
  } catch (err) {}
})();
```
- Then run it manually, or add it to the postinstall script in your package.json file, so it can run automatically upon installing the project.

**Comment by ethanneff** [comment] 2020-12-10 14:08
This is still broken in `"react-native-screens": "2.16.1",`

This is my current `patch-package`

```diff
diff --git a/node_modules/@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene.js b/node_modules/@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene.js
index d2f4c34..6a9d8fe 100644
--- a/node_modules/@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene.js
+++ b/node_modules/@react-navigation/bottom-tabs/lib/module/views/ResourceSavingScene.js
@@ -2,8 +2,7 @@ function _extends() { _extends = Object.assign || function (target) { for (var i
 
 import * as React from 'react';
 import { Platform, StyleSheet, View } from 'react-native';
-import { Screen, screensEnabled // @ts-ignore
-, shouldUseActivityState } from 'react-native-screens';
+import { Screen, screensEnabled } from 'react-native-screens';
 const FAR_FAR_AWAY = 30000; // this should be big enough to move the whole view out of its container
 
 export default class ResourceSavingScene extends React.Component {
```

**Comment by WoLewicki** [comment] 2020-12-10 14:52
@ethanneff can you provide a reproduction of this in a fresh project with `"react-native-screens": "2.16.1"`?

**Comment by LorhanSohaky** [comment] 2020-12-11 04:10
This is my current patch-package for `@react-navigation/drawer@5.11.4`

```ts
diff --git a/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js b/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js
index 152a20a..9e6c177 100644
--- a/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js
+++ b/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js
@@ -2,8 +2,7 @@ function _extends() { _extends = Object.assign || function (target) { for (var i
 
 import * as React from 'react';
 import { Platform, StyleSheet, View } from 'react-native';
-import { Screen, screensEnabled // @ts-ignore
-, shouldUseActivityState } from 'react-native-screens';
+import { Screen, screensEnabled } from 'react-native-screens';
 const FAR_FAR_AWAY = 30000; // this should be big enough to move the whole view out of its container
 
 export default class ResourceSavingScene extends React.Component {

```

**Comment by woodcockjosh** [comment] 2020-12-25 14:07
So the reason this is closed is because it's totally acceptable to have warnings in the console? Can we get an actual fix to this issue please?

**Comment by pors** [comment] 2020-12-25 14:09
> So the reason this is closed is because it's totally acceptable to have warnings in the console? Can we get an actual fix to this issue please? 

How about creating a PR to fix it yourself?

**Comment by woodcockjosh** [comment] 2020-12-25 14:13
@pors that's not my point. The question is why is the issue closed when this is still a bug?

**Comment by woodcockjosh** [comment] 2020-12-25 15:28
You can use these packages until the warnings are gone in case you don't like warnings.

https://www.npmjs.com/package/react-navigation-bottom-tabs-no-warnings
https://www.npmjs.com/package/react-navigation-drawer-no-warnings

Merry Christmas!

**Comment by inglesuniversal** [comment] 2021-01-18 04:21
@woodcockjosh Way to go!!! What a way to close 2020!!! That library tasted better than the Christmas Turkey... LOL

And in deed, that same release has to become part of the current official libraries.

In my case I made use of:

https://www.npmjs.com/package/react-navigation-bottom-tabs-no-warnings

Thanks so much and #StaySafe

**Comment by emac3** [comment] 2021-01-22 08:44
2.16.0 fixes the issue to me (see https://github.com/software-mansion/react-native-screens/pull/709), but latest version of [react-native-screens](https://www.npmjs.com/package/react-native-screens) from npm is 2.15.2, not sure why (should be 2.16.1 I believe)

**Comment by pors** [comment] 2021-01-22 11:58
> 2.16.0 fixes the issue to me (see [software-mansion/react-native-screens#709](https://github.com/software-mansion/react-native-screens/pull/709)), but latest version of [react-native-screens](https://www.npmjs.com/package/react-native-screens) from npm is 2.15.2, not sure why (should be 2.16.1 I believe)

Expo currently doesn't support 2.16 yet it seems:

```
cat ./node_modules/expo/bundledNativeModules.json | fgrep screens
  "react-native-screens": "~2.15.0",
```

But good to know it is in the pipeline!

**Comment by nandorojo** [comment] 2021-01-24 23:01
> This is my current patch-package for `@react-navigation/drawer@5.11.4`
> 
> ```ts
> diff --git a/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js b/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js
> index 152a20a..9e6c177 100644
> --- a/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js
> +++ b/node_modules/@react-navigation/drawer/lib/module/views/ResourceSavingScene.js
> @@ -2,8 +2,7 @@ function _extends() { _extends = Object.assign || function (target) { for (var i
>  
>  import * as React from 'react';
>  import { Platform, StyleSheet, View } from 'react-native';
> -import { Screen, screensEnabled // @ts-ignore
> -, shouldUseActivityState } from 'react-native-screens';
> +import { Screen, screensEnabled } from 'react-native-screens';
>  const FAR_FAR_AWAY = 30000; // this should be big enough to move the whole view out of its container
>  
>  export default class ResourceSavingScene extends React.Component {
> ```

@ethanneff What do you do with `shouldUseActivityState`'s usage below?

```jsx
export default function ResourceSavingScene({
  isVisible,
  children,
  style,
  ...rest
}) {
  // react-native-screens is buggy on web
  if (screensEnabled !== null && screensEnabled !== void 0 && screensEnabled() && Platform.OS !== 'web') {
    if (shouldUseActivityState) { // what do we do with this line?
```

**Comment by lovebes** [comment] 2021-02-02 00:09
if you guys are using expo for web (`expo start:web`) and have this problem, try this:

1. save this file as `fix-for-web.sh` in root directory.
```
#!/bin/bash
# for react-native-screens
# reference: https://github.com/react-navigation/react-navigation/issues/8993
import=shouldUseActivityState
echo "Fixing $import ..."
if grep -q "export const $import = false;" ./node_modules/react-native-screens/lib/module/index.js; then
    echo "$import fixed already!"
else
    echo -e "\nexport const $import = false;">> ./node_modules/react-native-screens/lib/module/index.js
fi
```
you might need to do `bash chmod +x ./fix-for-web.sh` 

2. in `package.json`, add this in `scripts` section:
```
  "scripts": {
    "start": "expo start",
    ....
    "postinstall": "bash ./fix-for-web.sh"
  },
```

**Comment by darynmitchell** [comment] 2021-02-03 06:07
I can confirm that per [this comment on 'warnings printing to console for un-exported members of react-native-screens'](https://github.com/react-navigation/react-navigation/pull/9178#issuecomment-760143668), you can make the compile/console warning go away if you upgrade react-native-screens — if you are ok with expo warning you that your react-native-screens version number is out of range (Expo 40 wants screens version ~2.15.0, actual current version 2.17.x)

**Comment by ctrlShiftBryan** [comment] 2021-04-04 12:31
> How to fix this when using expo?

If you are using react-native and expo you can run:
```
yarn add react-native-screens
```
This will install 3.0 and fix the issue when running expo for web

**Comment by sandz9b** [comment] 2021-04-06 14:25
> > How to fix this when using expo?
> 
> If you are using react-native and expo you can run:
> 
> ```
> yarn add react-native-screens
> ```
> 
> This will install 3.0 and fix the issue when running expo for web

This works for me. Thank you!
