### ISSUE TITLE
android gestureEnabled and goback then the screen disappear

### ISSUE THREAD

**Issue by xuqianjin** [react-navigation/react-navigation#8079] opened 2020-04-20 07:09 UTC
**Current Behavior**
 <img src="https://user-images.githubusercontent.com/12406066/79723198-ece2e280-8317-11ea-9674-6ea7a9955dfd.gif" width = "250" alt="图片" align=center />

**How to reproduce**
step 1
```
screenOptions={{
          ...TransitionPresets.SlideFromRightIOS,
          gestureEnabled: true,
        }}

```
step2
```
    <View style={{flex: 1, alignItems: 'flex-start', justifyContent: 'center'}}>
      <Text style={{color: 'blue'}}>this is pageb</Text>
      <View style={{width: 50}}>
        <Button
          title="goback"
          onPress={() => {
            navigation.goBack();
          }}
        />
      </View>
    </View>
```

**Your Environment**
```
    "@react-native-community/masked-view": "^0.1.9",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.11",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.5.0"
```

complete code
```
// In App.js in a new project

import * as React from 'react';
import {View, Text, Button} from 'react-native';
import {NavigationContainer, useNavigation} from '@react-navigation/native';
import {createStackNavigator, TransitionPresets} from '@react-navigation/stack';

function PageA() {
  const navigation = useNavigation();
  return (
    <View style={{flex: 1, alignItems: 'flex-start', justifyContent: 'center'}}>
      <Text style={{color: 'red'}}>this is pagea</Text>
      <View style={{width: 50}}>
        <Button
          title="push"
          onPress={() => {
            navigation.push('pageb');
          }}
        />
      </View>
    </View>
  );
}

function PageB() {
  const navigation = useNavigation();
  return (
    <View style={{flex: 1, alignItems: 'flex-start', justifyContent: 'center'}}>
      <Text style={{color: 'blue'}}>this is pageb</Text>
      <View style={{width: 50}}>
        <Button
          title="goback"
          onPress={() => {
            navigation.goBack();
          }}
        />
      </View>
    </View>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator
        headerMode="none"
        initialRouteName="launch"
        screenOptions={{
          ...TransitionPresets.SlideFromRightIOS,
          gestureEnabled: true,
        }}>
        <Stack.Screen name="pagea" component={PageA} />
        <Stack.Screen name="pageb" component={PageB} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;

```

**Comment by zhugy-yami** [comment] 2020-04-20 10:03
me too!

**Comment by satya164** [comment] 2020-04-20 10:24
Duplicate of #7938

**Closed by satya164** 2020-04-20 10:24 UTC
Labels: bug, package:stack
