### ISSUE TITLE
folly::toJson: JSON object value was a NaN or INF error on rendering simple navigation examples

### ISSUE THREAD

**Issue by emanuelmartin** [react-navigation/react-navigation#9480] opened 2021-04-01 18:04 UTC
**Current Behavior**
App showing error `folly::toJson: JSON object value was a NaN or INF` error on rendering simple navigation examples

- What code are you running and what is happening?
New project with Windows template:
`npx react-native init <projectName> --template react-native@^0.64.0`
`npx react-native-windows-init --overwrite`

Added react navigation to the project and tried it with simple code:
`App.js

<img width="361" alt="image" src="https://user-images.githubusercontent.com/33545553/113334699-3d610f00-92e1-11eb-9317-061e54fd8fe8.png">
`

`navigator.js

<img width="356" alt="image" src="https://user-images.githubusercontent.com/33545553/113334750-4ce05800-92e1-11eb-9691-aad33cc92ccd.png">
`

`HomeScreen.js

<img width="455" alt="image" src="https://user-images.githubusercontent.com/33545553/113334780-55389300-92e1-11eb-9aad-c0b179ae5f69.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/33545553/113334797-5b2e7400-92e1-11eb-956e-9026f5a2d39b.png">
Tried both with function and component
`

**Expected Behavior**

- What do you expect should be happening?
To render my Home Screen inside the stack navigator, screens render without trouble when not using the navigator.

**How to reproduce**
Code's already up here.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Windows
| @react-navigation/native       | 5.9.3
| @react-navigation/stack        | 5.14.3
| react-native-gesture-handler   | -
| react-native-safe-area-context | 3.2.0
| react-native-screens           | 3.0.0
| react-native                   | 0.64.0
| expo                           | -
| node                           |  14.16.0
| npm or yarn                    | npm

**Comment by SBS-FPATE-RINALDI** [comment] 2021-04-07 22:41
Running into same issue. In the debugger the error is "Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the UIManager."

I have double-checked that all dependencies are installed.

**Comment by aJieBai** [comment] 2021-04-09 10:39
same issue "Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the"

**Comment by prupipho** [comment] 2021-04-09 10:45
Hello,
I think this is related to **react-native-screens**, I ran into the same problem after updating to 3.0, but it seems to work ok setting the version back down to **"^2.18.1"**. 

The issue I noticed after that though. It is that the bottom tab text doesn´t change to blue as before when page/screen is selected. But that´s probably a completely different issue, maybe related to react-navigation?

**Comment by RahidAkhundzada** [comment] 2021-04-13 18:56
> . It is that the bottom tab text doesn´t change to blue as before when page/screen is selected.
not work.if your project work.please craete new one for community and send us git .

**Comment by kacperkapusciak** [comment] 2021-04-14 13:28
Maintainer of `react-native-screens` here.

This issue is caused by our library and was fixed in [v3.1.1](https://github.com/software-mansion/react-native-screens/releases/tag/3.1.1). Please upgrade to the newest version of the `react-native-screens` package and the provided code will work just fine.

The bug was resolved [here](https://github.com/software-mansion/react-native-screens/issues/885) so I'll close this issue.

Tagging: @emanuelmartin @SBS-FPATE-RINALDI @aJieBai

**Closed by kacperkapusciak** 2021-04-14 13:28 UTC
Labels: bug, package:stack

**Comment by emanuelmartin** [comment] 2021-04-14 13:38
Thanks @kacperkapusciak!! 
Gonna upgrade

You're the master 👏👏

**Comment by aJieBai** [comment] 2021-04-14 13:45
@kacperkapusciak Thank you for the upgrade

**Comment by SBS-FPATE-RINALDI** [comment] 2021-04-15 18:35
@kacperkapusciak After upgrading to 3.1.1 using npm I am still running into the same error using a Stack Navigator. I am using react-native-windows. Here is my code:

```
import React from 'react';
import type { Node } from 'react';
import {
  useColorScheme,
  View,
} from 'react-native';

import { FancyMathSample } from '../components/FancyMath';
import { SerialPortExample } from '../components/SerialPort';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

// import 'react-native-gesture-handler'; - will be needed for iOS and Android

const Stack = createStackNavigator();

const Home = (): Node => {
  return (
    <View>
      <FancyMathSample></FancyMathSample>
    </View>
  );
}

const Test = () => {
  return (
    <View>
      <SerialPortExample></SerialPortExample>
    </View>
  )
}

const App: () => Node = () => {

  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={Home} />
        <Stack.Screen name="Test" component={Test} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default App;
```

**Comment by kacperkapusciak** [comment] 2021-04-16 06:59
@SBS-FPATE-RINALDI I'm unfamiliar with flowtypes and I have no way of knowing what `FancyMathSample` and `SerialPortExample` here is but besides that, your example should work.

Try deleting `node_modules/`, cleaning cache and reinstalling packages again.
In elevated PowerShell that would be:
```bash
# in project directory
rm -Recurse node_modules/
npm cache clean --force
npm install
npm start -- --reset-cache
# in new PowerShell window still in project directory
npm run windows 
```

Hope that helps 🤞

**Comment by SBS-FPATE-RINALDI** [comment] 2021-04-16 16:16
@kacperkapusciak  ah yep. The cache clean did the trick, should have thought of that. 🤦  Thank you!!
