### ISSUE TITLE
[Question/Bug] Navigation initial state param

### ISSUE THREAD

**Issue by James2516** [react-navigation/react-navigation#2409] opened 2017-08-17 11:41 UTC
https://snack.expo.io/HJKoZNuv-

I want to go straight into the `DayStack.Day` screen with `AppNavigator.router.getActionForPathAndParams('Day', { day: '1' })` but the `{ day: '1'}` param is not getting passed to the navigator at

    navigationOptions: ({ navigation }) => ({
      title: `Day ${navigation.state.params.day}`,
    }),

`navigation.state` is undefined.

**Comment by kelset** [comment] 2017-12-03 10:36
Pinging OP @James2516  since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover I think it's actually related to https://github.com/react-community/react-navigation/issues/1848 --- and I think this is technically a duplicate of https://github.com/react-community/react-navigation/issues/2588 (so I'll close that one for this since it's older & has a snack)

**Comment by kelset** [comment] 2018-01-04 09:12
Hi there @James2516,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Closed by kelset** 2018-01-04 09:12 UTC
Labels: bug
