### ISSUE TITLE
Nested Navigator self setParams not working when a subScreen is above its stack

### ISSUE THREAD

**Issue by kevinscience** [react-navigation/react-navigation#4185] opened 2018-05-10 05:16 UTC
### Current Behavior

Suppose I have:

TabNavigator: Main
- Screen: A
- Screen:B

StackNavigator:Root
- Screen:Main
- Screen:C

In Screen A, I have 
```
setTitle(){
        console.log('setTitle called');
        this.props.navigation.setParams({title:'Went to C'})
    }
```
will be pass to Screen C and will be called in Screen C as a callback function.
But, The fact is that, when Screen C is on, setParams in Screen A is not working.

### Expected Behavior

`this.props.navigation.setParams({title:'Went to C'})` is working in any circumstances.

### How to reproduce

I have made a sample project to reproduce the bug
https://snack.expo.io/HkoCblM0z

When one press the button on Screen A, it navigate to Screen C, there is a callback function called in Screen C's constructor. But it's not working. Nothing happened.
please see the log on console. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.12
| react-native     | 0.55.2
| node             | 8.11.1
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment] 2018-05-23 22:36
repro'd this issue on 2.0 as well: https://snack.expo.io/rkSZTDXJm

**Comment by fredriksebek** [comment] 2018-05-24 20:45
I initially thought it was due to API changes, but didn't find anything that stood out. Happy I found this post or else I would have gone crazy. Happy you are able to reproduce it @brentvatne!

**Comment by normdoow** [comment] 2018-05-25 04:20
I am having a similar issue to this. I have a StackNavigator nested inside a DrawerNavigator. Stacks set up like this...
```
const innerDrawerStack = StackNavigator({
    Home: { screen: Menu },
    CardsView: { screen: CardsView },
    Feedback: { screen: FeedbackView }
}, {
    navigationOptions: ({navigation}) => ({
        headerLeft: <HamburgerButton navigation={ navigation } />,
        headerStyle: {
            backgroundColor: colors.primaryColor,
        },
        headerTitleStyle: {
            fontWeight: 'bold',
            fontSize: 16,
            color: 'white'
        },
        gesturesEnabled: false
    }),
    initialRouteName: 'Home'
})

const DrawerStack = DrawerNavigator({
    InnerStack: { screen: innerDrawerStack } //inner drawer stack adds the header since drawers don't have a header
},{ contentComponent: CustomDrawerView })
```

my component `Home` calls `this.props.navigation.setParams({credit: resp.val.toFixed(2)});` to set the navigation options dynamically for that component. This works fine when navigating to the component normally. But when calling reset to clear the stack. like this...
```
resetNavToHome(props) {     //pass in the props of the component to use for navigation
        return props
               .navigation
               .dispatch(NavigationActions.reset({
                    index: 0,
                    actions: [
                        NavigationActions.navigate({ routeName: 'DrawerStack'})
                    ]
                }));
    }
```
This will take me to the drawerstack which then goes to the nested initial route `Home` but when i call `setParams` this time it will restart the `Home` component in an infinite loop and will freeze.

I believe part of the issue with this is the nested stacks. almost like the setParams is dealing with the wrong stack since it just got reset. I think this is the same issue as the TabNavigator issues. If you have any more questions I would be glad to try and give more info. I think this is still an issue. I would greatly appreciate a fix or work around as I need this dynamic capability for my header.

**Comment by lichenglu** [comment] 2018-06-17 01:40
Thanks for the great work! Can we get some update on this issue? If it will not be addressed in the near future, then I might use a custom header as a workaround for now.

**Comment by normdoow** [comment] 2018-06-17 23:53
I just found a fix to the issue for me by calling setParams within `IneractionManager.runAfterInteractions` like this...
```
InteractionManager.runAfterInteractions(() => {
            this.props.navigation.setParams({credit: resp.val.toFixed(2)})
        });
```

**Comment by WillyRamirez** [comment] 2018-06-20 18:58
@ericvicenti Hi, could you kindly give us an update on the ETA for this? A release is depending on this :)) Thanks!

**Comment by brentvatne** [comment] 2018-06-27 23:58
@WillyRamirez - https://github.com/react-navigation/react-navigation/pull/4587 fixes this, waiting for review from @ericvicenti

**Closed** 2018-06-28 00:37 UTC
Labels: bug

**Comment by brentvatne** [comment] 2018-06-28 01:14
released in 2.5.5

**Comment by sushrut-desora** [comment] 2020-05-04 15:58
Still not working. I had to use the solution from this comment to get it to work - https://github.com/react-navigation/react-navigation/issues/4185#issuecomment-397914845

"@react-navigation/core": "5.3.4
"@react-navigation/native": "5.1.6"
"@react-navigation/stack": "5.2.13",

**Comment by kuldeepworkid** [comment] 2021-10-04 12:34
Even Not working in v6
