### ISSUE TITLE
no reason that nested TabNavigator can navigate directly to its parent StackNavigator through this.props

### ISSUE THREAD

**Issue by woowalker** [react-navigation/react-navigation#4261] opened 2018-05-17 11:12 UTC
### Current Behavior
**StackNavigator**
|--**TabNavigator**
|----**TabA**
|----**TabB**
|--**PageA**
|--**PageB**

and now in **TabA**, i can navigate directly to **PageA** through 
`this.props.navigation.navigate('PageA')`
but i think through `this.props.navigation.navigate`, **TabA** can only access to **TabB**,
it seems mess up.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7894779/40172705-07abf354-5a02-11e8-9bfe-f100e770c58b.gif)

### Expected Behavior

- **_every createXNavigator should be a unique instance_** (old version seems to be ?) 
- if not, in some case, we will be limited by the only one stack
for example:

**StackNavigator**
|--**StackNavigatorA**
|----**PageA**
|----**PageB**
|--**StackNavigatorB**
|----**PageC**
|----**PageD**

now i stay in **PageB**, i want to switch to **StackNavigatorB**'s **PageC**, when navigate done to **StackNavigatorB**, i want the **StackNavigatorA** reset to **PageA** (like SwitchNavigator do), and then you can not access the **StackNavigatorA** instance, and when you navigate to **PagaA**, you lost **PageC**.

hope that somebody understand what i mean, and why not using createSwitchNavigator, because **SwitchNavigator switch pages without animation**...

### How to reproduce
code here: [https://snack.expo.io/@woowalker/unnamed-snack](url)
or see below:
```
import React, {Component} from 'react'
import {View, Text, TouchableOpacity} from 'react-native'
import {createStackNavigator, createTabNavigator} from 'react-navigation'

class TabA extends Component {
  render() {
    return (
      <View>
        <Text>{'tabA'}</Text>
        <TouchableOpacity onPress={() => this.props.navigation.navigate('TabB')}>
          <Text>{'nav to tabB'}</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={() => this.props.navigation.navigate('PageB')}>
          <Text>{'nav to PageB'}</Text>
        </TouchableOpacity>
      </View>
    )
  }
}

class TabB extends Component {
  render() {
    return (
      <View>
        <Text>{'tabB'}</Text>
      </View>
    )
  }
}

const TabNav = createTabNavigator({
  TabA: {screen: TabA},
  TabB: {screen: TabB},
})

class PageA extends Component {
  render() {
    return (
      <View>
        <Text>{'pageA'}</Text>
      </View>
    )
  }
}

class PageB extends Component {
  render() {
    return (
      <View>
        <Text>{'pageB'}</Text>
      </View>
    )
  }
}

const StackNav = createStackNavigator({
  PageTab: {screen: TabNav},
  PageA: {screen: PageA},
  PageB: {screen: PageB}
})

export default StackNav;

```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| react             | 16.3.1

**Comment by brentvatne** [comment] 2018-05-23 16:41
it sounds like what you want to do is reset the tabs when you switch away to another tab. you can extend the tab router, implement a custom navigator, or wrap the navigator and do it from there (see: https://www.youtube.com/watch?v=wJJZ9Od8MjM for info on how to do that)

ultimately this is a question and not a bug so i will close this. see https://reactnavigation.org/help.html for more information on how to get help.

**Closed by brentvatne** 2018-05-23 16:41 UTC
