### ISSUE TITLE
Reset navigation mounting all intermediate screens, but then destroyed

### ISSUE THREAD

**Issue by carsonwah** [react-navigation/react-navigation#2421] opened 2017-08-18 20:41 UTC
## Structure
```
const Tab = TabNavigator(
  Stack: { screen: Stack }
)

const Stack = StackNavigator(
  Home: { screen: Home },
  SubView1: { screen: Subview1},
  SubView2: { screen: Subview2}
)
```

## Reset Action (from SubView2)
```
const resetToHome = NavigationActions.reset({
  index: 0,
  key: null,
  actions: [
    NavigationActions.navigate({routeName: 'Home'}),
  ],
});
this.props.navigation.dispatch(resetToHome);
```

## Current Behavior
Successfully reset to Home. But as I have some componentWillMount() / componentDidMount() logics, I found that these functions in Home and SubView1 are triggered, which I expect not.

It also seems that the component is destroyed immediately, so my async function produces some warning as below.

## Sample warning message
![2017-08-19 04 24 34](https://user-images.githubusercontent.com/25053707/29476753-10abf5ac-8498-11e7-9d02-fb94f6e06131.png)

------

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.12
| react-native     |  expo sdk 19.0.0 (supposingly 0.46)

**Comment by spencercarli** [comment] 2017-08-21 23:19
A demo of this issue would aid in working through this issue - thanks!

**Comment by ravirajn22** [comment] 2017-08-22 11:47
const App = StackNavigator({
     Screen1: { screen: Screen1 },
     MainTab: { screen: SomeTabNavigator },
     Screen2: { screen: Screen2 },
     Screen3: { screen: Screen3 },
    })

  My stack is now (Screen1 is not in stack because I have reset to MainTab)

  MainTab -> Screen2 -> Screen3 (current screen)

  then I reset using dispatch

     this.props.navigation.dispatch(NavigationActions.reset({
        index: 0,
        actions: [
        NavigationActions.navigate({ routeName: 'Screen1'})
       ]
     })

The reset happens and I can go to 'Screen1' but 'Screen2' componentDidMount() is called. Why?

**Comment by carsonwah** [comment] 2017-08-22 19:23
Thanks @spencercarli for looking into here. My situation is just the same as @ravirajn22 . The problem is reset will invoke all the intermidiate screen to mount and unmount themselves.

I think this should be unexpected for reset action and it causes quite a trouble.
For example I have some network call before mount:
```
// SubView1
componentWillMount() {
  axios.get('xxx').then(response => {
    this.setState({ response: response });
  });
}
```
This is invoked when I reset from SubView2 to Home (unexpected already). But when it want to setState(), it prompts a warning saying that SubView1 (this) does not exist anymore.

------

For anyone wants a temp workaround for this warning, I can only think stopping the setState, but not the network call.
```
constructor(props) {
    super(props);
    this.state = {
      unmounting: false,
    }
  }
componentWillUnmount() {
    this.state = {
      unmounting: true, // can't use setState because it is async
    };
  }
componentWillMount() {
  axios.get('xxx').then(response => {
    if (!this.state.unmounting) { this.setState(...) }
  })
  }
```
WARNING: this is an anti-pattern in react.
Or you may use isMounted() method to check but it's deprecated now.
See: https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

**Comment by ravirajn22** [comment] 2017-08-24 09:16
@carsonwah I feel this library is no longer maintained by core developers they are all gone. Have u got any efficient work around, the above doesn't seems to be right.

**Comment by quadsurf** [comment] 2017-08-24 13:50
@carsonwah ... i think @spencercarli is breathing new life into this lib, which we can all be grateful for and hopeful of (Spencer is a big advocate for RN and has a highly reputable blog)! In order for issue resolution though, Spencer has been asking for demos. It's unclear whether he is accepting inline code snippets as demos, or if he is requiring more Expo-like demos with accompanying repo. I do hope that copy-and-pasted example code pasted directly into these github issue trackers will suffice for his demo requests, so react-navigation can expedite issue resolution.

**Comment by carsonwah** [comment] 2017-08-26 16:37
@quadsurf Sorry that my project is quite large so it's difficult to share it here. I just made a demo on expo snack but I surprisingly I found no bug there. Maybe there is some setting in my project that causes it. At this moment I haven't found out what exactly is the cause, but anyone see this and having the same issue is welcome to use this as the template to investigate more.

[https://snack.expo.io/SkH0z7kYW](https://snack.expo.io/SkH0z7kYW)

**Comment by rpopovici** [comment] 2017-09-01 13:49
@carsonwah some of these issues are being discussed here #723 and some potential solutions in these PRs:
idempotent pushes #2334
queued action dispatch #1313
queued transitions in Transitioner #2400

**Comment by kelset** [comment] 2017-12-03 10:40
Pinging OP @carsonwah since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

Moreover, we merged the queued action dispatch PR so your issue should be fixable now.

**Comment by carsonwah** [comment] 2017-12-03 17:24
@kelset I have implemented some workaround to fix this, so I can't test it for now. You may close it first. I can come back to this later if I found this issue not fixed yet. Thanks for the work.

**Comment by Pabloitto** [comment] 2017-12-15 22:48
somebody fix this problem? or is there any workaround ?

**Comment by carsonwah** [comment] 2017-12-16 01:19
@Pabloitto Have you tried the latest version? Mine (beta-21) seems not having this problem anymore. I can log `componentWillUnmount`, but not `componentWillMount`.

**Comment by mssio** [comment] 2017-12-19 09:36
I also have this problem when using NavigationActions.reset with more than 1 action, when only 1 action provided the warning is not shown.

I am also using beta-21, don't know if it has been fixed on beta-22.

**Comment by mssio** [comment] 2017-12-19 09:48
I also have this problem on. Mine also on beta-21. But in my problem it only happen when there is no extra params.

Example code: 

This will trigger the warning

````js
const navigationAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({
          routeName: 'Tabs',
        }),
        NavigationActions.navigate({
          routeName: 'Article',
          params: { uuid: 'kawasan-0001', type: 'history' },
        }),
      ],
    })
````

This will not trigger the warning
````js
const navigationAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({
          routeName: 'Tabs',
        }),
        NavigationActions.navigate({
          routeName: 'Article',
        }),
      ],
    })
````

**Comment by zaiz91** [comment] 2018-01-17 06:27
I have the same bug with Beta-26. Anyone has a workaround for this?

My bad workaround is 

`let willMount;
...
componentWillMount() {
    if(!willMount) {
       willMount = Date.now();
       this.setState(...)
    }
}`

**Comment by carsonwah** [comment] 2018-02-06 10:42
Just upgraded to 1.0.0-beta.30 and still got this issue. I'm not storing my navigation stack in redux, so I still get no way to fix this.

There is a new `popToTop()` action, but I cannot make it work. It keeps throwing `Error: Cannot get config because the route does not have a routeName` when I use it.

**Comment by kelset** [comment] 2018-02-06 11:05
Ok I'll reopen this.

**Comment by carsonwah** [comment] 2018-02-06 12:53
@kelset I have successfully reproduce the issue!

https://snack.expo.io/S1-VzXDLz

The bug happens when there is `setParams()` inside `componentWillMount()` or `componentDidMount()` methods, of "screens that are being navigated in the reset action".

For example, this reset action causes the bug:

```javascript
class SomeComponent extends Component {
  componentDidMount() {
    this.props.navigation.setParams({ title: 'some title' });
  }
}
// somewhere else...
const resetToHome = NavigationActions.reset({
    index: 0,
    key: null,
    actions: [
      NavigationActions.navigate({routeName: 'Home'}),
      NavigationActions.navigate({routeName: 'SomeComponent'}),  // Appearing here
    ],
  });
```

I cannot go deeper into `react-navigation` source code to debug as I had a hard time understanding the code. Hope this observation can help resolving the bug soon. Thanks for the great works, this library is definitely getting better and better.

---

@mssio I cannot reproduce your case. Do you have any `setParams()` in your components?

**Comment by kelset** [comment] 2018-02-06 14:00
cc @ericvicenti

**Comment by rpopovici** [comment] 2018-02-06 15:19
@kelset @ericvicenti I believe one of my PRs #2400 was fixing this problem. The transitioner is leaking state between transitions. Some actions like **set params** or **reset** don't really have a transition attached but they must pass the newly determined state further down the line.

    const nextScenes = NavigationScenesReducer(
      **this.state.scenes**,
      nextProps.navigation.state,
      this.props.navigation.state
);
Currently, only actual state is used to determine the next scene, which can be an issue if componentWillReceiveProps is called multiple times during a transition. This is why I came up the simple solution to queue all potential transitions in order to do not put the transitioner in invalid state.

Same problem with  **const indexHasChanged =
nextProps.navigation.state.index !== this.props.navigation.state.index;**

indexHasChanged should be calculated against pevious props at every step and not only against current props.

From my PR:
const indexHasChanged = nextProps.navigation.state.index !== prevProps.navigation.state.index;

In a way, this problem is similar to the one solved in #1313

**Comment by rpopovici** [comment] 2018-02-06 15:38
Apparently @brentvatne had an attempt to fix this in https://github.com/react-navigation/react-navigation/commit/f8426bef7ebe39722e155c8ca774a96255867036

**Comment by brentvatne** [comment] 2018-02-07 20:39
hey folks we'll be getting to reset issues shortly. `reset` works very strangely at the moment and we need to rethink it, so we'll discuss and write up a [RFC](https://github.com/react-navigation/rfcs) soon

**Comment by Barylskyigb** [comment] 2018-02-12 12:32
I've tried v1.0.3 and looks like the issue is still there

**Comment by neilhamilton** [comment] 2018-02-20 01:53
Definitely experiencing this and it's a show stopper! Causing all kinds of crashes when doing a reset. Additional snack: https://snack.expo.io/HJoDK8uPM

**Comment by neilhamilton** [comment] 2018-02-20 14:32
Anyone else who stumbles here and is a beginner like me, I've instead used the popToTop action and it provides what looks like the same result as Reset.

**Comment by JoseIgnacio92** [comment] 2018-02-27 15:19
Some solution for this, when I execute reset, the componentWillMount of all previous screens is executed

Dependencies:

    "react-navigation": "^1.2.1",
    "react-native": "0.52.1",

**Comment by JoseIgnacio92** [comment] 2018-03-01 18:37
In my case in each event I had a call to an api, create a global variable that stopped the calls. But the arrangement seemed too far-fetched. Then I found that the rendering of each screen is also executed.
I chose to leave the library, it's very good but this bug scared me a little.

sorry for my English

**Comment by JoseIgnacio92** [comment] 2018-03-01 22:09
Aldo executes the render

**Comment by Pagebakers** [comment] 2018-03-09 06:11
Having this issue in 1.2.1 and now in 1.5 aswel. As soon as I reset, all componentWillMount hooks will be run again. componentWillUnmount is never called anywhere.

**Comment by hkung77** [comment] 2018-03-20 07:29
Seems like this issue is being worked on actively. I just wanted to give an FYI, it seems like the replace function is also causing the same issue?

**Comment by bthuan** [comment] 2018-04-10 15:46
i have the same issue with 1.5, everything is working fine with 1.0.2. 
My application: a 'home' component which has fetch data function inside componentDidMount, and based on the data it will redirect to another 'details' component. Whenever I do a reset to 'home' inside 'details', the 'home' component's method is called again which triggers the fetch function and then redirects to 'details' again and again

**Comment by brentvatne** [comment] 2018-05-01 00:33
can someone who is having this issue please share a mcve (https://stackoverflow.com/help/mcve)? that will help a lot for us to be able to test fixes

**Comment by carsonwah** [comment] 2018-05-01 16:14
@brentvatne Here: https://snack.expo.io/S1-VzXDLz

**Comment by brentvatne** [comment] 2018-11-09 17:43
@tetreault - even better than sharing the full project is to share a MCVE: https://stackoverflow.com/help/mcve - this is actually what we ask for when reporting bugs. please create one and share it here otherwise you will probably not get any answers

**Comment by satya164** [comment] 2020-03-17 09:55
Closing since this is a very old issue. Please open a new issue if you're still facing the issue with the latest version.

**Closed by satya164** 2020-03-17 09:55 UTC
Labels: bug, package:stack, version-4

**Comment by pastean** [comment] 2020-05-05 14:03
Is there a better solution than the setTimeout in componentDidMount yet? I am using react-navigation v4 (upgraded from v1) and I still have this issue.

**Comment by dustinth** [comment] 2020-07-09 16:39
Here is my solution if anybody interested:
Basic idea is listen to the onTransitionStart and onTransitionEnd, do some tricky work.

// StackNavigator Example
const RootStackNavigator = StackNavigator(reactNavigationRouters, {
  navigationOptions: ({ navigation }) => { },
  initialRouteName: 'LaunchScene',
  headerMode: 'screen',
  onTransitionStart: (newState: any) => {
    transitionManager.transitionStarted(newState)
  },
  onTransitionEnd: (newState: any) => {
    transitionManager.transitionEnded(newState)
  }
})

// TransitionManager.ts
class TransitionManager {
  private _currentScene?: string
  private _listeners: { [key: string]: () => void } = {}

  public transitionStarted(newState: any) {
    const routeName = newState.scene.route.routeName
    if (!routeName) {
      return
    }
    this._currentScene = routeName
  }

  public transitionEnded(newState: any) {
    const routeName = newState.scene.route.routeName
    if (!routeName) {
      return
    }
    this._currentScene = undefined
    if (this._listeners[routeName]) {
      try {
        this._listeners[routeName]()
      } catch (error) {
        console.warn('TRANSITION END Listener Error: ', error)
      }
    }
    this._listeners = {}
  }

  public setTransitionListener(routeName: string, listener: () => void) {
    if (this._currentScene !== routeName) {
      listener()
      return
    }
    this._listeners[routeName] = listener
  }
}

const transitionManager = new TransitionManager()
export { transitionManager }

After that, in your Scene listen to the didFocus on props.navigation something like following:
// Scene.ts
componentDidMount() {
  this.props.navigation.addListener('didFocus', ()=>{
    this.props.navigation.setParams({...})
  })
}
