### ISSUE TITLE
Specify reset key to define what state should be reset

### ISSUE THREAD

**Issue by Kerumen** [react-navigation/react-navigation#691] opened 2017-03-14 22:39 UTC
This is a call to support. The number of issues which mention this is countless.
Currently there is no other way to build a modern app with a Splashscreen or a Login / Register process without this. And it seems everyone try to find workarounds but each has its downsides.
I would be happy to set up a PR but the source code of react-navigation is too cryptic for me yet.

Relevant issues:
#395 
#199 
#452
#156 
#335 
#325
#59
...

Thanks!

**Comment by Jacse** [comment] 2017-03-16 00:26
👍  With all the open issues related to this it is pretty clear it is a major missing feature.

**Comment by ericvicenti** [comment] 2017-03-17 17:24
Thanks for filing this, this certainly seems to be a top-priority issue.

I think this could be fixed by adding a `key` to the `reset` action, which specifies which node is getting reset.

Then we could hardcode a special key for the top-level nav state, like 'root', so that you can fire a reset action with the 'root' key to reset the nav of the whole app.

**Comment by ralkan** [comment] 2017-05-05 13:48
@Kerumen I've opened a [Pull Request](https://github.com/react-community/react-navigation/pull/1384) regarding this issue.

If this PR gets approved you will be able to specify a `stateName` parameter and then dispatch a reset action for a specific `StackNavigator`.

Cheers!

**Comment by 0x6e6562** [comment] 2017-05-26 16:03
@Kerumen Did #789 resolve your issue? Just curious, since I had no luck with that patch but the fix from @ralkan #1384 does appear to work.

**Comment by vendramini** [comment] 2017-08-04 01:41
People, is there a solution for this issue? I'm really tired to try to solve this. I tried a lot of things that i can't even put some code here to ask for a objective help. So I will try to show my current situation simple as possible.

Basically: I have a `DrawerNavigator` with some nested `StackNavigator`.
```javascript
export const MainNavigator = DrawerNavigator(
    {
        OrderNew: {
            screen: OrderNew,
            navigationOptions: {
                drawerLabel: DrawerLabel('New Order')
            }
        },
        Orders: {
            screen: OrderNavigator, //a StackNavigator
            navigationOptions: {
                drawerLabel: DrawerLabel('Orders')
            }
        },
        MenuNavigator: {
            screen: MenuNavigator, //a StackNavigator
            navigationOptions: {
                drawerLabel: DrawerLabel('Menu')
            }
        },
    //more screens...
    {
        initialRouteName: 'OrderNew',
        drawerPosition: 'right',
        contentComponent: props => <ScrollView style={{backgroundColor: 'rgba(227, 100, 29, .95)'}}><DrawerMenu state={props} /></ScrollView>,
    }
);
```javascript
So, I'm passing a `contentComponent` with my own menu component. My idea is to overwrite the `onItemPress` event of `DrawerItems` component and put my logic here.

What I want is: I would like to reset `MenuNavigator` (and other stack screens) every time users press that item. I just can't achieve this. As i said, I tried a lot of code. Actually, it's like this:
```javascript
onItemPress={
    router => {
        const navigateAction = NavigationActions.navigate({
            routeName: router.route.routeName,
        });

        this.props.state.navigation.dispatch(navigateAction);
    }
}
```
The above code works, I can navigate through drawer items. Now, in my head, I just should pass an subaction resetting to the first item on navigator. So I tried:

```javascript
onItemPress={
    router => {
        const navigateAction = NavigationActions.navigate({
            routeName: router.route.routeName,
            action: NavigationActions.reset({
                index: 0,
                actions: [
                    NavigationActions.navigate({routeName: router.route.routes[0].routeName}),
                ]
            })
        });

        this.props.state.navigation.dispatch(navigateAction);
    }
}
```
And explodes an error:

> There is no route defined for key Menu.
Must be one of: 'Orders','OrderClient'

I just can't solve this and all issues that I saw didn't exposes an objective solution neither a clearly way. I don't want to open another issue for this, maybe the problem is mine misunderstood about the lib behavior.

Please, help me.

**Comment by sraka1** [comment] 2018-03-12 11:58
@brentvatne @ericvicenti is this not a duplicate of https://github.com/react-navigation/react-navigation/pull/789?

**Comment by satya164** [comment] 2020-03-18 14:15
Closing since this is possible in v5.

**Closed by satya164** 2020-03-18 14:15 UTC
Labels: critical, package:stack, version-4
