### ISSUE TITLE
Navigating to screen with tabBar visible set to false causes transition glitch

### ISSUE THREAD

**Issue by MyGuySi** [react-navigation/react-navigation#667] opened 2017-03-13 14:33 UTC
I've got a TabNavigator with some nested StackNavigators. If I navigate to a screen in one of those StackNavigators that has `tabBar: { visible: false }` it causes the transition to glitch the first time it loads. Subsequent navigations are fine.

![](https://media.giphy.com/media/IW8h4etgX65tC/giphy.gif)

It's difficult to tell whats happening from the video but I've slowed it right down and the screen that I'm navigating to appears, then disappears and then the animated transition begins. It basically flashes the screen before the transition. I can make a copy of it slowed right down if you need to see it.

I'm using 1.0.0-beta.6

**Comment by JonFridrik** [comment] 2017-03-30 10:36
I am having the same trouble. Can you not push the tabbar screen down the stack instead of changing the visibility?

**Comment by spencercarli** [comment] 2017-08-15 02:28
I'm going to close this since there hasn't been activity in a few months (making me think it's been fixed in a more recent release). If it hasn't, please re-open or ping me. Thanks!

**Comment by Arnarkari93** [comment] 2018-02-21 15:04
@spencercarli  This has no been fixed. ("react-navigation": "^1.0.0-beta.19")

**Comment by brentvatne** [comment] 2018-05-08 01:07
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!

**Closed by brentvatne** 2018-05-08 01:07 UTC
Labels: bug, transitions
