### ISSUE TITLE
Nested TabNavigator is buggy

### ISSUE THREAD

**Issue by BowgartField** [react-navigation/react-navigation#3102] opened 2017-12-10 15:02 UTC
### Current Behavior
When you use a TabNavigator in a other TabNavigator  the nested  TabNavigator (second) randomly work or not.
The tabNavigator buttons doesn't load the new screen when I click on it and doesn't change the active tab. Swipe left or swipe right are also not working.
Also the screen's content loading randmoly with no particular reasons.

I try to restart packager and reload the app but nothing works.
The only solution that I found to continue to work is to set the `swipeEnabled` on false in TabNavigator's options when it's not working and  set it to true when the bug is reproducing, but this hack not working all time. Sometimes 'true' is working but somethings 'false' works.

I only test it on Android and in Debug mode because I don't have a IOS device.

[Project Repository](https://exp.host/@bowgartfield/resell)

### Expected Behavior
The second TabNavigator should load the content of `return` function of my Tab screen but it's not the case. The swipe between differents screen should also work but not work as well.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.49.5
| node             | v9.2.1
| yarn      | 1.3.2
| npm | 5.6.0

**Comment by DavideValdo** [comment] 2017-12-11 15:30
+1 on Android

**Comment by BowgartField** [comment] 2017-12-18 12:19
What the status ?

**Comment by budiadiono** [comment] 2017-12-20 14:16
@BowgartField Try to set `lazy` to `true` as described here: https://github.com/react-community/react-navigation/issues/662#issuecomment-343120433 for temporary workaround. It works for me.

**Comment by satya164** [comment] 2018-01-04 05:47
Duplicate of #662 

Nesting tab navigators is not supported unless you disable swipes and animations on all of them but one. This is a limitation of the underlying native components on Android and there is no workaround.

**Closed** 2018-01-04 09:05 UTC
Labels: bug, component: Tabs
