### ISSUE TITLE
Navigate to stack route should not initialize initialRouteName if not needed

### ISSUE THREAD

**Issue by Aure77** [react-navigation/react-navigation#7989] opened 2020-04-09 15:48 UTC
**Current Behavior**

If I navigate from a switch route (route A) to a sub stack route (route C). _initialRouteName_ (route B) defined in stack navigator is init & rendered (performance...). Moreover, If I go back from this route (C), this navigate to stack _initialRouteName_ (B) not original route (A)...

**Expected Behavior**

_initialRouteName_ from stack navigator should be lazy loaded.
goBack() from sub stack route should back to previous route (not stack _initialRouteName_)

**How to reproduce**

https://snack.expo.io/yXqO7aJou

console.log("render C") is printed when navigate from screen "A" to "B".
Press "Go Back to A ?" in screen "B" & you will be redirected to screen "C"...

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| react-navigation               | 4.3.7
| react-navigation-stack         | 2.0.16
| react-native-safe-area-context | 0.6.0
| react-native                   | 0.61.4
| expo                           | also yes
| node                           | 12
| npm or yarn                    | yarn

**Comment by satya164** [comment] 2020-04-16 22:58
Duplicate of https://github.com/react-navigation/react-navigation/issues/6995

**Closed by satya164** 2020-04-16 22:58 UTC
Labels: bug, version-4
