### ISSUE TITLE
DrawerNav starts on screen with RTL language

### ISSUE THREAD

**Issue by dkpalmer** [react-navigation/react-navigation#270] opened 2017-02-10 06:44 UTC
We're currently implementing RTL support. When setting Arabic as the default language, the DrawerNavigation start position is on screen:

![simulator screen shot feb 9 2017 11 34 48 pm](https://cloud.githubusercontent.com/assets/2394698/22816764/17624b4c-ef21-11e6-9082-1626e504bdf1.png)

And slides out to:

![simulator screen shot feb 9 2017 11 34 56 pm](https://cloud.githubusercontent.com/assets/2394698/22816772/1fe10592-ef21-11e6-8d49-57da4883f7bb.png)

When using a LTR language such as English or French, the menu position starts off screen and slides in as expected:

![simulator screen shot feb 9 2017 11 35 24 pm](https://cloud.githubusercontent.com/assets/2394698/22816789/3c9884ee-ef21-11e6-986a-f85d6a83772f.png)

![simulator screen shot feb 9 2017 11 35 27 pm](https://cloud.githubusercontent.com/assets/2394698/22816793/410e9662-ef21-11e6-9534-e099f6b36cf6.png)

Also for reference, we had to manually configure the drawer to slide in from the right in RTL mode as follows:

```
const Navigator = DrawerNavigator({
  View1: {
    screen: View1Screen,
  },
  View2: {
    screen: View2Screen,
  },
}, {
  drawerPosition: I18nManager.isRTL ? 'right' : 'left',
});
```

react-native: 0.42.0rc
react-navigation: 1.0.0-beta.3

**Comment by yaronlevi** [comment] 2017-02-14 07:53
+1

**Comment by yoavrofe** [comment] 2017-03-29 07:23
+1

**Comment by dkpalmer** [comment] 2017-04-03 21:12
Quick bump. Any chance to get a second set of eyes on this, or any suggestions on places to start if one wanted to look at patching this?

**Comment by annelorraineuy** [comment] 2017-05-05 18:44
+1

**Comment by annelorraineuy** [comment] 2017-05-05 19:12
It looks like this issue might be solved in `react-native-drawer-layout@1.3.0`. https://github.com/react-native-community/react-native-drawer-layout/pull/30

Currently `react-navigation@1.0.0-beta.9` is using `react-native-drawer-layout-polyfill@1.2.0` with dependency on
```
"dependencies": {
    "react-native-drawer-layout": "1.2.0"
  }
```

Is it possible to upgrade just this package? Or do we have to wait for the next react-navigation release?

**Comment by annelorraineuy** [comment] 2017-05-05 20:20
I take it back. I upgraded to 1.3.0 and my drawer is still in the middle of the screen when its closed.

**Comment by annelorraineuy** [comment] 2017-05-05 20:43
cc @DanielMSchmidt

**Comment by DanielMSchmidt** [comment] 2017-05-06 09:24
I am currently working on this 👍

**Comment by AdelHamad** [comment] 2017-05-22 23:19
+1

**Comment by kelset** [comment] 2017-10-07 19:05
Pinging OP @dkpalmer  since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by thisischris** [comment] 2017-10-11 12:28
@kelset This seems to be related to / a duplicate of: https://github.com/react-community/react-navigation/issues/1773. We still experience this issue, and it's essentially rendering the Arabic version of our app unusable. Any pointers would be welcome.

**Comment by kelset** [comment] 2017-10-11 12:52
Hey @thisischris thanks for letting me know. Since this is the older one of the two issues I'm going to close the other one.

First off I think we should ask @DanielMSchmidt if he ever produced any code related to this in the end. It looks like it was fixed for the [project we rely on](https://github.com/react-native-community/react-native-drawer-layout/issues/29#issuecomment-299711350) but since we are already using v1.3.2 I'm not sure.

**Comment by DanielMSchmidt** [comment] 2017-10-12 07:02
@kelset I was under the assumption that it should work in `react-navigation` as it works in the drawer and the react-native-drawer-layout-polyfill version is recent

**Comment by kelset** [comment] 2017-10-12 10:02
@DanielMSchmidt same ><' That's why I don't understand why the bug is still present. Btw what do you think of [this diagnosis](https://github.com/react-community/react-navigation/issues/1773#issuecomment-332128066)?

@thisischris or @dkpalmer or adlahd3 can you post a small snippet that shows the bug in Snack or a repo?

**Comment by brentvatne** [comment] 2018-06-28 00:51
we're using the latest version of react-native-drawer-layout-polyfill so hopefully this is resolved. if not, please create an issue on https://github.com/react-navigation/react-navigation-drawer

**Closed by brentvatne** 2018-06-28 00:51 UTC
Labels: bug, component: Drawer, needs more info

**Comment by deepas96** [comment] 2019-12-17 06:10
@dkpalmer  It worked perfectly for me
