### ISSUE TITLE
7.0.0-alpha `static` router conditional not working on iOS

### ISSUE THREAD

**Issue by b0iq** [react-navigation/react-navigation#11884] opened 2024-03-11 21:49 UTC
### Current behavior

When the context updated it showing blank screen on iOS only

### Expected behavior

it should navigate or replace the current screen

### Reproduction

https://snack.expo.dev/kzNqGjJ0vCaf3-tcFgHrm

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

        "@react-navigation/native": "7.0.0-alpha.12",
        "@react-navigation/native-stack": "7.0.0-alpha.13",
        "react-native-safe-area-context": "^4.9.0",
        "react-native-screens": "^3.29.0",

**Comment by satya164** [comment] 2024-03-11 22:01
You need to provide a runnable repro. I tried the example from the docs on my iPhone and it works as expected https://reactnavigation.org/docs/7.x/auth-flow#implement-the-logic-for-restoring-the-token

**Comment by b0iq** [comment] 2024-03-11 22:24
Dear @satya164, I tried the repro. same issue.
 I found that the issue maybe because of I have enable fabric and new architecture. 

So the question is... is it going to be supported soon?

**Comment by satya164** [comment] 2024-03-11 22:27
Can you open an issue in React Native Screens repo for Fabric?

**Comment by tboba** [comment] 2024-05-06 13:59
Hi @b0iq! I just tested this bug on react-native-screens with version `3.31.1` and I can see this isn't reproducible anymore (I also tested `3.29.0` and the issue was there indeed). Could you check if bumping the version fixes this issue?

**Comment by tboba** [comment] 2024-05-14 14:55
Hi there! Since there's no information about the current situation, let me close this issue for now. However, if you think this issue should be considered again, we'll re-open it for sure!

Cheers 👋

**Closed by tboba** 2024-05-14 14:55 UTC
Labels: bug, library:react-native-screens, platform:ios, repro provided
