### ISSUE TITLE
iOS swipe back gesture is still enabled when using Modal in a StackNavigator

### ISSUE THREAD

**Issue by miyaliunian** [react-navigation/react-navigation#3230] opened 2018-01-05 15:05 UTC
If I open a <Modal> in a screen in a StackNavigator, the swipe back gesture still works. So if the modal is transparent I can see that the screen underneath is swept away.

I expect the swipe back gesture to be disabled when modals are up.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.22
| react-native     | 0.51.0
| node             |
| npm or yarn      |

**Comment by kelset** [comment] 2018-01-05 15:06
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-05 15:06 UTC
