### ISSUE TITLE
drawer bug - android - rn 0.76.3

### ISSUE THREAD

**Issue by nigelrudolf** [react-navigation/react-navigation#12324] opened 2024-12-06 16:02 UTC
### Current behavior

On android, pressing on a drawer item does not navigate to the corresponding screen unless pressed very close to the drawer item text. A video showing this behaviour is included.

Code to reproduce:
```
import './gesture-handler';
import React from 'react';
import {
  Text,
  View,
} from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createDrawerNavigator } from '@react-navigation/drawer';


function App(): React.JSX.Element {

  const Drawer = createDrawerNavigator();

  const HomeScreen = () => {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
  const ProfileScreen = () => {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Profile Screen</Text>
      </View>
    );
  }

  return (
    <NavigationContainer>
     <Drawer.Navigator>
      <Drawer.Screen name="Home" component={HomeScreen} />
      <Drawer.Screen name="Profile" component={ProfileScreen} />
    </Drawer.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

https://www.youtube.com/shorts/1KKELfcDdJE

### Expected behavior

Pressing anywhere across the full width of the drawer item should navigate to the corresponding screen.

### Reproduction

https://github.com/nigelrudolf/drawer-bug

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

  "dependencies": {
    "@react-navigation/drawer": "^7.0.19",
    "@react-navigation/native": "^7.0.13",
    "react": "18.3.1",
    "react-native": "0.76.3",
    "react-native-gesture-handler": "^2.21.2",
    "react-native-reanimated": "^3.16.3",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^4.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "15.0.1",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
    "@react-native/babel-preset": "0.76.3",
    "@react-native/eslint-config": "0.76.3",
    "@react-native/metro-config": "0.76.3",
    "@react-native/typescript-config": "0.76.3",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.3.1",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}

**Comment by nigelrudolf** [comment] 2024-12-06 16:07
repro: https://github.com/nigelrudolf/drawer-bug

**Comment by Tobbe** [comment] 2024-12-07 14:36
@nigelrudolf I think I might be seeing the same thing. But for me even if I press on the text it eventually stops working. Like after 10 or 20 navigations it stops responding. And also, if I press outside of the text it will eventually trigger a navigation. If I quickly just keep pressing the same item (outside of the text) for 20-60 seconds it will navigate to the page. Do you see the same behavior?

**Comment by huarlensouza** [comment] 2024-12-08 06:16
I used the version @react-navigation/drawer: "^7.0.19", and it caused the same issue:
![Image](https://github.com/user-attachments/assets/5cdded2b-fef6-4803-8693-c919a1f18ef6)


However, with the version @react-navigation/drawer: "6.7.2", it works perfectly.
![Image](https://github.com/user-attachments/assets/f768c615-ef22-410c-80b1-95ca6f4769f4)

**Comment by dickv** [comment] 2024-12-08 20:29
Same problem ("@react-navigation/drawer": "^7.0.19")

Pressing toggle button => pressing menu item => nothing happens
Pressing toggle button => pressing just in front of menu item text => changes screen
Sliding drawer open => pressing item => works as intended

[Image](https://github.com/user-attachments/assets/9641ae40-312e-4de9-a4ac-b4575ae98a76)

**Comment by redfisher26** [comment] 2024-12-09 17:12
Same problem

**Comment by lovegaoshi** [comment] 2024-12-09 17:53
i want to add this is a newarch problem in my case. If I use v7 with old arch its fine, with new arch it happens about 30% of the time, closing and re-opening the drawers most of the time resolves it.

**Comment by guiac** [comment] 2024-12-10 12:55
Its happening the same thing here. What is the workaround to solve it?

**Comment by Code-Divine** [comment] 2024-12-10 13:14
This is embarrassing how can you simply break core functionality. here is another repo with the bug https://github.com/Code-Divine/rn-drawer-test The repo has nothing, literally nothing but the drawer, and it doesn't work on android.

**Comment by david-phx** [comment] 2024-12-10 23:44
I can confirm that I am experiencing the same issue with Expo version 52.0.18 and React Native 0.76.5 on a Google Pixel. Works fine on Expo 52.0.17 and React Native 0.76.3 though.

This only occurs when the drawer is opened using the hamburger menu, navigation works when the drawer is opened by swiping.

There's another issue #12329 for this bug.

**Closed** 2024-12-12 20:44 UTC
Labels: bug, platform:android, repro provided
