### ISSUE TITLE
Tabbing back fast multiple times results in error

### ISSUE THREAD

**Issue by tknuts** [react-navigation/react-navigation#6820] opened 2020-02-11 12:44 UTC
On iOS device it fails with:

"The action 'POP' with payload {"count: 1"} was not handled by any navigator.

I'm running version 5.0.1

Looks like throttling on navigation is missing.

Regards Thomas

**Comment by WoLewicki** [comment] 2020-02-13 14:01
Could you provide a snack that shows this bug?

**Comment by salvoguastella** [comment] 2020-02-13 16:04
I got the same error on Android emulator.
I'm running version 5.0.1

How to replicate:

- Have to screen with Stack navigation
- Navigate from screen A to screen B
- Spam-click Back on screen B header
- You should get the error as soon you get back to screen A

You'll might have to do this a few times in order to get the error:
`The action 'POP' with payload '{"count":1}' was not handled by any navigator. If you are trying to navigate to a screen, check if the screen exists in your navigator. If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/en/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator.`

Hope it helps,
Salvo

**Comment by neoswallow** [comment] 2020-02-19 17:49
I am running 5.0.5.
I have a similar but slight different problem.
I don't get error but weird stacking issue.

I have screen A, B, C with stack navigation (problem is same whether it's native stack or not).
I navigate from A to B to C.
From C, if I go back to B and to A in rapid (as in no delay between tapping back button as soon as you're able but it doesn't have to be spamming fast) succession, as soon as screen lands on A, it will go to B on its own and back to A.
As this point, if you go to B again, animation direction is reversed as in you're going back to B rather than going forward to B.
And also you don't get back button as if you started stack from B.
So you can't go back to A at this point.

I have redux installed and redux log (from React Native Debugger app) shows 2 pops from C to B and B to A but not that weird ghost stack from A to B to A that happened on its own.

**Comment by kulpubekov** [comment] 2020-02-22 09:04
Hey!

I have several tabs in the bottom navigation (home, songs, dishes, waiter). 
home screen - loaded by default.
 On the screen of the house there are two necessary buttons (songs and dishes). if I first press the tab in the bottom navigation, for example, dishes, and then try to switch from the home screen to the dishes screen, then everything works fine.
 but if I first try to go from home screen to the screen with dishes without clicking on the bottom navigation, then I get the error - **The action 'NAVIGATE' with payload '{"name": "Dishes"}' was not handled by any navigator. If you are trying to navigate to a screen, check if the screen exists in your navigator.**

`import * as React from 'react';
import { Button, View, Text, Platform } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import HomeScreen from '../screens/HomeScreen';
import SongsScreen from '../screens/SongsScreen';
import DishesScreen from '../screens/DishesScreen';
import CallScreen from '../screens/CallScreen';
import OrdersScreen from '../screens/OrdersScreen';
import QueuesScreen from '../screens/QueuesScreen';

const HomeStack = createStackNavigator();
function HomeStackScreen() {
  return (
    <HomeStack.Navigator>
      <HomeStack.Screen name="Home" component={HomeScreen} />
    </HomeStack.Navigator>
  );
}

const SongsStack = createStackNavigator();
function SongsStackScreen() {
  return (
    <SongsStack.Navigator>
      <SongsStack.Screen name="Songs" component={SongsScreen} />
      <SongsStack.Screen name="Queues" component={QueuesScreen} />
    </SongsStack.Navigator>
  );
}

const DishesStack = createStackNavigator();
function DishesStackScreen() {
  return (
    <DishesStack.Navigator>
     <DishesStack.Screen name="Dishes" component={DishesScreen} />
     <DishesStack.Screen name="Orders" component={OrdersScreen} />
    </DishesStack.Navigator>
  );
}


const CallStack = createStackNavigator();

function CallStackScreen() {
  return (
    <CallStack.Navigator>
      <CallStack.Screen name="Call" component={CallScreen} />
    </CallStack.Navigator>
  );
}


const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator
       tabBarOptions={{
               activeTintColor: '#fff',
                labelStyle: {
                  fontSize: 12,
                  color: '#aaa',
                },
                style: {
                  backgroundColor: '#000',
                },
              }}>
        <Tab.Screen name="Home"  component={HomeStackScreen} />
        <Tab.Screen name="Songs" component={SongsStackScreen} />
        <Tab.Screen name="Dishes" component={DishesStackScreen} />
        <Tab.Screen name="Waiter" component={CallStackScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
`

this component from home screen  where i try to change navigation 
`import React  from 'react';
import {Image, TouchableHighlight} from 'react-native';
import styles from './styles';
import MenuButton from '../../assets/images/menu-button.png';
import {withNavigation} from '@react-navigation/compat';

const { buttonImage} = styles;

const TouchableMenu = ({navigation: {navigate, push}}) =>{
  return (
    <TouchableHighlight onPress={() => push('Dishes')}>
      <Image
        source={MenuButton}
        style={buttonImage}
      />
    </TouchableHighlight>
  );
};

export default withNavigation(TouchableMenu)`

Does anyone have any ideas how to solve this problem?

**Comment by neoswallow** [comment] 2020-02-22 18:53
First try name each screen unique.
You assigned same name for tab and each stack screen under tab.
Name Home tab like HomeTab and Dishes tab DishesTab.
See if that makes any difference.
If you're getting same error, then try this:
`navigation.navigate('DishesTab', params: {.screen: 'Dishes', ...otherParams })`

**Comment by osdnk** [comment] 2020-02-24 09:34
This issues should be gone with https://github.com/react-navigation/react-navigation/commit/040f5dbb9dfdf6379425d2590ec021ff5287fbd8

**Comment by KaitoCode** [comment] 2020-02-24 10:55
Hey, i updated my Project and for me the Error still occurs in my iOs Simulator. 
I can't reproduce it 100% in Snack but when you are in a Stack (Home or Settings in my Example) and and going through. Then hitting the Backbutton several times ... it should not be possible to get from the Home/Settings Screen to the Welcome Screen, by hitting an not existing Back Button.

https://snack.expo.io/Bk7Kj7ZEL

**Comment by neoswallow** [comment] 2020-02-24 22:35
I just updated to latest of every navigation packages

    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.7",
    "@react-navigation/drawer": "^5.0.7",
    "@react-navigation/native": "^5.0.7",
    "@react-navigation/native-stack": "^5.0.5",
    "@react-navigation/stack": "^5.0.9",

And our problem (fantom navigation) is still there.

**Comment by osdnk** [comment] 2020-02-26 15:49
I'm looking at this right now and I'll try to fix it today

**Comment by januarioprime** [comment] 2020-03-10 13:42
issue still persists

**Comment by satya164** [comment] 2020-03-18 14:37
This should be fixed in latest version of stack. Closing.

**Closed by satya164** 2020-03-18 14:37 UTC
Labels: bug, needs repro, package:stack

**Comment by margabit** [comment] 2020-03-22 17:50
Any update? Which version will contain the fix?

**Comment by codetker** [comment] 2020-03-26 11:17
Any update? Still exists

**Comment by eramudeep** [comment] 2020-03-30 10:05
i am getting this the action GO_BACK was not handled by any navigator

**Comment by erikfenriz** [comment] 2020-04-01 18:42
Still there: 
![Screen Shot 2020-04-01 at 21 42 35](https://user-images.githubusercontent.com/25347909/78174317-bb39d280-7461-11ea-9381-e1603992237a.png)

**Comment by ax88** [comment] 2020-04-01 20:27
Still here:
"@react-navigation/native": "^5.1.4"
"@react-navigation/stack": "^5.2.9"
<img width="1408" alt="Screenshot 2020-04-01 at 22 26 30" src="https://user-images.githubusercontent.com/2803425/78183316-fd661280-7467-11ea-8340-e0d31d3d54ff.png">

**Comment by 92sajid110** [comment] 2020-04-06 13:50
Any update yet I am getting this error in auth flow in stack navigator.
Note same auth flow copy paste from docs its only works for upper stack or bottom stack at once

**Comment by 92sajid110** [comment] 2020-04-06 13:51
and before update it works well

**Comment by OmarGulzar** [comment] 2020-04-06 14:20
The

**Comment by OmarGulzar** [comment] 2020-04-06 14:25
You should use the name prop of the screen in navigation.navigate().
e.g <Stack.Screen name"xyz" component={X}/> 

navigation.navigate('xyz')

**Comment by lordival** [comment] 2020-04-06 18:07
i am getting this error when trying to navigate from an item within a custom drawer.. 

`            <DrawerItem
                label={`Your trainer: ${props.loggedInUser.trainer}`}
                onPress={() => props.navigation.navigate('Trainer Profile')}
            />
`

**Comment by sabdelkhaliq** [comment] 2020-04-07 17:22
I am also getting the same error...

```
onPress={() => {
                  navigation.navigate('Stack', {
                    screen: 'Deck'
```

export default function Stack() {
```

    return (
      <Stack.Navigator>
        <Stack.Screen name="DeckList">
           {(props) => <DeckList {...props} decks={context.decks} />}
        </Stack.Screen>
        <Stack.Screen name="Deck" component={Deck}>
        </Stack.Screen>
        <Stack.Screen name="DeckCard" component={DeckCard}>
        </Stack.Screen>
        />
      </Stack.Navigator>
    );
}


```
-----------------------

```

export default function Tabs() {
  return (
    <NavigationContainer>
      <MyContext.Consumer>
        {(context) => (
          <Tab.Navigator>
            <Tab.Screen name="Stack">
              <Stack {...props} decks={context.decks}/>
            </Tab.Screen>
            <Tab.Screen name="AddDeck">
              {(props) => (
                <NewDeck {...props} fetchDecks={context.fetchDecks} />
              )}
            </Tab.Screen>
          </Tab.Navigator>
        )}
      </MyContext.Consumer>
    </NavigationContainer>
  );
}



```

**Comment by AurangzaibRamzan** [comment] 2020-04-15 08:31
+1

**Comment by theasc** [comment] 2020-04-15 11:46
+1

**Comment by theasc** [comment] 2020-04-15 12:02
Tried with version @react-navigation/stack 5.2.10 still got the issue.

**Comment by afrojuju1** [comment] 2020-04-15 16:03
Still experiencing this `@react-navigation/stack 5.2.10`

**Comment by slasho** [comment] 2020-04-21 20:55
same here using reac-navigation v5

**Comment by kvlknctk** [comment] 2020-04-30 20:51
This is a big mistake.

**Comment by Selast** [comment] 2020-05-06 10:54
Still there. Any update about this?

**Comment by fmflame** [comment] 2020-05-15 19:31
My issue is pretty much the same: "The action 'setParams' with payload {"count: 1"} was not handled by any navigator"
Here is the scenario: It happens when I click the back button on a screen but then swipe my FlatList right before the back kicks in (takes some time in emulators), which triggers onMomentumScrollEnd that calls setParams.
I have tried to check if maybe my component was unloaded at that point, but nope, it unloads right after the setParams is called. So it must be a bug, right?

**Comment by aspen646** [comment] 2020-05-19 17:30
Hey guys, i waas having an error like this, and i found a solution, my "navigation.navigate('Menu') was inside a AsyncStorage.get().then in a arrow function with response parameter, when i click login or logoff, actually go to the page i pretend, but this error always show, so instead of put navigation.navigate('Menu') inside .then() i put a variable to turn true if sucess inside asyncStorage get, and in the end of the function i made if(variable){navigation.navigate('Menu')} and worked!

![a795e295-5075-4fd6-8097-ffca9079ac98](https://user-images.githubusercontent.com/39605748/82358239-9b904680-99dc-11ea-9d68-693972ad84aa.jpg)

**Comment by karatepicke** [comment] 2020-05-25 14:43
> You should use the name prop of the screen in navigation.navigate().
> e.g <Stack.Screen name"xyz" component={X}/>
> 
> navigation.navigate('xyz')

This fixed the error for me. Previously I was referring the component-name. For anyone having this issue, I'm recommending you give Omar's solution a try.

**Comment by aniket07-git** [comment] 2020-06-08 12:52
Same issue 👎 
console.error: The action 'REPLACE' with payload {"name":"Home"} was not handled by any navigator.

Do you have a screen named 'Home'?

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.

This is a development-only warning and won't be shown in production.

construct
    [native code]:0

**Comment by iamir4g** [comment] 2020-08-01 12:59
i have same isuue. can u solve this?

> Hey guys, i was having an error like this, and i found a solution, my "navigation.navigate('Menu') was inside a AsyncStorage.get().then in a arrow function with response parameter, when i click login or logoff, actually go to the page i pretend, but this error always show, so instead of put navigation.navigate('Menu') inside .then() i put a variable to turn true if sucess inside asyncStorage get, and in the end of the function i made if(variable){navigation.navigate('Menu')} and worked!
> 
> ![a795e295-5075-4fd6-8097-ffca9079ac98](https://user-images.githubusercontent.com/39605748/82358239-9b904680-99dc-11ea-9d68-693972ad84aa.jpg)
> **Note: i'm just a beginner in React Native/Javascript, but i think the navigation can't be handled inside a arrow function with parameters, at least the way i did**

many people have this issue why close this??!!

**Comment by Asinox** [comment] 2020-09-27 19:40
Any update about it? I have the same issue

**Comment by mrlego** [comment] 2020-10-13 00:29
same problem form me... is there any fix for this issue?

**Comment by fvilar** [comment] 2020-11-24 19:00
keep happening:

`"@react-navigation/drawer": "^5.11.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
`

**Comment by Kyvix** [comment] 2020-12-12 17:45
Same Issue Here

**Comment by HY88883** [comment] 2021-01-06 03:23
I successfully solved this problem because of the button delay. If the back button can only be pressed once, then the bug will not appear. You can rewrite the button and limit the number of clicks with code.

 `state = {
    type: false,
      isDisabled:false
  };

    const {type,isDisabled} = this.state;

<BackButton
              isDisabled={isDisabled}
            imgSource={require('@/assets/image/processCenter/close-icon.png')}
            touchStyle={{
              position: 'absolute',
              top: scaleSizeH(8),
              left: scaleSizeW(12),
            }}
            _onPress={() => {
                this.setState({isDisabled:true})
                const {navigation}=this.props
                navigation.pop()
            }}
            imgStyle={{
              width: scaleSizeW(24),
              height: scaleSizeH(24),
            }}
          />
`

`import React, {PureComponent} from 'react';
import {
  View,
  StyleSheet,
  ColorValue,
  StyleProp,
  ViewStyle,
  Image,
  GestureResponderEvent,
} from 'react-native';
import {scaleSizeH, scaleSizeW} from '@/utils/index';
import Touchable from '@/components/Touchable';

interface IProps {
  _onPress?: (event: GestureResponderEvent) => void;
  touchStyle?: object;
  imgSource: any;
  imgStyle?: object;
  isDisabled?:boolean
}
class BackButton extends PureComponent<IProps> {
  static defaultProps = {
    imgStyle: {
      width: scaleSizeW(24),
      height: scaleSizeH(24),
    },
  };
  render() {
    const {_onPress, touchStyle, imgSource, imgStyle,isDisabled} = this.props;
    return (
      <Touchable onPress={_onPress} style={touchStyle} disabled={isDisabled}>
        <Image source={imgSource} style={imgStyle} />
      </Touchable>
    );
  }
}

export default BackButton;
`

**Comment by Sub-Zero-1** [comment] 2021-01-28 10:22
I had an issue, where I got the message "...was not handled by any navigator. Do you have screen name xyz?" It was weired, as it only happend for one screen and only sporadically. I solved it by using a delay.
First navigate to the navigator. Then use a delay to navigate to the screen within the navigator.
```
		this.props.navigation.navigate('YourNavigator')
		// timeout to avoid screen not found error
		setTimeout(() => {
			this.props.navigation.navigate('YourScreenWithinYourNavigator')
		}, 200)
```

**Comment by yogeshcl** [comment] 2021-03-11 16:10
handleBackButtonClick=()=> {
        let canGoBack = this.props.navigation.canGoBack();
        if (canGoBack) {
            this.props.navigation.pop();
        } else {
            console.log("Back button pressed multiple times")       
        }
        return true;
     }

> same problem form me... is there any fix for this issue?

**Comment by jtibrewal09** [comment] 2021-05-17 16:42
I'm using bottom tab navigator and opening the modal component from one of the tab. On calling props.navigation.pop(); inside the modal, it's showing:

<img width="1210" alt="Screenshot 2021-05-17 at 10 11 38 PM" src="https://user-images.githubusercontent.com/13987345/118525507-fc24a180-b75e-11eb-8f32-dca79cafc53e.png">

Any lead on fixing this error will be helpful.

**Comment by WouterFlorijn** [comment] 2021-07-17 13:48
@satya164 @osdnk is there any update on this? I don't see why this is closed. The issue still persists and is very easy to reproduce. It happens with any button that calls `navigation.pop` when pressed, you just need to press it quickly twice.

Of course it's a development-only error, but it's very unelegant and annoying when debugging.

**Comment by satya164** [comment] 2021-07-17 13:59
@WouterFlorijn if you're calling `navigation.pop` multiple times, it's impossible for React Navigation to know if you wanted to call it multiple times or not. For your custom back button., you need to add a debounce or disable the button after pressing it once so that it cannot be tapped multiple times. The built-in back button already does it.

**Comment by stevehs17** [comment] 2022-11-11 02:08
I'm still seeing this:
```
The action 'GO_BACK' was not handled by any navigator.
Is there any screen to go back to?
```

    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@types/react": "18.0.9",
    "@types/react-native": "0.67.6",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.1",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-fast-image": "^8.5.11",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "^2.9.1",
    "react-native-restart": "^0.0.24",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-svg": "^12.3.0",
    "react-native-vector-icons": "^9.1.0",

**Comment by GuidoGagliardini** [comment] 2023-03-08 15:00
Same issue here!

**Comment by abdalla-finder** [comment] 2024-10-10 02:31
Same issue on android swipe back gesture navigation, this is an actual user facing crash and its showing in googleplay

     "react-native": "0.74.5",
     "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/material-bottom-tabs": "^6.2.5",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.3.21",
