### ISSUE TITLE
setParams is not working on callback function

### ISSUE THREAD

**Issue by jbaek7023** [react-navigation/react-navigation#2931] opened 2017-11-08 11:12 UTC
I've been struggling with this problem for days. :(

I posted similar questions on Stackoverflow. But no one could figure it out and now I think it seems like package error, so I'm posting my question here.

### Current Behavior

- setParams is not working on callback function

### Expected Behavior
- setParams is working and I can see changed params on navigationOptions.

### Detail
I drew its flow on diagram for your better understanding.

![hello](https://user-images.githubusercontent.com/23069682/32550316-f6b7b67c-c4cf-11e7-9d42-4b1e02c98fc7.jpg)

(1) - (Tag Screen) I pass selectedStyleIds on Tag Screen.
```
headerRight: (
  <RkButton
    rkType='clear'
    onPress={() => {
      console.log('PRINT STYLE TAG navigation')
      console.log(navigation); 
      navigation.state.paramsFunction.onCheck({selectedStyleIds: navigation.state.params.selectedStyleIds});
      navigation.goBack();
    }}>
    <RkText rkType="header3" style={{marginRight:15, color:'#f64e59'}}>SAVE</RkText>
  </RkButton>
),
```

As you can see onCheck is callback function sent from (Main Screen). It navigates to Tag Screen when I press the tag button

```
  _handleTagStylePress = () => {
    this.props.navigation.navigate('TagStyle', {onCheck: this.onCheck, selectedStyleIds: this.state.selectedStyleIds});
  }
```

(2) - Here is the problem. onCheck (callback function), it can setState but it can't setParams.
```
 onCheck = ({selectedStyleIds}) => {
    console.log('passing here');
    console.log(this.props.navigation); <- You can see its output right below of this code
    console.log(selectedStyleIds); <- this prints [1,2,3,4,5]
    this.props.navigation.setParams({selectedStyleIds}); <- this doesn't work..!
    this.setState({selectedStyleIds}); <- This is working fine. I can see changed selectedStyleIds on Main Screen.
  }
```
console.log(this.props.navigation); output
```
Object {
  "dispatch": [Function anonymous],
  "goBack": [Function goBack],
  "navigate": [Function navigate],
  "setParams": [Function setParams],
  "state": Object {
    "key": "id-1510137161799-6",
    "params": Object {
      ...
      "selectedStyleIds": Array [],
      "text": "",
    },
    "routeName": "AddClotho",
  },
}
```

(3) - From Main Screen navigationOptions, navigation.state.params.selectedStyleIds returns always `Array []` (setParams is not working).

```
headerRight: (
      <RkButton
        rkType='clear'
        onPress={() => {
          let {image, text, bigType, clothType, selectedSeasonIds,
            gender, selectedSizeIds, selectedColorIds, selectedStyleIds,
            brand, location, link, inWardrobe, onlyMe, base64 } = navigation.state.params;
          console.log('onsave');
          console.log(navigation.state.params.selectedStyleIds); <- Array [] 
          console.log(navigation); <- prints empty navigation object with empty selectedStyleIds
          console.log('done');

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.12
| react-native     | https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
| node             | v4.6.1
| npm or yarn      | yarn (0.27.5) and npm (4.6.1)

Please let me know if anything is not clear.
Thanks for your support

**Comment by gaodeng** [comment] 2017-11-08 14:01
I encountered the same problem.
My App Navigation is like this.
```
StackNavigator 
      MainTab
              HomeScreen
              ProfileScreen
      SettingScreen
```
if StackNavigaytor index is 0, HomeScreen And ProfileScreen SetParams is called correctly.

if StackNavigator index is 1, HomeScreen And ProfileScreen 
 SetParams have incorrect behave

I think it caused by here react-navigation/src/routers/StackRouter.js line 150

```javascript

  // Check if a child scene wants to handle the action as long as it is not a reset to the root stack
      if (action.type !== NavigationActions.RESET || action.key !== null) {
        const keyIndex = action.key
          ? StateUtils.indexOf(state, action.key)
          : -1;
        const childIndex = keyIndex >= 0 ? keyIndex : state.index;
        const childRoute = state.routes[childIndex];
        const childRouter = childRouters[childRoute.routeName];
        if (childRouter) {
          const route = childRouter.getStateForAction(action, childRoute);
          if (route === null) {
            return state;
          }
          if (route && route !== childRoute) {
            return StateUtils.replaceAt(state, childRoute.key, route);
          }
        }
      }

```

  https://github.com/react-community/react-navigation/blob/6e4afe2153264491838687436899340dfd6ee6a4/src/routers/StackRouter.js#L150


It should do a recursive search. otherwise, the MainTab Navigator will never have a chance to handle this SetParams,then the HomeScreen's and ProfileScreen's SetParams is dropped

**Comment by jbaek7023** [comment] 2017-11-08 14:08
Wow you are genius. Now I can see what causes the error. 

But I don't understand what your **recursive search** means. Did you mean I have to pass navigation props..??? Can you provide an example code or more explanation? 

Thank you

**Comment by gaodeng** [comment] 2017-11-08 14:21
It's StackRouter's bug,I don't think we have a workaroud here.Hope this problem is quickly fixed。

**Comment by jbaek7023** [comment] 2017-11-08 14:31
@gaodeng wow that's terrible news. But I want to open this issue in case other people can answer to this problem.

**Comment by TheRightChoyce** [comment] 2017-11-09 00:16
I believe I'm running into the same (or similar) issue. 

When I set up my navigation like so:

```
export const MainStack = StackNavigator({
    Home: {
        screen: Home,
    },
    About: {
        screen: About,
    },
}, {
        mode: 'card',
});

export const Root = StackNavigator({
    MainScreen: {
        screen: MainStack,
    },
    ModalScreen: {
        screen: ModalScreen,
    },
},  {
    mode: 'modal',
    headerMode: 'none',
});
```

Then any way I try to call `setParams` fails.

E.g.

```
const setParamsAction = NavigationActions.setParams(
{
    params: { foo: 'bar' },
    key: this.props.navigation.state.params.goBackToKey
});
this.props.navigation.dispatch(setParamsAction);
```

fires the `Navigation/SET_PARAMS` action and I can log it in the router, but nothing happens.

If I simply move the `ModalScreen` into `MainStack`, then the `setParams` works without any other coding change.  

e.g.. this works:

```
export const MainStack = StackNavigator({
    Home: {
        screen: Home,
    },
    About: {
        screen: About,
    },
   ModalScreen: {
        screen: ModalScreen,
    },
}, {
        mode: 'card',
});

export const Root = StackNavigator({
    MainScreen: {
        screen: MainStack,
    },
},  {
    mode: 'modal',
    headerMode: 'none',
});
```

The reason I separated them was it seemed like the easiest way to have a true modal experience. I can work around the issue using the modified navigations stacks, but it took a while to figure out what was causing the issue and @gaodeng's post above pointed me in the right direction.

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
| node             | v8.0.0
| npm or yarn      | yarn 1.2.1

**Comment by jbaek7023** [comment] 2017-11-09 01:29
@TheRightChoyce Thanks for your input! Glad you solved your problem. 

Your StackNavigator looks almost same as mine but mine doesn't work. :(  

**I'm guessing I messed up with my FABs, PostMain, MainScreen. I'm confused. Maybe should I make another StackNavigator for FABs?** 

```
export default StackNavigator ({
  [...]
  PostMain: { <- This is Main Screen (This can't setParams) 
    screen: PostMain
  },
  TagStyle: { <- This is Tag Style
    screen: TagStyleScreen
  },
  [...]
  FABs: { <- I call Main Screen from FABs. (I added this component to screen just in case)
    screen: FABs
  }
```
I rewrote my use case. 



My Navigator
MainTabNavigator > StackNavigator (it has a FABs) {MainScreen, PostMain, FABs, TagStyle ...}

- On MainScreen, it has FABs component to navigate to PostMain. 
- From PostMain, I navigate to TagStyle to tag 
- On TagStyle, setParams and navigate to PostMain (setParams work)
- On PostMain, setParams(NOT WORKING) and navigate to FABs.

**Comment by TheRightChoyce** [comment] 2017-11-09 01:47
One other thing I ran into (after posting) was that if you call `goBack` immediately after the `setParams` then the `goBack` appears to take precedence and you'll never see the results of the `setParams`. I'm not sure if that's intended behavior, but didn't see it documented as such anywhere.

What I did was simply wrap then `goBack` call in a `setTimeout` to force it to run on the next "tick".. e.g. `setTimeout(() => navigation.goBack());`

So in your case.. maybe try this?

```
headerRight: (
  <RkButton
    rkType='clear'
    onPress={() => {
      console.log('PRINT STYLE TAG navigation')
      console.log(navigation); 
      navigation.state.paramsFunction.onCheck({selectedStyleIds: navigation.state.params.selectedStyleIds});
      setTimeout(() => navigation.goBack());
    }}>
    <RkText rkType="header3" style={{marginRight:15, color:'#f64e59'}}>SAVE</RkText>
  </RkButton>
),
```

I'm still pretty new to the library, so just relaying what I discovered through hacking around : )

**Comment by jbaek7023** [comment] 2017-11-09 01:54
@TheRightChoyce On TagStyle screen, setParams is working. 

In case I tried with setTimeout but it's not working :( 

`setTimeout(() => navigation.goBack(); )`

But thank you!

**Comment by jbaek7023** [comment] 2017-11-09 02:27
I have to create custom header in 3 days if this is not working. :(

**Comment by gaodeng** [comment] 2017-11-10 09:35
@jbaek7023 
For StackNavigator, I override the route SetParams like below. I think  the similar approach will work for TabNavigator

```javascript
const defaultGetStateForAction = RootStack.router.getStateForAction;
RootStack.router.getStateForAction = (action, state) => {

  if (action.type === NavigationActions.SET_PARAMS) {



    var result = findRouteAndUpdatePath(action, state.routes);
    // console.log(result);
    return { ...state, routes: result.routes }

    // state.routes=state.routes.slice();



  }

  return defaultGetStateForAction(action, state);
};

function findRouteAndUpdatePath(action, routes, ) {


  var found = false;

  for (var i = 0; i < routes.length; i++) {

    var route = routes[i]

    if (route.routes) {
      result = findRouteAndUpdatePath(action, route.routes)
      found = result.found
    }

    if (found) {

      routes = routes.slice();
      routes[i] = { ...route }
      routes[i].routes = result.routes;
      return { found, routes };
    }

    if (route.key === action.key) {
      routes = routes.slice();
      routes[i] = { ...route, params: action.params }
      found = true;
      break;
    }


  }


  return { found, routes }
}


```
the code snippet is  from my experiment project 
I am implementing a   light / dark theme for it.Need SetParams update the navigator style dynamically, then I encountered this bug.
this workaround maybe can fix your problem two, I put a link here, in case you want to reference
https://github.com/gaodeng/Biu-for-ReadHub

**Comment by jbaek7023** [comment] 2017-11-10 10:02
@gaodeng  Cool. 

I think you are overriding react-navigation package. 

Thanks for sharing code but I think it will be better to create 'custom header' using <View />. I can't use any code that I don't understand on my app :( I thought this is very simple problem

Cheers,
John

**Comment by kesha-antonov** [comment] 2017-11-16 10:20
+1. Please fix this

**Comment by fuxianwei** [comment] 2017-11-19 12:14
+1 This problem is very troublesome

**Comment by jbaek7023** [comment] 2017-11-19 12:20
Please keep this post open for others. It seems like there are many people suffering with StackNavigator's setParams

**Comment by jwrubel** [comment] 2017-11-20 14:18
The `setTimeout()` trick mentioned [here](https://github.com/react-community/react-navigation/issues/1912#issuecomment-327791208) worked for me, in the interim.

**Comment by THPubs** [comment] 2017-12-07 08:37
This method worked for me: https://github.com/react-community/react-navigation/issues/1274#issuecomment-299170607

**Comment by MrHazimAli** [comment] 2017-12-12 08:40
+1 please fix this

**Comment by askarhu** [comment] 2017-12-18 02:34
Please please fix this...off late developing in React Native is getting so frustrating with all these breaking changes and not much of help to keep these packages up to date. While I truly appreciate the tremendous help of the OSS community it's certainly frustrating to see the nature of this and the potential of breaking changes all over the place. This is one of the key components and so please fix it ASAP.

**Comment by brentvatne** [comment] 2018-05-08 00:51
closing because it appears to be resolved. if you can repro, please create a new issue and follow the issue template

**Closed by brentvatne** 2018-05-08 00:51 UTC
Labels: bug, help wanted
