### ISSUE TITLE
Android back button Press lead to exit App After Redux Integration

### ISSUE THREAD

**Issue by Victoriayangx** [react-navigation/react-navigation#3181] opened 2017-12-23 12:06 UTC
**Version**
 "react-native": "0.46.1",
"react-navigation": "^1.0.0-beta.11",

**Expected behaviour**
When I go to second scene and press Android back button, it should back to previous page (like Actions.pop())

**Actual behaviour**
It exit from application from every pages I tried, and this only happens on no-debugger mode.
when i open debugger(Debugger JS Remotely),it is ok to back to previous page, when i close debugger or release a version ,it exitApp again.

**What I do**
1、i turn up the BackHandler.android.js in react-native ,the path is : "react-native/Libraries/Utilities/BackHandler.android.js"， test and found: 
when i open debugger:  subscriptions contains the function: this.onBackAndroid ，and  the param invokeDefault is false.      
when i close debugger: subscriptions is [] ,contains nothing ，and then  the param invokeDefault is true.    

Below is the code:
******App.js:
 componentDidMount() {
    if (Platform.OS == 'android') {
          BackHandler.addEventListener('hardwareBackPress', this.onBackAndroid);
    }
  }

  componentWillUnmount() {
    if (Platform.OS == 'android') {
       BackHandler.removeEventListener('hardwareBackPress',this.onBackAndroid);
    }
  }

  onBackAndroid = () => {
    const routers = this.props.nav.routes;
    console.log("this.props.nav.index",this.props.nav.index);
      if (routers instanceof Array && routers.length > 0 && routers[this.props.nav.index].routeName == "Home") {
        console.log("this.lastBackPressed",this.lastBackPressed);
         if (this.lastBackPressed && this.lastBackPressed + 400 >= Date.now()) {
           setTimeout(()=>{
             BackHandler.exitApp();
           },1500);
         }
        this.lastBackPressed = Date.now();
        Toast.info("双击退出应用", 1);
        return true;
      }
      this.props.dispatch(NavigationActions.back());
     return true;
  };

*******BackHandler.android.js:
RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT, function() {
  var backPressSubscriptions = new Set(_backPressSubscriptions);
  var invokeDefault = true;
  var subscriptions = [...backPressSubscriptions].reverse();
  for (var i = 0; i < subscriptions.length; ++i) {
    if (subscriptions[i]()) {
      invokeDefault = false;
      break;
    }
  }

  if (invokeDefault) {
    BackHandler.exitApp();
  }
});

Pls help ,thanks....

**Comment by aMarCruz** [comment] 2017-12-23 20:30
This works for me:

in your root navigator class:
```
class AppNav extends React.PureComponent {

  constructor (props: Props) {
    super(props)
    this.onBackPress = this.onBackPress.bind(this)
  }

  componentDidMount () {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress)
  }

  componentWillUnmount () {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress)
  }

  onBackPress () {
    const { dispatch } = this.props
    const nav = this.props.nav
    dispatch(NavigationActions.back())
    return nav !== this.props.nav
  }

  // ... etc
}

const mapStateToProps = (state: RootState) => ({
  nav: state.nav,
})

export const AppNavigator = connect(mapStateToProps)(AppNav)
```

**Comment by kelset** [comment] 2017-12-23 21:41
It looks like you are using an old version of RN and of the library, can you try implementing your code according to what @aMarCruz wrote there + what's written [in the docs](https://reactnavigation.org/docs/guides/redux#Handling-the-Hardware-Back-Button-in-Android) **after** you have updated both libraries?

**Comment by Victoriayangx** [comment] 2017-12-24 05:23
i update my code and my library ,but stil failed. when open debugger,it is ok ,when close ,it exitApp again

**Comment by Shhzdmrz** [comment] 2018-01-03 04:37
@aMarCruz  and @kelset there is one problem with this code. It is not exiting the app from the home screen or while the index is zero.
Thank you @aMarCruz

**Comment by austenLacy** [comment] 2018-01-03 16:57
@Victoriayangx 

I am on v0.46.0 of react-native and had the same issue. I tracked the issue down to this file in the react-native code base

https://github.com/facebook/react-native/blob/master/Libraries/Utilities/BackHandler.android.js#L25

When running with the chrome debugger turned off the line

```
var subscriptions = Array.from(_backPressSubscriptions.values()).reverse()
```

always returns an empty array for `subscriptions` which in turn causes the `invokeDefault` variable to stay `true` and the `.exitApp()` function to be called.

After more investigation, I think the issue was discovered and discussed in the following PR https://github.com/facebook/react-native/pull/15182.

Even after copy/pasting the PR change in an older version of RN it did not work most likely caused by the issue described in the PR.

After some *very* slight modifications I got it working by changing to

```javascript
RCTDeviceEventEmitter.addListener(DEVICE_BACK_EVENT, function() {
  var invokeDefault = true;
  var subscriptions = []
  _backPressSubscriptions.forEach(sub => subscriptions.push(sub))

  for (var i = 0; i < subscriptions.reverse().length; ++i) {
    if (subscriptions[i]()) {
      invokeDefault = false;
      break;
    }
  }

  if (invokeDefault) {
    BackHandler.exitApp();
  }
});
```

Simply using a `.forEach` which was the original implementation on the PR before the amended `Array.from` syntax works throughout. 

So you *could* fork react-native and use a modified version, submit a PR though I imagine that will take a little while to be approved and merged upstream, or you can do something similar to what I did which was to override the `RCTDeviceEventEmitter.addListener(...)` for the `hardwareBackPress` event.

```javascript
// other imports
import { BackHandler, DeviceEventEmitter } from 'react-native'

class MyApp extends Component {
  constructor(props) {
    super(props)
    this.backPressSubscriptions = new Set()
  }

  componentDidMount = () => {
    DeviceEventEmitter.removeAllListeners('hardwareBackPress')
    DeviceEventEmitter.addListener('hardwareBackPress', () => {
      let invokeDefault = true
      const subscriptions = []

      this.backPressSubscriptions.forEach(sub => subscriptions.push(sub))

      for (let i = 0; i < subscriptions.reverse().length; i += 1) {
        if (subscriptions[i]()) {
          invokeDefault = false
          break
        }
      }

      if (invokeDefault) {
        BackHandler.exitApp()
      }
    })

    this.backPressSubscriptions.add(this.handleHardwareBack)
  }

  componentWillUnmount = () => {
    DeviceEventEmitter.removeAllListeners('hardwareBackPress')
    this.backPressSubscriptions.clear()
  }

  handleHardwareBack = () => { /* do your thing */ }
  
  render() { return <YourApp /> }
}

```

**Comment by felipebraga** [comment] 2018-01-09 17:31
I have a similar issue after add **react-native-pathjs-charts**.

And I didn't find how to solve it.

**Comment by gtaylor44** [comment] 2018-02-02 04:07
austenLacy sovled my issue with react-native-pathjs-charts and BackHandler. The official bug fix is still pending.

https://github.com/facebook/react-native/pull/17820

**Closed** 2018-02-07 20:11 UTC
Labels: needs more info

**Comment by Laurensdc** [comment] 2018-03-12 13:28
For me, @aMarCruz solution works, and the solution in the docs does not.

**Comment by sagarrabadiya** [comment] 2018-04-02 05:49
for me, @aMarCruz works correctly, the docs should add that solution.

**Comment by cristianPerez** [comment] 2018-05-31 05:55
For me, @aMarCruz solution works, and the solution in the docs does not.

**Comment by jordyvanraaij** [comment] 2018-05-31 12:34
+ 1, the example in the docs is not working. The solution of @aMarCruz does!

**Comment by cristianPerez** [comment] 2018-06-19 15:42
I recommend to avoid redux integration with reactNavigation, you can upload to the latest version 2.3.x  and only manage your navigation with a service like this:

```
// NavigationService.js
import { NavigationActions, StackActions } from 'react-navigation';

let navigator;

function setNavigator(navigatorRef) {
  navigator = navigatorRef;
}

const navigate = (routeName, params) => {
  navigator.dispatch(NavigationActions.navigate({
    routeName,
    params,
  }));
};

const reset = (routeName, params = {}) => {
  navigator.dispatch(StackActions.reset({
    index: 0,
    actions: [
      NavigationActions.navigate({ routeName, params }),
    ],
  }));
};

const resetAll = (routeName, params = {}) => {
  navigator.dispatch(StackActions.reset({
    index: 0,
    actions: [
      NavigationActions.navigate({ routeName, params }),
    ],
    key: null, // THIS LINE
  }));
};

const popToTop = (options = {}) => {
  navigator.dispatch(StackActions.popToTop(options));
};

// add other navigation functions that you need and export them

export default {
  navigate,
  setTopLevelNavigator,
  reset,
  resetAll,
  popToTop,
};
```
You can call the NavigationService from your actionCreators normally, and your android backbutton works normal, without redux integration.

**Comment by YashGadle** [comment] 2018-08-19 16:02
Hi, I have not used redux instead I am using Context API. My problem only occurs in production builds, whenever I press Hardware Back button it simply exits the app. I can't even use the solution provided by @aMarCruz because I haven't used redux. I am stuck with my app waiting to go into production. Can anyone suggest some workaround?

**Comment by policz** [comment] 2018-09-28 01:47
Firstly my BackHandler works fine, but when i'm Home screen (consider as one or last screen) the app actually navigating to Sign in page(it's throwing the user out of application)
Below are my files

**_AppNavigatorContainer.js_**

class AppNavigatorContainer extends Component {

  addListener = createReduxBoundAddListener("root")

  constructor(props) {
    super(props)
    this.state = {
      didReceiveNotificationThatCanBeHandled: false,
      notification: null,
      didNetworkBecomeUnreachable: false
    }
    this.onBackPress = this.onBackPress.bind(this)
  }
componentWillReceiveProps(nextProps) {
    //TODO: Uncomment once VPN problem is fixed
    // if (nextProps.isNetworkReachable !== this.props.isNetworkReachable) {
    //   this.state.didNetworkBecomeUnreachable = !nextProps.isNetworkReachable
    // }
  }

  componentWillMount() {
      BackHandler.addEventListener('hardwareBackPress', this.onBackPress)
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress)
    //TODO: Uncomment once VPN problem is fixed
    // stopListening()
  }

    onBackPress() {
    console.log(this.props);
    const { dispatch, navigationState } = this.props
    dispatch(NavigationActions.back());
    return true;
    }


**_AppNavigator.js_**

import React from 'react'
import {
  StackNavigator,
  addNavigationHelpers
} from 'react-navigation';
import stackConfiguration from './stackConfiguration'
import routeConfiguration from './routeConfiguration'

export const AppNavigator = StackNavigator(
  routeConfiguration,
  stackConfiguration
);

export default ({
  dispatch,
  navigationState,
  addListener
}) => {
  return (
    <AppNavigator navigation={addNavigationHelpers({
      dispatch,
      state: navigationState,
      addListener
    })} />
  )
}

**Comment by policz** [comment] 2018-09-28 01:48
Firstly my BackHandler works fine, but when i'm on Home screen (consider as one or last screen) the app actually navigating to Sign in page(it's throwing the user out of application)
Below are my files

AppNavigatorContainer.js

class AppNavigatorContainer extends Component {

addListener = createReduxBoundAddListener("root")

constructor(props) {
super(props)
this.state = {
didReceiveNotificationThatCanBeHandled: false,
notification: null,
didNetworkBecomeUnreachable: false
}
this.onBackPress = this.onBackPress.bind(this)
}
componentWillReceiveProps(nextProps) {
//TODO: Uncomment once VPN problem is fixed
// if (nextProps.isNetworkReachable !== this.props.isNetworkReachable) {
// this.state.didNetworkBecomeUnreachable = !nextProps.isNetworkReachable
// }
}

componentWillMount() {
BackHandler.addEventListener('hardwareBackPress', this.onBackPress)
}

componentWillUnmount() {
BackHandler.removeEventListener('hardwareBackPress', this.onBackPress)
//TODO: Uncomment once VPN problem is fixed
// stopListening()
}

onBackPress() {
console.log(this.props);
const { dispatch, navigationState } = this.props
dispatch(NavigationActions.back());
return true;
}
AppNavigator.js

import React from 'react'
import {
StackNavigator,
addNavigationHelpers
} from 'react-navigation';
import stackConfiguration from './stackConfiguration'
import routeConfiguration from './routeConfiguration'

export const AppNavigator = StackNavigator(
routeConfiguration,
stackConfiguration
);

export default ({
dispatch,
navigationState,
addListener
}) => {
return (
<AppNavigator navigation={addNavigationHelpers({
dispatch,
state: navigationState,
addListener
})} />
)
}

**Comment by NaveenJayaram94** [comment] 2018-11-01 15:59
> Hi, I have not used redux instead I am using Context API. My problem only occurs in production builds, whenever I press Hardware Back button it simply exits the app. I can't even use the solution provided by @aMarCruz because I haven't used redux. I am stuck with my app waiting to go into production. Can anyone suggest some workaround?

Did you fix the issue, I'm also facing same issue
