### ISSUE TITLE
Typescript failing navigate to specific screen

### ISSUE THREAD

**Issue by theo-m** [react-navigation/react-navigation#6946] opened 2020-02-24 10:49 UTC
**Current Behavior**

- What code are you running and what is happening?

```
Stack(
  APP: Tab(A: ScreenA, B: ScreenB), 
  SETTINGS_PAGES: Stack(C: ScreenC, D: ScreenD)
)
```
ScreenB inherits the composite navigator props from its Tab navigator and root Stack navigator.
From ScreenB I want to navigate to ScreenC, as per the [docs](https://reactnavigation.org/docs/en/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator) I am using this function call:
```jsx
navigator.navigate("SETTINGS_PAGES", {screen: "C"})
```

This works as it's being executed correctly, but typescript fails:

```
[rn:typecheck] src/views/ProfilePage/ProfileHome.tsx(44,33): error TS2345: Argument of type '["SETTINGS_PAGES", { screen: string; }]' is not assignable to parameter of type '["SETTINGS_PAGES"] | ["SETTINGS_PAGES", undefined]'.
[rn:typecheck]   Type '["SETTINGS_PAGES", { screen: string; }]' is not assignable to type '["SETTINGS_PAGES", undefined]'.
[rn:typecheck]     Type '{ screen: string; }' is not assignable to type 'undefined'.
```

I think the reason is that the types file is not respecting the doc, I'm on 5.1.4 and the typing is:
```typescript
    /**
     * Navigate to a route in current navigation tree.
     *
     * @param name Name of the route to navigate to.
     * @param [params] Params object for the route.
     */
    navigate<RouteName extends keyof ParamList>(...args: ParamList[RouteName] extends undefined | any ? [RouteName] | [RouteName, ParamList[RouteName]] : [RouteName, ParamList[RouteName]]): void;
    /**
     * Navigate to a route in current navigation tree.
     *
     * @param route Object with `key` or `name` for the route to navigate to, and a `params` object.
     */
    navigate<RouteName extends keyof ParamList>(route: {
        key: string;
        params?: ParamList[RouteName];
    } | {
        name: RouteName;
        key?: string;
        params: ParamList[RouteName];
    }): void;
```
**Expected Behavior**

- What do you expect should be happening?

Typescript should not fail

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.0.5 |
| react-native                   | 0.61.5 |
| expo                           | not using expo |

**Comment by shagun121** [comment] 2020-02-24 11:30
https://youtu.be/ucWLMWo4uDM Check this video to understand how to use it with typescript
(VIDEO IS IN HINDI)

**Comment by theo-m** [comment] 2020-02-24 12:45
Hi @shagun121, thanks for the help but I don't think it applies in this case.

**Comment by theo-m** [comment] 2020-02-24 13:31
Somehow found that `navigator.push` works with typescript, this is the solution I'm keeping as of now. Leaving the issue open as I believe the documentation should make this clearer.

**Comment by theo-m** [comment] 2020-02-24 16:53
Leaving the issue open as I believe the docs are stale w.r.t. to typescript, but I can get my way with:
```jsx
navigation.navigate({ name: "PROFILE", key: "APP" })
```

**Comment by satya164** [comment] 2020-03-18 14:44
Duplicate of #6931

**Closed by satya164** 2020-03-18 14:44 UTC
Labels: bug

**Comment by HAFDIAHMED** [comment] 2021-11-09 10:44
i have the same issue
