### ISSUE TITLE
TabNavigator nested TabNavigator does not work properly

### ISSUE THREAD

**Issue by XueMary** [react-navigation/react-navigation#3192] opened 2017-12-27 09:20 UTC
The master TabNavigator works normally, but the TabNavigator nested in the TabNavigator slides the exception and the contents are not displayed

**Comment by Ajith-Pandian** [comment] 2017-12-27 11:44
@XueMary Please provide more information and code snippets. It will help to describe your problem clearly.

**Comment by Ajith-Pandian** [comment] 2017-12-27 12:07
@XueMary Please provide related screenshots and code snippets. That will help to describe your problem more clearly.

**Comment by ShayanJavadi** [comment] 2017-12-27 22:36
@XueMary Add a code snippet and I'll be able to help you with this. I've done a few nested TabNavigators in my apps.

**Comment by kelset** [comment] 2017-12-29 10:54
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

That said, I think it's already been reported here https://github.com/react-navigation/react-navigation/issues/1805 so please read there before posting again.

**Closed by kelset** 2017-12-29 10:54 UTC
