### ISSUE TITLE
Syntax Error Typescript (import type )

### ISSUE THREAD

**Issue by gauravroyzz** [react-navigation/react-navigation#9247] opened 2021-01-25 08:05 UTC
Below is the error which im getting for typescript syntax while the app opens.

SyntaxError: User/node_modules/@react-navigation/native/src/useBackButton.tsx: Unexpected token (3:12)

`import * as React from 'react';
  2 | import { BackHandler } from 'react-native';
> 3 | import type { NavigationContainerRef } from '@react-navigation/core';`

the error is in the 3rd line with import type, and its also present in other files too.

Package.json has as devDependencies :

`
"@babel/core": "^7.12.10",
    "@babel/plugin-proposal-decorators": "^7.12.12",
    "@babel/runtime": "^7.6.2",
      "metro-react-native-babel-preset": "^0.64.0",
`

and these as dependencies:

`
"@react-navigation/bottom-tabs": "^5.2.1",
    "@react-navigation/drawer": "^5.11.5",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
`

**Comment by gauravroyzz** [comment] 2021-01-25 08:06
yes
@github-actions

**Comment by marakoss** [comment] 2021-01-26 09:52
Same issue here. Confirming. I've tried multiple configurations with babel. No luck yet.

**Comment by gauravroyzz** [comment] 2021-01-27 17:12
@marakoss ive tried with deleting yarn.lock and reinstalling, and it worked somehow. 
But this types of error are so bad.

**Comment by marakoss** [comment] 2021-01-27 17:29
@gauravroyzz my project did also magically started working after i updated EXPO-cli from 4.0.7 to 4.1.0. But before that even the base Tabs template from Expo (expo40+node14+yarn+typescript+navigation) didn't compile. I assume some combination of versions just don't work nicely with each other, which is really frustrating for novice RN developers. Anyways if we can't reproduce it anymore, we should probably close this.

**Comment by dbbk** [comment] 2021-01-30 17:57
This is still an issue, the base tabs template in Expo simply doesn't build.

**Comment by marakoss** [comment] 2021-01-30 18:00
@dbbk please post your full yarn.lock file (or package-lock). And add details of what version of node, npm, yarn, expo-cli r u using. I've already update mine and it works, So I don't want to touch it.

**Comment by satya164** [comment] 2021-02-11 14:24
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.

**Closed by satya164** 2021-02-11 14:24 UTC
Labels: bug, needs repro

**Comment by jsbls** [comment] 2021-03-10 16:30
@dbbk Add @babel/core as a **global** dependency, since `expo-cli` apparently doesn't recognize project-specific deps. Should help.

**Comment by raajnadar** [comment] 2021-03-10 17:05
Don't add `@babel/core` globally instead use `expo-cli` inside each project as dev dependency. Installing a package globally is no good.
