### ISSUE TITLE
Using @react-navigation/stack 6.1.0 causes app to freeze (android)，How to solve it?

### ISSUE THREAD

**Issue by flaplee** [react-navigation/react-navigation#11514] opened 2023-08-01 04:53 UTC
### Current behavior

Normal when not using @react-navigation/stack version 6.1.0，
Probabilistic occurrence when using @react-navigation/stack version 6.1.0，When it happens, the page is stuck, unable to operate, unable to return, and can only kill the APP and restart it。

### Expected behavior

Normal when using @react-navigation/stack version 6.1.0，not to freeze (android)

### Reproduction

none

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

"@react-native-async-storage/async-storage": "1.17.10",
    "@react-navigation/native": "6.0.6",
    "@react-navigation/stack": "6.1.0",
    "crypto-js": "4.1.1",
    "fbjs": "3.0.4",
    "i18n-js": "3.8.0",
    "intl-pluralrules": "1.3.1",
    "lodash": "4.17.21",
    "mobx": "6.1.8",
    "mobx-react": "7.0.0",
    "react": "17.0.1",
    "react-native": "0.64.4",
    "react-native-color-matrix-image-filters": "5.2.10",
    "react-native-dotenv": "3.3.1",
    "react-native-fast-image": "8.5.11",
    "react-native-fs": "2.18.0",
    "react-native-gesture-handler": "2.1.0",
    "react-native-htmlview": "0.16.0",
    "react-native-linear-gradient": "2.5.6",
    "react-native-root-siblings": "4.1.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "2.18.1",
    "react-native-sqlite-storage": "6.0.1",
    "react-native-swipe-list-view": "3.2.9",
    "react-native-webview": "11.17.2",

**Comment by okwasniewski** [comment] 2023-08-08 09:02
Closing as duplicate of #11515

**Closed by okwasniewski** 2023-08-08 09:02 UTC
Labels: bug, needs repro, platform:android
