### ISSUE TITLE
Screen flicker on Android using stack navigation

### ISSUE THREAD

**Issue by erhathaway** [react-navigation/react-navigation#1679] opened 2017-05-24 21:10 UTC
### Current Behavior
On Android only, there is a very noticeable screen flicker when navigating between screens in stack navigation with a dark background. This is much harder to see on a light background (such as in the react-navigation Expo demo), but it is still there...

### Expected Behavior
No screen flicker when using dark backgrounds with stack navigation on Android

### Environment
Currently using react-native-create-app, but this bug is also present on the react-navigation Expo demo (https://exp.host/@react-navigation/NavigationPlayground)

```
    "expo": "^16.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.43.4",
    "react-navigation": "^1.0.0-beta.11"
```

**Comment by rziehl** [comment] 2017-05-27 19:58
Can confirm this is happening to me too on Android (7.1.2 on a Nexus 5X). Very simple setup:

```
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-navigation": "^1.0.0-beta.9"
```

I have a TabNavigator embedded within a StackNavigator. The home screen is two tabs and one is a list, when you tap a list item, it pushes a new screen and the white flicker is fairly visible.

```
const MainScreenNavigator = TabNavigator({
    Home: { screen: HomeTab },
    List: { screen: ListTab },
}, {
  tabBarOptions: {
    ...
    style: {
      backgroundColor: 'rgba(121, 85, 72, 1.0)'
    }
  },
});

const AwesomeProject = StackNavigator({
  RootScreen: { screen: MainScreenNavigator },
  ListItemViewScreen: { screen: ListItemViewScreen }
});
```

**Comment by FredyC** [comment] 2017-07-12 17:39
I am curious, did you find some solution for this? The only thing that helps is setting `animationEnabled: false` although I would like to keep the animation so it's not a very viable option.

**Comment by rziehl** [comment] 2017-07-12 17:50
@FredyC unfortunately I didn't. For my project, I actually dropped react-navigation entirely and made a single view app with dynamically updating components instead for simplicity's sake. I'll probably revisit react-navigation in future for a different project.

**Comment by erhathaway** [comment] 2017-07-12 18:26
@FredyC I haven't found a solution yet. `animationEnabled: false` didn't work for me. I switched to tab navigation and hid the tab bar... Once this gets fixed, I'll switch back to stack navigation.

**Comment by FredyC** [comment] 2017-07-12 19:38
@rziehl  Yea, I am thinking about the same, in its basic functionality, it's just about rendering different components based on the state. 

@erhathaway That's strange. I am having this issue with TabNavigator with hidden tabs. Do you perhaps have some other settings there that could influence this? I have this only so far...
```
  swipeEnabled: false,
  animationEnabled: false,
  navigationOptions: {
    tabBarVisible: false,
  },
```

**Comment by kddc** [comment] 2017-09-19 15:28
I experienced the same issue like described in the first post

**Comment by kelset** [comment] 2017-11-04 09:04
Pinging OP @erhathaway since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by kelset** [comment] 2017-11-12 10:25
Hi there @erhathaway ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by JuanCAlpizar** [comment] 2017-12-08 00:23
@kelset  sorr for being late to the party, but it's still happening on the latest `1.0.0-beta.21`

**Comment by kelset** [comment] 2017-12-08 09:54
@JuanCAlpizar 
> If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by HafizAhmedMoon** [comment] 2018-02-19 06:58
I was having the same issue and `containerStyle` was set to transparent. Remove `containerStyle` or make `backgroundColor` to black, this make it unnoticeable.

```
transitionConfig: () => ({
    containerStyle: {
      backgroundColor: "#000",
    }
  })
```

**Closed** 2018-05-08 01:08 UTC
Labels: bug

**Comment by flyskywhy** [comment] 2018-12-21 07:46
When use DrawerNavigator and StackNavigator, need:

    cardStyle: {
        backgroundColor: 'transparent',
    },

and need:

use [react-native-root-view-background](https://github.com/johniak/react-native-root-view-background) to setRootViewBackgroundColor('black')

**Comment by elirangoshen** [comment] 2019-03-12 15:05
i'm still having that issue.. with RN 0.57 and react navigation 3, when i'm navigating to the drawer navigator stack.
I added the below code and it helped in the stack navigator.. but when i transition to the drawer navigator so it show me white flickering during that transition. 

`   cardStyle: {
      backgroundColor: "transparent",
      opacity: 1,
    },
    transitionConfig: () => ({
        containerStyle: {
          backgroundColor: "transparent",
        },
        transitionSpec: {
          // For an instant transition
          duration: 0,
          useNativeDriver: true,
        },
    }),`

**Comment by Dror-Bar** [comment] 2019-03-23 14:09
Thanks, this worked for me:
`cardStyle: { opacity: 1 }`

Example of use:
```
const RootNavigator = createStackNavigator({
    Login: { screen: Login },
    Home: { screen: Home }
},
    {
        initialRouteName: 'Login',
        cardStyle: { opacity: 1 } // Prevent white flicker on Android when navigating between screens
    }
);
```

**Comment by jhoanborges** [comment] 2019-07-22 16:24
i still facing the same issue on android

**Comment by jhoanborges** [comment] 2019-07-22 16:40
After trying everything, i figured it out that i was using this package, so i jsut removed it 
[](https://github.com/kmagiera/react-native-screens)

**Comment by callmejm** [comment] 2019-09-09 15:47
> Thanks, this worked for me:
> `cardStyle: { opacity: 1 }`
> 
> Example of use:
> 
> ```
> const RootNavigator = createStackNavigator({
>     Login: { screen: Login },
>     Home: { screen: Home }
> },
>     {
>         initialRouteName: 'Login',
>         cardStyle: { opacity: 1 } // Prevent white flicker on Android when navigating between screens
>     }
> );
> ```

Hi, but this will cause when closing the stack scene not smooth

**Comment by nihp** [comment] 2019-11-12 09:58
Header section is flickering for me. Any solutions

**Comment by nihp** [comment] 2019-11-13 08:53
@all any solution to avoid flickering in iOS?

**Comment by 378978764** [comment] 2020-06-09 15:41
> After trying everything, i figured it out that i was using this package, so i jsut removed it
> [react-native-screens](https://github.com/kmagiera/react-native-screens)

But `@react-navigatin/stack` requires `react-native-screens`, if I remove `react-native-screens` by `yarn remove react-native-screens`, the following error occurs:
```
error: bundling failed: Error: Unable to resolve module `react-native-screens` from `node_modules/@react-navigation/stack/src/views/Screens.tsx`: react-native-screens could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/sheng/Documents/local/TestAnimationNone/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```
How to solve this?

**Comment by rohitbindal** [comment] 2020-12-04 14:10
Ok, I found a solution in RN 0.63.3 and react-navigation 5 ( tested on android).  
 Screen was flickering when i was using `createStackNavigator`:  
```import React from "react";
import LoginScreen from "../screens/Login/LoginScreen";
import SplashScreen from "../screens/GettingStarted/SplashScreen";
import { createStackNavigator } from "@react-navigation/stack";

const RootStack = createStackNavigator();

const RootStackNavigator = ({ navigation }) => (
  <RootStack.Navigator>
    <RootStack.Screen name="SplashScreen" component={SplashScreen} />
    <RootStack.Screen name="LoginScreen" component={LoginScreen} />
  </RootStack.Navigator>
);
export default RootStackNavigator;
```  
Instead of this, using `createNativeStackNavigator` from `react-native-screens/native-stack` and changing `stackAnimation` property to anything but default worked like a charm.  

```import React from "react";
import LoginScreen from "../screens/Login/LoginScreen";
import SplashScreen from "../screens/GettingStarted/SplashScreen";
import { enableScreens } from "react-native-screens";
import { createNativeStackNavigator } from "react-native-screens/native-stack";

enableScreens();
const RootStack = createNativeStackNavigator();

const RootStackNavigator = ({ navigation }) => (
  <RootStack.Navigator
    screenOptions={{
      headerShown: false,
      stackAnimation: "none",
    }}
  >
    <RootStack.Screen name="SplashScreen" component={SplashScreen} />
    <RootStack.Screen name="LoginScreen" component={LoginScreen} />
  </RootStack.Navigator>
);
export default RootStackNavigator;
```  
React Navigation Docs: [createNativeStackNavigator](https://reactnavigation.org/docs/native-stack-navigator)
API: [createNativeStackNavigator](https://github.com/software-mansion/react-native-screens/tree/master/native-stack)

**Comment by ronherrema** [comment] 2020-12-28 11:46
@rohitbindal I wonder if there is an equivalent solution when using createBottomTabNavigator()?

**Comment by iqqmuT** [comment] 2020-12-31 21:56
I had this issue on Android 10 and using these libraries:
React Native: 0.63.4
React Navigation 5.x

Disabling transition animations fixed the issue for me:
```js
const Stack = createStackNavigator();

<Stack.Navigator screenOptions={{ animationEnabled: false }}>
  <Stack.Screen name="Home" component={HomeScreen} />
</Stack.Navigator>
```

**Comment by luanws** [comment] 2021-04-15 21:28
Try to install the "react-native-screens" dependency using expo-cli:

`expo install react-native-screens`

**Comment by ParteekSJ** [comment] 2021-07-26 22:41
I found a simple solution.
Wrap your <Stack.Navigator> in a <View> and set the flex to 1 and a background colour of your choice.

<View style={{flex: 1, backgroundColor: 'black'}}> // <-- LIKE THIS

**Comment by ronherrema** [comment] 2021-08-11 10:34
I finally discovered that when using the bottom tab navigator, the key to eliminating the flicker was to add `import { enableScreens } from "react-native-screens"`, and then at the beginning of my function to add `enableScreens(true)`.

**Comment by brunolcarlos** [comment] 2021-09-20 23:47
Put the <View> outside your NavigationContainer with flex: 1 and backgroundColor with the color you like

**Comment by blujedis** [comment] 2021-10-31 03:59
> I found a simple solution. Wrap your <Stack.Navigator> in a View and set the flex to 1 and a background colour of your choice.
> 
> <View style={{flex: 1, backgroundColor: 'black'}}> // <-- LIKE THIS

This is by far the best solution. The issue is if you have both light/dark modes it's not a simple to just set the background. On Android it would only work for one of the modes. So by going this route you can use a hook or whatever and grab your theme and just set it to the `navigation.colors.background` and everything plays nice.

**Comment by Ifechukwudaniel** [comment] 2021-11-07 20:03
This worked for me 

`
        animation:"none"
`

**Comment by Meenakshi-Kannan-Preludesys** [comment] 2021-12-21 11:43
Hi, I'm using RN 0.63 and react-native-router-flux 4.3.1, when i'm navigating to the drawer navigator stack.
when I'm doing the transition in router -> scene I'm getting small flickering during that transition. Anyone please aware of that give me a suggestion on this.

**Comment by Yogeshgs3694** [comment] 2021-12-21 11:46
Hi, I'm using RN 0.63 and react-native-router-flux 4.3.1, when i'm navigating to the drawer navigator stack. when I'm doing the transition in router -> scene I'm getting small flickering during that transition. Anyone please aware of that give me a suggestion on this.

**Comment by abbous** [comment] 2022-09-26 10:48
```
<NavigationContainer theme={{ colors: { background: "#22232b" } }}> if you're using dark theme you need to customize your navigation theme
<Stack.Navigator
          screenOptions={{
            headerShown: false,
            animationEnabled: false, // prevent animation when navigating
          }}
        >
</Stack.Navigator>
```

**Comment by eyale** [comment] 2022-10-20 15:35
Faced same issue with flickering content of the screen if

headerShown: true,

None of the issues above not helped.

**Comment by waslinux** [comment] 2022-12-01 23:15
> This worked for me
> 
> `animation:"none"`

saved me!!!!       <Stack.Navigator screenOptions={{animation: 'none'}}>
TNX Guy!

**Comment by jerinwega** [comment] 2022-12-28 07:44
presentation: Platform.OS === ANDROID ? 'transparentModal' : 'modal',
 
 hope this is what everyone's looking for

**Comment by elton11220** [comment] 2023-02-21 06:40
> presentation: Platform.OS === ANDROID ? 'transparentModal' : 'modal',
> 
> hope this is what everyone's looking for

Excellent!! But the transition anim is different from when it is 'card' or 'modal'

**Comment by jerinwega** [comment] 2023-02-21 08:55
@elton11220 Yeah! couldn't find anything better
