### ISSUE TITLE
Slow transition  when navigating between screens

### ISSUE THREAD

**Issue by anastely** [react-navigation/react-navigation#6942] opened 2020-02-23 17:43 UTC
I'm trying to use redux with react-navigation to use state from a redux store for rendering different Bottom Tabs based on it.
It's Works and render Bottom Tabs bassed on user login state as I want.

But I have an issue, It's **Slow Transitions** when to navigate from **Tab to tab or Screen or just open Drawer!**

**Code**
Root RN config file "Root.js"

```
const loginRoutes = {
  Home: {
    screen: Home,
    navigationOptions: {
      title: 'Home',
    },
  },
  Browse: {
    screen: Browse,
    navigationOptions: {
      title: 'Browse',
    },
  },
  Search: {
    screen: Search,
    navigationOptions: {
      title: 'Search',
    },
  },
  Radio: {
    screen: Radio,
    navigationOptions: {
      title: 'Radio',
    },
  },
  Library: {
    screen: YourLibrary,
    navigationOptions: {
      title: 'Library',
    },
  },
};

const noLoginRoutes = {
  Home: {
    screen: Home,
    navigationOptions: {
      title: 'Home',
    },
  },
  Browse: {
    screen: Browse,
    navigationOptions: {
      title: 'Browse',
    },
  },
  Search: {
    screen: Search,
    navigationOptions: {
      title: 'Search',
    },
  },
  Radio: {
    screen: Radio,
    navigationOptions: {
      title: 'Radio',
    },
  },
};



const routes = {
....
   Profile: {screen: Profile},
  Album: {screen: Album},
  Genre: {screen: Genre, navigationOptions: {headerShown: false}},
  Player: {screen: Player},
....
};



const Root = ({isLogin}) => {
  const Container = createAppContainer(
    createDrawerNavigator(
      {
        // ...drawerRoutes,
        App: createStackNavigator(
          {
            ...routes,
            Tabs: createBottomTabNavigator(
              isLogin ? loginRoutes : noLoginRoutes,
              tabsConfig,
            ),
          },
          routesConfig,
        ),
      },
      drawerConfig,
    ),
  );

  return <Container />;
};

const mapStateToProps = state => {
  return {
    isLogin: state.user.isLogin,
  };
};

export default connect(mapStateToProps)(Root);


**App.js**

export default class App extends React.Component {

  render() {
    return (
      <Provider store={store}>
        <PersistGate loading={renderLoading} persistor={persistor}>
          <Root />
        </PersistGate>
      </Provider>
    );
  }
}

```

Video 

[Here](https://i.imgur.com/PL4yVZR.mp4)

>     "react-native": "0.61.5",
>     "react-navigation": "^4.1.0",
>     "react-navigation-drawer": "^2.3.3",
>     "react-navigation-stack": "^2.0.16",
>     "react-navigation-tabs": "^2.7.0",

**Comment by ansal-exp** [comment] 2020-02-24 07:27
Same for me. I switched back to version 3.9.1 but it behaves the same. Very very slow transitions. 

:-)

**Comment by anastely** [comment] 2020-02-24 07:40
@ansal-exp hmm, So that's not related to my code?🤔

**Comment by osdnk** [comment] 2020-02-24 10:35
Can you make some snack example?

**Comment by anastely** [comment] 2020-02-24 10:59
@osdnk  Hey, check this [one](https://snack.expo.io/@lekgwaraj/redux-dynamic-routes) "it's an example Not contain my own screens data"  it's work well on snack :/ 
but as you see in the video it's slow to respond.
BTW I don't use expo if were wondering

**Comment by satya164** [comment] 2020-03-06 15:26
> it's work well on snack

You need to provide code that reproduces your problem

**Comment by satya164** [comment] 2020-03-18 14:36
Closing due to no repro.

**Closed by satya164** 2020-03-18 14:36 UTC
Labels: bug, needs more info, needs repro
