### ISSUE TITLE
Unable to resolve module `@react-navigation/native`

### ISSUE THREAD

**Issue by Kisepro** [react-navigation/react-navigation#5306] opened 2018-11-29 11:03 UTC
Hello,

Since I upgraded react-native I get this error.
I followed the instructions and have deleted package.lock.json but still not working.

```
error: bundling failed: Error: Unable to resolve module `@react-navigation/native` from `C:\Project\myBjjGit\project\node_modules\react-navigation\src\react-navigation.js`: Module `@react-navigation/native` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (C:\Project\myBjjGit\project\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (C:\Project\myBjjGit\project\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (C:\Project\myBjjGit\project\node_modules\metro\src\node-haste\DependencyGraph.js:219:16)
    at Object.resolve (C:\Project\myBjjGit\project\node_modules\metro\src\lib\transformHelpers.js:141:30)
    at dependencies.map.result (C:\Project\myBjjGit\project\node_modules\metro\src\DeltaBundler\traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Project\myBjjGit\project\node_modules\metro\src\DeltaBundler\traverseDependencies.js:369:18)
    at C:\Project\myBjjGit\project\node_modules\metro\src\DeltaBundler\traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (C:\Project\myBjjGit\project\node_modules\metro\src\DeltaBundler\traverseDependencies.js:298:30)
```

software | version
-- | --
react-navigation | 2.18.2
react-native | 0.57.5
react | 16.6.1

**Comment by Kisepro** [comment] 2018-11-29 11:03
May be related to https://github.com/react-navigation/react-navigation/issues/5281

**Comment by luco** [comment] 2018-11-29 16:22
+1 on this

**Comment by brentvatne** [comment] 2018-11-29 21:43
did you follow the steps from the error message where it says "to resolve try the following"?

closing because no repro provided as required by template

**Closed by brentvatne** 2018-11-29 21:43 UTC

**Comment by Kisepro** [comment] 2018-11-30 11:20
> Since I upgraded react-native I get this error.
> **I followed the instructions and have deleted package.lock.json but still not working**.

**Comment by brentvatne** [comment] 2018-11-30 19:13
sorry i don't know what could be causing the problem, it's something unrelated to react-navigation though so there's not much i can do. if you create a new issue and follow the template (in particular provide a reproducible example) i could look though
