### ISSUE TITLE
error: uncompiled PNG file passed  as argument. Must be compiled first into .flat file..

### ISSUE THREAD

**Issue by adsellor** [react-navigation/react-navigation#3315] opened 2018-01-19 21:47 UTC
### Current Behavior
While trying to build production apk with gradle v4.3 and gradle tools 3.0 process crashes. I have come across this issue (https://github.com/react-navigation/react-navigation/issues/3097) and tried to set `android.enableAapt2=false` in `[root]\android\gradle.properties`. However, it dosn't help, as deleting assets from `drawable-*` folders, as well as other steps suggested the mentioned above issue.
### Expected Behavior
Bundling without issues with AAPT2.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.49.5
| node             | 9.3.0
| npm   | 5.6.0

**Comment by kelset** [comment] 2018-01-19 22:11
Duplicate of #3097

**Closed by kelset** 2018-01-19 22:11 UTC

**Comment by shayegh** [comment] 2019-02-21 16:36
Hi
use this config
org.gradle.configureondemand=true
in your android/gradle.properties

**Comment by arled** [comment] 2019-03-20 13:52
Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.

**Comment by lokeshpathak7** [comment] 2019-08-06 12:06
hello i have same issue did anyone got the suitable answer please help me
