### ISSUE TITLE
Screen doesn't re-render when navigationOptions changed

### ISSUE THREAD

**Issue by outaTiME** [react-navigation/react-navigation#4271] opened 2018-05-18 22:13 UTC
I'm using sharing navigation options (https://reactnavigation.org/docs/en/headers.html#sharing-common-navigationoptions-across-screens) to share the same set of options in my screens, for some reason when I update the `screenprops` the `navigationOptions` re-executes and returns the new result but the screen doesn't get updated.

This works good in react-navigation v1 but not in v2.

I checked if the problem could be related to the new options resolution (https://reactnavigation.org/docs/en/navigation-options-resolution.html) but seems it's not the case.

I'm attaching both test cases where you can see the different behaviors, when you tap "Update theme" in v1 both the header background and the hexa code label are updated, in v2 just label is updated but not the header (it's just getting updated when you navigate)

React Navigation (v1)
- https://snack.expo.io/HyxA86hAf

React Navigation (v2) (ISSUE)
- https://snack.expo.io/SJUV_6nCz

**Comment by maxdavidson** [comment] 2018-06-05 22:57
The issue seems to be that there's a some sort of change detection (line 24) in Navigator's `getDerivedStateFromProps` that doesn't take `screenProps` into account, so `router.getScreenOptions(childNavigation, screenProps)` is only run when the route state changed.

https://github.com/react-navigation/react-navigation/blob/7f86362e86e14e13f3709278ca709b896662b22b/src/navigators/createNavigator.js#L16-L79

**Comment by brentvatne** [comment] 2018-06-05 22:58
@maxdavidson - this issue was reported before that change

**Comment by maxdavidson** [comment] 2018-06-05 23:18
@brentvatne Hmm, maybe my issue unrelated then, but `screenProps` updates do work fine in v2.0.4 before https://github.com/react-navigation/react-navigation/pull/4424 was merged.

I'm injecting it on the root navigator and picking it up in navigationOptions on a tab navigator to update the tab labels.

```typescript
Profile: {
  screen: Profile,
  navigationOptions({ screenProps }) {
    return {
      tabBarLabel: getTabBarLabel(screenProps.authStatus),
      tabBarIcon: getTabBarIcon(screenProps.authStatus),
    };
  },
},
```

**Comment by brentvatne** [comment] 2018-06-07 01:06
@maxdavidson - can you create an issue for that?

**Comment by brentvatne** [comment] 2018-06-07 01:07
@outaTiME - any chance you could provide a more barebones example of that? the snacks provided are pretty large and contain lots of unrelated code

**Comment by jamuhl** [comment] 2018-06-08 13:02
Not sure we got the issue also in v2.0.4.

We pass down a translation function `t` which gets changed on language change: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/App.js#L16

To set screen title: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/pages/Home.js#L9

But title (language) does only change when navigating to Page2 and then back to Home

Worked in <v2.x.x but not anymore in v2.x.x

**Comment by brentvatne** [comment] 2018-06-08 16:08
@jamuhl - can you post a minimal reproducible example (https://stackoverflow.com/help/mcve) on https://snack.expo.io or in a github repo?

**Comment by jamuhl** [comment] 2018-06-08 17:54
That sample is already stripped down...just adds i18n to the mix which you can ignore -> just look at it as a fresh function passed to props -> screenProps (there is not much i could strip away there)

npm i, npm start

as i myself do not really use that in production and just maintain react-i18next do not expect me to take additional time to build an additional even more minimal samples. Just was a suggestion to help as at least it's a lot more minimal than the other sample of @outaTiME ...

**Comment by brentvatne** [comment] 2018-06-08 23:40
@jamuhl - thanks. no need to be sassy

**Closed** 2018-06-09 00:35 UTC
Labels: needs repro

**Comment by brentvatne** [comment] 2018-06-09 00:40
you can try out `react-navigation@2.3.0-beta.0` which fixes this issue on the project that @jamuhl shared. i suspect it will be the same for you @outaTiME

**Comment by outaTiME** [comment] 2018-06-10 22:29
Awesome @brentvatne, with the `react-navigation@2.3.0-beta.0` it works as expected 🎉 
Finally I can upgrade my app when version 2.3 of react-navigataion is released.

Thanks !!!

**Comment by jamuhl** [comment] 2018-06-11 07:03
@brentvatne can confirm works with the 2.3.0-beta.0

Didn't meant to sound harsh but might have accidentally done so. So please excuse that.

Thanks for getting the fix up so fast. Keep up the good work - i know from maintaining i18next - it's not always easy.

**Comment by brentvatne** [comment] 2018-06-11 18:00
thanks @outaTiME and @jamuhl! i'll release 2.3.0 later today if all goes well

**Comment by brentvatne** [comment] 2018-06-11 23:04
https://github.com/react-navigation/react-navigation/releases/tag/2.3.0

**Comment by Guy6767** [comment] 2019-09-26 08:35
I am trying to apply themes to my app, but I can't seem to get the tab navigator to re-render when the navigationOptions had changed. The changes are only applied after navigating to a different tab.

I am passing the theme prop with Context API:

```
import StackNavigator from './src/Screens/StackNavigator';
import { ThemesContext } from './src/Context/ThemesContext';

const AppContainer = () => {
  const { theme } = useContext(ThemesContext);

  return <StackNavigator theme={theme} />
}

const App = () => {
  return (
    <View style={styles.container}>
      <ThemesContextProvider>
          <AppContainer />
      </ThemesContextProvider>
    </View>
  );
};
```

I am then using that theme prop to conditionally render the style of the tabBarIcon:

```

const TabsNavigator = createMaterialTopTabNavigator(
    {
    Settings: { 
      screen: SettingsScreen,
      navigationOptions({theme}) {
        return {
          tabBarLabel: "",
          tabBarIcon: ({tintColor}) => (
            <Icon name="settings" color={theme == 'dark' ? 'white' : 'black' } size={28} />
          )
        }
      } 
    }
  }, 
  {
    ...
  }
);
``` 

After modifying the `theme` value with Context API, the change in the `tabBarIcon` is only reflected after navigating to a different tab. I am using **react-navigation 3.12.0**.

**Comment by DanielMarkiel** [comment] 2019-10-25 09:34
@Guy6767 I've got exactly the same problem. Have you found any solution?

**Comment by Guy6767** [comment] 2019-10-27 18:38
@DanielMarkiel Yes. The buttons to toggle the themes in my app was nested inside a screen inside a tab navigator. What I did is call the following function to navigate to the "Tabs" route, then back to the "Settings" screen. This forced the tab icons to refresh, but without the user noticing anything. It's a workaround but it solved it for me.
```
const refreshAction = NavigationActions.navigate({ 
  routeName: 'Tabs',
  action: NavigationActions.navigate({ routeName: 'Settings' }),
});
```
