### ISSUE TITLE
[TabNavigator] scene transitions slow on android

### ISSUE THREAD

**Issue by petermikitsh** [react-navigation/react-navigation#739] opened 2017-03-20 01:28 UTC
Hello, I'm experiencing some performance issues with the `TabNavigator`. I've read through various other reports, so I've omitted the basic 'gotchas' that can perf issues:

- no console.log statements
- no remote debugger attached

Other observations:

- flipping between very basic scenes (e.g., with a single Text element) seems fine
- more complex scenes problematic
- runs fine on iOS (no dropped frames)

![tabnav](https://cloud.githubusercontent.com/assets/1571918/24086695/97d43b96-0cd1-11e7-820e-21e03739bf64.gif)

A 'Performance' section might not be a bad idea in the docs.

Thanks!

**Comment by petermikitsh** [comment] 2017-03-20 02:05
Did a release build and the animations were still dropping frames.

![Uploading release_build.gif…]()

**Comment by satya164** [comment] 2017-03-20 02:18
Can you try this on a real device instead of emulator? I have never seen this issue. It just uses native view pager under the hood, so it's strange that there will be perf issues.

Also the tabs don't re-render when switching, so this page is already rendered and should be fast. Only reason I can think of is something with graphics and the emulator.

**Comment by Rewieer** [comment] 2017-03-20 14:20
@satya164 what if a rerender happens while switching tab (eg fetching data). Might a rerender (either on the next or previous element) cause a lag even through the animation is happening on the UI Thread ?

**Comment by satya164** [comment] 2017-03-20 14:23
No, I don't think so.

**Comment by petermikitsh** [comment] 2017-03-20 16:19
I don't currently have a real device I can test on (lost my USB cable), but I downloaded the [NavigationExample app](https://github.com/react-community/react-navigation/tree/master/examples/NavigationPlayground) and I'm not seeing any dropped frames, which seems to suggest that it may be more an issue with my app, and not the emulator. However, most of these pages in the simulator are pretty simple.

The distinguishing features of 'Home' tab in my app are:
- I make API calls in `componentDidMount`, but those Promises are wrapped in a `InteractionManager.runAfterInteractions` callback.
- I am rendering an SVG document (the triangular mesh) which has 262 `Path` elements. So this scene has a much larger component tree than my 'Submit' and 'Responses' scenes. However, tabs are not re-rendered when switching between them, so it shouldn't impact the transition.

**Comment by satya164** [comment] 2017-03-20 16:39
> lost my USB cable

You can build an APK and send it to your phone for testing.

**Comment by petermikitsh** [comment] 2017-03-20 17:47
Tried the APK build on device. It was crashing. Wasn't going to get too far without logs. So I experimented with removing my large SVG from my Home scene. Somehow, that seems to have fixed performance when switching tabs. So my best guess now is that this is more an issue with `react-native-svg`, possibly connected to https://github.com/react-native-community/react-native-svg/issues/137.

![issue](https://cloud.githubusercontent.com/assets/1571918/24113490/3148bc06-0d5a-11e7-9fde-9b162dcd8d73.gif)

**Comment by farrukhbashir** [comment] 2017-04-26 08:44
I am using the tabNavigator when i Display a Swipable List in one tab then the TabNavigator slow how i resolve this...how to stop rerender in tabNavigator

**Comment by kohchenggee** [comment] 2017-06-14 09:51
I have also tried tabNavigator, if use swipe to move the screen it's quite smooth, but if I tap on the tabs, it's lagging

**Comment by ugiacoman** [comment] 2017-06-23 00:07
@kohchenggee I'm running into the same issue. Have you found a solution?

**Comment by Clowning** [comment] 2017-06-25 16:50
Same as @kohchenggee  ! A solution ? :)

**Comment by allmaxgit** [comment] 2017-06-29 07:07
Very slow transitions on device. Need solution.

**Comment by Buthrakaur** [comment] 2017-09-04 05:58
Poor performance was caused by https://github.com/getsentry/react-native-sentry/issues/158 in my case.

**Comment by SteffeyDev** [comment] 2017-09-05 18:58
I'm not using react-native-sentry and finding that while swiping is fast to load on Android, tapping on the tab bar icon has a notable delay (same as @kohchenggee).

**Comment by matthamil** [comment] 2017-09-15 06:15
Is this issue still occurring in the latest release? If so, can someone post an example app reproducing the problem to expo or [snack](https://snack.expo.io/)?

**Comment by Maxeh** [comment] 2017-09-20 19:58
@kohchenggee have the same issue, did you find a solution?

**Comment by matheusrocha89** [comment] 2017-09-21 19:30
@kohchenggee Having the same issue, did you find any solution?

**Comment by Maxeh** [comment] 2017-09-21 20:19
I actually found a solution. In my case the laggy behavior was caused by a FlatList (ListView) which rendered components of the type "Component". I changed "Component" in the FlatList to "PureComponent" and everything works fine now. I guess the laggy behavior occurred due to re-rendering when tabs were changed.

**Comment by matheusrocha89** [comment] 2017-09-21 23:58
@Maxeh I think my problem is the same as yours, I have FlatList too, I will try your approach and see if I fix this problem in my project

**Comment by allmaxgit** [comment] 2017-09-22 04:11
I have FlatLists on tabs and using PureComponent everywhere.
Works good only without addNavigationHelpers but I need link redux.

**Comment by orest22** [comment] 2017-09-29 00:35
I have the same issue. Any ideas how to solve it?

**Comment by satya164** [comment] 2017-10-08 16:30
https://twitter.com/satya164/status/917061292065738752

**Comment by rvlewerissa** [comment] 2017-10-11 08:17
In my case, it's really fast when I use swipe, but really slow when tapping on the icon the change tab.

**Comment by yasir-netlinks** [comment] 2017-11-19 14:23
I have a case where its slow when I tap on one of the tabs, it responds slow and just to be clear there are no animation issue, it takes a moment before navigating to that Tab, while swiping between that tabs work just fine , no stutters or anything of that sort. I have hooked all the Tabs in redux, and basically all the Tabs (4 tabs) are forms (Im keeping some state in redux for validation). The reason I am saying this because I'm not sure if this behavior is related to a performance issue in react navigation or maybe is because of redux! Any thoughts regarding this would be much appreciated. is there a way we can test this!

**Comment by michelalbers** [comment] 2018-01-02 14:18
Got the same issue here. Swiping is super smooth but tapping the button incredibly slow.

**Comment by powdahound** [comment] 2018-01-02 22:53
Ran into the same issue. Smooth while swiping but button tap was very slow. Resolved by removing all console.log and disabling redux-logger's verbose printing of state while logging actions.

**Comment by napro8509** [comment] 2018-01-03 16:17
help me to create Vertical tab navigator

**Comment by hegelstad** [comment] 2018-01-26 19:42
I got the same issue. Tabs take as much as 2 minutes to change on Genymotion Samsung Galaxy 6.

**Comment by Laurensdc** [comment] 2018-02-02 12:07
Same issue.

**Comment by Laurensdc** [comment] 2018-02-05 07:10
Had issues using this with Native base.

**Comment by brentvatne** [comment] 2018-02-07 20:14
if you have issues with this it may be due to excessive console.log statements, which can slow down your app in development

**Closed by brentvatne** 2018-02-07 20:14 UTC
Labels: bug

**Comment by Laurensdc** [comment] 2018-02-08 11:51
@brentvatne Removing console.logs didn't resolve the issue, also the issue stayed on the production version.
Getting rid of the NativeBase library seems to fix performance issues.

**Comment by michelalbers** [comment] 2018-02-08 11:58
It was native base for me too. Bummer - I really liked their design
