### ISSUE TITLE
Unable to give a transparent color to react navigation fullscreen modal

### ISSUE THREAD

**Issue by romit07** [react-navigation/react-navigation#5268] opened 2018-11-22 08:23 UTC
### Current Behavior

- Unable to give transparent color to fullScreen Modal(StackNavigator), "transparent" color in card style is not having any effect and the background is still white

> {
    mode: "modal",
     cardStyle: {
      backgroundColor: "transparent",
      opacity: 1
     }
  }

- 
![image](https://user-images.githubusercontent.com/5871036/48889547-42ce0500-ee5c-11e8-91e0-799f3114299d.png)

my current code:
```
class ImageDetail extends React.Component {
  render() {
    const modalColor = this.props.navigation.getParam("modalColor");
    return (
      <View
        style={{ flex: 1, flexDirection: "column", justifyContent: "flex-end" }}
      >
        <View
          style={{
            height: "50%",
            width: "100%",
            backgroundColor: "#fff",
            justifyContent: "center"
          }}
        >
          <Text>Testing a modal with transparent background</Text>
        </View>
      </View>
    );
  }
}

const MainNavigator = createStackNavigator(
  {
    BrowserHome: { screen: BrowserHome },
    ImageDetailModal: {
      screen: ImageDetail,
      navigationOptions: {
        header: null
      }
    }
  },
  {
    mode: "modal",
    cardStyle: {
      backgroundColor: "transparent",
      opacity: 1
    }
  }
);
const AppContainer = createAppContainer(MainNavigator);
export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
}

```
### Expected Behavior

- Previous version did not require AppContainer enclosure and this was my code in previous version of react-navigation:
```
class ImageDetail extends React.Component {
  render() {
    const modalColor = this.props.navigation.getParam("modalColor");
    return (
      <View
        style={{ flex: 1, flexDirection: "column", justifyContent: "flex-end" }}
      >
        <View
          style={{
            height: "50%",
            width: "100%",
            backgroundColor: "#fff",
            justifyContent: "center"
          }}
        >
          <Text>Testing a modal with transparent background</Text>
        </View>
      </View>
    );
  }
}

const MainNavigator = createStackNavigator(
  {
    BrowserHome: { screen: BrowserHome },
    ImageDetailModal: {
      screen: ImageDetail,
      navigationOptions: {
        header: null
      }
    }
  },
  {
    mode: "modal",
    cardStyle: {
      backgroundColor: "transparent",
      opacity: 1
    }
  }
);
export default class App extends React.Component {
  render() {
    return <MainNavigator />;
  }
}

```
![image](https://user-images.githubusercontent.com/5871036/48889693-b3752180-ee5c-11e8-9f89-382314556922.png)

Here "Go to next screen" button in screen: BrowserHome while a fullscreen modal named ImageDetail is presented over the top having backgroundColor as transparent

### How to reproduce

- Set "transparent" as background color in cardStyle

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.0
| react-native     | 0.57.0
| node             | 11.0.0
| yarn      | 1.12.3

**Comment by eriveltonelias** [comment] 2018-11-22 12:36
Hi @romit07! 

thanks for your report. I'll close this one because is related with https://github.com/react-navigation/react-navigation/issues/5253 if not, please tell me to reopen.

**Closed by eriveltonelias** 2018-11-22 12:36 UTC

**Comment by brentvatne** [comment] 2018-11-26 19:45
you should use the `transparentCard` option: https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig

**Comment by NguyenHoangMinh1996** [comment] 2018-11-30 08:56
> you should use the `transparentCard` option: https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig
i have a purpose to make modal-screen like romit07 once, but stuck at this. 
      transparentCard: true  ----> make my screen turn black. 
![nov-30-2018 15-55-08](https://user-images.githubusercontent.com/32347846/49278787-5dd1f200-f4b8-11e8-8b33-36786b0c3192.gif)

**Comment by brentvatne** [comment] 2018-11-30 19:14
@NguyenHoangMinh1996 - please create a new issue and follow the template, including a link to the reproducible example
