### ISSUE TITLE
Animation Warning - Sending onAnimatedValueUpdate with no listeners registered

### ISSUE THREAD

**Issue by tradebulls** [react-navigation/react-navigation#7839] opened 2020-03-20 07:05 UTC
Hi,

I have multiple stacks in my main navigator and one of them is Bottom Tab Navigator. As we don't have switchNavigator in version 5, we are using reset to clear the previous stack and navigate to a screen.

However, in this case we get a warning "Sending onAnimatedValueUpdate with no listeners registered".
If we set the options animationEnabled: false, the warning is gone but we want the animation to be enabled.

Can anyone help?

**Comment by Bardiamist** [comment] 2020-03-25 03:58
Same problem. That happens when I use `TransitionPresets.ScaleFromCenterAndroid`.

**Comment by a-eid** [comment] 2020-03-25 19:51
same issue happens when

```
    navigation.dispatch(
      CommonActions.reset({
        index: 1,
        routes: [{ name: 'SomeRoute' }],
      }),
    )
``

**Comment by neelchanda** [comment] 2020-04-15 17:14
Same issue here. In Stack.Navigator, I have a conditional returning a set of screens based on the validity of the user's session token.

For example: 
```
<Stack.Navigator>
    {state.token == null 
        ? ( <>AUTH STACK SCREENS</> )
        : ( <>MAIN STACK SCREENS</> )
    }
</Stack.Navigator>
```

When the token is cleared on logout, the app returns to the auth screens (login, sign up, etc.) as expected but with the error `Sending 'onAnimatedValueUpdate' with no listeners registered`

**Comment by LaneRamp** [comment] 2020-04-16 03:05
I see the warning for the exact same reason as https://github.com/react-navigation/react-navigation/issues/7839#issuecomment-614166939. I think this is just a harmless artifact of an asynchronous callback that's triggered before but received after the navigator component is unmounted. If not, would be good to hear what problems this will cause in the long run.

**Comment by martincarstens** [comment] 2020-04-24 03:13
I hope the solution I have is relevant to this topic, but I had the same error using createMaterialTopTabNavigator.

I've wrapped the render in some curly braces with a condition:

```
function TopTabs() {
  const { wait  } = useSelector(state => state.app);
  return (
    <>
      {!wait &&
        <TopTab.Navigator>
          <TopTab.Screen name="Tab1" component={Tab1Screen} />
          <TopTab.Screen name="Tab2" component={Tab2Screen} />
        </TopTab.Navigator>}
    </>
  );
}
```

I have a Redux action that sets `wait` as follows
```
dispatch({
  type: GENERATE_AUTH_TOKEN_SUCCESS,
  isSignedIn: true
})

setInterval(() => {
  dispatch({ type: SET_TOP_TABS_READY })
},0)
```
`SET_TOP_TABS_READY ` sets `wait` to `false` which signals TopTabs to render. That seemed to silence the warning in my case.

My Root navigator looks like:
```
{isSignedIn ? (
  <Tab.Navigator>
    <Tab.Screen name="Home" component={TopTabs} />
    <Tab.Screen name="Settings" component={SettingsScreen} />
   </Tab.Navigator>
) : 
(<Stack.Navigator>
  <Stack.Screen name="SignIn" component={SignInScreen} />
</Stack.Navigator>)}
```

**Comment by matheusf31** [comment] 2020-04-27 20:58
I have same issue, just in IOS.

**Comment by codyng** [comment] 2020-04-30 05:46
Same here.

I have used createMaterialTopTabNavigator() and performing a network request inside the first top tab screen.

**Comment by codyng** [comment] 2020-04-30 05:53
I need to delay a bit to request the HTTP GET to bypass the warning. I think the inner code of react navigation didn't capture the onAnimatedValueUpdate event???

**Comment by matheusf31** [comment] 2020-04-30 17:34
> I have same issue, just in IOS.
> 
> I have tab navigation with stack navigation. If I set the options animationEnabled: false in stack navigation options, the warning is gone but I want the animation to be enabled.
> 
> Can anyone help?

Another thing, this happen when i set unmountOnBlur: true, in the tab navigator

**Comment by osdnk** [comment] 2020-04-30 19:13
hey,
any chance for some snack? 😄

**Comment by StarryFire** [comment] 2020-05-09 18:26
This happened to me too when i navigate from one stack to another stack, both of which have TopTabNavigators inside them which fire api calls via actions in redux saga and display a loader inside them until the data is loaded in redux store. 
There also happens to be a memory leak, i am not sure if this is related to this issue
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SceneView (created by Pager)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (created by PanGestureHandler)
    in PanGestureHandler (created by Pager)
    in Pager (created by TabView)
    in RCTView (created by TabView)
    in TabView (at MaterialTopTabView.tsx:48)
    in MaterialTopTabView (at createMaterialTopTabNavigator.tsx:41)
    in MaterialTopTabNavigator (at TopTabNavigator/index.js:14)
    in TopTabNavigator (at LeadDetails/index.js:100)
    in RCTView (at Container/index.js:23)
    in RCTView (at Container/index.js:12)
    in Container (at LeadDetails/index.js:99)
    in LeadDetailsScreen (at withLoader/index.js:48)
```

**Comment by hengkx** [comment] 2020-06-30 07:25
same problem

**Comment by jbromberg** [comment] 2020-07-01 18:55
I have the same issue whenever sliding backward in a stack to return to the previous page.

**Comment by aristech** [comment] 2020-07-01 19:01
Should we ignore this warning?

**Comment by colopreda** [comment] 2020-07-08 19:48
Same issue here. How should we procede?

**Comment by unicornRainbows** [comment] 2020-07-21 01:00
Same issue.. I guess its just a warning so in release build won't be a problem. App doesn't get affected as far as I can tell so all good.

Think this is where a PR would be appreciated. :) 

<3

**Comment by ankerbachryhl** [comment] 2020-07-25 10:49
Same issue here.

**Comment by MannySAD** [comment] 2020-08-13 09:14
Same issue.

**Comment by crisecheverria** [comment] 2020-08-18 08:17
How to ignore this warning?

**Comment by lucqroz** [comment] 2020-08-20 00:30
Para mim resolveu removendo o mode no StackScreen

**Comment by RRMoelker** [comment] 2020-08-28 13:50
Thank you @crisecheverria .

Let me expand on that answer.
LogBox didn't work for me because I'm not yet on React Native 0.63.

I had to use:
```
YellowBox.ignoreWarnings([
  // See: https://github.com/react-navigation/react-navigation/issues/7839
  'Sending \`onAnimatedValueUpdate\` with no listeners registered.',
]);
```

For even older versions you should use:
```
console.disableYellowBox = [
  // See: https://github.com/react-navigation/react-navigation/issues/7839
  'Sending \`onAnimatedValueUpdate\` with no listeners registered.',
]
```

Here is some background information on the new LogBox and references to the old usage: https://reactnative.dev/blog/2020/07/06/version-0.63#logbox

**Comment by mu-tayyab** [comment] 2020-09-09 12:00
i found the solution its works for me just pass initialRouteName={routes.sellerHome} your drawr stack screen initial screen name
<Drawer.Navigator
        initialRouteName={routes.sellerHome}
        drawerStyle={{backgroundColor: theme.colors.dark}}
        drawerContent={(props) => <DrawerContent {...props} />}>
        <Drawer.Screen name={routes.sellerHome} component={sellerHome} />
        <Drawer.Screen
          name={routes.updateProfileScreen}
          component={UpdateProfile}
        />
       
      </Drawer.Navigator>

**Comment by ManAnRuck** [comment] 2020-09-09 14:42
i had the same issue.
in my case it was because the auth flavour was showing for a very short moment.
i resolved it by returning null instead of a milli second the auth screen and then the main screen.

**Comment by satya164** [comment] 2020-09-14 15:48
Closing since you didn't provide a repro to debug the issue.

**Closed by satya164** 2020-09-14 15:48 UTC
Labels: bug, needs more info, needs repro, package:bottom-tabs

**Comment by duasfh** [comment] 2020-09-25 08:47
@satya164 nice attitude

**Comment by yarapolana** [comment] 2020-09-25 17:31
@satya164 unfortunately this is a harder task to create a repo since it happens on different occasions.
for example in my case if you navigate quickly to a nested screen this would happen same if you went back too quick after navigating in.
I think at least let the community have a go on it instead of closing it.

**Comment by dclawson** [comment] 2020-11-06 11:12
> This happened to me too when i navigate from one stack to another stack, both of which have TopTabNavigators inside them which fire api calls via actions in redux saga and display a loader inside them until the data is loaded in redux store.
> There also happens to be a memory leak, i am not sure if this is related to this issue
> 
> ```
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
>     in SceneView (created by Pager)
>     in RCTView (at createAnimatedComponent.js:233)
>     in AnimatedComponent(Component) (created by PanGestureHandler)
>     in PanGestureHandler (created by Pager)
>     in Pager (created by TabView)
>     in RCTView (created by TabView)
>     in TabView (at MaterialTopTabView.tsx:48)
>     in MaterialTopTabView (at createMaterialTopTabNavigator.tsx:41)
>     in MaterialTopTabNavigator (at TopTabNavigator/index.js:14)
>     in TopTabNavigator (at LeadDetails/index.js:100)
>     in RCTView (at Container/index.js:23)
>     in RCTView (at Container/index.js:12)
>     in Container (at LeadDetails/index.js:99)
>     in LeadDetailsScreen (at withLoader/index.js:48)
> ```

I have this exact error, did you manage to progress with this at all?  Memory leak is causing my app to crash when deep linked through from a push notification.

**Comment by StarryFire** [comment] 2020-11-06 11:16
@dclawson Hi, this problem still occurs in my app but i have decided to ignore it since it doesn't really affect the overall working of the app.

This has never crashed my app though.

**Comment by ghasemikasra39** [comment] 2020-11-10 22:15
I am getting the same warning. Any solution?

**Comment by promit13** [comment] 2020-11-22 23:18
I get the same warning. And my app becomes irresponsive.

**Comment by gre-dev** [comment] 2020-11-23 01:29
Same (after 8 months of opening the issue).

**Comment by IamMasterWayne** [comment] 2020-12-01 09:59
**+1**
Facing..
Sending `onAnimatedValueUpdate` with no listeners registered

**Comment by Merlier** [comment] 2020-12-02 17:00
Same :+1: 
I'm trying to repro the warning in an isolated manner but not easy

**Comment by tonypangs** [comment] 2020-12-04 09:05
Same +1 but not always reproducible

**Comment by gd996** [comment] 2020-12-11 14:03
I get this as well, very hard to reproduce because it just pops out here and there. It happens when I go back with iOS (swipe back), using StackNavigator alone (nothing else).

**Comment by Merlier** [comment] 2020-12-11 16:33
It seems to be linked to memory leaks (like an async task running). I succeeded to reduce the frequency of that warning. But sometimes there is still one appearing.

**Comment by Zygro** [comment] 2020-12-17 15:38
Still an issue

**Comment by nelsonprsousa** [comment] 2020-12-17 23:31
> I get this as well, very hard to reproduce because it just pops out here and there. It happens when I go back with iOS (swipe back), using StackNavigator alone (nothing else).

We are also getting this warning. We'll try to provide a repo with this problem during the next few weeks...

**Comment by cbrdev28** [comment] 2020-12-18 15:50
I've also observed the same warning.
In a few words, I'm using a `StackNavigator` which will render different screens based on the `authToken`.
The warning doesn't appear very often, but I saw it when:
- I forced kill the app
- Re-run the app
- Let it attempt to asynchronously fetch the `authToken` and re-render based on that.

**Comment by mohity777** [comment] 2021-01-16 22:26
same. Any updates?

**Comment by patricktan98** [comment] 2021-01-30 06:20
Do any PR or patches solve this?

**Comment by truongluutpp** [comment] 2021-02-02 11:04
> same issue happens when this code is executed...
> 
> ```js
>     navigation.dispatch(
>       CommonActions.reset({
>         index: 1,
>         routes: [{ name: 'SomeRoute' }],
>       }),
>     )
> ```

The problem has resolved. It saves my time

**Comment by yhugow** [comment] 2021-02-12 06:42
In my case I change navigation type into any;

From:
```
import {StackNavigationProp} from '@react-navigation/stack';

type RootStackParamList = {
  MasterPage: {};
};

type MasterPageNavigationProp = StackNavigationProp<
  RootStackParamList,
  'MasterPage'
>;

interface InitialPageProps {
  navigation: MasterPageNavigationProp;
}

interface InitialPageState {}

export default class InitialPage extends React.Component<
  InitialPageProps,
  InitialPageState
> {
  ....
}
 
```

To this:
```
interface InitialPageProps {
  navigation: any;
}

interface InitialPageState {}

export default class InitialPage extends React.Component<
  InitialPageProps,
  InitialPageState
> { 
 ....
}
```


Hope it helps :)

**Comment by benomatis** [comment] 2021-02-21 11:16
> same issue happens when this code is executed...
> 
> ```js
>     navigation.dispatch(
>       CommonActions.reset({
>         index: 1,
>         routes: [{ name: 'SomeRoute' }],
>       }),
>     )
> ```

This actually appears to solve the issue, I believe the key is in increasing the `index` (I had a value of 0 previously, and changed it to 1). I don't know the actual cause, but that's what I changed, and it made the warning go away.

**Comment by benomatis** [comment] 2021-02-21 12:19
From comment https://github.com/react-navigation/react-navigation/issues/7839#issuecomment-604050799 (above)

> same issue happens when this code is executed...
> 
> ```js
>     navigation.dispatch(
>       CommonActions.reset({
>         index: 1,
>         routes: [{ name: 'SomeRoute' }],
>       }),
>     )
> ```

This actually made the warning go away for me. I think the key is the value of `index`, it appears changing its value will prevent the warning appearing. I don't know the reason behind it, but it works.

**Comment by petrovskyi** [comment] 2021-02-25 19:54
just need to change value . For me this works

navigation.reset({
        index: 0,
        routes: [{name: 'Navigation'}],
      });

**Comment by naraB** [comment] 2021-02-27 19:00
> I have the same issue whenever sliding backward in a stack to return to the previous page.

I had the same issue and solved it by specifying the ```initialRouteName``` inside of the ```Stack.Navigator```, just like @mu-tayyab did in ```Drawer.Navigator```

**Comment by cchampou** [comment] 2021-03-09 16:34
I had the issue too. Finally found out that my stack config object was declared in the render function of the component, instead of being created above. I guess new reference of config object passed to the config props caused the issue.

**Comment by cokepizza** [comment] 2021-04-03 19:32
same here

**Comment by kutsan** [comment] 2021-04-05 13:41
I'm also getting this issue and seems like there isn't any fix right now.

**Comment by havi-b** [comment] 2021-04-08 23:37
Also incurring this issue. Im not doing anything particularly weird or taxing either...

Im calling:
`
              navigation.navigate('FinalizeDetails', {
                    _id: item._id,
                    prevScreen: route.name,
                  });
`

**Comment by havi-b** [comment] 2021-04-08 23:38
Also incurring this issue. Im not doing anything particularly weird or taxing either...

Im calling:
`
              navigation.navigate('Details', {
                    _id: item._id,
                  });
`

**Comment by lukasa1993** [comment] 2021-04-09 13:12
> Closing since you didn't provide a repro to debug the issue.

maybe this needs to be reopened ? happens constantly

**Comment by Elpayet** [comment] 2021-04-16 10:27
having same issue here too

**Comment by namantayal** [comment] 2021-04-16 21:16
In my case is was a useEffect without dependency array. After adding dependency array the issue was resolved.

 useEffect(() => {
  }, []  -> Adding this resolved my issue
);

**Comment by maxgfr** [comment] 2021-04-23 10:07
> Same issue here. In Stack.Navigator, I have a conditional returning a set of screens based on the validity of the user's session token.
> 
> For example:
> 
> ```
> <Stack.Navigator>
>     {state.token == null 
>         ? ( <>AUTH STACK SCREENS</> )
>         : ( <>MAIN STACK SCREENS</> )
>     }
> </Stack.Navigator>
> ```
> 
> When the token is cleared on logout, the app returns to the auth screens (login, sign up, etc.) as expected but with the error `Sending 'onAnimatedValueUpdate' with no listeners registered`

I had the same problem. To fix it, I did something like that : 

```
<NavigationContainer>
     {state.token == null 
         ? ( <Stack.Navigator>AUTH STACK SCREENS</Stack.Navigator> )
         : ( <Stack.Navigator>MAIN STACK SCREENS</Stack.Navigator> )
     }
</NavigationContainer>
```

**Comment by petrovskyi** [comment] 2021-04-30 03:11
`  const redirectToNavigation = useCallback(() => {
    navigation.reset({
      index: 1,
      routes: [{name: 'Navigation'}],
    });
  }, [navigation]);

  useEffect(() => {
    if (isFirstOnBoardingCompleted) {
      redirectToNavigation();
    }
  }, [isFirstOnBoardingCompleted, redirectToNavigation]);`

separating function from lifecycle ,helps me to fix this issues !!!

> I had this same problem in **iOS emulator** when I back to last screen with swipe gesture.
> To go to that screen I was calling this onPress event in a TouchableOpacity:
> 
> ```js
> onPress={() => navigation.navigate('foo')}
> ```
> 
> I changed this to:
> 
> ```js
> const goToFoo = () => {
>     navigation.navigate('foo')
> }
> ```
> 
> and in TouchableOpacity...
> 
> ```js
> onPress={() => goToFoo()}
> ```
> 
> ### and the warning disappeared!!
> I'm not sure but I believe this warning is related with component life cycle, maybe RN was not register that listeners correctly because every component mount this listeners created by this function called direct in JSX are erased (or never has been registered)

thx for your answer :)

**Comment by praneeth-hiver** [comment] 2021-05-09 18:21
Happens with StackActions.replace as well

**Comment by vinayr** [comment] 2021-05-15 17:24
The warning message don't appear if I use `setTimeout` for reset.

```
setTimeout(() => {
  navigation.reset({
    index: 0,
    routes: [{ name: 'Login' }],
  });
})
```

**Comment by paul712** [comment] 2021-07-13 08:14
> How to ignore this warning?
> 
> Done!
> `import { LogBox } from 'react-native';`
> `LogBox.ignoreLogs(['Sending...']);`

In Chinese, there's a word called '掩耳盗铃'.

**Comment by Andrea-Arguello** [comment] 2021-08-04 19:37
I am also experiencing this issue, and it only happens when I reset the stack after a successful login, and it sends the warning _twice._ This is done in a sagas using the following function:
`function resetStack(routeName, params) {
  if (_navigator) {
    _navigator.dispatch(
      StackActions.reset({
        index: 0,
        actions: [NavigationActions.navigate(
          {
            routeName,
            params,
          }
        )],
      })
    );
  }
}`

Weirdly enough, I call this function in a few other places, and the warning doesn't seem to pop up.

**Comment by aryanm5** [comment] 2021-09-09 00:28
I get this warning in v6 whenever I attempt to swipe past the last tab, or before the first tab.

**Comment by KrisLau** [comment] 2021-09-21 15:16
Disabling `inlineRequires` also resolves the error. Not sure why but hopefully this will help with troubleshooting

**Comment by keerthivasaa** [comment] 2021-10-02 17:32
> Also incurring this issue. Im not doing anything particularly weird or taxing either...
> 
> Im calling: `navigation.navigate('Details', { _id: item._id, });`

In Details screen, import { useRoute } from '@react-navigation/native' and use const route = useRoute();

**Comment by emclab** [comment] 2021-11-01 19:46
Same warning message with 6.x on IOS when navigate to a nested child screen.

**Comment by juniordeleon013** [comment] 2022-01-30 14:59
I solve this issue by just adding to initialRouteName="YOUR ROUTE" to my  stack navigator

for example:

```
const Stack = createStackNavigator();

export const MyStackNavigation = () => {

  return (
    <Stack.Navigator
      initialRouteName="HomeScreen"
    >
      <Stack.Screen name="HomeScreen" component={HomeScreen} />
    </Stack.Navigator>
  );
}
```

**Comment by khushbujilka22** [comment] 2022-03-08 14:26
I solve this issue by replacing "@react-navigation/stack" with "@react-navigation/native-stack" for stack navigator.

**Comment by shettayyy** [comment] 2022-03-31 18:21
@DesertStrom16 Your solution worked for me. Thank you.

**Comment by camboYY** [comment] 2022-07-27 03:16
> ```js
> 
> ```

this happens to me as well

**Comment by MorenoMdz** [comment] 2022-08-18 18:50
> Hey! This issue is closed and isn't watched by the core team. You are welcome to discuss the issue with others in this thread, but if you think this issue is still valid and needs to be tracked, please open a new issue with a repro.

You are really annoying btw Bot.

**Comment by jparksecurity** [comment] 2022-10-17 20:18
#10628 has repro. So now, can it be fixed?

**Comment by anhnch** [comment] 2022-10-30 11:14
> I solve this issue by replacing "@react-navigation/stack" with "@react-navigation/native-stack" for stack navigator.

You saved my life. This not only dodge the sending onAnimatedValueUpdate with no listeners regsitered, but also get me out of the block issue of screen frozen everytime going back to the previous screen

**Comment by abiliocoelho** [comment] 2022-12-29 22:47
```js
import { LogBox } from "react-native";
LogBox.ignoreLogs(["Sending `onAnimatedValueUpdate` with no listeners registered.",]);
```

**Comment by cohogan** [comment] 2023-03-14 08:37
Has anyone had any luck recently with this issue?

**Comment by juniordeleon013** [comment] 2023-03-15 00:04
> Has anyone had any luck recently with this issue?

Well, I resolved this warning using a setTimeout in the useEffect that call a list of data. 

I don't know exactly why, but I supposed that the data is render when It's still trying to finish the navigation animation, making a conflict, but I'm 100% sure.

useEffect(() => {
        
        setTimeout(() => {
            
            dispatch( GetActiveUsersRequest() );

        }, 300);
        
    }, [])

**Comment by mrWetCookie** [comment] 2023-03-20 03:08
> Hola,
> 
> Tengo varias pilas en mi navegador principal y una de ellas es Bottom Tab Navigator. Como no tenemos switchNavigator en la versión 5, estamos usando restablecer para borrar la pila anterior y navegar a una pantalla.
> 
> Sin embargo, en este caso recibimos una advertencia "Enviando onAnimatedValueUpdate sin oyentes registrados". Si configuramos las opciones animationEnabled: false, la advertencia desaparece pero queremos que la animación esté habilitada.
> 
> ¿Alguien puede ayudar?



> Hola,
> 
> Tengo varias pilas en mi navegador principal y una de ellas es Bottom Tab Navigator. Como no tenemos switchNavigator en la versión 5, estamos usando restaurar para borrar la pila anterior y navegar a una pantalla.
> 
> Sin embargo, en este caso recibimos una advertencia "Enviando onAnimatedValueUpdate sin oyentes registrados". Si configuramos las opciones animationEnabled: false, la advertencia desaparece pero queremos que la animación esté habilitada.
> 
> ¿Alguien puede ayudar?
Hola estimado, yo pude resolver ese error solamente con un comando:

import {  LogBox } from 'react-native';

LogBox.ignoreAllLogs();

**Comment by geunee20** [comment] 2023-04-07 09:04
This warning is displayed when I tried to swipe left/right in the left/right most screen of the tab bar(specifically, Material Top Tabs Navigator). Could you just make it possible to swipe left/right at the left/right most screen and switch the screen from left/right most screen to right/left most screen?

**Comment by fadyshawky** [comment] 2023-05-04 08:19
> How to ignore this warning?
> 
> Done! `import { LogBox } from 'react-native';` `LogBox.ignoreLogs(['Sending...']);`

this solution will be a work around to just dismiss the warning but it won't solve the problem.

**Comment by iaroslav-ternovyi** [comment] 2023-07-05 15:22
> I have the same issue whenever sliding backward in a stack to return to the previous page.

I wrote a patch that fixes this issue, maybe it will be helpful for someone


```
diff --git a/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx b/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
index 64a551e..207c737 100755
--- a/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
+++ b/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
@@ -107,6 +107,7 @@ export default class Card extends React.Component<Props> {
   componentDidMount() {
     this.animate({ closing: this.props.closing });
     this.isCurrentlyMounted = true;
+    this.props.gesture.addListener(() => { return });
   }
 
   componentDidUpdate(prevProps: Props) {
@@ -144,6 +145,7 @@ export default class Card extends React.Component<Props> {
     this.props.gesture.stopAnimation();
     this.isCurrentlyMounted = false;
     this.handleEndInteraction();
+    this.props.gesture.removeAllListeners();
   }
 
   private isCurrentlyMounted = false;

``` 
To create one go to `node_modules/@react-navigation/stack/src/views/Stack/Card.tsx` and add those line
<img width="620" alt="image" src="https://github.com/react-navigation/react-navigation/assets/78478548/01bb65aa-e7a3-4a57-a018-7309db7dd413">
`this.props.gesture.addListener(() => { return });`
<img width="483" alt="image" src="https://github.com/react-navigation/react-navigation/assets/78478548/b5fe916c-cbd8-40a9-a37d-4edf19cfd59e">
`this.props.gesture.removeAllListeners();`
than do `npx patch-package @react-navigation/stack` it will create a patch file in our repo so you don't need to change it each time

**Comment by billnbell** [comment] 2023-07-09 02:07
> > I have the same issue whenever sliding backward in a stack to return to the previous page.
> 
> I wrote a patch that fixes this issue, maybe it will be helpful for someone
> 
> ```
> diff --git a/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx b/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
> index 64a551e..207c737 100755
> --- a/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
> +++ b/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
> @@ -107,6 +107,7 @@ export default class Card extends React.Component<Props> {
>    componentDidMount() {
>      this.animate({ closing: this.props.closing });
>      this.isCurrentlyMounted = true;
> +    this.props.gesture.addListener(() => { return });
>    }
>  
>    componentDidUpdate(prevProps: Props) {
> @@ -144,6 +145,7 @@ export default class Card extends React.Component<Props> {
>      this.props.gesture.stopAnimation();
>      this.isCurrentlyMounted = false;
>      this.handleEndInteraction();
> +    this.props.gesture.removeAllListeners();
>    }
>  
>    private isCurrentlyMounted = false;
> ```
> 
> To create one go to `node_modules/@react-navigation/stack/src/views/Stack/Card.tsx` and add those line
> 
> <img alt="image" width="620" src="https://user-images.githubusercontent.com/78478548/251198725-01bb65aa-e7a3-4a57-a018-7309db7dd413.png">
> `this.props.gesture.addListener(() => { return });`
> 
> <img alt="image" width="483" src="https://user-images.githubusercontent.com/78478548/251198772-b5fe916c-cbd8-40a9-a37d-4edf19cfd59e.png">
> `this.props.gesture.removeAllListeners();`
> 
> than do `npx patch-package @react-navigation/stack` it will create a patch file in your repo so you don't need to change it every time.

Can we get a PR and get this committed since it works?

**Comment by billnbell** [comment] 2023-07-09 02:08
Also can we reopen this? [iaroslav-ternovyi](https://github.com/iaroslav-ternovyi)

**Comment by Xaypanya** [comment] 2023-07-18 20:00
> i found the solution its works for me just pass initialRouteName={routes.sellerHome} your drawr stack screen initial screen name <Drawer.Navigator initialRouteName={routes.sellerHome} drawerStyle={{backgroundColor: theme.colors.dark}} drawerContent={(props) => <DrawerContent {...props} />}> <Drawer.Screen name={routes.sellerHome} component={sellerHome} /> <Drawer.Screen name={routes.updateProfileScreen} component={UpdateProfile} />
> 
> ```
>   </Drawer.Navigator>
> ```

Thanks, this works with Stack.Navigator too

**Comment by caixingyue** [comment] 2023-08-04 09:21
I have seen this problem for several years, and many people have encountered it in the process, and I have also encountered it. But no suitable solution was found. Can anyone provide a reasonable solution?

**Comment by dmitryou** [comment] 2023-08-11 03:42
> > Has anyone had any luck recently with this issue?
> 
> Well, I resolved this warning using a setTimeout in the useEffect that call a list of data.
> 
> I don't know exactly why, but I supposed that the data is render when It's still trying to finish the navigation animation, making a conflict, but I'm not 100% sure. So I tried to delay the dispatch in order to let the navigation animation finish, and it works.
> 
> ```
> useEffect(() => {
>         
>         setTimeout(() => {
>             
>             dispatch( GetActiveUsersRequest() );
> 
>         }, 300);
>         
>     }, [])
> ```

In my case was problem to render the Flat List with data, always first time was empty, I wrapped navigation with setTimeout

  const onEditTimeZone = () => {
    dispatch(fetchTimeZone());
    //this setTimeout solves first time load bug for timezones
    setTimeout(() => {
      navigation && navigation.navigate(Screens.TIME_ZONE_EDIT);
    }, 300)
  }

**Comment by ilies-space** [comment] 2023-08-16 17:54
in my case i had this line causing the issue:

    navigation.navigate('Home', { scannedBarcode: scanResult.data }); 

Instead i tried this :


    navigation.removeListener
    navigation.navigate('Home', { scannedBarcode: scanResult.data }); 

Calling **navigation.removeListener** before navigating solved the issue for me.

**Comment by caixingyue** [comment] 2023-08-17 02:03
> in my case i had this line causing the issue:
> 
> ```
> navigation.navigate('Home', { scannedBarcode: scanResult.data }); 
> ```
> 
> Instead i tried this :
> 
> ```
> navigation.removeListener
> navigation.navigate('Home', { scannedBarcode: scanResult.data }); 
> ```
> 
> Calling **navigation.removeListener** before navigating solved the issue for me.

There is no way to solve the actual problem. You try to use createMaterialTopTabNavigator to quickly switch left and right, and the problem still occurs. Currently, the problem is with "fast switching"

**Comment by R4DIC4L** [comment] 2023-08-23 07:11
> i found the solution its works for me just pass initialRouteName={routes.sellerHome} your drawr stack screen initial screen name <Drawer.Navigator initialRouteName={routes.sellerHome} drawerStyle={{backgroundColor: theme.colors.dark}} drawerContent={(props) => <DrawerContent {...props} />}> <Drawer.Screen name={routes.sellerHome} component={sellerHome} /> <Drawer.Screen name={routes.updateProfileScreen} component={UpdateProfile} />
> 
> ```
>   </Drawer.Navigator>
> ```

I have initialRouteName set for all my navigators, but still encounter the warning on iOS only ...

**Comment by barrymichaeldoyle** [comment] 2023-09-18 14:06
Can we reopen this issue please?

**Comment by cyberkaidev** [comment] 2023-09-24 15:44
I have the same problem when I use:
```
navigation.dispatch(
    CommonActions.reset({
        index: 1,
        routes: [{ name: 'TabsRoutes' }],
    }),
);
```

**Comment by watislaf** [comment] 2023-10-25 14:57
same problem

**Comment by GuidoGagliardini** [comment] 2023-11-08 17:49
same issue here, plese reopen this issue. 
```

    "@react-navigation/drawer": "^6.6.5",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "expo": "~49.0.13",
    "react": "18.2.0",
```

**Comment by Saliheen** [comment] 2024-02-06 06:10
> Hey! This issue is closed and isn't watched by the core team. You are welcome to discuss the issue with others in this thread, but if you think this issue is still valid and needs to be tracked, please open a new issue with a repro.

please be quite

**Comment by tnson1307** [comment] 2024-03-07 03:59
> I solve this issue by replacing "@react-navigation/stack" with "@react-navigation/native-stack" for stack navigator.

it's worked for me, thank you

**Comment by Crackiii** [comment] 2024-03-15 13:11
If you have something like

`cons animation = new Animated.Value`


add this:

`animation.addListener(() => { return })`

☝🏻 this worked for me

**Comment by andreirat** [comment] 2024-04-29 12:35
> > I solve this issue by replacing "@react-navigation/stack" with "@react-navigation/native-stack" for stack navigator.
> 
> it's worked for me, thank you

Also worked for me. Thanks!

**Comment by bob-devereux** [comment] 2024-06-18 14:25
Upgrading react-navigation/native from 6.1.8 to 6.1.17 fixed this issue for me.
