### ISSUE TITLE
proposal/fix: StackNavigator RESET action replaces with no animation unless action.direction = 'back' | 'forward' is supplied

### ISSUE THREAD

**Issue by faceyspacey** [react-navigation/react-navigation#1663] opened 2017-05-24 00:29 UTC
Currently the StackNavigator's RESET functionality is half-baked. The various problems are highlighted in this older issue: 

https://github.com/react-community/react-navigation/issues/351#issuecomment-303285227

I think I've come up with the simplest solution that solves the most use-cases:

## StackNavigator RESET Behavior Proposal

- by default the `RESET` action replaces "in place" with **no animation**
- an `action.direction` key lets you choose which way to animate *(regardless of whether there are more or less routes on the stack than before)*. Possible values are: `forward` or `back`, and a third `auto` option, whose direction will automatically be determined based on whether more or less routes were added than existed before.
- the animation is always **one slide forward** or **one slide back**. Animating through many pages at once (like it currently does) is ***NEVER*** the correct user experience. 
- lastly, you can reset a stack without taking the user there in the UI. Often you may want to reset a stack, but the let user manually navigate back to the given stack as a natural course of using the app. This is configurable via: `action.quiet === true`. By default it's falsy. But if it's set to `true`, then all other indexes in your router tree state stay the same :). And the user sees nothing unless he happens to be looking at the reset StackNavigator (i.e. because all other indexes in the state happened to stay the same). Also note: the `quiet` option would be useful in other actions as well, not just RESET--you should be able to target nested routers and update them with any action, and not have to take the user there in the UI. 💯 

## Notes:
*Overall, this solves all problems regarding developer-control of whether the stack is replaced in place without animation vs having animation when it makes sense for the user. In addition, being able to choose direction is important because it's not always the case that if you have less routes you want a back transition. That's the developer's business, not the user's. There may be a perfectly good reason for this. That said `auto` is a must since when you want the reset animated, most of the time the difference in routes gets it right (and since having to dig into current state to make the comparison is a waste of developer energy). Lastly, as far as the 2 new keys introduced--perhaps for consistency they can simply be specialized keys on the `params` object.*

**Comment by ppong** [comment] 2017-05-24 16:16
Here are some other github issues related to reset:
https://github.com/react-community/react-navigation/issues/1672
https://github.com/react-community/react-navigation/issues/1493

**Comment by faceyspacey** [comment] 2017-05-24 18:12
@ppong excellent, maybe that will inspire the maintainers to hit all these birds/issues at once. ...my proposal solves both of those.

**Comment by nicgutierrez** [comment] 2017-05-24 21:05
hey @faceyspacey, did anyone submit a PR for this yet?

**Comment by faceyspacey** [comment] 2017-05-24 21:08
@nicgutierrez no, not yet. I got a few PRs for various things--mainly router related. I'm working my way through understanding the codebase. Soon I'll get to transitioners and animations, which such a PR would rely on. I'll hopefully make a PR at that point in time. But don't let that stop you if you have the time.

**Comment by nicgutierrez** [comment] 2017-05-24 21:10
@faceyspacey that's great to hear. I'm currently very busy at work but I will definitely look into this as well if I can find some time! in the meantime, thank you for taking the time and making the proposal :)

**Comment by ronitslyper** [comment] 2017-06-12 10:35
+1

**Comment by NSLS** [comment] 2017-06-13 23:17
+1

**Comment by 0x6e6562** [comment] 2017-06-14 21:40
+1

**Comment by Jafnee** [comment] 2017-06-15 02:51
merge pls. i want

**Comment by phuongmt** [comment] 2017-06-16 04:51
+1

**Comment by mtacchino** [comment] 2017-06-16 09:28
+1

**Comment by cyakimov** [comment] 2017-06-16 15:02
Rather than keep adding "+1" you can just simply add a 👍 reaction to first comment.

**Comment by mansarip** [comment] 2017-06-22 16:43
Any news about this?

**Comment by hmenzagh** [comment] 2017-06-24 23:42
Is there any mews about that ? Or a known workaround ? Thanks

**Comment by fschai89** [comment] 2017-07-06 08:21
+10

**Comment by hmenzagh** [comment] 2017-07-10 14:28
@faceyspacey  I feel like that's a MAJOR problem .. I'm actualy trying to find anoter navigation plugin because of this .. does anyone know of any workaround or just a plain different navigation solution ?

**Comment by voidstarfire** [comment] 2017-07-20 13:38
Considering making you own one. 
All the navigators I've tried (4 in total) for React Native have all been convoluted and terrible.

react-navigator is full of bugs and missing documentation.

**Comment by sunweiyang** [comment] 2017-08-03 06:34
@NSshentu recently posted this code change in #1493; perhaps it will help inspire a fix for this proposal? One can argue about the approach, but it works quite well for many of us.
gorokhovich/react-navigation@30e6d0c

**Comment by alexkuc** [comment] 2017-08-31 13:15
Anyone else tried gorokhovich/react-navigation@30e6d0c?

**Comment by voidstarfire** [comment] 2017-10-09 09:54
I can suggest Wix react-native-navigation, it's the best one I've used so far.

**Comment by faustoct** [comment] 2018-01-05 22:59
Is there any workaround to achieve the animation back, please?

**Comment by carlos-pereira** [comment] 2018-01-11 17:46
+1

**Comment by pisangGoreng** [comment] 2018-01-19 07:01
+ 1

**Comment by hmenzagh** [comment] 2018-01-19 12:18
I can't believe this hasn't been fixed yet

**Comment by brentvatne** [comment] 2018-01-23 00:37
hey @faceyspacey - thanks for identifying this. can you or someone else who is interested in this feature please translate it into the rfc format as per https://github.com/react-navigation/rfcs? we're moving feature/change requests off of the issues here and into a more formal process (rfc if you know how to design it, https://expo.canny.io/feature-requests if you just want to see someone else do it). thanks!

**Closed by brentvatne** 2018-01-23 00:37 UTC
Labels: feature request, related: reset

**Comment by ericvicenti** [comment] 2018-02-01 20:10
I just landed https://github.com/react-navigation/react-navigation/pull/3400, which addresses a common concern with the reset action, allowing you to specify the key of the navigation state to be reset. Eventually we hope to support `immediate` options on most of the navigation actions, which will allow you to perform navigations without animation

**Comment by evanjmg** [comment] 2018-03-12 16:54
@ericvicenti  I added immediate: true to both reset and action push, I still get an animation back. Is there anything I'm missing?

**Comment by iagorm** [comment] 2018-09-18 14:02
almost 2 years and we still don't have a solution for this?

**Comment by oliver-auka** [comment] 2018-09-18 14:08
Solution: Don't use this library.
I downloaded version v2 recently for a new project, though I'd give it a try. Don't bother, use another navigator. I suggest https://github.com/wix/react-native-navigation it has native transitions and lots of functionality out of the box, keep it simple.

**Comment by alexkuc** [comment] 2018-09-18 14:11
Don't be too harsh on the devs, guys. A year ago, the project had 50% of the issues opened, now it is down to only 96 (with nearly 4k issues closed). A phenomenal work indeed! What I did as a workaround (a year ago) was to create a git patch and apply it. Surely, it's not ideal but it's better than nothing. Finally, from what I can tell is that this issue will be addressed in v1 [source](https://github.com/react-navigation/react-navigation/issues/2585).

**Comment by iagorm** [comment] 2018-09-18 14:15
> Solution: Don't use this library.
> I downloaded version v2 recently for a new project, though I'd give it a try. Don't bother, use another navigator. I suggest https://github.com/wix/react-native-navigation it has native transitions and lots of functionality out of the box, keep it simple.

I think this is not my reality since I already made a lot of screens on the app based on this lib.

@alexkuc  I like the project, I saw the grow this library had in past year, I just want to know if this problem is fixed, nothing more, maybe I can study the stack structure and try to add a solution upon it and make a PR.

**Comment by voidstarfire** [comment] 2018-09-18 14:19
I think it's important to warn people though. I know a CTO who has abandoned React Native because of this library and other developers who hate RN because of this navigator.

I mean it still doesn't include basic navigation functionality :-|

@iagorm it's not too hard to replace the whole navigation, they have some similarities and if you're using TypeScript it'll tell you what you need to change when pushing/popping/resetting etc.

There is away to animate the reset, I have done it but it requires a vast amount of spaghetti code.

**Comment by alexkuc** [comment] 2018-09-18 23:29
@voidstarfire @iagorm Consider looking at this - [react-native-router-flux](https://github.com/aksonov/react-native-router-flux). This should be ridiculously good as not only it is v4, it had 1.3.k commits and 233 contributors. As far as I could tell, this is a _very_ mature router indeed. As a bonus tip: from what I recall, the shortcomings and missing features are available in this router.

**Comment by voidstarfire** [comment] 2018-09-19 07:46
@alexkuc thanks for the tip but this is based of this lib (code on code, bugs on bugs) and as you can see from the demo there is no support for reset animation. It's the same issue. :-)

**Comment by JuBertoo** [comment] 2019-04-11 16:31
Hello ! 
I'm beginner with react navigation. 
@faceyspacey Does your solution still work? 
I can not make it work. 
Would you have an example ?

**Comment by webmasterdragon** [comment] 2019-06-25 10:03
Hi Guys, Any update or solution here?

**Comment by fbartho** [comment] 2019-07-23 22:48
We still would like disable the animation...

**Comment by yoppoy** [comment] 2019-11-12 20:05
Any updates on the reset transition? Thanks

**Comment by satya164** [comment] 2019-11-12 20:41
The animation logic has been rewritten to avoid such unexpected behaviour. You ca use stack 2.0 (https://reactnavigation.org/docs/en/stack-navigator-2.0.html) or react-navigation 5 (https://reactnavigation.org/docs/en/next/stack-navigator.html) to get proper animation behaviour.

**Comment by GuilhermeDaniluski** [comment] 2020-01-14 14:42
> The animation logic has been rewritten to avoid such unexpected behaviour. You ca use stack 2.0 (https://reactnavigation.org/docs/en/stack-navigator-2.0.html) or react-navigation 5 (https://reactnavigation.org/docs/en/next/stack-navigator.html) to get proper animation behaviour.

stack 2.0 link is not working

**Comment by tyleragnew** [comment] 2020-02-24 20:21
@satya164 - do you have the correct link for stack navigator 2.0 or react-nav 5 per above? getting 404s on those links.
