### ISSUE TITLE
Set header title vertically aligned

### ISSUE THREAD

**Issue by panda0603** [react-navigation/react-navigation#4946] opened 2018-09-04 05:44 UTC
I'm trying to get my header title and header left component to be vertically aligned. I've got it horizontally aligned already, but it does not seem to get vertically aligned at all. I've tried alignItems, justifyContent already but no luck :( Any help? 

```
const AppNavigator = createStackNavigator(
  {
    Home: {
      screen: City,
      navigationOptions: () => ({
        title: "select city",
        header: null
      })
    },
    selectCity: {
      screen: citySelect,

      navigationOptions: ({ navigation }) => ({
        title: "Info",
        headerStyle: {
          height: 30,
          backgroundColor: "#FEF253",
        },
        headerTitleStyle: {
          textAlign: 'center',
          alignSelf: 'center',
          justifyContent: "center",
          flex: 1
        },
        headerLeft: (
          <TouchableOpacity onPress={() => { navigation.dispatch(DrawerActions.toggleDrawer()) }}>
            <Feather color="black" size={30} name={"menu"} />
          </TouchableOpacity>),
        headerRight: (<View></View>)
      })
    }
  },
  {
    cardStyle: {
      paddingTop: Expo.Constants.statusBarHeight
    }
  }
);

export default AppNavigator;
```

**Comment by daviscabral** [comment] 2018-09-04 06:52
Can you provide images showing the issue? I recommend that you take a look again in the issue template and fill the gaps in the information.

I always get back to this post when I am with doubts about flex-box or when something is not working as I was expecting - I hope this might be useful for you too: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by panda0603** [comment] 2018-09-04 07:27
![12](https://user-images.githubusercontent.com/34116285/45016331-402ef100-b05f-11e8-9448-cca252f26a93.jpg)
@daviscabral Thanks for the reply. This is the issue. The gray bit above is the status bar

**Comment by daviscabral** [comment] 2018-09-04 08:11
Take a look about the `headerForceInset` property. I believe that's what you are looking for.

Now with the image of the issue, this seems to be a duplicate of #4912.

**Comment by panda0603** [comment] 2018-09-04 09:34
@daviscabral  wow thank you very much the headerForceInset worked indeed. Though, do you know why this works? my case doesn't seem to happen to most of the people, I'm not quite sure why this works

**Comment by eriveltonelias** [comment] 2018-09-13 13:49
Hi @panda0603! 

Please, next time follow the issue template.

**Closed by eriveltonelias** 2018-09-13 13:49 UTC
