### ISSUE TITLE
Header-Height changes when card-modal is being dragged on iOS

### ISSUE THREAD

**Issue by BerkeAras** [react-navigation/react-navigation#10227] opened 2021-12-29 09:01 UTC
### Current behavior

The height of the header inside of a card-style modal on iOS changes as the user drags the modal to the top (rubber-band-effect). (See Video)

https://user-images.githubusercontent.com/36629890/147644036-27c83f8d-4f18-460e-bd88-451dad9c9474.MP4

### Expected behavior

The height of the header should be consistent.

### Reproduction

https://snack.expo.dev/Kf-5XUujGQ

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.10.1
| react-native-gesture-handler           | 2.1.0
| react-native-reanimated                | 2.3.1
| react-native                           | 0.64.3
| expo                                   | 44.0.0
| node                                   | 14.17.0
| npm or yarn                            | yarn 1.22.10

**Comment by satya164** [comment] 2021-12-29 11:34
cc @WoLewicki

**Comment by agata** [comment] 2021-12-30 04:33
I had the same problem.

**Comment by BerkeAras** [comment] 2022-01-01 14:53
@agata Could you fix that?

**Comment by WoLewicki** [comment] 2022-01-03 15:12
Does it happen only if you use expo? If so, I believe it is the same issue as https://github.com/expo/expo/issues/15482 and I think we should close this to keep the discussion in one place.

**Comment by imcrainjames** [comment] 2022-01-28 21:53
Seeing the same thing with `@react-navigation/stack`. Not using an expo managed workflow, but we are using expo modules. Happens intermittently on some devices, all the time on others.

Packages:

- npm, 8.1.2 
- expo, 43.0.5
- node, 16.13.1
- react-native, 0.66.4
- react-native-screens, 3.10.1
- react-native-reanimated, 2.3.1
- react-native-gesture-handler, 2.2.0
- react-native-safe-area-context, 3.3.2
- @react-navigation/native, 6.0.6
- @react-navigation/bottom-tabs, 6.0.9
- @react-navigation/stack, 6.0.11

**Comment by jeffaus** [comment] 2022-04-20 02:12
For those like me encountering the same issue down the line, if you build your app using EAS build and run that you won't have this issue. The issue is only present when running the App through Expo Go for development.

**Comment by WoLewicki** [comment] 2022-04-20 14:15
I will close this issue then since it is not caused by `react-navigation`. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-04-20 14:15 UTC
Labels: bug, platform:ios, repro provided, package:native-stack
