### ISSUE TITLE
backBehaviour: initialRoute not working correctly

### ISSUE THREAD

**Issue by KolenkoJan** [react-navigation/react-navigation#7295] opened 2019-10-03 13:09 UTC
### Current behaviour
Consider having 3 tabs eg: Dashboard, Favorites, FAQ. Steps to reproduce:

1. Land on Dashboard tab (initial tab)
2. Go to Favorites Tab -> deep into favorites tab
3. Back to Dashboard tab
4. Press back by android hardware button.

It navigates to Favorites tab instead of closing the app or putting it to background.

### Expected behaviour

1. Expected to put app in background when pressing back on initial route instead of navigating to another tab if it has other screens active.

2. If pressing back on another tab it goes back in its stack navigator till it reaches initial route and then closes the app.

### Code sample

```
import React from 'react';
import {View, Button, Text} from 'react-native';
import {createAppContainer} from 'react-navigation';
import {createMaterialTopTabNavigator} from 'react-navigation-tabs';

const Screen = () => {
  return (
    <View>
      <Text>Sample Text</Text>
    </View>
  );
};

const Screen1 = ({navigation}) => {
  return (
    <View>
      <Button onPress={() => navigation.navigate("contact2")}>Press Me</Button>
    </View>
  );
};

const ContactNavigator = createStackNavigator(
    {
        contact1: Screen1,
        contact2: Screen,
    },
    {
        headerMode: "none",
        initialRouteName: "contact1"
    }
);

const TabNavigator = createMaterialTopTabNavigator(
  {
    Screen1: Screen,
    Screen2: ContactNavigator,
    Screen3: Screen,
  },
  {
    backBehavior: 'initialRoute',
  },
);

export default createAppContainer(TabNavigator);
```

### Your Environment

| software              | version
| --------------------- | -------
| react-native          | 0.59.9
| react-navigation | 3.12.0

**Comment by satya164** [comment] 2020-03-18 15:41
Duplicate of ##6573

**Closed by satya164** 2020-03-18 15:41 UTC
Labels: package:bottom-tabs, version-4
