### ISSUE TITLE
NavigationProps Index signature missingb [Type checking with TypeScript]

### ISSUE THREAD

**Issue by Elias-Graf** [react-navigation/react-navigation#6755] opened 2020-01-27 14:09 UTC
So if I do:
```
interface SomeProps {
    StackNavigationProp<Screens, 'someScreen'>;
}
```
I get: `Index signature is missing in type 'Screens'`. I've read through your documentation and noticed that you are using
```
type Screens = {
    someScreen: undefined;
};
```
where I'm using (because of eslint rules and I generally prefer interfaces in this case)
```
interface Screens {
    someScreen: undefined;
}
```

It seems to be a known "issue"/design pattern in typescript https://github.com/microsoft/TypeScript/issues/15300. Any chances of "fixing"/changing this?

**Comment by satya164** [comment] 2020-03-18 14:19
Since it's a limitation in TS itself, we can't fix it in the library. Closing since the issue is not actionable for us.

If you figure out a way, feel free to send a pull request.

**Closed by satya164** 2020-03-18 14:19 UTC
Labels: tooling, typescript
