### ISSUE TITLE
TabNavigator nest TabNavigator does't render View

### ISSUE THREAD

**Issue by jokeewu** [react-navigation/react-navigation#3278] opened 2018-01-16 03:03 UTC
### Current Behavior
- TabNavigator nest TabNavigator does't render View.

### Expected Behavior
- TabNavigator nest TabNavigator render View well.

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.26
| react-native     | 0.52.0
| node             | v8.8.0
| npm or yarn      | 5.4.2

**Comment by jokeewu** [comment] 2018-01-16 09:37
![ddsdsdsd](https://user-images.githubusercontent.com/5811682/34981687-36940c3e-fae3-11e7-8273-2ab782d96644.jpeg)

When TabNavigator nest TabNavigator, the second does't render correctly.

The tab slide does't smooth, and tab content does't show.

`RootNavigator.js`

```javascript
export default StackNavigator(
  {
    Main: {
      screen: MainTabNavigator,
      navigationOptions: {
        header: null
      }
    },
}
```

`MainTabNavigator.js`

```javascript
export default TabNavigator(
  {
    Home: {
      screen: HomeTabNavigator,
      navigationOptions: {
        tabBarLabel: '首页',
        title: '首页',
        tabBarIcon: ({ tintColor }) => (
          <Image
            source={require('../assets/images/icon_home.png')}
            style={[styles.tabIcon, {tintColor: tintColor}]}
          />
        ),
        header: null
      }
    },
```

`HomeTabNavigator.js`

```javascript
export default TabNavigator(
  {
    RecommendList: {
      screen: RecommendListScreen,
      navigationOptions: {
        tabBarLabel: '推荐',
        title: '推荐',
        header: null,
      },
    },
    ArticleList: {
      screen: ArticleListScreen,
      navigationOptions: {
        tabBarLabel: '文章',
        title: '文章',
        header: null,
      },
    },
    PictureSetList: {
      screen: PictureSetListScreen,
      navigationOptions: {
        tabBarLabel: '图集',
        title: '图集',
        header: null,
      },
    },
    VideoList: {
      screen: VideoListScreen,
      navigationOptions: {
        tabBarLabel: '视频',
        title: '视频',
        header: null,
      },
    }
  }, 
  {
    headerMode: 'none',
    tabBarComponent: TabBarTop,
    initialRouteName: 'RecommendList',
    tabBarPosition: 'top',
    swipeEnabled: true,
    tabBarOptions: {
      showIcon: false,
      inactiveTintColor: '#4a4a4a',
      activeTintColor: '#e9ae6a',
      indicatorStyle: {
        backgroundColor: '#e9ae6a'
      },
      style: {
        backgroundColor: '#ffffff',
        borderBottomColor: '#ffffff',
      },
      labelStyle: {
        
      }
    },
  }
);
```

**Comment by kelset** [comment] 2018-01-16 09:43
Duplicate of https://github.com/react-navigation/react-navigation/issues/1805#issuecomment-349705594

**Closed by kelset** 2018-01-16 09:43 UTC
Labels: needs more info
