### ISSUE TITLE
Tab Navigator conflicts with my Swiper

### ISSUE THREAD

**Issue by ahmedsamyabdelhay** [react-navigation/react-navigation#3222] opened 2018-01-04 15:24 UTC
I have a swippable deck of cards (the one like in Tinder) in one of the tabs of a Tab Navigator. When I swipe my deck of cards, it often conflicts with the navigation swipe and I get navigated to the next tab. So how to avoid that without disabling swiping.

Also I have a second issue. I have another Tab Navigator nested within the first Tab Navigator. On Android, the inner one screens don't show up. I found other report similar issue and a temporary solution was suggested which is disabling the swiping and the navigation animation (see [here](https://github.com/react-navigation/react-navigation/issues/662#issuecomment-290938479)

**Comment by kelset** [comment] 2018-01-04 17:35
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-04 17:35 UTC
