### ISSUE TITLE
Typescript: Navigating to a screen in a nested navigator

### ISSUE THREAD

**Issue by neiker** [react-navigation/react-navigation#7786] opened 2020-03-11 19:58 UTC
**Current Behavior**

- Navigating to another stack works but TS complains.

**Expected Behavior**

- Don't complain about the types

**How to reproduce**

```ts
type UnloggedStackParamList = {
  Home: undefined;
  SignIn: undefined;
  SignUp: undefined;
};

type SignUpParamList = {
  SignUpEmail: undefined;
  SignUpPassword: {
    email: string;
  };
  SignUpValidation: {
    email: string;
    code?: string;
  };
};

type SignInParamList = {
  SignInEmail: undefined;
  SignInPassword: {
    email: string;
  };
};
```

I'm on `SignInEmail` screen inside `SignIn` stack and if user introduce an already existing email and is not verified, I want to redirect to `SignUpValidation` screen inside `SignUp` stack.

What I do is:
```ts
navigate('SignUp', {
  screen: 'SignUpValidation',
  params: { email },
});
```

This works, but TS complains:
```
Argument of type '["SignUp", { screen: string; params: { email: string; }; }]' is not assignable to parameter of type '["SignUp"] | ["SignUp", undefined]'.
  Type '["SignUp", { screen: string; params: { email: string; }; }]' is not assignable to type '["SignUp", undefined]'.
    Type '{ screen: string; params: { email: string; }; }' is not assignable to type 'undefined'.ts(2345)
```

This is my navigator definition:
```ts
type SignInEmailScreenProps = {
  navigation: CompositeNavigationProp<
    StackNavigationProp<UnloggedStackParamList, 'SignIn'>,
    StackNavigationProp<SignInParamList, 'SignInEmail'>
  >;
};
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.0.9
| @react-navigation/stack        | 5.1.1
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.61.5
| expo                           | nop
| node                           | 13.3.0
| npm or yarn                    | npm 6.13.7

**Comment by wygkzqa** [comment] 2020-03-18 15:08
I have the same problem

**Comment by satya164** [comment] 2020-03-18 15:14
Duplicate of #6931

**Closed by satya164** 2020-03-18 15:14 UTC
Labels: bug, package:stack
