### ISSUE TITLE
A way to automatically focus to the last dynamically created tab. 

### ISSUE THREAD

**Issue by panda0603** [react-navigation/react-navigation#6764] opened 2020-01-09 15:29 UTC
**Current Behavior**

Using react navigation v5, I am currently using dynamic bottom tab navigator, to add and remove tabs on a button press. Tab navigator and stack navigator is nested as follows: 

```

function RootStack({id}) {
  return (
    <Stack.Navigator headerMode="none">
      <Stack.Screen name={`Fav-${id}`}>
        {props => <Favourites {...props} id={id} />}
      </Stack.Screen>
      ...
    </Stack.Navigator>
  );
}

<Tab.Navigator tabBar={() => null}>
        {tabArray.map(data => {
          return (
            <Tab.Screen name={data.id} key={data.id}>
              {props => <RootStack {...props} id={data.id} />}
            </Tab.Screen>
          );
        })}
</Tab.Navigator>
```

upon pushing an item in tabArray, a tab is successfully dynamically created. However, the focus automatically goes to the first item in the array every time I push a new item. 

**What I would like to do is to automatically focus to the last tab added to the array.** 

I have tried following: 

```
      tabArray.push({       // on button click to create new tab
        id: UID,
      });
    this.props.navigation.navigate(UID); // after pushing, navigate to the created item. 
```
However, above doesn't work as it says it cannot handle navigate function. I guess navigation.navigate is executed too fast before new tab is rendered. 

Any way to automatically focus to the last pushed tab? 

Thanks

**Expected Behavior**

automatically focus to the last tab added to the array.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Both
| @react-navigation/native      | 5.0.0-alpha.24
| @react-navigation/bottom-tabs | 5.0.0-alpha.34
| react-native-screens          |2.0.0-alpha.22
| react-native                  |0.61.5
| expo                          |
| node                          | 10.16
| npm or yarn                   | npm

**Comment by satya164** [comment] 2020-05-06 15:10
Duplicate of #7611

**Closed by satya164** 2020-05-06 15:10 UTC
Labels: enhancement
