### ISSUE TITLE
InteractionManager.runAfterInteractions triggers only first time with @react-navigation/drawer@6.3.1

### ISSUE THREAD

**Issue by tomasmozeris** [react-navigation/react-navigation#10337] opened 2022-02-09 07:42 UTC
### Current behavior

InteractionManager.runAfterInteractions triggers only first time you visit the screen

### Expected behavior

InteractionManager.runAfterInteractions triggers each time you visit the screen

### Reproduction

https://snack.expo.dev/gUhhNNxT3

- Press Navigate
- Accept alert
- Go back
- Press Navigate
- Alert is not triggered anymore from useEffect InteractionManager.runAfterInteractions

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

https://snack.expo.dev/gUhhNNxT3

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| @react-navigation/bottom-tabs          | 6.2.0
| @react-navigation/drawer               | 6.3.1
| @react-navigation/material-top-tabs    | 6.1.1
| @react-navigation/stack                | 6.1.1
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.2.0
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.6
| react-native                           | 0.67.2
| expo                                   | 43.0.0

**Comment by sajudis** [comment] 2022-02-10 11:48
We are also having this issue with @react-navigation/drawer@6.3.1

**Comment by deenMuhammad** [comment] 2022-02-17 13:23
@tomasmozeris  i think this issue is caused by InteractionManager and here is how i resolved the issue: 

```js
import { InteractionManager } from "react-native";
export default {
  ...InteractionManager,
  runAfterInteractions: f => {
    // ensure f get called, timeout at 500ms
    let called = false;
    const timeout = setTimeout(() => {
      called = true;
      f();
    }, 500);
    InteractionManager.runAfterInteractions(() => {
      if (called) return;
      clearTimeout(timeout);
      f();
    });
  },
};```
Originally @gre gave workaround here https://github.com/facebook/react-native/issues/8624

**Comment by emanuelboros** [comment] 2022-02-21 15:43
After a bit of version checking, I found out that this commit is the culprit https://github.com/react-navigation/react-navigation/commit/ba868fcc87035958dd3250e81691f1f3098be033.
From version 6.3.0 to 6.3.1. While 6.3.0 works fine the bugfix release does not. 
And I'm not sure why since I checked in the project for reanimated 2, which we do have 2.2.4.

**Comment by SergioAN007** [comment] 2022-03-26 00:03
"@react-navigation/drawer": "^6.3.2",
        "@react-navigation/elements": "^1.3.1",
        "@react-navigation/native": "^6.0.8",
        "@react-navigation/native-stack": "^6.5.2",

Drawer v. 6.3.2 problem not fixed(

**Closed** 2022-03-26 23:16 UTC
Labels: bug, package:drawer, platform:android, platform:ios, repro provided

**Comment by marlti7** [comment] 2024-01-08 07:15
> @tomasmozeris i think this issue is caused by InteractionManager and here is how i resolved the issue:
> 
> ```js
> import { InteractionManager } from "react-native";
> export default {
>   ...InteractionManager,
>   runAfterInteractions: f => {
>     // ensure f get called, timeout at 500ms
>     let called = false;
>     const timeout = setTimeout(() => {
>       called = true;
>       f();
>     }, 500);
>     InteractionManager.runAfterInteractions(() => {
>       if (called) return;
>       clearTimeout(timeout);
>       f();
>     });
>   },
> };
> ```
> 
> Originally @gre gave workaround here [facebook/react-native#8624](https://github.com/facebook/react-native/issues/8624)

write where?
