### ISSUE TITLE
tabBarBadgeStyle prop doesn't work

### ISSUE THREAD

**Issue by tannerschmutte** [react-navigation/react-navigation#11812] opened 2024-02-06 15:47 UTC
### Current behavior

the tabBarBadge remains ugly red no matter what I do.

### Expected behavior

allow the tabBarBadge to be styled

### Reproduction

https://snack.expo.dev/@inpubliq/55a5c4?platform=ios

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

{
     "dependencies": {
     "@expo/vector-icons": "^13.0.0",
     "@react-navigation/material-bottom-tabs": "^6.2.12",
     "react-native-paper": "^5.1.4",
     "react-native-safe-area-context": "4.6.3",
     "@react-navigation/native": "^6.1.9"
     }
}

**Comment by satya164** [comment] 2024-02-06 18:08
Duplicate of #11809

**Closed by satya164** 2024-02-06 18:08 UTC
Labels: bug, platform:android, platform:ios, repro provided
