### ISSUE TITLE
tabBarVisible not work if use  tabBar={(props) => <MyTabBar {...props} />}

### ISSUE THREAD

**Issue by ajiehatajie** [react-navigation/react-navigation#8363] opened 2020-06-01 05:26 UTC
**How to reproduce**
tabBarVisible not working if use tabBar 
if not using tabBar tabBarVisible  is work 

` <Tab.Navigator
        tabBar={(props) => <MyTabBar {...props} />}`

in my other project with version
`@react-navigation/material-bottom-tabs": "^5.2.4",
    "@react-navigation/material-top-tabs": "^5.2.4",
    "@react-navigation/native": "^5.3.2",
    "@react-navigation/stack": "^5.3.6",`

  tabBar={(props) => <MyTabBar {...props} />} tabBarVisible  is work 
**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      |^5.5.0
| @react-navigation/bottom-tabs |^5.5.1
| react-native-screens          |^2.8.0
| react-native                  |"0.62.2
| node                          | v12.16.3 
| npm or yarn                   | yarn

**Comment by asherccohen** [comment] 2020-06-05 18:31
Hi, I can confirm that this is still happening with:

- @react-navigation/stack (found: 5.3.6, latest: 5.4.1)
- @react-navigation/bottom-tabs (found: 5.2.9, latest: 5.5.1)

I am not using material.

**Comment by satya164** [comment] 2020-06-05 18:37
Duplicate of #8172

**Closed by satya164** 2020-06-05 18:37 UTC
Labels: bug, package:bottom-tabs

**Comment by satya164** [comment] 2020-06-05 18:40
Add this in your tab bar:

```js
function MyTabBar({ state, descriptors, navigation }) {
  const focusedOptions = descriptors[state.routes[state.index].key].options;

  if (focusedOptions.tabBarVisible === false) {
    return null;
  }

  // rest
}
```

**Comment by ajiehatajie** [comment] 2020-06-06 02:20
> ```js
>   if (focusedOptions.tabBarVisible === false) {
>     return null;
>   }
> ```

thanks

**Comment by asherccohen** [comment] 2020-06-08 10:20
Thanks, this worked.

**Comment by prescindivel** [comment] 2020-06-09 15:31
thanks!

**Comment by Maskedman99** [comment] 2020-06-14 15:20
@satya164 I'm using materialTopTabNavigator. I don't want to show the top bar at all, users can navigate only by swiping left and right. How do I hide the top tab bar.
I saw https://reactnavigation.org/docs/hiding-tabbar-in-screens/ but this is about hiding tab bar for specific screens that are not directly displayed from topTabNavigator. Also saw https://github.com/react-navigation/react-navigation/issues/8143 but it was closed saying refer to docs.

This is my code
```
const Tab = createMaterialTopTabNavigator();

const Home = () => {
  return (
    <Tab.Navigator screenOptions={{tabBarVisible: false}}>
      <Tab.Screen component={Global} name="Global" />
      <Tab.Screen component={GlobalHistory} name="Global History" />
    </Tab.Navigator>
  );
};
```
**Expected behaviour:** Do not Show tab bar in ``Global`` and ``GlobalHistory``

**Comment by Maskedman99** [comment] 2020-06-18 09:25
This removes the tab and shows only indicator
```
    <Tab.Navigator
      tabBarComponent={() => null}
      tabBarOptions={{
        tabStyle: {height: 0},
        style: {backgroundColor: 'transparent'}
      }}>
      <Tab.Screen component={A} name="A" />
      <Tab.Screen component={B} name="B" />
    </Tab.Navigator>
```  
This removes the tab bar completely including the indicator
```
    <Tab.Navigator
      tabBarComponent={() => null}
      tabBarOptions={{
        style: {height: 0}
      }}>
      <Tab.Screen component={A} name="A" />
      <Tab.Screen component={B} name="B" />
    </Tab.Navigator>
```

**Comment by NxsHbb** [comment] 2022-02-16 05:48
> Add this in your tab bar:
> 
> ```js
> function MyTabBar({ state, descriptors, navigation }) {
>   const focusedOptions = descriptors[state.routes[state.index].key].options;
> 
>   if (focusedOptions.tabBarVisible === false) {
>     return null;
>   }
> 
>   // rest
> }
> ```

This worked like charm. Thanks man. God bless you.

**Comment by LucasHimelfarb** [comment] 2022-03-28 14:35
> Add this in your tab bar:
> 
> ```js
> function MyTabBar({ state, descriptors, navigation }) {
>   const focusedOptions = descriptors[state.routes[state.index].key].options;
> 
>   if (focusedOptions.tabBarVisible === false) {
>     return null;
>   }
> 
>   // rest
> }
> ```

what is "rest"? Please, complete the code. How to return Tabs components in your function?

**Comment by gyl89** [comment] 2023-09-19 13:06
Indeed, solution above works only for custom tab bar
