### ISSUE TITLE
navigate is not working on TouchableOpacity

### ISSUE THREAD

**Issue by Fazalcs13** [react-navigation/react-navigation#3219] opened 2018-01-04 10:52 UTC
I am facing an issue while developing an app on react-native that the navigate is not working and nothing happens. it only shows login success

Here is my code

        <TouchableOpacity
          style={styles.buttonlogin}
          activeOpacity = { .5 }
          onPress={ this.ButtonClickCheckFunction }
          >

          <Text style={styles.TextStyle}> SUBMIT </Text>

        </TouchableOpacity>

    ButtonClickCheckFunction = () =>{
       const { navigate } = this.props.navigation;
       const { UserEmail }  = this.state ;
       const { UserPassword }  = this.state ;

    const data = {email:UserEmail, password:UserPassword};
    //Alert.alert(data.password);
    const res = '';
    api.getLoginData(data.email, data.password)
      .then((jsonresponse) => {
          this.setState({
            responseArray: jsonresponse
          });
          console.log("server", jsonresponse);
          if(this.state.responseArray.length > 0){
            Alert.alert("Login Success");
            navigate('Home');
          }else{
            Alert.alert("Login failed");
          }
      });
    }

Here is my App.js

    import React, { Component } from 'react';
    import { StackNavigator } from 'react-navigation';
    import { responsiveHeight, responsiveWidth, responsiveFontSize } from 'react-native-responsive-
    dimensions';
    import {
    Platform,
    StyleSheet,
    Text,
    TouchableOpacity,
    Button,
    View,
    Alert,
    Image,
    TextInput
    } from 'react-native';

    import Login from './Activities/Login';
    import Home from './Activities/Home';

     const NavigationApp = StackNavigator({
     Logins: { screen: Login },
     Homes: { screen: Home },
     },{
      navigationOptions: {
       header: false,
     }
     });

     export default class App extends Component {

    render() {
     return <NavigationApp />;
    }
    }

     const styles = StyleSheet.create({
     container: {
   
     }
  
    });

**Comment by kelset** [comment] 2018-01-04 11:14
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-04 11:14 UTC
