### ISSUE TITLE
TabNavigator adding padding top to to the header

### ISSUE THREAD

**Issue by LastxTemplar** [react-navigation/react-navigation#3597] opened 2018-02-24 13:58 UTC
### Current Behavior

I upgraded to `1.0.0-beta.27` and I see a padding on the header that shouldn't be there.
Here is a [Screenshot](https://i.imgur.com/FAlnBbl.png)

### Expected Behavior

I should not be getting that extra padding. I was previously adding some padding to account for the translucent bar but I did remove that, this is how it looks at the moment:
```
static navigationOptions = ({ navigation }) => ({
        title: 'Dashboard',
        headerStyle: {
            backgroundColor: '#0a5642'
        },
        headerTitleStyle: {
            color: '#fff',
            alignSelf: 'center'
        },
        headerLeft: <View />,
        headerRight: <Icon
            raised
            containerStyle={{ backgroundColor: '#fff' }}
            name='user-circle-o'
            type='font-awesome'
            color='#0a5642'
            size={18}
            underlayColor='#fff'
            onPress={() => {
                navigation.navigate('user_profile');
            }}
        />
    });
```

### Your Environment
| software         | version
| ---------------- | -------
| expo/vector-icons | ^6.1.0
| axios     | ^0.17.0
| expo | ^25.0.0",
| moment | ^2.19.1
| react      | 16.2.0
| react-native | https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz
| react-native-animatable | ^1.2.4
| react-native-collapsible | ^0.9.0
| react-native-elements | ^0.19.0
| react-native-modal | ^4.1.1
| react-native-swiper | ^1.5.13
| react-navigation | ^1.1.2
| react-navigation-redux-helpers | ^1.0.1
| react-redux | ^5.0.6
| redux | ^3.7.2
| redux-thunk | ^2.2.0

**Comment by matthamil** [comment] 2018-02-24 19:25
Hi! Can you provide a reproducible example with [Snack](snack.expo.io)?

**Comment by LastxTemplar** [comment] 2018-02-24 19:54
I've updated my react-navigation version to the latest, I edited my question to show that.

And here is a link to the Snack:
[https://snack.expo.io/HyuMMHy_M](https://snack.expo.io/HyuMMHy_M)

**Comment by brentvatne** [comment] 2018-02-24 20:04
screenshot from the snack:

<img width="409" alt="screen shot 2018-02-24 at 12 01 37 pm" src="https://user-images.githubusercontent.com/90494/36634516-8090ab86-195a-11e8-9be2-871724debcb0.png">

this is not ideal but it is actually expected given the current implementation. but also why do you have a tab bar above a header?

if you switch to a bottom tab bar then this works as expected: https://snack.expo.io/r1604HyOM

<img width="400" alt="screen shot 2018-02-24 at 12 02 43 pm" src="https://user-images.githubusercontent.com/90494/36634533-a27afc42-195a-11e8-9a76-27bb72318850.png">

in your case, i think you updated from an old version of react-navigation since we added some automatic padding. you should read the release notes when you update and watch for breaking changes. see the related release notes here: https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.26

i'm going to close this issue because the original question is solved with the link above, and we're already tracking the need to improve layout situation so even super weird layouts like header below a tabbartop will work easily (https://github.com/react-navigation/rfcs/issues/13)

**Closed by brentvatne** 2018-02-24 20:04 UTC
