### ISSUE TITLE
There is no route defined for key navigation.dispatch(Navigation Action)

### ISSUE THREAD

**Issue by GaneshSaiKumar** [react-navigation/react-navigation#5706] opened 2019-03-19 11:29 UTC
My navigation stack is:
```

App (BottomTabnav)
|-HomeTab (Stack navigator)
|   |-itemList
|       |-itemDetail
|-MyAccountTab (Stack navigator)
|   |-Profile
|   |-settings
```
usecase: from item detail page user navigates to profile page and logs out. And comes back to item detail page through tab navigation and can see the item detail page.
Note: item detail page should be available only for logged in users.

Have tried to reset navigation stack from profile page on logout as
```
let resetAction = StackActions.reset({
    index: 0,
    actions: [
      NavigationActions.navigate({ routeName: 'HomeTab' }),
    ],
    key: null,
  })
  navigation.dispatch(resetAction)
```
but the following error pops up
`There is no route defined for key HomeTab`

@brentvatne @ericvicenti

**Comment by eriveltonelias** [comment] 2019-03-19 12:15
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by kesha-antonov** [comment] 2019-03-27 16:20
Same after upgrade RN from ```3.3.2``` to ```3.5.1```

**Comment by brentvatne** [comment] 2019-03-27 23:59
this is the only thing that could be related, as far as i can tell: https://github.com/react-navigation/react-navigation-core/commit/59238160d86284a3353d53af10688fcf3f36004f - all it does is make `key` default to `null` in reset, which you're already doing in the original example you shared @GaneshSaiKumar. someone please share a reproducible example

**Comment by stewardm** [comment] 2019-03-28 02:21
Who the hell this is

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 27, 2019 at 7:00 PM, Brent Vatne<notifications@github.com> wrote:   
this is the only thing that could be related, as far as i can tell: react-navigation/react-navigation-core@5923816 - all it does is make key default to null in reset, which you're already doing in the original example you shared @GaneshSaiKumar. someone please share a reproducible example

**Comment by ericvicenti** [comment] 2019-03-28 02:51
Hi stewardm!

Not sure how this message got sent to you, but this is a react navigation
issue (thats who the hell this is!)

Thanks to the magic of github, your email was transformed into a comment:
https://github.com/react-navigation/react-navigation/issues/5706#issuecomment-477418995

**Comment by aqmebrak** [comment] 2019-04-05 14:27
Not sure if this is the solution for you but I had a similar issue after upgradin from `3.2.3` to `3.6.1` that is resolved by setting the `key` parameter of the `reset()` function to the parent's key. As I don't have the same navigation behavior I can't tell you in your case which parent you should set `key` parameter to.

**Comment by chrisnojima** [comment] 2019-04-11 18:38
This happened to me just now. If you pass `key: undefined` to the reset action then it goes back to the old behavior (for me at least)

**Comment by hzburki** [comment] 2019-04-23 15:37
@chrisnojima worked for me too ... any explanation **why** though ???

**Comment by kesha-antonov** [comment] 2019-04-24 11:42
@chrisnojima solution worked for me! Thanks

**Comment by douglasfanucchi** [comment] 2019-04-25 23:04
Here It's a reprodution https://snack.expo.io/rJDeah1iN

**Comment by douglasfanucchi** [comment] 2019-04-25 23:08
Here It is a reproduction https://snack.expo.io/rJS0ph1oE

**Comment by giacomocerquone** [comment] 2019-05-17 21:05
My god... same solution, different scenario.

My nav is more like:

- switch
  - stack
    - tab
      - stack (without undefined couldn't perform a reset between screens of this stack)
      ...
    ...
  ...
...

**Comment by sibelius** [comment] 2019-06-03 19:21
this is breaking for us

we are using a drawer like this:

```jsx
const InnerAppRouter = createAppContainer(createStackNavigator(....))

const AppRouter = createAppContainer(createStackNavigator(
  {
    InnerAppRouter: {
      screen: createDrawerNavigator(
        {
          MainApp: {
            screen: InnerAppRouter,
          },
        },
        {
          contentComponent: props => <AppDrawer {...props} mainAppStack={InnerAppRouter} />,
        },
      ),
    },
  },
  {
    headerMode: 'none',
  },
));
```

this worked before:

```jsx
const resetAction = StackActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName, params })],
    });
    navigation.dispatch(resetAction);
```

now it is breaking

**Comment by sibelius** [comment] 2019-06-03 19:26
```jsx
const resetAction = StackActions.reset({
      index: 0,
      key: undefined,
      actions: [NavigationActions.navigate({ routeName, params })],
    });
    navigation.dispatch(resetAction);
```

```
      key: undefined,
```

make it work again

**Comment by genuinezack** [comment] 2019-07-16 20:38
The issue is related to the default value change that @brentvatne pointed out - where the `StackActions.reset` had its `key` value given an explicit default of `null`. This change (from the previous default of `undefined`) caused this issue in the following way:

1. Looking in the code for `StackRouter.js` - it appears that it sometimes uses `action.key == null` and sometimes uses `action.key === null` checks to determine whether or not the reset action is a "reset to root" action or not.
2. The `isResetToRootStack` check in [this line](https://github.com/react-navigation/core/blob/94c6ffa4e477e43533ed388e770e5144179cc83b/src/routers/StackRouter.js#L20) is one of the functions that uses `!==` rather than the looser `!=`.
3. Thus, by making the `key` value explicitly `null`, the default was changed for the `StackActions.reset` action. It now resets all the way to root and then perform `actions` from there.
4. Before this change, `isResetToRootStack` would return `false`, which in turn would cause us to get caught in [this bit of logic](https://github.com/react-navigation/core/blob/94c6ffa4e477e43533ed388e770e5144179cc83b/src/routers/StackRouter.js#L216) of the `getStateForAction` function, which defaults to having the current active child router handle the action.

I don't know this code well enough to speak to what the "intended" behavior should be, but I'm reasonably sure that's what caused the unexpected change.

**Comment by Dror-Bar** [comment] 2019-09-05 14:10
@chrisnojima Thank you for the solution to this weird, and annoying new bug.

**Comment by sridharAJ** [comment] 2019-09-20 10:18
@genuinezack @chrisnojima @brentvatne Can we use the `key:undefined ` solution in prod. I am encountering this issue after upgrading to react-navigationv3 from v2.

**Comment by hushicai** [comment] 2019-10-21 09:14
Same issue from v2 to v3.

**Comment by the-mace** [comment] 2019-12-11 03:05
" key: undefined" approach did not work for me

**Comment by chrisheninger** [comment] 2020-01-03 16:25
`key: undefined` fixed my issue of trying to reset a child stack navigator followed by navigating to a different screen inside that navigator that hadn't been part of the stack history.

Based on the documentation here: https://reactnavigation.org/docs/en/stack-actions.html#reset
```
key - string or null - optional - If set, the navigator with the given key will reset. If null, the root navigator will reset.
```

I was unable to use a key string (but there's a good chance I was just doing it incorrectly?)– but passing undefined resulted in the behavior I was looking for.

---

Does passing in a key of undefined result in the current navigator being reset? If so– this change to the documentation would've helped me:

```
key - string or undefined or null - optional (defaults to null) - If set, the navigator with the given key will reset. If undefined, the current navigator will reset. If null, the root navigator will reset. 
```

**Comment by Elias-Graf** [comment] 2020-01-14 07:41
`key: null` does not work for me either. Note that I'm trying to reset from inside my root component, and it complains that it can only be one of <routes> inside of a nested navigator....

**Comment by satya164** [comment] 2020-03-18 14:34
Closing since solution is posted in https://github.com/react-navigation/react-navigation/issues/5706#issuecomment-482246719

**Closed by satya164** 2020-03-18 14:34 UTC
Labels: needs repro, version-4

**Comment by Elias-Graf** [comment] 2020-03-18 14:57
@satya164 Did you actually test this? Because when I posted in this thread the solution did not work.

**Comment by satya164** [comment] 2020-03-18 14:58
@Elias-Graf you're using `key: null`, the solution posted is `key: undefined`

**Comment by Elias-Graf** [comment] 2020-03-18 14:59
@satya164 I think I tried both.. but if someone has the same issue, they should report it as I have moved on and cannot test it anymore, sorry.

**Comment by Dror-Bar** [comment] 2020-03-18 16:50
`key: undefined` worked for me.

react-native: 0.59.8
react-navigation: 3.9.1
