### ISSUE TITLE
Nested navigator - get active route name

### ISSUE THREAD

**Issue by jack828** [react-navigation/react-navigation#9113] opened 2020-11-30 20:28 UTC
**Current Behavior**
I have a nested navigator hierarchy (that i probably shouldn't use, but i do!)
e.g. in a stack, i have a tab, in that i have a drawer

I used to use this function (from firebase analytics docs):
```js
const getActiveRoute = navigationState => {
  if (!navigationState) {
    return { name: 'MenuSelect' }
  }
  const { index, routes } = navigationState
  const route = routes[index]
  // dive into nested navigators
  if (route.state) {
    return getActiveRoute(route.state)
  }
  return route
}

export default getActiveRoute
```

However now it constantly barrages me with warnings about using `route.state`.

I've updated my screen handler code to use the new version from [the docs](https://reactnavigation.org/docs/screen-tracking/) - but I use this in my navbar and also my drawer to show active states on drawer items.

I'd like to avoid having to pass the active route as a prop to all these components, as I'm not entirely sure if that would trigger re-renders for the entire application.

**Expected Behaviour**

A component-independent way of getting active route name from nested navigation structures - a hook would be lovely. 
`getFocusedRouteNameFromRoute` does not work and will return the navigator name from the top.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | either
| @react-navigation/native       | all latest as of 30/11/20
| react-native                   | 0.61
| expo                           | not used
| node                           | ~10
| npm or yarn                    | yarn

EDIT: versions
```
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/core": "^5.14.4",
    "@react-navigation/drawer": "^5.11.4",
    "@react-navigation/material-bottom-tabs": "^5.3.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
```

**Comment by jack828** [comment] 2020-11-30 20:30
Mis-copied version numbers from my project, updated

**Comment by delanebob** [comment] 2021-01-21 12:35
I've recently upgraded `@react-navigation` which added this warning to the `@react-navigation/core` library. Our application uses a complicated multilayer navigation with `Stack -> Tabs -> Stack(Modal mode) -> Stack`. This is due to requirements of multiple user types and UX requirements that we have the tab bar at the root page for all the stack sections, but not for the children of the stacks until we go back to the root. This is why I don't believe [this example](https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state) will work for our situation.

You can see a sample below of how we call `NavigationService.getActiveRouteName(route)` to return the lowest active child in the route. In this case the child we are looking for is also called 'Calendar' 
```jsx
<Tab.Screen
  name="Calendar"
  component={ CalendarModalWrapper }
  options={ ({ route }) => ({
    tabBarVisible: NavigationService.getActiveRouteName(route) === 'Calendar',
  }) }
/>
```

Within that method we recursively go through that route and find the lowest active route and returning the name once we hit the end. The solution still works perfect, but we can't work with all the warnings.
```js
const getActiveRouteName = (route) => {
  if (route.state) {
    return getActiveRouteName(route.state.routes[route.state.index]);
  }

  return route.name;
};
```

We tried also using `getFocusedRouteNameFromRoute` but it as @jack828 mentioned, it only seems to return the route name for that routers scope and not the child's name when I would go to that page. Another thing I noticed with our setup when using `getFocusedRouteNameFromRoute` was that if I went to a different tab and back to the calendar tab, both would return their route names once they had been focused at least once.

Would it be possibly to either remove the warning, or at least provide us with a similar solution to what we need that is internalised to react navigation?

**Comment by satya164** [comment] 2021-01-21 14:46
It gives warnings because it's impossible to do safely. Since React has one-way data flow, a parent cannot access the state of a child in a safe way. The only way is to have a callback which updates state in parent which you can implement if you really need it.

https://github.com/react-navigation/react-navigation/issues/8981#issuecomment-731233042

I'm closing this since there's nothing we can do about it as it against the fundamental design of React.

**Closed by satya164** 2021-01-21 14:46 UTC
Labels: bug

**Comment by satya164** [comment] 2021-01-21 15:27
> can you explain to me why reading `route.state` in a callback is against React's fundamentals? We can get the `route` object when passing a callback function to the options prop. I assume that the `route.state` within this object is some sort of snapshot.

Reading it isn't a problem in itself. It is a kind of snapshot. The problem is that this snapshot may not be up-to-date as it only updates when a navigation happens, not on first render. So you may be reading outdated and incorrect value which will give you unexpected behavior.

> which will internally read this property

The difference is that internally React Navigation also looks at a few other things to be able to give a correct value since `route.state` may not exist. And it even needs you to provide a default value since it will return `undefined` if there's no data. In future, we could add more workarounds, but it's not reasonable for consumers to keep all of these things in mind and write all of this logic by hand. Also these workarounds can only be done for the immediate child navigators and not for nested children, which makes it impossible to expose an API which works reliably.

**Comment by MaxwellDG** [comment] 2022-11-20 17:51
React Navigation v6 solution:

A nested route object can be discovered through parent Screen listeners. It's given in a callback argument, and can be passed to getFocusedRouteNameFromRoute to get the route name. In the example shown below, I chose to utilize it during the event 'state' (whenever state changes in the nested stack), but you can use it elsewhere if you want.

`
<Screen 
  listeners={({ route }) => ({
    state: () => {
      const subRoute = getFocusedRouteNameFromRoute(route)
      // Your logic here //
    }
  })}
/>
`
