### ISSUE TITLE
Everytime Drawer Flickering when app startup

### ISSUE THREAD

**Issue by Vicky-SilverSky** [react-navigation/react-navigation#8755] opened 2020-08-21 14:43 UTC
When i launch app everytime react navigation drawer opens and closes automatically.

i have listed the versions i have used for accomplish task:

"@react-navigation/drawer": "^5.9.0",
"@react-navigation/native": "^5.7.3",
"@react-navigation/stack": "^5.9.0",

**Comment by taduyde** [comment] 2020-08-24 10:15
the same issue, any update for this

**Comment by Vicky-SilverSky** [comment] 2020-08-25 06:05
> See I have used stack nav inside a drawer and never saw that issue.
> 
> I went through the example app that is in the repository and everything is perfect. I will recommend the same for you.
> 
> You are doing something wrong from your end can you share a snack demo so that I can help you.

i am using the same example available in documentation also i am attaching the code that i used of simple example

import * as React from 'react';
import { Button, View } from 'react-native';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { NavigationContainer } from '@react-navigation/native';

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button
        onPress={() => navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    </View>
  );
}

function NotificationsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button onPress={() => navigation.goBack()} title="Go back home" />
    </View>
  );
}

const Drawer = createDrawerNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Notifications" component={NotificationsScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
}

**Comment by lukhol** [comment] 2020-09-02 15:11
same issue for me

**Comment by rousan** [comment] 2020-09-06 10:23
I am also facing the same issue, any update?
Video: https://youtu.be/jbXsZCy23-M

**Comment by PedroBern** [comment] 2020-09-17 01:27
same here

**Comment by vishva-shukla** [comment] 2020-09-18 11:56
Facing same issue in Android

**Comment by satya164** [comment] 2020-10-23 11:01
Duplicate of #8755

**Closed by satya164** 2020-10-23 11:01 UTC

**Comment by notjulian** [comment] 2020-10-23 12:03
> Duplicate of #8755

sorry, it is a duplicate of the same id?

**Comment by developer8530** [comment] 2023-03-23 10:20
give fix width to drawerStyle solve this issue for me like
drawerStyle: { width: Screen.Width - 100 },

**Comment by Fungusjuice** [comment] 2024-08-12 19:21
still a problem
