### ISSUE TITLE
Avoid remounting of screen when navigating back

### ISSUE THREAD

**Issue by shekharskamble** [react-navigation/react-navigation#3698] opened 2018-03-09 15:31 UTC
### Current Behavior

I have the following main TabNavigator 

    export const SignedIn = TabNavigator ({
        Home: screen: HomeNavigation, 
        FeedBack: screen: FeedBackNavigation, 
        Search: screen: SearchNavigation, 
        Me: screen: ProfileNavigation,  
    });

and inside Home TabNavigator I have following stack navigator
 
    const HomeNavigation = StackNavigator({
    
        Home: screen: Home,
        UserProfile: screen: UserProfile,
       }, 
       { 
           headerMode: 'screen',
           mode: 'modal', 
        } 
    );

whenever I am navigating back from user profile to home screen, home screen get re-mounted again

### Expected Behavior

Home screen should not be remounted.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.26
| react-native     | 0.49.3
| node             | 9.5.0
| npm or yarn      | yarn 1.3.2

**Comment by rbadr** [comment] 2018-03-09 15:43
Duplicate of #3592 and #3623

**Comment by brentvatne** [comment] 2018-03-09 19:01
indeed this is a duplicate of #3592, I am currently refactoring Transitioner and will have a look at

**Closed by brentvatne** 2018-03-09 19:01 UTC
