### ISSUE TITLE
Blank Page in Release mode

### ISSUE THREAD

**Issue by nairicode** [react-navigation/react-navigation#3321] opened 2018-01-21 16:54 UTC
Hi, I have created app, it's works fine in dev mode, but when I making release apk I see Blank Page.

**Comment by kelset** [comment] 2018-01-22 09:34
Closing because you haven't followed the issue template; please open a new one that follows the template.
Without that, it's nearly impossible to understand & investigate the issue. I suggest you also try (in the new issue) to answer/explain in a way that fits these questions:

1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?

**Closed by kelset** 2018-01-22 09:34 UTC

**Comment by nairicode** [comment] 2018-01-22 09:43
now works but I don't know why, I have no changes.

**Comment by alfonsodev** [comment] 2018-04-03 16:10
I have the same issue, blank page when the application starts 
it happens on iOS + Release mode.
I'm running release mode with  
```
react-native run-ios --configuration Release
```
in the logs I get 
```
[7369] <Error>: assertion failed: 16G1114 15C107: libxpc.dylib + 72226 [EE650BC3-0539-32F0-9205-ECF6755E856F]: 0x7d
```
versions 
```
"react-navigation": "^1.5.8",
"react-native": "0.49.3",
"react-navigation-redux-helpers": "^1.0.3",
"react-redux": "^5.0.5",
"redux": "^3.7.2",
```

**Comment by jeremyfrancis** [comment] 2019-07-22 03:34
Same issue.
