### ISSUE TITLE
Permanent Drawer navigator not working 

### ISSUE THREAD

**Issue by AkalUstat** [react-navigation/react-navigation#7887] opened 2020-03-27 20:59 UTC
I have a drawer that contains a custom drawer component and contains a singular child screen, which is a stack navigator. For some reason , the permanent drawer isnt working, although i am using example code from the docs and I am on version `5.3.4`.

I have the iPad Pro simulators running and none of them are exhibiting the permanent behavior 
![Screen Shot 2020-03-27 at 1 47 46 PM](https://user-images.githubusercontent.com/43657841/77799286-b2946700-7031-11ea-9666-cde3041bfca5.png)

**Current Behavior**

**Expected Behavior**

- What do you expect should be happening?
There should be a permanent sidebar

**How to reproduce**
Current code I am using in my codebase: 
```js
const DrawerNav = () => {
  const dimensions = useWindowDimensions();
  return (
       <AppDrawer.Navigator drawerContent={( props ) => <CustomDrawer {...props} />}drawerType={dimensions.width > 900 ? 'permanent' : 'front'}>
            <AppDrawer.Screen name="Stack" component={ScreenStack} />
        </AppDrawer.Navigator>
  );
};

const Routes = () => (
        <NavigationContainer>
            <DrawerNav />
        </NavigationContainer>
);
```
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios
| @react-navigation/native       | 5.1.3
| @react-navigation/drawer       | 5.3.4
| react-native-reanimated        |1.7.0
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context |0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.5
| expo                           | N/A
| node                           | 10.15.3
| npm or yarn                    | npm

**Comment by AkalUstat** [comment] 2020-03-27 22:16
tried creating a snack, getting this error with the drawer package
```
Unable to resolve module 'module://fbjs/lib/invariant.js'
  Evaluating module://fbjs/lib/invariant.js
  Evaluating module://react-native-reanimated.js
  Evaluating module://@react-navigation/drawer.js
  Evaluating module://App.js.js
  Loading module://App.js
```

**Comment by PetteriHaro** [comment] 2020-04-04 17:41
Getting same exact behavior on
```
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/native": "^5.0.9",
```

**Comment by satya164** [comment] 2020-04-18 11:17
Closing since you didn't provide a repro. If you have a minimal repro, feel free to open an issue.

**Closed by satya164** 2020-04-18 11:17 UTC
Labels: bug, needs repro, package:drawer

**Comment by PetteriHaro** [comment] 2020-04-18 11:35
How is there not enough to reproduce in @AkalUstat comment? Setting the `drawerType` property to `permanent` doesn’t work. Anyone that uses this lib can try to repro this with one line.

**Comment by raajnadar** [comment] 2020-04-18 13:20
@AkalUstat add `"fbjs": "latest"` to the package.json in snack. Use version `5.0.0` for all the react navigation package it will work. Give it a try and let me know if that worked.

I used this versions for nested stack inside drawer.

```
{
  "dependencies": {
    "react-native-paper": "3.6.0",
    "@react-navigation/native": "5.0.0",
    "@react-navigation/stack": "5.0.0",
    "@react-navigation/drawer": "5.0.0",
    "@react-navigation/material-top-tabs": "5.0.0",
    "@react-navigation/material-bottom-tabs": "5.0.0",
    "@react-navigation/bottom-tabs": "5.0.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "latest",
    "@react-native-community/masked-view": "latest",
    "react-native-reanimated": "1.4.0",
    "fbjs": "latest"
  }
}
```
